### ISSUE TITLE
Missing Release for a long time

### ISSUE THREAD

**Issue by MudraMartin** [ansible-semaphore/semaphore#1003]
Hi @fiftin thank you for a good job on semaphore. Would it be possible to release the next version? Some core functionality is missing and a lot has been already implemented / merged pull requests into this repository (for an example collection support from ansible galaxy). But a lot has not been released in the current version 2.8.53. Would it be possible to release these features into built version for package manager?

**Comment by SvenC56** [comment]
If you are looking for a docker image the repo has moved: 

```
docker pull semaphoreui/semaphore:v2.8.65
```

See https://github.com/ansible-semaphore/semaphore/commit/fe8cc8cc4cdabc4f202f44468e9f28fc985e9b1e

**Comment by MudraMartin** [comment]
@SvenC56  Thank you, but we are using the package manager version of the Semaphore. We really miss support for collections and since it was successfully implemented and merged a long time ago we really miss newer version of these packages.

Good to know that docker version might be more ahead than PackageManager releases - thank you.

**Comment by MudraMartin** [comment]
@SvenC56 I tried this mentioned docker version and it is deffinitely newer than the packagemanager released version. But... in this current docker version... you cannot clone git repositories with HTTPS... because of this bug:
https://github.com/ansible-semaphore/semaphore/issues/957

**Comment by bendem** [comment]
I'm wondering what's wrong, there is a github action that's supposed to release to github, it ran, but attached artifacts to a dummy release:
https://github.com/ansible-semaphore/semaphore/runs/7119270720?check_suite_focus=true#step:10:98

**Comment by MudraMartin** [comment]
@bendem So i digged into the source code and it turns out that in goreleaser config file (.goreleaser.yml) there is in default 

```
config  release:
  # Do not auto publish release
  draft: true
```

So... maybe autorelease is turned of with the draft true...

**Comment by bendem** [comment]
Proposed to remove it, we'll see

**Comment by C0rn3j** [comment]
I needed an up to date version too so I at least packaged the git version on AUR

https://aur.archlinux.org/packages/semaphore-git

**Comment by MudraMartin** [comment]
@C0rn3j Yeah thank you. I managed to build my own DEB package. Also I added support for HTTPS GIT repositories. If anyone needed I can provide the deb package.

**Comment by fiftin** [comment]
New release available: https://github.com/ansible-semaphore/semaphore/releases/tag/v2.8.67
