### ISSUE TITLE
Adding additional pip modules to Docker container?

### ISSUE THREAD

**Issue by kwanlowe** [ansible-semaphore/semaphore#1005]
Good afternoon. 
I have just started testing with Ansible-Semaphore. Apologies in advance if this is covered elsewhere.

I am testing some existing playbooks that access Hashicorp Vault for secrets. As part of our non-Semaphore process, we install the ansible and the "hvac" modules to support Hashicorp Vault. Is there a way to install these additional local Python modules in the Docker container short of rebuilding the container? 

We receive this message if the module is not installed in the local Ansible installation:
fatal: [localhost]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'community.hashi_vault.hashi_vault'. Error was a , original message: Please pip install hvac to use the hashi_vault lookup module.. Please pip install hvac to use the hashi_vault lookup module."}

**Comment by kwanlowe** [comment]
Maybe I can rephrase this a little differently. :)
Are there any guides to rebuilding the Semaphore container so that I can inject some additional tools needed for my playbooks?  These include the hvac module, rsync, and some other utilities. I saw the docs on the Taskfile.yml but didn't make much headway. I tried using it as a task, building through deploy, etc.. but have a feeling I'm on the wrong track.

**Comment by PhotoTeeborChoka** [comment]
Hi, you don't need to rebuild the semaphore container, just build the container with the desired functionality by creating a mini `Dockerfile` on top of the base semaphore image you want to use (`FROM` directive) and add all the utilities you need specifically for your use case. Then tag the newly created image as <YOUR_NAME>:<THE_SEMAPHORE_TAG_U_USE> and you are good to use that image instead of the stock one.

**Comment by oscarenzo** [comment]
Hello,

There are a better way to avoid use two times *USER* in this case?

```
FROM semaphoreui/semaphore:v2.8.77

LABEL DistBase="Alpine 3.16.3"

USER root
RUN apk add py3-jmespath
USER semaphore
```

By default the image use the **semaphore** user, I would like to keep these configuration but need to add a new python library and by default have permission problems:

```
Step 3/3 : RUN apk add py3-jmespath
 ---> Running in e75b698ab3bd
ERROR: Unable to lock database: Permission denied
ERROR: Failed to open apk database: Permission denied
The command '/bin/sh -c apk add py3-jmespath' returned a non-zero code: 99
```

Then need to up to root to install the packages and goback to **semaphore** user.

Thank you.

**Comment by fiftin** [comment]
I use Ansible to install required pip modules.

**Comment by kwanlowe** [comment]
Thanks all. I used @PhotoTeeborChoka's recommendation and added the necessary pip modules.

My build is here in case anyone's interested:

https://github.com/kwanlowe/digitalhermit_website/tree/master/linux/semaphore

```
FROM semaphoreui/semaphore
user root
RUN /sbin/apk add py3-pip
user semaphore
RUN pip install kubernetes hvac
```

I'm still tweaking the build process and may need to package my internal modules separately versus in the semaphore container build.

**Comment by hanserasmus** [comment]
@fiftin 
> I use Ansible to install required pip modules.

Can you please elaborate on this bit? I too am using the docker container, and have the `cisco.ios` collection as a requirement in my repository, but  this needs `ansible-pylibssh` which is not installed in the docker container. I would rather not have to pull and rebuild my images every time to a local registry. Could you please explain what you mean by the above, and maybe include some steps? That would be really helpful.

**Comment by smooth-baking-powder** [comment]
> I use Ansible to install required pip modules.

Hey, how you do it in detail? 

i need to install the matrix module:  https://docs.ansible.com/ansible/9/collections/community/general/matrix_module.html

Thanks

**Comment by fiftin** [comment]
Hi @corincorvus do you use docker?

**Comment by smooth-baking-powder** [comment]
> Hi @corincorvus do you use docker?
Hey, yes i do.

**Comment by fiftin** [comment]
@corincorvus you can provide `/etc/semaphore/requirements.txt` to your container.

**Comment by smooth-baking-powder** [comment]
> @corincorvus you can provide `/etc/semaphore/requirements.txt` to your container.

Ok thanks, the first modules are installed. it wont working.. after a while i tried to solve i found this: 

The list of installed modules: 
virtualenv
matrix-client
just
requests

```
{
    "PYTHONPATH": "/home/semaphore/.local/lib/python3.11/site-packages"
}
```

why i need this variable to work with the modules?

Now i stuck on roles :/ 
Playbook: https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/installing.md

Error:
```
9:59:44 AM
Already up to date.
9:59:44 AM
installing static inventory
9:59:44 AM
collections/requirements.yml has no changes. Skip galaxy install process.
9:59:44 AM
No roles/requirements.yml file found. Skip galaxy install process.
9:59:45 AM
ERROR! the role 'galaxy/playbook_help' was not found in /tmp/semaphore/repository_3_15/roles:/tmp/semaphore/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/tmp/semaphore/repository_3_15
9:59:45 AM
9:59:45 AM
The error appears to be in '/tmp/semaphore/repository_3_15/setup.yml': line 8, column 7, but may
9:59:45 AM
be elsewhere in the file depending on the exact syntax problem.
9:59:45 AM
9:59:45 AM
The offending line appears to be:
9:59:45 AM
9:59:45 AM
    # Most of the roles below are not distributed with the playbook, but downloaded separately using `ansible-galaxy` via the `just roles` command (see `justfile`).
9:59:45 AM
    - role: galaxy/playbook_help
9:59:45 AM
      ^ here
```

some hosts not work fine, while i use docker playbook.

on 2 hosts i get this error:
```
11:55:10 AM
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'requests'
11:55:10 AM
fatal: [network]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (requests) on network's Python /usr/bin/python3. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}
```

On all other it works. on no host i installed python, except in semaphore docker container.
