### ISSUE TITLE
Key Store: Missing DELETE button

### ISSUE THREAD

**Issue by alexrjs** [ansible-semaphore/semaphore#101]
Problem:
If I want to delete a key which is no longer needed or wrong, I cannot do this, since no DELETE Button/Method is available on the Interface.
![bildschirmfoto 2016-05-21 um 08 49 03](https://cloud.githubusercontent.com/assets/10467960/15446994/29a6ad2c-1f31-11e6-8091-2f15cee422b5.png)

**Comment by matejkramny** [comment]
This is dup of #94 

It will be done :). For now, please open the db and delete it manually
