### ISSUE TITLE
Build requires tools that are dead upstream

### ISSUE THREAD

**Issue by C0rn3j** [ansible-semaphore/semaphore#1015]
Namely Packr and goverage.

Goverage was made to solve an issue in core Go, as per https://github.com/haya14busa/goverage#goverage---go-test--coverprofile-for-multiple-packages

Go has this issue fixed a long time ago. https://github.com/golang/go/commit/283558e42b88a6afa39da6ad4ae87558dc053776

Packr was also created to fix an issue with core Go, but Go has since gained the featureset needed - https://github.com/gobuffalo/packr#readme

**Comment by fiftin** [comment]
So, we should migrate from packr to https://pkg.go.dev/embed. Thank you @C0rn3j .

**Comment by johanneskastl** [comment]
Any news on this?

**Comment by C0rn3j** [comment]
packr isn't used for much it looks like, these should be all of the affected files that need to be changed:
```bash
deployment/semaphore.spec:##go install github.com/gobuffalo/packr/v2@latest

go.sum:github.com/gobuffalo/packr v1.10.4 h1:k/aQq1+9UlSxfr9+QXz1sQ8vJVFTXqrEDdKgeonlt4Y=
go.sum:github.com/gobuffalo/packr v1.10.4/go.mod h1:rYwMLC6NXbAbkKb+9j3NTKbxSswkKLlelZYccr4HYVw=

api/router.go:    "github.com/gobuffalo/packr"
api/router.go:var publicAssets2 = packr.NewBox("../web/dist")

db/sql/migration.go:// getVersionSQL takes a path to an SQL file and returns it from packr as
db/sql/SqlDb.go:  "github.com/gobuffalo/packr"
db/sql/SqlDb.go:var dbAssets = packr.NewBox("./migrations")

Taskfile.yml:      - go install github.com/gobuffalo/packr/...@v1.10.4
Taskfile.yml:    desc: Runs Packr for static assets
Taskfile.yml:      - db/db-packr.go
Taskfile.yml:      - api/api-packr.go
Taskfile.yml:      - packr
Taskfile.yml:      - golangci-lint run --skip-files "\w*(-packr.go)" --disable goconst --timeout 240s ./...

Taskfile_windows.yml:      - packr

.gitignore:*-packr.go

go.mod:   github.com/gobuffalo/packr v1.10.4
```

Looks like `..` is not supported, so that's a problem, with this as a possible solution:
https://sudarakayasindu.medium.com/go-embed-instead-of-packr-e1e0fa245091

Or restructuring the files.

I am not amazing with Go, so it'd be nice if someone else was able to tackle this.


EDIT: Failed attempt here https://github.com/ansible-semaphore/semaphore/commit/1edab49d70521f36480dadab9aed9ed507ec9f13

There's three things to resolve

1) router.go uses a parent location, this is not supported in embed. This should ideally be fixed by rearranging the file structure. Less ideally by copying files over in the Taskfile during compile then removing them again.

2) Migrate `web/dist` to embed

3) Migrate DB `migrations` to embed

**Comment by C0rn3j** [comment]
Seems fixed, thanks!

https://github.com/ansible-semaphore/semaphore/commit/67954b95aafe047856d9d2bb5fd539d17686b118

**Comment by tboerger** [comment]
Yeah that's right, I haven't seen this issue otherwiese it would be closed already :)
