### ISSUE TITLE
API does not implement GET for schedules

### ISSUE THREAD

**Issue by cf-sewe** [ansible-semaphore/semaphore#1028]
- I am automating Semaphore configuration via the API
- I want to be able, to determine the schedules for a certain task. 

Currently it is not possible to:
- either list all the schedules (`GET /projects/<id>/schedules` returns HTTP 405)
- or get the schedule id from the tasks (`GET /projects/<id>/templates/<tid>` does not return the schedule id.

Can you please confirm my analysis is correct, and there is no way to get the schedule Id of a task template via API?
If thats correct, could you consider adding this to the API?

```
TASK [Semaphore | Determine Schedules] *******************************************************************************************************************************************************
fatal: [docker]: FAILED! => changed=false
  connection: close
  content_length: '0'
  date: Tue, 13 Sep 2022 10:15:54 GMT
  elapsed: 0
  msg: 'Status code was 405 and not [200]: HTTP Error 405: Method Not Allowed'
  redirected: false
  status: 405
  url: http://172.25.0.9:3000/api/project/9/schedules
```

**Comment by fiftin** [comment]
Yes, you are right. Yes, we will implement this.

**Comment by EHEX-schildt** [comment]
works fine for me with v2.10.22 all schedule got listed with `GET /projects/<id>/schedules` (except one special case #2233)

**Comment by cf-sewe** [comment]
I guess this can be closed then. Thank you for the info!
