### ISSUE TITLE
Listing playbook hosts failed: exit status 4

### ISSUE THREAD

**Issue by jake-vukelich** [ansible-semaphore/semaphore#1034]
Red Hat Enterprise Linux release 8.6 (Ootpa) - installed with package manager (yum) using a mysql database. Semaphore user has root access to its database. 

I had an Ubuntu server setup with Ansible Semaphore but need to switch to RHEL. Everything was working fine with Ubuntu. 
Playbook runs when using Ansible CLI. Permissions look the same on both servers in the semaphore directory. Inventory and repository files/directories are being written as they should. 

I'm using HTTPS to authenticate to an Azure repo storing the playbooks. I've been testing with a basic "check for windows version - set kms license" playbook with a couple Windows Server 2019 VMs. I'm using a static inventory in Semaphore - example:

[all]
10.X.X.X

Prepare TaskRunner with template: win_license.yml
Updating Repository From https://dev.azure.com/Repository_Name
From https://dev.azure.com/Repository_Name
* branch main -> FETCH_HEAD
Already up to date.
Get current commit hash
Get current commit message
installing static inventory
No roles/requirements.yml file found. Skip galaxy install process.
Listing playbook hosts failed: exit status 4

Any suggestions on how to troubleshoot this error? Thanks.

**Comment by fiftin** [comment]
Could you try latest version of Semaphore?

**Comment by jake-vukelich** [comment]
Updating to the latest version of Semaphore resolved the issue. Thanks very much!
