### ISSUE TITLE
BoltDB instance starts task numbers at 2147483645

### ISSUE THREAD

**Issue by bverkron** [ansible-semaphore/semaphore#1048]
Just migrated to the new image [2.8.68](https://hub.docker.com/layers/semaphoreui/semaphore/v2.8.68/images/sha256-621895e3c3a67038831152583f6a728b50a29d38c845807fb0ca223d51d9ad44?context=explore) (I believe) to use BoltDB and my very first task has an ID of 2147483645 instead of 1.

Here is my old setup on the previous image with mysql (dark) vs 2.8.68 with BoltDB (light). I assume this is due to Bolt as I don't think much else changed in this release vs the last one.

![Screen Shot 2022-10-06 at 11 58 00 AM](https://user-images.githubusercontent.com/19174503/194397601-8c3f8580-6796-4885-9e55-c3db3a75152f.png)

![Screen Shot 2022-10-06 at 11 57 57 AM](https://user-images.githubusercontent.com/19174503/194397612-b099906b-e24f-493e-98c2-5804fc3ea00b.png)

**Comment by fiftin** [comment]
It is ok for BoltDB. 
I don't remember details why I choose this behaviour, but it is motivated by the sorting way in BoltDB.
