### ISSUE TITLE
Delete of User leads to problems viewing Task overview

### ISSUE THREAD

**Issue by lanbugs** [ansible-semaphore/semaphore#1055]
Hi,

i have created a testuser did some task runs and delete it afterwards. 
After deleting the user the task list is empty and hanging in loading state.

Other projects are not affected of the problem only the project were i executed some tasks.

I use the last stable version with boltdb.

Regards,

Max

**Comment by fiftin** [comment]
Fixed in [v2.8.69](https://github.com/ansible-semaphore/semaphore/releases/tag/v2.8.69).
