### ISSUE TITLE
Current docker-compose Version broken

### ISSUE THREAD

**Issue by lanbugs** [ansible-semaphore/semaphore#1064]
Hi developers,

after installation of semaphore on my RPi it loops "exec /sbin/tini: exec format error".

Platform: Ubuntu 20.04.5 LTS aarch64
Docker: Docker version 20.10.20, build 9fdeb9c
Docker-compose: Docker Compose version v2.11.2

Images:
Container               Repository              Tag                 Image Id            Size
semaphore-mysql-1       mysql                   8.0                 5e229524f286        494MB
semaphore-semaphore-1   semaphoreui/semaphore   latest              7a140afd8832        569MB

Docker-compose file is from semaphore docs, only passwords are modified.

Output from docker-compose logs -f

semaphore-semaphore-1  | exec /sbin/tini: exec format error
semaphore-semaphore-1  | exec /sbin/tini: exec format error
semaphore-semaphore-1  | exec /sbin/tini: exec format error
semaphore-semaphore-1  | exec /sbin/tini: exec format error
semaphore-semaphore-1  | exec /sbin/tini: exec format error
semaphore-semaphore-1  | exec /sbin/tini: exec format error
semaphore-semaphore-1  | exec /sbin/tini: exec format error
semaphore-semaphore-1  | exec /sbin/tini: exec format error
semaphore-semaphore-1  | exec /sbin/tini: exec format error
semaphore-semaphore-1  | exec /sbin/tini: exec format error
semaphore-semaphore-1  | exec /sbin/tini: exec format error
semaphore-semaphore-1  | exec /sbin/tini: exec format error
semaphore-semaphore-1  | exec /sbin/tini: exec format error
semaphore-semaphore-1  | exec /sbin/tini: exec format error
semaphore-semaphore-1  | exec /sbin/tini: exec format error
semaphore-semaphore-1  | exec /sbin/tini: exec format error
semaphore-semaphore-1 exited with code 1
... loop ...

Regards,

Max

**Comment by thunderstorm99** [comment]
Hi @lanbugs, this is due to the fact, that for now the semaphore docker image is x86_64 only. @fiftin linked the project that wants to bring arm cpu support to the docker image.

**Comment by fiftin** [comment]
Hi @thunderstorm99 , @lanbugs 
I working on it.

**Comment by fiftin** [comment]
@lanbugs, @thunderstorm99 

Please try v2.8.73 (latest) on ARM64 (https://hub.docker.com/r/semaphoreui/semaphore/).

![image](https://user-images.githubusercontent.com/914224/198143610-299cb3d5-ce57-4bcd-9ced-64eeb75cd8e9.png)

It works on my RPI.
