### ISSUE TITLE
No collections/requirements.yml file found.

### ISSUE THREAD

**Issue by VladoPortos** [ansible-semaphore/semaphore#1068]
This is quite confusing.

I have the folder and file in the git next to the yaml file that is called.

collections/requirements.yml 

```
---
collections:
  - name: ansible.posix
```

```
/tmp/semaphore/repository_1_1 $ ls -all
total 28
drwxr-xr-x    4 semaphor root          4096 Oct 28 16:39 .
drwxr-xr-x    1 semaphor root          4096 Oct 28 16:34 ..
drwxr-xr-x    8 semaphor root          4096 Oct 28 16:34 .git
-rw-r--r--    1 semaphor root          6240 Oct 28 15:48 README.md
-rw-r--r--    1 semaphor root           563 Oct 28 16:18 add_user.yaml
drwxr-xr-x    2 semaphor root          4096 Oct 28 16:30 collections
/tmp/semaphore/repository_1_1 $ ls collections/
requirements.yml
```

Why is semaphore not seeing it ?  Its the last thing that I need to figure out before I can use semaphore.

**Comment by VladoPortos** [comment]
Well unless I'm doing something wrong this just don't work... I tried in docker version and the latest .deb on dedicated VM... same result... collections are ignored roles are detected

**Comment by VladoPortos** [comment]
Another interesting stuff:
 Just for lolz I moved the collection folder into /playbook directory . This one is defined here: 
```
"tmp_path": "/playbook",
```

And then it finally found the file... it is looking one folder off. Although checking the code it should see it in the git folder...

```
requirementsFilePath := path.Join(t.getPlaybookDir(), "collections", "requirements.yml")
```

Maybe this change is not present in v2.8.73 ?

**Comment by VladoPortos** [comment]
Checked the release code of v2.8.73 and its there... I do not know go well enough to debug this... I tried one last thing and thats to use default path "/tmp/semaphore/" but that does not help either.... this is beyon me :-/

**Comment by fiftin** [comment]
Hi @VladoPortos 
Thank you very much, it is regression! Will be fixed ASAP.

**Comment by VladoPortos** [comment]
Looks to be working in the latest release, thanks ! Enjoy the coffee :)

**Comment by fiftin** [comment]
@VladoPortos Thank you :) Fixed in [v2.8.74](https://github.com/ansible-semaphore/semaphore/releases/tag/v2.8.74).

**Comment by bverkron** [comment]
I seem to be getting the same issue using the latest docker image (2.8.74, I see the new template UI changes)

I'm attempting to load a docker collection so I can execute to docker maintenance tasks on a host. This is my requirements file which gets pulled down by the Ansible Task as expected.

```
/tmp/semaphore/repository_2_6/collections $ cat requirements.yml 
collections:
  - name: community.docker
    source: https://galaxy.ansible.com/tmp/semaphore/repository_2_6/collections
```

But the task shows `No collections/requirements.yml file found. Skip galaxy install process.` and says it can't find the module...
```
...
3:34:57 PM
* branch master -> FETCH_HEAD
3:34:57 PM
Already up to date.
3:34:57 PM
Get current commit hash
3:34:57 PM
Get current commit message
3:34:57 PM
installing static inventory
3:34:57 PM
No collections/requirements.yml file found. Skip galaxy install process.
3:34:57 PM
No roles/requirements.yml file found. Skip galaxy install process.
3:35:00 PM
Started: 2147483564
3:35:00 PM
Run TaskRunner with template: Update Portainer
3:35:01 PM
3:35:01 PM
PLAY [Update Portainer to latest version] **************************************
3:35:01 PM
3:35:01 PM
TASK [Pull image] **************************************************************
3:35:04 PM
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'docker'
3:35:04 PM
fatal: [master_control]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python3"}, "changed": false, "msg": "Failed to import the required Python library (Docker SDK for Python: docker above 5.0.0 (Python >= 3.6) or docker before 5.0.0 (Python 2.7) or docker-py (Python 2.6)) on mastercontrol's Python /usr/bin/python3. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter, for example via `pip install docker` (Python >= 3.6) or `pip install docker==4.4.4` (Python 2.7) or `pip install docker-py` (Python 2.6). The error was: No module named 'docker'"}
3:35:04 PM
3:35:04 PM
PLAY RECAP *********************************************************************
3:35:04 PM
master_control : ok=0 changed=0 unreachable=0 failed=1 skipped=0 rescued=0 ignored=0
3:35:04 PM
3:35:04 PM
Running playbook failed: exit status 2
```

**Comment by flaudisio** [comment]
@bverkron it seems the `collections/requirements.yml` path is relative to the playbook file's directory.

So, this layout works:

```
├── collections/
│   └── requirements.yml
└── webservers.yml
```

But not this one:

```
├── collections/
│   └── requirements.yml
└── playbooks/
    └── webservers.yml
```

In this case, you need to move `collections/` to the `playbooks/` directory:

```
└── playbooks/
    ├── collections/
    │   └── requirements.yml
    └── webservers.yml
```

@fiftin first of all, thanks for such a great project! Semaphore is awesome!

I see the `roles/requirements.yml` [path logic](https://github.com/ansible-semaphore/semaphore/blob/4559b52c4ad9d401646ad4845f007ccbb72c99de/services/tasks/runner.go#L519) is different from the `collections/` [one](https://github.com/ansible-semaphore/semaphore/blob/4559b52c4ad9d401646ad4845f007ccbb72c99de/services/tasks/runner.go#L490)... is that intentional? Maybe both of them could use the `<repo-root>/{roles,collections}/requirements.yml` format to be more intuitive.
