### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by yodatak** [ansible-semaphore/semaphore#1069]
I want to be able to take the inventory from the git repository , to have a single repository with my inventory and my playbooks is it something interesting to semaphore ?

**Comment by fiftin** [comment]
Hi @yodatak 
You can do this. Create/Open inventory, select Type **File** and specify path to you inventory file.

![image](https://user-images.githubusercontent.com/914224/198816092-e5830e5f-03b3-4a5e-a57c-62c549c18391.png)
