### ISSUE TITLE
Duplicating / copying Task Template overwrites original template instead of creating new one

### ISSUE THREAD

**Issue by bverkron** [ansible-semaphore/semaphore#1074]
When I try to duplicate / copy button on an existing task template it overwrite the original template when I click [Create] instead of creating a new one with the defined values.

To reproduce:

* Open an existing Task Template and click the copy button in the top right.
![image](https://user-images.githubusercontent.com/19174503/198916594-aeaf7b93-d9df-4584-a26c-f54f73e7b108.png)

* Modify the values in the New Template dialog
* Click [Create]
* Original task template gets overwritten instead of creating a new task with those values

**Comment by dorinand** [comment]
@fiftin do you have any update regarding this? I encounter same issue. 

Running version `v2.8.81`

BTW, Thank you for awesome tool. 👍

**Comment by UNiXMIT** [comment]
It would be very useful to have this feature working. It would speed up setup and save having to start from scratch each time, especially when each task has a lot of survey variables set. Thanks

**Comment by UNiXMIT** [comment]
In '/web/src/views/project/TemplateView.vue' and 'onTemplateCopied' should it reference 'e.item-id' instead of 'e.item.id'?
I know very little about this language so I could be way off. Thanks

**Comment by morganchester** [comment]
2.8.89 still has the bug (using snap)

**Comment by UNiXMIT** [comment]
Anyone have a workaround for this? Adding the same survey variables to each task individually is becoming very tiring.

**Comment by UNiXMIT** [comment]
Are any issues being fixed or just new features added?

**Comment by UNiXMIT** [comment]
I've managed to workaround this issue by using the API. I GET the task template I want to copy. Then modify the JSON response with the changes I need to make and use it to create a new task template. Easier than starting from scratch.

**Comment by webtroter** [comment]
Hello
I can confirm I also have the problem, and like @UNiXMIT said, removing the `"id":n` from the payload correctly creates the duplicate.

One thing I find weird is that we receive a HTTP 201 when there was no creation and only a modification of the existing template/resource

**Comment by UNiXMIT** [comment]
Still broken in the latest version 2.9.37

**Comment by Pshemas** [comment]
yup, still broken and super annoying on my end - it forces me to create manually the same task in each view (with changed variables).
