### ISSUE TITLE
target unreachable

### ISSUE THREAD

**Issue by ksrdl** [ansible-semaphore/semaphore#1077]
Hello, 

i have this error when i try to launch my playbook 

![image](https://user-images.githubusercontent.com/38161967/199460842-c67e30a1-efe4-41a9-8984-a54448ff16cb.png)

i can ping the target from the semaphore container :

![image](https://user-images.githubusercontent.com/38161967/199461156-fc063ed7-98ad-4646-8763-8631f20a1001.png)

i can connect to the target with the specify ssh key 

![image](https://user-images.githubusercontent.com/38161967/199461593-f0380e6d-0cc1-495a-91ce-af5efaa51cb8.png)

someone can help me pls ? 

Kelian

**Comment by cf-sewe** [comment]
Did you configure the SSH key in Semaphore (Under Keystore -> Add Key with type `ssh`)?
If the SSH key is configured, Semaphore [uses](https://github.com/ansible-semaphore/semaphore/blob/4559b52c4ad9d401646ad4845f007ccbb72c99de/lib/GitRepository.go#L30) the SSH option `StrictHostKeyChecking=no` which ignores the host key.

**Comment by ksrdl** [comment]
Hello, i have put my ssh key in the keystore of semaphore

for the option `StrictHostKeyChecking=no` where i can put this pls ? 

thank

**Comment by cf-sewe** [comment]
As mentioned the option is automatically added if you configured it in the repository (in the Inventory refer to the configured SSH key).

**Comment by ksrdl** [comment]
ok sorry, but that doesn't work for me...

**Comment by cf-sewe** [comment]
What is your key format?
Please also login to the semaphore container and call `ssh -v root@<target>` manually, to check if there is a more detailed error explanation.

**Comment by ksrdl** [comment]
it's rsa key

**Comment by ksrdl** [comment]
ssh -v tell me nothing because the connection work fine

from the container with the specified ssh key that work fine

![image](https://user-images.githubusercontent.com/38161967/199519466-89edbbee-47d2-46cf-80aa-3e7f3f7de3f5.png)


EDIT : for information it's an docker install

**Comment by ksrdl** [comment]
when i run the playbook manually from the semaphore container with the same ssh key that's work fine 

![image](https://user-images.githubusercontent.com/38161967/199534451-d85d17ab-4495-4b59-8a00-ca955ed85b2c.png)

but from the web app always unreachable

Kelian

**Comment by ksrdl** [comment]
adding `ANSIBLE_HOST_KEY_CHECKING: "False"` in the docker compose file and that's work now from the web UI
