### ISSUE TITLE
Enhancement:  Add run button to task template overview page

### ISSUE THREAD

**Issue by nlvw** [ansible-semaphore/semaphore#1082]
When you select a task template you get a nice overview of the template with a history and buttons to delete, clone, or edit.  It would be nice to be able to also run the task from this page as well.

<img width="858" alt="image" src="https://user-images.githubusercontent.com/5723368/199804500-02a23d0c-18e4-409c-8ebf-303064fa5bf5.png">

Right now you have to go back a page and do a ton of verticle/horizontal scrolling to find the correct template and then run the correct template.

<img width="858" alt="image" src="https://user-images.githubusercontent.com/5723368/199804834-bc0fdcdc-02ff-4f78-b15d-af092dee5af6.png">

<img width="857" alt="image" src="https://user-images.githubusercontent.com/5723368/199804927-6f796974-557f-429c-aa27-7b4df8a398ad.png">

**Comment by ksrdl** [comment]
Hello,

You have to update to the latest version, we have this button in the latest 
![image](https://user-images.githubusercontent.com/38161967/199943269-eb9460ff-42dc-4498-8f52-6dbb9a74d37b.png)

**Comment by nlvw** [comment]
Nice! I guess I missed the announcement.
