### ISSUE TITLE
400 on telegram alerts

### ISSUE THREAD

**Issue by John-Limb** [ansible-semaphore/semaphore#1085]
Hello, 
I couldn't find anywhere else to post issues, nor find any similar online. 

I'm getting 400 error when sending telegram message, I've created a bot, 
Copied number:auth token and put it into the 'telegram-token' parameter on the snap, and chat/group number into the telegram chat parameter. Also enabled alerts in both UI and snap settings. 

Is there any more documentation to look at? I can't find much online
Or any log path on the server I can look into?

Thanks
John

**Comment by John-Limb** [comment]
Please close the issue, this is now working.

**Comment by ProstoNikita** [comment]
@John-Limb, what problem did you have?
