### ISSUE TITLE
Color Highlighting to Playbook Output

### ISSUE THREAD

**Issue by asmartin** [ansible-semaphore/semaphore#111]
Semaphore looks great! I am really impressed by its functionality. One thing that would be nice is to add color highlighting to the playbook output like Ansible has when run from the cli (e.g. red for error, orange for warning, green for success, blue for skipped, etc). This would make it a lot easier to review the output for problems

**Comment by matejkramny** [comment]
👍  would be great to have

In addition it could parse the output into some logical groups and present it better in the interface

**Comment by asmartin** [comment]
Having the output summarized like this would be really neat:
http://ara.readthedocs.io/en/latest/faq.html#what-does-the-web-interface-look-like

**Comment by matejkramny** [comment]
Great!

On another note, the dashboard could have something like circle's insights: https://circleci.com/blog/announcing-circleci-insights-helping-you-understand-your-builds/

**Comment by asmartin** [comment]
Yes, that's a good idea as well

**Comment by Vitexus** [comment]
The ANSIBLE_FORCE_COLOR[](https://docs.ansible.com/ansible/latest/reference_appendices/config.html#ansible-force-color) = True environment setting still not work and output is black/white :(

**Comment by fiftin** [comment]
Done in https://github.com/ansible-semaphore/semaphore/releases/tag/v2.8.66
