### ISSUE TITLE
'task release' binary reports 404

### ISSUE THREAD

**Issue by magichome** [ansible-semaphore/semaphore#1122]
### Discussed in https://github.com/ansible-semaphore/semaphore/discussions/1106

<div type='discussions-op-text'>

<sup>Originally posted by **magichome** November 29, 2022</sup>
I've forked the semaphore repo and making some customizations.  When I build the code with 'task release' and run the associated binary for my architecture, it starts normally but every URL gives 404 "not found" error.  The official release of semaphore is 3x larger than my binary so I feel like the build is not including something.  Local builds run fine, its only the release build that gives 404.  Any suggestions would be appreciated.</div>

**Comment by tjf-ARUS** [comment]
Shot myself in the foot on this one.  I changed a config file so that packr wasn't including static content. (Or something like that.) Issue should be closed.

**Comment by magichome** [comment]
This was my error.  I messed up a config file so packr wasn't including static content.  Sorry for the noise.
