### ISSUE TITLE
Specify variables during a run

### ISSUE THREAD

**Issue by asmartin** [ansible-semaphore/semaphore#114]
I often times will create a playbook that looks like this:

```

---
- hosts: '{{ hostlist }}'
  roles:
   - myrole
```

When I run it, I then pass the `hostlist` variable on the command line to denote which host(s) to run it on:

```
ansible-playbook -e "hostlist=server1:server2" myserver.yml
```

Is it possible to create a task template that sets this up, but then per run allows you to customize the value passed inside of the `-e` flag? For example, configuring it like this in the task template:

```
["-e", "hostlist=$HOSTLIST"]
```

And then in the run itself:

```
["HOSTLIST:" "server1:server2"]
```

Is this or another method for passing data per run possible? Thanks!

**Comment by matejkramny** [comment]
Hmm there isn't a way to do that currently, but there is an issue (#96) proposing to extend the functionality of tasks further.

Could propose how the UI could look like or what options should be available?

**Comment by asmartin** [comment]
Really all you would need is the `Extra CLI Arguments` input to be available from the "run" window too, then you can fill in those custom extra cli arguments per-run rather than just per-template

**Comment by gasperzupancic** [comment]
Maybe all you need is to make an option to select "inventory" that you already have when you run a playbook or pass {{hosts}} manualy in the field?
Or better option is to select inventory that you created previosly and an option to select [group] from that inventory?

our host-all list looks like

[group1]
server[1:10].local.domain

[group2]
other_server[1:3].different.domain

...

that way i can only push something to [groupN] if i want. What do you think?

**Comment by asmartin** [comment]
It would be nice to be able to push other generic variables too. For
example I have a boolean variable that I use to toggle running dependent
roles, so it would be nice to set that too from this interface for a run

**Comment by twhiston** [comment]
Task execution extra vars textarea solves this (as the json data is passed to --extra-vars) allowing the original proposal to run as intended

**Comment by florian-asche** [comment]
Is it possible, to input a "Survey Variables" into the "CLI args"?

**Comment by r3nor** [comment]
> Is it possible, to input a "Survey Variables" into the "CLI args"?

I would also like to know

**Comment by elmar-aliyev-hiq** [comment]
> Is it possible, to input a "Survey Variables" into the "CLI args"?

It appears that the "--extra-vars" CLI argument needs to be passed in JSON format. The following works if you put it in the "CLI args" text field:
```
[
  "--extra-vars",
  "{'var1':'<value>','var2':'<value>'}"
]
```

**Comment by lmrlyv** [comment]
> Is it possible, to input a "Survey Variables" into the "CLI args"?

It appears that the "--extra-vars" CLI argument needs to be passed in JSON format. The following works if you put it in the "CLI args" text field:

```
[
  "--extra-vars",
  "{'var1':'<value>','var2':'<value>'}"
]
```

**Comment by declan727** [comment]
I am not sure what the point of the inventory field in the Task Template is for if it does not pass this to the playbook. this would require you to have playbooks for every system combination and know which one to put into Semaphore or all of them.

**Comment by skarczjh** [comment]
In the CLI args field, you can add the -l ${HOSTNAME} flag. This will limit the playbook to the one host. What I would _much_ prefer is a way to use Survey Variables.

This is what works:

![image](https://github.com/user-attachments/assets/3379b8dd-a908-4b29-917c-657241de5759)

This would be more better:

![image](https://github.com/user-attachments/assets/c7887a77-bd1d-451d-8445-b12e63d35a22)

Which would then prompt the user to enter a hostname at runtime:

![image](https://github.com/user-attachments/assets/6965eb3c-e7bd-4bbf-9ef3-007ed61d8951)

**Comment by YaKen1** [comment]
> Is it possible, to input a "Survey Variables" into the "CLI args"?

Have you find a way to pass variables via cli args? because when I specify --tags and "{{ tag_name }}", semaphore handles the ""{{ tag_name }}"" as a string, and no tags are executed since there is no tag name ""{{ tag_name }}""

**Comment by jcw1571** [comment]
How do you add tags to the task template?  example:  --tags webservers

**Comment by smithj33** [comment]
> How do you add tags to the task template? example: --tags webservers

Enter -t webservers as a CLI arg.

**Comment by smithj33** [comment]
> > Is it possible, to input a "Survey Variables" into the "CLI args"?
> 
> Have you find a way to pass variables via cli args? because when I specify --tags and "{{ tag_name }}", semaphore handles the ""{{ tag_name }}"" as a string, and no tags are executed since there is no tag name ""{{ tag_name }}""

This cannot be done because it cannot be done on the command line neither. Semaphore follows typical Ansible conventions. Semaphore could break normal convention and implement something like this, but you can just as easily enter a -t CLI argument by itself and then add seperate arguments for tag names when needed.
