### ISSUE TITLE
Extra variables validation error

### ISSUE THREAD

**Issue by dmitrygribenchuk** [ansible-semaphore/semaphore#1141]
Hello. After updating to 2.8.77 have a bug with environment variables: I can't save with empty environment variables. 

![image](https://user-images.githubusercontent.com/15670247/211764461-7f48b6c2-b516-40db-b765-0040bdff8242.png)

Configuration, saved before update working and updating correctly. The problem only with a new configuration.

**Comment by nati0n** [comment]
It is annoying, the fix is to just enter {} for your environment variables.

**Comment by dmitrygribenchuk** [comment]
I'm, as user, expect, that if I did not touch the field - it should not affect the result
