### ISSUE TITLE
CRON Expression Format unclear

### ISSUE THREAD

**Issue by EHEX-schildt** [ansible-semaphore/semaphore#1143]
The semapore Web Interface link to this go cron doku:
https://pkg.go.dev/github.com/robfig/cron#hdr-CRON_Expression_Format
This is a cron "table" using 6 space-separated fields.

If i try to set a Cron with 6 fields i get the message: `Cron: expected exactly 5 fields, found 6: [* * * * * *]`
=> so here is just die doku link misleading.

**Comment by Travisnv** [comment]
This misleading error text really bugs me. Given that scheduled trigger is a very basic stuff. Perhaps, we need to fix this.

**Comment by NotGovernor** [comment]
Which field needs to be dropped to make it accept it for now as a workaround? Seconds?
It won't accept `0 0 7 * * *` for daily at 7 am for example.

**Comment by EHEX-schildt** [comment]
> Which field needs to be dropped to make it accept it for now as a workaround? Seconds? It won't accept `0 0 7 * * *` for daily at 7 am for example.

it is a CRON with five fields. There are no seconds.

'0 7 * * *' should work for you.

**Comment by NotGovernor** [comment]
Thanks!

**Comment by cmsj** [comment]
The link being used is wrong, it's linking to the original version of `robfig/cron`. The correct link should be to v3:

https://pkg.go.dev/github.com/robfig/cron/v3#hdr-CRON_Expression_Format

**Comment by EHEX-schildt** [comment]
Cron and Schedules handleing in version 2.10.11+ is improved
