### ISSUE TITLE
Prompt to accept SSH fingerprint

### ISSUE THREAD

**Issue by asmartin** [ansible-semaphore/semaphore#115]
If you attempt to connect to a host for the first time, you are prompted to accept the server's SSH key fingerprint:

```
The authenticity of host 'example (10.10.10.10)' can't be established.
RSA key fingerprint is a4:d9:a4:d9:a4:d9a4:d9:a4:d9a4:d9a4:d9a4:d9a4:d9a4:d9.
Are you sure you want to continue connecting (yes/no)?
```

Ideally you'd be able to click a button or enter `yes` from semaphore. Right now you have to type `yes` in the CLI prompt where semaphore is running, which probably isn't visible to most users. Note that this could also occur if the host's fingerprint changes, so there should be a way to deal with that too (e.g. accept it and continue or abort)

**Comment by matejkramny** [comment]
Ideally later on we want to schedule tasks to run at intervals (or at a future date). This needs to be carefully thought out.

**Comment by asmartin** [comment]
When you add a host to inventory, you could try a test ssh connection to it and prompt at that time to accept the fingerprint maybe

**Comment by niieani** [comment]
Semaphore currently fails silently when connecting to new hosts inside Docker. I wasted quite some time debugging this until I copy & pasted the SSH command after manually entering bash in the container and seeing it actually stops at the prompt:
```
Are you sure you want to continue connecting (yes/no)
```

This feature is a must!

**Comment by florisvangeel** [comment]
Experiancing same behaviour under proxmox 6 in buster, running:
`semaphore -config /etc/semaphore/config.json`
as root. next step is to run the program as privileged user so the sim linked cluster root ssh keys of proxmox don't get broken.

**Comment by florisvangeel** [comment]
Awesome running the semaphore under the ansible user solved my problem.
Hope it helps you as well.

My problem is resolved. However i suspect this software is doing something that breaks out of a unprivileged container when run as root, now it just fiddled with ansibles rsa, so i either run it as a nother user or perhaps easyer adapt to its changes.
