### ISSUE TITLE
Setup fails during migrations

### ISSUE THREAD

**Issue by johnjeffers** [ansible-semaphore/semaphore#116]
Centos 7.2.1511
mysql  Ver 15.1 Distrib 5.5.47-MariaDB, for Linux (x86_64) using readline 5.1

I get the following error when running setup:

```
# ./semaphore -setup

...snip...

 > DB Hostname (default 127.0.0.1:3306): 
 > DB User (default root): 
 > DB Password: *************
 > DB Name (default semaphore): 
 > Playbook path: 

 Generated configuration:
 {
 	"mysql": {
 		"host": "127.0.0.1:3306",
 		"user": "root",
 		"pass": "*************",
 		"name": "semaphore"
 	},
 	"port": "",
 	"bugsnag_key": "",
 	"tmp_path": "/tmp/semaphore",
 	"cookie_hash": "fHZ5W3TSIDnmsXuWUTf4UxF/9971o3ZSxIFRAWDnGUk=",
 	"cookie_encryption": "kworRzvSnZW46gDMBnRH8JQpv+f/lENxrchb1YVdSzQ="
 }

 > Is this correct? (yes/no): yes
 Running: mkdir -p /tmp/semaphore..
 Configuration written to /tmp/semaphore/semaphore_config.json..
 Pinging database..

 Running DB Migrations..
Creating migrations table
Executing migration v0.0.0 (at 2016-05-26 03:27:38.759845774 +0000 UTC)...
 [11/11]
Executing migration v1.0.0 (at 2016-05-26 03:27:38.796427455 +0000 UTC)...
 [7/7]
Executing migration v1.1.0 (at 2016-05-26 03:27:38.854228715 +0000 UTC)...
 [1/1]
Executing migration v1.2.0 (at 2016-05-26 03:27:38.861603993 +0000 UTC)...
 [1/1]
Executing migration v1.3.0 (at 2016-05-26 03:27:38.865485867 +0000 UTC)...
 [3/3]
Executing migration v1.4.0 (at 2016-05-26 03:27:38.882379524 +0000 UTC)...
 [2/2]
Executing migration v1.5.0 (at 2016-05-26 03:27:38.89167682 +0000 UTC)...
 [1/1]
Executing migration v0.1.0 (at 2016-05-26 03:27:38.895479413 +0000 UTC)...
 [1/6]
 ERR! Query: alter table user change `created` `created` datetime not null default current_timestamp

Rolling back v0.1.0 (time: 2016-05-26 03:27:38.89577671 +0000 UTC)...
Rollback SQL doesn't exist.


 Database migrations failed!
 Error 1067: Invalid default value for 'created'
```

**Comment by hanynowsky** [comment]
I get the same error here:
```
Running: mkdir -p /etc/ansible/semaphore/tmp..
 Configuration written to /etc/ansible/semaphore/tmp/semaphore_config.json..
 Pinging database..

 Running DB Migrations..
Creating migrations table
Executing migration v0.0.0 (at 2016-05-26 10:58:15.992304595 +0200 CEST)...
 [11/11]
Executing migration v1.0.0 (at 2016-05-26 10:58:16.227770548 +0200 CEST)...
 [7/7]
Executing migration v1.1.0 (at 2016-05-26 10:58:16.371573227 +0200 CEST)...
 [1/1]
Executing migration v1.2.0 (at 2016-05-26 10:58:16.386835577 +0200 CEST)...
 [1/1]
Executing migration v1.3.0 (at 2016-05-26 10:58:16.399710604 +0200 CEST)...
 [3/3]
Executing migration v1.4.0 (at 2016-05-26 10:58:16.461822009 +0200 CEST)...
 [2/2]
Executing migration v1.5.0 (at 2016-05-26 10:58:16.507931483 +0200 CEST)...
 [1/1]
Executing migration v0.1.0 (at 2016-05-26 10:58:16.533321001 +0200 CEST)...
 [1/6]
 ERR! Query: alter table user change `created` `created` datetime not null default current_timestamp

Rolling back v0.1.0 (time: 2016-05-26 10:58:16.533960748 +0200 CEST)...
Rollback SQL doesn't exist.


 Database migrations failed!
 Error 1067: Invalid default value for 'created'

```

- # mysql --version
mysql  Ver 15.1 Distrib 5.5.49-MariaDB, for Linux (x86_64) using readline 5.1

**Comment by johnjeffers** [comment]
This appears to be specific to MariaDB, because it doesn't understand the CURRENT_TIMESTAMP data type. It works fine in MySQL.

**Comment by matejkramny** [comment]
One solution is to remove the default values from the schema. I think we
already had this bug and this slipped past CI
On Thu, 26 May 2016 at 5:13 pm, John Jeffers <notifications@github.com>
wrote:

> This appears to be specific to MariaDB, because it doesn't understand the
> CURRENT_TIMESTAMP data type. It works fine in MySQL.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ansible-semaphore/semaphore/issues/116#issuecomment-221918975>
>
-- 
Matej Kramny

**Comment by m4dm4rtig4n** [comment]
Same bug :/

**Comment by hanynowsky** [comment]
Yeah. When I uninstalled MariaDb and installed MySQL 5.7 on the same CentOS 6. I got through and DB migration worked fine.

**Comment by m4dm4rtig4n** [comment]
I try to install MySQL but i have another bug XD

```
Executing migration v1.1.0 (at 2016-05-27 23:57:52.273178986 +0200 CEST)...
 [1/1]
 ERR! Query: /* update precision of output logs - also prevents confusion when sorting the table to guarantee it is in the same order */
alter table task__output change `time` `time` datetime(6) not null;

Rolling back v1.1.0 (time: 2016-05-27 23:57:52.273418679 +0200 CEST)...
Rollback SQL doesn't exist.


 Database migrations failed!
 Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(6) not null' at line 2

```

**Comment by hanynowsky** [comment]
Please install MySQL 5.7 and retry

**Comment by m4dm4rtig4n** [comment]
I have try with 5.6 and it's work fine.

**Comment by mguissine** [comment]
Tried both MySQL 5.6 and 5.7, still fails during migrations (on step 11):

 Pinging database..

 Running DB Migrations..
Creating migrations table
Executing migration v0.0.0 (at 2016-06-01 16:38:09.470137842 +0000 UTC)...
 [11/11]
Executing migration v0.1.0 (at 2016-06-01 16:38:16.516239564 +0000 UTC)...
 [3/6]
 ERR! Query: alter table task change `created` `created` datetime not null default current_timestamp

Rolling back v0.1.0 (time: 2016-06-01 16:38:16.577967909 +0000 UTC)...
Rollback SQL doesn't exist.


 Database migrations failed!
 Error 1054: Unknown column 'created' in 'task'

**Comment by matejkramny** [comment]
@mguissine you need the latest version

**Comment by mguissine** [comment]
Thanks @matejkramny, Do I need the latest version of MySQL or semaphore?

**Comment by matejkramny** [comment]
You should have `MySQL >= 5.6.4` and Semaphore [v2.0.2](https://github.com/ansible-semaphore/semaphore/releases/tag/v2.0.2)

You can upgrade from the UI if that is possible. There will be a new version soon.

**Comment by mguissine** [comment]
OK, both are on the latest but I still getting errors. I'll wait for the new version, thanks!
