### ISSUE TITLE
Define multiple vault password for a template

### ISSUE THREAD

**Issue by Guits32** [ansible-semaphore/semaphore#1169]
Hello (thanks a lot for your project, it's amazing, and very usefull),

Here is my usecase: for one playbook I have 3 different vault password, I would like to be able to pass all of them to a task template. Right now, from my current investigation, we can only set one vault password by task template.

Do you have any workaround, or do I miss something in the template creation?

**Comment by matthewblaha** [comment]
This is the main issue I'm having with Semaphore too. I have many large playbooks that sometimes use secrets encrypted with different ids, I can easily setup Ansible to use several, but no good way to do that in Semaphore.

When running Ansible-playbook I generally use a wrapper that configures ANSIBLE_VAULT_IDENTITY_LIST or use a script to fetch the secrets.

I see this is basically a duplicate of #1002

**Comment by Guits32** [comment]
Ok, thank you @matthewblaha, I close the issue then.
