### ISSUE TITLE
Where we can look file rsa private key in docker

### ISSUE THREAD

**Issue by roomit-xyz** [ansible-semaphore/semaphore#1187]
Dear Sir,

I have some problem during cloning, failed.
I got this error

```
5:40:46 PM
Unable to creating ssh auth method
5:40:46 PM
Failed updating repository: x509: decryption password incorrect
```

I have run used docker, and used gitlab as repository. 
I used ssh key for authentication.

Best Reagrds
Dwi

**Comment by mgukov** [comment]
Hello, @roomit-xyz,  do you use a ssh key with passphrase?
