### ISSUE TITLE
Branch support for repositories

### ISSUE THREAD

**Issue by stokkie90** [ansible-semaphore/semaphore#119]
Possible to specify an branch when making an task template

Maybe also include cloning submodules `--recursive`, when roles are in other repositories

**Comment by stryker250** [comment]
To add to this, would it be possible to specify the branch for the playbook repository as well?
This would be useful when testing a playbook which resides in a branch other than master.

**Comment by knsr** [comment]
Hi,
I made a small and simple modification in api/tasks/runner.go to support tags or branches add in git url.
see [ add support for git repo tags or branches ](https://github.com/knsr/semaphore/commit/d40f1d7f09bf5b5042bcf86b8680cef2031ec05a)

With this, you just have to specify the tag or branch at the end of url in the playbook repository definition.
`git://github.com:userspace/reponame.git#tag|branch`

_Full disclosure : I am not a golang dev ;)_

**Comment by davey-dev** [comment]
+1

Not everyone keeps everything on master

**Comment by mikequentel** [comment]
Hi @knsr was there a pull request for enhancement [add support for git repo tags or branches](https://github.com/knsr/semaphore/commit/d40f1d7f09bf5b5042bcf86b8680cef2031ec05a) -- I do not see it at [master/api/tasks/runner.go](https://github.com/ansible-semaphore/semaphore/blob/master/api/tasks/runner.go) -- it is an excellent enhancement. Many thanks.

**Comment by knsr** [comment]
Hi @mikequentel it was a mistake by my newness on GitHub 😀

**Comment by mikequentel** [comment]
Hi @knsr np--I am hoping one of the frequent contributors/owners will (please) respond to your pull request (this is an excellent enhancement)... @matejkramny @stokkie90 @stryker250 @davey-dev ?

For now @knsr I kindly suggest looking at [info on contributing](https://github.com/ansible-semaphore/semaphore/blob/master/CONTRIBUTING.md) and the [results of circleci for pull request 227](https://circleci.com/gh/ansible-semaphore/semaphore/99#config/containers/0) to ensure nothing is missing for the pull request--I don't know how strict this team are in accepting new pull requests.

**Comment by matejkramny** [comment]
@mikequentel i'll have a look now. We're not very strict. Code review to make sure nothing "bad" gets in, if it is useful to the community we will merge it.

**Comment by mikequentel** [comment]
Many thanks @matejkramny

**Comment by mcassaniti** [comment]
Is this able to get added to an FAQ of some sort on the wiki and this issue closed?

**Comment by mcassaniti** [comment]
I've added an FAQ wiki page and mentioned branching as part of the repository URL. Is this issue now considered resolved?
