### ISSUE TITLE
Get Semaphore username for use in Ansible playbooks

### ISSUE THREAD

**Issue by UNiXMIT** [ansible-semaphore/semaphore#1197]
Is it possible to get the active users Semaphore username for use in an Ansible playbook that they run from a task?

Thank you

**Comment by fatihusta** [comment]
you can add these task in your playbook/task

```
- name: 'Print Semaphore Variables'
  run_once: true
  delegate_to: localhost
  debug:
    var: semaphore_vars
```

ref: https://docs.ansible-semaphore.com/administration-guide/cicd

**Comment by UNiXMIT** [comment]
That's perfect thank you. I missed docs page that when searching.
