### ISSUE TITLE
Better README

### ISSUE THREAD

**Issue by Fale** [ansible-semaphore/semaphore#12]
Hi,
This project is amazing, please keep up with the good work :).

Reading the README file, I've encounter a section that is not very clear to me, specifically it is the "Note to Ansible guys" one.

    Thanks very much for making Ansible, and Ansible Tower. It is a great tool!. Your UI is pretty horrible though, and so we'd be happy if you could learn and use parts of this tool in your Tower.

Who did the previou affirmation? Where? When?

    It would be amazing if this could be your Community Edition of Ansible Tower.

Is this a response or a second part of the same sentence?

**Comment by matejkramny** [comment]
no its just a random sentence designed to send a message to Ansible (the company)

Its not a reply to anything as we never received response when we enquired about Tower & Ansible Tower with Ansible.
