### ISSUE TITLE
[Inventory] Convert Tabs into blanks automatically or add some sort of linting to the inventory

### ISSUE THREAD

**Issue by Moep90** [ansible-semaphore/semaphore#1204]
Hey guys,

I just had the issue (by accident) that I had tabs in my `Static YAML`.
When starting a task I got the verification error that it could not be determind weather this inventory is JSON nor YAML.

If possible I'd like to suggest a verification by inventory type.
so if `Static YAML` check if yaml is valid, if `Static` check if its valid ini file etc etc.

**Comment by steadfasterX** [comment]
yes tabs should be simply converted to spaces for static yml inventories @fiftin 

related error is:

> Syntax Error while loading YAML.   found character that cannot start any token
> The error appears to be in '/opt/XXXX/inventory_20218.yml': line 22, column 5, but may be elsewhere in the file depending on the exact syntax problem.
> The offending line appears to be:
>       thinktank:         ansible_ssh_user: XXXX  
> ^ here 
> There appears to be a tab character at the start of the line.  YAML does not use tabs for formatting. Tabs should be replaced with spaces.

**Comment by fiftin** [comment]
Sorry for delay. Fixed (in `develop` branch): tab = 2 spaces.
