### ISSUE TITLE
Cannot login to fresh install of v2.8.89

### ISSUE THREAD

**Issue by UNiXMIT** [ansible-semaphore/semaphore#1219]
I installed v2.8.89 fresh and added multiple users via the command line but none of them can login. Any ideas?

`semaphore user add --admin --name "Your Name" --login your_login --email your-email@examaple.com --password your_password`

**Comment by UNiXMIT** [comment]
Seems that the 'semaphore setup' command, although asking you for user details, doesn't seem to set them up correctly. I eventually managed to add an admin with the command line and login.

**Comment by fiftin** [comment]
Hi @UNiXMIT What database do you use?

**Comment by UNiXMIT** [comment]
Not an issue in the latest version.
