### ISSUE TITLE
Database migrations failed!

### ISSUE THREAD

**Issue by mgsreddy** [ansible-semaphore/semaphore#123]
Server version: 5.5.47-MariaDB MariaDB Server
Semaphore version : 2.0.2

issue:

> Is this correct? (yes/no): yes
 Running: mkdir -p /etc/ansible..
 Configuration written to /etc/ansible/semaphore_config.json..
 Pinging database..

 Running DB Migrations..
Creating migrations table
Executing migration v0.0.0 (at 2016-06-06 11:45:28.853907527 -0700 PDT)...
 [11/11]
Executing migration v1.0.0 (at 2016-06-06 11:45:28.870141697 -0700 PDT)...
 [7/7]
Executing migration v1.1.0 (at 2016-06-06 11:45:28.885980876 -0700 PDT)...
 [1/1]
Executing migration v1.2.0 (at 2016-06-06 11:45:28.888410896 -0700 PDT)...
 [1/1]
Executing migration v1.3.0 (at 2016-06-06 11:45:28.889805971 -0700 PDT)...
 [3/3]
Executing migration v1.4.0 (at 2016-06-06 11:45:28.896278671 -0700 PDT)...
 [2/2]
Executing migration v1.5.0 (at 2016-06-06 11:45:28.899740481 -0700 PDT)...
 [1/1]
Executing migration v0.1.0 (at 2016-06-06 11:45:28.902268714 -0700 PDT)...
 [1/6]
 ERR! Query: alter table user change `created` `created` datetime not null default current_timestamp

Rolling back v0.1.0 (time: 2016-06-06 11:45:28.902625855 -0700 PDT)...
Rollback SQL doesn't exist.

 Database migrations failed!
 Error 1067: Invalid default value for 'created'

**Comment by pipko** [comment]
The same on MySQL 5.5.49-0ubuntu0.14.04.1
Semaphore v2.0.2

**Comment by scline** [comment]
In the meantime, I was able to bypass this error by installing version 2.0 then performing an upgrade from the GUI.

**Comment by matejkramny** [comment]
Will be fixed when 2.0.3 is out (see the diff here: https://github.com/ansible-semaphore/semaphore/compare/v2.0.2...master)
