### ISSUE TITLE
Adding a new user results in error

### ISSUE THREAD

**Issue by hhenkel** [ansible-semaphore/semaphore#124]
When I try to add a new user under "users" => "new user" the mask is prefilled with my current user information. When I try to alter those settings and click "create user" I recieve a HTTP 400 error. Furthermore the name of my current user is changed to the new name.

**Comment by matejkramny** [comment]
Looks like it wants to change your user details instead of adding a new user.

**Comment by matejkramny** [comment]
As a workaround you can run the interactive setup and provide a new user there.
