### ISSUE TITLE
Demo Prompt 401 - inaccessible

### ISSUE THREAD

**Issue by matthew-palmer** [ansible-semaphore/semaphore#1255]
The demo site prompts for credentials and initial landing page responds with a 401
Seems to be a repeat of  #1013 but does not explain the fix required

<img width="465" alt="Screen Shot 2023-06-01 at 1 54 26 PM" src="https://github.com/ansible-semaphore/semaphore/assets/52665248/44633faf-ed96-454a-8c02-4e93c32b16d6">

**Comment by fiftin** [comment]
Fixed) some time it down :D
