### ISSUE TITLE
Is there any plan to support Chinese?

### ISSUE THREAD

**Issue by rayshen3** [ansible-semaphore/semaphore#1260]
![image](https://github.com/ansible-semaphore/semaphore/assets/9734936/f9a0755f-40ee-4483-a96a-9f734bb13266)

**Comment by tboerger** [comment]
Generally the data should be stored in utf-8 format, so storing Chinese values shouldn't be a problem. If you still encounter issues please provide more details including logs and configurations within a new issue.
