### ISSUE TITLE
New Debian 11.7 install

### ISSUE THREAD

**Issue by Pontiac76** [ansible-semaphore/semaphore#1263]
I found out about this project via YouTube - https://www.youtube.com/watch?v=NyOSoLn5T5U

I use Ansible at work at times, so having a UI and better key management and user management would be so much better, so I'm trialling this in my own lab.  But I've come across something odd...

The focal point I have is Christian put in a "become" statement which I assume is the sudo equivilent.

So after a big fight with getting this installed (Dependency hell with official documentation not correct on pretty much every tool needed to get this going), what is being done in the background to get "become" to work?   

I created an "ansible" user on the target system, I made sure sudo was installed, and I added the user to the sudoers, and I can switch to the root user using sudo, but I keep getting errors asking if I'm root when I run the tak in Semaphore?  

I've tried changing "become" to "sudo" and got told that sudo is no longer a valid command.  The official documentation for ansible doesn't have "become" as a thing.  It does have "become_user" but even with both parameters set (Yes and root), I'm still not getting in.  If I change the key store to log in as root, it works.

I'm MAKING the connection to the destination because I'm being told I'm not root.  So I'm at a loss to what's going on here?

**Comment by andreas-marschke** [comment]
Your problem isn't with Ansible Semaphore (an open source project not directly affiliated with Ansible, however provides a UI to Ansible), but with Ansible. I ask you to review the Ansible documentation about [privilege escalation](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_privilege_escalation.html).
Furthermore, to simplify troubleshooting  if it *is* a problem with Semaphore and not with Ansible, ensure your playbooks are working as intended when run from the commandline locally.

**Comment by ansibleguy** [comment]
Greetings!

@Pontiac76 This does not seem to be a Semaphore issue.
If you have Problems setting up the Python/Ansible/Semaphore stack:
- Look into this documentation: [Manual Installation](https://github.com/ansibleguy/ansible-semaphore-docs/blob/manual-setup-docs/administration-guide/installation_manually.md)

If you have questions for the basic usage of Ansible:
- Read the [Ansible Getting started Guide](https://docs.ansible.com/ansible/latest/getting_started/index.html)
- Check out Videos to get an [Intro to Ansible](https://www.youtube.com/results?search_query=Intro+to+Ansible)
- This is not the right place for an 'issue' like that (:

**Comment by Pontiac76** [comment]
Kinda makes sense.  I'll close.
