### ISSUE TITLE
SSH config file support

### ISSUE THREAD

**Issue by matthewschroer** [ansible-semaphore/semaphore#1270]
I would like to be able to use an inventory file that references an ssh config file

When I try to run a playbook semaphore is unable to connect because it does not have my ssh config file containing all my ssh settings.

**Comment by 9whirls** [comment]
Don't use snap (which has its own file system) to install Semaphore. Semaphore installed as a local service via deb or rpm package can use the ssh config file.

**Comment by matthewschroer** [comment]
I did both an docker and a snap install. I will close until I get around to installing via package
