### ISSUE TITLE
Cant delete templates.

### ISSUE THREAD

**Issue by StasABerg** [ansible-semaphore/semaphore#1294]
Im trying to delete a template but get prompted with and error that the I cant delete it due to ''resources below being in use"
the resource is the template Im trying to delte
![image](https://github.com/ansible-semaphore/semaphore/assets/114340468/e3ae0eae-34fe-42aa-b984-0a12d8d1ed26)

Using version 2.8.89

**Comment by theapu** [comment]
I got the same problem. I had set cron for the template. Afte removing cron job line from the cron field I was able to delete the template.

**Comment by StasABerg** [comment]
Yeah you need to empty the cronjob field in order to delete the task.
A bit weird solutions but works!
Thanks @theapu
