### ISSUE TITLE
Documentation needs migration and SSL info

### ISSUE THREAD

**Issue by slimandslam** [ansible-semaphore/semaphore#130]
There is nothing on the wiki page about implementing SSL.  Don't answer it here, answer it on your installation wiki.   Also, there is nothing on the wiki page about migrating Semaphore 1.x installations to 2.x.  If it can't be done easily, then mention that on the wiki.

**Comment by matejkramny** [comment]
See wiki.

**Comment by slimandslam** [comment]
That's what I'm talkin bout!  Nice.

**Comment by matejkramny** [comment]
:). I'm currently progressing through #94

**Comment by slimandslam** [comment]
Awesome!

**Comment by kantmakm** [comment]
It would be quite helpful to post an example of a valid ENVIRONMENT json entry for the 2.x semaphore release in the documentation.  I have no idea what that is supposed to look like!

**Comment by matejkramny** [comment]
Its the same as ansible's `--extra-vars` parameter:

https://docs.ansible.com/ansible/playbooks_variables.html#id30

Semaphore passes quoted JSON to ansible. In theory you could also pass space-delimited variables. The UI will (in future releases) have a proper editor for this and convert it to json and back.

I've posted this to the wiki as well.

**Comment by kantmakm** [comment]
Thanks!  I'm almost up and going with 2.  I cannot easily figure out where hosts are defined:  I'm getting:
10:52:34: access key spireimitix installed
10:52:34: Updating repository
10:52:34: From bitbucket.org:spiremedia/masterplaybook
10:52:34:  * branch            master     -> FETCH_HEAD
10:52:34: Already up-to-date.
10:52:34: access key spireimitix installed
10:52:34: installing static inventory
10:52:35: Using /etc/ansible/ansible.cfg as config file
**10:52:35:  [WARNING]: provided hosts list is empty, only localhost is available**
10:52:35: Loaded callback default of type stdout, v2.0
10:52:35: 
10:52:35: PLAYBOOK: software-deploy.yaml *************************************************
10:52:35: 1 plays in project-deploy/software-deploy.yaml
10:52:35: 
10:52:35: PLAY [celoxis] *****************************************************************
10:52:35: skipping: no hosts matched
10:52:35: 
10:52:35: PLAY RECAP *********************************************************************
10:52:35: 

I do have a group in /etc/ansible/hosts  called celoxis defined, and I see that the output tells me it's using /etc/ansible/ansible.cfg  where I defined :
inventory      = /etc/ansible/hosts

I have also added an Inventory item through semaphore called celoxis that looks like this:
![image](https://cloud.githubusercontent.com/assets/833202/16275663/32bf1476-3868-11e6-90db-e2e7302e39f4.png)

**Comment by kantmakm** [comment]
Nevermind!  Figured it out:
The inventory needs to look like a complete host entry so instead of just the IP address, the inventory should contain:

[groupname]
10.1.1.1
10.1.1.2

**Comment by slimandslam** [comment]
So during installation of v2.x, if you give it an installation path to an existing 1.x installation, it will automatically migrate and update everything?
