### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by popoyorc** [ansible-semaphore/semaphore#131]
Hi I can now successfully run sempahore in development, but I don't know where or how to go next? Apologies I am new to `GO`. Thanks

**Comment by matejkramny** [comment]
You can either download the [pre-buiilt binary](https://github.com/ansible-semaphore/semaphore/wiki/Installation#install-instructions) or follow the [instructions](https://github.com/ansible-semaphore/semaphore/blob/master/CONTRIBUTING.md) for developers.

**Comment by matejkramny** [comment]
Sorry I read about half of your question and thought i had an answer. Sorry!.

The next step is go to http://localhost:3000 and create your test project. Create lots of environments, inventories and access keys to test with. Then create a few templates that use them and go run tests.

If there's something specific you're looking to improve, please let us know so we can point you to the right direction.

**Comment by popoyorc** [comment]
Thanks @matejkramny , I would like to know how to get the binary files from my development environment? Again apologies Im new to `go`.

**Comment by popoyorc** [comment]
Found the binaries in `src/github.com/ansible-semaphore/semaphore/cli`. leaving it here for others to see.

**Comment by matejkramny** [comment]
not sure what you mean, but you can run `./make.sh` which will generate binaries for many platforms.
