### ISSUE TITLE
Request for Git-based Ansible Inventory Support

### ISSUE THREAD

**Issue by whoamiUNIX** [ansible-semaphore/semaphore#1312]
Hello Ansible Semaphore team,

I would like to request the addition of **Git-based Ansible inventory support in Ansible Semaphore**.
It lacks native integration with Git for seamless version control and collaboration on inventories.

**Comment by pratikkumar-mohite** [comment]
@whoamiUNIX working on this https://github.com/ansible-semaphore/semaphore/issues/455 will add the git integration as well

**Comment by krauthex** [comment]
Hey @pratikkumar-mohite, just wanted to ask if you have any idea if this feature will make it in one of the upcoming releases of semaphore? :-) thanks for your effort!

**Comment by zorrobiwan** [comment]
Possible in a certain way:
https://github.com/ansible-semaphore/semaphore/discussions/1071

**Comment by nroach44** [comment]
> Possible in a certain way: #1071

Yeah, this is the trick I use, but I'd like to keep my inventory (and host-vars) separate, allowing me to publicise my playbook repo easily.

**Comment by zorrobiwan** [comment]
got it

**Comment by pwannenmacher** [comment]
Will there be an option to select a Git repo as an investoy in the UI in the near future?

**Comment by fiftin** [comment]
Duplicate https://github.com/ansible-semaphore/semaphore/issues/902
