### ISSUE TITLE
Feature Request: Receive Webhooks to run Tasks

### ISSUE THREAD

**Issue by andreas-marschke** [ansible-semaphore/semaphore#1319]
This feature request came out of an integration requirement.

I'm trying to automate events in another service that is capable of emitting webhooks. On certain events emitted this way I want to run a task in Ansible or in Semaphore. 
Events that can happen are:
 - User Key Rotation
 - Developer Opens a new branch
 - A merge was done
 - etc.

For these events the system is capable of firing a webhook. Ansible Semaphore is supposed to receive these webhooks and translate values from the data posted by the webhook as variables to pass to the playbook based on my definition of what values are to be extracted.

Consider the following body of a POST Request:
```json
{
  "event_type": "user-key-update",
  "user": "foobar",
}
```
with the following headers: 
```
SERVICE_TOKEN: abc
Host: service.example.com
```

I filter for the host it comes from and extract the user for which to run the playbook template and pass the user as `{"user": "foobar"}` to the playbook.

This would allow me to provide a range of automation events and allows for the accountability through the Ansible Semaphore event system.

**Comment by tqm-deployer** [comment]
+1

**Comment by icaliman** [comment]
+1

**Comment by fiftin** [comment]
Done
