### ISSUE TITLE
fork/exec /usr/bin/ansible-playbook: not a directory

### ISSUE THREAD

**Issue by Grunticus03** [ansible-semaphore/semaphore#1320]
I installed semaphore from the .deb package, following the instructions here.  When trying to run a task, I receive the following output:
```
2:07:39 AM
Task 1 added to queue
2:07:42 AM
Preparing: 1
2:07:42 AM
Prepare TaskRunner with template: Linux Update Only
2:07:42 AM
installing static inventory
2:07:42 AM
No collections/requirements.yml file found. Skip galaxy install process.
2:07:42 AM
No roles/requirements.yml file found. Skip galaxy install process.
2:07:47 AM
Started: 1
2:07:47 AM
Run TaskRunner with template: Linux Update Only
2:07:47 AM
Running playbook failed: fork/exec /usr/bin/ansible-playbook: not a directory
```
I'm running a simple task to update apt repositories.  Just trying to validate Semaphore functionality.
```
---

- hosts: all
  become: true

  tasks:
    - name: Update apt packages
      apt:
        upgrade: no
        update_cache: yes
```
If I run this playbook using `ansible-playbook` it executes fine.

**Comment by Grunticus03** [comment]
@fiftin, since you've marked it as a bug, is there an alternative format I could write the playbook in to get this to work?

**Comment by fiftin** [comment]
Hi @wwalker0307 

I didn't find the source of the issue yet.

What the path of your `ansible-playbook` tool? You can get it by command:

```
which ansible-playbook
```

**Comment by Grunticus03** [comment]
```
root@ansible:/home/administrator# which ansible-playbook
/usr/bin/ansible-playbook
```

**Comment by ansibleguy** [comment]
Greetings.

Just covering the basics for your environment:
* What version of Semaphore are you running?
* Is Semaphore also running as root or do you use a dedicated 'serviceuser'?
  * Has the user running semaphore execution privileges for the binary '/usr/bin/ansible-playbook'? (if not root..)
* If you have installed Ansible using apt - I would recommend using the pip-based installation instead as described in the [Ansible Installation Guide](https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#pipx-install) (much newer Version)

\- AnsibleGuy

**Comment by Grunticus03** [comment]
* What version of Semaphore are you running?
2.8.9

* Is Semaphore also running as root or do you use a dedicated 'serviceuser'?
  * Has the user running semaphore execution privileges for the binary '/usr/bin/ansible-playbook'? (if not root..)
The service is configured to run as root.  I believe below shows that root has execution privileges
![image](https://github.com/ansible-semaphore/semaphore/assets/36755138/5c4674b2-a6fd-463f-a880-203dc8d7cc4a)


* If you have installed Ansible using apt - I would recommend using the pip-based installation instead as described in the [Ansible Installation Guide](https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#pipx-install) (much newer Version)
It looks like, in my attempts to troubleshoot, both apt and pip packages are installed.  I believe I originally installed via apt.
![image](https://github.com/ansible-semaphore/semaphore/assets/36755138/7b69bab7-a344-4651-92b1-a8aff7722268)

**Comment by Grunticus03** [comment]
I removed both apt and pip installations of ansible and then installed the pip package, no change in Semaphore.  The new path to ansible-playbook is /usr/local/bin/ansible-playbook and it's still owned by root with execute privileges.  ansible --version shows 2.13.11

**Comment by ansibleguy** [comment]
From what I've read - this exact error message occurs when one tries to set the 'Dir' attribute of an instance of 'exec.Command' to a non-existent one.
The only usage of that attribute seems to be here: https://github.com/ansible-semaphore/semaphore/blob/develop/lib/AnsiblePlaybook.go#L20
But this uses the path to "{repository}" that should not result in '/usr/bin/ansible-playbook'.

Could you supply the task-template and repository config you are using?

**Comment by Grunticus03** [comment]
```
---

- hosts: VM_Guests
  become: true

  tasks:
  - name: Update apt packages
    apt:
      upgrade: no
      update_cache: yes
```

![image](https://github.com/ansible-semaphore/semaphore/assets/36755138/6eb95053-f13c-473e-8569-5ccd08512903)

**Comment by ansibleguy** [comment]
I think I see the problem.
The 'repository' in Semaphore should be the directory containing your Ansible directory structure as [described in the Ansible documentation](https://docs.ansible.com/ansible/2.8/user_guide/playbooks_best_practices.html#directory-layout)

You have supplied the path to a single playbook.
Semaphore checks if the repository is a directory => that is not the case => error.

@wwalker0307 Please try supplying the path '/etc/ansible/playbooks' as repository location and retry it.

**Comment by ansibleguy** [comment]
If my assumption is correct:

@fiftin Problems with this I see on the side of Semaphore:
* The path in the error message is wrong (_not sure if that could be a problem of the underlying library/module - as I've seen a similar problem in another GO application_)
* The [documentation about repositories](https://docs.ansible-semaphore.com/user-guide/repositories) does not mention it has to be a directory
* A validation, to check if the repository indeed is a directory, should be done before adding it: https://github.com/ansible-semaphore/semaphore/blob/9a35aabb57e129dd5e8e851cebc44d81997a04df/api/projects/repository.go#L64

I'll note it and may add a PR to fix the most pressing ones

**Comment by Grunticus03** [comment]
Yes, that's exactly what the problem was, I supplied a file instead of a folder path.  That resolves this particular problem.  I took another look at the documentation and it seems pretty clear on what a repository should consist of.  A validation check seems like a good path forward, though this is more of a user error issue.
