### ISSUE TITLE
Using Netbox as an inventory source

### ISSUE THREAD

**Issue by kollross** [ansible-semaphore/semaphore#1334]
I'm trying to configure semaphore to use a dynamic inventory from Netbox (much like you can do via ansible on the CLI).

Is this feasible?   

I tried to dump the current ansible inventory file (backhanded by netbox) and dumping it into a yml file (ansible-inventory --list > inventory.yml) and specifying that as a "inventory file" but that didn't appear to work correctly.

**Comment by WilliamDEdwards** [comment]
Same question. FFR, this was moved to a discussion: https://github.com/ansible-semaphore/semaphore/discussions/1336

**Comment by kollross** [comment]
Correct
