### ISSUE TITLE
semaphore not working

### ISSUE THREAD

**Issue by sahara101** [ansible-semaphore/semaphore#1340]
Hello, I have installed ansible and semaphore on an ubuntu lxc container. After creating a test yml file, it is working via ansible. 
Semaphore just shows failed in the task but not why it failed. Repository is set to local /etc/ansible/playbooks so not via git.

Any ides? Thanks!

**Comment by andreas-marschke** [comment]
Can you share the task run log from within Semaphore?
If you open the task you should be able to see the logs for its execution.

**Comment by sahara101** [comment]
I reinstall semaphore and now I get some text, here it is:

`2:02:32 AM
Task 2147483645 added to queue
2:02:34 AM
Preparing: 2147483645
2:02:34 AM
Prepare TaskRunner with template: Updates
2:02:34 AM
No collections/requirements.yml file found. Skip galaxy install process.
2:02:34 AM
No roles/requirements.yml file found. Skip galaxy install process.
2:02:39 AM
Started: 2147483645
2:02:39 AM
Run TaskRunner with template: Updates
2:02:39 AM
[WARNING]: * Failed to parse /etc/ansible/hosts with script plugin: problem
2:02:39 AM
running /etc/ansible/hosts --list ([Errno 13] Permission denied:
2:02:39 AM
'/etc/ansible/hosts')
2:02:39 AM
[WARNING]: * Failed to parse /etc/ansible/hosts with yaml plugin: an error
2:02:39 AM
occurred while trying to read the file '/etc/ansible/hosts': [Errno 13]
2:02:39 AM
Permission denied: b'/etc/ansible/hosts'. [Errno 13] Permission denied:
2:02:39 AM
b'/etc/ansible/hosts'
2:02:39 AM
[WARNING]: * Failed to parse /etc/ansible/hosts with ini plugin: an error
2:02:39 AM
occurred while trying to read the file '/etc/ansible/hosts': [Errno 13]
2:02:39 AM
Permission denied: b'/etc/ansible/hosts'. [Errno 13] Permission denied:
2:02:39 AM
b'/etc/ansible/hosts'
2:02:39 AM
[WARNING]: Unable to parse /etc/ansible/hosts as an inventory source
2:02:39 AM
[WARNING]: No inventory was parsed, only implicit localhost is available
2:02:39 AM
[WARNING]: provided hosts list is empty, only localhost is available. Note that
2:02:39 AM
the implicit localhost does not match 'all'
2:02:39 AM
ERROR! an error occurred while trying to read the file '/etc/ansible/books/updates.yml': [Errno 13] Permission denied: b'/etc/ansible/books/updates.yml'. [Errno 13] Permission denied: b'/etc/ansible/books/updates.yml'
2:02:39 AM
Running playbook failed: exit status 4`

Any ideas why it would have no access? 

root@ansible:/etc/ansible/books# ll -d /etc/ansible/
drwxr-xr-x 5 root root 4096 Jul 15 08:51 /etc/ansible//

root@ansible:/etc/ansible/books# ll /etc/ansible/
total 72
drwxr-xr-x  5 root root  4096 Jul 15 08:51 ./
drwxr-xr-x 80 root root  4096 Jul 15 09:06 ../
-rw-r--r--  1 root root  1069 Jul 12 19:09 LICENSE
-rw-r--r--  1 root root 20211 Jul 14 14:57 ansible.cfg
-rw-r--r--  1 root root 20209 Jul 14 14:57 ansible.cfg.bak
drwxr-xr-x  2 root root  4096 Jul 15 09:09 books/
drwxr-xr-x  3 root root  4096 Jul 12 19:09 group_vars/
-rw-r--r--  1 root root   266 Jul 15 08:51 hosts
-rw-r--r--  1 root root  2859 Jul 12 19:09 readme.md
drwxr-xr-x  4 root root  4096 Jul 14 15:00 roles/


Thanks!

**Comment by ansibleguy** [comment]
Greetings!

Please:
* Use code-blocks for shell output
* Provide some more information about your setup:
  * How did you install it? dpkg? snap?
  * Is semaphore ran using a systemd service?
  * By what user is the semaphore process running? root? semaphore?
  * Output of `tree -d` of your /etc/ansible directory

Also: playbooks should be placed in the same directory as the 'roles' sub-directory - see: [Ansible Directory Layout](https://docs.ansible.com/ansible/2.8/user_guide/playbooks_best_practices.html#directory-layout)
Else you will run into 'funny' issues.

\- AnsibleGuy

**Comment by sahara101** [comment]
I had semaphore installed via snapd. Deleted and installed with package manager and now it seems to work. 

Thanks!

**Comment by ansibleguy** [comment]
@sahara101 Good to hear you were able to solve your issue.
Can you please 'close' this issue-ticket?
Thanks
