### ISSUE TITLE
[Bug?] Task getting populated in ALL view rather than CUSTOM view in Task Templates

### ISSUE THREAD

**Issue by sahilister** [ansible-semaphore/semaphore#1343]
**Steps to reproduce**

- _Task Templates_ section > Edit pencil > create new view with name test_view
- Click _test_view_ > create _NEW TEMPLATE_
- Task template shows under ALL view and not test_view 

**Expected behavior**

Task should show in view it was created in.

**Actual behavior**

All newly created tasks show up under ALL view.

**System Information** 

Version - Semaphore 2.8.90 through DEB package on Debian bookworm server.
Arch - AMD64

Let me know if View feature wasn't intended to be used for categorizing task templates.

**Comment by andreas-marschke** [comment]
Hi @sahilister 

I think this is more a misunderstanding between user expectation and UI communication.

Yes, you have views and a "new template" button, but you can also find a dropdown selection in the new template form for View, which is not automatically populated with the view you've currently selected.

![image](https://github.com/ansible-semaphore/semaphore/assets/1198936/1ba0053d-744e-40e0-8c6d-36ef6bc14cac)

I don't think it should be either.

Kind regards,

Andreas.

**Comment by sahilister** [comment]
thanks @andreas-marschke for the information. That does solves the purpose.
