### ISSUE TITLE
ModuleNotFoundError: No module named 'docker'

### ISSUE THREAD

**Issue by samcro1967** [ansible-semaphore/semaphore#1349]
Having trouble installing a docker plugin using semaphore.

I have 2 hosts, host1 and host2.  Semaphore is running in a docker container on host1.  If I am reading the documentation correctly, the requirement is for the docker pip package to be installed on the target machine (host2)..  I have done ``pip install docker' as user 1000 on host2.  I am always running the playbook as user 1000.  I can run the ansible playbook on host1 and install the plugin on host2.  I can run the playbook locally on host2 and install the plugin.  When I try to run the playbook from Semaphore or from the cli inside the semaphore container on host1, I get the error message below.

Hoping someone has come across this or has an idea what to try.

**Error Message**
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'docker'
fatal: [host2]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (Docker SDK for Python: docker above 5.0.0 (Python >= 3.6) or docker before 5.0.0 (Python 2.7)) on host2's Python /bin/python3. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter, for example via `pip install docker` (Python >= 3.6) or `pip install docker==4.4.4` (Python 2.7). The error was: No module named 'docker'"}
```

**Ansible Config**
```
  - name: Install docker-file-log-driver plugin
      community.docker.docker_plugin:
      plugin_name: deepcompute/docker-file-log-driver:1.0
      state: present
      alias: file-log-driver
    vars:
      ansible_python_interpreter: /bin/python3
    tags:
     - docker
```

**Comment by ansibleguy** [comment]
Greetings!

For Ansible it is very rare that you need to install any requirements on the actual target host.
The [module documentation](https://docs.ansible.com/ansible/latest/collections/community/docker/docker_plugin_module.html#requirements) mentions `..on the host that executes this module`. I don't think those modules are actually copied and executed to the target host 'host2' as the docker API allows for remote management.

Please try installing the requirements in the context of the user that runs Semaphore on 'host1' and re-try it.

\- AnsibleGuy

**Comment by samcro1967** [comment]
Doing a `pip install --user semaphore docker` inside the semaphore container on host1 had no effect.  Still getting the same error.

**Comment by ansibleguy** [comment]
Is there a reason for the `ansible_python_interpreter: /bin/python3`?
Could you try to re-run it without?

**Comment by samcro1967** [comment]
I added that per a suggestion I found on [stackoverflow ](https://stackoverflow.com/questions/59384708/ansible-returns-with-failed-to-import-the-required-python-library-docker-sdk-f) to make sure the right python interpreter is being used when using the python docker SDK.  It had no effect and I forgot to remove it.  Just removed and rested with the same results.

**Comment by ansibleguy** [comment]
Hmm. Have you tried manually executing the ansible-playbook via shell on the semaphore server? (after changing the user to 'semaphore')

**Comment by samcro1967** [comment]
Yes, running it from the cli in the semaphore container as the semaphore user does not work.

**Comment by ansibleguy** [comment]
So we can at least take the semaphore software 'out of the equation' as it does also not work without it.
I'll check if I can reproduce the issue on my setup. For now I'm pretty out of ideas what exactly could be the problem - but I have the feeling its some issue with the python environment.

**Comment by samcro1967** [comment]
Definitely seems to be something with the python environment in the semaphore container.  I am able to run the test python script below on host1 successfully, but it fails inside the semaphore container.

test.py
```
import docker
client = docker.from_env()
image = client.images.pull("alpine")
print(image.id)
```

```
 python3 ./test.py
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 496, in _make_request
    conn.request(
  File "/usr/lib/python3.10/site-packages/urllib3/connection.py", line 395, in request
    self.endheaders()
  File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/home/semaphore/.local/lib/python3.10/site-packages/docker/transport/unixconn.py", line 27, in connect
    sock.connect(self.unix_socket)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.10/site-packages/urllib3/util/retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3.10/site-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 496, in _make_request
    conn.request(
  File "/usr/lib/python3.10/site-packages/urllib3/connection.py", line 395, in request
    self.endheaders()
  File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/home/semaphore/.local/lib/python3.10/site-packages/docker/transport/unixconn.py", line 27, in connect
    sock.connect(self.unix_socket)
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/semaphore/.local/lib/python3.10/site-packages/docker/api/client.py", line 214, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
  File "/home/semaphore/.local/lib/python3.10/site-packages/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
  File "/home/semaphore/.local/lib/python3.10/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/home/semaphore/.local/lib/python3.10/site-packages/docker/api/client.py", line 237, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ansible/./test.py", line 2, in <module>
    client = docker.from_env()
  File "/home/semaphore/.local/lib/python3.10/site-packages/docker/client.py", line 96, in from_env
    return cls(
  File "/home/semaphore/.local/lib/python3.10/site-packages/docker/client.py", line 45, in __init__
    self.api = APIClient(*args, **kwargs)
  File "/home/semaphore/.local/lib/python3.10/site-packages/docker/api/client.py", line 197, in __init__
    self._version = self._retrieve_server_version()
  File "/home/semaphore/.local/lib/python3.10/site-packages/docker/api/client.py", line 221, in _retrieve_server_version
    raise DockerException(
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
```

**Comment by samcro1967** [comment]
@ansibleguy I was able to get the docker python SDK working in the container.  I had to add the docker group to the semaphore container in my docker compose as well as mount docker.sock.  Now I am able to run the test script above successfully and validate the SDK is installed and working correctly from the cli as the semaphore user in the container. 
 `python3 -c "import docker; print(docker.__version__)"` returns `6.1.3`.

The playbook still gets the same error.  I also has to install the python docker SDK on the host2 (target machine) as root since I have `become: true` set in my playbook.  The playbook now runs from the cli and the semaphore GUI.

**Comment by ansibleguy** [comment]
@samcro1967 This might not work if you want to target remote docker-servers though.
If you want to check your Python environment you could give my docs-PR a read: [Manual Installation](https://github.com/ansibleguy/ansible-semaphore-docs/blob/manual-setup-docs/administration-guide/installation_manually.md)
Feedback to the docs would also be appreciated!

Have a nice Day!

**Comment by samcro1967** [comment]
@ansibleguy My use case is targeting remote docker servers and is working.  Thanks for sharing your docs, a lot of good information.  I am running Semaphore/ansible in a docker container on the source host.  That use case is a little different than what you are covering in the docs uless I am just missing it.  I have a custom Dockerfile to update the container with docker, pip, and the docker python SDK.  There are also permissions I had to get sorted out so the semaphore user can execute `docker ps` in the container without sudo.  Then I could test that python was working but more importantly that the SDK was working.  I also had to install the SDK on the target machines as root so sequence wise had to make sure that is done before installing the docker plugin.

If you wanted to add something around docker and docker plugins when using the semaphore docker container, I have shared my Dockerfile below and well as a snippet of my docker compose.

I would also maybe add `python3 -c "import docker; print(docker.__version__)"` as a way to confirm the SDK is installed and to validate what version is installed as well as the test script above to use the SDK to pull the alpine image as a test that permissions are setup correctly.

**Docker Compose**
```
  semaphore:
    hostname: semaphore
    image: registry.local:5000/username/semaphore:latest
    container_name: semaphore
    restart: unless-stopped
    group_add:
      - "999" # GID of docker group on localhost
    volumes:
      - ${docker}/semaphore/temp:/tmp/semaphore/
      - ${docker}/semaphore/ansible/ansible.cfg:/etc/ansible/ansible.cfg
      - ${docker}/semaphore/config/config.json:/etc/semaphore/config.json
      - ${docker}/semaphore/.ssh:/home/semaphore/.ssh
      - ${docker}/ansible:/ansible
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
    ...
```

**Dockerfile**
```
FROM semaphoreui/semaphore:latest

USER root
RUN apk add rsync py3-pip docker bash nano sudo
RUN pip install ara
RUN echo "semaphore ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/semaphore
RUN chmod 0440 /etc/sudoers.d/semaphore
user semaphore
RUN pip install docker
```

**Comment by ansibleguy** [comment]
@samcro1967 Yeah - sorry. Got the issues mixed up and overlooked that your installation is inside a docker container. Sorry ^^
Thanks for sharing your config.
The documentation for docker might also have room for improvement, yes.
Especially when it comes to such use-cases.
