### ISSUE TITLE
Different ssh key for git clone and inventory ssh

### ISSUE THREAD

**Issue by droidlabour** [ansible-semaphore/semaphore#135]
There must be a flag to specify different SSH Key for git clone and inventory SSH purpose.
It makes sense to specify the flag in this API Endpoint. `/project/{project_id}/tasks`

**Comment by matejkramny** [comment]
It is possible. You can pick an ssh key for the inventory and another key for the repo access.

The SSH key specified when making a template is for inventory access. It doens't really make sense to override the repo key there.
