### ISSUE TITLE
 Error: unknown command "/etc/semaphore/config.json" for "semaphore"

### ISSUE THREAD

**Issue by Ijoezl** [ansible-semaphore/semaphore#1355]
Hi Guys need help.

I am getting this error to start my semaphore in Centos 8. I have installed v2.8.90 version in my VM. Using local MariaDB for MySQL. I am attaching my config.json here. Fyi i am using root user to install semaphore.

Kindly help out guys i have been stuck for like a week like this. Tell me if you need any more info. From the log it seems like its in restarting loop.

Jul 20 15:49:29 icba10-ansible-centos8 systemd[1]: Started Semaphore Ansible UI.
Jul 20 15:49:29 icba10-ansible-centos8 semaphore[131271]: Error: unknown command "/etc/semaphore/config.json" for "semaphore"
Jul 20 15:49:29 icba10-ansible-centos8 semaphore[131271]: Run 'semaphore --help' for usage.
Jul 20 15:49:29 icba10-ansible-centos8 semaphore[131271]: unknown command "/etc/semaphore/config.json" for "semaphore"
Jul 20 15:49:29 icba10-ansible-centos8 systemd[1]: semaphore.service: Main process exited, code=exited, status=1/FAILURE
Jul 20 15:49:29 icba10-ansible-centos8 systemd[1]: semaphore.service: Failed with result 'exit-code'.
Jul 20 15:49:29 icba10-ansible-centos8 systemd[1]: semaphore.service: Service RestartSec=100ms expired, scheduling restart.
Jul 20 15:49:29 icba10-ansible-centos8 systemd[1]: semaphore.service: Scheduled restart job, restart counter is at 5.
Jul 20 15:49:29 icba10-ansible-centos8 systemd[1]: Stopped Semaphore Ansible UI.
Jul 20 15:49:29 icba10-ansible-centos8 systemd[1]: semaphore.service: Start request repeated too quickly.
Jul 20 15:49:29 icba10-ansible-centos8 systemd[1]: semaphore.service: Failed with result 'exit-code'.
Jul 20 15:49:29 icba10-ansible-centos8 systemd[1]: Failed to start Semaphore Ansible UI.
Jul 20 15:51:01 icba10-ansible-centos8 systemd[1]: Started Semaphore Ansible UI.
Jul 20 15:51:02 icba10-ansible-centos8 semaphore[131322]: Error: unknown command "/etc/semaphore/config.json" for "semaphore"
Jul 20 15:51:02 icba10-ansible-centos8 semaphore[131322]: Run 'semaphore --help' for usage.
Jul 20 15:51:02 icba10-ansible-centos8 semaphore[131322]: unknown command "/etc/semaphore/config.json" for "semaphore"
Jul 20 15:51:02 icba10-ansible-centos8 systemd[1]: semaphore.service: Main process exited, code=exited, status=1/FAILURE
Jul 20 15:51:02 icba10-ansible-centos8 systemd[1]: semaphore.service: Failed with result 'exit-code'.
Jul 20 15:51:02 icba10-ansible-centos8 systemd[1]: semaphore.service: Service RestartSec=100ms expired, scheduling restart.
Jul 20 15:51:02 icba10-ansible-centos8 systemd[1]: semaphore.service: Scheduled restart job, restart counter is at 1.
[config.json.txt](https://github.com/ansible-semaphore/semaphore/files/12115802/config.json.txt)

**Comment by ansibleguy** [comment]
Greetings!

It does seem to me you are lacking the '--config' flag before the config file.
Can you provide the content of your Systemd service?

You command should look like this:
```
semaphore service --config /etc/semaphore/config.json
```

\- AnsibleGuy

**Comment by Ijoezl** [comment]
Hi Ansibleguy,

I already changed the line as you provided. It seems like the unknown command no longer can be seen in the logs. But still unable to make semaphore service up. I just changed the semaphore.service content for 'restart=no' due to its stuck at restarting loop. But still cannot be up. Please refer to image and txt attached.

![semaphore service](https://github.com/ansible-semaphore/semaphore/assets/140132840/713cf200-359e-4c5d-9d19-3c557881e07b)
![semaphore status](https://github.com/ansible-semaphore/semaphore/assets/140132840/d88a315b-0fe1-427c-965e-26d61bde9b1a)
[semaphore log.txt](https://github.com/ansible-semaphore/semaphore/files/12121774/semaphore.log.txt)

**Comment by ansibleguy** [comment]
Greetings!

Here is how I successfully run it:

```
[Unit]
Description=Ansible Semaphore
Requires=network.target mariadb.service

ConditionPathExists=/usr/bin/semaphore
ConditionPathExists=/etc/semaphore/config.json

Documentation=https://docs.ansible-semaphore.com/

[Service]
ExecStart=/usr/bin/semaphore service --config /etc/semaphore/config.json
ExecReload=/bin/kill -HUP $MAINPID
Restart=on-failure
RestartSec=10s

# I encountered some errors when the expected language isn't set
Environment=LANG="en_US.UTF-8"
Environment=LC_ALL="en_US.UTF-8"

### Would be recommended to use a serviceuser:
# User=semaphore
# Group=semaphore

### If logs should be sent to syslog
# StandardOutput=journal
# StandardError=journal
# SyslogIdentifier=semaphore

[Install]
WantedBy=multi-user.target
```
Source: https://github.com/ansibleguy/sw_semaphore/blob/latest/templates/etc/systemd/system/semaphore.service.j2

I commented out the optional parts.

After changing the config:

```bash
systemctl daemon-reload
systemctl stop semaphore.service
systemctl start semaphore.service
```

BTW: Please copy config as text - not images. (:

\- AnsibleGuy

**Comment by tboerger** [comment]
As you can see on https://github.com/ansible-semaphore/semaphore/blob/1834c6ebcbb3f867a598b4d6a12db53c385f01e5/deployment/systemd/semaphore.service#L7 you are using a wrong start command
