### ISSUE TITLE
Error: "Request failed with status code 403"

### ISSUE THREAD

**Issue by don-rumata** [ansible-semaphore/semaphore#1364]
Hi, in the latest version of semaphore I can't save the inventory

`apt show semaphore `

```yaml
Package: semaphore
Version: 2.8.92
```

`lsb_release --all`

```
LSB Version:    core-11.1.0ubuntu2-noarch:printing-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal
```

https://imgur.com/a/ojI8L9S

What other information do you need?

**Comment by ansibleguy** [comment]
Seems to be the same issue as: https://github.com/ansible-semaphore/semaphore/issues/1433

**Comment by don-rumata** [comment]
In `2.9.37` - no problem.
