### ISSUE TITLE
Cannot create anything after changes in the GUI

### ISSUE THREAD

**Issue by Laz80UK** [ansible-semaphore/semaphore#137]
After compiling the latest code, I get an
`error, could not add key:400 `
message whenever I try to add anything other than a task template.
I can also see HTTP code 400 on the console, but nothing more verbose.

**Comment by matejkramny** [comment]
Does it return anything in the body?

**Comment by Laz80UK** [comment]
I can see the errors in the GUI, e.g. "Erorr" "Inventory not added: 400".
(There is also a typo in Error :))

The executable provides the following on the console:
`[GIN] 2016/06/22 - 17:24:45 | 400 |    6.801296ms | 10.2.0.90 |   POST    /api/project/2/inventory`

Other than that, nothing. Anywhere else I can check?
Many thanks.

**Comment by matejkramny** [comment]
Sorry for the delay. What does the browser send?

It seems like something is empty (and required) or a different type (go is a bit sensitive on this subject)

**Comment by seidzade** [comment]
hi 

I have the same issue , thats what browser sends as result of any "add" request 

![2016-06-27_14-08-16](https://cloud.githubusercontent.com/assets/13468079/16377798/c55628f4-3c70-11e6-9b90-af8d9bec6f9f.png)


Any idea what can be done to understand what is the issue ?

**Comment by matejkramny** [comment]
This is dup #142
