### ISSUE TITLE
Request: Retrieve task status via API

### ISSUE THREAD

**Issue by Laz80UK** [ansible-semaphore/semaphore#138]
Could you please add a function to the API to retrieve the current status of a task?
Something similar as the task output is available now.
It's pretty easy to do, but would be very useful for time consuming jobs.
Many thanks.

**Comment by matejkramny** [comment]
Ok. Will be added.

**Comment by twhiston** [comment]
@strangeman would you be interested in taking this one?

**Comment by gcavalcante8808** [comment]
Have you guys created the openapi/swagger specification ?

Maybe I can help with it.

2018-03-19 20:07 GMT-03:00 Tom Whiston <notifications@github.com>:

**Comment by twhiston** [comment]
@gcavalcante8808 no, but feel free to propose something, this one should be super easy as it just takes a task id and returns the task status

**Comment by strangeman** [comment]
I checked this out and found that we already can get the task status via `/tasks/{task_id}` endpoint. No need to implement separate endpoint for status, I think.

![2018-03-29-193308_1366x768_scrot](https://user-images.githubusercontent.com/1083576/38081731-13d1b81c-3388-11e8-8e3f-d497d82a98f6.png)

**Comment by twhiston** [comment]
yeah if it is in there then people can extract the value they need on their side and we don't need a new endpoint. Nice. Closing this
