### ISSUE TITLE
config.json with docker

### ISSUE THREAD

**Issue by ksrdl** [ansible-semaphore/semaphore#1382]
Hello,

Is it possible to use the config file config.json with a docker instance ?

Kélian

**Comment by lafayetteduarte** [comment]
Yep . 
I wrote some examples last week on configuring openid that uses a config mapped to the docker container.
You can see the example on this fork:
https://github.com/lafayetteduarte/semaphore/tree/develop/examples/openid/keycloak

**Comment by ansibleguy** [comment]
You should be able to map the file using a docker-volume.
Semaphore is started using the `/etc/semaphore/config.json` file: https://github.com/ansible-semaphore/semaphore/blob/develop/deployment/docker/prod/Dockerfile#L32

**Comment by ksrdl** [comment]
Thanks @lafayetteduarte @ansibleguy, i'll try this :)
