### ISSUE TITLE
Execute ansible in a pyevn

### ISSUE THREAD

**Issue by OliPou** [ansible-semaphore/semaphore#1397]
Hello team,

I try to find it the documentation, but I might miss it. Is it a way to execute ansible semaphore inside of pyenv ?

Regards,

**Comment by ansibleguy** [comment]
Greetings!

It is covered in the [manual installation docs](https://docs.ansible-semaphore.com/administration-guide/installation_manually#python3)

**Comment by OliPou** [comment]
Am I not really understand everything but how do I make my ansible semaphore pointing to my virtualenv ?

**Comment by ansibleguy** [comment]
One needs to `activate` it first.
Here you can see how to do so in a systemd-service: https://docs.ansible-semaphore.com/administration-guide/installation_manually#python-modules-in-virtualenv

`source /home/semaphore/venv/bin/activate && /usr/bin/semaphore service --config /etc/semaphore/config.json`
