### ISSUE TITLE
Contrib : sample systemd semaphore.service

### ISSUE THREAD

**Issue by philippelecoq** [ansible-semaphore/semaphore#140]
Create file /etc/systemd/system/semaphore.service

---

[Unit]
Description=ansible-semaphore
After=syslog.target
Requires=network.target

[Service]
Type=forking
User=ansible
ExecStart=/bin/sh -c '/usr/bin/semaphore -config  /var/lib/semaphore/semaphore_config.json >> /var/log/semaphore.log 2>&1 &'
Restart=always
RestartSec=8s

[Install]
WantedBy=multi-user.target

---

systemctl enable semaphore
systemctl start semaphore
systemctl status semaphore

**Comment by matejkramny** [comment]
Thanks for this.

This could be added to the setup process. User could pick between `launchctl`, `upstart`, so on..

**Comment by nwlucas** [comment]
I modified the above to be a bit more configurable. This is what I have in use on a staging server:

 /etc/systemd/system/semaphore.service
```shell
[Unit]
Description=Ansible Semaphore
After=syslog.service
Before=nginx.service
Requires=network.target


[Service]
Type=forking
EnvironmentFile=-/etc/default/ansible-semaphore
ExecStart=/bin/sh -c "/usr/bin/semaphore -config ${SEMAPHORE_CONFIG} >> ${SEMAPHORE_LOGS} 2>&1 &"
Restart=always
RestartSec=10s

[Install]
WantedBy=multi-user.target
```


And the accompanying /etc/default/ansible-semaphore
```shell
#Ansible Semaphore Defaults

SEMAPHORE_CONFIG=/data/ansible-semaphore/semaphore_config.json
SEMAPHORE_LOGS=/var/log/semaphore.log

```

**Comment by philippelecoq** [comment]
User=ansible  (or other user name) is very important.
Running ansible with root is not recommended.


Philippe


-------- Message d'origine --------
De : Nigel Williams-Lucas <notifications@github.com> 
Date :27/06/2016  17:27  (GMT+01:00) 
A : ansible-semaphore/semaphore <semaphore@noreply.github.com> 
Cc : "www.MyPiDrone.com" <philippe.le-coq@laposte.net>, Author <author@noreply.github.com> 
Objet : Re: [ansible-semaphore/semaphore] Contrib : sample systemd
  semaphore.service (#140) 

I modified the above to be a bit more configurable. This is what I have in use on a staging server:

/etc/systemd/system/semaphore.service

[Unit]
Description=Ansible Semaphore
After=syslog.service
Before=nginx.service
Requires=network.target


[Service]
Type=forking
EnvironmentFile=-/etc/default/ansible-semaphore
ExecStart=/bin/sh -c "/usr/bin/semaphore -config ${SEMAPHORE_CONFIG} >> ${SEMAPHORE_LOGS} 2>&1 &"
Restart=always
RestartSec=10s

[Install]
WantedBy=multi-user.target
And the accompanying /etc/default/ansible-semaphore

#Ansible Semaphore Defaults

SEMAPHORE_CONFIG=/data/ansible-semaphore/semaphore_config.json
SEMAPHORE_LOGS=/var/log/semaphore.log

**Comment by twhiston** [comment]
I dont really see the need for an environment file here, the config should be in /etc/semaphore and the logs will be written to journald, which for sure you have if you have systemd installed, so its best not to subvert that process. I also would not add, by default the nginx service to systemd as you may use any number of other web servers instead. Also totally agree with philippelecoq about the username. Never run this as a service with root!

That being said a systemd file in the project needs to happen and will be in the next release.
