### ISSUE TITLE
Unable to send email due to the error "Can't send email!"

### ISSUE THREAD

**Issue by Jaryllan** [ansible-semaphore/semaphore#1412]
I check in the historical issue that this was being fixed. But I am still unable to send the email due to the error "Can't send email!".
Source: #880  

In the log it has the following error.
ERRO[0145] 504 5.7.4 Unrecognized authentication type [SI2PR02CA0049.apcprd02.prod.outlook.com 2023-08-11T06:21:58.062Z 08DB99B4BF579D54]
PANI[0145] 504 5.7.4 Unrecognized authentication type [SI2PR02CA0049.apcprd02.prod.outlook.com 2023-08-11T06:21:58.062Z 08DB99B4BF579D54]  error="Can't send email!"

Would like to know what causes this issue, or any other configuration that can be configured other than the config.json?

**Comment by ansibleguy** [comment]
Just linking - might be related to: https://github.com/ansible-semaphore/semaphore/issues/1360

**Comment by tboerger** [comment]
After merging My PR https://github.com/ansible-semaphore/semaphore/pull/1788 have been merged which fixes this issue. the mail notification is working fine if the config.json includes all mentioned options and after enabling alerts for your user.

**Comment by yschulz** [comment]
I am quite confused, I have just tried to enable email alerts with office365 and face the same issue. Running latest release v2.10.22 and verified I can send emails via swaks from the same docker network.

I thought this would be fixed, but then I saw issue #1086, which is open but far older. Would you be so kind to clarify @tboerger if this is an open issue or an issue on my end?
