### ISSUE TITLE
Permission Denied Could not read from remote repository

### ISSUE THREAD

**Issue by herlit** [ansible-semaphore/semaphore#1425]
Hi,
I'm trying to use semaphore to connect to github. Semaphore works great with my local repo. But with github  i get this error:

Task 38 added to queue
Preparing: 38
Prepare TaskRunner with template: install netcat
Cloning Repository git@20.201.28.152:herlit/semaphore
Cloning into 'repository_3_4'...
Warning: Permanently added '[20.201.28.152]:443' (ED25519) to the list of known hosts.
Load key "/opt/semaphore/access_key_269663495": error in libcrypto
git@20.201.28.152: Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists. Failed updating repository: exit status 128

I tried to manually clone the repo and succeeded. This works: git clone git@20.201.28.152:herlit/semaphore

This also works and I get aunthenticated: ssh -vT git@20.201.28.152(this is github.com. I don't know why but it doesn't work with the domain name)

This is the output of: ssh -vT -i /home/semaphore/.ssh/id_ed25519.pub git@20.201.28.152

OpenSSH_8.9p1 Ubuntu-3ubuntu0.3, OpenSSL 3.0.2 15 Mar 2022
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: Reading configuration data /etc/ssh/ssh_config.d/04-ipa.conf
debug1: Executing command: 'true'
debug1: /etc/ssh/ssh_config line 20: Applying options for 20.201.28.152
debug1: /etc/ssh/ssh_config line 23: Applying options for *
debug1: Executing proxy command: exec /usr/bin/sss_ssh_knownhostsproxy -p 443 20.201.28.152
debug1: identity file /home/semaphore/.ssh/id_ed25519.pub type 3
debug1: identity file /home/semaphore/.ssh/id_ed25519.pub-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.9p1 Ubuntu-3ubuntu0.3
debug1: Remote protocol version 2.0, remote software version babeld-9ff4dbf2
debug1: compat_banner: no match: babeld-9ff4dbf2
debug1: Authenticating to 20.201.28.152:443 as 'git'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ssh-ed25519
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: SSH2_MSG_KEX_ECDH_REPLY received
debug1: Server host key: ssh-ed25519 SHA256:+DiY3wvvV6TuJJhbpZisF/zLDA0zPMSvHdkr4UvCOqU
debug1: Host '[20.201.28.152]:443' is known and matches the ED25519 host key.
debug1: Found key in /home/semaphore/.ssh/known_hosts:4
debug1: rekey out after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey in after 134217728 blocks
debug1: Will attempt key: /home/semaphore/.ssh/id_ed25519.pub ED25519 SHA256:fF+gU0rESVoT4GDDA+vrWhkPOptmNtpqW/vHE/Xkj/E explicit
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp256-cert-v01@openssh.com,sk-ssh-ed25519-cert-v01@openssh.com,sk-ecdsa-sha2-nistp256-cert-v01@openssh.com,rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,sk-ssh-ed25519@openssh.com,sk-ecdsa-sha2-nistp256@openssh.com,ssh-ed25519,ecdsa-sha2-nistp521,ecdsa-sha2-nistp384,ecdsa-sha2-nistp256,rsa-sha2-512,rsa-sha2-256,ssh-rsa>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Offering public key: /home/semaphore/.ssh/id_ed25519.pub ED25519 SHA256:fF+gU0rESVoT4GDDA+vrWhkPOptmNtpqW/vHE/Xkj/E explicit
debug1: Server accepts key: /home/semaphore/.ssh/id_ed25519.pub ED25519 SHA256:fF+gU0rESVoT4GDDA+vrWhkPOptmNtpqW/vHE/Xkj/E explicit
Load key "/home/semaphore/.ssh/id_ed25519.pub": error in libcrypto
debug1: No more authentication methods to try.
git@20.201.28.152: Permission denied (publickey).

Sorry for the long post. Any ideas? Thanks in advance
Herlit

**Comment by Richardswe** [comment]
It looks like you're using the public SSH key for Semaphore, but you need to have the public SSH on github and the private one in the keystore in Semaphore.
