### ISSUE TITLE
FR: show date+time instead of humanized

### ISSUE THREAD

**Issue by steadfasterX** [ansible-semaphore/semaphore#1448]
## setup

- semaphore: non-docker
- version: 2.9.2 (pre-release)

## description

atm the format of when a task has started and its duration is "humanized" in a way which makes it impossible to identify when a task was **exactly(!) _started_** or what the **exact(!) _duration_** was:

![image](https://github.com/ansible-semaphore/semaphore/assets/8750713/685197d3-cdbd-47e1-9dba-0aa15b81db7f)

3 hours can be "2 hours and 34 minutes", who knows? only when you calculate start and end manually you can then identify the real duration..
Also when you want to identify an unusual duration or simply to see if the duration increases/decreases over the last runs the current output is not useful at all.

The start info "a few weeks/days/.. ago" is not very useful as well. e.g when trying to identify a specific task in hundreds of template runs and you want to investigate an issue which occurs since a specific date and time. also it will be much more easier to find when a template was executed the last time or how often etc etc. impossible atm as regardless where you look the date is nowhere mentioned at all.

## solution proposal

afaiu the code this defines that "humanized" output (for 'start' at least) somehow (sorry go+vue noob): https://github.com/ansible-semaphore/semaphore/blob/9f9606e18ac3cb7c44c070829faad678cfc5d521/web/src/main.js#L16

imho it would be fully ok to switch this globally, i.e. everywhere to date + time (imho: `YYYY-DD-MM HH:MM:SS`).

as an enhanced variant of this it might be useful letting the user choose between the displayed format (like `YYYY-DD-MM HH:MM:SS` or `2 weeks ago`) but that is more nice to have (for me) as it is more important (for me) to see the real start date+time and exact duration time..

**Comment by macau23** [comment]
The normal solution for this is to mouseover for the datetime.

**Comment by steadfasterX** [comment]
this is not a solution sorry. it takes me 1 sec to find a specific date+time and ^10 time to do it manually by mouseover every single task (having dozens per day). other then that mouseover stopped working for me a while ago (no scripts blocked but maybe still something in my setup ofc)

**Comment by fiftin** [comment]
Done in v2.10.23-beta.

**Comment by steadfasterX** [comment]
> Done in v2.10.23-beta.

looks great thanks! is there a way to set it to 24 hours clock?

**Comment by fiftin** [comment]
> looks great thanks! is there a way to set it to 24 hours clock?

Done.
