### ISSUE TITLE
Save user ID in event logs.

### ISSUE THREAD

**Issue by tokuhirom** [ansible-semaphore/semaphore#145]
[![https://gyazo.com/9327053566e3e41ca7407b1c4fc3cf32](https://i.gyazo.com/9327053566e3e41ca7407b1c4fc3cf32.png)](https://gyazo.com/9327053566e3e41ca7407b1c4fc3cf32)

I want to know who caused these events.
I suggest to add `user_id` column in `event` table.

**Comment by fiftin** [comment]
Implemented in https://github.com/ansible-semaphore/semaphore/releases/tag/v2.7.5
