### ISSUE TITLE
Error: cannot decrypt access key, perhaps encryption key was changed

### ISSUE THREAD

**Issue by Arkhenys** [ansible-semaphore/semaphore#1457]
Good afternoon, 

I just made a fresh install of Ansible Semaphore v2.9.4. 
When I run a task template, I know have an error 500 with the following log : "cannot decrypt access key, perhaps encryption key was changed" error="Cannot write new event to database"

I use mysql 8.0.33 with Semaphore. 
Both instances are docker based.

It worked previously from semaphore v2.8.90 to semaphore v2.9.2. I did not try v2.9.3 as v2.9.4 was already the latest stable release in the available releases on the semaphore releases page.

Thanks in advance for your help !

**Comment by fiftin** [comment]
Hi @Arkhenys,

Did you provide variable `SEMAPHORE_ACCESS_KEY_ENCRYPTION` to container?

**Comment by fiftin** [comment]
Is it possible that you provided `SEMAPHORE_ACCESS_KEY_ENCRYPTION` for v2.9.4 but didn't provide it for v2.8.90?

Looks like you have unencrypted data in database but Semaphore tries decrypt them with some key.

**Comment by Arkhenys** [comment]
Hi @fiftin and thanks for your quick reply. 

I'm not sure about what I did differently from previous version upgrade. 
I deploy Semaphore automatically using ansible and custom plugins so I just change the semaphore version in my inventory before each deployment. 
But you may be right I maybe had a confusion with the access key encryption.

I juste redeployed entirely the semaphore instance + the mysql container and everything seems back to normal. 
Thanks for your help, have a good day !
