### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Rev1408** [ansible-semaphore/semaphore#146]
Hi,

I have started trying ansible-semaphore. I followed the instruction in https://github.com/ansible-semaphore/semaphore. It went well and semaphore is running on port 3000.

Now the problem is, I am not sure where the node app is located, as mentioned in this article http://code-complete.com/code/?p=40
Looks like my semaphore is pointing to github, but i want it to point to my local checkout, i am not sure what and how i need to configure. The only file i see is semaphore_config.json in my playbook path.

Also when i try to run a playbook I get the below error
```
[GIN] 2016/06/27 - 17:42:40 | 200 |     235.662µs | 10.250.50.51 |   GET     /public/html/projects/createTaskModal.html
&{{25 13 waiting false   {63602646162 239381004 0x102bd60} <nil> <nil>} {0 0 0 0 0 <nil>  <nil> false} {0   <nil> <nil> <nil>} {0  0  <nil> {0   <nil> <nil> <nil>} <nil> {0   <nil> <nil> <nil>} } {0  0  0 {0   <nil> <nil> <nil>}} {0  0 <nil> } [] 1}
[1]
[GIN] 2016/06/27 - 17:42:42 | 201 |   37.933153ms | 10.250.50.51 |   POST    /api/project/1/tasks
Stopped running tasks
[GIN] 2016/06/27 - 17:42:42 | 200 |     164.044µs | 10.250.50.51 |   GET     /public/html/projects/taskModal.html
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4d9b42]

goroutine 54 [running]:
panic(0xa9f480, 0xc820010100)
        /usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:464 +0x3e6
github.com/ansible-semaphore/semaphore/routes/tasks.(*task).installKey(0xc8200d5600, 0x1, 0xc8203cbb80, 0x9, 0xc8203cbb79, 0x3, 0xc8203cbb90, 0xc8203cbba0, 0x0, 0x0, ...)
        /Users/m/p/gospace/src/github.com/ansible-semaphore/semaphore/routes/tasks/runner.go:209 +0x142
github.com/ansible-semaphore/semaphore/routes/tasks.(*task).run(0xc8200d5600)
        /Users/m/p/gospace/src/github.com/ansible-semaphore/semaphore/routes/tasks/runner.go:87 +0x571
created by github.com/ansible-semaphore/semaphore/routes/tasks.(*taskPool).run
        /Users/m/p/gospace/src/github.com/ansible-semaphore/semaphore/routes/tasks/pool.go:32 +0x1d6
2016/06/27 17:42:42 notifying bugsnag: runtime error: invalid memory address or nil pointer dereference
2016/06/27 17:42:42 bugsnag.Notify: not notifying in development
```
May be I am doing something wrong, Can you please, help me.

Thank You.

**Comment by matejkramny** [comment]
Does your ssh key have a private key?

**Comment by Rev1408** [comment]
yes, i have a private key

**Comment by matejkramny** [comment]
The panic is called from `installKey` function.

There's a ticket about this somewhere & problem is some fields in the key are empty.

Btw this isn't run on node any more (used be when the article was made).

**Comment by Rev1408** [comment]
That found the issue, I had two ssh keys, one was a bad, for some reason my task was using the bad one even thought i said to use the good one.I have to go to mysql and delete the bad keys and it works now.

Also I had this error 
panic: Error 1364: Field 'task' doesn't have a default value
I had to run SET GLOBAL sql_mode = '';
