### ISSUE TITLE
How do I set the `web_host` configuration option from docker-compose

### ISSUE THREAD

**Issue by miversen33** [ansible-semaphore/semaphore#1460]
Looking at the [configuration options](https://docs.ansible-semaphore.com/administration-guide/configuration#configuration-options), there is an option to set the `web_host` (or the URL to follow to reach the application, if I am reading [this](https://docs.ansible-semaphore.com/administration-guide/configuration#public-url) right)

```
If you use nginx or other web server before Semaphore, you should provide configuration option web_host.

For example you configured NGINX on the server which proxies queries to Semaphore.

Server address https://exmaple.com and you proxies all queries https://exmaple.com/semaphore to Semaphore.

Your web_host will be https://exmaple.com/semaphore.
```

However, when reading the [docker installation documentation](https://docs.ansible-semaphore.com/administration-guide/installation#docker) there doesn't appear to be a way to declare this variable from within a compose script. I thought maybe I could just define it myself via `SEMAPHORE_WEB_HOST` but alas, that didn't work. 

Am I missing something or is this feature not supported with the docker compose setup? If its not supported, what would the work effort be to provide that? Having the ability to specify the path to the application (without having to modify the configuration in an ephemeral container) would be great :)

**Comment by dpavle** [comment]
Try ```SEMAPHORE_WEB_ROOT```. Alternatively, you could mount a config.json file to /etc/semaphore/ and specify the web_host option there.

**Comment by miversen33** [comment]
I ended up opting to install locally as opposed to using the docker-compose installation as I was running into some weird issues such as DNS not resolving all the time, jobs taking a very long time to report status, etc.

Thank you for the answer though! I appreciate it :)
