### ISSUE TITLE
error: could not add key:400

### ISSUE THREAD

**Issue by itxx00** [ansible-semaphore/semaphore#147]
With 2.0.3 when I try to add a ssh key I got this error log : 
[GIN] 2016/06/28 - 15:58:51 | 400 |   66.499234ms | 192.168.199.210 |   POST    /api/project/1/keys

how can I debug this error ? thanks.

**Comment by matejkramny** [comment]
There's going to be an update shortly fixing this.

Sorry for inconvenience.

**Comment by docholiday** [comment]
Hi, I installed the current version 2.0.4, but I still get this error...

**Comment by gcavalcante8808** [comment]
At least in the 2.0.4 its working. Verify if you keys have the lines that
starts and close the key ( like ----- end of private key ----) or something
like that.

Im using this version of semaphore with the gcavalcante8808/semaphore
docker image.

Em 25 de out de 2016 11:44 AM, "docholiday" <notifications@github.com>
escreveu:
