### ISSUE TITLE
Roles Path not being set to the root of a repository

### ISSUE THREAD

**Issue by aaronnad** [ansible-semaphore/semaphore#1479]
Hi,

With testing semaphore v2.9.4 the tasks do not respect the root of the repository for finding roles.

My task looks like so;
![Screenshot 2023-09-11 at 15 54 04](https://github.com/ansible-semaphore/semaphore/assets/69530732/26c6dc5f-8a29-46f6-a0be-0fb157efd8c3)
So the repository is pulled down and the playbook in pb-build/deploy_semaphore.yml is then ran.

I would expect semaphore to then look in the root of the repository for the `roles` dir to check for any roles. This isn't the case and instead it attempts to look in `pb-build` or `pb-build/roles`

```log
ERROR! the role 'nsSemaphore' was not found in /tmp/semaphore/repository_2_1/pb-build/roles:/tmp/semaphore/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/tmp/semaphore/repository_2_1/pb-build

The error appears to be in '/tmp/semaphore/repository_2_1/pb-build/ansible_semaphore.yml': line 11, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:
roles:
- nsSemaphore
^ here
Running playbook failed: exit status 1
```
![Screenshot 2023-09-11 at 15 51 10](https://github.com/ansible-semaphore/semaphore/assets/69530732/ef3cc3db-5462-4c2c-b470-78810f38d684)

Should semaphore not automatically look in the root of the repo rather than the subdirs specified within? Or at least look in the root of the repo as well as? Such as in this instance it would be looking in `/tmp/semaphore/repository_2_1/roles`.

**Comment by ansibleguy** [comment]
Greetings!

This is no behavior that Semaphore is concerned with.

It is completely done by Ansible (that is the program executing the playbooks & roles).
See: [Ansible directory structure](https://docs.ansible.com/ansible/2.8/user_guide/playbooks_best_practices.html#directory-layout)

Also: Your error message is regarding your YAML syntax. You might even wan to read into the [Ansible getting started](https://docs.ansible.com/ansible/latest/getting_started/index.html) guide to get to know the tool you want to use.

I hope this can help you get started! (:
Please close the issue, as this is no Semaphore-specific issue

**Comment by aaronnad** [comment]
The error i was getting wasn't the syntax issue, it was because the role couldn't be found :).

I've since put in a custom ansible.cfg in the semaphore home directory so the custom roles we create can be found correctly.
