### ISSUE TITLE
Secret format error

### ISSUE THREAD

**Issue by ms32035** [ansible-semaphore/semaphore#1491]
Not sure what changed in the latest docker image, but suddenly all my tasks started to fail with `
Error: secret must be valid json in key 'semaphore'` That secret is an ssh key

**Comment by devedse** [comment]
Same here, I only just started using Semaphore and I am now also seeing this error:
```
Error: secret must be valid json in key
```

**Comment by aaronnad** [comment]
The latest docker image is actually a pre-release on version 2.9.21

You'll want to pin the docker tags to v2.9.4 at the moment - look at the releases tab in github.
Pinning docker images is best practice anyway to prevent things like this from happening (also makes rollbacks to known good versions easier)

**Comment by devedse** [comment]
Maybe a latest and nightly tag would work better for that.

**Comment by aaronnad** [comment]
Aye, its related to  #1490 for sure.
Hopefully a slight improvement on image tags would be best.

**Comment by fiftin** [comment]
Fixing in progress ;)

**Comment by fiftin** [comment]
Hi @ms32035 @devedse I need your help :) Do you use docker version? What version?

**Comment by fiftin** [comment]
I refactored configuration mechanism and it can have side effects.

**Comment by ms32035** [comment]
Yep. Latest tag for arm64

**Comment by devedse** [comment]
@fiftin , I think I was on [v2.9.21] or [v2.9.19] when the bug happened. I have since switched back to [v2.9.18] which works fine.

**Comment by fiftin** [comment]
@devedse yes, significant refactoring of configuration was done. All tests passed but looks like some old configs broken.

Do you use env var `SEMAPHORE_ACCESS_KEY_ENCRYPTION` ? Do you have custom `config.json` or use env vars?

**Comment by devedse** [comment]
Nope I use none of that.

**Comment by fiftin** [comment]
Hi @devedse

Please try latest pre-release, I think it will work to you: https://github.com/ansible-semaphore/semaphore/releases/tag/v2.9.36

**Comment by ms32035** [comment]
That has worked

**Comment by devedse** [comment]
I'm still seeing the same error after upgrading to [v2.9.36](https://github.com/ansible-semaphore/semaphore/releases/tag/v2.9.36):
![image](https://github.com/ansible-semaphore/semaphore/assets/2350015/65325df7-4025-450d-81e7-68b7a22fd659)
