### ISSUE TITLE
Ansible Galaxy support

### ISSUE THREAD

**Issue by jkrehm** [ansible-semaphore/semaphore#150]
Are there plans to implement support for Ansible Galaxy?

Specifically I'm interested in something like what [Tower](http://docs.ansible.com/ansible-tower/latest/html/userguide/projects.html#ansible-galaxy-support) does, so dependencies get installed automatically.

Is that something other Semaphore users would find helpful?

**Comment by jkrehm** [comment]
Awesome! Thanks guys!

**Comment by jeremieca** [comment]
Up ?

**Comment by strangeman** [comment]
@jeremieca it works as planned. You need to put `requirements.yml` file to the `roles` directory.
