### ISSUE TITLE
Issue with tasks POST API

### ISSUE THREAD

**Issue by darkweak** [ansible-semaphore/semaphore#1508]
Hello,

I can't figure out why I receive a 400 Bad request HTTP status code when I send the following payload
```
{
    "template_id": 1,
    "environment": "{\"testing\":\"that\"}",
    "project_id": 1
}
```

But it returns a 200 OK when using empty brackets
```
{
    "template_id": 1,
    "environment": "{}",
    "project_id": 1
}
```

Tried on latest v3 and latest v2

**Comment by ansibleguy** [comment]
Just to keep it clear:
Could you link the documentation you are referring to and post the full HTTP-call/-URL you are using? (stripped of host of course)

This discussion might be helpful: https://github.com/ansible-semaphore/semaphore/discussions/1228 (or not)

**Comment by darkweak** [comment]
here is the curl request
```
curl --location 'http://localhost:3001/api/project/1/tasks' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json, text/plain, */*' \
--header 'Sec-Fetch-Site: same-origin' \
--header 'Accept-Language: fr-FR,fr;q=0.9' \
--header 'Accept-Encoding: gzip, deflate' \
--header 'Sec-Fetch-Mode: cors' \
--header 'Host: localhost:3001' \
--header 'Origin: http://localhost:3001' \
--header 'Referer: http://localhost:3001/project/1/templates/1' \
--header 'Content-Length: 51' \
--header 'Connection: keep-alive' \
--header 'Sec-Fetch-Dest: empty' \
--header 'Cookie: semaphore={YOUR_SEMAPHORE_TOKEN}' \
--data '{
    "template_id": 1,
    "environment": "{\"testing\":\"that\"}",
    "project_id": 1
}'
```

I'm referring to the swagger
https://www.ansible-semaphore.com/api-docs/#/project/post_project__project_id__tasks

And I followed this comment but it doesn't work
https://github.com/ansible-semaphore/semaphore/issues/1043#issuecomment-1269835356

**Comment by darkweak** [comment]
I think the issue came from a bad Content-Length HTTP request header, it works now.
