### ISSUE TITLE
Documents should notice ansible-semaphore requires git 2.3+

### ISSUE THREAD

**Issue by tokuhirom** [ansible-semaphore/semaphore#151]
ansible-semaphore uses GIT_SSH_COMMAND environment variable.

This environment variable introduced at git 2.3. Document should notice the required version.
https://github.com/blog/1957-git-2-3-has-been-released

(Centos7's git version is 1.8.3)

**Comment by matejkramny** [comment]
note: maybe resolved if #75 gets resolved

**Comment by twhiston** [comment]
closing in favour of #75
