### ISSUE TITLE
run playbook in template with Extra CLI Arguments

### ISSUE THREAD

**Issue by unix196** [ansible-semaphore/semaphore#153]
good day. 
Inventory:
[pc]
192.168.1.[102:155]

playbook:

 hosts: "{{ pc }}"
  remote_user: root
  gather_facts: no
  tasks:
  cron: name="adjustment time" minute="05" hour="14" job="/usr/sbin/ntpdate 192.168.1.1"

I specify in playbook extra cli argument: ["-e","pc=192.168.1.116"].  Run playbook, it use host 192.168.1.116, thats OK.  Then I update extra cli argument: ["-e","pc=192.168.1.111"], run it, but playbook whatever use 192.168.1.116.

**Comment by unix196** [comment]
semaphore v 2.0.4

**Comment by twhiston** [comment]
closing due to semaphore version. If this still happens in 2.4.1 please open a new issue
