### ISSUE TITLE
When running playbook with APT thru Semaphore it fails

### ISSUE THREAD

**Issue by matus-barta** [ansible-semaphore/semaphore#1538]
Hello everyone,
I hope this is ok to post here.

I am having issues running APT playbook thru Semaphore, but when I run it in terminal it runs without issues.

The error I am getting. This looks like the apt command is not running as `sudo`.
`FAILED! => {"changed": false, "msg": "Failed to lock apt for exclusive operation: Failed to lock directory /var/lib/apt/lists/: E:Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)"}`

Here is my playbook to run updates.
```yaml
- hosts: "*"
  become: true
  tasks:
    - name: upgrade apt packages
      become: true
      apt:
        update_cache: yes
        upgrade: yes
```
When I run it in terminal I have no issues.
```bash
ansible-playbook ./playbooks/apt.yml --user admin --ask-become-pass -i ./inventory/hosts
```

**Here are my Semaphore settings**
Template:
![image](https://github.com/ansible-semaphore/semaphore/assets/9406345/47de4f4b-e786-4eb0-8444-690db7b3ea28)

Inventory (did set here sudo credentials, this should be enough?):
![image](https://github.com/ansible-semaphore/semaphore/assets/9406345/37bdf5b6-544a-49f8-ae0d-0da4010febbd)

In key store, I have my SSH keys for GitHub repo and for the machine for running the playbooks from terminal. And the sudo login.

**My troubleshooting steps:**
- updated the Semaphore docker container
- somewhere I saw to add become to the task and playbook, so tried that
- checked if this playbook runs in terminal with `ansible-playbook`
- tested my credentials and updated the sudo login in Semaphore just in case I mistyped it first time

Honestly I am lost, I can't find anything related to this regarding the Semaphore side. Just ansible or running it in terminal manually.

I am sure I just didn't tick some small setting somewhere but I just dan't find it.

Thank you for help.

**Comment by DevAlphaKilo** [comment]
```
-u <REMOTE_USER>, --user <REMOTE_USER>
connect as this user (default=None)
```

Initial thought is when you're using the terminal you're including ` --user admin` but the Semaphore server is attempting to connect to the target host using the **sempahore** user. Is your target host setup to use the **semaphore** user for the desired goal? If not, you can add this user to your target host, or configure the Semaphore server to use a different user when logging in.

#### Possible Solution

By default, Semaphore attempts to connect using the **semaphore** user. 
 
Try including `ansible_ssh_user`  **or** `ansible_user` in either your Semaphore environment file, or related **group_vars** file for the target host. **_Both are not required._**

![image](https://github.com/ansible-semaphore/semaphore/assets/44307521/d9701c52-e2c0-4478-9cb6-7a4402af24ce)

If you need to set different users for separate hosts using the same environment file you can use the **group_vars** schema to set this variable across separate groups. 

Why did I include both in the example? Good question.

![image](https://github.com/ansible-semaphore/semaphore/assets/44307521/f7c5292c-77ea-4b39-8f54-e6c64309ad58)

`ansible --version`

Determine which version of Ansible you're using, _hopefully > 2.0_, and update your configs to match. 

**Documentation:**

https://docs.ansible.com/ansible/latest/cli/ansible-playbook.html
https://docs.ansible.com/archive/ansible/2.4/intro_inventory.html

**Comment by Kimbaras** [comment]
Hey!

I'm having the same issue, but I suspect it's something more "general".

While troubleshooting a bigger playbook (with which I run into issues on commands / actions which require sudo privileges) I tried to run a simple "apt update" playbook, which resulted in the same error reported here.
I then tried to run an even simpler playbook, which creates two files on the remote client, both created by a command task running a simple "touch" command.

The first file (running under a regular user) works flawlessly (so it's not a login / ssh problem), the second running as "sudo touch" simply hangs indifinetely.
So seems the "become" part is pretty much ignored or currently it's not working. Maybe it's related to [this issue](https://github.com/ansible-semaphore/semaphore/issues/1518)?

My installation:
- Ubuntu 22.04
- Semaphore 2.9.37 (manual installation through the releases .deb file
- Ansible 2.15.4 

PS: while I encountered the same error as the original post, it's not my principal problem, so not sure if you prefer me to open a dedicated issue.

Thanks!

**Comment by matus-barta** [comment]
@DevAlphaKilo thank you for suggestion, I tried it, but didn't help.

@Kimbaras your description of the issue describes exactly it's behavior, I can run non sudo playbooks without issues but when playbook has become command it just ignores it (at least it look like it).

I will follow the issue #1518 and will hope fix will come soon.
