### ISSUE TITLE
Release candidates

### ISSUE THREAD

**Issue by dusatvoj** [ansible-semaphore/semaphore#1541]
Hello,
This project is great and I hope it will have long life.

I found out that you have pretty tricky versioning. Have you ever thought about using release candidates for testing? (not just fixup versions until there's stable enough to be labeled as release)

Thank you

**Comment by fiftin** [comment]
Hi @dusatvoj 
currently we have `-beta` versions. But now we starting use semantic versioning with `-rc`.
