### ISSUE TITLE
RBAC Privilege Escalation

### ISSUE THREAD

**Issue by DevAlphaKilo** [ansible-semaphore/semaphore#1542]
Hello again! Loving the product, keep up the great work!!

## Problem

When experimenting with the implemented RBAC roles it was determined that my test user **Bob**, when assigned the role of **Manager** can promote himself to the **Owner** role un-expectedly. The user is confirmed **not an admin**, only the **external** box is checked for this user. In theory this user should only be able to demote themselves to a lesser role.

This does not follow traditional RBAC models, as users should not be able to escalate their privileges un-intendedly.

Not sure if this has been upgraded in subsequent versions but I am stuck on **v2.9.4** due to related LDAP bug #1522 

## System Setup

**Type:** Docker Image
**Version:** 2.9.4

## Reproduction

1. Create new user (Local or LDAP, doesn't matter) ***I used LDAP.***
2. Login w/ new user to create user entry into the backend system
3. Logout as new user
4. Login as project owner
5. Assign new user to project as manager
6. Logout as project owner
7. Login as new user
8. Navigate to project assigned as manager
9. Go to Team settings
10. Promote yourself to owner, you've been working hard. 🥳

**Comment by suptower** [comment]
Duplicate #1459

**Comment by DevAlphaKilo** [comment]
Looks like this is a duplicate of #1459 as described above, closing.
