### ISSUE TITLE
Invalid value for DEFAULT_GATHERING

### ISSUE THREAD

**Issue by oyearunpal** [ansible-semaphore/semaphore#1545]
On running playbook getting below error

**ERROR: Invalid value "False" for configuration option "setting: DEFAULT_GATHERING ", valid values are: implicit, explicit, smart**

Here is full message

```
6:34:39 PM
Task 2147483632 added to queue
6:34:42 PM
Started: 2147483632
6:34:42 PM
Run TaskRunner with template: Ping
6:34:42 PM
Preparing: 2147483632
6:36:52 PM
Warning: Permanently added 'xxx.xx.xx' (ED25519) to the list of known hosts.
6:36:53 PM
From xxx.xx.xx:devops/iaac
6:36:53 PM
* [new branch] semaphore -> origin/semaphore
6:36:53 PM
Updating Repository git@xxx.xxx.xx:devops/iaac.git
6:39:04 PM
Warning: Permanently added 'xxx.xx.xx' (ED25519) to the list of known hosts.
6:39:04 PM
From xxx.xx.xx:devops/iaac
6:39:04 PM
* branch semaphore -> FETCH_HEAD
6:39:04 PM
Updating 167ac7c..0a92c06
6:39:04 PM
Fast-forward
6:39:04 PM
ansible/playbooks/general/get_hostname.yml | 1 +
6:39:04 PM
1 file changed, 1 insertion(+)
6:39:04 PM
No collections/requirements.yml file found. Skip galaxy install process.
6:39:04 PM
No roles/requirements.yml file found. Skip galaxy install process.
6:39:04 PM
ERROR: Invalid value "False" for configuration option "setting: DEFAULT_GATHERING ", valid values are: implicit, explicit, smart
6:39:04 PM
Running playbook failed: exit status 5
```

**Comment by DevAlphaKilo** [comment]
This is an issue with your `ansible.cfg` file.

As indicated by the error, **false** is not an acceptable option for the **gathering** key in `[default]`. 

Options are to replace **false** with one of the valid options, or remove/comment out the line in the config file.

`valid values are: implicit, explicit, smart`

```
[default]
...
# smart - gather by default, but don't regather if already gathered
# implicit - gather by default, turn off with gather_facts: False
# explicit - do not gather by default, must say gather_facts: True
gathering = explicit
```

Correcting the bad value should fix your issue.

**Comment by oyearunpal** [comment]
Thanks, it resolved the issue. 

However I also want to know why it took so much time to run a playbook. If you see in above logs it took 

2.10mins in 'Preparing: 2147483632'
2.11mins in 'Updating Repository git@xxx.xxx.xx:devops/iaac.git'

**Comment by oyearunpal** [comment]
The issue of 'taking too much time to run a playbook' is also resolved.

I resolved it by installing semaphore UI via https://docs.ansible-semaphore.com/administration-guide/installation#docker where as previously I was doing from https://hub.docker.com/r/semaphoreui/semaphore

Note sure if it gets resolved by changing db from boltDB to postgres
