### ISSUE TITLE
Is JetPorch support in the roadmap?

### ISSUE THREAD

**Issue by philtreF** [ansible-semaphore/semaphore#1567]
Hi, 

Is https://www.jetporch.com in the roadmap or would that be completely out of scope? 

Fred

**Comment by ramiuslr** [comment]
Unfortunately it looks like *JetPorch* development is now discontinued.
Michael DeHaan announced his decision a few weeks ago.

Website and SourceHut instances are down, only a read-only Github mirror remains.

**Comment by tboerger** [comment]
Project is dead, closing this issue.
