### ISSUE TITLE
Email alerts for docker images don't work anymore

### ISSUE THREAD

**Issue by techsolo12** [ansible-semaphore/semaphore#1571]
Hello guys,

after the update from 2.9.23 to 2.9.37 the email notifications for docker images don't work anymore.
When a task failed no email alert or something else is shown in the task window.

Also no logs will be shown in container.
It seems that the container don't do nothing in background after the task failed.
I also tested the two images after 2.9.37 but there the issue also apear.
I wish i can post logs but there are no entry that show anything to relate to this issue.

**Comment by Menschomat** [comment]
I am facing this problem, too. Is 2.9.23 the last working version?

**Comment by tboerger** [comment]
You need to enable alerts for your user, otherwise there are no email alerts for failed tasks are sent.

Beside that I have done some fixing related to required headers for email alerts within #1788

**Comment by techsolo12** [comment]
@tboerger i also have enabled email alters at user settings. With you fix it still wouldn't work for me.

config.json, with the same settings in docker-compose.yml
```
"email_alert": true,
"email_secure": true,
"email_sender": "ansible@domain.tld",
 "email_host": "smtp.mailserver.tld",
 "email_port": "465",
 "email_username": "admin@domain.tld",
 "email_password": "password",
```
