### ISSUE TITLE
Error in semaphoreui/semaphore docker container "Failed to find required executable \"rsync\" in paths: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

### ISSUE THREAD

**Issue by antonio-pon** [ansible-semaphore/semaphore#1588]
When a run playbook by semaphore UI (in docker container) that error occure: "(fatal: [kl-test-redos]: FAILED! => {"changed": false, "msg": "Failed to find required executable \"rsync\" in paths: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"})"
This playbook contain task with ansible.posix.synchronize which use rsync. I connect to semaphore container and can't find rsync (which rsync give empty result). Please, add rsync to official docker container in dockerHub.

**Comment by derpedda** [comment]
Same here for me, also not able to add through apk at runtime
EDIT: should be addressed in #1564 and commit 965d503, though in the current develop-branch Docker-image it does not seem to have made it into the dev image with the new runner setup

**Comment by tboerger** [comment]
In the meantime there should be a release that includes rsync.
