### ISSUE TITLE
Add oidc env variable

### ISSUE THREAD

**Issue by Ereaey** [ansible-semaphore/semaphore#1593]
I propose adding an environment variable for configuration.

I am wondering if it is possible to add env variables for the oidc configuration.
In particular the secret_client_id which allows me to have a stable configuration and a secret_client_id variable depending on the deployment

Thanks !

**Comment by zarinbal** [comment]
Given the completion of the ticket regarding OIDC environment variables in Semaphore, I'm seeking the specific names of these variables for configuring OIDC. 

Despite thorough searches through the documentation and source code, especially within the semaphore-wrapper file located at (https://github.com/ansible-semaphore/semaphore/blob/develop/deployment/docker/common/semaphore-wrapper), I have been unable to find them. Could you assist in identifying these variables or direct me to where I might find this information in the project's resources?

**Comment by tboerger** [comment]
I think this doesn't exist yet... But I'm trying to resolve that.

**Comment by fiftin** [comment]
@zarinbal we added ability to use OIDC `client_id` and `client_secret` from separate files. You can use following configuration for this:

```
"oidc_providers": {
   "gitlab": {
       "display_name": "GitLab",
       "provider_url": "https://gitlab.com",
       "redirect_url": "http://localhost:4000/api/auth/oidc/gitlab/redirect",

       // What you need:
       "client_id_file": "/path/to/the/id/file",
       "client_secret_file": "/path/to/the/secret/file",
   }
}
```

**Comment by zarinbal** [comment]
@fiftin 
Thanks for your response. I understand in the context of config file we can set it. However, I am asking for the docker environment variables and it seems there is no way to set the oidc_providers through the docker environment variables.

**Comment by tboerger** [comment]
I'm on it... Be patient and give me some time :)

**Comment by RoboMagus** [comment]
Can this issue be re-opened until the support for OIDC configuration through environment variables is both fully implemented and documented?

**Comment by fiftin** [comment]
@RoboMagus do you have idea how to implement this?

**Comment by bakito** [comment]
This module could help here.
https://github.com/caarlos0/env/

It allows parsing env vars with dynamic prefixes.

`env.ParseWithOptions(&replicas[i], env.Options{Prefix: "foo"})`

**Comment by RoboMagus** [comment]
> @RoboMagus do you have idea how to implement this?

Not quite, but seeing as @tboerger has mentioned they're working on it I'm expecting the feature to be added. 
Bu the feature is as of yet not available so I think this issue should be re-opened until it is.

**Comment by tboerger** [comment]
It's not that easy as initially thought, the map is difficult to translate to proper environment variables.

**Comment by deadnews** [comment]
Why is this issue closed?

Configuration via `config.json` doesn't seem like a good fit for deployment via `ansible` + `docker compose`.

* The cogfig has auto-generated values that you don't know in advance. For example:
```json
  "cookie_hash": "***",
  "cookie_encryption": "***",
  "access_key_encryption": "***",
```

(I don't know why this is in the config).

* As I understand it, the application can change the config from the Web UI. These changes will be overwritten when the application is re-deployed.

**Comment by rkkotnik** [comment]
Is there any way to pass this ENVs now? Still havent found the solution. Would be nice to use SSO in my SemaphoreUI.

**Comment by xMacJ** [comment]
Is there any updates on using OIDC env variables in the compose file?

**Comment by grunt009** [comment]
Looks like this is being worked on here #2324

**Comment by e36Alex** [comment]
I am also waiting for this. Great you are already working on it!
