### ISSUE TITLE
Missing To header in email alert causes email being caught by antispam

### ISSUE THREAD

**Issue by xnilsit** [ansible-semaphore/semaphore#1603]
When testing email notifications I noticed, that my spam filter complained about the missing To header.

After investigating I noticed, that th To header was indeed not implemented.

https://github.com/ansible-semaphore/semaphore/blob/85d9936082bc8a3fc763ff8d3f1f6a6695bfc956/services/tasks/alert.go#L13-L17

I fixed it in my fork and will create a pull request, so it can be merged if you approve of the changes.

**Comment by tboerger** [comment]
My PR https://github.com/ansible-semaphore/semaphore/pull/1788 have been merged which fixes this issue.
