### ISSUE TITLE
custom inventory script support

### ISSUE THREAD

**Issue by tokuhirom** [ansible-semaphore/semaphore#161]
Ansible Tower supports custom inventory script.
http://docs.ansible.com/ansible-tower/latest/html/administration/custom_inventory_script.html

Can ansible semaphore support similar feature?

**Comment by tokuhirom** [comment]
Note: Running user scripts on ansible semaphore may break ansible semaphore host.

**Comment by twhiston** [comment]
Related to #47

**Comment by danielskowronski** [comment]
Do you have any started work implementing this, so I could help, or do I just need to fork and create a feature from scratch?

**Comment by fiftin** [comment]
Hi @danielskowronski, from scratch

**Comment by danielskowronski** [comment]
OK, thanks. I'll take a look and try to implement this.

For other users who struggle with that - I have a small workaround which suits my needs, maybe you'll find it useful. I've set up crontab on a server with Semaphore that executes dynamic inventory script and saves as file on disk, which Semaphore can access. 
It may not work for cloud environments which provision nodes very often but in my case I have an internal service that acts as database for Ansible inventory and exposes API.

**Comment by jdhayes** [comment]
I use a Python script for the `hosts` file within my Ansible project, works fine with Semaphore.
The script itself access my Cobbler database via an API and returns a list of systems and groups.
This could be modified (heavily) to collect from any source (Google, AWS, etc).

Here is a Cobbler example:
    https://raw.githubusercontent.com/ansible-community/contrib-scripts/main/inventory/cobbler.py
The above seems a bit complex to me, so I use a much more watered down version.

Here are some references to some other examples (ie. OpenStack):
    https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/user_guide/intro_dynamic_inventory.rst

**Comment by jdhayes** [comment]
Even more examples:
https://github.com/alibaba/ansible-provider-docs/tree/master/contrib/inventory

**Comment by tboerger** [comment]
Custom inventories are already supported by the `file` implementation where you can write anything into it.
