### ISSUE TITLE
CRON not working

### ISSUE THREAD

**Issue by Jarod2801** [ansible-semaphore/semaphore#1610]
Hi,

I got ansible and semaphore installed on a Ubuntu 22.04 VM.

Semaphore version: v2.8.75
Ansible version: core 2.15.5

I created a task template which should run every 2 minutes (just for testing, will be weekly later)
When I run the task manually, everything works fine.
But looks like the CROn settings are not respected as the task doesn't run every 2 minutes.

![image](https://github.com/ansible-semaphore/semaphore/assets/10256277/e8ff516d-5b2b-4261-a1d2-f2951221d336)

Am I doing something wrong?

**Comment by uelibo** [comment]
Hi,
*/2 0 * * * means every 2 minutes when the hour is 0, without restricting the hour use this:
*/2 * * * *

For weekly use something like this:
0 5 * * 1 means 5:00 AM on mondays (1)

**Comment by Jarod2801** [comment]
Thanks @uelibo ,

thaqt was the solution! Works fine now.

Thank you very much!

**Comment by oussjarrousse** [comment]
cron is not in the documentation by the way
