### ISSUE TITLE
OIDC with Github

### ISSUE THREAD

**Issue by Alex-Giaquinto** [ansible-semaphore/semaphore#1618]
Not sure if this is the right place for this, but does anyone have a working example of how to set up OIDC authentication with Github? I saw that it is working on the demo provided in the README, but having trouble getting it up on my end. I just upgraded to version 2.9.37, the button appears when I add the OIDC config to the config.js according to the documentation. But when I click the button the page just basically refreshes and I am back on the login screen. If anyone has an idea it would be super helpful!!! Thank you!

**Comment by hmoffatt** [comment]
Have you configured Semaphore to use a path in the web root by any chance? ie xyz.com/semaphore instead of just xyz.com?

**Comment by Alex-Giaquinto** [comment]
@hmoffatt I don't believe so. Is there any specific snippet of the config you would like to see? Maybe can help lead you in the right direction?

**Comment by hmoffatt** [comment]
I only asked because I noticed that OpenID Connect login is broken when you use a path component. I fixed this in https://github.com/ansible-semaphore/semaphore/pull/1572

I have not tried using OIDC with GitHub so I don't think I can offer any help otherwise.

**Comment by fiftin** [comment]
Yes, I have:

```
        "oidc_providers": {

                "github": {
                        "icon": "github",
                        "display_name": "Sign in with GitHub",
                        "client_id": "***",
                        "client_secret": "***",
                        "redirect_url": "https://cloud.ansible-semaphore.com/api/auth/oidc/github/redirect",
                        "endpoint": {
                                "auth": "https://github.com/login/oauth/authorize",
                                "token": "https://github.com/login/oauth/access_token",
                                "userinfo": "https://api.github.com/user"
                        },
                        "scopes": ["read:user", "user:email"]
                },

        }
```
