### ISSUE TITLE
is it possible to assign runner to one or more projects?

### ISSUE THREAD

**Issue by fatihusta** [ansible-semaphore/semaphore#1624]
I have different datacenters. All locations just can access to repo and semaphore. So I want to assign semaphore runner to specific project (s). Is it possible?

**Comment by pdcar** [comment]
+1 for this ability

**Comment by Pampei** [comment]
+1 for this ability

**Comment by mhixon4479** [comment]
+1 for this

**Comment by tboerger** [comment]
Please stop these +1 comments. Use the thumbs up emoji for the feature request or simply subscribe to the feature request.

**Comment by tboerger** [comment]
AFAIK you can't assign runners to projects, but this totally makes sense.

**Comment by Hexa-Bytes** [comment]
Any news on this, please ?

**Comment by fiftin** [comment]
The feature available in [Pro](https://semaphoreui.com/pro) version.
