### ISSUE TITLE
AWS Dynamic inventory

### ISSUE THREAD

**Issue by albruz** [ansible-semaphore/semaphore#163]
I can't select AWS dynamic inventory in the inventory type.
How can i do? There is a way to pass the ec2.py script?
Thank you

**Comment by nigeldaniels** [comment]
@albruz did you ever find a solution?

**Comment by albruz** [comment]
Unfortunately no..the only way to find and use the ec2 instances is to set the TAG variable in the environment

**Comment by nigeldaniels** [comment]
It won't even allow me to select ec2 as an inventory type when I try to
create a new inventory. Have you seen this?

**Comment by pselibas** [comment]
+1

**Comment by Challa-shekhar** [comment]
is there any fix for the dynamic inventory yet?

**Comment by igoratencompass** [comment]
Same issue here

**Comment by frostymarvelous** [comment]
Disabled for me too.

**Comment by pgporada** [comment]
Check out the suggestion on https://github.com/ansible-semaphore/semaphore/issues/47#issuecomment-285345592

**Comment by matejkramny** [comment]
dup of #47
