### ISSUE TITLE
Permission denied for the playbooks.

### ISSUE THREAD

**Issue by markwor** [ansible-semaphore/semaphore#1630]
Hallo,

I want to use Semaphore with our Ansible environment.

But every time i get an error.

I installed semaphore with snap.

ERROR! an error occurred while trying to read the file '/etc/ansible/test.yml': [Errno 13] Permission denied: b'/etc/ansible/test.yml'. [Errno 13] Permission denied: b'/etc/ansible/test.yml'

![image](https://github.com/ansible-semaphore/semaphore/assets/151013334/d8432351-7e79-446d-aff1-8e8f805fab24)

Repo is local:
![image](https://github.com/ansible-semaphore/semaphore/assets/151013334/cb699d83-86f2-4372-aa31-18aaa5336a5d)

Key Store:
![image](https://github.com/ansible-semaphore/semaphore/assets/151013334/b4093ea3-d444-4e1c-bb46-e996fb2a805f)

I changed the permission to 777 for a test:
-rwxrwxrwx   1 root root  740 Nov 16 08:23 test.yml

Can anyone help me?

Best regards,
Markus

**Comment by macau23** [comment]
Become the user semaphore is running as and try to cat the file. You might not have permissions on a directory higher up.
Not that? Check selinux/apparmor. Doing anything with chroots? Make sure you change the right file.

**Comment by markwor** [comment]
I found the solution.

Semaphore has only access to the tmp_patch.
It is configured at:
`snap/semaphore/common/config.json`
`"tmp_path":                     "/root/snap/semaphore/common/repositories"`
