### ISSUE TITLE
Unable to use custom modules

### ISSUE THREAD

**Issue by ksourdrille** [ansible-semaphore/semaphore#1647]
Hi, i've created a python script for a custom module but i'm not able to use it with semaphore.

My script module is located in my repo under :

ansible --> library --> script.py

My playbook is here :

ansible --> playbooks --> playbook.yml

I can use it with ansible in CLI when i add -M library like this : 
`ansible-playbook -i inventory.yml -M ansible/library playbooks/playbook.yml --check`

But when i want to use it with semaphore i can't :
![image](https://github.com/ansible-semaphore/semaphore/assets/100124349/bb2459e6-3ed1-4d0c-9c7b-47700cc1fb51)

i've tried to add -M in the template CLI AGRS like this : 

![image](https://github.com/ansible-semaphore/semaphore/assets/100124349/43586ef7-8a25-4c7d-9fdf-02714717dce3)

But that's doesn't work ...

Someone have any idea ?

**Comment by BogdanLivadariu** [comment]
@ksourdrille have you tried:
```
[
  "-M", "library"
]
```

**Comment by ksourdrille** [comment]
@BogdanLivadariu it works 😊, thank you 👍
