### ISSUE TITLE
Docker Container logs Secrets

### ISSUE THREAD

**Issue by JohannesFleischer** [ansible-semaphore/semaphore#1649]
I am just starting with semaphore and am currently playing around with it a bit.
While doing so, I found out, that the [docker container](https://hub.docker.com/r/semaphoreui/semaphore/tags?page=1&name=v2.9.37) prints the secrets to the log on startup.

This is a behavior that a user does not expect and can therefore be easily overlooked.
It also overrides all security measures regarding these passwords and can therefore easily lead to critical security problems.

**Comment by fiftin** [comment]
@JohannesFleischer what secrets do you mean?

**Comment by JohannesFleischer** [comment]
@fiftin When starting from zero the container prints this on startup:

![image](https://github.com/ansible-semaphore/semaphore/assets/71658262/5fbdb868-1e68-4c8b-bcd1-407f1b238a7e)


It is a bit tricky to reproduce because it does this just once, and you have to restart all over to get this error again.
But I was able to reproduce it a few times.

**Comment by JohannesFleischer** [comment]
> @fiftin When starting from zero the container prints this on startup:
> 
> ![image](https://private-user-images.githubusercontent.com/71658262/307087723-5fbdb868-1e68-4c8b-bcd1-407f1b238a7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2MjI4NTQsIm5iZiI6MTcwODYyMjU1NCwicGF0aCI6Ii83MTY1ODI2Mi8zMDcwODc3MjMtNWZiZGI4NjgtMWU2OC00YzhiLWJjZDEtNDA3ZjFiMjM4YTdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDE3MjIzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3M2U2M2U3MjlmNjViMTBkZGUyMjc5YjczNzkwMzQ4MzA2MmE5ZDdmNTllMzRmMzFlYWRlM2JmY2UzYjQ0YjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zBTUf84SK9TBrzAZr9xwwkn8tdOkG-h-_wlwmdURsks)
> 
> It is a bit tricky to reproduce because it does this just once, and you have to restart all over to get this error again. But I was able to reproduce it a few times.

nvmd I got the trick:

It occurs whenever a new config is generated. E. g. as a docker volume. When this is re(created) it prints out the secrets
