### ISSUE TITLE
semaphore on ppc64le

### ISSUE THREAD

**Issue by ALutz273** [ansible-semaphore/semaphore#1658]
Hello,

I think the project is mega good. 
Unfortunately, it is not available on the IBM Power platform. 

There is not the package go-task for ppc64le 
Is there another way to compile on ppc64le? 

https://github.com/ansible-semaphore/semaphore/issues/566

**Comment by ALutz273** [comment]
Any Update?

**Comment by tboerger** [comment]
Generally it could be possible to get it working if you execute the tasks defined in Taskfile manually.

**Comment by tboerger** [comment]
I have to remove the container build for ppc64le at https://github.com/semaphoreui/semaphore/pull/2010 because it takes hours to complete. If you still want to run Semaphore on ppc64le you can use the built binaries or the packages, but not our prebuilt images.
