### ISSUE TITLE
not able to install semaphore

### ISSUE THREAD

**Issue by maniyara** [ansible-semaphore/semaphore#166]

**Comment by matejkramny** [comment]
Can you elaborate?

**Comment by zakkhan** [comment]
Can you please help as i not able to install semaphore   on Ubuntu 14 

i got error while running  

#  semaphore -setup


Executing migration v1.1.0 (at 2016-07-26 21:36:46.01249632 -0700 PDT)...
 [1/1]
 ERR! Query: /* update precision of output logs - also prevents confusion when sorting the table to guarantee it is in the same order */
alter table task__output change `time` `time` datetime(6) not null;

Rolling back v1.1.0 (time: 2016-07-26 21:36:46.013665314 -0700 PDT)...
Rollback SQL doesn't exist.


 Database migrations failed!
 Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(6) not null' at line 2


Please help

**Comment by maniyara** [comment]
hi
Issue is resolved
thanks for replay
regards
azar

**Comment by mozzymoz** [comment]
How did you resolve this issue?

**Comment by matejkramny** [comment]
update mysql version @mozzymoz (see https://github.com/ansible-semaphore/semaphore/wiki/Installation)
