### ISSUE TITLE
SECURITY: Enable GitHub Dependabot to see Vulnerabilities

### ISSUE THREAD

**Issue by ansibleguy** [ansible-semaphore/semaphore#1662]
To make known Vulnerabilities transparent - [Dependabot](https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-supply-chain-security#what-is-dependabot) should be enabled for the repository: https://github.com/ansible-semaphore/semaphore/settings/security_analysis

From a Security standpoint this is critical knowledge the users should be aware of!

Currently it shows 19 existing Vulnerabilities:
![image](https://github.com/ansible-semaphore/semaphore/assets/79044229/7e503944-5ae9-465b-878d-a23240479cd3)
Reference: https://github.com/ansibleguy/semaphore-test/security/dependabot

**Comment by fiftin** [comment]
Done, thank you!
