### ISSUE TITLE
Inventory (static) not working as expected

### ISSUE THREAD

**Issue by ghost** [ansible-semaphore/semaphore#167]
Hi all, 

Current inventory is segregated into three blocks, Slot1, Slot2 and BothSlots. Appearence is this:

[slot1]
fqdn_server_name1
fqdn_server_name2

[slot2]
fqdn_server nameA
fqdn_server_nameB

[bothslots:children]
slot1
slot2

Above static inventory configuration does not work in Semaphore 2.0.4 whilst it does in ansible-playbook at console. Error thrown follows:

Started: 44

access key ansible_RSA installed
Updating repository
From 127.0.0.1:/etc/semaphore/playbooks/
- branch            master     -> FETCH_HEAD
  Already up-to-date.
  access key ansible_RSA installed
  **installing static inventory**

PLAY [Check system time and NTP configuration] *******************************************

TASK [Execute commands] ***************************************************
**fatal: [slot1]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh.", "unreachable": true}
fatal: [slot2]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh.", "unreachable": true}**

PLAY RECAP *********************************************************************
slot1                      : ok=0    changed=0    unreachable=1    failed=0  
slot2                      : ok=0    changed=0    unreachable=1    failed=0   

Running playbook failed: exit status 3

Just to clarify this post before any potential answer arrives, any fqdn_server_name detailed int he above defined groups [slot1] and [slot2] is reacheable by name and IP in the server and the network (DNS resolution is not an issue at all). 

This Issue is centered on the inventory treatment Semaphore does, and more concretely in regard to the expansion of groups. 

Any help with be much more than welcomed. 
BR,

Jonathan

**Comment by arthurtsang** [comment]
i've children groups and it works for me.  did you try turning on debug (-vvv) and check what's the ssh command ansible is using?  and try running it directly (you can remove -C and eveything after the hostname) you should be able to ssh to the host.
