### ISSUE TITLE
https://semui.co appears to be down, so documentation, demo site, etc. are down as well

### ISSUE THREAD

**Issue by fseesink** [ansible-semaphore/semaphore#1670]
Just a note that the site

https://semui.co/

appears to be down.  As the documentation is hosted there, and the demo site https://demo.ansible-semaphore.com/ appears to redirect there, that means all of that is down at the moment.

**Comment by fseesink** [comment]
Attempts to visit that site on port 80 result in another error entirely with a URL beginning
```
https://error.etp.akamai.com/error.html?lang=en&host=semui.co&uri=%2F&source=...
```

and showing in red
> website access prohibited
The website you are trying to access either presents a security risk or is not allowed under your organization's acceptable use policy.
If you think you are receiving this message in error, please contact your IT help desk.
[[MAIL]](mailto:[MAIL])
[[PHONE]](tel:[PHONE])
[Create Ticket](https://error.etp.akamai.com/[TICKET])
URL : semui.co/

This indicates that Akamai is blocking access to that domain.  I checked (as we use Akamai) and confirmed that the Akamai Enterprise Threat Protector indicates
```
domain: semui.co
threatName: Known Malware
severityLevel: High
count: 10
latest_date: 2023-12-07 16:03:23-05:00
```
You have a problem.

**Comment by fiftin** [comment]
It works now
