### ISSUE TITLE
Failed to import the required Python library (setuptools) on semaphore's Python /usr/bin/python3.

### ISSUE THREAD

**Issue by blade1989** [ansible-semaphore/semaphore#1673]
Can't install dependencies needed for playbook, inside the Semaphore Docker container. The specific package is `python3-setuptools`

The full error is:

```bash
Failed to import the required Python library (setuptools) on semaphore's Python /usr/bin/python3. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter
```

When I log in, to the docker image, and try to update the apk repo, I get the following error:

```bash
apk update
ERROR: Unable to lock database: Permission denied
ERROR: Failed to open apk database: Permission denied
```
When I try to su in to the root account, I get the following:

```bash
su root 
su: must be suid to work properly
```

How do I install dependencies needed for the package?

I have a playbook that only does API GET/POST request. So, no login to external server is needed. It would be best if I can make the web requests on localhost(docker image).

**Comment by tboerger** [comment]
Please try the latest container versions (currently `develop` tag) where you should be able to mount a requirements.txt into /etc/sempahore which will install the defined list of pypi dependencies while starting the container.
