### ISSUE TITLE
Ansible Semaphore openID error "Email cannot be empty"

### ISSUE THREAD

**Issue by coder9a** [ansible-semaphore/semaphore#1674]
Having issues in configuring ansible semaphore with OpenID, below is the OpenID configuration
"oidc_providers": {
    "authentik": {
        "display_name": "SSO",
        "provider_url": "https://xxHOSTxx/application/o/ansible/",
        "client_id": "xxxx",
        "client_secret": "xxxx",
        "scopes": ["openid","email","profile"],
        "username_claim": "preferred_username",
        "name_claim": "preferred_username",
        "email_claim": "email",
        "redirect_url": "https://abc.example.com/api/auth/oidc/authentik/redirect",
        "endpoint": {
            "issuer": "https://xxHOSTxx/application/o/ansible/",
            "auth": "https://xxHOSTxx/application/o/authorize/",
            "token": "https://xxHOSTxx/application/o/token/",
            "userinfo": "https://xxHOSTxx/application/o/userinfo/",
            "jwks": "https://xxHOSTxx/application/o/ansible/jwks/"
        }
    }
}

Attached the error that I received in the logs
![Screenshot from 2023-12-11 20-15-43](https://github.com/ansible-semaphore/semaphore/assets/42884781/fdcce907-d767-4214-b176-2a5d74a91a87)
![Screenshot from 2023-12-11 20-25-25](https://github.com/ansible-semaphore/semaphore/assets/42884781/094a5a49-32aa-43cc-ba35-f664dc048c2e)

Able to login with username and password manually
**Note:-** Using Authentik for SSO login, integrated Active directory already for SSO
Authentik Version - 2023.10.4
Semaphore Version - v2.9.37

**Comment by seniordevops7** [comment]
Same problem here, but different error message:
```
time="2023-12-13T05:05:58Z" level=error msg="claim 'email' missing from id_token or not a string"
```

**Comment by coder9a** [comment]
Yes, the above error I got after making some changes in the Application providers on Authentik
Any suggestion about this config on Authentik
![image](https://github.com/ansible-semaphore/semaphore/assets/42884781/fd0a6a2e-ae98-447f-a7a9-3a2a22791b85)

**Comment by Loigzorn** [comment]
Hello everyone,

I had a similar behaviour on my setup.
Some time ago I opened a discussion on this topic.

I was able to resolve this earlier.
Here is the [link](https://github.com/ansible-semaphore/semaphore/discussions/1663) to the discussion.

Hope this helps!

Regards

**Comment by seniordevops7** [comment]
Excellent, thank you so much  @Loigzorn

**Comment by coder9a** [comment]
It's working for me, thanks @Loigzorn 
Just one more thing,
As of now, after logging into Authentik server, it redirects to Ansible-Semaphore login page after clicking on the Ansible application. So, is there a way to log in directly to Ansible without clicking on SSO?

**Comment by Loigzorn** [comment]
Hello @coder9a,

Glad to hear you have a working setup.

To your question: no, I don't Authentik is capable of such. 
All what Authentik is doing in this setup 
- on the semaphore login page 'SSO' is clicked
- the user gets redirected to Authentik to prove his identity 
- on success the user is logged into semaphore with the scopes provided be Authentik

Lets say you are already logged into Authentik and you are now going to the semaphore site, semaphore has no knowledge about you already logged into Authentik. 
To prove you identity (and provide semaphore with the needed scopes) it is necessary to click on the 'SSO' button again.

**Comment by coder9a** [comment]
Okay, got it
Thanks for the help @Loigzorn
