### ISSUE TITLE
Can you specific a different interface to bind to?

### ISSUE THREAD

**Issue by lhorace** [ansible-semaphore/semaphore#168]
Hello,

Is it possible to bind to a different IP/Interface? I've gone through the options in my semaphore_config.json file and [Installation Wiki](https://github.com/ansible-semaphore/semaphore/wiki/Installation) and can't find anything relevant to what I am looking for.

Regards

**Comment by ea1het** [comment]
Hi lhorace, 

Use the "port" directive on semaphore_config.json to get this:

{
        "mysql": {
                "host": "127.0.0.1:3306",
                "user": "semaphore",
                "pass": "xxxxxxxxxxxxxxx",
                "name": "semaphore"
        },
        **"port": "127.0.0.1:80",**
        "bugsnag_key": "",
        "tmp_path": "/tmp/semaphore",
        "cookie_hash": "{
        "mysql": {
                "host": "127.0.0.1:3306",
                "user": "root",
                "pass": "",
                "name": "semaphore"
        },
        "port": "127.0.0.1:80",
        "bugsnag_key": "",
        "tmp_path": "/tmp/semaphore",
        "cookie_hash": "n1wpe3bUAk3fSpinZWQyWgRSt5Y4HxYaFuycCqk5Ni4=",
        "cookie_encryption": "W++3BWhBGaAm1SVfTE4RW/wYKRaFKEQjZ/VSB9SIX+U="
 }=",
        "cookie_encryption": "xxxxxxxxxxxxxxxxxxxxxxxxxx"
 }

Later confirm with this command:

[root@orchestration ~]# **netstat -apn --inet |grep  LISTEN  |grep semaphore**
tcp        0      0 127.0.0.1:80                0.0.0.0:*                   LISTEN      32240/semaphore

**Comment by lhorace** [comment]
Fixed

**Comment by Twim4** [comment]
doesn't work on v2.5.0

**Comment by twhiston** [comment]
please open a new issue with all details if you have a problem rather than resurrecting a closed issue from 2 years ago
