### ISSUE TITLE
Views creation for Task Templates don't work

### ISSUE THREAD

**Issue by akordowski** [ansible-semaphore/semaphore#1696]
The Semaphore UI version 2.9.37 is running in a Docker container with a MySql database.

I try to add some Views in the **Task Templates** section.
First the *Edit Views* dialog without any views appears.

![grafik](https://github.com/ansible-semaphore/semaphore/assets/9746197/0d28f085-6c48-4f74-9a10-9467875e27d3)

After clicking the *Add View* button a new empty entry with a green checkmark appears.

![grafik](https://github.com/ansible-semaphore/semaphore/assets/9746197/f038c5b2-c74f-4c87-a2f7-4ddd5b037098)

After adding some views I close the dialog via the _X_ button in the dialog.

![grafik](https://github.com/ansible-semaphore/semaphore/assets/9746197/547515c0-3e50-4cc7-a28f-a5d0ad1ca417)

But the created views never appear in the navigation and after reloading the page ond opening the dialog again they are gone.

**Comment by maghog** [comment]
You have to click on the green checkmark to the right of your new view.

**Comment by akordowski** [comment]
Thank you! Oh boy, I thought this is an indicator not a button 🤦‍♂️
