### ISSUE TITLE
state transition error after playbook edit.

### ISSUE THREAD

**Issue by bibby** [ansible-semaphore/semaphore#17]
Repro:
- From Playbooks, click on the name of a defined playbook.
- Click Edit on the left-side bottom, transition to the *Edit Playbook* form.
- Click the green Edit button.

JS Console will balk, citing `Error: No such state 'playbook.view'`.
Originates from `public/js/controllers/playbook/edit.js:21`

```
$state.transitionTo('playbook.view', {
    playbook_id: data._id
});
```

**Comment by matejkramny** [comment]
Thanks for reporting. Will be fixed by next release
