### ISSUE TITLE
Ansilbe failed with error "Inappropriate ioctl for device"

### ISSUE THREAD

**Issue by sunyq** [ansible-semaphore/semaphore#170]
Hello,
I am trying with semaphore, but have never succeed to run one task, because it always failed with such an error:
  `fatal: [10.221.83.93] => {'msg': "FAILED: (25, 'Inappropriate ioctl for device')", 'failed': True}`
_10.221.83.93 is the ip address of one remote node._

I tried to run command `ansible` and `ansible-playbook` with the same yaml file and inventory( under the tmp_path of semaphore) and it runs correctly without any error.

I tried with ansible 2.1.0 and 1.9.2.
The git version on my host is 1.7.1.

Could that be because of my old git version?

Regards

**Comment by Denjag** [comment]
I had the same issue when I used paramiko for the transport. The error was due to a too big hostname for the target.
If that can help you.

**Comment by tomxiaxia** [comment]
I had the same issue 
15:19:38: fatal: [10.22.0.58]: UNREACHABLE! => {"changed": false, "msg": "(25, 'Inappropriate ioctl for device')", "unreachable": true}
15:19:38: fatal: [10.22.0.59]: UNREACHABLE! => {"changed": false, "msg": "(25, 'Inappropriate ioctl for device')", "unreachable": true}
How did you solve it?
