### ISSUE TITLE
command: "semaphore upgrade" - replaces /usr/bin/semaphore with tar.gz version. 

### ISSUE THREAD

**Issue by fne007** [ansible-semaphore/semaphore#1701]
root@ans-01:/tmp# semaphore version
**v2.9.41-beta**
root@ans-01:/tmp# semaphore upgrade
downloading https://github.com/ansible-semaphore/semaphore/releases/download/**v2.9.41-beta**/semaphore_2.9.41-beta_linux_amd64.tar.gz
replacing /usr/bin/semaphore

### Semaphore is updating even it's not necessary.  (v2.9.41-beta)

visit https://github.com/ansible-semaphore/semaphore/releases for the changelog
root@ans-01:/tmp# file /usr/bin/semaphore
/usr/bin/semaphore: gzip compressed data, max compression, original size modulo 2^32 37277184

### semaphore is replacing itself with the renamed  .tar.gz 

root@ans-01:/tmp# mv /usr/bin/semaphore semaphore.tar.gz
root@ans-01:/tmp# tar -xzf semaphore.tar.gz

### after rename and tar -xzf the binary is ready to go.

root@ans-01:/tmp# file semaphore
semaphore: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=FNBp5LkMwganjgcQrJWh/8CMHmL6jUJrW2DcoEMC-/Jcy5ep0ELN8bNlv8Cpg0/gmht4crFs9yNJ3bFE5rV, stripped
root@ans-01:/tmp# mv semaphore /usr/bin/semaphore

### FIX: moving extracted binary to the right place and restart the service.

root@ans-01:/tmp# service semaphore restart
root@ans-01:/tmp# service semaphore status
● semaphore.service - Semaphore Ansible
     Loaded: loaded (/etc/systemd/system/semaphore.service; enabled; preset: enabled)
     Active: active (running) since Mon 2024-01-15 11:28:37 CET; 4s ago
       Docs: https://github.com/ansible-semaphore/semaphore
   Main PID: 397440 (semaphore)
      Tasks: 6 (limit: 4644)
     Memory: 38.5M
        CPU: 196ms
     CGroup: /system.slice/semaphore.service
             └─397440 /usr/bin/semaphore service --config=/etc/semaphore/config.json

Jan 15 11:28:37 ans-01 systemd[1]: semaphore.service: Consumed 1min 5.931s CPU time.
Jan 15 11:28:37 ans-01 systemd[1]: Started semaphore.service - Semaphore Ansible.
Jan 15 11:28:37 ans-01 semaphore[397440]: Loading config
Jan 15 11:28:37 ans-01 semaphore[397440]: Validating config
Jan 15 11:28:37 ans-01 semaphore[397440]: MySQL semaphore@127.0.0.1:3306 semaphore
Jan 15 11:28:37 ans-01 semaphore[397440]: Tmp Path (projects home) /opt/semaphore/tmp
Jan 15 11:28:37 ans-01 semaphore[397440]: Semaphore v2.9.41-beta
Jan 15 11:28:37 ans-01 semaphore[397440]: Interface 127.0.0.1
Jan 15 11:28:37 ans-01 semaphore[397440]: Port :3000
Jan 15 11:28:37 ans-01 semaphore[397440]: Server is running

best regards,
fne

**Comment by karloff10** [comment]
It also switches to a beta version, which does not correspond to the description of the command.<br>
root@localhost:~# /usr/local/bin/semaphore -h | grep upgrade
  upgrade     Upgrade to latest **stable** version

stable releases should not contain beta releases
<br><br>
```sh
root@localhost:~# file /usr/local/bin/semaphore
/usr/local/bin/semaphore: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=3nmIoJmbJNzdnZgDTHvU/EbhBBDQ6oE6iLBY2jkM-/U6RcarqkC7p08u1sOjMM/1alnJrKgsg9NY5F8yx1D, stripped

root@localhost:~# /usr/local/bin/semaphore version
v2.9.64

root@localhost:~# /usr/local/bin/semaphore upgrade
downloading https://github.com/semaphoreui/semaphore/releases/download/v2.9.68-beta/semaphore_2.9.68-beta_linux_amd64.tar.gz
replacing /usr/local/bin/semaphore
visit https://github.com/ansible-semaphore/semaphore/releases for the changelog

root@localhost:~# file /usr/local/bin/semaphore
/usr/local/bin/semaphore: gzip compressed data, max compression, original size modulo 2^32 26054144
```

Obviously semaphore also breaks after a reload/restart:
```sh
root@localhost:~# /usr/local/bin/semaphore server --config /home/semaphore/config.json
-bash: /usr/local/bin/semaphore: cannot execute binary file: Exec format error
```

**Comment by tboerger** [comment]
I personally dislike this kind of update mechanism. If this is some feature really wanted by the community it should be implemented properly based on some pretty tested library. Otherwise it would make more sense to offer reall deb/rpm repositories. If somebody is installing the binary it's up to him to update it.

**Comment by fiftin** [comment]
@tboerger let's remove `upgrade` command? ) I don't like it too.

Do you know how to create deb/rpm repo? And it will be cool to try to post Semaphore to Debian/Ubuntu repo...

**Comment by tboerger** [comment]
For the repo it depends if you really want to maintain your own repo or if this should be handled by some service like https://packagecloud.io/pricing/ or https://cloudsmith.com/pricing which offer since free plans.

If you want to build the repo on your own there are options to host this on s3 compatible storage like https://github.com/deb-s3/deb-s3

I think it's good to remove the upgrade command or replace it by something like https://github.com/sanbornm/go-selfupdate but this should be disabled (maybe via build tags) for repo/docker/snap builds.

**Comment by tboerger** [comment]
Oh there is also the openbuildservice by SUSE which could build and provide rpm and deb repositories. Even the new Kubernetes repositories are based on that.

**Comment by fiftin** [comment]
removed command
