### ISSUE TITLE
URL rejected: Port number was not a decimal number between 0 and 65535

### ISSUE THREAD

**Issue by jrndberg** [ansible-semaphore/semaphore#1705]
Cannot use private repos with https clone

That is the error I get when I use https://gitlab.com/repo.git, and with a password and username I have added in my keys.

Please let me know if u need anything else

**Comment by nightly-brew** [comment]
I noticed the same bug just today, same exact code and impossibility to clone the repository.

Trying to run a task stored in a private repo (github in my case, not gitlab like OP).
The repo is cloned through https.
The access key used has an email address in the username field, and the PAT token as password.

Manually cloning with git works like a charm.

In the task log I noticed the email being split at the @, eg. username = git@dev.local becoming dev.local

Did a test and managed to make it work by changing the username in the key to something else, without any @ (eg TEST).
I think there's something wrong with the @

**Comment by Yuri-Lima** [comment]
Do we have any workaround for now. I am facing the same issue.

**Comment by jrndberg** [comment]
My workaround was to use an access token

So like `https://<you-name>:<access-token>@git.net/path/to/your/repo`

How to set one up: https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html

**Comment by fiftin** [comment]
Hi @nightly-brew I tried to clone github repo with email as login, and I got error `URL rejected: Port number was not a decimal number between 0 and 65535`.

Please provide example which works for you.

**Comment by nightly-brew** [comment]
> Hi @nightly-brew I tried to clone github repo with email as login, and I got error `URL rejected: Port number was not a decimal number between 0 and 65535`.
> 
> Please provide example which works for you.

Hi, thanks for taking a look.

As per OP, I was cloning a github repo through https.

My auth/pass on semaphore was something like the following:
    user: user@mail.com <-- email used on github
    pass: \<github PAT token\> <-- personal access token registered under my github account

I managed to patch things up by using something else as user, which for some obscure reason, works just as well on github
    user: TEST  <-- I literally just ended up writing this and it worked
    pass: \<github PAT token\>

While testing, whenever I tried using an '@' in the username, the 'URL rejected' error would pop up again.
I think this was a regression introduced after an update, but I can't remember the version I had before.

Hope it helps.

**Comment by relentlessWhalePilot** [comment]
Please check to make sure your authentication type, repository URL and Git settings are correct and consistent with eachother.

I had this error when there was a mismatch, using SSH keys against a HTTP address in Azure DevOps, vice versa. Make sure you are using an SSH url provided by the Git service if using SSH keys, or use a PAT if using https address.

![image](https://github.com/semaphoreui/semaphore/assets/171953008/484be72f-6cb3-44ae-a2c1-80aab4e26d7d)
