### ISSUE TITLE
Could not unmarshal arguments to []string

### ISSUE THREAD

**Issue by lhorace** [ansible-semaphore/semaphore#171]
Hello,

I am not sure if this is a intended behaviour or not. However, once you have supplied a JSON to `Extra CLI Arguments` and later redact it. You can no longer run the same task again due to the following errors:

```
01:08:48: Could not unmarshal arguments to []string
01:08:48: Running playbook failed: unexpected end of JSON input
```

The workaround at least for me is to recreate the task.

Regards

**Comment by matejkramny** [comment]
The json value could be invalid

**Comment by lhorace** [comment]
There is no _json_ value as it's be redacted/removed.

Ways to reproduce
1. Create a Task Template
2. Supply a valid JSON object to `Extra CLI Arguments`
3. Execute task
4. Return back to the template task on completion and remove/erase JSON object
5. Run the same task template again

Expected Result:

Task executes successfully

Actual Result:

```
01:08:48: Could not unmarshal arguments to []string
01:08:48: Running playbook failed: unexpected end of JSON input
```

Additional notes:

I suspect that the program is inserting an undefined/non-existent value to whatever function in the back end.

**Comment by matejkramny** [comment]
Ok understood. Thanks! I'll put this into 2.1

**Comment by frostymarvelous** [comment]
I had to put in an empty `[]` in Extra CLI Arguments.
That fixed it for me.

**Comment by strangeman** [comment]
This is not the bug. Placeholder for Extra CLI Arguments says: `*MUST* be a JSON array!`. `nothing` - isn't an array.

**Comment by matejkramny** [comment]
If the value is empty semaphore should ignore it

**Comment by strangeman** [comment]
Found error. If I created Task template from scratch, `arguments` field in database = `NULL`. If I edit task template, arguments` field in database = `` (empty value).

**Comment by frostymarvelous** [comment]
@strangeman   I understood that after I figure it out.

But initially I understood it to mean it must be valid *if* there is a value.

**Comment by matejkramny** [comment]
The bug is bad checking. The code shouldn't attempt to deserialise `nil` into `[]string`, hence the error

**Comment by strangeman** [comment]
>The code shouldn't attempt to deserialise nil into []string, hence the erro

It shouldn't. It trying to deserialise "" (empty string), not `nil`. 
BTW, should we close it, because my PR was merged?

**Comment by matejkramny** [comment]
I see, you're right..
