### ISSUE TITLE
Error in semaphore Installation 

### ISSUE THREAD

**Issue by zakkhan** [ansible-semaphore/semaphore#172]
i am not able to install semaphore on Ubuntu 14

i got an error while running
# semaphore -setup

Executing migration v1.1.0 (at 2016-07-26 21:36:46.01249632 -0700 PDT)...
[1/1]
ERR! Query: /\* update precision of output logs - also prevents confusion when sorting the table to guarantee it is in the same order */
alter table task__output change time time datetime(6) not null;

Rolling back v1.1.0 (time: 2016-07-26 21:36:46.013665314 -0700 PDT)...
Rollback SQL doesn't exist.

Database migrations failed!
Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(6) not null' at line 2

Please help

**Comment by matejkramny** [comment]
What is your db version?

**Comment by javiervivanco** [comment]
I have the same problem. 

MYSQL 5.5
`Executing migration v1.1.0 (at 2017-05-31 12:27:42.182063102 -0300 ART)...
 [1/1]
 ERR! Query: /* update precision of output logs - also prevents confusion when sorting the table to guarantee it is in the same order */
alter table task__output change `time` `time` datetime(6) not null;

`

**Comment by twhiston** [comment]
Semaphore requires mysql >= 5.6.4
