### ISSUE TITLE
Cannot delete a template

### ISSUE THREAD

**Issue by lbouriez** [ansible-semaphore/semaphore#1722]
Hello,
I am trying to delete a template (...project/1/templates/32)
I get a popup saying: 
![image](https://github.com/ansible-semaphore/semaphore/assets/4749766/32b61ce4-3cc7-408b-8a4f-e247915e2d81)
And the link in the popup is the same as the template I am trying to delete.
Does anyone has an idea how to remove it ?

**Comment by fiftin** [comment]
Hm, looks like a bug

**Comment by fiftin** [comment]
I reproduced your issue:

* make Build task template
* convert the task to Deploy and select the task as build template
* save template
* convert template to simple task
* try to delete

How you can fix issue right know:
* edit template
* change template to Deploy and select other Build template
* delete template

**Comment by EHEX-schildt** [comment]
did you have set a cron?

if yes, remove the content of the Cron field,save, then delete the template.

**Comment by lbouriez** [comment]
So in my case the issue was due to the cron, thanks @EHEX-schildt . Once the cron removed I was able to remove the templates. Maybe the error message should be improved here to avoid futur confusion :)

**Comment by fiftin** [comment]
Fixed
