### ISSUE TITLE
Docker: Current used ansible version has an uri/json issue 

### ISSUE THREAD

**Issue by peedy2495** [ansible-semaphore/semaphore#1750]
Latest docker image semaphoreui/semaphore [6a7dbb3e39ab] is still using ansible 2.14.5.
I'm struggling with this issue: https://github.com/ansible/ansible/issues/80709 which has been closed on May 30, 2023

**Comment by andreas-marschke** [comment]
You can always use the existing container definition and upgrade the ansible version inside it: 
```dockerfile

FROM semaphoreui/semaphore:latest

USER root

WORKDIR /home/semaphore

# Where requirements.txt has all the right versions of the dependencies you need
COPY ./requirements.txt /tmp/requirements.txt

# Add here any other dependencies from the OS you need
RUN apk update && apk add py3-pip py3-setuptools alpine-sdk make gcc wget python3-dev jq

# Even libc and build tools if necessary for bindings
RUN apk add --virtual .build-deps gcc musl-dev

# Now install all the dependencies 
RUN pip install -r /tmp/requirements.txt

# Switch back to semaphore user so that the container starts
# and works with the entrypoint defined in the parent container.
USER semaphore
```

And say you have a requirements.yml like: 
```yaml
ansible==9.2.0
ansible-core==2.16.3
ansible-specdoc==0.0.14
appdirs==1.4.4
baron==0.10.1
cffi==1.16.0
cryptography==42.0.3
Jinja2==3.1.3
MarkupSafe==2.1.5
packaging==23.2
pycparser==2.21
PyYAML==6.0.1
redbaron==0.9.2
resolvelib==1.0.1
rply==0.7.8
```

You can build a patched container:
```sh
$>  docker build --label semaphore-patched -t semaphore-patched .
```

Afterwards you can test it:
```sh
$> docker run -it semaphore-patched:latest ansible --version
ansible [core 2.16.3]
  config file = None
  configured module search path = ['/home/semaphore/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.11/site-packages/ansible
  ansible collection location = /home/semaphore/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.11.6 (main, Oct  4 2023, 06:22:18) [GCC 12.2.1 20220924] (/usr/bin/python3)
  jinja version = 3.1.3
```

Would this help?

**Comment by peedy2495** [comment]
Thank you for your suggestion.
I still created a vm with the latest stuff. But now, I'll switch back to docker ;-)
I created a repo for this solution: [peedy2495/semaphore-docker](https://github.com/peedy2495/semaphore-docker)

**Comment by tboerger** [comment]
I think the container should be refactored a little bit to install ansible via pip instead of the package, that way somebody could also add a mechanism to easily build custom images with different versions.

**Comment by fiftin** [comment]
@tboerger do you have idea how to do this?

**Comment by tboerger** [comment]
The containers are installing Ansible directly from pypi instead of relying on the alpine packages now. We have a recent Ansible version installed now.
