### ISSUE TITLE
Concurrency problem with ssh-agent

### ISSUE THREAD

**Issue by chrisvanmeer** [ansible-semaphore/semaphore#1751]
Running multiple (3 or more) task templates at the exact same time with version `2.9.45` sometimes results in issues with the `ssh-agent`.

Then we see the following on one of the jobs:
```
3:10:24 AM Failed to install inventory: listening on socket "/tmp/semaphore/ssh-agent-20-1707444623.sock": listen unix /tmp/semaphore/ssh-agent-20-1707444623.sock: bind: address already in use
3:10:24 AM Running playbook failed: listening on socket "/tmp/semaphore/ssh-agent-20-1707444623.sock": listen unix /tmp/semaphore/ssh-agent-20-1707444623.sock: bind: address already in use
```

We didn't have this problem while running version `2.9.37` (probably because it didn't use the `ssh-agent` yet).

As a temporary workaround, I spread apart the simultaneous jobs with 1 minute to avoid a lock on the socket while this is under investigation.

**Comment by johan-smits** [comment]
Any progress on this issue?

**Comment by tboerger** [comment]
No status update, so it looks like nobody started to work on it.

**Comment by mcgru** [comment]
> Running multiple (3 or more) task templates at the exact same time with version 2.9.45 sometimes results in issues with the ssh-agent.

Sorry, i cannot find it in documentation - could you describe ho to use ssh-agents to make Semaphore possible to access remote target hosts from playbooks using that ssh-agent ?

**Comment by agarzon-orangerine** [comment]
Since the last update, suddenly my semaphore stop working:

`Failed to install inventory: listening on socket "/tmp/semaphore/ssh-agent-3-1716905006.sock": listen unix /tmp/semaphore/ssh-agent-3-1716905006.sock: bind: address already in use`

I create a new instance from scratch just for testing and still fails, same error.

**Comment by kism** [comment]
I'm getting this specifically when I have the inventory and playbook coming from the same git repo

If I set the inventory to come from a local folder everything works again.

```
2:40:13 PM
Failed to install inventory: listening on socket "/tmp/semaphore/ssh-agent-2-1716964813.sock": listen unix /tmp/semaphore/ssh-agent-2-1716964813.sock: bind: address already in use
2:40:13 PM
Running playbook failed: listening on socket "/tmp/semaphore/ssh-agent-2-1716964813.sock": listen unix /tmp/semaphore/ssh-agent-2-1716964813.sock: bind: address already in use
```

**Comment by fiftin** [comment]
Hi @kism could you provide more details about issue. Is the issue reproducible with other templates/repositories?

**Comment by MAHARLOS** [comment]
I had the same issue and it was caused by creating two inventorys from a repo with the same name by accident. My fix was to push the same inventory with a different name.

**Comment by fiftin** [comment]
Hi @MAHARLOS please try latest beta version `v2.9.113-beta`.

**Comment by kism** [comment]
@fiftin works for me! Thanks!

(Tag is incorrect btw)
https://github.com/semaphoreui/semaphore/releases/tag/v2.9.13-beta

**Comment by isaacblum** [comment]
The beta version fixed my issue as well. Thank you.
