### ISSUE TITLE
Create a Webhook-friendly job endpoint

### ISSUE THREAD

**Issue by samerbahri98** [ansible-semaphore/semaphore#1756]
As Ansible Semaphore is having more and more CI/CD features, it is still missing some SCM integrations. And one of the most useful ones is to be able to run jobs on GitHub Events.

GitHub sends Webhooks in the form of HTTP POST requests to a designated URL, but it does not allow us to modify the header and the body of the request.

A list of improvements that would be considered:
- Add `/api/project/{projects}/templates/{template_id}/run` endpoint (method is POST)
- This endpoint is very similar to `/api/project/{projects}/tasks`, but the api token and the request body are passed as request params instead of body and header.
- This endpoint passes the content of its header, body and query parameters as ansible vars to the playbook it's trying to run (or terraform vars, when using terraform).
- The logic and complexity of handling what to run and how, will be handled by the end user from that point. No further modifications to the software are needed (which seems to be the issue with other implementations such as #1365 )

If this is implemented successfully then we can even use semaphore cloud to build and deploy ansible semaphore itself as a proof of its capabilities (instead of GitHub actions)

**Comment by andreas-marschke** [comment]
There are several issues with your proposal.

 - Security: The URL and mechanic you propose is a direct unauthenticated execution of any defined task already in Semaphore, depending on what one will have implemented as a task would be freely exectuted which implies huge safety dangers to the  infrastructure as Semaphore would execute with no concern who would've sent or requested the execution.
 - pre-preparing the datastructures sent to the endpoint are not prepared for the task, so the task would have to take apart the values being passed in, that's more work a normal playbook implementation would not need
 -  Github Events can be implemented with #1365 just as well without running into dangers described above as it gates against what a Webhook is allowed to call, meaning any nefarious POST requests against the endpoint does not endanger your infrastructure

**Comment by fiftin** [comment]
@andreas-marschke it is use case which I asked ;)

Now I understand why this functionality is needed. But let's bring it to Integrations. Webhooks will be used for other functionality.

We can add predefined templates for GitHub events, and other services.

**Comment by samerbahri98** [comment]
> There are several issues with your proposal.
> 
> * Security: The URL and mechanic you propose is a direct unauthenticated execution of any defined task already in Semaphore, depending on what one will have implemented as a task would be freely exectuted which implies huge safety dangers to the  infrastructure as Semaphore would execute with no concern who would've sent or requested the execution.
> * pre-preparing the datastructures sent to the endpoint are not prepared for the task, so the task would have to take apart the values being passed in, that's more work a normal playbook implementation would not need
> * Github Events can be implemented with [Add Support for Webhooks #1365](https://github.com/ansible-semaphore/semaphore/pull/1365) just as well without running into dangers described above as it gates against what a Webhook is allowed to call, meaning any nefarious POST requests against the endpoint does not endanger your infrastructure

These are good points. Here are my two cents on that:
- There is still authentication (API token) to be handled as API token. I am moving it from the Headers to the Query parameters, which isn't as huge of a difference as it seems. If someone doesn't have the API token, they cannot trigger arbitrary playbooks, and if they do, they can run the playbooks whether they put it in the query parameters or in the headers. There is also authorization because the API token will belong to a service account that is assigned to a project, rather than to an admin account that has access to all the projects . On top of that, the requests sent by github can be verified if they are legitimate or not, as documented [here](https://docs.github.com/en/webhooks/using-webhooks/validating-webhook-deliveries), and also the GitHub webhook settings are only accessible to the repository owner. The way I see it is to have two different semaphore projects, one for processing webhook events and one for the actual project. If this is not ideal then the alternative we currently have is to use two different pieces of software that are capable of doing the same thing (semaphore and github actions), or two pieces of software where one is proxying the semaphore api.
- the way I see it, from the semaphore side, this is very similar to supplying the build and deploy version. From Ansible itself, the tool is more than capable of processing this kind of logic. From the playbooks side, the logic to process the request would be in a separate playbook and you would import the playbook you want to run with the `import_playbook` module if separation of concerns is important.
- It is correct in the sense that if that PR is merged, then this issue is irrelevant. I was operating with the consensus that the maintainers didn't want to merge that PR, since the changes to the project didn't seem to be intuitive to use. But if it is merged, I would be happy with the result and close this issue.

**Comment by fiftin** [comment]
Hi @samerbahri98 and @andreas-marschke I reviewed the MR. I ready to merge it but it is not complete. I didn't find the endpoint for calling from external service.
UPDATE: sorry, I found.

**Comment by fiftin** [comment]
@samerbahri98 I think we can do it more intuitive by adding integration templates.

**Comment by samerbahri98** [comment]
I agree

**Comment by tboerger** [comment]
Should we close this issue in favor of the open webhook pull request?

**Comment by samerbahri98** [comment]
For now I will close it yes. And if the webhook pull request doesn't get merged then I will open it back.
