### ISSUE TITLE
Trailing zero at task templates view

### ISSUE THREAD

**Issue by dusatvoj** [ansible-semaphore/semaphore#1757]
Hello,
I can see trailing zero at every task template under ID of last task. 

![image](https://github.com/ansible-semaphore/semaphore/assets/11560794/e645dbff-ebd5-45db-a150-e9ce8052e81b)

Is it just typo or it means something?

**Comment by andreas-marschke** [comment]
If I had to guess, it's because of this part of the template used for TaskLink:
```vue
<div style="color: gray; font-size: 14px;">
{{
  $t('by', {
    user_name: item.last_task.user_name, formatDate: item.last_task.created |
      formatDate
   })
}}
</div>
```

Where formatDate/item.last_task.created isn't filled correctly.

cc @fiftin
