### ISSUE TITLE
[Question] Are dynamic Inventories actually implemented?

### ISSUE THREAD

**Issue by sla-te** [ansible-semaphore/semaphore#1759]
I found a merge about it, stating it is but i cannot find any of its functionality in the UI. I have configured a dynamic inventory (using hetzner.hcloud) and I do indeed get a list if I do `ansible-inventory --graph` (it only appears to work if I have changed directory to .ansible/tmp/repository_1_1). Despite this works, none of the entries are visible within the UI..

Am I missing something here?

**Comment by samerbahri98** [comment]
yes, they do work. I always use it with vultr.

**Comment by sla-te** [comment]
ok, then its not clear to me, what implemented actually means. Are they supposed to show up in the "frontend" after having defined them? Could not find any docs about it.

@samerbahri98, maybe you could shed some light on how you realized it with vultr?

**Comment by samerbahri98** [comment]
you set the inventory to file and you point to the directory that contains your inventory (relative to the git repo). you also need to enable the hetzner.hcloud plugin in your ansible.cfg and create the correct file.

For example, let's say your git repo is like this:
```
.
├── ansible.cfg
├── inventory
│   ├── dev
│   └── prod
│       ├── hcloud.yml
│       └── hosts.ini
├── playbooks
└── roles
```
`hcloud.yml` is your hetzner inventory and `hosts.ini` will have groups and stuff.

then your semaphore inventory would be like this:
![image](https://github.com/ansible-semaphore/semaphore/assets/59774865/62e0bb3e-24d7-4e53-a38c-c4e0771faaac)
and your ansible.cfg contains this:
```ini
[inventory]
enable_plugins = ini, hetzner.hcloud.hcloud
```

`.ansible/tmp/repository_x_x` is where semaphore clones your git repo by the way. do not rely on that path because the numbers tend to change.
Let me know if something is not clear enough.

**Comment by sla-te** [comment]
@samerbahri98 
> .ansible/tmp/repository_x_x is where semaphore clones your git repo by the way. do not rely on that path because the numbers tend to change.

Yea I figured that out earlier already, as though we should maintain our inventory/playbook/cfg via version control, how do you realize that cleanly? A second repository, that you clone to $HOME of your service user without top level directory or do you just manage these files manually?

Enabling the plugins via ansible.cfg is new to me. Is it required to set this even if you use a requirements.yml in combination with a systemd unit, that has a ExecStartPre set as follows?
```
ExecStartPre=/bin/bash -c 'source /home/semaphore/venv/bin/activate \
                           && python3 -m pip install --upgrade -r /home/semaphore/requirements.txt'
ExecStartPre=/bin/bash -c 'source /home/semaphore/venv/bin/activate \
                           && ansible-galaxy collection install --upgrade -r /home/semaphore/requirements.yml \
                           && ansible-galaxy role install --force -r /home/semaphore/requirements.yml'
```      


> you set the inventory to file and you point to the directory that contains your inventory (relative to the git repo). you also need to enable the hetzner.hcloud plugin in your ansible.cfg and create the correct file.

As of now I have inventory set to `inventory=/home/semaphore/.ansible/tmp/repository_1_1/inventory/hcloud.yml` in ansible.cfg and it does appear to fetch it properly, as if i run `ansible-inventory --graph` it does list the inventory it fetches from hetzner properly, is this not correct?

Btw I did some more testing and got it to at least pickup all hosts in the inventory itself. While doing that I realized, that for some reason when I run a task, it will fail due to not finding the already installed hetzner.hcloud plugin... To workaround that, I had to create a subfolder in my playbook folder `myplaybook/collections/requirements.yml` and `myplaybook/collections/requirements.txt` (which is suggested not to do via the [official setup tutorial](https://docs.semui.co/administration-guide/installation_manually#ansible-collections-and-roles)), any idea why it does not find the plugin?

On the long run, all I would want to achieve is one global inventory, that every task can use.

**Comment by sla-te** [comment]
We switched to awx, as semaphore does seem too lightweight for our use case
