### ISSUE TITLE
Try to add template

### ISSUE THREAD

**Issue by ados1991** [ansible-semaphore/semaphore#176]
[GIN] 2016/08/11 - 14:25:47 | 200 |   49.266497ms | 192.168.99.1 |   GET     /api/project/2/inventory
2016/08/11 14:26:04 notifying bugsnag: Error 1452: Cannot add or update a child row: a foreign key constraint fails (`semaphore`.`project__template`,
CONSTRAINT `project__template_ibfk_2` FOREIGN KEY (`ssh_key_id`) REFERENCES `access_key` (`id`))
2016/08/11 14:26:04 bugsnag.Notify: not notifying in development

2016/08/11 14:26:04 [Recovery] panic recovered:
POST /api/project/2/templates HTTP/1.1
Host: 192.168.99.100:3000
Accept: application/json, text/plain, _/_
Accept-Encoding: gzip, deflate
Accept-Language: fr-FR,fr;q=0.8,en-US;q=0.6,en;q=0.4
Cache-Control: no-cache
Connection: keep-alive
Content-Type: application/json;charset=UTF-8
Cookie: semaphore=MTQ3MDkyMzk5MnxHb2FlTFNLU3ExZFpSUF9EeG15VTBOeXVWN29OVGtIQXpxX18xYVc0NDIyTTVWb1VZeUZ2bFBGNk01c2xVRm1yNEkxaS03VXRjTzVKNGlfUm9ORjN6aUk9
fGUBsdYJ5UIGqDFok7eYWsyzKBfFCW_XRsakAC1PMpNR
Origin: http://192.168.99.100:3000
Referer: http://192.168.99.100:3000/project/2/templates
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36

Error 1452: Cannot add or update a child row: a foreign key constraint fails (`semaphore`.`project__template`, CONSTRAINT `project__template_ibfk_2` F
OREIGN KEY (`ssh_key_id`) REFERENCES `access_key` (`id`))
/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:426 (0x42de89)
/Users/m/p/gospace/src/github.com/bugsnag/bugsnag-go/bugsnag.go:52 (0x534831)
/usr/local/Cellar/go/1.6/libexec/src/runtime/asm_amd64.s:472 (0x45d17e)
/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:426 (0x42de89)
/Users/m/p/gospace/src/github.com/ansible-semaphore/semaphore/api/projects/templates.go:62 (0x65b687)
/Users/m/p/gospace/src/github.com/gin-gonic/gin/context.go:97 (0x53d8ea)
/Users/m/p/gospace/src/github.com/ansible-semaphore/semaphore/api/projects/project.go:39 (0x65704b)
/Users/m/p/gospace/src/github.com/gin-gonic/gin/context.go:97 (0x53d8ea)
/Users/m/p/gospace/src/github.com/gin-gonic/gin/logger.go:66 (0x54f21a)
/Users/m/p/gospace/src/github.com/gin-gonic/gin/context.go:97 (0x53d8ea)
/Users/m/p/Projects/semaphore/cli/main.go:72 (0x401aef)
/Users/m/p/gospace/src/github.com/gin-gonic/gin/context.go:97 (0x53d8ea)
/Users/m/p/gospace/src/github.com/gin-gonic/gin/recovery.go:45 (0x54ff81)
/Users/m/p/gospace/src/github.com/gin-gonic/gin/context.go:97 (0x53d8ea)
/Users/m/p/gospace/src/github.com/gin-gonic/gin/gin.go:284 (0x544542)
/Users/m/p/gospace/src/github.com/gin-gonic/gin/gin.go:265 (0x544177)
/usr/local/Cellar/go/1.6/libexec/src/net/http/server.go:2081 (0x61e44e)
/usr/local/Cellar/go/1.6/libexec/src/net/http/server.go:1472 (0x61acfe)
/usr/local/Cellar/go/1.6/libexec/src/runtime/asm_amd64.s:1998 (0x45f831)

**Comment by kootstra** [comment]
In order for someone to be able to help you a little more information would be appreciated. For example:  

* Which Semaphore version are you running? 
* Is it standalone or the Docker Image? 
* What is your Semaphore config thus far?
* Anything else you have tried?

**Comment by pgporada** [comment]
Kootstra, I just ran into this on Ubuntu 16.04
```
Linux laptappy 4.4.0-36-generic #55-Ubuntu SMP Thu Aug 11 18:01:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

Semaphore version
```
v2.0.4
```

The error
```
2016/09/13 21:42:56 [Recovery] panic recovered:
POST /api/project/1/templates HTTP/1.1
Host: localhost:3000
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.5
Cache-Control: no-cache
Connection: keep-alive
Content-Type: application/json;charset=utf-8
Cookie: semaphore=MTQ3MzgxNjU4M3xzd1R2cGp5YmttWDM3Mm1Rd0lXY1dJMHRUX2U5QVdobU5pUnJEUnJDeEVVcHViTkJmbkxxRmtIa3FwVFJGSWs0TGVWR1VkU3hpRjc5aVEzQWZRVWVTa289fMR-_Cm1t7JfJU5gLrlPSkxj4N24t3iLDqUm12p_UrwK
Dnt: 1
Referer: http://localhost:3000/project/1/templates
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0


Error 1452: Cannot add or update a child row: a foreign key constraint fails (`semaphore`.`project__template`, CONSTRAINT `project__template_ibfk_3` FOREIGN KEY (`inventory_id`) REFERENCES `project__inventory` (`id`))
/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:426 (0x42de89)
/Users/m/p/gospace/src/github.com/bugsnag/bugsnag-go/bugsnag.go:52 (0x534831)
/usr/local/Cellar/go/1.6/libexec/src/runtime/asm_amd64.s:472 (0x45d17e)
/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:426 (0x42de89)
/Users/m/p/gospace/src/github.com/ansible-semaphore/semaphore/api/projects/templates.go:62 (0x65b687)
/Users/m/p/gospace/src/github.com/gin-gonic/gin/context.go:97 (0x53d8ea)
/Users/m/p/gospace/src/github.com/ansible-semaphore/semaphore/api/projects/project.go:39 (0x65704b)
/Users/m/p/gospace/src/github.com/gin-gonic/gin/context.go:97 (0x53d8ea)
/Users/m/p/gospace/src/github.com/gin-gonic/gin/logger.go:66 (0x54f21a)
/Users/m/p/gospace/src/github.com/gin-gonic/gin/context.go:97 (0x53d8ea)
/Users/m/p/Projects/semaphore/cli/main.go:72 (0x401aef)
/Users/m/p/gospace/src/github.com/gin-gonic/gin/context.go:97 (0x53d8ea)
/Users/m/p/gospace/src/github.com/gin-gonic/gin/recovery.go:45 (0x54ff81)
/Users/m/p/gospace/src/github.com/gin-gonic/gin/context.go:97 (0x53d8ea)
/Users/m/p/gospace/src/github.com/gin-gonic/gin/gin.go:284 (0x544542)
/Users/m/p/gospace/src/github.com/gin-gonic/gin/gin.go:265 (0x544177)
/usr/local/Cellar/go/1.6/libexec/src/net/http/server.go:2081 (0x61e44e)
/usr/local/Cellar/go/1.6/libexec/src/net/http/server.go:1472 (0x61acfe)
/usr/local/Cellar/go/1.6/libexec/src/runtime/asm_amd64.s:1998 (0x45f831)
```

Reproduction steps
1. Add a project
1. Click task template
1. Click new template
1. Partially fill out the list
1. Click create
1. Behold explosion

**Comment by joostjacobs** [comment]
```4. Partially fill out the list``` - if that means you did not select an SSH key because you had not yet added one, semaphore will indeed explode as on database level it has a foreign key constraint for an ssh key. This had me stumped as well on the first try, as the error in the front end is a large red X and the number 500.

The frontend SHOULD, in my opinion, give more clarity on why things are exploding. If an SSH key is mandatory/required, the front end should communicate that to the user about the requirement. In the event that things DO explode, the front end SHOULD be able to provide more information instead of just the HTTP status code.

That is at least my opinion.
