### ISSUE TITLE
Provided hosts list is empty, only localhost is available

### ISSUE THREAD

**Issue by kootstra** [ansible-semaphore/semaphore#177]
Running Semaphore 2.0.4  using the [dsmorse/semaphore-docker](https://hub.docker.com/r/dsmorse/semaphore-docker/) docker image.  When running a task I get an error that the provided hosts list is empty, although I have specified them.

The playbook I am running is the [lamp_simple_rhel7](https://github.com/ansible/ansible-examples/tree/master/lamp_simple_rhel7) example I have downloaded from [ansible/ansible-examples](https://github.com/ansible/ansible-examples) github site. This example has been loaded into a locally running [Go Git Service](https://gogs.io/) docker image, 

When running a task the playbook is correctly checked out from GoGS and the following log output is generated: 

```
14:34:00: Started: 45

14:34:00: access key GoGSkey installed
14:34:00: Updating repository
14:34:00: From gogs:/Repo/test
14:34:00:  * branch            master     -> FETCH_HEAD
14:34:00: Already up-to-date.
14:34:00: access key GoGSkey installed
14:34:00: installing static inventory
14:34:00:  [WARNING]: provided hosts list is empty, only localhost is available
14:34:00: 
14:34:00: PLAY [apply common configuration to all nodes] *********************************
14:34:00: skipping: no hosts matched
14:34:00: 
14:34:00: PLAY [configure and deploy the webservers and application code] ****************
14:34:00: skipping: no hosts matched
14:34:00: 
14:34:00: PLAY [deploy MySQL and configure the databases] ********************************
14:34:00: skipping: no hosts matched
14:34:00: 
14:34:00: PLAY RECAP *********************************************************************
14:34:00: 
```

The hosts that have been mentioned in the [hosts file](https://github.com/ansible/ansible-examples/blob/master/lamp_simple_rhel7/hosts) are the following: 

```
[webservers]
webserver.local

[dbservers]
dbserver.local
```

In Semaphore I have configured the environment as the following: 

```
"hosts=webserver.local"
```

but since there is no example, I don't know if this is he right syntax. It does speak about JSON, but that doesn't explain what the format is that should be applied. So, a little help is appreciated to get this example up and running.

**Comment by pianzide1117** [comment]
+1

**Comment by pianzide1117** [comment]
@kootstra  I just found it is because the temp path is not right. You`d better config the tmp path with a absolute path. That work for me . I bold it below.
{
        "mysql": {
                "host": "10.0.200.115:3306",
                "user": "ansible",
                "pass": "888888",
                "name": "semaphore"
        },
        "port": "",
        "bugsnag_key": "",
        **"tmp_path": "/root/asi",**
        "cookie_hash": "Cm1JD0jO61vOpiOThiPRLvuppfBVcpeayGcChwX0ewQ=",
        "cookie_encryption": "88oXbFpMXsd4ZVaHGNZgrvxsZ+AIWMWEmNJ8lI/59LQ="
 }

**Comment by Yakha** [comment]
@pianzide1117 , I've the same issue : 
`00:25:34: Using /etc/ansible/ansible.cfg as config file
00:25:34:  [WARNING]: provided hosts list is empty, only localhost is available`

where my semaphore conf file like follow : 
`{
 	"mysql": {
 		"host": "127.0.0.1:3306",
 		"user": "XXXX",
 		"pass": "XXXXX",
 		"name": "semaphore"
 	},
 	"port": "",
 	"bugsnag_key": "",
 	"tmp_path": "/etc/ansible/playbook",
 	"cookie_hash": "0EXw1O7gkcnjLvj+b05w3fJBUELn9EB/qsOHNphAoAI=",
 	"cookie_encryption": "hsHGFIrRHnka9dkl2ZQEwM+KyWoYBJLdaVWzFEMYjAU="
 }`

Have you an idea ? :o

**Comment by pianzide1117** [comment]
@Yakha I just tried to use inventory which config in semaphore web , and did nothing to ansible.cfg. maybe it is working for you .

**Comment by Koxx3** [comment]
I have the same issue :(

**Comment by matejkramny** [comment]
Try running the command that semaphore runs: `ansible-playbook ...`

**Comment by Koxx3** [comment]
I am tryong to execute playbooks from Semaphore UI.

**Comment by matejkramny** [comment]
I'm trying to establish if it works without semaphore. If it works without semaphore, it's something to fix on semaphore, otherwise it's an error in your playbook or ansible.

**Comment by Koxx3** [comment]
I found the issue ... I was on the Semaphore side.
check here for the solution : https://github.com/ansible-semaphore/semaphore/issues/226
