### ISSUE TITLE
Can you provide a flatpak

### ISSUE THREAD

**Issue by cmonty14** [ansible-semaphore/semaphore#1774]
Hi,
for easy deployment/installation you provide a [Snap](https://snapcraft.io/semaphore).

Could you please provide a [Flatpak](https://flatpak.org/), too?

THX

**Comment by tboerger** [comment]
A flatpak doesn't make sense for web applications, flatpaks are usually used for desktop applications and not for web-based server applications.

**Comment by cmonty14** [comment]
Do you advise to run a container then?
Because Snap is not an option on MicroOS.

**Comment by tboerger** [comment]
Absolutely! For servers I would always suggest to use the container. The runtime doesn't matter being it Docker, Containerd or Podman.

**Comment by tboerger** [comment]
I'm closing this issue because it doesn't make sense for headless server applications. If @fiftin  got a different opinion on that he can easily reopen the feature request.
