### ISSUE TITLE
Postfix email integration not working

### ISSUE THREAD

**Issue by imagdy83** [ansible-semaphore/semaphore#1775]
I've configured postfix on the same server where semaphore is installed and sent a test email with it and it works fine, integrating it with semaphore however there are no emails being sent

**Comment by tboerger** [comment]
Please provide more details how you have installed and configured semaphore.

**Comment by imagdy83** [comment]
We installed the linux version of semaphore on ubuntu, configured it as a service, used the config.json file to apply the configurations we needed, integrated it with SSO, and with the email part we used the following parameters

  "email_alert": true,
        "email_sender": "root@semaphore.knowisag.local",
        "email_host": "semaphore.knowisag.local",
        "email_port": "",
        "email_username": "",
        "email_password": "",
        "email_secure": false,

postfix is intalled on the same server, tested it as well and it can send emails

**Comment by tboerger** [comment]
And your can't find any information within the semaphore logs or the postfix queue?

**Comment by imagdy83** [comment]
no information within semaphore logs, or postfix queue no

**Comment by imagdy83** [comment]
any updates please

**Comment by tboerger** [comment]
Just went through all of that... Have you enabled alerting for you user? Otherwise no email gets sent.

![Screenshot from 2024-02-26 15-50-26](https://github.com/ansible-semaphore/semaphore/assets/156964/e533844a-20eb-4de9-9854-99b8ccc3a6af)

**Comment by tboerger** [comment]
This issue seem to be related to the wrong alert configuration per user as emails can be easily verified with mailhog.
