### ISSUE TITLE
Prevent leaking SSH key in `/tmp/semaphore`?

### ISSUE THREAD

**Issue by WilliamDEdwards** [ansible-semaphore/semaphore#1779]
From what I understand, before a play, Semaphore writes the SSH key used to a file in `/tmp/semaphore`, which is removed after the play.

I suppose that file's contents could be dumped - and therefore logged - inside a playbook by malicious users. Am I misunderstanding the security model? Or are users running playbooks regarded as 'trusted'?

**Comment by WilliamDEdwards** [comment]
Upon actually inspecting the code (sorry, should've done that before taking the easy route of asking :) ), it looks like an SSH agent is started instead of writing a file: https://github.com/ansible-semaphore/semaphore/blob/develop/db/AccessKey.go#L159

This question still stands for vault passwords, though.

**Comment by tboerger** [comment]
Since there is nothing like an ssh agent for the vault password I can't see any alternative to writing the vault password to the disk.

**Comment by darcystan** [comment]
That's the default location, but you can specify a different location in the config.json file. A location owned by the semaphore service user (and other permissions removed), would limit access to the semaphore user and would be much more secure than the global /tmp location.

**Comment by WilliamDEdwards** [comment]
> That's the default location, but you can specify a different location in the config.json file. A location owned by the semaphore service user (and other permissions removed), would limit access to the semaphore user and would be much more secure than the global /tmp location.

As long as the file is owned by the Semaphore system user, I can dump it on the Ansible controller.

**Comment by tboerger** [comment]
This could potentially get resolved if proot gets implemented.

**Comment by darcystan** [comment]
> > That's the default location, but you can specify a different location in the config.json file. A location owned by the semaphore service user (and other permissions removed), would limit access to the semaphore user and would be much more secure than the global /tmp location.
> 
> As long as the file is owned by the Semaphore system user, I can dump it on the Ansible controller.

I'm curious if this is different for any other Ansible controller? If so, how do they mitigate it?

**Comment by tboerger** [comment]
Semaphore has started to integrate an SSH agent to prevent any credential leak.
