### ISSUE TITLE
Semaphore really slow because of serving css file

### ISSUE THREAD

**Issue by macau23** [ansible-semaphore/semaphore#1780]
The semaphore UI is really slow, and web developer tools show it is taking 15 seconds to load /css/app.888d9ffe.css

Edit: looks like a problem within our network, but this does show up a slow point for semaphore

**Comment by tboerger** [comment]
I have created a pr which changes the static asset behavior and which adds some cache headers.

But generally serving the assets takes milliseconds for me.

**Comment by tboerger** [comment]
As already mentioned this issue is related to your network as this generally works pretty well.
