### ISSUE TITLE
 Prevent leaking Database password in Logs

### ISSUE THREAD

**Issue by skywalker123p** [ansible-semaphore/semaphore#1781]
Hello,

 Prevent leaking Database password in Logs

In Logs database password is visible in plain text. Please don't log any sensitive information like Password, SSH keys in logs. thanks.

**Comment by tboerger** [comment]
That would be possible if the docker image stops using the setup command which would require a full coverage of environment variables.

**Comment by mjknoxie** [comment]
duplicate of #1308

**Comment by tboerger** [comment]
No, it's not a duplicate. This issue refers to the database password that leaks into the logs if semaphore starts initially based on the container.

**Comment by mjknoxie** [comment]
I see, lot's of leaky passwords then. Hopefully it finds its way to being resolved.

**Comment by fiftin** [comment]
@mjknoxie what passwords do you mean?

**Comment by mjknoxie** [comment]
@fiftin detailed in https://github.com/semaphoreui/semaphore/issues/1308 

I thought this report was a duplicate of 1308, but @tboerger said it's not, which is fine.

**Comment by tboerger** [comment]
This issue can easily getting solved by avoiding the setup execution and relying on environment variables only. The other issue can only be resolved by some kind of ephemeral chroot environment which automatically cleans up.

**Comment by mjknoxie** [comment]
Not sure if the op has retried the latest beta, but that closed #1308 for me. Thanks!

**Comment by tboerger** [comment]
The wrapper script which generates the configuration and leaks initially the database password haven't been changed so far, that's why this issue is still open.

**Comment by fiftin** [comment]
Hi @mjknoxie new release doesn't use files to temporary store passwords and keys.  Semaphore uses Stdin to send passwords to Ansible.

**Comment by fiftin** [comment]
@skywalker123p thank you, we removed printing DB creds from Docker container.
