### ISSUE TITLE
Error semaphore docker

### ISSUE THREAD

**Issue by marcus1502** [ansible-semaphore/semaphore#1786]
Olá,

Estou com um erro na hora que executo um playbook onde e criado uma conta de serviço, no semaphore criei a credencial de acesso com permissão root, mais quando executo da o erro abaixo:

fatal: [10.62.0.27]: FAILED! => {"changed": false, "msg": "useradd: Permission denied.\nuseradd: cannot lock /etc/passwd; try again later.\n", "name": "admin-svc-sc", "rc": 1}

![image](https://github.com/ansible-semaphore/semaphore/assets/19429592/028d0865-2299-4049-815e-73044325d7df)

**Comment by tboerger** [comment]
You should ask questions in english. Beside that the error is quite obvious and isn't an semaphore issue. Do this as root and it would work.
