### ISSUE TITLE
Error bundler.js:9 

### ISSUE THREAD

**Issue by ados1991** [ansible-semaphore/semaphore#179]
(semaphore)[root@ansible_semaphore semaphore]# ./make.sh watch
Creating util/bindata.go with file proxy

/var/www/ansible-semaphore/goenv/semaphore/src/github.com/ansible-semaphore/semaphore/public/bundler.js:9
bundle.forEach(file => {
                     ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3

**Comment by ados1991** [comment]
Fix with this : 
file bundle.js
var fs = require('fs'),
	async = require('async'),
	bundle = require('./bundle.json'),
	out = fs.createWriteStream('./js/bundle.js'),
	path = require('path'),
	child_process = require('child_process'),
	uglify = null;

bundle.forEach(function(file) {
	var o = {}
	if (typeof file == 'object') {
		o = file;
		file = o.src;
	}

	if (file.substr(0, 1) != '/') {
		file = '/js/' + file;
	}

	file = file + '.js';

	console.log(file);
	var contents = fs.readFileSync('.' + file);

	out.write('\n/* BUNDLED FILE: ' + file + ' */\n')
	if (o.pre) {
		out.write(o.pre + '\n');
	}

	out.write(contents + '\n');

	if (o.post) {
		out.write(o.post + '\n');
	}
});

Can i contribute to the project, because we will use it in my company ?

Thanks

**Comment by matejkramny** [comment]
Hi there! You need a modern version of node.js or run with the `--harmony` flag since the arrow function is an ES6 feature.

You are very welcome to contribute, let me know if you need help with anything.

Matej
