### ISSUE TITLE
Docker: twice npm installed

### ISSUE THREAD

**Issue by bibby** [ansible-semaphore/semaphore#18]
The docker image contains two fully installed application instances,
one in `/srv/semaphore` and the other in `/usr/src/app/`.

This is because of the nature of the [iojs:onbuild](https://github.com/iojs/docker-iojs/blob/c48cc2ebffcb191ef090f5addfd52162f0ad2de2/1.6/onbuild/Dockerfile) image. It uses [ONBUILD](https://docs.docker.com/reference/builder/#onbuild) directives that both copy and install the application dependencies at `/usr/src/app` as the first steps in a dockerfile that choose it as a parent. This can be seen at the top of the build output.

```
Sending build context to Docker daemon 
Step 0 : FROM iojs:onbuild
# Executing 3 build triggers
Trigger 0, COPY package.json /usr/src/app/
Step 0 : COPY package.json /usr/src/app/
Trigger 1, RUN npm install
Step 0 : RUN npm install
 ---> lots of npm
Trigger 2, COPY . /usr/src/app
Step 0 : COPY . /usr/src/app
 ---> d6bb6ad37b43
```

Afterwards, the semaphore docker file does the same, but at `/srv/semaphore`.

Recommend either shifting away from the `:onbuild` tag to `:1.6` or changing the expected app root to the one assumed by the onbuild image.

**Comment by matejkramny** [comment]
The dockerfile isn't using :onbuild tag any more, so none of this should be happening.
