### ISSUE TITLE
Error Cloning Repository when running task

### ISSUE THREAD

**Issue by tboerger** [ansible-semaphore/semaphore#1806]
### Discussed in https://github.com/ansible-semaphore/semaphore/discussions/952

<div type='discussions-op-text'>

<sup>Originally posted by **powej2** May 31, 2022</sup>
I am new to Semaphore and have installed and configured it.

I am using a internal GITLAB server.

I am having difficulty trying to resolve this error:

```
1:42:22 PM Task 4 added to queue
1:42:25 PM Preparing: 4
1:42:25 PM Prepare TaskRunner with template: Add_user
1:42:25 PM Cloning Repository https://gitlab.xxx.com/user/capture-ansible.git
1:42:25 PM Cloning into 'repository_1_1'...
1:42:25 PM fatal: bad numeric config value '0
1:42:25 PM ' for 'GIT_TERMINAL_PROMPT': invalid unit
1:42:25 PM Failed updating repository: exit status 128
```

I could not find any assistance on Google or on GITHUB that seemed to help me resolve this.</div>

**Comment by fiftin** [comment]
We have it in docs: https://docs.semui.co/administration-guide/troubleshooting#fatal-bad-numeric-config-value-0-for-git_terminal_prompt-invalid-unit

**Comment by tboerger** [comment]
Great, wegen it's documented this issue can get closed.
