### ISSUE TITLE
Failed to connect to the host via ssh: No user exists for uid 1000

### ISSUE THREAD

**Issue by platteel** [ansible-semaphore/semaphore#1815]
Connecting to a server with SSH using a Username/Password or providing a SSH key results in a strange error on the latest clean Semaphore installation (2.9.45) using docker (ARM version). 
**Failed to connect to the host via ssh: No user exists for uid 1000**

When running the same command and script from my Linux terminal on Windows with Ansible, it just works fine.

I just can't figure out what is going wrong. Any help is welcome

```
7:45:55 PM                Started: 8
7:45:55 PM                Run TaskRunner with template: Ping
7:45:55 PM                Preparing: 8
7:45:55 PM                Task 8 added to queue
7:45:56 PM                Updating Repository https://gitea.novaatom.com/bitsbeyond/ansible.git
7:45:56 PM                From https://gitea.novaatom.com/bitsbeyond/ansible
7:45:56 PM                * branch main -> FETCH_HEAD
7:45:56 PM                installing static inventory
7:45:56 PM                No collections/requirements.yml file found. Skip galaxy install process.
7:45:56 PM                No roles/requirements.yml file found. Skip galaxy install process.
7:45:57 PM                task path: /tmp/semaphore/repository_1_1/ping/ping.yaml:7
7:45:57 PM                become_method: sudo
7:45:57 PM                TASK [Example from an Ansible Playbook] ****************************************
7:45:57 PM                
7:45:57 PM                PLAY [Ping all servers ********************************************************
7:45:57 PM
7:45:57 PM                1 plays in ping/ping.yaml
7:45:57 PM                forks: 5
7:45:57 PM                extra_vars: ('@/tmp/semaphore/access_key_833775013', '@/tmp/semaphore/access_key_164556117', '{"semaphore_vars":{"task_details":{"id":8,"username":"admin"}}}')
7:45:57 PM                inventory: ('/tmp/semaphore/inventory_8',)
7:45:57 PM                tags: ('all',)
7:45:57 PM                Running playbook failed: exit status 4
7:45:57 PM                <192.168.1.231> ESTABLISH SSH CONNECTION FOR USER: admin
7:45:57 PM                <192.168.1.231> SSH: EXEC sshpass -d10 ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'User="admin"' -o ConnectTimeout=10 -o 'ControlPath="/tmp/semaphore/.ansible/cp/c4bdce110a"' 192.168.1.231 '/bin/sh -c '"'"'echo ~admin && sleep 0'"'"''
7:45:57 PM                <192.168.1.231> (255, b'', b'No user exists for uid 1000\r\n')
7:45:57 PM                fatal: [192.168.1.231]: UNREACHABLE! => {
7:45:57 PM                "changed": false,
7:45:57 PM                "msg": "Failed to connect to the host via ssh: No user exists for uid 1000",
7:45:57 PM                "unreachable": true
7:45:57 PM                }
7:45:57 PM
7:45:57 PM                PLAY RECAP *********************************************************************
7:45:57 PM                192.168.1.231 : ok=0 changed=0 unreachable=1 failed=0 skipped=0 rescued=0 ignored=0
7:45:57 PM
7:45:57 PM                script declined parsing /tmp/semaphore/inventory_8 as it did not pass its verify_file() method
7:45:57 PM                ansible-playbook [core 2.14.5]
7:45:57 PM                config file = None
```

**Template**
<img width="511" alt="Screenshot 2024-03-07 200646" src="https://github.com/ansible-semaphore/semaphore/assets/87372585/f6141f21-3171-4313-8ce8-7fba47bb8f04">

**Inventory**
<img width="326" alt="Screenshot 2024-03-07 200615" src="https://github.com/ansible-semaphore/semaphore/assets/87372585/3098b9cc-9f6b-4b9d-8e2a-e83c8a92901d">

**SSH from within the container**
<img width="587" alt="Screenshot 2024-03-07 200909" src="https://github.com/ansible-semaphore/semaphore/assets/87372585/c04ada75-6490-46e3-82f8-512fbda6aaa4">

**Docker Compose setup**
<img width="343" alt="Screenshot 2024-03-07 201120" src="https://github.com/ansible-semaphore/semaphore/assets/87372585/9989931c-22bb-4860-bf81-1139664a3ace">

<img width="585" alt="Screenshot 2024-03-07 201155" src="https://github.com/ansible-semaphore/semaphore/assets/87372585/e34a25b4-f079-48a9-a58d-7df638641b88">

**Comment by tboerger** [comment]
It would suprise me if this works somewhere else as this message comes from the target system and doesn't look like this is related so Semaphore.

**Comment by platteel** [comment]
Using Ubuntu 20.04 to login to the remote host using ssh and a certificate works just fine.

<img width="749" alt="Screenshot 2024-03-08 095815" src="https://github.com/ansible-semaphore/semaphore/assets/87372585/4559e2ff-8886-48b8-846d-dca46ea514de">

**Comment by tboerger** [comment]
What gets printed if you execute `id` within the Semaphore container? This should show UID 1001 as this is the Semaphore user.

**Comment by platteel** [comment]
Running `Id` shows UID 1000 (none). When I list all available ID’s in the container, then you will see that UID 1001 (Semaphore) is present. The same happens on the Dev container build (Arm)

**Comment by tboerger** [comment]
The container references only uid 1001... Is it possible that you start the container with something like --user?

**Comment by platteel** [comment]
> The container references only uid 1001... Is it possible that you start the container with something like --user?

Yes, I used a bad example for setting up Semaphore that included -user: "${PUID}:${PGID}". I didn't see the reverence of the problem being related to this setting, but I should have known.
I reverted to the default example on Semaphore docs and removed -User and the unnecessary host-path references. 
It now works, thanks for helping.

**Comment by tboerger** [comment]
Great that it works now ;)
