### ISSUE TITLE
Unable to specify a Git repository on a port other than 22?

### ISSUE THREAD

**Issue by niieani** [ansible-semaphore/semaphore#182]
It seems like it's not possible to have the repository on a port other than 22. Please correct me if I'm wrong.

**Comment by kootstra** [comment]
This is something I ran into as well. The only way I've been able to overcome it was by creating a /root/.ssh/config file and map the ssh key to the mapping

```
Host gitsrv
    Hostname gitserver.local
    User git
    port 8022
	IdentityFile ~/.ssh/id_rsa
```
In your Semaphore config you refer to the repository as : gitsrv:/user/test.git

It goes without saying that modifying a container like this is not inline with best practices, and ideally you'd create an image of your own, basing it on the semaphore image with the additional keys and modifications. Then use that image to base your containers on.

**Comment by niieani** [comment]
As long as we need to modify the image of Semaphore, it would be good to also add support for local repositories (specified by path, rather than Git URL).

**Comment by matejkramny** [comment]
Support for local paths is already possible @niieani.

Instead of the git URL, specify a local path

**Comment by thetooth** [comment]
Not sure if this has been fixed or no one knows git urls, but the following works on 2.0.4-2.1.0: ssh://git@domain.com:10022/user/repo.git there is no extra colon needed just add your path directly after the port.
