### ISSUE TITLE
No administrator of the project.

### ISSUE THREAD

**Issue by brusmolot** [ansible-semaphore/semaphore#185]
Hello. Project creator clicked delete administrator privileges, and now there is the administrator of the project.

![git-isuue](https://cloud.githubusercontent.com/assets/21698230/18190392/d52ce910-70ec-11e6-9cf3-6c02c710a665.png)

**Comment by craftbyte** [comment]
We will try to fix that in the next release, in the meantime you can assign the admin value in the database.

**Comment by brusmolot** [comment]
Thank you

**Comment by matejkramny** [comment]
fixed with https://github.com/ansible-semaphore/semaphore/commit/bc342313df847ec0968ebb3ac2d379562585ecb4
