### ISSUE TITLE
Provide a field for name/description of a Task Template

### ISSUE THREAD

**Issue by gcavalcante8808** [ansible-semaphore/semaphore#188]
Hello Folks,

I Think that will be a improvement if we have the option to set a 'name' or 'description' for a given template task. Eg:

I have different groups and I have one playbook that receives de 'hosts var' through --extra-vars; in this, case it would be awesome if we can have something like:

Name                                        Playbook            SSH Key     Inventory   Environment     Repository  
Homolog(USA)                     homolog.yml    MyKey       MyInventory                         PlayBook-App
Homolog(BRA)                     homolog.yml    MyKey       MyInventory                         PlayBook-App
Homolog(ESP)                     homolog.yml            MyKey       MyInventory                         PlayBook-App

In this example the only difference between the three tasks is the fact that --extra-vars receive different values, like "targets=usa", making just one playbook with three possible configurations.

Otherwise, if I need some type of visual differential between my tasks then I need to copy the playbook and hardcode the group-name into every file ...

Is this an acceptable request?

**Comment by pselibas** [comment]
+1
