### ISSUE TITLE
Users page does not updated correctly

### ISSUE THREAD

**Issue by parkjaeil0x01** [ansible-semaphore/semaphore#1884]
![image](https://github.com/semaphoreui/semaphore/assets/118321813/08fb8535-d7da-4997-a555-77aa4b7981cc)

as you can see, you can find the "testuser1" in the DB table but,

![image](https://github.com/semaphoreui/semaphore/assets/118321813/cad928d3-8d50-4646-b6eb-b47970ce52aa)

in the semaphore 'Users' page, you cannot see the "testuser1".

There is a history of previously updating to the BETA version for a while and then updating to the STABLE version again.
Did this have an impact?

What I updated before:
v2.9.45 -> v2.9.52-beta -> v2.9.64

**Comment by parkjaeil0x01** [comment]
@fiftin 
Thank you for your fast reaction to this issue.
I've just tested your develop branch's docker image to my semaphore server but my testuser1 account still does not show for now.

How can I fix it?

Thank you again and have a great day.


Edited) Oh. sorry, develop branch wasn't deployed to dev... I just knew that. :(

**Comment by fiftin** [comment]
@parkjaeil0x01 can it be a cache?

Fix already in beta: `docker pull semaphoreui/semaphore:v2.9.65-beta`.
