### ISSUE TITLE
Run a task on a single host

### ISSUE THREAD

**Issue by pselibas** [ansible-semaphore/semaphore#190]
I use the -l command line option allot. This allows me to target a playbook to a single host in my inventory file. This would be very useful in semaphore.

In fact I would propose the following:
1) When a user executes a task, give the user the ability to select an inventory at the time of execution if no inventory is selected. 
2) In addition to this, a user could also select a single or subset of the inventory selected. Basically a list of check boxes on the webpage for that selected inventory.

**Comment by rakshazi** [comment]
@pselibas you can achieve this by passing `["-l", "yourhostlimit"]` in task template edit dialog in field "Extra CLI arguments"

**Comment by mmalchuk** [comment]
@rakshazi what about the API call? Model schema don't have extra_arguments

**Comment by rakshazi** [comment]
Didn't use this way, I don't know
