### ISSUE TITLE
Missing python module netaddr

### ISSUE THREAD

**Issue by bufanda** [ansible-semaphore/semaphore#1925]
Using the Jinja2 Filter 'ansible.utils.ipaddr' results in error with Message

```
"The ipaddr filter requires python's netaddr be installed on the ansible controller"
```

I am using the Docker Image  `semaphoreui/semaphore` in the latest version from docker hub.

This is a standard filter which comes with ansible and is installed per default 

https://docs.ansible.com/ansible/latest/collections/ansible/utils/docsite/filters_ipaddr.html

Shouldn't all default modules, collection and packages have their dependencies have installed per default too?

How can I solve this? Do I need to build the Docker Image myself and add all dependencies?
Couldn't find a solution to this problem or how to install custom python packages.

**Comment by fiftin** [comment]
Hi @bufanda it is external collection: https://galaxy.ansible.com/ui/repo/published/ansible/utils/

You can add it via `collections/requirements.yml`:

```yml
---
collections:
- ansible.utils
```
