### ISSUE TITLE
Console output prints double 

### ISSUE THREAD

**Issue by parkjaeil0x01** [ansible-semaphore/semaphore#1944]
![image](https://github.com/semaphoreui/semaphore/assets/118321813/842d9bd4-6185-46c1-937b-4e9dec2dd3ef)

For some time now, I have been experiencing a problem where the console output is output twice.

I am using semaphore as a docker container.
After the container restarts, the problem is resolved for a while, but after some time, the same problem repeats.

**Comment by fiftin** [comment]
It has been fixed in v2.9.64. What version do you use?

**Comment by parkjaeil0x01** [comment]
> It has been fixed in v2.9.64. What version do you use?

I'm using v2.9.65-beta now.

Edited)
I just rolled back my semaphore version v2.9.65-beta to v2.9.64 and the problem has been solved.
I thought the v2.9.65-beta was solved with the console output problem too as v2.9.64.

Thank you sir!
