### ISSUE TITLE
404 on ssh key creation

### ISSUE THREAD

**Issue by simoare** [ansible-semaphore/semaphore#196]
Guys,

i am using the v2.0.4/semaphore_linux_amd64 and i am not able to create a new ssh key for example, i got a 404 error. it looks to be already fixed but i suppose maybe a regression or something like that.  i have the same problem with 2.0.3 as well. the error is "could not add key:400" 

-- semaphore start

GIN] 2016/10/07 - 09:26:51 | 200 |     170.609µs | 127.0.0.1 |   GET     /
[GIN] 2016/10/07 - 09:26:51 | 200 |    7.173216ms | 127.0.0.1 |   GET     /public/js/bundle.js
[GIN] 2016/10/07 - 09:26:51 | 200 |    1.693541ms | 127.0.0.1 |   GET     /public/css/semaphore.css
[GIN] 2016/10/07 - 09:26:52 | 404 |      29.337µs | 127.0.0.1 |   GET     /favicon.ico
[GIN] 2016/10/07 - 09:26:53 | 200 |     659.899µs | 127.0.0.1 |   GET     /public/vendor/fontawesome/fonts/fontawesome-webfont.woff2
[GIN] 2016/10/07 - 09:26:56 | 403 |      43.284µs | 127.0.0.1 |   GET     /api/user

-- after key creation:

[GIN] 2016/10/07 - 09:29:02 | 200 |     104.508µs | 127.0.0.1 |   GET     /public/html/projects/keys/add.html
[GIN] 2016/10/07 - 09:30:25 | 400 |    1.747264ms | 127.0.0.1 |   POST    /api/project/1/keys

Cheers,
Simone

**Comment by simoare** [comment]
[GIN] 2016/10/07 - 09:29:02 | 200 |     104.508µs | 127.0.0.1 |   GET     /public/html/projects/keys/add.html
[GIN] 2016/10/07 - 09:30:25 | 400 |    1.747264ms | 127.0.0.1 |   POST    /api/project/1/keys

**Comment by rakshazi** [comment]
@simoare may be you have no permission for this aciton? Check your permissions in `Team` page (in project)

**Comment by jeski** [comment]
I've a similar issue, using semaphore v2.1.0 (ubuntu xenial) Keys aren't created.  The form accepts the input for the keys, yet when selecting the keys from the repository page, no keys are available,

This from the log:

2017/02/12 10:44:17 [Recovery] panic recovered:
GET /api/project/1/keys HTTP/1.1
Host: localhost:3000
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.5
Cache-Control: no-cache
Connection: keep-alive
Cookie: semaphore=MTQ4NjkxMDQxMHxveVZTUXc0d3VmOUNWUm5TVGlySS1Db1BYTnRUMnJxWmZRUnFnYjlNTlZmVTFYTkt2VGw4VjR1UjgtRUJ4MVFXZFlaNy1ucWdZLVFZamtrUlozeVZ1SW89fI-agIeNRuEpfdd87WcGTGPeH5iiF_J6HiecuCjJs1D5
Referer: http://localhost:3000/project/1/keys
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0


Error 1054: Unknown column 'removed' in 'field list'
/usr/local/go/src/runtime/panic.go:458 (0x42adc3)
/Users/m/p/gospace/src/github.com/bugsnag/bugsnag-go/bugsnag.go:52 (0x50e003)
/usr/local/go/src/runtime/asm_amd64.s:479 (0x4588ac)
/usr/local/go/src/runtime/panic.go:458 (0x42adc3)
/Users/m/p/gospace/src/github.com/ansible-semaphore/semaphore/api/projects/keys.go:48 (0x61335a)
/Users/m/p/gospace/src/github.com/gin-gonic/gin/context.go:97 (0x51573a)
/Users/m/p/gospace/src/github.com/ansible-semaphore/semaphore/api/projects/project.go:39 (0x615743)
/Users/m/p/gospace/src/github.com/gin-gonic/gin/context.go:97 (0x51573a)
/Users/m/p/gospace/src/github.com/gin-gonic/gin/logger.go:66 (0x524167)
/Users/m/p/gospace/src/github.com/gin-gonic/gin/context.go:97 (0x51573a)
/Users/m/p/gospace/src/github.com/ansible-semaphore/semaphore/cli/main.go:72 (0x4016e2)
/Users/m/p/gospace/src/github.com/gin-gonic/gin/context.go:97 (0x51573a)
/Users/m/p/gospace/src/github.com/gin-gonic/gin/recovery.go:45 (0x524ffa)
/Users/m/p/gospace/src/github.com/gin-gonic/gin/context.go:97 (0x51573a)
/Users/m/p/gospace/src/github.com/gin-gonic/gin/gin.go:284 (0x51b6be)
/Users/m/p/gospace/src/github.com/gin-gonic/gin/gin.go:265 (0x51afa0)
/usr/local/go/src/net/http/server.go:2202 (0x5e0c7d)
/usr/local/go/src/net/http/server.go:1579 (0x5dd5e7)
/usr/local/go/src/runtime/asm_amd64.s:2086 (0x45b3d1)

**Comment by strangeman** [comment]
Strange, adding and deleting keys working well for me. Can you record a screen capture session and provide additional info (key examples, browser info)?

**Comment by jeski** [comment]
will do.

**Comment by twhiston** [comment]
closing due to age
