### ISSUE TITLE
config interface option does not accept "lo"

### ISSUE THREAD

**Issue by mindcloud69** [ansible-semaphore/semaphore#1962]
semaphore version v2.9.64

In my config I want to specify that the server only listens on localhost so I put lo in the interface option. 

`"interface": "lo", `

I do not get an exit code just.
Apr 20 11:18:12 xxx systemd[1]: semaphore.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- The unit semaphore.service has entered the 'failed' state with result 'exit-code'.

Am I missing an obvious way to force the server to only listen on localhost? I have a reverse proxy setup and would like to prevent non https access to port 3000.

**Comment by tboerger** [comment]
The naming is misleading, use 127.0.0.1 as value.

**Comment by mindcloud69** [comment]
Thank you that worked!
