### ISSUE TITLE
Whats is the latest version? 2.9.70?

### ISSUE THREAD

**Issue by zimbres** [ansible-semaphore/semaphore#1965]
There is a container with version 2.9.70 but 2.9.64 seems to be the latest one.

The tools like Renovate, Watchtower, etc... get confused.

**Comment by tboerger** [comment]
Generally there had the version 2.9.70 been tagged, but it is missing the GitHub release for that tag. Maybe @fiftin can shed light on the issue.

**Comment by fiftin** [comment]
Yes, I forgot to publish release on GitHub. But now it 2.9.75.
