### ISSUE TITLE
The task log is not displayed

### ISSUE THREAD

**Issue by kovalewvladimir** [ansible-semaphore/semaphore#1968]
The large log is not displayed on the web. It crashes with an error
```
vue.runtime.esm.js:1897 RangeError: Maximum call stack size exceeded
    at String.replace (<anonymous>)
    at f (ansi_to_html.js:507:17)
    at D (ansi_to_html.js:517:7)
    at e.value (ansi_to_html.js:605:7)
    at Object.formatLog (main.js:18:53)
    at TaskLogView.vue:1:1858
    at a.Nt [as _l] (vue.runtime.esm.js:2646:16)
    at a.D (TaskLogView.vue:1:1545)
    at e._render (vue.runtime.esm.js:3569:22)
    at a.r (vue.runtime.esm.js:4081:21)
```

![image](https://github.com/semaphoreui/semaphore/assets/6761962/26b7d1a8-dde7-4573-b28a-8796207fa1e4)

I've identified that there is an issue with the ansi-to-html library. See the link for the problem description.
https://github.com/rburns/ansi-to-html/issues/87

**Comment by yashunkin** [comment]
Hello, I have the same issue. Any ideas how to fix it?

**Comment by Aric000** [comment]
Press ctrl+a in the black area to select all, looking if it's the question about font color

**Comment by kovalewvladimir** [comment]
![image](https://github.com/semaphoreui/semaphore/assets/6761962/038a2e6e-1570-44c3-9638-ac5f84ad59b8)

Empty

**Comment by kovalewvladimir** [comment]
The issue with the ansi-to-html JavaScript library.
There is a very simple and effective solution:
https://github.com/semaphoreui/semaphore/pull/1969

**Comment by kovalewvladimir** [comment]
> Press ctrl+a in the black area to select all, looking if it's the question about font color

The issue with the [ansi-to-html](https://github.com/rburns/ansi-to-html/issues/87) JavaScript library.
There is a very simple and effective solution: https://github.com/semaphoreui/semaphore/pull/1969

**Comment by fiftin** [comment]
Looks like we should use different library, for example https://www.npmjs.com/package/ansi_up

**Comment by kovalewvladimir** [comment]
> Looks like we should use different library, for example https://www.npmjs.com/package/ansi_up

Checked it out, the library does indeed solve our problem. I'll try to send a pull request as soon as I can.

**Comment by fiftin** [comment]
Fixed. Available in `develop`.
