### ISSUE TITLE
Time Mismatch on Project Activity page

### ISSUE THREAD

**Issue by kwadroke** [ansible-semaphore/semaphore#197]
Times on Project Activity are 5 hours off of the Task history times. The server's timezone is CDT (UTC -5). 
Is there somewhere I can adjust/override this to match?

Copy/paste from same task on http://server:3000/project/1

_Project Activity
10/7/16 **5**:43 AM: yumupdates_week1.yaml - Task ID 2 finished
10/7/16 **5**:43 AM: yumupdates_week1.yaml - Task ID 2 finished
10/7/16 **5**:42 AM: yumupdates_week1.yaml - Task ID 2 is running
10/7/16 **5**:42 AM: yumupdates_week1.yaml - Task ID 2 queued for running_ 

_Task history
yumupdates_week1.yaml10/7/16 **10**:42 AM_

I'm using the latest release version for x86_64

**Comment by rakshazi** [comment]
And in some cases, semaphore shows `-5` as time for play in task history list
![bug-with-time](https://cloud.githubusercontent.com/assets/3428087/21215116/c34f764c-c2a7-11e6-812c-4832c40a13c0.png)
