### ISSUE TITLE
v2.9.70 Database Migration Error

### ISSUE THREAD

**Issue by samcro1967** [ansible-semaphore/semaphore#1974]
Started getting the error below about 5 days ago using docker image semaphoreui/semaphore:latest.  Switching to semaphoreui/semaphore:v2.9.64 resolved the issue.  FYI Latest release on Github is v2.9.64.  Latest tag on Docker Hub is v2.9.70.

```
semaphore:/usr/local/bin$ ./semaphore migrate --config /etc/semaphore/config.json
Loading config
Validating config
Executing migration v2.9.70 (at 2024-04-27 14:22:54.770648308 +0000 UTC m=+0.062359398)...
 [2/57]WARN[0000]
 ERR! Query: alter table `option` change `value` `value` varchar(1000)

FATA[0000] Error 1812 (HY000): Tablespace is missing for table `semaphore`.`option`.
semaphore:/usr/local/bin$
````

**Comment by tboerger** [comment]
I think the migration itself is fine, but you got some corruption within your database: https://bobcares.com/blog/mysql-tablespace-is-missing-for-table/

**Comment by tboerger** [comment]
I'm closing this report for now, if you got more details to share which indicate a bug within Semaphore we could reopen this.
