### ISSUE TITLE
All users have administrator privileges

### ISSUE THREAD

**Issue by Nikopol315** [ansible-semaphore/semaphore#198]
I'm confused, why all users have administrator privileges(every user can change a password of other users)?

It seems to be a big security leak. Isn't it? 

If a user does not have an access to the project, it can easily change a password of another user, who has admin privileges. Then, it can login as a project administrator user and give the same admin privileges for the project to the any user

**Comment by Nikopol315** [comment]
It's the awesome project! Nice GUI to run ansible tasks. Many thanks to the author!

But, because of this issue, I'm not able to use it in my organisation :(

**Comment by rakshazi** [comment]
@Nikopol315 as for 2.0.4, only user with admin rights can perfom admin actions in project, but buttons (and links) still visibly for all users.
You can test it:
1. Create 2 users: `admin` (with admin rights for project) and `user` (without admin rights)
2. Try to remove or edit existing project with `admin` user - all ok, you can do that.
3. Try to remove or edit existing project with `user` user - you will see error on this actions.

**Comment by matejkramny** [comment]
Thanks for reporting

**Comment by akentosh** [comment]
Any ideas on when the fixes will be merged?

**Comment by matejkramny** [comment]
hmm soon hopefully. Haven't given much attention to this project recently unfortunately.

**Comment by twhiston** [comment]
fixed by #405
