### ISSUE TITLE
Playbook repository from self signed cert repo?

### ISSUE THREAD

**Issue by davey-dev** [ansible-semaphore/semaphore#199]
I am trying to run a playbook repository from gerrit but keep getting:

```
Cloning into 'repository_1'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Failed updating repository: exit status 128
```

**Comment by gcavalcante8808** [comment]
@davey-dev Its seems the same 'problem' about the SSH Strict Key Checking. Take a look at: https://github.com/gcavalcante8808/docker-semaphore#note-about-host-key-verification-failed

Probably the 'ssh-keyscan -H <SERVER> >> ~/.ssh/known_hosts' command 'fixes' the error.

**Comment by davey-dev** [comment]
The issue I have now is that it's failing to clone with:

`13:58:58: fatal: unable to access 'https://gerrit.internal/autit/ansible-roles/': server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none`

I had the same issue from command line until this issue:
`git config --global http.sslverify false`

But semaphore is still failing to clone.

**Comment by davey-dev** [comment]
I added the cert to:
/etc/ssl/certs/ca-certificates.crt

and it's cloning now.

**Comment by elico** [comment]
Any other solution?

**Comment by itheodoridis** [comment]
well, if you are using the docker image and docker-compose, you don't have much choice. The user running the app in the container is semaphore not root. So you can really do anything like update-ca-certificates or edit the ca-certificates file (probably better off). 
Your only choice there would be to modify the Dockerfile and build your own image. I am trying that now.

**Comment by elico** [comment]
@itheodoridis I am using AlmaLinux 8 VM and I have found a way to disable all certificate checks but that's not the optimal way.
I have added two environment variables which Shouldn't be used in general use case:
```
# /etc/systemd/system/semaphore.service
[Unit]
Description=Semaphore Ansible UI
Wants=network-online.target
After=network-online.target

[Service]
Type=simple
Environment=GIT_SSL_NO_VERIFY=true
Environment=ANSIBLE_HOST_KEY_CHECKING=False
ExecReload=/bin/kill -HUP $MAINPID
ExecStart=/usr/bin/semaphore --config /etc/semaphore/config.json server
SyslogIdentifier=semaphore
Restart=always

[Install]
WantedBy=multi-user.target
```

The:
Environment=GIT_SSL_NO_VERIFY=true
Environment=ANSIBLE_HOST_KEY_CHECKING=False

This resolve the issue in any case and these can be added into a Dockerfile but it will make the service less secure and more vulnerable if it can access the WWW directly.

I will look for another solution on AlmaLinux\RHEL\CENTOS etc... the cert store is for root ca's and most self signed certificates are considered a CA by themself and I will try to verify this with curl and openssl later on. 

******
This works for https of a specific host:
https://gist.github.com/elico/0f9f1fcaf188847bd0499dc5cb9a0c02

ie: `bash add-host-cert-to-local-store.sh self-signed-domain.example.com`

**Comment by itheodoridis** [comment]
Thank you, in a vm things are more flexible as you have supposedly sudo/root and can do many things. The best way is indeed to install the ca certificate because git doesn't like it at all when you disable verify.
I am trying to do it in docker, it seems a little more difficult but I have found there are possible some bugs to work out there. At least for an ssh repo. I am still investigating. Ideally this should have been foreseen in the build to allow for local installations of gitlab.
