### ISSUE TITLE
500 error on css/semaphore.css

### ISSUE THREAD

**Issue by Mooash** [ansible-semaphore/semaphore#20]
I don't know what I'm doing wrong, but I'm on Ubuntu 14.04 with docker version `1.5.0, build a8a31ef`.

I've followed the basic installed but I'm getting a 500 on the CSS file located at `http://domain/css/semaphore.css` which means the interface never loads. I get a 500 error.

`css/semaphore.less` does exist however and that loads fine.

What am I doing wrong?

**Comment by matejkramny** [comment]
I will get back to you.

**Comment by decker502** [comment]
I get the same problem

**Comment by zvfvrv** [comment]
I get the same problem

**Comment by matejkramny** [comment]
Please update your semaphore image.

The issue was that bower wasn't installed therefore some dependencies (such as fontawesome) wouldn't be downloaded.. The less file couldn't be compiled and everything just silently failed :P.

**Comment by zvfvrv** [comment]
Thx for fix. Now i have a problem with the login-page. I can't login with admin user, when i click log in button, server reload login page again.

**Comment by craftbyte** [comment]
@zvfvrv Can confirm this happens on a fresh install.

**Comment by zvfvrv** [comment]
@craftbyte yes, this happens with a new installation

**Comment by matejkramny** [comment]
I found the offending problem to be a strange environment variable which coincidentally exists (??) when semaphore is run.. the variable value is invalid, therefore the session store will not be able to use redis and silently fail.

Working on a fix.

**Comment by matejkramny** [comment]
The docker image is live.. Please test & let me know
