### ISSUE TITLE
Could I use UTF-8 as default character set for MySQL or others?

### ISSUE THREAD

**Issue by parkjaeil0x01** [ansible-semaphore/semaphore#2008]
Recently, I had to display Korean or other languages in the console output.

However, when the Ansible playbook was first executed and displayed on the semaphore, Korean was displayed normally, but when the playbook execution was completed and the saved record was reopened, Korean was displayed as '?' I found an issue where the text was all garbled.

![image](https://github.com/semaphoreui/semaphore/assets/118321813/a2077d3b-3689-40fd-9d41-aaa0cba0fafe)

To solve this, I checked the DB character set of my MySQL and confirmed that the default character set is as follows.

```sql
SELECT DEFAULT_CHARACTER_SET_NAME, DEFAULT_COLLATION_NAME
FROM information_schema.SCHEMATA
WHERE SCHEMA_NAME = 'semaphore_db';
```
```json
[
  {
    "DEFAULT_CHARACTER_SET_NAME": "latin1",
    "DEFAULT_COLLATION_NAME": "latin1_swedish_ci"
  }
]
```

Now, to change it to UTF-8, I ran the following query:

```sql
USE semaphore_db;

-- Generate ALTER TABLE statements for each table in the database
SELECT CONCAT('ALTER TABLE ', table_name, ' CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;')
FROM information_schema.tables
WHERE table_schema = 'semaphore_db';

-- Execute each generated ALTER TABLE statement to change the character set of existing tables to utf8

-- Step 2: Set default character set for semaphore_db to utf8
ALTER DATABASE semaphore_db CHARACTER SET utf8 COLLATE utf8_unicode_ci;

-- Set default character set for newly created tables in semaphore_db to utf8
ALTER DATABASE semaphore_db DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
```

And I ran a new task and expected Korean output, but Korean characters are still displayed as '?' in the data saved after printing.

Is there any way to fix this?

**Comment by tboerger** [comment]
Semaphore doesn't really care about the database creation, this is up to your setup of the database server.

Just initialize it with the right collation and it should work without any issue.

**Comment by parkjaeil0x01** [comment]
> Semaphore doesn't really care about the database creation, this is up to your setup of the database server.
> 
> Just initialize it with the right collation and it should work without any issue.

Thank you, sir

I'll try it again.

Have a great day :)

**Comment by tboerger** [comment]
Closing it for now as the admin need to set the right collation and character set, not semaphore.
