### ISSUE TITLE
Cannot trigger project task via API

### ISSUE THREAD

**Issue by berndonline** [ansible-semaphore/semaphore#201]
Hello,
I really like Ansible Semaphore, really great tool but I am not very successful with the API.
The authentication via the API works but when I trigger the task http 400.

[GIN] 2016/10/15 - 23:22:34 | 204 |  210.459635ms | 192.168.100.1 |   POST    /api/auth/login
[GIN] 2016/10/15 - 23:22:34 | 400 |    1.928326ms | 192.168.100.1 |   POST    /api/project/3/tasks

I use postman and run authentication and task in a collection.
I dont know if I do something wrong, here the config:

POST /api/auth/login HTTP/1.1
Host: 192.168.100.149:3000
Accept: application/json
Content-Type: application/json
Cache-Control: no-cache
Postman-Token: a2d953ff-dae8-b4af-c892-eaa114183427
{
  "auth": "username",
  "password": "password"
}

POST /api/project/3/tasks HTTP/1.1
Host: 192.168.100.149:3000
Accept: application/json
Content-Type: application/json
Cache-Control: no-cache
Postman-Token: b36ba8ca-b3de-7880-73d8-278ebe00da71

{
  "task": "cumulus/site.yml"
}

**Comment by pianzide1117** [comment]
@berndonline  api-docs.yml is out of date. task post body is wrong and you must send cookie which return form login.

**Comment by pianzide1117** [comment]
You can filddler the web request to find right post body.

**Comment by matejkramny** [comment]
I've updated the documentation to reflect the api.

You should also be using API tokens as described here: https://ansible-semaphore.github.io/semaphore/#!/authentication/post_user_tokens
