### ISSUE TITLE
login after setup: 400 BAD REQUEST with Windows x64 binary 

### ISSUE THREAD

**Issue by JJWTimmer** [ansible-semaphore/semaphore#202]
Using latest release of semaphore_windows_amd64.exe (v2.0.4): 
I ran the setup process, and Semaphore installed the tables in my db. I started again with the config, and then localhost:3000 I tried to login with my username and password I set during setup, but it says 'Invalid login'. I doublechecked spelling and casing in the console, I tried to match the bcrypt password to my password in an online tool, and generate a new bcrypt password and set it in the database, but it all fails.

In the chrome console I see POST http://localhost:3000/api/auth/login with payload '''{auth: "jasper", password: "password"}''' with errorcode 400 BAD REQUEST. I don't see logging I can add here.

**Comment by matejkramny** [comment]
Sorry for the delay.. I investigated and on windows it seems to put a space (perhaps CR character) after the username (maybe even password).

Fix coming up

**Comment by matejkramny** [comment]
username has `\r` character after it...
