### ISSUE TITLE
Problem: Task numbers count backwards from max int

### ISSUE THREAD

**Issue by Willsr71** [ansible-semaphore/semaphore#2026]
### Issue

Task IDs appear to count backwards from max int. The first task ID I have is #2147483565 , the most recent is #2147483365 . This is by no means a serious bug, just kind of entertaining.

### Impact

Web-Frontend (what users interact with), Web-Backend (APIs)

### Installation method

Docker

### Browser

Firefox, Chrome

### Semaphore Version

v2.9.75

### Logs & errors

![image](https://github.com/semaphoreui/semaphore/assets/4505441/2f1266cd-2748-4949-a257-3ebb022863fb)

### Manual installation - system information

caddy

### Configuration

default bolt db

**Comment by fiftin** [comment]
Hi @Willsr71 

This is a feature of how BoltDB works.
