### ISSUE TITLE
Automated builds on docker hub

### ISSUE THREAD

**Issue by bcorijn** [ansible-semaphore/semaphore#204]
Hey,

Would it be possible to update the automated build of https://hub.docker.com/r/castawaylabs/semaphore/ to Semaphore V2? As long as it's made clear that you should override the default login details in the docker file (or remove those altogether so you are forced to do so), I don't really see a reason why it should not work. I had forked the repo to push it to my own docker hub registry, but in the end it's quite a bit of overhead without adding any functionality from my side.

**Comment by matejkramny** [comment]
Hi Bruno, it is possible however the preferred method (as of v2) is to download and run the binary.

I agree it is confusing, but creating a container image by placing a binary inside seems not the right way to use Docker. I may be wrong though :P

**Comment by Janpot** [comment]
@matejkramny What would be the right way to use docker then? This seems like a perfectly fine use case to me.

**Comment by matejkramny** [comment]
Ok, i just thought its a bit of an antipattern to build a binary, then put it into a container so it can be ran in docker.

From the users' perspective, the effort level is somewhat equal to finding and running a docker image compared to downloading a binary and running it.

I suppose there are some security benefits by isolating the application though, as well as keeping the app live.

As to your PR (recently closed), I am happy to merge it into this repo however a new Dockerfile needs to be made to support it.

**Comment by brunowoo** [comment]
I've done some changes on the docker files and created a new PR @matejkramny. For now the docker compose file won't work as I pointed it towards your existing automated build, which obviously will need an update. The main image needs the set of environment variables listed in the docker compose file to be present on first run, so it can pass them to the setup task.

**Comment by gcavalcante8808** [comment]
@brunowoo Just In Case,  I provide a semaphore image which I use to manage my Infrastructure. The image is available at:

https://hub.docker.com/r/gcavalcante8808/semaphore/

**Comment by brunowoo** [comment]
@gcavalcante8808 Thanks for the recommendation. Normally I prefer 'official' builds though, to prevent things going stale in the future.

@matejkramny Thanks for the merge. As said in the PR, for now it will break the Compose file until the docker hub image updates.

**Comment by panda87** [comment]
@gcavalcante8808 I tried to use your image which looks very good, but I had problems with the ssh keys. Did you add or share volume with the host keys?

**Comment by gcavalcante8808** [comment]
@panda87 The ssh keys are saved in the semaphore through the interface (during the project creation phase, Keys item). Can you post the errors on the Issues page at https://github.com/gcavalcante8808/docker-semaphore?

**Comment by rgarrigue** [comment]
Build have been ok for a month https://hub.docker.com/r/castawaylabs/semaphore/builds/
