### ISSUE TITLE
Possible to let semaphore install requirements?

### ISSUE THREAD

**Issue by 030** [ansible-semaphore/semaphore#206]
It works to deploy on systems using semaphore. I wonder whether it is possible to install dependency roles as well or should this be done on system level?

**Comment by rakshazi** [comment]
You mean auto-install ansible-galaxy roles and python dependencies? I want this feature, too. Unfortunately my golang and js skills is very poor to do it myself and send request.

@craftbyte @Echobob @matejkramny can you implement this, please?

pS: ansible/ansible-container do these automaticaly.

**Comment by matejkramny** [comment]
@rakshazi you can also download the binary file from Releases or use the docker image.

Requirements: https://github.com/ansible-semaphore/semaphore/wiki/Installation

**Comment by rakshazi** [comment]
@matejkramny I want semaphore to run `ansible-galaxy install -r requirements.yml` before task run.
It's not about semaphore requirements itself :)

**Comment by haoxinglu** [comment]
Any chance semaphore is able to run `ansible-galaxy install -r requirements.yml` before task run now?

**Comment by pbolle** [comment]
Hi is there any progress in this topic?
It would be cool if semaphore would behave like Ansible Tower (see http://docs.ansible.com/ansible-tower/latest/html/userguide/projects.html#ansible-galaxy-support)

If some body would create a mergerequest is there a change that this would excepted?

Regards Philipp

**Comment by Echobob** [comment]
Hi @pbolle, 

We would certainly review and merge any MR submitted. We're a bit busy with some of our other requirements at the moment but I'll make sure to review that MR if I see it. 

Thanks,
Alan

**Comment by pbolle** [comment]
Hi,

I was motivated to create this Feature. But it is implemented! In runner.go in runGalaxy the update of the requirements is still implemented.

The way I see it the ticket can be closed.

Regards Philipp

**Comment by matejkramny** [comment]
Indeed it is
