### ISSUE TITLE
Problem: Container is not starting after getting v2.9.109 with Error Messages

### ISSUE THREAD

**Issue by DaBlubber** [ansible-semaphore/semaphore#2060]
### Issue

After updating the Semaphore to the latest version
the container is not able to start anymore.

### Impact

Semaphore Project

### Installation method

Docker

### Database

MySQL

### Browser

Firefox, Chrome, Microsoft Edge

### Semaphore Version

latest version

### Ansible Version

```bash
Not able to join but i think 9.40
```

### Logs & errors

Attempting to connect to database semaphore on 10.10.10.250:3306 with user semaphore ...
/usr/local/bin/server-wrapper: source: line 184: can't open './venv/bin/activate': No such file or directory
Attempting to connect to database semaphore on 10.10.10.250:3306 with user semaphore ...
/usr/local/bin/server-wrapper: source: line 184: can't open './venv/bin/activate': No such file or directory
Attempting to connect to database semaphore on 10.10.10.250:3306 with user semaphore ...

### Manual installation - system information

haproxy

### Configuration

Env Variables

0 SEMAPHORE_PLAYBOOK_PATH=/tmp/semaphore/
1 SEMAPHORE_ADMIN_PASSWORD=-----------
2 SEMAPHORE_ADMIN_NAME=---------
3 SEMAPHORE_ADMIN_EMAIL=-----------
4 SEMAPHORE_ADMIN=--------------
5 ANSIBLE_HOST_KEY_CHECKING=false
6 SEMAPHORE_DB_DIALECT=mysql
7 SEMAPHORE_DB_HOST=10.10.10.250:3306
8 SEMAPHORE_DB=--------------
9 SEMAPHORE_DB_USER=-------------------
10 SEMAPHORE_DB_PASS=---------------
11 GIT_SSL_NO_VERIFY=true
12 PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
13 ANSIBLE_VERSION=9.4.0

**Comment by kelvin-keegen** [comment]
same issue...This was after the update.

**Comment by fiftin** [comment]
@kelvin-keegen , @DaBlubber what OS do you use?

**Comment by fiftin** [comment]
Do you map `/home/semaphore` directory with volume?

**Comment by DaBlubber** [comment]
> @kelvin-keegen , @DaBlubber what OS do you use?

Hey i am using Debian 12 with Docker Managed by Portainer



> Do you map `/home/semaphore` directory with volume?

Yes, this is mounted. With version 2.9.75 everything works well


To add something   i have to semaphore on the same machine because one testing and one more produtice and the test machine dont have the problem. Just this one machine.
But i also added another empty machine with new db etc. but i get the same error this time.

So no idea about the problem.

**Comment by fiftin** [comment]
@DaBlubber Please try `v2.9.110-beta`.

**Comment by DaBlubber** [comment]
> @DaBlubber Please try `v2.9.110-beta`.

Hi,
thanks for that  now the machine is starting and seems to work well.

Thank you.

**Comment by agarzon-orangerine** [comment]
> v2.9.110-beta

Does not work. Same error: `Failed to install inventory: listening on socket "/tmp/semaphore/ssh-agent-3-1716905006.sock": listen unix /tmp/semaphore/ssh-agent-3-1716905006.sock: bind: address already in use`

**Comment by tboerger** [comment]
@agarzon-orangerine you are talking about something totally different then this reported issue.
