### ISSUE TITLE
Error cloning http repository

### ISSUE THREAD

**Issue by fiftin** [ansible-semaphore/semaphore#2071]
### Discussed in https://github.com/semaphoreui/semaphore/discussions/2061

<div type='discussions-op-text'>

<sup>Originally posted by **root3200** May 27, 2024</sup>
Hello.

In the new version 2.9.109 the http protocol is implemented, I'm using it to clone my private repositories but only works when the repository is public, in private I get the following error .

![Captura de pantalla 2024-05-27 125616](https://github.com/semaphoreui/semaphore/assets/58263431/f035f64a-b2e3-493c-af4f-a66cfd5fff96)

Researching I found that there is a how fix, but I think it does not apply to the http protocol.

https://docs.semui.co/administration-guide/troubleshooting#fatal-bad-numeric-config-value-0-for-git_terminal_prompt-invalid-unit

</div>

**Comment by Sentire84** [comment]
I've got the same error, but with another bug.
![Bildschirmfoto 2024-05-30 um 14 05 34](https://github.com/semaphoreui/semaphore/assets/56742876/b54ad4fb-a8a4-4a58-84c6-01cfbe787b6f)
I created  a key with my Github credentials in the key section. My Github username contains "name@domain"  but the script ignores it as you see in the screenshot.

**Comment by fiftin** [comment]
Hi @Sentire84 what version of Semaphore do you use?

**Comment by fiftin** [comment]
`v2.9.13-beta` HTTP support fixed.

**Comment by Sentire84** [comment]
Hi @fiftin, good point.....  I'm using v2.9.75, so i think I have to upgrade.
Thank you for the quick response.
