### ISSUE TITLE
Problem: .deb package should depend on ansible

### ISSUE THREAD

**Issue by nerdoc** [ansible-semaphore/semaphore#2092]
### Issue

When installing the .deb package from the releases page (and probable .rpm too), you get semaphore to working, you can add all kinds of stuff and setup your complete tasks, but when it comes to running tasks, you always end up with a weird, task terminal, stopping before running a task:
![grafik](https://github.com/semaphoreui/semaphore/assets/2955584/c0399b61-3451-4e83-853f-9a08ac3dc9fb)
This is all, nelow is darkness.

I needed hours to find out what is missing. What helped, was stopping the semaphore service, and running the server "manually":
```bash
semaphore server --config=/etc/semaphore.conf.json
```
Then you get some output, and:
```
...
INFO[0018] Task 14 added to queue                       
INFO[0020] Set resource locker with TaskRunner 14       
INFO[0020] Task 14 removed from queue                   
INFO[0023] Stopped running TaskRunner 14                
INFO[0023] Release resource locker with TaskRunner 14   
panic: exec: "ansible-playbook": executable file not found in $PATH
```

So: yes, you **have** to install ansible to make ansible work. :rofl: 

It's obvious, but not self-explanatory when installing. The install docs don't say anything about that, and I simply forgot about it.

An easy fix would be: depend the .deb on ansible.

### Impact

Other

### Installation method

Package

### Database

Postgres

### Browser

Firefox

### Semaphore Version

2.9.113

### Ansible Version

```bash
2.10.8  - not applicable
```

### Manual installation - system information

Linux semaphore 5.15.149-1-pve #1 SMP PVE 5.15.149-1 (2024-03-29T14:24Z) x86_64 x86_64 x86_64 GNU/Linux

**Comment by tboerger** [comment]
Ansible is intentionally NOT part of the requirements because there are mutliple ways to install it. If Ansible have been installed via pip3 it won't be detected by the deb dependency. And beside the os version of Ansible there are also PPAs and third-party repositories to install Ansible.

**Comment by nerdoc** [comment]
Ok, understood, that's true. You may think I'm a noobie - but it would really help in the setup docs to  at least mention the installation of ansible ;-)

**Comment by tboerger** [comment]
It absolutely makes sense to mention the installation of Ansible by itself within the docs. Maybe you want to contribute a bit at https://github.com/semaphoreui/semaphore-docs? :)

**Comment by nerdoc** [comment]
I just saw that there already is a hint at [installation.md](https://github.com/semaphoreui/semaphore-docs/blob/main/administration-guide/installation.md): 

    Python, Ansible and Git should be installed on your system.

 :man_facepalming:

Those who can read have a great advantage. ;-)
