### ISSUE TITLE
Passing ENV variables to Ansible

### ISSUE THREAD

**Issue by bcorijn** [ansible-semaphore/semaphore#212]
As my project uses Ansible Vault, I had mounted a password file into the Semaphore container and passed the location of that file through the environment variable "ANSIBLE_VAULT_PASSWORD_FILE" in the expectation that Ansible would pick it up automatically (cfr. http://docs.ansible.com/ansible/playbooks_vault.html#running-a-playbook-with-vault).

However, it seems the playbook command does not get passed the environment variables set in the current environment, but a new set of them. I can pass it as an extra argument since that does work, but I had preferred to keep the vault setup out of Semaphore and in my Docker setup instead, so it would work transparently.

**Comment by gcavalcante8808** [comment]
@brunowoo  Did you already put the env variables into the "Environment" space?

**Comment by brunowoo** [comment]
@gcavalcante8808: You mean the environments defined per project? If I understand correctly that requires a JSON list that will be passed as "extra-vars" into Ansible and are completely unrelated to actual environment variables?

**Comment by brunowoo** [comment]
I ended up fixing my problem by passing it as "Extra CLI Argument" through the Task Template. Doesn't really achieve what is in the title, but at least it works for my use-case

**Comment by kpashka** [comment]
Hey @bcorijn, check my recent pull request #256 (and related issue #255)
Just pass any environment variables to semaphore (e.g. via systemd), and they'll be cascaded to Ansible

**Comment by bcorijn** [comment]
Hey @kpashka, that should solve this issue indeed! I had ran into it a few more times, but worked around it by passing an Ansible environment into my role, which got added during runtime so Semaphore could not remove it. Your PR is a cleaner solution!

**Comment by matejkramny** [comment]
It will be released soon

**Comment by ric79** [comment]
Hello, can I have more details about how you solved the problem?
At the moment:

1)
**Extra CLI Arguments**
`["-i", "environments/dev", "--vault-password-file", "vault-pass.py"]`

2)
vault-pass.py:
```
#!/usr/bin/python
import os
print os.environ['my_ansible_vault_pass']
```

3)
```
Environment JSON:
{
  "my_ansible_vault_pass": "xxxx"
}
```

However, I got:
```
Traceback (most recent call last):
  File "/home/ansible/playbooks/repository_1/vault-pass.py", line 3, in <module>
    print os.environ['my_ansible_vault_pass']
  File "/usr/lib/python2.7/UserDict.py", line 23, in __getitem__
    raise KeyError(key)
KeyError: 'my_ansible_vault_pass'
ERROR! Vault password script /home/ansible/playbooks/repository_1/vault-pass.py returned non-zero (1): None
```
This means that semaphore is not setting the environment variable my_ansible_vault_pass. Any ideas?
