### ISSUE TITLE
Problem:  After Update to 2.10.7 no templates run with Error Message

### ISSUE THREAD

**Issue by DaBlubber** [ansible-semaphore/semaphore#2122]
### Issue

After update to the latest so 2.10.7 no templates will run with error message
11:05:37 AM
Failed to install inventory: cannot decrypt access key, perhaps encryption key was changed
11:05:37 AM
Running playbook failed: cannot decrypt access key, perhaps encryption key was changed

### Impact

Ansible (task execution)

### Installation method

Docker

### Database

MySQL

### Browser

Chrome, Microsoft Edge

### Semaphore Version

2.10.7

### Ansible Version

```bash
ansible [core 2.16.8]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/semaphore/apps/ansible/9.4.0/venv/lib/python3.11/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/semaphore/apps/ansible/9.4.0/venv/bin/ansible
  python version = 3.11.9 (main, Apr 14 2024, 13:40:00) [GCC 13.2.1 20231014] (/opt/semaphore/apps/ansible/9.4.0/venv/bin/python3)
  jinja version = 3.1.4
  libyaml = True
```

### Logs & errors

11:05:37 AM
Failed to install inventory: cannot decrypt access key, perhaps encryption key was changed
11:05:37 AM
Running playbook failed: cannot decrypt access key, perhaps encryption key was changed

### Configuration

0 SEMAPHORE_DB=semaphoredev
1 SEMAPHORE_DB_USER=semaphoredev
2 SEMAPHORE_DB_PASS=....
3 SEMAPHORE_DB_DIALECT=mysql
4 SEMAPHORE_DB_HOST=10.10.10.250
5 SEMAPHORE_DB_PORT=3306
6 GIT_SSL_NO_VERIFY=true
7 SEMAPHORE_ADMIN_PASSWORD=....
8 SEMAPHORE_ADMIN_NAME=admin
9 SEMAPHORE_ADMIN_EMAIL=admin@admin.de
10 SEMAPHORE_ADMIN=admin
11 ANSIBLE_HOST_KEY_CHECKING=false
12 PATH=/opt/semaphore/apps/ansible/9.4.0/venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
13 ANSIBLE_VERSION=9.4.0
14 VIRTUAL_ENV=/opt/semaphore/apps/ansible/9.4.0/venv
15 SEMAPHORE_ACCESS_KEY_ENCRYPTION=fYsY[...]vgexc=

### Additional information

Before i installed the newest version this entry was not there: 15 SEMAPHORE_ACCESS_KEY_ENCRYPTION=fYsY[...]vgexc=
I made the command to create the access key and added the access key via env
Before i got the same error message in web ui
Also when i go back to the former version 2.9.112 everyhting works well again

**Comment by andygeorge** [comment]
I'm receiving this as well in `Semaphore v2.10.8-beta-dabc8eb-1718996548`.

**Comment by DaBlubber** [comment]
Hey together,
is there a handling error please tell me thanks

**Comment by daastek** [comment]
If SEMAPHORE_ACCESS_KEY_ENCRYPTION variable was not set earlier, setting it to empty string seems to work with v2.10.7 and above.

**Comment by DaBlubber** [comment]
Hi,

@daastek  alright works just with empty string.
Thanks
