### ISSUE TITLE
Problem: Inventory not cloning

### ISSUE THREAD

**Issue by phillf** [ansible-semaphore/semaphore#2123]
### Issue

Ansible doesn't seem to be authenticating to the repository with the PAT when cloning for the inventory even though it cloned the playbook just fine.

The inventory and playbook assets are being pulled from a private self-hosted GitLab repo.

### Impact

Ansible (task execution)

### Installation method

Package

### Database

BoltDB

### Browser

Firefox, Chrome

### Semaphore Version

2.9.112-4f95ac8-1717064987

### Logs & errors

 8:50:44 AM
Task 2147483600 added to queue
8:50:47 AM
Started: 2147483600
8:50:47 AM
Run TaskRunner with template: Update apt packages
8:50:47 AM
Preparing: 2147483600
8:50:48 AM
Updating Repository https://git.nullthe.net/pjfernandes/ansible-playbooks.git
8:50:48 AM
From https://git.nullthe.net/pjfernandes/ansible-playbooks
8:50:48 AM
 * branch            main       -> FETCH_HEAD
8:50:48 AM
Already up to date.
8:50:48 AM
cloning inventory repository
8:50:48 AM
Cloning Repository https://git.nullthe.net/pjfernandes/ansible-playbooks.git
8:50:49 AM
Cloning into 'inventory_2147483600'...
8:50:49 AM
remote: HTTP Basic: Access denied. The provided password or token is incorrect or your account has 2FA enabled and you must use a personal access token instead of a password. See https://git.nullthe.net/help/topics/git/troubleshooting_git#error-on-git-fetch-http-basic-access-denied
8:50:49 AM
fatal: Authentication failed for 'https://git.nullthe.net/pjfernandes/ansible-playbooks.git/'
8:50:49 AM
Failed to install inventory: exit status 128
8:50:49 AM
Running playbook failed: exit status 128

### Manual installation - system information

Linux semaphore.creativetech.me 6.8.4-3-pve #1 SMP PREEMPT_DYNAMIC PMX 6.8.4-3 (2024-05-02T11:55Z) x86_64 x86_64 x86_64 GNU/Linux

Hosted in an LXC container on Proxmox PVE 8.2.

**Comment by fiftin** [comment]
Hi @phillf is it GitLab?

**Comment by fiftin** [comment]
Please try `v2.10.8-beta`.

**Comment by phillf** [comment]
Will follow up when I get home.

Also watching https://github.com/semaphoreui/semaphore/issues/2128

**Comment by phillf** [comment]
```v2.10.8-beta``` seems to have fixed the issue. I also saw you pushed ```v2.10.9-beta``` so I also tested that out. No regression detected.
