### ISSUE TITLE
Update Contributing guide to use pug and jstransformers

### ISSUE THREAD

**Issue by gcavalcante8808** [ansible-semaphore/semaphore#213]
Currently, 

The development documentation states about the use of jade/transformers, but during the 'npm -i -g nodemon less jade' command, npm print warnings about the change of the jade project to pug.

**Comment by gcavalcante8808** [comment]
And, if possible, a basic config.json as well.

**Comment by matejkramny** [comment]
Hi Gabriel,

- Test config.json: https://github.com/ansible-semaphore/semaphore/blob/master/make.sh#L17 <https://github.com/ansible-semaphore/semaphore/blob/master/make.sh#L17>
- You can alternatively run setup which will guide you through the setup and create a config json for you.
- Also the program can print example config using the `-printConfig` flag

(run `semaphore -h` for all options)

Kind regards,
Matej

**Comment by gcavalcante8808** [comment]
Hello Friend,

I achieve the development path using the followings steps:

1) Install go and node.js. In my case I just download them and extracted on ~/bin, creating the necessary symlinks;

2) Add environment variables to .profile (or .bashrc) need by go and npm:

```
PATH=/~/bin:/~/GoProjects/bin:/~/.npm-global/bin:$PATH
GOPATH=~/GoProjects
GOROOT=~/bin/golang
NPM_CONFIG_PREFIX=~/.npm-global
export PATH GOPATH GOROOT NPM_CONFIG_PREFIX
```

3) Create project path and clone the repository with --recursive:

```
mkdir ~/GoProjects/src/github.com/ansible-semaphore/
cd ~/GoProjects/src/github.com/ansible-semaphore/
git clone --recursive git@github.com:ansible-semaphore/semaphore.git
```

4) Install go dependencies:

```
go get github.com/jteeuwen/go-bindata/...
go get github.com/mitchellh/gox
go get github.com/cespare/reflex
go get -u ./...
```

5) Install node.js dependencies (using pug instead of jade, globally --> .npm-global):
```
npm i -g nodemon less pug async
```

6) Create a container with MySQL installed:

```
docker run -d --name semaphore-db -v semaphore-data:/var/lib/mysql -p 3306:3306 -e MYSQL_USER=semaphore -e MYSQL_DATABASE=semaphore -e MYSQL_PASSWORD=semaphore -e MYSQL_ROOT_PASSWORD=semaphore mysql
```

7) Download the 2.0.4 version into main directory and run the setup to trigger the db migration:

```
wget https://github.com/ansible-semaphore/semaphore/releases/download/v2.0.4/semaphore_linux_amd64
chmod +x semaphore_linux_amd64
./semaphore_linux_amd64 -setup
```
8) Created a config.json to start the development:

```
cat <<EOT >> config.json
{
	"mysql": {
		"host": "127.0.0.1:3306",
		"user": "semaphore",
		"pass": "semaphore",
		"name": "semaphore"
	},
	"session_db": "127.0.0.1:6379",
	"port": ":8010"
}
EOT
```
9) Started the watch processes:

```
./make.sh watch
```
10) Point the browser to localhost:8000.

In this point I would think about to update the contributing guide to make it more simple to understand. 

Is this and acceptable request?
