### ISSUE TITLE
Question: why bash script run default user root. can change to another user to run bash scripts?

### ISSUE THREAD

**Issue by yasok787** [ansible-semaphore/semaphore#2138]
### Question

9:38:28 AM
Task 103 added to queue
9:38:30 AM
Started: 103
9:38:30 AM
Run TaskRunner with template: repmgr
9:38:30 AM
Preparing: 103
9:38:31 AM
db-postgres | UNREACHABLE! => {
9:38:31 AM
    "changed": false,
9:38:31 AM
    "msg": "Failed to connect to the host via ssh: root@192.168.1.1: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).",
9:38:31 AM
    "unreachable": true
9:38:31 AM
}
9:38:31 AM
Running playbook failed: exit status 4

**Comment by fiftin** [comment]
Need more details: os, version, logs, etc.
