### ISSUE TITLE
Dashboard - event.object_name incorrect

### ISSUE THREAD

**Issue by brunowoo** [ansible-semaphore/semaphore#214]
I seem to be bothering you with quite some issues/questions, but here's another one I noticed:

When checking the global dashboard or a project dashboard, the event.object_name seems to be incorrectly loaded. I would expect it to show the playbook name of the task that the event it is related to, instead it is showing the playbook name of the oldest task available in the history. It thus also shows the same object_name for every event in the dashboard.

Digging into the code it looks like this query is to blame: https://github.com/ansible-semaphore/semaphore/blob/master/api/events.go#L44-L46. It does not take into account the event.object_id or the fact that the task might get deleted while the event remains.

**Comment by matejkramny** [comment]
Thanks, no bother at all.
