### ISSUE TITLE
Problem: Unable to acces new Schedule page.

### ISSUE THREAD

**Issue by Sinitronics** [ansible-semaphore/semaphore#2145]
### Issue

After upgrading to 2.10.11 I'm not able to view the new schedule page, it's just blank. Log file gives a bunch of errors see below.

I did downgrade and remove the schedules from all templates which after re-upgrading was then able to see the schedules page but once added a schedule back to a template the schedule page goes blank again.

### Impact

Web-Frontend (what users interact with)

### Installation method

Package

### Database

BoltDB

### Browser

Firefox, Chrome

### Semaphore Version

2.10.11

### Logs & errors

Jun 28 16:05:02 ansible semaphore[136179]: time="2024-06-28T16:05:02Z" level=error msg="websocket: close sent" fields.level=Error
Jun 28 16:05:02 ansible semaphore[136179]: time="2024-06-28T16:05:02Z" level=error msg="close tcp 192.168.0.9:3000->192.168.0.249:53816: use of closed network connection" fields.level=Error
Jun 28 16:05:03 ansible semaphore[136179]: 2024/06/28 16:05:03 http: panic serving 192.168.0.249:47036: reflect.Set: value of type struct { ID int "json:\"id\""; ProjectID int "json:\"project_id\""; TemplateID int "json:\"template_id\""; CronFormat string "json:\"cron_format\""; RepositoryID *int "json:\"repository_id\""; LastCommitHash *string "json:\"last_commit_hash\"" } is not assignable to type db.Schedule
Jun 28 16:05:03 ansible semaphore[136179]: goroutine 172 [running]:
Jun 28 16:05:03 ansible semaphore[136179]: net/http.(*conn).serve.func1()
Jun 28 16:05:03 ansible semaphore[136179]:         /opt/hostedtoolcache/go/1.22.4/x64/src/net/http/server.go:1898 +0xbe
Jun 28 16:05:03 ansible semaphore[136179]: panic({0xb56520?, 0xc0002a0f80?})
Jun 28 16:05:03 ansible semaphore[136179]:         /opt/hostedtoolcache/go/1.22.4/x64/src/runtime/panic.go:770 +0x132
Jun 28 16:05:03 ansible semaphore[136179]: reflect.Value.assignTo({0xc0007c0c00?, 0xc0002859a0?, 0xc000268900?}, {0xc6c937, 0xb}, 0xc20780, 0x0)
Jun 28 16:05:03 ansible semaphore[136179]:         /opt/hostedtoolcache/go/1.22.4/x64/src/reflect/value.go:3356 +0x299
Jun 28 16:05:03 ansible semaphore[136179]: reflect.Value.Set({0xc20780?, 0xc000285950?, 0x71?}, {0xc0007c0c00?, 0xc0002859a0?, 0x4090a0?})
Jun 28 16:05:03 ansible semaphore[136179]:         /opt/hostedtoolcache/go/1.22.4/x64/src/reflect/value.go:2325 +0xe6
Jun 28 16:05:03 ansible semaphore[136179]: github.com/ansible-semaphore/semaphore/db/bolt.unmarshalObject({0xc0000f803a, 0x71, 0x71}, {0xb39fa0, 0xc000285950})
Jun 28 16:05:03 ansible semaphore[136179]:         /home/runner/work/semaphore/semaphore/db/bolt/BoltDb.go:277 +0x252
Jun 28 16:05:03 ansible semaphore[136179]: github.com/ansible-semaphore/semaphore/db/bolt.unmarshalObjects({0x18fadd0, 0xc0004090a0}, {{0xc71445, 0x11}, {0x1906d48, 0xc20780}, 0x0, {0x0, 0x0}, {0xc68107, ...}, ...}, ...)
Jun 28 16:05:03 ansible semaphore[136179]:         /home/runner/work/semaphore/semaphore/db/bolt/BoltDb.go:324 +0x286
Jun 28 16:05:03 ansible semaphore[136179]: github.com/ansible-semaphore/semaphore/db/bolt.(*BoltDb).getObjectsTx(0xc0000e7100?, 0xc000179420, 0x4119bb?, {{0xc71445, 0x11}, {0x1906d48, 0xc20780}, 0x0, {0x0, 0x0}, ...}, ...)
Jun 28 16:05:03 ansible semaphore[136179]:         /home/runner/work/semaphore/semaphore/db/bolt/BoltDb.go:373 +0x1d0
Jun 28 16:05:03 ansible semaphore[136179]: github.com/ansible-semaphore/semaphore/db/bolt.(*BoltDb).GetProjectSchedules.(*BoltDb).getObjects.func2(0x18?)
Jun 28 16:05:03 ansible semaphore[136179]:         /home/runner/work/semaphore/semaphore/db/bolt/BoltDb.go:378 +0xbf
Jun 28 16:05:03 ansible semaphore[136179]: go.etcd.io/bbolt.(*DB).View(0x7?, 0xc0000e7200)
Jun 28 16:05:03 ansible semaphore[136179]:         /home/runner/work/semaphore/semaphore/vendor/go.etcd.io/bbolt/db.go:917 +0x72
Jun 28 16:05:03 ansible semaphore[136179]: github.com/ansible-semaphore/semaphore/db/bolt.(*BoltDb).getObjects(...)
Jun 28 16:05:03 ansible semaphore[136179]:         /home/runner/work/semaphore/semaphore/db/bolt/BoltDb.go:377
Jun 28 16:05:03 ansible semaphore[136179]: github.com/ansible-semaphore/semaphore/db/bolt.(*BoltDb).GetProjectSchedules(0xc0001700f0, 0x1)
Jun 28 16:05:03 ansible semaphore[136179]:         /home/runner/work/semaphore/semaphore/db/bolt/schedule.go:35 +0x17d
Jun 28 16:05:03 ansible semaphore[136179]: github.com/ansible-semaphore/semaphore/api/projects.GetProjectSchedules({0x18fc5d0, 0xc000178c40}, 0xc000808b40)
Jun 28 16:05:03 ansible semaphore[136179]:         /home/runner/work/semaphore/semaphore/api/projects/schedules.go:48 +0x17b
Jun 28 16:05:03 ansible semaphore[136179]: net/http.HandlerFunc.ServeHTTP(0x7f4635f735b8?, {0x18fc5d0?, 0xc000178c40?}, 0xc000808fc0?)
Jun 28 16:05:03 ansible semaphore[136179]:         /opt/hostedtoolcache/go/1.22.4/x64/src/net/http/server.go:2166 +0x29
Jun 28 16:05:03 ansible semaphore[136179]: github.com/ansible-semaphore/semaphore/api.Route.GetMustCanMiddleware.func4.1({0x18fc5d0, 0xc000178c40}, 0xc000808b40)
Jun 28 16:05:03 ansible semaphore[136179]:         /home/runner/work/semaphore/semaphore/api/projects/project.go:59 +0x127
Jun 28 16:05:03 ansible semaphore[136179]: net/http.HandlerFunc.ServeHTTP(0xc000808b40?, {0x18fc5d0?, 0xc000178c40?}, 0xc28ea0?)
Jun 28 16:05:03 ansible semaphore[136179]:         /opt/hostedtoolcache/go/1.22.4/x64/src/net/http/server.go:2166 +0x29
Jun 28 16:05:03 ansible semaphore[136179]: github.com/ansible-semaphore/semaphore/api/projects.ProjectMiddleware.func1({0x18fc5d0, 0xc000178c40}, 0xc000808b40)
Jun 28 16:05:03 ansible semaphore[136179]:         /home/runner/work/semaphore/semaphore/api/projects/project.go:43 +0x43d
Jun 28 16:05:03 ansible semaphore[136179]: net/http.HandlerFunc.ServeHTTP(0x18fc5d0?, {0x18fc5d0?, 0xc000178c40?}, 0x0?)
Jun 28 16:05:03 ansible semaphore[136179]:         /opt/hostedtoolcache/go/1.22.4/x64/src/net/http/server.go:2166 +0x29
Jun 28 16:05:03 ansible semaphore[136179]: github.com/ansible-semaphore/semaphore/api.authentication.func1({0x18fc5d0, 0xc000178c40}, 0xc000808b40)
Jun 28 16:05:03 ansible semaphore[136179]:         /home/runner/work/semaphore/semaphore/api/auth.go:102 +0x57
Jun 28 16:05:03 ansible semaphore[136179]: net/http.HandlerFunc.ServeHTTP(0xc05180?, {0x18fc5d0?, 0xc000178c40?}, 0xc?)
Jun 28 16:05:03 ansible semaphore[136179]:         /opt/hostedtoolcache/go/1.22.4/x64/src/net/http/server.go:2166 +0x29
Jun 28 16:05:03 ansible semaphore[136179]: github.com/ansible-semaphore/semaphore/api.JSONMiddleware.func1({0x18fc5d0, 0xc000178c40}, 0xc000808b40)
Jun 28 16:05:03 ansible semaphore[136179]:         /home/runner/work/semaphore/semaphore/api/router.go:44 +0xf6
Jun 28 16:05:03 ansible semaphore[136179]: net/http.HandlerFunc.ServeHTTP(0xb56500?, {0x18fc5d0?, 0xc000178c40?}, 0xc0000c56f0?)
Jun 28 16:05:03 ansible semaphore[136179]:         /opt/hostedtoolcache/go/1.22.4/x64/src/net/http/server.go:2166 +0x29
Jun 28 16:05:03 ansible semaphore[136179]: github.com/ansible-semaphore/semaphore/api.StoreMiddleware.func1.1()
Jun 28 16:05:03 ansible semaphore[136179]:         /home/runner/work/semaphore/semaphore/api/router.go:35 +0x28
Jun 28 16:05:03 ansible semaphore[136179]: github.com/ansible-semaphore/semaphore/db.StoreSession({0x190bc38, 0xc0001700f0}, {0xc0001743f0, 0xc}, 0xc0000c57d8)
Jun 28 16:05:03 ansible semaphore[136179]:         /home/runner/work/semaphore/semaphore/db/Store.go:442 +0x5f
Jun 28 16:05:03 ansible semaphore[136179]: github.com/ansible-semaphore/semaphore/api.StoreMiddleware.func1({0x18fc5d0, 0xc000178c40}, 0xc000808b40)
Jun 28 16:05:03 ansible semaphore[136179]:         /home/runner/work/semaphore/semaphore/api/router.go:34 +0x126
Jun 28 16:05:03 ansible semaphore[136179]: net/http.HandlerFunc.ServeHTTP(0xc000808b40?, {0x18fc5d0?, 0xc000178c40?}, 0xc0fb20?)
Jun 28 16:05:03 ansible semaphore[136179]:         /opt/hostedtoolcache/go/1.22.4/x64/src/net/http/server.go:2166 +0x29
Jun 28 16:05:03 ansible semaphore[136179]: github.com/ansible-semaphore/semaphore/cli/cmd.runService.func1.1({0x18fc5d0, 0xc000178c40}, 0xc000808b40)
Jun 28 16:05:03 ansible semaphore[136179]:         /home/runner/work/semaphore/semaphore/cli/cmd/root.go:74 +0xea
Jun 28 16:05:03 ansible semaphore[136179]: net/http.HandlerFunc.ServeHTTP(0x0?, {0x18fc5d0?, 0xc000178c40?}, 0x411d65?)
Jun 28 16:05:03 ansible semaphore[136179]:         /opt/hostedtoolcache/go/1.22.4/x64/src/net/http/server.go:2166 +0x29
Jun 28 16:05:03 ansible semaphore[136179]: github.com/ansible-semaphore/semaphore/api.Route.CORSMethodMiddleware.func1.1({0x18fc5d0, 0xc000178c40}, 0xc000808b40)
Jun 28 16:05:03 ansible semaphore[136179]:         /home/runner/work/semaphore/semaphore/vendor/github.com/gorilla/mux/middleware.go:51 +0x89
Jun 28 16:05:03 ansible semaphore[136179]: net/http.HandlerFunc.ServeHTTP(0xc0008087e0?, {0x18fc5d0?, 0xc000178c40?}, 0xc0002a89b8?)
Jun 28 16:05:03 ansible semaphore[136179]:         /opt/hostedtoolcache/go/1.22.4/x64/src/net/http/server.go:2166 +0x29
Jun 28 16:05:03 ansible semaphore[136179]: github.com/gorilla/mux.(*Router).ServeHTTP(0xc000000180, {0x18fc5d0, 0xc000178c40}, 0xc000585c20)
Jun 28 16:05:03 ansible semaphore[136179]:         /home/runner/work/semaphore/semaphore/vendor/github.com/gorilla/mux/mux.go:212 +0x1e2
Jun 28 16:05:03 ansible semaphore[136179]: github.com/ansible-semaphore/semaphore/cli/cmd.runService.ProxyHeaders.func2({0x18fc5d0, 0xc000178c40}, 0xc000585c20)
Jun 28 16:05:03 ansible semaphore[136179]:         /home/runner/work/semaphore/semaphore/vendor/github.com/gorilla/handlers/proxy_headers.go:59 +0x143
Jun 28 16:05:03 ansible semaphore[136179]: net/http.HandlerFunc.ServeHTTP(0xc000326ab4?, {0x18fc5d0?, 0xc000178c40?}, 0x447d00?)
Jun 28 16:05:03 ansible semaphore[136179]:         /opt/hostedtoolcache/go/1.22.4/x64/src/net/http/server.go:2166 +0x29
Jun 28 16:05:03 ansible semaphore[136179]: github.com/ansible-semaphore/semaphore/cli/cmd.runService.cropTrailingSlashMiddleware.func3({0x18fc5d0, 0xc000178c40}, 0xc000585c20)
Jun 28 16:05:03 ansible semaphore[136179]:         /home/runner/work/semaphore/semaphore/cli/cmd/server.go:27 +0xbd
Jun 28 16:05:03 ansible semaphore[136179]: net/http.HandlerFunc.ServeHTTP(0x469f79?, {0x18fc5d0?, 0xc000178c40?}, 0xc0002a8b68?)
Jun 28 16:05:03 ansible semaphore[136179]:         /opt/hostedtoolcache/go/1.22.4/x64/src/net/http/server.go:2166 +0x29
Jun 28 16:05:03 ansible semaphore[136179]: net/http.serverHandler.ServeHTTP({0xc0001701b0?}, {0x18fc5d0?, 0xc000178c40?}, 0x6?)
Jun 28 16:05:03 ansible semaphore[136179]:         /opt/hostedtoolcache/go/1.22.4/x64/src/net/http/server.go:3137 +0x8e
Jun 28 16:05:03 ansible semaphore[136179]: net/http.(*conn).serve(0xc00058b0e0, {0x18fe388, 0xc0004273e0})
Jun 28 16:05:03 ansible semaphore[136179]:         /opt/hostedtoolcache/go/1.22.4/x64/src/net/http/server.go:2039 +0x5e8
Jun 28 16:05:03 ansible semaphore[136179]: created by net/http.(*Server).Serve in goroutine 1
Jun 28 16:05:03 ansible semaphore[136179]:         /opt/hostedtoolcache/go/1.22.4/x64/src/net/http/server.go:3285 +0x4b4

### Manual installation - system information

Linux ansible 5.15.0-107-generic #117-Ubuntu SMP Fri Apr 26 12:26:49 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

**Comment by fiftin** [comment]
Hi @Sinitronics thank you! It is a bug related to BoltDB. Will be fixed ASAP.

**Comment by vaz-ar** [comment]
I had the same issue, upgrading to 2.10.12-beta fixed it

**Comment by vaz-ar** [comment]
Not sure if it is related to those database changes, but there are some issues with the tasks history displayed on the "Task Templates" page with the 2.10.12-beta, only the latest task run has its status shown, all the others show "Not launched":
![image](https://github.com/semaphoreui/semaphore/assets/3344540/0b4271d2-c3d4-4b17-833c-39080129843a)

The history is still there when going on a specific task page, it is only on the "Task Templates" that there is an issue.

**Comment by fiftin** [comment]
https://github.com/semaphoreui/semaphore/issues/2180
