### ISSUE TITLE
Question: is `v2.19.10` tagged correctly or shouldn't it rather read `v2.10.10`?

### ISSUE THREAD

**Issue by cschug** [ansible-semaphore/semaphore#2154]
### Question

I was wondering if 41e72f1 shouldn't have been tagged as `v2.10.10` instead of [`v2.19.10`](https://github.com/semaphoreui/semaphore/releases/tag/v2.19.10). To me it looks like a typo, otherwise the versioning doesn't make much sense (to me).

If that was indeed a mistake, the tag should be fixed and any releases stating `v2.19.10` should be yanked like for example also the container image [`docker.io/semaphoreui/semaphore:v2.19.10`](https://hub.docker.com/layers/semaphoreui/semaphore/v2.19.10/images/sha256-ddc0592cc23693927fc74b9bc2b16615d4f1914d4e3faf5e6ce621dfaaa1adec?context=explore). Those who prefer to follow versioned container image tags (rather than using `latest`) get tricked by that release (and in the same way automated tracking mechanism relying on semantic versioning like Renovate) which would easily miss younger releases like [`v2.10.11`](https://github.com/semaphoreui/semaphore/releases/tag/v2.10.11).

**Comment by gautamkrishnar** [comment]
This version no longer exists in the docker registry. I think this issue can be closed.
