### ISSUE TITLE
don't know how to use it , is there any usage document

### ISSUE THREAD

**Issue by huangered** [ansible-semaphore/semaphore#216]
Spend one afternoon, don't know how to use it , is there any usage document?
1. how to decide run which playbook? only see a playbook repo, does it need special structure?
2. how to set inventory?
3. why the ssh key need both public and private key.

**Comment by gcavalcante8808** [comment]
hello @huangered 

1) You create a task template and the first field receives the playbook file name;
2) During the Task Template Creation you choose a previous created inventory;
3) As stated in the screen, you dont need the public key but is recommended ... The private key will be downloaded into your semaphore server and used by ansible to access the target hosts.

**Comment by huangered** [comment]
@gcavalcante8808 thanks for you reply , i will have a try again.
