### ISSUE TITLE
Windows Support (Powershell/WinRM)

### ISSUE THREAD

**Issue by daBONDi** [ansible-semaphore/semaphore#217]
A other KeyType would be Awesome for Windows Hosts like follow host file to allow managing windows hosts with winrm calls

[windows]
win1 ansible_host=192.168.1.152

[windows:vars]
ansible_user=vagrant
ansible_password=vagrant
ansible_port=5986
ansible_connection=winrm
ansible_winrm_server_cert_validation=ignore

**Comment by matejkramny** [comment]
this is related to hosts file generation right?

**Comment by daBONDi** [comment]
Sorry to forgot this
Yes this is a sample host file, and the UI dont let specify this, maybe a dropdown box with SSH/WinRM or something

**Comment by Tuimalila** [comment]
Is it possible at least to manually add windows clients to semaphore? I've been searching but I hadn't had any luck finding out the answer...

**Comment by steaksauce-** [comment]
Any status on this? I looked at Semaphore today to see about managing some Windows hosts, but it seems like I cannot?

**Comment by twhiston** [comment]
renamed issue to Windows Support (Powershell/WinRM)

I think this would be possible but ideally we need a windows based developer to step up to the plate and make a PR as I don't have access to any windows boxes.

**Comment by slickvoodoo** [comment]
Connecting to windows hosts works as long as you configure the inventory correctly. I tried it out today. It's just not intuitive in the UI (for example you must specify an SSH key - even though it won't be used).

**Comment by steaksauce-** [comment]
Maybe this can get done by accomplishing the following (keep in mind, I am not a Semaphore user -- at least yet):
- Modify UI to allow creating and maintaining host vars (to set windows hosts up correctly)
- Modify UI to allow creating and maintaining connections to hosts without SSH key

Ansible Tower has this thing called "Machine Credentials" where you can optionally specify the SSH keys. Maybe something similar is in call here.

**Comment by strangeman** [comment]
@twhiston we use Semaphore for windows too - and it works correctly. All connection parameters set via group_vars.

**Comment by twhiston** [comment]
@strangeman - so what do we actually need to do here? It seems to me that the inventory should 'just work' if you write it correctly and apart from that we just need to remove selecting an ssh key as a mandatory field in the web interface to make the user experience slightly nicer, anything else?

**Comment by strangeman** [comment]
I think there is nothing to do. All these things can be done via Ansible config or vars.
Disabling of ssh key may cause another question, like "I want to use SSH password instead of key" :)

**Comment by twhiston** [comment]
Yeah i agree, and making a lot of changes to the ssh (and especially allowing passwords) is not something I want to do. Closing this
