### ISSUE TITLE
Problem: Bash Task-Templates offer options when run that are ignored

### ISSUE THREAD

**Issue by ShaneMcC** [ansible-semaphore/semaphore#2174]
### Issue

When running a new instance of a bash-based task, the Debug (`--vvvv`), Dry Run (`--check`) and Diff (`--diff`) tick boxes are presented to the user, but it doesn't look like these flags are actually passed to the command. These should be hidden from the user.

Also the `Advanced >` section is present, but you can't enable "Allow CLI Arguments in Task" for bash-based tasks so this should also be hidden (though it would be nice to be able to pass arguments other than survey vars)

### Impact

Web-Frontend (what users interact with)

### Installation method

Docker

### Database

MySQL

### Browser

Chrome

### Semaphore Version

v2.10.11-d31ebd3-1719395023

**Comment by fiftin** [comment]
Hi @ShaneMcC yes, will do. Thank you ;)

**Comment by ShaneMcC** [comment]
Looks like this has been fixed in 2.10.19, closing.
