### ISSUE TITLE
Problem: "Task Templates" pages shows "Not Launched" for every tasks except the last one that ran

### ISSUE THREAD

**Issue by vaz-ar** [ansible-semaphore/semaphore#2180]
### Issue

The "Task Templates" pages shows "Not Launched" for every tasks except the last one that ran

### Impact

Web-Frontend (what users interact with)

### Installation method

Docker

### Database

BoltDB

### Browser

Firefox

### Semaphore Version

v2.10.12-beta, v2.10.13-beta, v2.10.15-beta

**Comment by vaz-ar** [comment]
![image](https://github.com/semaphoreui/semaphore/assets/3344540/273940f6-01b9-479c-9f4c-ea68ff5346e3)

**Comment by vaz-ar** [comment]
I think that this is due to the changes in e247c05cfb6bea01e69904ea8e8dfb1088ba64b7 but I am not sure what the fix would be here.

**Comment by fiftin** [comment]
Hi @vaz-ar it is issue related to boltdb. Result of query optimization :) Will be fixed soon.

**Comment by vaz-ar** [comment]
Ok thanks!

**Comment by vaz-ar** [comment]
@fiftin I just installed 2.10.21, looks like this is fixed, thanks!

**Comment by fiftin** [comment]
@vaz-ar please upgrade to v2.10.22 - some bugs fixed.
