### ISSUE TITLE
Possible to play local playbooks? 

### ISSUE THREAD

**Issue by ashish235** [ansible-semaphore/semaphore#22]
It would be really good if semaphore can also play playbooks from a local server in my n/w or on the host machine where I 've installed semaphore. I might not keep all my ansible code in github for various reasons. 

Please suggest if this can be released in future or it's not feasible at all.

**Comment by matejkramny** [comment]
Try putting a bare git repository into a folder somewhere, and point the `git url` in semaphore there.

Let me know how it goes :)

**Comment by ashish235** [comment]
@matejkramny, Sorry to ask a very naive question. Please correct me if misunderstood.

Do I need to do something like mentioned in the below URL?

**Comment by matejkramny** [comment]
Yep exactly.

You should be able to do it like this:

1. Create a repository with your playbooks
2. Clone that repository (eg `git clone --bare /path/to/my/playbooks playbooks.git`)
3. Point semaphore to `playbooks.git` folder.

**Comment by kantmakm** [comment]
Can the "Playbook Location" be expressed with an ssh url?  (Ex. git@bitbucket.org:kantmakm/masterplaybook.git where it will use a private key from the identities)  or is the HTTPS location what it wants?  I have pointed semaphore to my git repo using ssh, but it does not seem to be reading my .yml files - yet it's not returning any errors.  Great project! Thanks!
![image](https://cloud.githubusercontent.com/assets/833202/7542786/ee37287c-f57c-11e4-8bc0-c34fec5e8a58.png)

**Comment by matejkramny** [comment]
Jobs are Tasks that have been run in the past.

Have you defined any tasks?

Semaphore doesn't automatically download the playbooks' contents and give you options to run them (although, thats a nice idea)

**Comment by matejkramny** [comment]
And locations can be in any git supported format..

- `git://host/repo.git`
- `git@host:repo.git`

**Comment by kantmakm** [comment]
"Semaphore doesn't automatically download the playbooks' contents and give you options to run them"

AhHa!  That's exactly what I thought was supposed to happen!  I figured that semaphore would checkout all .yml files from bitbucket and parse them into tasks.

So instead I should take a simple playbook (in this case for installing mod24_ssl) that is in a mod24_ssl.yml checked into my repo:
---
- hosts: ssl_webservers
  remote_user: user
  become: yes
  tasks:
  - name: mod24_ssl install
    yum: name=mod24_ssl state=present
  handlers:
    - name: restart apache
      service: name=httpd state=restarted
But I'm unclear how to feed it to Semaphore - I see you can add a job - but there's only 2 params: name and play - no option to upload - should the value for play be the full path on the server to the .yml ?
![image](https://cloud.githubusercontent.com/assets/833202/7543811/c941c8da-f584-11e4-9d1e-791f2c0afbf3.png)

**Comment by kantmakm** [comment]
Sorry for the formatting :-(

**Comment by kantmakm** [comment]
Does Semaphore not use /etc/ansible/hosts  for host info?

**Comment by kantmakm** [comment]
I ask b/c I added a host and a job.  My host needs a username and a private key for ssh - I added these in identities, but could see how to associate an identity with a host.  In my regular /etc/ansible/hosts file I specify the user and key with ansible_ssh_user=user ansible_ssh_private_key_file=/root/.ssh/sshkey.pem on the host entry.  Here's output fom the job:

Updating SSH Keys
SSH Keys Updated.

Downloading Playbook.
Cloning into 'playbook_554cfa9178d4b3ad10a08853'...
Warning: Permanently added 'bitbucket.org' (RSA) to the list of known hosts.


Playbook Downloaded.

Set up Ansible Hosts file with contents:
[ec2-lampservers]
54.166.82.XXX


Starting play /root/mod24_ssl2.yml.

PLAY [54.166.82.XXX] ********************************************************** 

GATHERING FACTS *************************************************************** 
fatal: [54.166.82.111] => SSH Error: Permission denied (publickey).
    while connecting to 54.166.82.XXX:22
It is sometimes useful to re-run the command using -vvvv, which prints SSH debug output to help diagnose the issue.

TASK: [mod24_ssl install] ***************************************************** 
FATAL: no hosts matched or all hosts have already failed -- aborting


PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/root/mod24_ssl2.retry

54.166.82.111              : ok=0    changed=0    unreachable=1    failed=0

**Comment by matejkramny** [comment]
For your first comment, you would add a host group: `ssl_webservers` and add an x number of ip's into it, playbook file being `mod24_ssl.yml`

The error in the last comment is that ansible is unable to log into your ssh server. Semaphore uses the playbooks' `identity` public & private keys to access the server. For this to work, you must have an associated `identity`, and have the public key of the `identity` installed to your remote server's `~/.ssh/authorized_keys`.

**Comment by kantmakm** [comment]
I have really been trying to figure out how to associate an identity to a playbook and have come up short.  I'm sure it's something simple like adding an idenity identityname to the playbook file, but can't find an example anywhere.  I have tried to workaround by adding the username and private key both in the /etc/ansible.cfg  file and in my ~/.ssh/config file - I can now run playbooks from command line without passing through --private-key= , however, semaphore jobs are still failing with unable to authenticate.

I don't know that it makes a difference, but this semaphore is running as a straight node app - not running through vagrant.

**Comment by kantmakm** [comment]
To be clear - I do have the master playbook associated with an identity - and it does use those ssh keys to fetch the project from bitbucket, but the jobs need different ssh credentials to get to the deployment servers.

**Comment by kantmakm** [comment]
AhHa - it wants to use the same ssh key for both fetching the repo AND deploying the playbook.  So the answer is to add the bitbucket ssh key to authorized_keys on the server or add the server's key to bitbucket!

**Comment by matejkramny** [comment]
Indeed, let us know how it goes :+1:!

**Comment by kantmakm** [comment]
Is there a way to kill a zombied task?  I've tried stopping and restarting the node app, but there a task that won't seem to clear out.

![image](https://cloud.githubusercontent.com/assets/833202/7576481/40fbff9e-f7fb-11e4-9352-9c77e91635cf.png)

**Comment by kantmakm** [comment]
Back to original post - you can run jobs through semaphore by specifying the absolute path on the server that ansible runs on (ex. /home/ansible/myjob.yml )  And oddly, that was more intuitive to me than running a relative root job to the git project. (not sure that works on a vagrant install - my install is a pure nodejs w/o any VMs.)  Now I get the relative root (to the project) and it's working fine.

**Comment by matejkramny** [comment]
The 'running' bit in the UI might be slightly deceiving, as it might not actually be running (eg after you restart semaphore while the job runs).

One note for you is that semaphore stores playbooks in /root/. Thats why its preferred to be running in a VM/Docker.

**Comment by kantmakm** [comment]
Semaphore was definitely "stuck" and I could not run any jobs until I deleted everything in the task collection in mongodb.

**Comment by matejkramny** [comment]
I see. Was it stuck running a child process (eg git pull was stuck)?

I would say restarting semaphore would help should that happen again. There's a queue system in (runner.js) which is empty on start and just pressing start in the UI will start queuing it.
The UI can be misleading as i said earlier, indicating that its still 'running' but semaphore was shut down while it was running or got stuck (etc).

**Comment by kantmakm** [comment]
Yes - it got stuck waiting on a password prompt from mysql - In my script I had forgotton it should be:

  - name: Create database.
    shell: mysql -u {{ mysql_user }} -p{{ mysql_password }} < {{ conf_dir }}/{{ project_name }}.sql
with no space between the -p and the password.

I did restart several times thinking that should clear it out, but easy enough just to empty the collection.

I will say this is just a great tool.  I've gotten more done with ansible+semaphore in the past few days than I was able to accomplish with puppet in 2-3 weeks!

**Comment by azimut** [comment]
This is still confusing to me. Can someone write the steps down on a documentation?. I did a "git clone" on /root/ansible but now I can't seem to make the jobs to run.

I really need to run them locally since my playbooks are originally on svn (i have no choice) and I am doing a "git svn clone ...".

**Comment by matejkramny** [comment]
Hi @azimut, steps to do what?

**Comment by ashish235** [comment]
I agree, this was really confusing and complicated to do and I had to really give up using semaphore.

**Comment by Lakshman-LD** [comment]
@ashish235  what git url did u specify for running playbooks in local machine

**Comment by gvenka008c** [comment]
@kantmakm I am seeing the below error when running playbook from semaphore

runner.js:241 fatal: [xx.xxx.xxx.xx]: UNREACHABLE! => {"changed": false, "msg": "ERROR! SSH encountered an unknown error during the connection. We recommend you re-run the command using -vvvv, which will enable SSH debugging output to help diagnose the issue", "unreachable": true}
fatal: [xx.xxx.xxx.xx]: UNREACHABLE! => {"changed": false, "msg": "ERROR! SSH encountered an unknown error during the connection. We recommend you re-run the command using -vvvv, which will enable SSH debugging output to help diagnose the issue", "unreachable": true}

I have the user's public key in his home directory
/home/username/.ssh/authorized_keys

Can you please suggest?

**Comment by kantmakm** [comment]
The way to troubleshoot is to perform each step by hand first - see where it fails. You might want to ssh to the machine and then run a traceroute to the [xx.xxx.xxx.xx] machine and see where the connection hangs.

**Comment by gvenka008c** [comment]
@kantmakm Thanks. I am able to run my playbook using
#ansibile-playbook -i inventory playbookname.yml

But when I run it from semaphore, it is giving ssh issue.

**Comment by gvenka008c** [comment]
@kantmakm How does the ansible playbook gets called? Where does semaphore stores the private/pubic key? 

how does semaphore knows which inventory files to use? We have defined everything in ansible.cfg. Also how can we use a mix of static and dynamic inventory?

**Comment by kantmakm** [comment]
@gvenka008c  You figure that out and post it to the group, OK?

**Comment by gvenka008c** [comment]
@kantmakm sure :) :+1:

**Comment by gvenka008c** [comment]
@kantmakm I logged into the semaphore docker and found that the keys were places under ~/.ssh as id_rsa and id_rsa.pub.

I was able to login to the remote box using an ssh from the docker that is running semaphore

$ sudo docker exec -it semaphore /bin/bash
root@b29051cc8349:/srv/semaphore# cd ~/.ssh/
root@b29051cc8349:~/.ssh# ls -ltr
total 16
-rw-r--r-- 1 root root 2662 Mar 16 00:36 known_hosts
-r-------- 1 root root  436 Mar 16 16:11 id_rsa.pub
-rw------- 1 root root 1674 Mar 16 16:11 id_rsa
-rw-r--r-- 1 root root  116 Mar 16 16:11 config

b29051cc8349:~/.ssh# ssh -i id_rsa gvenka008c@xx.xxx.xxx.xxx
Last login: Wed Mar 16 18:13:02 2016 from a-xx-xxx-xxx-xxx.sys.net
[gvenka008c@icinga-fxbo-02p ~]$

@matejkramny How does semaphore knows to pass my user name "gvenka008c" from within the docker? May be this will help me in fixing the server not reachable issue.

Also where does the downloaded playbook from git gets stored on the docker?

**Comment by kantmakm** [comment]
@gvenka008c   The identities section is where uname, passwd, and keys are kept:
![image](https://cloud.githubusercontent.com/assets/833202/13824090/234dfb80-eb72-11e5-984d-b0149c0f63b2.png)

The downloaded playbooks go into root's home directory.

**Comment by gvenka008c** [comment]
@kantmakm Agreed. But I couldn't find the playbook. Also how does it connect while running the ansible playbook? as the user that we give in Name section of New Identity?

unner.js:241 Updating SSH Keys

runner.js:241 SSH Keys Updated.

runner.js:241
Downloading Playbook.

runner.js:241 Cloning into 'playbook_56e9bdbf202a9e0100a38f19'...
Playbook Downloaded.

When you say root's home directory, did you mean /root? 

ff0e28a9abf2:~# pwd
/root
root@ff0e28a9abf2:~# ls -ltr
total 4
-rwxr-xr-x 1 root root 46 Mar 16 20:14 ssh_wrapper.sh
root@ff0e28a9abf2:~#

**Comment by kantmakm** [comment]
yep /root  and the playbooks get cleaned up after they run - if they fail for some reason, you should see a playbook.yaml.retry file in there.

![image](https://cloud.githubusercontent.com/assets/833202/13827687/8c114d6e-eb83-11e5-883b-4eef457f0517.png)

**Comment by gvenka008c** [comment]
@kantmakm Thanks. So for example i added a user entity as "gvenka008c". So when the playbook runs, does it run as "gvenka008c" or as a root user inside docker? All our servers are centos and won't allow running playbook as root user. 

Can you please post me the command that semaphore uses to run the playbook?

#ansible-playbook -i inventory name playbook.yml -u ???

My playbooks are failing due to ssh issue so i feel it is not connecting as account gvenka008c.

Thoughts?

**Comment by kantmakm** [comment]
It runs as root inside docker and passes through your user credentials to bitbucket and to the remote machine.  Check /etc/log/secure on the remote machine and see if your failed connections are logged.

I'm not sure of the command line semaphore uses to exec playbooks.

**Comment by gvenka008c** [comment]
@kantmakm Thanks. Here is what i see on the remote machine. Just says connection closed.

Mar 16 20:58:17 icinga-fxbo-02p sshd[18403]: Connection closed by xx.xxx.xxx.xxx
Mar 16 20:58:48 icinga-fxbo-02p sshd[20668]: Connection closed by xx.xxx.xxx.xxx

**Comment by matejkramny** [comment]
Just a tip, your `~/.ssh/authorized_keys` may have wrong permissions. Some OS (like CentOS) will see this as insecure and deny any logins

**Comment by gvenka008c** [comment]
@matejkramny I checked the permissions and it is all set to read only

ff0e28a9abf2:~/.ssh# ls -ltr
total 16
-rw-r--r-- 1 root root 2440 Mar 16 20:15 known_hosts
-r-------- 1 root root 1674 Mar 16 21:09 id_rsa
-r-------- 1 root root  436 Mar 16 21:09 id_rsa.pub

**Comment by matejkramny** [comment]
Also check `$HOME`, `$HOME/.ssh`.

The issue may not be there though, so I'd recommend testing the ssh connection by placing the files on your computer and running `ssh -i <path to id_rsa> user@host`

**Comment by kantmakm** [comment]
The fact that you are able to download the playbook with the keys means that your keys are good for ssh-ing - at least to fetch code.  I'd double check the $HOME/.ssh/authorized_keys file on the remote server and ensure that the same public key is indeed there.

**Comment by gvenka008c** [comment]
@kantmakm Yes, both the keys are same.

**Comment by kantmakm** [comment]
Then you should check to see if the semaphore docker is using the same outbound IP as you are and whether or not port 22 is open on the remote machine to the outbound docker IP.  And the permissions on authorized_keys id owner+rw  ?

**Comment by kantmakm** [comment]
Then make sure all key files and auth files are utf-8 encoded.

**Comment by gvenka008c** [comment]
#docker ps shows 0.0.0.0:80->80/tcp . How do make sure docker using same IP as hostname? 
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS              PORTS                NAMES
ff0e28a9abf2        castawaylabs/semaphore:latest   "node /srv/semaphore/"   5 hours ago         Up 5 hours          0.0.0.0:80->80/tcp   semaphore_semaphore_1

Yes, port 22 is opened. I was able to ssh to the remote machine within docker using the id_rsa.

b29051cc8349:~/.ssh# ssh -i id_rsa gvenka008c@xx.xxx.xxx.xxx
Last login: Wed Mar 16 18:13:02 2016 from a-xx-xxx-xxx-xxx.sys.net
[gvenka008c@icinga-fxbo-02p ~]$

root@b29051c:~/.ssh# ls -ltr
total 16
-rw-r--r-- 1 root root 2662 Mar 16 00:36 known_hosts
-r-------- 1 root root 436 Mar 16 16:11 id_rsa.pub
-rw------- 1 root root 1674 Mar 16 16:11 id_rsa
-rw-r--r-- 1 root root 116 Mar 16 16:11 config

**Comment by kantmakm** [comment]
Check the /etc/sudoers file on the server and ensure that defaults requiretty is commented out
#defaults requiretty   (Thats from memory, it's something close to that.)

Also make sure the sudo user does not have to enter a password to sudo.

**Comment by gvenka008c** [comment]
@kantmakm Yes, checked and it is commented out already.

icinga-fxbo-02p ~]# more  /etc/sudoers | grep requiretty
#Defaults    requiretty

Also sudo user is not required to enter password.
[gvenka008c@icinga-fxbo-02p ~]$ sudo su
[root@icinga-fxbo-02p gvenka008c]#

**Comment by gvenka008c** [comment]
@here @kantmakm @matejkramny Any updates?

**Comment by matejkramny** [comment]
@gvenka008c sorry, but I am running out of ideas here.

My suggestion it was something with ssh. Semaphore simply runs bash commands through a web interface.

Re-reading this thread, your logs said the host is `UNREACHABLE`. This would indicate connection problems to ssh, as we've discussed later, however the issue may be before it reaches ssh. Eg, it cannot connect to the box at all from semaphore.

Some research leads to [here](https://github.com/ansible/ansible/issues/12916#issuecomment-156316370) and [here](http://sgargan.blogspot.co.uk/2013/10/troubleshooting-ssh-connections-in.html)

You can also try adding a line below [this one](https://github.com/ansible-semaphore/semaphore/blob/master/lib/runner.js#L197):

```
args.push('-vvvv');
```

**Comment by gvenka008c** [comment]
@matejkramny I logged into sempahore as admin@semaphore.local. I setup up all the hosts, keys etc to run the playbook. 

When establishing SSH connection, there is no user. Where does this gets the user name from? Is this the user that we create and add ssh keys? Any reason why it is not populating user name?

TASK [setup] *******************************************************************
<96.119.246.11> ESTABLISH SSH CONNECTION FOR USER: None

In the script i see as below
     LOGNAME: user,
     USER: user,

**Comment by matejkramny** [comment]
@gvenka008c the SSH user can be specified in the playbook.

**Comment by anjoze** [comment]
Try this:

https://github.com/semaphoreui/semaphore/issues/558#issuecomment-2503801516
