### ISSUE TITLE
Problem: schedules are deleted after (associated) template update

### ISSUE THREAD

**Issue by gaeldb** [ansible-semaphore/semaphore#2204]
### Issue

Hello team,

We encounter a blocking problem after updating to version 2.10.11-d31ebd3-1719394739.
Schedules are deleted after every template update.

Steps to reproduce:
- Create a template.
- Create a schedule and assign to the template.
- (Manual execution: OK, schedule execution: OK)
- Edit template, and save.
- **Schedule have been deleted.**

The delete action is listed in project activity, see attached capture.
Nothing in semaphore service logs.

### Impact

Service (scheduled tasks, alerts)

### Installation method

Binary

### Database

MySQL

### Browser

Firefox

### Semaphore Version

2.10.11-d31ebd3-1719394739

### Logs & errors

![image](https://github.com/user-attachments/assets/3de7d328-b509-46c7-b194-cbf7757863ff)

**Comment by gaeldb** [comment]
Tested 2.10.21 with BoltDB (docker)
Same blocking bug

**Comment by gaeldb** [comment]
Seems to be related to https://github.com/semaphoreui/semaphore/blob/24bc4a83b8f1c75a870e2b88b980454dddb61b2e/web/src/components/TemplateForm.vue#L588

Schedule is dropped during registering.
I can provide a PR with fix, but need to understand the concept.

Here, if we have only 1 schedule for the template => it will be this.schedules[0] and it will always be deleted.

**Comment by gaeldb** [comment]
Should be fixed by 2.10.22
Testing

**Comment by fiftin** [comment]
Hi @gaeldb yes, has been fixed in v2.10.222.

Thank you for your help!

**Comment by gaeldb** [comment]
I confirm => all good now
Thank you ++
