### ISSUE TITLE
can't connect to MySQL

### ISSUE THREAD

**Issue by nganivet** [ansible-semaphore/semaphore#221]
Brand new install, default configuration except for indicating a MySQL password, MySQL server is running locally, the password has been double-checked and the semaphore database exists (mysql -h localhost -u root -p semaphore).
```
 Pinging database..

 Cannot connect to database!
 dial tcp 127.0.0.1:3306: getsockopt: connection refused
```
What else could be wrong? Has this something to do with the fact that redis is n o longer required and configured? I am running semaphore as root for this test, so filesystem perms should not be an issue.

**Comment by cedr-x** [comment]
try remove "-h localhost" or  check if "skip-networking" is in the args of your server with 
`# tr '\0' '\n' </proc/$(pgrep  'mysqld$')/cmdline`

**Comment by matejkramny** [comment]
Let us know if there is a bug in the code preventing the connection to your mysql server
