### ISSUE TITLE
Template Creating error + only 2 apps avalible

### ISSUE THREAD

**Issue by masterwishx** [ansible-semaphore/semaphore#2211]
### Issue

When creating Ansible Template , template created in history but not available/seen in Menu :  

![image](https://github.com/user-attachments/assets/33fd3e58-e539-4059-bfdc-596d42968a3e)

Also only 2 apps avalible :  

![image](https://github.com/user-attachments/assets/ed5d186c-2214-4e2a-a0e7-77a7d06bb748)

### Impact

Service (scheduled tasks, alerts), Docker

### Installation method

Docker

### Database

MySQL

### Semaphore Version

Using latest version of  https://github.com/imagegenius/docker-semaphore

**Comment by masterwishx** [comment]
back to 2.10.19 fixed issue with new template created

**Comment by masterwishx** [comment]
Template issue fixed in lasted 2.10.21.
But 2 apps still available in lasted version

**Comment by fiftin** [comment]
Hi, it is really strange... Trying to reproduce.

**Comment by masterwishx** [comment]
> Hi, it is really strange... Trying to reproduce.

Using https://github.com/imagegenius/docker-semaphore in Unraid

**Comment by masterwishx** [comment]
> Hi, it is really strange... Trying to reproduce.

Wow, just checked the lasted version 2.10.22 and seems it was fixed !  

![image](https://github.com/user-attachments/assets/43076455-4056-4975-b309-1e5f11142970)

**Comment by masterwishx** [comment]
> Hi, it is really strange... Trying to reproduce.

Now have another issue cant run any task :(
https://github.com/semaphoreui/semaphore/issues/2218
