### ISSUE TITLE
Problem: Tasks not visible in v2.10.20

### ISSUE THREAD

**Issue by tinyoverflow** [ansible-semaphore/semaphore#2213]
### Issue

The Task Templates page doesn't show any task templates, even though they exist. I've tested this by opening the task details page manually by ID.
![pic1](https://github.com/user-attachments/assets/ffb9f935-e950-48db-aa73-c437b87e9934)

This bug was introduced in v2.10.20. Downgrading to v2.10.19 resolves this issue.
![image](https://github.com/user-attachments/assets/a49ca01a-49c4-44e3-a8be-93b4719679ed)

This is also a fresh install via Docker with just the admin user created using environment variables.

### Impact

Web-Frontend (what users interact with)

### Installation method

Docker

### Database

MySQL

### Browser

Firefox, Chrome

### Semaphore Version

v2.10.20-21ba6c6-1721538018

**Comment by Peteco007** [comment]
Hello ! 

I have the same issue here. However I don't use docker and my database engine is PostgreSQL. Reverting to version v2.10.19 solves the problem for me too.

**Comment by bakito** [comment]
Same issue here with 2.10.20 and bolt db.

**Comment by masterwishx** [comment]
i have very close issue but new tasks not visible
https://github.com/semaphoreui/semaphore/issues/2211

**Comment by masterwishx** [comment]
back to 2.10.19 fixed issue with new template created

**Comment by masterwishx** [comment]
checked again ,it seems the task that was not runned are not shown

**Comment by fiftin** [comment]
Thank you all! Fixed in v2.10.21.
