### ISSUE TITLE
Problem: Inconsistent versioning. Docker tag `v2.19.10`.

### ISSUE THREAD

**Issue by deadnews** [ansible-semaphore/semaphore#2215]
### Issue

The docker tag `v2.19.10` is inconsistent with the latest version. The latest version is `v2.10.21`.

[v2.19.10](https://hub.docker.com/layers/semaphoreui/semaphore/v2.19.10/images/sha256-ddc0592cc23693927fc74b9bc2b16615d4f1914d4e3faf5e6ce621dfaaa1adec) — a month ago
[v2.10.21](https://hub.docker.com/layers/semaphoreui/semaphore/v2.10.21/images/sha256-93dadf7954467c99ac8f91ea2064f6b761de8a98e4005fdd75d18cf8e59d234d) — 2 hours ago
[latest](https://hub.docker.com/layers/semaphoreui/semaphore/latest/images/sha256-93dadf7954467c99ac8f91ea2064f6b761de8a98e4005fdd75d18cf8e59d234d) — 2 hours ago

Tools like [renovate](https://github.com/renovatebot/renovate) will not be able to update the image to the latest version because of the inconsistency.

### Impact

Docker

### Installation method

Docker

### Semaphore Version

v2.19.10

**Comment by bakito** [comment]
I used a renovate package rule as work-around.
```
  "packageRules": [
    {
      "matchPackageNames": [
        "semaphoreui/semaphore"
      ],
      "allowedVersions": "<2.19.0"
    }
  ]
```

**Comment by fiftin** [comment]
Tag removed. Thank you!
