### ISSUE TITLE
Problem: Initialize Terraform pg backend with env variables

### ISSUE THREAD

**Issue by sti0** [ansible-semaphore/semaphore#2242]
### Issue

I'm trying to setup a Terraform task with a [PG backend](https://developer.hashicorp.com/terraform/language/settings/backends/pg). 

As recommended I use the [libpg environment variable](https://www.postgresql.org/docs/current/libpq-envars.html#LIBPQ-ENVARS). This works flawless when executing Terraform locally.

I put the pg env variables (`PGHOST`, `PGUSER`....) into a Semaphore environment object which is assigned to the task. But this won't work. After executing the task it still tries to connect to localhost instead:

```
11:37:44 AM
11:37:44 AM
Initializing the backend...
11:37:44 AM
╷
11:37:44 AM
│ Error: dial tcp 127.0.0.1:5432: connect: connection refused
11:37:44 AM
│ 
11:37:44 AM
│ 
11:37:44 AM
╵
```

### Impact

Other

### Installation method

Docker

### Database

Postgres

### Browser

Chrome

### Semaphore Version

2.10.22

### Configuration

![image](https://github.com/user-attachments/assets/9a01c863-4c0d-4593-9ef5-6d46c6b30d36)

![image](https://github.com/user-attachments/assets/5f47d0b2-aa5b-4abb-8087-5465c845ea9e)

![image](https://github.com/user-attachments/assets/19a905cf-30df-4b63-9fff-b2c2abb019d0)

**Comment by sti0** [comment]
Seems that `environment_variables` are not applied when doing `terraform init` (https://github.com/semaphoreui/semaphore/blob/a5ea39e229b2d703990f317fa919b2e05cc96793/db_lib/TerraformApp.go#L87). Could this be the reason?

Same line might be the reason why other Terraform CLI parameters are not applied as well (no more arguments applied).

**Comment by ollikurki** [comment]
Hello, I checked and at least the secret environment variable type works if you put TF_VAR_ prefix to your variable name so I would think the normal environment variables would too. You will need to create the secrets again it seems, at least when I tested it they didn't update.

Edit: fixed the prefix

**Comment by sti0** [comment]
Hi @ollikurki ,
I recreated the env variables and prefixed them with `TF_ENV_`. 
![image](https://github.com/user-attachments/assets/f9ddc106-ba87-4b3f-8691-4680703a5fea)

This doesn't work:
![image](https://github.com/user-attachments/assets/41cc2347-0e4c-4992-b61a-5c262a95b31e)

In my understanding env variables are not passed to the `init` command as well:
https://github.com/semaphoreui/semaphore/blob/a5ea39e229b2d703990f317fa919b2e05cc96793/db_lib/TerraformApp.go#L87

**Comment by ricorx7** [comment]
I believe I see a similar issue with Terraform AWS S3 backend.  I get the same error when it tries to initialize the backend.  I have set up the environment with ENV and Secret ENV values.  I have prefixed with TF_VAR_ and nothing works.  If I log into the container and go where the repository was cloned and manually set the ENV variables, then`terraform init` works.  So I know setting ENV should allow everything to work.
![image](https://github.com/user-attachments/assets/fa66eb57-8e02-4abf-861d-b56e8f7ea496)

**Comment by ollikurki** [comment]
Ahh yeah, I typo'd the prefix it should be TF_VAR_ and for me it works on the Secrets section if I create "Secret Environment Variable" type secrets:
![image](https://github.com/user-attachments/assets/8a90f754-f1ae-4848-9215-f6acf4d894be)
![image](https://github.com/user-attachments/assets/99d5908b-5871-43d5-89c6-b2cef5d4cc4c)
![image](https://github.com/user-attachments/assets/d3b7a7b8-542f-4938-9eb5-b69541938d88)
![image](https://github.com/user-attachments/assets/da53ea37-6eb9-4399-9b71-e9399d96f425)
![image](https://github.com/user-attachments/assets/f48c23d6-9068-4883-9bc0-0a224f1521d4)

But yeah, the normal Environment Variables don't seem to work.

**Comment by sti0** [comment]
It works for Terraform variables.

But in case of Postgres backend we don't use Terraform variables but host environment variables (PGHOST, PGUSER....). These variables need to be accessable in the init command.

It's not possible to use Terraform variables to define backend credentials.

**Comment by ollikurki** [comment]
Ohh, sorry I wasn't of much help then. I just fixated on the variable point because I had the same problem with the Environment Variables not working when trying to use terraform for my hypervisor and didn't clearly read the whole issue.

**Comment by mohamed-mfarag** [comment]
Same issue here with Terraform http backend initialisation during init phase.

**Comment by maxim-vde** [comment]
Same issue here when using the AWS S3 backend:

![image](https://github.com/user-attachments/assets/593f4c8a-0999-464b-9f7a-65fc1cfa00d1)

The backend doesn't use TF VARS but actual environment variables.
