### ISSUE TITLE
Unable to connect to mysql from docker container

### ISSUE THREAD

**Issue by charlesmims** [ansible-semaphore/semaphore#229]
Semaphore running in docker is unable to connect to mysql.  I'm probably doing something wrong, but figured it was worth seeing if anyone can spot what that is, and documenting how to do it better than the existing documentation.

steps to reproduce:

`git clone https://github.com/ansible-semaphore/semaphore.git`

`docker run -d --name=mysql -e MYSQL_ROOT_PASSWORD=secret-pw mysql`

`IPADDRESS=$(docker inspect mysql | jq -r .[0]."NetworkSettings"."Networks"."bridge"."IPAddress")`

`docker run -it --link mysql:mysql -p 3000:3000 --name semaphore -e SEMAPHORE_ADMIN=charles -e SEMAPHORE_ADMIN_EMAIL=charlesmims@gmail.com -e SEMAPHORE_ADMIN_NAME="Charles Mims" -e SEMAPHORE_ADMIN_PASSWORD=secretpw2016 -e SEMAPHORE_DB_HOST=$IPADDRESS -e SEMAPHORE_DB_PORT=3306 -e SEMAPHORE_DB_PASS=secret-pw -e SEMAPHORE_DB=semaphore -e SEMAPHORE_DB_USER=root charlesmims/semaphore semaphore -config /tmp/semaphore/semaphore_config.json`

I get ```Attempting to connect to database semaphore on 172.17.0.2 with user:pass root:secret-pw
waiting
waiting
waiting
waiting
waiting```

Troubleshooting, 
I connected to the semaphore container with `docker exec -it semaphore sh` and installed mysql with `apk add --update semaphore` and then was able to connect to mysql using mysql client:
```
/ # mysql -h 172.17.0.2 -p
Enter password:
Enter password:
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MySQL connection id is 72
Server version: 5.7.16 MySQL Community Server (GPL)

Copyright (c) 2000, 2016, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MySQL [(none)]>
```

```/ # env|grep DB
SEMAPHORE_DB_PORT=3306
SEMAPHORE_DB=semaphore
SEMAPHORE_DB_PASS=secret-pw
SEMAPHORE_DB_HOST=172.17.0.2
SEMAPHORE_DB_USER=root```

**Comment by matejkramny** [comment]
`SEMAPHORE_DB_HOST` can just be `mysql` since docker provides hostname entries to linked containers.

You also seem to be running config from a file and providing environment variables?

**Comment by bugacha** [comment]
I'm running into the same issue in 2025

I'm taking docker-compose from here 
https://docs.semaphoreui.com/administration-guide/installation/docker/

upon start I get this :

```
nc: bad address 'mysql'
nc: bad address 'mysql'
```

**Comment by fiftin** [comment]
Hi @bugacha what version? Cloud you share your docker compose file?

**Comment by Sheenam3** [comment]
@bugacha I was able to resolve this error by changing /etc/resolv.conf and add this as a first line : nameserver 127.0.0.11

nameserver 127.0.011 (should be the first line) to /etc/resolv.conf  on the host and mount the file from docker compose. we need to make sure this should not happen or reset itself because docker is using automatic service discovery and with custom network it is not able to access other containers with the name. i.e why it is not able to access nc: bad address 'mysql'.
