### ISSUE TITLE
Question: I have a list of hosts in my inventory file, and I need to use a different SSH key for each host. How can I configure this so that each host is accessed with its unique SSH key, rather than using a single key for all hosts?

### ISSUE THREAD

**Issue by chakib2002** [ansible-semaphore/semaphore#2300]
### Question

I have a list of hosts in my inventory file, and I need to use a different SSH key for each host. How can I configure this so that each host is accessed with its unique SSH key, rather than using a single key for all hosts?

### Related to

Ansible (task execution)

**Comment by whafflez** [comment]
Hey, this kinda depends on how you have installed Semaphore.

I have it running in docker and have used a bind to make the files (I have about 4 SSH keys) accessible within the container and then they can be manually specified in the vars section of the hosts file (whether you manually enter it or pull it from your git repository is up to you).

**Comment by chakib2002** [comment]
@whafflez Thank's for sharing that
