### ISSUE TITLE
Database migrations failed!

### ISSUE THREAD

**Issue by TeMbl4** [ansible-semaphore/semaphore#234]
Mysql Version:
mysql  Ver 14.14 Distrib 5.5.53, for debian-linux-gnu (x86_64) using readline 6.3

After config qustions...i see this:
Pinging database..
 Running DB Migrations..
Skipping v0.0.0
Skipping v1.0.0
Executing migration v1.1.0 (at 2016-12-02 11:30:28.373489481 -0500 EST)...
 [1/1]
 ERR! Query: /* update precision of output logs - also prevents confusion when sorting the table to guarantee it is in the same order */
alter table task__output change `time` `time` datetime(6) not null;

Rolling back v1.1.0 (time: 2016-12-02 11:30:28.374125539 -0500 EST)...
Rollback SQL doesn't exist.

 Database migrations failed!
 Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(6) not null' at line 2

i hope it help

**Comment by matejkramny** [comment]
Hi! Please see https://github.com/ansible-semaphore/semaphore/wiki/Installation.

Your Mysql version is too old!

We have a ticket to support older versions but it means rewriting the way output logs are stored.
