### ISSUE TITLE
2.0.5 release?

### ISSUE THREAD

**Issue by gcavalcante8808** [ansible-semaphore/semaphore#236]
There are 37 commits since the last release... Can you provide a New build containing the changes? If possible, merge nikita's event color pr ... Thank you

PS Im waiting for this release to build a New gcavalcante8808/ansible-semaphore image. 

Thanks in advance.

**Comment by matejkramny** [comment]
There is still a lot to fix before releasing.

Will be 2.1 because there are changes to migrations

**Comment by matejkramny** [comment]
Coming up
