### ISSUE TITLE
Problem: CLI Arg in task only in JSON format

### ISSUE THREAD

**Issue by ghost** [ansible-semaphore/semaphore#2367]
### Issue

It would be great to not have to write in JSON the CLI args when running a task.

Currently to limit an Ansible playbooK I need to do :

![image](https://github.com/user-attachments/assets/c583c805-aeba-42e4-acbc-0f4a4401671e)

But if I add the arg in the task template, it works without being in JSON format :

![image](https://github.com/user-attachments/assets/3628402c-4f7f-45fe-8331-03fa07909c14)

The goal would be to be able to limit the scope of an ansible playbook easily like in CLI without having to format in JSON every time.

### Impact

Web-Frontend (what users interact with), Ansible (task execution), Configuration

### Installation method

Package

### Database

MySQL

### Browser

Chrome

### Semaphore Version

2.10.22-e44910d-1721658299

### Ansible Version

```bash
ansible [core 2.14.14]
```

### Manual installation - system information

        'c:.                              
        lkkkx, ..       ..   ,cc,           ----------------
        okkkk:ckkx'  .lxkkx.okkkkd          OS: AlmaLinux 9.4 x86_64
        .:llcokkx'  :kkkxkko:xkkd,          Host: VMware20,1
      .xkkkkdood:  ;kx,  .lkxlll;           Kernel: Linux 5.14.0-427.33.1.el9_44
       xkkx.       xk'     xkkkkk:          Uptime: 18 hours, 39 mins
       'xkx.       xd      .....,.          Packages: 1237 (rpm)
      .. :xkl'     :c      ..''..           Shell: bash 5.1.8
    .dkx'  .:ldl:'. '  ':lollldkkxo;        Display (Virtual-1): 1280x800 @ 60 z
  .''lkkko'                     ckkkx.      Cursor: Adwaita
'xkkkd:kkd.       ..  ;'        :kkxo.      Terminal: /dev/pts/0
,xkkkd;kk'      ,d;    ld.   ':dkd::cc,     CPU: Intel(R) Xeon(R) Silver 4216 (z
 .,,.;xkko'.';lxo.      dx,  :kkk'xkkkkc    GPU: VMware SVGA II Adapter
     'dkkkkkxo:.        ;kx  .kkk:;xkkd.    Memory: 932.52 MiB / 15.34 GiB (6%)
       .....   .;dk:.   lkk.  :;,           Swap: 0 B / 32.00 GiB (0%)
             :kkkkkkkdoxkkx                 Disk (/): 7.35 GiB / 85.95 GiB (9%)s
              ,c,,;;;:xkkd.                 Local IP (ens33): 192.168.3.18/22
                ;kkkkl...                   Locale: en_CA.UTF-8
                ;kkkkl
                 ,od;

### Configuration

Inventory / task scope limitation.

**Comment by fiftin** [comment]
Hi @SysAdminShed 

You are right. Looks like new args UI works not as expected :)

**Comment by ghost** [comment]
Wanted to add the following :

When adding multiple limit of the scope (with proper JSON format), it gives the following error :

9:51:06 AM
ERROR! the playbook: Producer could not be found

JSON format used : ["-l", "benchtest","benchtest2"]

**Comment by kingp0dd** [comment]
i tried limiting host by

["-l", "host"] 

but getting error 

ERROR! the playbook: ["-l", "host"] could not be found

**Comment by ghost** [comment]
Don't use the JSON format, just input the -l host.

Best,

**Comment by kingp0dd** [comment]
that worked thank you

**Comment by CryptoFewka** [comment]
Odd behavior discovered today: 
This works: `-l groupName`
This fails: `--limit groupName`

The error message received is: `ERROR! the playbook: --limit groupName could not be found`

It seems that the template's CLI args field cannot handle `--limit`, though `-limit` and `-l` both work.

**Comment by CryptoFewka** [comment]
This also means that things like `--skip-tags` and `--vault-password-file` won't work currently when defined in CLI Args.
