### ISSUE TITLE
Docs: Can't see Swagger api from doc

### ISSUE THREAD

**Issue by salvio2v** [ansible-semaphore/semaphore#2368]
### Problem

At https://semaphoreui.com/api-docs/ the page has no description of apis.

**Comment by AETH-erial** [comment]
+1 for this, the routes "https://semaphoreui.com/swagger-ui-bundle.js" and "https://semaphoreui.com/swagger-ui-standalone-preset.js" are coming back with a 403 response code.

In the response headers for those two endpoints, i am also seeing
`x-cache: Error from cloudfront`

**Comment by fiftin** [comment]
Fixed )
