### ISSUE TITLE
Problem: Many scheduled jobs accumulated, all are showing as "Waiting"

### ISSUE THREAD

**Issue by anultravioletaurora** [ansible-semaphore/semaphore#2376]
### Issue

I have an Ansible job in Semaphore that runs every 10 minutes. I'm not sure what happened but overnight I saw that Semaphore had 200 jobs showing as "Waiting". 
![image](https://github.com/user-attachments/assets/5e068924-dbc8-4589-ae54-55501321fdc0)

I've since canceled this job from running, but I'm wondering if there a way to batch delete these jobs so that I can get jobs running again?

### Impact

Ansible (task execution)

### Installation method

Docker

### Database

Postgres

### Browser

Firefox, Chrome, Safari

### Semaphore Version

v2.10.22-e44910d-1721658561

**Comment by anultravioletaurora** [comment]
Not sure what happened but now jobs are executing again - closing this issue!

**Comment by fiftin** [comment]
Hi @anultravioletaurora please reopen the issue if you will get it again.

Thank you
