### ISSUE TITLE
Feature request: SQLite support

### ISSUE THREAD

**Issue by rakshazi** [ansible-semaphore/semaphore#238]
Hello!
It will be very good enhancement to support both MySQL and SQLite databases.
Can you implement this feature, please?

It's the best solution for small teams.

pS: In my case (our team case) we have MySQL server only for running semaphore

**Comment by matejkramny** [comment]
is this embedded sqlite or is it running as its own instance?

**Comment by rakshazi** [comment]
@matejkramny better is embedded version, because it can be used as portable solution and does not need any additional dependencies on running host

**Comment by matejkramny** [comment]
Go supports the sqlite dialect (as well as postgres).

Quick search shows this package: https://github.com/mattn/go-sqlite3

It's definitely possible

**Comment by rakshazi** [comment]
@matejkramny thank you!

**Comment by fiftin** [comment]
This feature will not be implemented. SQLite require CGo. We want to keep Ansible Semaphore as "Pure Go" software. We working on BultDB support.
