### ISSUE TITLE
Problem Cookie Reverse Proxy

### ISSUE THREAD

**Issue by albruz** [ansible-semaphore/semaphore#239]
Hello! I set up an apache reverse proxy to secure Semaphore but when I try to log in it keeps me in the login page even if it was succesfull..i think it could be a problem with the cookie but i can't figure out a solution..any ideas?

**Comment by matejkramny** [comment]
Look for the cookie it is sending (if any). Could be domain/expiry of the cookie being sent or the reverse proxy ignoring the cookie header.

**Comment by rakshazi** [comment]
Possibly duplicate of #193
