### ISSUE TITLE
Feature: improve some parts of the UI which are hard to use currently

### ISSUE THREAD

**Issue by steadfasterX** [ansible-semaphore/semaphore#2398]
### Related to

Web-Frontend (what users interact with)

### Impact

better user experience

## menu: "Environment Variables"
* I use a big screen and it is always a problem to identify the correct line to edit an environment file. see attached screen.
the current annoying workaround is detach the tab from the browser, shrink the window width, find & edit
![Screenshot_20241008_125150](https://github.com/user-attachments/assets/0ea3f045-4437-4466-b51d-2a04bc28e994)

## menu: "Inventory"
* big screen or not but the edit window of a static inventory is waaaay **too small**. this plus the fact that tabs will break everything (#1204) making managing an inventory a very annoying task :) 
![Screenshot_20241008_125243](https://github.com/user-attachments/assets/5504fbea-dd8e-41e8-91ae-0d8ed267e7a2)

## menu: "Task Templates" -> Task log
* tasks which produces a LOT of output (hundreds of lines) will totally mess-up the whole output. it looks like these lines will be printed within the tasks coming next
    * Example: https://gist.github.com/steadfasterX/c27661c1a3ef498772b12577a21e4b92 . that log output starts from the problematic task which then prints that much that it overloads the next tasks making it almost impossible to track
* output can contain very long lines where you need to scroll endlessly to the right. it would be great if it line wrap at the end of the window maybe?
  

## menu: "Environment Variables"
either dynamically shrink the width of the frame or maybe even better(?): move the edit pencil button at the beginning (left of the env name). problem with the latter is that this breaks the design flow with other menus where the edit pencil is on the right always

## menu: "Inventory"
allow to increase width and height of the input box (e.g. by mouse drag/drop in the bottom right corner of that box or similiar)

## menu: "Task Templates" -> Task log
* the first one might occur as there is a limit hardcoded somewhere so increasing that _might_ be a quick solution. **but** problematic is that this might overload a browser though. so I guess a better approach would be to just do not print that much output and instead give a message that the output is truncated (which would be a very important info then)
* the second one is likely "just" a line wrap when its longer then X

**Comment by tdrnz** [comment]
Another vote for wrapping output text in the the task log window.

Have been dealing with a lot of Mikrotik gear lately and the outputs when gathering current OS/firmware levels are quite long. When running via a terminal application the output is fine but Semaphore not so much.

![image](https://github.com/user-attachments/assets/07fffe87-df5c-48a0-a1f8-70c1ea8030f1)

**Comment by fiftin** [comment]
I hope all issues has been fixed in 2.11.0.

**Comment by steadfasterX** [comment]
awesome!
word wrap in task output
re-sizable window
env view is usable on big screens!
great job as always dude!

**Comment by tdrnz** [comment]
Legend!
Excellent work, thank you very much!
