### ISSUE TITLE
Getting 'TypeError: Cannot read property 'private_key' of undefined' when running playbook

### ISSUE THREAD

**Issue by vsayer** [ansible-semaphore/semaphore#24]
Hi,

I'm getting semaphore to crash when running a playbook.

Steps to reproduce:
1. Add identity: populated name, private key (copied from ~/.ssh/id_rsa), public key (copied from ~/.ssh/id_rsa.pub); password was not entered (what is that field for?)
2. Add Playbook: populated name, playbook location (used ssh://user@ip_address/path/to/playbook.git), identity used was above identity from 1. vault password wasn't entered (what is this for?)
3. Add a host group and host; doubt that this affects the bug although it's not clear which host group your playbook would use if your playbook is group generic.
4. Add job under created playbook: some path under the git repository specified above)
5. On run job, I get this: "TypeError: Cannot read property 'private_key' of undefined" and semaphore subsequently crashes.

If you could also a HOWTO for a test playbook flow, that would help the end user use this. Thanks

**Comment by vsayer** [comment]
Also, it appears at the git clone step, semaphore is updating my keys to require a passphrase. Is that correct? If so, what's the workaround if I have no passphrase set for my keys?

**Comment by rmessner** [comment]
Hi, 

I'm having the same issue.
In my case, it didn't save the identity, that's why when you try to start a job, you got the "TypeError: Cannot read property 'private_key' of undefined".

I worked around this by editing again the playbook, you can see that the identity is not set, select it and save again. This should be working.

**Comment by matejkramny** [comment]
This issue is that either the key is null/undefined in the database or the `_id` is not leading to a key.

You can edit the database.

If your question is still relevant, what is the log output?
