### ISSUE TITLE
common inventory..

### ISSUE THREAD

**Issue by emb3dd3d** [ansible-semaphore/semaphore#240]
Not sure how to mark this as an enhancement request..

It would be nice to have a common inventory to select into the projects instead of having to create a new inventory for each project.  I kinda quickly looked around but didn't see any info on a shared inventory pool.   

It looks good!!  People have been wanting an alternative.. I am stumbling around with foreman now  and getting the inventory into it is just a nightmare, whenever there is an update.

Keep up the good work.

**Comment by matejkramny** [comment]
Inventories can be global without changes in the database, but the UI and API needs to support that.

What's your reason for using an alternative?

**Comment by rakshazi** [comment]
Referred to #225

**Comment by emb3dd3d** [comment]
right on!!
