### ISSUE TITLE
Problem: cron input field in task template missing

### ISSUE THREAD

**Issue by fpodschwadek** [ansible-semaphore/semaphore#2402]
### Issue

After updating to the latest Docker image of `semaphoreui/semaphore`, the input field for cron settings in task templates is no longer available (see screenshot). It should assumedly sit between the `View` selection and the `I want to run a task ...` checkbox.

Cron jobs set with earlier versions are still running but the cron settings field is also no longer available in the task template for those.

![image](https://github.com/user-attachments/assets/129307e9-4715-4a22-88bc-a2e479e62aae)

### Impact

Web-Frontend (what users interact with), Service (scheduled tasks, alerts)

### Installation method

Docker

### Database

MySQL

### Browser

Firefox

### Semaphore Version

latest: Pulling from semaphoreui/semaphore  
Digest: sha256:2a2df841e4b6b33e82f87101e942ab6008207bd3b8e936bc9a48e2eea3671498  
Status: Image is up to date for semaphoreui/semaphore:latest  
docker.io/semaphoreui/semaphore:latest

**Comment by fiftin** [comment]
Hi @fpodschwadek 
It has been moved to separate page **Schedule**. According to many comments it is more useful then in Template. You can apply multiple schedules to one template. Additionally  you can active/deactivate schedules.

![image](https://github.com/user-attachments/assets/361d1e00-335c-40ed-bd34-16216c0608df)

**Comment by fpodschwadek** [comment]
Splendid! Thanks for the quick reply!
