### ISSUE TITLE
Adding a Task Template fails: Error 500.

### ISSUE THREAD

**Issue by robertdebock** [ansible-semaphore/semaphore#243]
When I'm using the UI to add a Task Template, I'm returned an Internal Server Error, 500. The logs display this message: `Error 1054: Unknown column 'alias' in 'field list'`.

Using Semaphore version 2.1.0.

I've setup [tests using cURL](https://github.com/robertdebock/docker-compose-semaphore/blob/master/tests/tests.bats) to reproduce this error. The [results are here](https://travis-ci.org/robertdebock/docker-compose-semaphore/builds/188804762).

Semaphore shows: (from docker-compose)
```
semaphore    | 2017/01/04 10:11:27 notifying bugsnag: Error 1054: Unknown column 'alias' in 'field list'
semaphore    | 
semaphore    | 
semaphore    | 2017/01/04 10:11:27 [Recovery] panic recovered:
semaphore    | POST /api/project/1/templates HTTP/1.1
semaphore    | Host: localhost
semaphore    | Accept: */*
semaphore    | Connection: Keep-Alive
semaphore    | Content-Length: 119
semaphore    | Content-Type: application/json
semaphore    | Cookie: semaphore=MTQ4MzUyNDY4Nnw1Z3ZjVUJsazdUSnAyX1d1WlpuSlh2bUZvQUxoeml1d2xnVkxiRGVZR3NYQXNWM1B0RHBwd1RlT3NXSzU4dS1vbHZKQ0NfQ2hHS3FJb2pGYzQycmxJMzQ9fLOSxGxevQU5dJa3JQPFTyOHk3elt6JF_E--4NQLqZDb
semaphore    | User-Agent: curl/7.51.0
semaphore    | X-Forwarded-For: 172.19.0.1
semaphore    | X-Forwarded-Host: localhost
semaphore    | X-Forwarded-Server: semaphore.meinit.nl
semaphore    | 
semaphore    | 
semaphore    | Error 1054: Unknown column 'alias' in 'field list'
semaphore    | /usr/local/go/src/runtime/panic.go:458 (0x42adc3)
semaphore    | /Users/m/p/gospace/src/github.com/bugsnag/bugsnag-go/bugsnag.go:52 (0x50e003)
semaphore    | /usr/local/go/src/runtime/asm_amd64.s:479 (0x4588ac)
semaphore    | /usr/local/go/src/runtime/panic.go:458 (0x42adc3)
semaphore    | /Users/m/p/gospace/src/github.com/ansible-semaphore/semaphore/api/projects/templates.go:62 (0x619605)
semaphore    | /Users/m/p/gospace/src/github.com/gin-gonic/gin/context.go:97 (0x51573a)
semaphore    | /Users/m/p/gospace/src/github.com/ansible-semaphore/semaphore/api/projects/project.go:39 (0x615743)
semaphore    | /Users/m/p/gospace/src/github.com/gin-gonic/gin/context.go:97 (0x51573a)
semaphore    | /Users/m/p/gospace/src/github.com/gin-gonic/gin/logger.go:66 (0x524167)
semaphore    | /Users/m/p/gospace/src/github.com/gin-gonic/gin/context.go:97 (0x51573a)
semaphore    | /Users/m/p/gospace/src/github.com/ansible-semaphore/semaphore/cli/main.go:72 (0x4016e2)
semaphore    | /Users/m/p/gospace/src/github.com/gin-gonic/gin/context.go:97 (0x51573a)
semaphore    | /Users/m/p/gospace/src/github.com/gin-gonic/gin/recovery.go:45 (0x524ffa)
semaphore    | /Users/m/p/gospace/src/github.com/gin-gonic/gin/context.go:97 (0x51573a)
semaphore    | /Users/m/p/gospace/src/github.com/gin-gonic/gin/gin.go:284 (0x51b6be)
```

Please tell me that I'm incorrect, but it looks like a bug.

**Comment by gcavalcante8808** [comment]
This error seems to be related to the fact that only the -setup triggers the dB migration. If we check at the gcavalcante8808/ansible-semaphore the problem wont occur because of the -setup on the first run.

**Comment by robertdebock** [comment]
Thanks @gcavalcante8808, I've updated my code and it works perfectly.

**Comment by nhproject** [comment]
I'm trying to add or modify template, I'm getting the following error on the log:

> [GIN-debug] [WARNING] Headers were already written. Wanted to override status code 400 with 500
> 2017/02/08 09:26:36 notifying bugsnag: websocket: could not find connection header with token 'upgrade'
> 2017/02/08 09:26:36 bugsnag.Notify: not notifying in development
> 
> 
> 2017/02/08 09:26:36 [Recovery] panic recovered:
> GET /api/ws HTTP/1.1
> Host: 127.0.0.1:3000
> Accept-Encoding: gzip, deflate, sdch, br
> Accept-Language: en-US,en;q=0.8,he;q=0.6,da;q=0.4
> Cache-Control: no-cache
> Connection: Keep-Alive
> Cookie: ajs_anonymous_id=%22d9c0902b-91d2-4418-98eb-a5c0c41f6c39%22; ajs_group_id=null; ajs_user_id=%22shahar.harap%40zooz.com%22; _ga=GA1.2.318759243.1485763309; semaphore=MTQ4NjU0NTE4Mnxtejh2dXY0QmpWeElZTnBoN0FLMGtaTV9ybUJqTXQ0aW9uVVRKZWpZTmlqcU5MSFF5WXNuczdtTlhhUU81SzhLenlXLTlsMDZSd1pmbVprLXB4SnNpNzQ9fHKBi4NVNuIbiwVXsAQNIMvLUeHSZ1KWhVtQW7b8H3_3
> Origin: https://semaphore.zooz.co
> Pragma: no-cache
> Proxy-Connection: Keep-Alive
> Sec-Websocket-Extensions: permessage-deflate; client_max_window_bits
> Sec-Websocket-Key: fQLVUhbqzVi3YdBpRx0HvQ==
> Sec-Websocket-Version: 13
> User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
> 
> 
> websocket: could not find connection header with token 'upgrade'
> /usr/local/go/src/runtime/panic.go:458 (0x42adc3)
> /Users/m/p/gospace/src/github.com/bugsnag/bugsnag-go/bugsnag.go:52 (0x50e003)
> /usr/local/go/src/runtime/asm_amd64.s:479 (0x4588ac)
> /usr/local/go/src/runtime/panic.go:458 (0x42adc3)
> /Users/m/p/gospace/src/github.com/ansible-semaphore/semaphore/api/sockets/handler.go:102 (0x4b940f)
> /Users/m/p/gospace/src/github.com/gin-gonic/gin/context.go:97 (0x51573a)
> /Users/m/p/gospace/src/github.com/gin-gonic/gin/logger.go:66 (0x524167)
> /Users/m/p/gospace/src/github.com/gin-gonic/gin/context.go:97 (0x51573a)
> /Users/m/p/gospace/src/github.com/ansible-semaphore/semaphore/cli/main.go:72 (0x4016e2)
> /Users/m/p/gospace/src/github.com/gin-gonic/gin/context.go:97 (0x51573a)
> /Users/m/p/gospace/src/github.com/gin-gonic/gin/recovery.go:45 (0x524ffa)
> /Users/m/p/gospace/src/github.com/gin-gonic/gin/context.go:97 (0x51573a)
> /Users/m/p/gospace/src/github.com/gin-gonic/gin/gin.go:284 (0x51b6be)
> /Users/m/p/gospace/src/github.com/gin-gonic/gin/gin.go:265 (0x51afa0)
> /usr/local/go/src/net/http/server.go:2202 (0x5e0c7d)
> /usr/local/go/src/net/http/server.go:1579 (0x5dd5e7)
> /usr/local/go/src/runtime/asm_amd64.s:2086 (0x45b3d1)
> 
> [GIN-debug] [WARNING] Headers were already written. Wanted to override status code 400 with 500

Semaphore 2.1.0

I'd like for your help on this.

Best

Nitzan

**Comment by nhproject** [comment]
I'm trying to add or modify template, I'm getting the following error on the log:

[GIN-debug] [WARNING] Headers were already written. Wanted to override status code 400 with 500
2017/02/08 09:26:36 notifying bugsnag: websocket: could not find connection header with token 'upgrade'
2017/02/08 09:26:36 bugsnag.Notify: not notifying in development

2017/02/08 09:26:36 [Recovery] panic recovered:
GET /api/ws HTTP/1.1
Host: 127.0.0.1:3000
Accept-Encoding: gzip, deflate, sdch, br
Accept-Language: en-US,en;q=0.8,he;q=0.6,da;q=0.4
Cache-Control: no-cache
Connection: Keep-Alive
Cookie: ...
Origin: ...
Pragma: no-cache
Proxy-Connection: Keep-Alive
Sec-Websocket-Extensions: permessage-deflate; client_max_window_bits
Sec-Websocket-Key: ...
Sec-Websocket-Version: 13
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

websocket: could not find connection header with token 'upgrade'
/usr/local/go/src/runtime/panic.go:458 (0x42adc3)
/Users/m/p/gospace/src/github.com/bugsnag/bugsnag-go/bugsnag.go:52 (0x50e003)
/usr/local/go/src/runtime/asm_amd64.s:479 (0x4588ac)
/usr/local/go/src/runtime/panic.go:458 (0x42adc3)
/Users/m/p/gospace/src/github.com/ansible-semaphore/semaphore/api/sockets/handler.go:102 (0x4b940f)
/Users/m/p/gospace/src/github.com/gin-gonic/gin/context.go:97 (0x51573a)
/Users/m/p/gospace/src/github.com/gin-gonic/gin/logger.go:66 (0x524167)
/Users/m/p/gospace/src/github.com/gin-gonic/gin/context.go:97 (0x51573a)
/Users/m/p/gospace/src/github.com/ansible-semaphore/semaphore/cli/main.go:72 (0x4016e2)
/Users/m/p/gospace/src/github.com/gin-gonic/gin/context.go:97 (0x51573a)
/Users/m/p/gospace/src/github.com/gin-gonic/gin/recovery.go:45 (0x524ffa)
/Users/m/p/gospace/src/github.com/gin-gonic/gin/context.go:97 (0x51573a)
/Users/m/p/gospace/src/github.com/gin-gonic/gin/gin.go:284 (0x51b6be)
/Users/m/p/gospace/src/github.com/gin-gonic/gin/gin.go:265 (0x51afa0)
/usr/local/go/src/net/http/server.go:2202 (0x5e0c7d)
/usr/local/go/src/net/http/server.go:1579 (0x5dd5e7)
/usr/local/go/src/runtime/asm_amd64.s:2086 (0x45b3d1)

[GIN-debug] [WARNING] Headers were already written. Wanted to override status code 400 with 500
Semaphore 2.1.0

I'd like for your help on this.

Best

Nitzan

**Comment by matejkramny** [comment]
@nhproject the error is not template related.

> websocket: could not find connection header with token 'upgrade'

semaphore uses websockets to push updates back to the browser. Can you open a new issue & paste this log incl the browser you're doing this on?

Thanks
