### ISSUE TITLE
task can't run and PLAY RECAP return null

### ISSUE THREAD

**Issue by godfery** [ansible-semaphore/semaphore#245]
Task Log
Status
success
User
root
Started
Ended
Created
Raw output

14:47:36: Started: 29

14:47:36: access key 134 installed
14:47:36: Updating repository https://github.com/godfery/lnmp.git
14:47:41: From https://github.com/godfery/lnmp
14:47:41:  * branch            master     -> FETCH_HEAD
14:47:41: Already up-to-date.
14:47:41: access key 134 installed
14:47:41: installing static inventory
14:47:42: /usr/lib64/python2.6/site-packages/cryptography/__init__.py:26: DeprecationWarning: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of cryptography will drop support for Python 2.6
14:47:42:   DeprecationWarning
14:47:42: Using /etc/ansible/ansible.cfg as config file
14:47:42: Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.6/site-packages/ansible/plugins/callback/__init__.pyc
14:47:42: 
14:47:42: PLAYBOOK: b.yml ****************************************************************
14:47:42: 1 plays in b.yml
14:47:42: 
14:47:42: PLAY RECAP *********************************************************************
14:47:42: 

  I don't know why?

**Comment by godfery** [comment]
Hei hi
     我解决了这个问题。 原因是我的inventory 配置错误。写成  hosts 文件形式可以了。例如
[cod]
192.168.100.251
192.168.3.134

**Comment by GoodHaHa** [comment]
@godfery 赤裸裸的 chinese

**Comment by godfery** [comment]
@GoodHaHa  我英语太差就不写了。
