### ISSUE TITLE
different result between cli and semaphore

### ISSUE THREAD

**Issue by liuyangc3** [ansible-semaphore/semaphore#246]
here is my playbook: https://github.com/nxintech/playbooks/blob/master/test.yml

it can not work in semaphore

run template:
![image](https://cloud.githubusercontent.com/assets/6705844/22173926/8c0a62a6-e00b-11e6-9112-601000803da4.png)

UI ouput : Host Unreachbale

![image](https://cloud.githubusercontent.com/assets/6705844/22173956/502242bc-e00c-11e6-8009-cc4493ecf64b.png)

but works in command line
![image](https://cloud.githubusercontent.com/assets/6705844/22173955/4413cf54-e00c-11e6-8fb5-a900f6660a53.png)

**Comment by twhiston** [comment]
cannot reproduce in current semaphore version
