### ISSUE TITLE
Problem: crypto/aes: invalid key size 64 error when adding SSH key

### ISSUE THREAD

**Issue by vybraan** [ansible-semaphore/semaphore#2465]
### Summary
When trying to add a new password key or SSH key in the Semaphore UI, it throws an Request failed with status code 400 error

### Impact

Web-Frontend (what users interact with), Web-Backend (APIs)

### Installation method

Docker

### Database

Postgres

### Browser

Firefox, Chrome

### Semaphore Version

v2.10.32-f33944e-1729509451

### Logs & errors

semaphore-1  | Server is running
semaphore-1  | time="2024-10-21T16:58:00Z" level=error msg="crypto/aes: invalid key size 64"
semaphore-1  | goroutine 13 [running]:
semaphore-1  | runtime/debug.Stack()
semaphore-1  |  /usr/local/go/src/runtime/debug/stack.go:24 +0x5e
semaphore-1  | runtime/debug.PrintStack()
semaphore-1  |  /usr/local/go/src/runtime/debug/stack.go:16 +0x13
semaphore-1  | github.com/ansible-semaphore/semaphore/api/helpers.WriteError({0x1957d60, 0xc000000c40}, {0x1953d00, 0x1dee2a0})
semaphore-1  |  /go/src/semaphore/api/helpers/helpers.go:122 +0x21b
semaphore-1  | github.com/ansible-semaphore/semaphore/api/projects.AddKey({0x1957d60, 0xc000000c40}, 0xc000269440)
semaphore-1  |  /go/src/semaphore/api/projects/keys.go:92 +0x5d4
semaphore-1  | net/http.HandlerFunc.ServeHTTP(0x70235f7755b8?, {0x1957d60?, 0xc000000c40?}, 0xc000269680?)
semaphore-1  |  /usr/local/go/src/net/http/server.go:2166 +0x29
semaphore-1  | github.com/ansible-semaphore/semaphore/api.Route.GetMustCanMiddleware.func4.1({0x1957d60, 0xc000000c40}, 0xc000269440)
semaphore-1  |  /go/src/semaphore/api/projects/project.go:59 +0x127
semaphore-1  | net/http.HandlerFunc.ServeHTTP(0xc000269440?, {0x1957d60?, 0xc000000c40?}, 0xc483c0?)
semaphore-1  |  /usr/local/go/src/net/http/server.go:2166 +0x29
semaphore-1  | github.com/ansible-semaphore/semaphore/api/projects.ProjectMiddleware.func1({0x1957d60, 0xc000000c40}, 0xc000269440)
semaphore-1  |  /go/src/semaphore/api/projects/project.go:43 +0x43d
semaphore-1  | net/http.HandlerFunc.ServeHTTP(0x1957d60?, {0x1957d60?, 0xc000000c40?}, 0x0?)
semaphore-1  |  /usr/local/go/src/net/http/server.go:2166 +0x29
semaphore-1  | github.com/ansible-semaphore/semaphore/api.authentication.func1({0x1957d60, 0xc000000c40}, 0xc000269440)
semaphore-1  |  /go/src/semaphore/api/auth.go:102 +0x57
semaphore-1  | net/http.HandlerFunc.ServeHTTP(0xc23920?, {0x1957d60?, 0xc000000c40?}, 0xc?)
semaphore-1  |  /usr/local/go/src/net/http/server.go:2166 +0x29
semaphore-1  | github.com/ansible-semaphore/semaphore/api.JSONMiddleware.func1({0x1957d60, 0xc000000c40}, 0xc000269440)
semaphore-1  |  /go/src/semaphore/api/router.go:45 +0xf6
semaphore-1  | net/http.HandlerFunc.ServeHTTP(0xb73400?, {0x1957d60?, 0xc000000c40?}, 0x78c4ec?)
semaphore-1  |  /usr/local/go/src/net/http/server.go:2166 +0x29
semaphore-1  | github.com/ansible-semaphore/semaphore/api.StoreMiddleware.func1.1()
semaphore-1  |  /go/src/semaphore/api/router.go:36 +0x28
semaphore-1  | github.com/ansible-semaphore/semaphore/db.StoreSession({0x1967560, 0xc000118728}, {0xc000379ba0, 0xc}, 0xc0001837d8)
semaphore-1  |  /go/src/semaphore/db/Store.go:463 +0x5f
semaphore-1  | github.com/ansible-semaphore/semaphore/api.StoreMiddleware.func1({0x1957d60, 0xc000000c40}, 0xc000269440)
semaphore-1  |  /go/src/semaphore/api/router.go:35 +0x126
semaphore-1  | net/http.HandlerFunc.ServeHTTP(0xc000269440?, {0x1957d60?, 0xc000000c40?}, 0xc2ede0?)
semaphore-1  |  /usr/local/go/src/net/http/server.go:2166 +0x29
semaphore-1  | github.com/ansible-semaphore/semaphore/cli/cmd.runService.func1.1({0x1957d60, 0xc000000c40}, 0xc000269440)
semaphore-1  |  /go/src/semaphore/cli/cmd/root.go:93 +0xea
semaphore-1  | net/http.HandlerFunc.ServeHTTP(0x0?, {0x1957d60?, 0xc000000c40?}, 0x411d65?)
semaphore-1  |  /usr/local/go/src/net/http/server.go:2166 +0x29
semaphore-1  | github.com/ansible-semaphore/semaphore/api.Route.CORSMethodMiddleware.func1.1({0x1957d60, 0xc000000c40}, 0xc000269440)
semaphore-1  |  /go/src/semaphore/vendor/github.com/gorilla/mux/middleware.go:51 +0x89
semaphore-1  | net/http.HandlerFunc.ServeHTTP(0xc000269320?, {0x1957d60?, 0xc000000c40?}, 0xc0001839b8?)
semaphore-1  |  /usr/local/go/src/net/http/server.go:2166 +0x29
semaphore-1  | github.com/gorilla/mux.(*Router).ServeHTTP(0xc00015a3c0, {0x1957d60, 0xc000000c40}, 0xc0002690e0)
semaphore-1  |  /go/src/semaphore/vendor/github.com/gorilla/mux/mux.go:212 +0x1e2
semaphore-1  | github.com/ansible-semaphore/semaphore/cli/cmd.runService.ProxyHeaders.func2({0x1957d60, 0xc000000c40}, 0xc0002690e0)
semaphore-1  |  /go/src/semaphore/vendor/github.com/gorilla/handlers/proxy_headers.go:59 +0x143
semaphore-1  | net/http.HandlerFunc.ServeHTTP(0xc00003ced5?, {0x1957d60?, 0xc000000c40?}, 0x702318c90338?)
semaphore-1  |  /usr/local/go/src/net/http/server.go:2166 +0x29
semaphore-1  | github.com/ansible-semaphore/semaphore/cli/cmd.runService.cropTrailingSlashMiddleware.func3({0x1957d60, 0xc000000c40}, 0xc0002690e0)
semaphore-1  |  /go/src/semaphore/cli/cmd/server.go:27 +0xbd
semaphore-1  | net/http.HandlerFunc.ServeHTTP(0x411d65?, {0x1957d60?, 0xc000000c40?}, 0xc000000c01?)
semaphore-1  |  /usr/local/go/src/net/http/server.go:2166 +0x29
semaphore-1  | net/http.serverHandler.ServeHTTP({0x19557e8?}, {0x1957d60?, 0xc000000c40?}, 0x6?)
semaphore-1  |  /usr/local/go/src/net/http/server.go:3137 +0x8e
semaphore-1  | net/http.(*conn).serve(0xc000477680, {0x1959c08, 0xc000094cc0})
semaphore-1  |  /usr/local/go/src/net/http/server.go:2039 +0x5e8
semaphore-1  | created by net/http.(*Server).Serve in goroutine 1
semaphore-1  |  /usr/local/go/src/net/http/server.go:3285 +0x4b4

**Comment by fiftin** [comment]
Looks like you provided incorrect `access_key_encryption`. https://docs.semaphoreui.com/administration-guide/security/#database-encryption. Need more info about your env variables and config file.

**Comment by vybraan** [comment]
Hi,

Thanks for pointing me in the right direction. After reviewing the documentation, I realized that a 32-bit key is required (```head -c 32 /dev/urandom | base64```), whereas I mistakenly used a 64-bit key (```openssl rand -base64 64```). I've corrected it, and everything is working as expected now.

Thanks for the help!
