### ISSUE TITLE
User and administrator manual

### ISSUE THREAD

**Issue by ly2ly** [ansible-semaphore/semaphore#248]
Hello,

Have you some manual and/or documentations about semaphore UI set up?

update
You can find et little user manual here 
https://code-complete.com/code/?p=40

**Comment by ly2ly** [comment]
Finally I finished to understand semaphore, congrats to the team, It is the best alternative to tower I find.
So, I make a little tutorial for my team (in french but I can translate it into english), if you want I can PR it in the wiki. 
Other thing, in semaphore, it will be interesting to categorize or put label on task, keys and playbooks. It can be a good enhancement I think.

**Comment by craftbyte** [comment]
@ly2ly can you create the label suggestion as an issue?

**Comment by ly2ly** [comment]
oki

**Comment by craftbyte** [comment]
also, if you can translate it to english, feel free to update the wiki

**Comment by keith4743** [comment]
great, useful guide.
