### ISSUE TITLE
Problem: big inventory suddenly fails with `Attempting to decrypt but no vault secrets found`

### ISSUE THREAD

**Issue by markush81** [ansible-semaphore/semaphore#2486]
### Issue

Running a playbook against big inventory, means > 60 hosts, in-between starts to fail, seems Ansible Vault decryption starts to not work anymore.

### Impact

Ansible (task execution)

### Installation method

Package

### Database

Postgres

### Browser

Safari

### Semaphore Version

2.10.32

### Ansible Version

```bash
ansible==10.4.0
```

### Logs & errors

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.errors.AnsibleError: An unhandled exception occurred while templating '...'. Error was a <class 'ansible.parsing.vault.AnsibleVaultError'>, original message: Attempting to decrypt but no vault secrets found
```

**Comment by fiftin** [comment]
Hi @markush81 
please check the Template. Do you see Vault in template settings?

**Comment by markush81** [comment]
> Hi @markush81 please check the Template. Do you see Vault in template settings?

maybe i wasn't detailed enough: it runs for several minutes well with a big inventory (and long run of several tasks), but after a while for a couple of hosts it starts to fail (so example number: 40 hosts out of 60 run green, 20 fail).

**Comment by markush81** [comment]
> > Hi @markush81 please check the Template. Do you see Vault in template settings?
> 
> maybe i wasn't detailed enough: it runs for several minutes well with a big inventory (and long run of several tasks), but after a while for a couple of hosts it starts to fail (so example number: 40 hosts out of 60 run green, 20 fail).

But today it worked twice ... hmm ... maybe some kind of hickup. I'll close ...
