### ISSUE TITLE
Error 1054: Unknown column 'dry_run' in 'field_list' - Trying to run a task

### ISSUE THREAD

**Issue by Mr-Chimp** [ansible-semaphore/semaphore#249]
I recently upgraded to version 2.1.0 using the built in upgrade and that all worked a treat. However now when I try and run any of my tasks in the interface I get the error "error launching task: HTTP 500" and in the logs:

Error 1054: Unknown column 'dry_run' in 'field list'

Any ideas on how to solve, these tasks were there before the migration.

**Comment by robertdebock** [comment]
Looks like a few columns are missing, relates to #243.

**Comment by lhorace** [comment]
In case if isn't clear, the solution is to re-run `semaphore -setup` which will update the databse. I'm not quite sure if this get's executed with `semaphore -update` (or -upgrade). I was a bit confused reading this.

**Comment by Mr-Chimp** [comment]
Thank you for clarifying @lhorace I just double checked and the problem has gone away since I did that thanks.
