### ISSUE TITLE
Question: How to change console font colors

### ISSUE THREAD

**Issue by robertwsaul** [ansible-semaphore/semaphore#2500]
### Question

When I run a job through semaphore that involves async polling, for whatever reasons the lines that report the async status are pure black, and invisible in the black background console. How do I change the color of the font or the color of the console background?

### Related to

Web-Frontend (what users interact with)

**Comment by fiftin** [comment]
Currently the colors are hard coded.

**Comment by fiftin** [comment]
@robertwsaul Cloud you share a screenshot?

**Comment by robertwsaul** [comment]
![sema](https://github.com/user-attachments/assets/707ab92b-c7bf-46ef-b18a-1b9a28310736)


> @robertwsaul Cloud you share a screenshot?

Screenshot attached, I think.

**Comment by Aric000** [comment]
yes，i met the same situation.

**Comment by EHEX-schildt** [comment]
You can use ansible.cfg in the repo to set color or env ANSIBLE_COLOR_DEBUG:
https://docs.ansible.com/ansible/latest/reference_appendices/config.html#color-debug

ASYNC use debug – to replace the default color "dark gray" with "white" add ansible.cfg to repo root:

ansible.cfg:
```ini
[colors]
debug = white
```
![semaphore_async_white](https://github.com/user-attachments/assets/3dbc6538-41a9-4de5-ae52-709fcb7e9ecd)

**Comment by robertwsaul** [comment]
That worked perfectly. Thank you! I didn't think the font settings would come through the semaphore console. Not sure why I thought that, but I was wrong.
