### ISSUE TITLE
Problem: mysql host running non default tcp-port is ignored (since v2.10.33)

### ISSUE THREAD

**Issue by strenker** [ansible-semaphore/semaphore#2502]
### Issue

I am using semaphore in a docker environment with an external MySQL-Server running on tcp-port 3307 (not MySQL default-Port 3306).

My docker-compose.yaml is set up with:

` SEMAPHORE_DB_HOST: <fqdn>`
` SEMAPHORE_DB_PORT: 3307`

The resulting semaphore config json shows:

`"mysql": {
    "host": "<fqdn>:3307",
    "user": "<user>",
    "pass": "<password>",
    "name": "<dbname>",
    "options": null
},` 

Since version v2.10.33 the external MySQL-Server is no longer accessible. The docker log shows:

`semaphore  | panic: dial tcp 192.168.17.21:3306: connect: connection refused
`

The DNS resolved IP-address is correct, but the non-default tcp-port for the MySQL-Server is ignored.

This worked perfectly up to semaphore version v2.10.32. 

### Impact

Database

### Installation method

Docker

### Database

MySQL

### Browser

Firefox

### Semaphore Version

v2.10.33

### Logs & errors

[+] Running 1/1
 ✔ semaphore Pulled                                                                               1.4s 
[+] Running 1/1
 ✔ Container semaphore  Recreated                                                                 0.2s 
Attaching to semaphore
semaphore  | Pinging database on <fqdn> port **3307**...
semaphore  | No additional python dependencies to install
semaphore  | Starting semaphore server
semaphore  | Loading config
semaphore  | Validating config
semaphore  | time="2024-10-26T11:25:16Z" level=warning msg="dial tcp 192.168.17.21:**3306**: connect: connection refused"
semaphore  | panic: dial tcp 192.168.17.21:**3306**: connect: connection refused
semaphore  | 
semaphore  | goroutine 1 [running]:
semaphore  | github.com/ansible-semaphore/semaphore/db/sql.(*SqlDb).Connect(0x4000064730, {0x1a?, 0x0?})
semaphore  |    /go/src/semaphore/db/sql/SqlDb.go:299 +0x770
semaphore  | github.com/ansible-semaphore/semaphore/cli/cmd.createStore({0x7f3cec, 0x4})
semaphore  |    /go/src/semaphore/cli/cmd/root.go:122 +0x64
semaphore  | github.com/ansible-semaphore/semaphore/cli/cmd.runService()
semaphore  |    /go/src/semaphore/cli/cmd/root.go:63 +0x3c
semaphore  | github.com/ansible-semaphore/semaphore/cli/cmd.init.func9(0x400018f000?, {0x7f3d20?, 0x4?, 0x7f3d24?})
semaphore  |    /go/src/semaphore/cli/cmd/server.go:18 +0x1c
semaphore  | github.com/spf13/cobra.(*Command).execute(0x198e680, {0x400004dd60, 0x2, 0x2})
semaphore  |    /go/src/semaphore/vendor/github.com/spf13/cobra/command.go:989 +0x828
semaphore  | github.com/spf13/cobra.(*Command).ExecuteC(0x198d540)
semaphore  |    /go/src/semaphore/vendor/github.com/spf13/cobra/command.go:1117 +0x344
semaphore  | github.com/spf13/cobra.(*Command).Execute(...)
semaphore  |    /go/src/semaphore/vendor/github.com/spf13/cobra/command.go:1041
semaphore  | github.com/ansible-semaphore/semaphore/cli/cmd.Execute()
semaphore  |    /go/src/semaphore/cli/cmd/root.go:56 +0xd0
semaphore  | main.main()
semaphore  |    /go/src/semaphore/cli/main.go:8 +0x1c
semaphore exited with code 0

### Manual installation - system information

Synology NAS provided reverse proxy

**Comment by fiftin** [comment]
Fixed in v2.10.34.

**Comment by strenker** [comment]
Fix in v2.10.34 confirmed.
Many thanks for so quickly solving this issue!
