### ISSUE TITLE
semaphore's io site down

### ISSUE THREAD

**Issue by rgarrigue** [ansible-semaphore/semaphore#251]
Hi

Accessing https://ansible-semaphore.github.io/semaphore I got a `Can't read from server. It may not have the appropriate access-control-origin settings.`

Regards,

**Comment by matejkramny** [comment]
@rgarrigue is it not working for a particular browser?

**Comment by rgarrigue** [comment]
My bad, uMatrix locked some stuff. But is this normal to end up on swagger ?

**Comment by matejkramny** [comment]
Yeah github hosts API documentation for the project
