### ISSUE TITLE
While adding a new ssh key to key store got "Request failed with status code 400" in modal window "New Key".

### ISSUE THREAD

**Issue by tomshomelab** [ansible-semaphore/semaphore#2510]
While adding a new ssh key to key store got "Request failed with status code 400" in modal window "New Key".

Semaphore version: v2.9.64
docker image: semaphoreui/semaphore:latest (c0068bfcb298)
use both nginx proxy and direct on :3000 port

Key name: k1
Type: SSH Key
Private key: tried both ed25519 and RSA

_Originally posted by @mcgru in https://github.com/semaphoreui/semaphore/discussions/2012_

**Comment by tomshomelab** [comment]
sorry im not sure how ive managed to make a new issue here. i was trying to create a link to use for an issue ive made manually  https://github.com/semaphoreui/semaphore/issues/2509

**Comment by fiftin** [comment]
Hi @tomshomelab 
Latest version of semaphore is 2.10.35.
