### ISSUE TITLE
Question: configurator issues

### ISSUE THREAD

**Issue by lgwapnitsky** [ansible-semaphore/semaphore#2512]
### Question

Is the docker configurator supposed to dynamically update? I've tried in multiple browsers, but only the original configuration appears to be copy-pasteable

### Related to

Configuration

**Comment by jershbytes** [comment]
I'm glad someone post this here as well. I've tried on Firefox, Chrome and Edge.
Nothing Dynamically updates. 

```
Uncaught ReferenceError: refreshDockerCommand is not defined
    at HTMLInputElement.<anonymous> (2_10_32/:1184:25)
```

Looking at web console log im seeing this so something tells me the function is getting missed somewhere.

**Comment by fiftin** [comment]
Fixed.
