### ISSUE TITLE
Problem: issue with key decryption after restarting docker containers

### ISSUE THREAD

**Issue by jg1000c** [ansible-semaphore/semaphore#2513]
### Issue

Hi, I'm getting this error after every docker container restart. I'm able to edit the keys and copy over the info and it fixes the issue but only until next reboot. 

Failed to install inventory: cannot decrypt access key, perhaps encryption key was changed
4:52:20 PM
Running app failed: cannot decrypt access key, perhaps encryption key was changed

### Impact

Ansible (task execution)

### Installation method

Docker

### Database

MySQL

### Semaphore Version

v2.10.22

### Ansible Version

```bash
2.16.9
```

### Manual installation - system information

traefik

**Comment by fiftin** [comment]
Hi @jg1000c do you mean restarting or recreating?

**Comment by jg1000c** [comment]
Hi, I mean the next time I run docker compose down and docker compose up -d. I'll have to go and override and fix the ssh keys. I also tried with latest .32 version and have same issue. 
<img width="965" alt="Screenshot 2024-10-30 at 5 27 55 PM" src="https://github.com/user-attachments/assets/4bcbd5ca-4c1f-45ac-9572-b483a872062c">

**Comment by fiftin** [comment]
@jg1000c https://github.com/semaphoreui/semaphore/issues/2261#issuecomment-2439985783

`docker compose down` kills container. So you need to store you config in volume or use environment variable `SEMAPHORE_ACCESS_KEY_ENCRYPTION`.

**Comment by jg1000c** [comment]
This is what I have now: 
 volumes:
      - ./playbooks:/semaphore_playbooks

Should I update to this to fix the issue?

volumes:
      - semaphore_data:/var/lib/semaphore
      - semaphore_config:/etc/semaphore

Also, thanks for your help. It is a great tool.

**Comment by jg1000c** [comment]
I just tested and adding the semaphore_config volume worked. Thanks for your help.
