### ISSUE TITLE
Synchronize module can't find rsync executable

### ISSUE THREAD

**Issue by kpashka** [ansible-semaphore/semaphore#255]
I'm using Ubuntu 16.04, Ansible 2.2.1.0, both hosts have `rsync` installed (in `/usr/local/bin`), 100% sure. One of the playbooks has `synchronize` module, and, for some reason, Semaphore can't find the executable:

```
21:44:13: fatal: [10.240.0.3]: FAILED! => {
21:44:13:     "changed": false, 
21:44:13:     "failed": true, 
21:44:13:     "invocation": {
21:44:13:         "module_args": {
21:44:13:             "_local_rsync_path": "rsync", 
21:44:13:             "_substitute_controller": false, 
21:44:13:             "archive": true, 
21:44:13:             "checksum": false, 
21:44:13:             "compress": true, 
21:44:13:             "copy_links": null, 
21:44:13:             "delete": true, 
21:44:13:             "dest": "10.240.0.3:/***", 
21:44:13:             "dest_port": null, 
21:44:13:             "dirs": false, 
21:44:13:             "existing_only": false, 
21:44:13:             "group": null, 
21:44:13:             "links": null, 
21:44:13:             "mode": "push", 
21:44:13:             "owner": null, 
21:44:13:             "partial": false, 
21:44:13:             "perms": null, 
21:44:13:             "private_key": "/tmp/semaphore/access_key_1", 
21:44:13:             "recursive": true, 
21:44:13:             "rsync_opts": null, 
21:44:13:             "rsync_path": "\"sudo rsync\"", 
21:44:13:             "rsync_timeout": 0, 
21:44:13:             "set_remote_user": true, 
21:44:13:             "src": "/tmp/semaphore/repository_1/***/***", 
21:44:13:             "ssh_args": null, 
21:44:13:             "times": null, 
21:44:13:             "verify_host": false
21:44:13:         }
21:44:13:     }, 
21:44:13:     "msg": "Failed to find required executable rsync"
21:44:13: }
```

**Comment by matejkramny** [comment]
Interesting, could you try running this w/o semaphore to rule it out?

It might be the setup of the box ansible is ran on or a permission issue perhaps.

**Comment by kpashka** [comment]
@matejkramny I was also running Semaphore locally on my Mac, had exactly the same issue. This specific playbook was working smoothly for like decades, but under semaphore something got wrong. Gonna try to debug it deeper today

**Comment by matejkramny** [comment]
I have a feeling it might be related to the `$PATH` variable which:

- Go infers $PATH from it's environment
- Ansible infers $PATH from go executing `ansible-playbook` (using  according to https://godoc.org/os/exec#LookPath)

**Comment by kpashka** [comment]
@matejkramny Don't see anything suspicious here:

```
➜ whereis rsync
/usr/bin/rsync
➜ echo $GOPATH
/Users/ejik/golang
➜ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/MacGPG2/bin:/Users/ejik/golang/bin
```

**Comment by kpashka** [comment]
@matejkramny Ok, you were correct, it worked, when I've passed `PATH` explicitly to task runner [here](https://github.com/ansible-semaphore/semaphore/blob/master/api/tasks/runner.go#L327):

```
	cmd.Env = []string{
		"HOME=" + util.Config.TmpPath,
		"PWD=" + cmd.Dir,
		"PYTHONUNBUFFERED=1",
		"PATH=" + os.Getenv("PATH"), // <- this
		// "GIT_FLUSH=1",
	}
```

But the solution itself is kinda clunky. Is there any better way to pass the real `PATH` to Semaphore, that will be cascaded to Ansible?

**Comment by kpashka** [comment]
@matejkramny Nevermind, found some best practices across the internet. Made a PR #256

**Comment by matejkramny** [comment]
so basically it's due to semaphore providing a clean environment to ansible

**Comment by kpashka** [comment]
@matejkramny Yep, and it's fixed now. Thanks for merging my PR!

**Comment by Kikyo-chan** [comment]
################no rsync Resulting problems#####################

which rsync
/usr/bin/which: no rsync in (/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin)

#yum install rsync -y
# which rsync      
/usr/bin/rsync

ok!
