### ISSUE TITLE
Problem: Cannot restore project frombac

### ISSUE THREAD

**Issue by thinhnggia** [ansible-semaphore/semaphore#2591]
### Issue

Hi,
I am currently using Semaphore with Docker. I successfully backup the project, but cannot restore the project from the backup file using the latest Docker image version. But then I tried to rollback to version v2.10.35, it still works.

For docker compose configuration, I follow this guide: https://docs.semaphoreui.com/administration-guide/installation/#docker

### Impact

Web-Frontend (what users interact with), Web-Backend (APIs), Docker

### Installation method

Docker

### Database

MySQL

### Browser

Chrome

### Semaphore Version

v2.10.43

### Logs & errors

![image](https://github.com/user-attachments/assets/3048d640-147b-47e4-a3e0-dc5e31b3669e)

**Comment by tungduync** [comment]
I also got the same error

**Comment by Studhey** [comment]
same here

**Comment by AlumnusDK** [comment]
Same here

**Comment by WilliamB78** [comment]
Hello, i found a typo in the url used by the vue component to call the api to restore the backup, hence the error 404 !

Pr is here : https://github.com/semaphoreui/semaphore/pull/2605

**Comment by fiftin** [comment]
@WilliamB78 thanks a lot!
