### ISSUE TITLE
Problem: Cannot run collection playbook

### ISSUE THREAD

**Issue by bbaassssiiee** [ansible-semaphore/semaphore#2593]
### Issue

I'd like to use SemaphoreUI as a self-service portal where users can deploy their k8s clusters on infrastructure provided to them. kubernetes_sigs.kubespray is a collection that has playbooks to manage Kubernetes clusters. The problems I have are that SemaphoreUI cannot install collections from GitHub (but I installed these as the semaphore user that runs ansible), but still Semaphore doesn't allow the use of `ansible.builtin.import_playbook` with collection playbooks.

Note: the playbook to install Kubernetes works from the command-line, but not from Semaphore.

Kubespray documentation: [https://kubespray.io/#/docs/ansible/ansible_collection?id=ansible-collection](https://kubespray.io/#/docs/ansible/ansible_collection?id=ansible-collection)

### Impact

Ansible (task execution)

### Installation method

Binary

### Database

Postgres

### Browser

Firefox

### Semaphore Version

2.10.43-e43af6b-1732277822

### Ansible Version

```bash
ansible [core 2.16.3]
  config file = /home/semaphore/ansible.cfg
  configured module search path = ['/home/semaphore/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.12/site-packages/ansible
  ansible collection location = /home/semaphore/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.12.6 (main, Nov  4 2024, 21:05:37) [GCC 8.5.0 20210514 (Red Hat 8.5.0-22)] (/usr/bin/python3.12)
  jinja version = 3.1.2
  libyaml = True

$ ansible-galaxy collection list

# /home/semaphore/.ansible/collections/ansible_collections
Collection                               Version
---------------------------------------- -------
ansible.netcommon                        7.1.0
ansible.posix                            1.6.2
ansible.utils                            5.1.2
community.crypto                         2.22.3
community.docker                         4.1.0
community.general                        10.0.1
community.library_inventory_filtering_v1 1.0.2
community.postgresql                     3.8.0
kubernetes.core                          5.0.0
kubernetes_sigs.kubespray                2.27.0
```

### Logs & errors

Installing 'kubernetes_sigs.kubespray:2.26.0' to '/home/semaphore/tmp/.ansible/collections/ansible_collections/kubernetes_sigs/kubespray'
9:00:13 AM
ERROR! Use of "manifest" requires the python "distlib" library

![image](https://github.com/user-attachments/assets/b59416e5-549c-4d57-930c-fd8d468b9798)

### Manual installation - system information

Linux myhost 4.18.0-553.22.1.el8_10.x86_64 #1 SMP Tue Sep 24 05:16:59 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux

Nginx is the reverse proxy.

### Configuration

Reproducing Semaphore installation: [https://github.com/playingfield/controller](https://github.com/playingfield/controller)
Project to install Kubernetes: [https://github.com/playingfield/clusterlust](https://github.com/playingfield/clusterlust)

**Comment by fiftin** [comment]
Hi,
how your Ansible installed? Looks like Semaphore uses different environment where distlib not installed. This is a common problem when packages are installed into user environment (I mean flag `--user`) and the Semaphore does not see them.

I recommend to use Semaphore UI with VENV.

**Comment by bbaassssiiee** [comment]
I've installed the ansible-core RPM and distlib indeed with --user

**Comment by fiftin** [comment]
`--user` option currently not recommended to use in Ubuntu. I don't know how about other distributions. There are 2 alternatives:
* Install python3 deps with using apt or dnf (`python3-distlib`). 
* Create venv with using `python3 -m venv myvenv`, install ansible to it and use it with Semaphore:
   ```bash
   source /path/to/myvenv/bin/activate
   semaphore server --config config.json
   ```

**Comment by bbaassssiiee** [comment]
If the `--user` option is not recommended, then why is it the first one mentioned in the docs?
https://github.com/semaphoreui/semaphore-docs/blob/72a08bd296b123e1ed00fb4fcbda6686d3130656/src/administration-guide/installation_manually.md?plain=1#L74

**Comment by bbaassssiiee** [comment]
From the docs I missed this: https://github.com/semaphoreui/semaphore-docs/blob/main/src/administration-guide/installation_manually.md#in-user-context

I still need to test with both options, and will report findings here...

**Comment by fiftin** [comment]
Hi @bbaassssiiee thank you

**Comment by bbaassssiiee** [comment]
These lines are missing in the [full example](https://github.com/semaphoreui/semaphore-docs/blob/main/src/administration-guide/installation_manually.md#python-modules-in-user-context):

```
# set the correct python path. You can get the correct path with: python3 -c "import site; print(site.USER_SITE)" 
Environment="PYTHONPATH=/home/semaphore/.local/lib/python3.10/site-packages"
```

**Comment by bbaassssiiee** [comment]
@fiftin thanks for suggesting a VENV. On RHEL8-like systems it's sensible to use ansible-core as RPM, but that lacks the required `distlib` library. Installing it as root (not nice in itself) will have it in /usr/local/lib and that is not found while running ansible-galaxy.
