### ISSUE TITLE
Allow rearrage of lists in UI (Task Templates, Inventory, etc)

### ISSUE THREAD

**Issue by strangeman** [ansible-semaphore/semaphore#260]
This would be useful in big projects.

**Comment by ericlakich** [comment]
+1

**Comment by laeshiny** [comment]
@ericlakich Your idea is great.

I don't know which keywords are needed to rearrange more exactly.
Why don't we handle this issue like below?

1. Add "order by alias (or name)" to each query that gets item list as you commented above
2. After that, if many people need to rearrange the list by an another keyword, let's add some parameters like "sort" or "order" to the each api that gets item list later.

**Comment by laeshiny** [comment]
I implement that add sort, order parameters to below apis.
- /project/id/(templates, inventory, environment, keys, repositories, users
PR : https://github.com/ansible-semaphore/semaphore/pull/298
