### ISSUE TITLE
Add Task Template ID to UI

### ISSUE THREAD

**Issue by strangeman** [ansible-semaphore/semaphore#261]
Currently, if we need to launch task via API (from CI system, for example), we can look Project ID from UI (from URL of opened project), but we cannot look Task Template ID anywhere. I suggest adding non-editable field to the Update Template form.

**Comment by strangeman** [comment]
Also would be useful to highlight mandatory fields to the same dialog. Semaphore returns 500 error if they are empty.

Mandatory fields:
- SSH Key￼
- Inventory￼
- Playbook Repository￼

Not mandatory fields:
- Playbook Alias￼
- Playbook Name￼
- Environment￼
- Extra CLI Arguments

**Comment by strangeman** [comment]
![2017-02-12-123742_1366x768_scrot](https://cloud.githubusercontent.com/assets/1083576/22859205/26b07fb4-f120-11e6-8225-4ff9494823c4.png)

**Comment by matejkramny** [comment]
Closed w/ #262
