### ISSUE TITLE
How can I add a comment to the task run?

### ISSUE THREAD

**Issue by strangeman** [ansible-semaphore/semaphore#263]
It will be useful when project used by many users - additional information why the task was launched will make the process much clearer.
Can I use "Environment Override" field? Will it be shown somewhere in task log? Or may be better add additional "Comment" field in "Create Task" dialog (and API endpoint)?

**Comment by matejkramny** [comment]
It's not very good to use the environment override field because it's going to override the environment set for the template.

There may be room for "comments" but it's a fairly significant feature to add

**Comment by fiftin** [comment]
Done
