### ISSUE TITLE
The ansible debug module can't use in semaphore

### ISSUE THREAD

**Issue by ssrshz** [ansible-semaphore/semaphore#266]
When debug module is  written in playbook,but it can't execute  and display in task log.

for example：

14:31:05: PLAY [vien info] ***************************************************************
14:31:05: 
14:31:05: TASK [netstat] *****************************************************************
14:31:05: task path: /etc/semaphore/repository_1/test3.yml:6

**Comment by strangeman** [comment]
Strange, working for me:
```
11:58:38: TASK [cloudflare : debug] ******************************************************
11:58:38: Friday 17 February 2017  11:58:38 +1000 (0:00:00.030)       0:02:54.021 ******* 
11:58:38: ok: [test8.example.com] => {
11:58:38:     "msg": "Is public True"
11:58:38: }
```

Can you show your playbook with debug statement? Maybe you're specified `verbosity` option?

**Comment by ssrshz** [comment]
if I use ‘register’,the debug module can't work well.
 <code>
 tasks:
  - shell: hostname
    register: ps
  - debug:
      var: ps
      verbosity: 0
</code>

**Comment by strangeman** [comment]
Worked for me with your playbook:

test_local.yml
```
---
- hosts: localhost
  name: localhost test
  tasks:
   - shell: hostname
     register: ps
   - debug:
       var: ps
       verbosity: 0
```

Task template:
![2017-02-17-171226_1366x768_scrot](https://cloud.githubusercontent.com/assets/1083576/23055936/7083e816-f534-11e6-8d00-583223a76d9a.png)

Task log:
![2017-02-17-171256_1366x768_scrot](https://cloud.githubusercontent.com/assets/1083576/23055941/7a825118-f534-11e6-9e83-884ce4ba13a9.png)

Can you show your entire playbook, task template and run log?

**Comment by ssrshz** [comment]
My playbook:
```---
- name: test info
  hosts: ups_ftp
  remote_user: tlkjadmin
  gather_facts: false
  tasks:
   - shell: hostname
     register: ps
   - debug:
       var: ps
       verbosity: 0
```
My task log:
```
15:42:19:  * branch            master     -> FETCH_HEAD
15:42:19:    d28cfc4..c5d895b  master     -> origin/master
15:42:19: Updating d28cfc4..c5d895b
15:42:19: Fast-forward
15:42:19:  test5.yml | 2 +-
15:42:19:  1 file changed, 1 insertion(+), 1 deletion(-)
15:42:19: access key ansible installed
15:42:19: installing static inventory
15:42:20: 
15:42:20: PLAY [test info] ***************************************************************
15:42:20: 
15:42:20: TASK [command] *****************************************************************
```
so what can I do?

but when i use this playbook,**no shell module**,it's fine:
```
---
- name: test info
  hosts: ups_ftp
  remote_user: tlkjadmin
  gather_facts: false
  tasks:
   - debug:
       var: ps
       verbosity: 0
```
strange!

**Comment by strangeman** [comment]
What about 'vanilla' ansible, launched from a command line, like `ansible-playbook blahblahblah`? It worked correctly? Try to increase verbosity to `-vvv`  or `-vvvv`.

**Comment by ssrshz** [comment]
Thanks,I deploy again ,not in docker,it's ok now. It seems can't work in docker.
