### ISSUE TITLE
BUG: Ansible CLI Args can't handle any double-hyphen flags like --skip-tags or --vault-password-file

### ISSUE THREAD

**Issue by CryptoFewka** [ansible-semaphore/semaphore#2664]
Odd behavior discovered today: 
This works: `-l groupName`
This fails: `--limit groupName`

The error message received is: `ERROR! the playbook: --limit groupName could not be found`

It seems that the template's CLI args field cannot handle `--limit`, though `-limit` and `-l` both work.

_Originally posted by @CryptoFewka in https://github.com/semaphoreui/semaphore/issues/2367#issuecomment-2563171156_

**Comment by CryptoFewka** [comment]
This blocks things like --skip-tags, which do not have an abbreviated version.

**Comment by fiftin** [comment]
Hi @CryptoFewka It is not transparent but you should use 2 args for this not one. 

![image](https://github.com/user-attachments/assets/0bb4427f-2800-46a9-91b1-d48e79727cbe)
