### ISSUE TITLE
Problem: can't run docker compose anymore

### ISSUE THREAD

**Issue by 00shorty** [ansible-semaphore/semaphore#2665]
### Issue

Hi,

I'm not longer able to run my docker-compose.yml. It's still complaining about:

> ERROR: The Compose file './docker-compose.yml' is invalid because:
> services.mysql.environment.MYSQL_RANDOM_ROOT_PASSWORD contains true, which is an invalid type, it should be a string, number, or a null
> services.semaphore.environment.SEMAPHORE_LDAP_ENABLE contains true, which is an invalid type, it should be a string, number, or a null

**Ubuntu**: 24.04.1 LTS
**Docker**:  27.4.1-1
**Docker-compose**: 29.2-6

I tried to set the values into quotation marks, without any luck. Only when I uncomment the entries it will work. 
It was working before and I only stopped the container due to the new version that I'ld like to install.

Regards,
_shorty

### Impact

Docker

### Installation method

Docker

### Database

MySQL

### Semaphore Version

latest docker container, also tried versions before still the same.

### Configuration

> services:
    mysql:
        image: mysql:8
        environment:
            MYSQL_USER: semaphore
            MYSQL_PASSWORD: safepa$$word!
            MYSQL_DATABASE: semaphore_db
            MYSQL_RANDOM_ROOT_PASSWORD: yes
        volumes:
            - semaphore_mysql:/var/lib/mysql
        networks:
            - semaphore_network
    semaphore:
        ports:
            - 80:3000
        image: semaphoreui/semaphore:latest
        environment:
            SEMAPHORE_DB_DIALECT: mysql
            SEMAPHORE_DB_HOST: mysql
            SEMAPHORE_DB_NAME: semaphore_db
            SEMAPHORE_DB_USER: semaphore
            SEMAPHORE_DB_PASS: safepa$$word!
            SEMAPHORE_ADMIN: ansible-user
            SEMAPHORE_ADMIN_PASSWORD: Pa$$w0rd!
            SEMAPHORE_ADMIN_NAME: Administrator
            SEMAPHORE_ADMIN_EMAIL: email@domain.local
            SEMAPHORE_LDAP_ENABLE: True
            SEMAPHORE_LDAP_BIND_DN: CN=Technical User 0040,OU=Service Accounts,OU=IT,DC=domain,DC=local
            SEMAPHORE_LDAP_BIND_PASSWORD: Itsmeasa4epa$$word!
            SEMAPHORE_LDAP_SERVER: DC.domain.local:636
            SEMAPHORE_LDAP_SEARCH_DN: OU=User,DC=domain,DC=local
            SEMAPHORE_LDAP_SEARCH_FILTER: (&(userPrincipalName=%s)(memberOf=CN=Semaphore_admin,OU=Semaphore,OU=Permissions,DC=domain,DC=local))
            SEMAPHORE_LDAP_NEEDTLS: yes
            SEMAPHORE_LDAP_MAPPING_DN: dn
            SEMAPHORE_LDAP_MAPPING_MAIL: userPrincipalName
            SEMAPHORE_LDAP_MAPPING_UID: userPrincipalName
            SEMAPHORE_LDAP_MAPPING_CN: cn
        volumes:
            - semaphore_data:/var/lib/semaphore
            - semaphore_config:/etc/semaphore
            - semaphore_tmp:/tmp/semaphore
        networks:
            - semaphore_network
volumes:
    semaphore_data:
    semaphore_config:
    semaphore_tmp:
    semaphore_mysql:
networks:
    semaphore_network: {driver: "bridge"}

**Comment by fiftin** [comment]
It is Docker compose issue, not Semaphore issue.
