### ISSUE TITLE
Build fails because of API breaking of google/go-github

### ISSUE THREAD

**Issue by nightvisi0n** [ansible-semaphore/semaphore#267]
Currently the build of semaphore fails with the following error: 

```
--> linux/amd64 error: exit status 2                                                                                   
Stderr: # github.com/ansible-semaphore/semaphore/util                                                                  
../util/upgrade.go:99: not enough arguments in call to gh.Repositories.ListReleases
```

This is because the used go lib `google/go-github` broke their API with a recent commit to master:  
https://github.com/google/go-github/commit/23d6cb9cacb5aa314e93d600fe20a48496a718d4

**Comment by nightvisi0n** [comment]
https://github.com/google/go-github/issues/526

**Comment by nightvisi0n** [comment]
@matejkramny I'm working on a PR fixing this partly..

**Comment by matejkramny** [comment]
Ok 👍 

A more permanent solution is using a system like [glide](https://github.com/Masterminds/glide)

**Comment by nightvisi0n** [comment]
Yeah that seems to be a good long-term solution :slightly_smiling_face:

**Comment by matejkramny** [comment]
I'm happy to accept PR for either
