### ISSUE TITLE
Need email alerts about failed tasks

### ISSUE THREAD

**Issue by strangeman** [ansible-semaphore/semaphore#269]
Hello! I want to get email alerts about failed tasks. Currently, there is no way (except API and Web UI) to get informed about it. 

I created simple code for this - https://github.com/strangeman/semaphore/commit/31599e01de606b9cfa3826b1add4ba7deb7b2eb8, can you suggest, what else should I add? As I see, I should fix setup procedure (provide reasonable default parameters), add setting for enable/disable alerting for the particular user, maybe something else?

**Comment by matejkramny** [comment]
I would suggest:

- `EmailPort` to be `int`
- using `html/template` for the message body (and subject maybe)
- abstracting the mail functions to the `util` package (will come handy if we later want other email notifications)

As you mentioned already:

- Setting to notify user per project
- Setting to notify user in global user configuration
- On/off in settings

Good job 👍
