### ISSUE TITLE
Support for SSH CA certificates

### ISSUE THREAD

**Issue by templed** [ansible-semaphore/semaphore#271]
Hello,

(First I'm sorry for making that PR earlier, my GitHub skills are not great).

I use SSH keys which have been signed by a certificate authority as a means of authorization and authentication for the machines I connect to. I am interested in using Semaphore to manage certain Ansible tasks but I do not wish to use a "standard" SSH key for connecting to my machines.

To this end I have made a patch for Semaphore that supports the SSH certificate logic. Essentially the SSH certificate is the private key file and its public key (with the filename ending in '-cert.pub') that contains a signature from the CA. OpenSSH will implicitly look for the certificate key so all that Semaphore needed to do was write the SSH key to the correct position and have the controllers for the frontend handle SSH keys and SSH certficiates simultaneously where appropriate.

The patch is at [https://github.com/commodityvectors/semaphore/tree/sshcert](url). Neither my Go nor my Javascript are that good so I'm anticipating some comments about how to improve what I've written.

**Comment by matejkramny** [comment]
FWIW, not too bad. If you want some sort of a review, I can annotate the PR.

From the code I'm guessing that git/ssh doesn't need any special parameters passed to them to use ssh certificates.
In theory if semaphore wrote the public key as it does [here](https://github.com/ansible-semaphore/semaphore/pull/270/files#diff-9e9248d31849b68e7211d68a85aa096aR225), it would work, right?

**Comment by templed** [comment]
When you pass an identity file to SSH (with, say, name 'foo') it will check for the existence of the certified public key called (called 'foo-cert.pub'). 

The line you linked is essentially all that is needed to get the backend to handle the certificate. Most of the rest of the code I wrote is to avoid completely copying the logic that exists for standard SSH keys since all the logic for those keys are still required for certificates.

I just did a quick test with both the SSH agent, and the SSH client which indicates that SSH silently (until debug1 level of verbosity) ignores the fact that the public key may be malformed, in my case it was a standard public key without any CA signature so it *appears* to be safe to not have a separate type and just always write the public key with the '-cert.pub' suffix. This would definitely tidy up the code I wrote if it works as expected.

I'll give this a test in Semaphore when I get home tonight.

**Comment by templed** [comment]
I've tested using Semaphore where the public key either doesn't exist, or is not signed by a CA and it works without any problems.

The (significantly smaller) patch is available [here](https://github.com/commodityvectors/semaphore/commit/fd38eb55a1f0e9ae57ee9b2ab529c56a3f31fbc5).

**Comment by matejkramny** [comment]
Looks much cleaner. Good job.

I'm happy to accept a PR for this as-is. The wording on the UI might need to be changed later since the public key now serves another purpose

**Comment by gitwittidbit** [comment]
So, does this work now? 

Because I have been trying to use a signed key but can't get this to work. Any hints please?
