### ISSUE TITLE
Project roadmap

### ISSUE THREAD

**Issue by mcassaniti** [ansible-semaphore/semaphore#273]
Can a project roadmap please be published? This might simply link to the milestones section of GitHub, but it would still be appreciated.

**Comment by CN-Sean** [comment]
+1

**Comment by Koxx3** [comment]
+1

**Comment by 4stackdev** [comment]
+1

**Comment by linsheng9731** [comment]
+1

**Comment by matejkramny** [comment]
I follow what the community wants and try to implement those as soon as I can. There has been huge help recently from @laeshiny, @strangeman and others (thanks!).

Shortly to follow (< 24hrs) is a release implementing this [long list of commits](https://github.com/ansible-semaphore/semaphore/compare/80a3402...master).

The release after that will likely have breaking changes which may need changes in the way semaphore is run.

Roadmap now in: #325

**Comment by matejkramny** [comment]
If you want to talk / suggest ideas / point the project in a specific direction, we have a discord channel open to everyone.

**Comment by mcassaniti** [comment]
Thank you very much. I've added a link on the wiki home page to the roadmap. I'll leave it to you to update the README.
