### ISSUE TITLE
Environment forms

### ISSUE THREAD

**Issue by mcassaniti** [ansible-semaphore/semaphore#274]
I'm proposing an enhancement to provide the necessary extra environment details via a form the user can fill when they run a task from a task template. Ideally the form would allow for drop-down lists, multi select lists and free text boxes. The contents of any lists would be populated when creating the form template, but it may also be ideal to single or multi-select on a form based on the inventory associated with the task.

Does this sound like a feature wanted by the semaphore community?

**Comment by matejkramny** [comment]
Is this related to ansible [prompts](https://docs.ansible.com/ansible/playbooks_prompts.html)?

Related: #113, #85

**Comment by mcassaniti** [comment]
It could be used to provide information to vars_prompt, or it could simply generate an environment blob. Ansible Tower does the former. It may be able to provide the vault password, but not a private key password.

**Comment by DLWood1001** [comment]
If I am understanding correctly, mcassaniti wants to dynamically build an HTML form that maps to --extra-vars on the command line. The Semaphore form can then dump the vars to JSON and pass it in via the --extra-vars parameter. The feature itself would be to allow the user to build the HTML form and attach it to a playbook template. When the user clicks the 'run' button, they would be prompted with the form, hopefully with good defaults. They can either accept the defaults and run the playbook or edit an individual value.

**Comment by mcassaniti** [comment]
@DLWood1001 nailed it in 1.

**Comment by induction-lab** [comment]
+1 wery need this feature!

**Comment by mcassaniti** [comment]
Can I get some direction on starting work on this? My options for getting our Ops environment using Ansible at present are to build our own menu system or add this feature. Considering I need to do something on my employers time, I'd rather add this feature.

**Comment by induction-lab** [comment]
Sorry for the bad English.
I would like a window of options for the possibility of substituting values ​​--extra_vars before running pleybook. This could be a different boolean, string, or combobox value whose format would be specified in the yaml parameter file. This would be a very useful thing for many possible cases. There is no one like this, and this would be a unique feature.

**Comment by mcassaniti** [comment]
I wouldn't say this feature is unique. It is similar to what Ansible Tower offers, and RunDeck. I'm thinking something similar to the way RunDeck works would be ideal, and although I haven't read their documentation in full for it, I'd like to see that specifying a value for one option might be able to affect the output of another.

As an example, if I specify a group from a combobox, the next option will limit which host I can pick based on the group.

**Comment by fiftin** [comment]
This feature available since v2.8.31.

<img width="300px" src="https://user-images.githubusercontent.com/914224/150744646-57af39a5-930a-4eba-81d2-691e7d03ac6c.png" />
