### ISSUE TITLE
Feature request: PostgreSQL support

### ISSUE THREAD

**Issue by mgarces** [ansible-semaphore/semaphore#278]
It would be awesome if **semaphore** could support [PostgreSQL](https://www.postgresql.org/) too.

It is a robust SQL solution, and in my specific scenario, would remove the need to just run MySQL/MariaDB/Percona, just for **semaphore**.

#238 mentions PostgreSQL, but I believe this should be a different issue.

**Comment by matejkramny** [comment]
Do you think there would have to be a separate query for each database engine?

[Example](https://github.com/ansible-semaphore/semaphore/blob/master/api/user.go#L28)

**Comment by mgarces** [comment]
TBH I haven't looked into all SQL being used, but your example [Example](https://github.com/ansible-semaphore/semaphore/blob/master/api/user.go#L28) does not look like I would need to change anything with PostgreSQL.

**Comment by frostymarvelous** [comment]
This would be great as well. 
We only run mysql for ansible semaphore. 

I looked at the example and the sql is compatible. I think the migrations might be a bit of an issue though if we have vendor specific ddl.

**Comment by sololegends** [comment]
The DDLs aren't significantly different from MySQL to PostgreSQL, major differences are only  some data types, different auto increment definition (Serial), index definitions, and a very different definitions of what a schema is.

**Comment by fiftin** [comment]
Implemented in v2.7.4

https://github.com/ansible-semaphore/semaphore/releases/tag/v2.7.4
