### ISSUE TITLE
Inventory directory

### ISSUE THREAD

**Issue by ric79** [ansible-semaphore/semaphore#281]
Hello.
I have problems in running playbooks on Semaphore

The directories structure is

- prj/playbooks/myplaybook.yml
- prj/environments/develop/inventory
- prj/environments/develop/host_vars/ ....
- prj/environments/develop/group_vars/ ....

From command line I usually run:
> cd prj/playbooks/
> ansible-playbook -vv myplaybook.yml -i ../environments/develop

On Semaphore I don't understand how to specify ../environments/develop in order to use the right environment tree

R

**Comment by ric79** [comment]
Found!
On task menu: ["-i", "environments/develop"]

**Comment by matejkramny** [comment]
@ric79 you can also specify an inventory in semaphore's interface
