### ISSUE TITLE
OpenStack dynamic inventory

### ISSUE THREAD

**Issue by irongomme** [ansible-semaphore/semaphore#288]
Is there any plan for having openstack into the dynamic inventory list ?

**Comment by cloudnull** [comment]
This would be great. I work on the OpenStack Ansible project and I'd love to have semaphore as an infrastructure UI interfacing with a dynamic inventory.

**Comment by matejkramny** [comment]
You could temporarily work around it using extra CLI arguments and trigger it with native ansible

**Comment by emonty** [comment]
Let me know if there is anything needed to make the ansible OpenStack Inventory plugin usable from semaphore. Since it'll spit json to stdout, I'd imagine it shouldn't be super terrible to connect together, right?

https://github.com/ansible/ansible/blob/devel/contrib/inventory/openstack.py

**Comment by niso120b** [comment]
I also need openstack in the dynamic inventory list, do you start working on it?!

**Comment by denzuko** [comment]
:+1:

**Comment by twhiston** [comment]
Functionally a dup of #47 
A generic way to deal with dynamic inventories will be coming!
