### ISSUE TITLE
Duplicated mapping key in api document

### ISSUE THREAD

**Issue by laeshiny** [ansible-semaphore/semaphore#290]
When I run Swagger-Editor with api-doc.yaml. I faced with below error message
```
YAML Syntax Error
Duplicated mapping key at line 163, column 3: Template: ^
Jump to line 162
```

I think that duplicated one should be replaced from Task to TaskOutput.
This is api doc : https://github.com/ansible-semaphore/semaphore/blob/develop/api-docs.yml

**Comment by matejkramny** [comment]
Nice catch!
