### ISSUE TITLE
SSH, git & passwords

### ISSUE THREAD

**Issue by javadan** [ansible-semaphore/semaphore#295]
Hi,  I'm having trouble with these SSH keys, and git, in semaphore.  

I made a local user, (user: git, password: git), 
made a git server and repo (on localhost) and committed my playbook, so I could try out this ui.  

I'm using the latest git on Centos 7.

I made another user, ansible_user, and I am able to clone the playbook repo manually, using: 
`git clone git@my-server:/srv/git/ansible.git`
or
`git clone ssh://git@10.20.2.38/srv/git/ansible.git`

but I have to enter the password, 'git', when it prompts me, for git's password.

So I'm not sure how to get past this.  Centos won't let me enter a blank ssh password for the git user.
Is it a server ssh setting I need to change, to allow users to not have passwords?  

And, which key pair does the UI actually want?  the git user's id_rsa/id_rsa.pub, or the ansible_user user's id_rsa/id_rsa.pub?

```
17:04:03: Run task with template: Playbook test
17:04:03: access key git_key installed
17:04:03: Cloning repository git@my-server:/srv/git/ansible.git
17:04:03: Cloning into 'repository_2'...
17:04:03: Cloning into 'repository_2'...
17:04:03: Permission denied, please try again.
17:04:03: Failed updating repository: exit status 128
17:04:03: Permission denied, please try again.
17:04:03: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).

```

**Comment by matejkramny** [comment]
git@my-server `.ssh` directory (or `authorized_keys` file) might be having incorrect permissions - check `/var/log/secure` it could say if ssh keys get denied.

The ssh keys are for the local user. If you have access from `root` user to .. github, then copy the ssh key's contents into semaphore. You might have another set of keys to access the *servers* which your playbook accesses.

You might not need to make a git server. If the directory is local to semaphore, you can simply enter the path (`/some/path/to/git`). The folder must be a git folder (see `git init --bare`)

I hope this clears somethings up!

**Comment by javadan** [comment]
Permissions look fine.  chmod 600 and git owns it.

The error is " Failed password for git"

If I try remove the password for this user, it won't let me.  Must I configure my linux to allow SSH users without passwords?

**Comment by javadan** [comment]
Ok, well I got past the git password with your path-based plan.  But now I'm stuck on the next step.


```
14:16:44: Started: 21
14:16:44: Run task with template: Deploy

14:16:44: access key Ansible User Key installed
14:16:44: Updating repository /opt/ansible/git/ansible
14:16:44: From /opt/ansible/git/ansible
14:16:44:  * branch            master     -> FETCH_HEAD
14:16:44: Already up-to-date.
14:16:44: access key Ansible User Key installed
14:16:44: installing static inventory
14:16:44: From /opt/ansible/git/ansible
14:16:44:  * branch            master     -> FETCH_HEAD
14:16:44: Already up-to-date.
14:16:44: access key Ansible User Key installed
14:16:44: installing static inventory
14:16:44: Using /etc/ansible/ansible.cfg as config file
14:16:44: Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc
14:16:44: 
14:16:44: PLAYBOOK: nopassword.yml *******************************************************
14:16:44: 1 plays in nopassword.yml
14:16:44: 
14:16:44: PLAY [test] ********************************************************************
14:16:44: 
14:16:44: TASK [setup] *******************************************************************
14:16:45: Using module file /usr/lib/python2.7/site-packages/ansible/modules/core/system/setup.py
14:16:45: <10.20.2.40> ESTABLISH SSH CONNECTION FOR USER: ansible_user
14:16:45: <10.20.2.40> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/opt/ansible/access_key_6"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ansible_user -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r 10.20.2.40 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1489580205.03-67668017685028 `" && echo ansible-tmp-1489580205.03-67668017685028="` echo ~/.ansible/tmp/ansible-tmp-1489580205.03-67668017685028 `" ) && sleep 0'"'"''
```


It just hangs here forever, and locks up the program.  Any idea what's going on?  

If I go to the machine it's trying to connect to, I see I have added the key in authorized_keys, and it matches the one being used in semaphore.
