### ISSUE TITLE
lookup('env', 'PWD') is not working properly in ansible group vars

### ISSUE THREAD

**Issue by haoxinglu** [ansible-semaphore/semaphore#296]
I'm running on ubuntu 14.04 trusty and semaphore version 2.2.0.
I have a variable in group vars that requires the repository directory. I used lookup('env', 'PWD') to get that. However, instead of giving me where the ansible-playbook commands runs, which I assume is the repository_<id> folder, it gives me where I start my semaphore. For example, if I run "semaphore -config /path/to/config.json" under user home directory, it will give me /home/user instead of /path/to/repository_<id>. 

Did I do something wrong here? Please help, thanks!

**Comment by matejkramny** [comment]
Is it possible to use a relative path?

This could be improved by setting the working directory to the repo when running the playbook.

**Comment by haoxinglu** [comment]
@matejkramny Can you explain a little bit more on setting the working directory to the repo? Do we do it in semaphore UI or settings or in ansible?
I haven't try with the relative path yet. But it might involve other code change so I want to see if we can make the lookup right first :D

**Comment by matejkramny** [comment]
Hmm looking through [the code](https://github.com/ansible-semaphore/semaphore/blob/master/api/tasks/runner.go#L333), it appears it is set correctly.

Can you print the environment to see what's going on?

**Comment by haoxinglu** [comment]
@matejkramny I print out the env inside ansible playbook as a task and it still gave me the directory where I ran the semaphore instead of the repository_<id>.

**Comment by haoxinglu** [comment]
@matejkramny Just want to change out if there's any update on this bug? Thanks!

**Comment by matejkramny** [comment]
My apologies, I was on vacation. I wanted to test this locally

**Comment by haoxinglu** [comment]
@matejkramny No worries and thanks a lot :D

**Comment by fiftin** [comment]
Fixed
