### ISSUE TITLE
About the rq queue back-end worker program

### ISSUE THREAD

**Issue by baxiaoshi** [ansible-semaphore/semaphore#30]
Hello, I'm also writing a ansible based management tool, but now found back-end rq worker processes do not directly on the background, don't know for backend worker program, how is your side

My English is not very good, please forgive me. Thanks

**Comment by matejkramny** [comment]
We use [`async.queue`](https://github.com/caolan/async#queue)

Sorry about the delay :P

Best of luck in your management tool.
