### ISSUE TITLE
mysql: `user__token` table has incorrect VARCHAR size for `id` field

### ISSUE THREAD

**Issue by neilmcgibbon** [ansible-semaphore/semaphore#303]
When calling the API to create a user token (POST /user/tokens) I was met with an HTTP 500.  

The panic included (part of trace removed for brevity):
```
Error 1406: Data too long for column 'id' at row 1
/usr/local/Cellar/go/1.8/libexec/src/runtime/panic.go:489 (0x42875f)
...
/Users/m/p/go/src/github.com/ansible-semaphore/semaphore/api/user.go:50 (0x910ad4)
...
```

The code that creates the API token takes a 32 byte[] and base64 encodes it:

```go
func createAPIToken(c *gin.Context) {
        //...
	tokenID := make([]byte, 32)
        // ...
	token := models.APIToken{
		ID:      strings.ToLower(base64.URLEncoding.EncodeToString(tokenID)),
                // ...
	}
        // ...
}
```

A 32 byte[] in base64 will yield a string of 44 characters: `4 * math.Ceil(32/3.0) = 44` (@see http://stackoverflow.com/questions/13378815/base64-length-calculation)

The `user__token` mysql table has an `id` field of 32 characters, this should be 44, so a migration of:

```mysql
 ALTER TABLE `user__token` CHANGE COLUMN `id` `id` VARCHAR(44) NOT NULL;
```

This worked for me - not sure if its already been picked up, but I couldn't find it in issues.

**Comment by matejkramny** [comment]
Thanks!
