### ISSUE TITLE
UI Freezes after failed SSH

### ISSUE THREAD

**Issue by javadan** [ansible-semaphore/semaphore#306]
I've set up an SSH key without passphrase for my user, ansible_user, such that I can ssh to my other computer as that user without needing to enter a password.

I've changed my playbook to not use a vault, and am just using something like this.  
  vars:
    - ansible_become_pass: xxxxxxx

The environment is set up as a copy of my /etc/ansible/hosts.

The git repo is just set to the directory where everything is stored.

But when I try running the playbook, I get the following, and the UI freezes, with the 'working' icon spinning in the top left.  I can't continue until I kill the process manually and restart.

Any idea what may be wrong?
     
```

13:28:48: Started: 23
13:28:48: Run task with template: Test Playbook

13:28:48: access key Ansible User key installed
13:28:48: Cloning repository /opt/ansible/git/ansible
13:28:48: Cloning into 'repository_4'...
13:28:48: done.
13:28:48: Cloning into 'repository_4'...
13:28:48: done.
13:28:48: access key Ansible User key installed
13:28:48: installing static inventory
13:28:48: Using /etc/ansible/ansible.cfg as config file
13:28:48: Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc
13:28:48: 
13:28:48: PLAYBOOK: nopassword.yml *******************************************************
13:28:48: 1 plays in nopassword.yml
13:28:48: 
13:28:48: PLAY [test] ********************************************************************
13:28:48: 
13:28:48: TASK [setup] *******************************************************************
13:28:49: Using module file /usr/lib/python2.7/site-packages/ansible/modules/core/system/setup.py
13:28:49: <10.20.2.40> ESTABLISH SSH CONNECTION FOR USER: ansible_user
13:28:49: <10.20.2.40> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/opt/ansible/access_key_7"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ansible_user -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r 10.20.2.40 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1490182129.03-186007576500653 `" && echo ansible-tmp-1490182129.03-186007576500653="` echo ~/.ansible/tmp/ansible-tmp-1490182129.03-186007576500653 `" ) && sleep 0'"'"''

```

**Comment by javadan** [comment]
Ah, well I reran with the tty in the foreground, and saw that it was waiting for me to enter a passphrase.

Intriguing.

**Comment by javadan** [comment]
Ooh... so, that gave me the next error, which was "Could not load \"/opt/ansible/access_key_7\" as a RSA1 public key" (missing whitespace.)

I added the fluff around the end, 
-----BEGIN RSA PRIVATE KEY-----
-----END RSA PRIVATE KEY-----

and it is now running... into the next error...

now it's stuck on 
21:53:17: PLAYBOOK: nopassword.yml *******************************************************
21:53:17: 1 plays in nopassword.yml
21:53:17: 
21:53:17: PLAY RECAP *********************************************************************


Stay tuned... i guess.

**Comment by javadan** [comment]
Ok, and last error was an actual error from setting a nonexistent host.  

Working now!  Hope this helps someone.

I do think something could probably be done about logging though.  

If I ran my script on the command line, it would have hard failed with an error message.  Instead it freezes the app with no debug info.

**Comment by jamesspi** [comment]
Hey @javadan, did you manage to get a "become" password prompt, or does it have to be entered in tty?

Thanks,
James

**Comment by NTDBANNU** [comment]
I am trying to execute a playbook from Ansible semaphore to a client machine and it gives me the below error. Has any one encountered this error before ? I would really appreciate your help.

![error](https://user-images.githubusercontent.com/24846966/29256566-39e3f3b6-8060-11e7-84fd-687ed9ccb838.png)
