### ISSUE TITLE
can't run task template - git says i have local changes

### ISSUE THREAD

**Issue by frisbee23** [ansible-semaphore/semaphore#308]
i try to make semaphore exec a previously working playbook. 
it fails at the git-checkout, because seemingly a previous ansible run has create a retry file.
is this known ? is there a workaround?
thanks in advance,
fil

12:50:00: Started: 65

12:50:00: access key TSK_key1 installed
12:50:00: Updating repository git@git.example.com:lol-its/cm.git
12:50:00: Updating repository git@git.example.com:lol-its/cm.git
12:50:05: From git.example.com@lol-its/cm
12:50:05:  * branch            master     -> FETCH_HEAD
12:50:05: error: Your local changes to the following files would be overwritten by merge:
12:50:05: 	site.retry
12:50:05: Please commit your changes or stash them before you merge.
12:50:05: Aborting
12:50:05: Updating 137b41a..985094e
12:50:05: Failed updating repository: exit status 1

**Comment by frisbee23** [comment]
Semaphore 2.1.0
git version 2.11.0
on Linux 4.9.9-coreos-r1 /debian stretch

**Comment by strangeman** [comment]
Add `*.retry` to the `.gitignore` :)

@matejkramny Maybe we should call something like `git reset --hard` before repo pull?

**Comment by frisbee23** [comment]
thanx dude! that should help
yeah, i think it's cool that not always the whole repo is pulled, it saves time. 
but ansible like to create these files. so some git way of cleaning the repo would be good i guess.
i also solved it now by manually deleting the file and upgradeing semaphore. also, now it created a .retry file again, but apparently somethings different, because i can re-run the playbook.

**Comment by strangeman** [comment]
I think you added `.retry` file to your repo before. And now, when a content of this file isn't changed - all is ok, but when ansible changing that file content - it cause `Your local changes to the following files would be overwritten by merge` error.
If you do not need to save intermediate play states in CVS, you shouldn't store this file in the repo.

**Comment by frisbee23** [comment]
that may indeed be the case. i was sick one week and don't really know .. thanks for the quick help dude.

**Comment by matejkramny** [comment]
should be reset or a flag passed to ansible to not add/modify `.retry` files

**Comment by twhiston** [comment]
I'm going to close this as ignoring retry files is the easiest approach and i dont see why you would ever commit retry files to vcs.
