### ISSUE TITLE
Variables

### ISSUE THREAD

**Issue by jamesspi** [ansible-semaphore/semaphore#311]
Hi!

Would it be possible to prompt a user for a variable whilst running a template, without having to make any changes to the template itself?

Thanks!
James

**Comment by lowks** [comment]
+1 This would be great!

**Comment by mattg-92** [comment]
+1 Would be really great instead of having to edit things constantly

**Comment by induction-lab** [comment]
+1

**Comment by mcassaniti** [comment]
Is this related to #274 ?

**Comment by fiftin** [comment]
This feature available since v2.8.31.

<img width="300px" src="https://user-images.githubusercontent.com/914224/150744646-57af39a5-930a-4eba-81d2-691e7d03ac6c.png" />
