### ISSUE TITLE
feature request/question if already exists: run task-templates periodically/automatically ie. with cronjob

### ISSUE THREAD

**Issue by frisbee23** [ansible-semaphore/semaphore#313]
hi,
i used to work with puppet earlier. in our setup or i think even in general, puppet runs periodically, i think once an hour, and applies the manifest to each corresponding host.

i want something similar with the ansible scripts i wrote. that they are periodically applied. now i also want to manage all my ansible stuff with semaphore. im not sure if it fit's your vision of semaphore, but i'd like to add a cronjob to my crontab that says something like: <each hour> semaphore --run-task-template task-template-alias1 # this is pseudo code

maybe such a thing is planned. maybe the 'best practice' for this use case is to just write a shell script. im interested in your thoughts..

i hope im clear enough. if not pls just ask..
thanks in advance,
fil

**Comment by strangeman** [comment]
Hi! You may call API via CRON. Here I explained how to call API via curl: https://github.com/ansible-semaphore/semaphore/issues/184#issuecomment-285866357

**Comment by frisbee23** [comment]
aye. thank you. i might write a wiki site for it.

**Comment by fiftin** [comment]
Available in https://github.com/ansible-semaphore/semaphore/releases/tag/v2.7.20.
