### ISSUE TITLE
Is there a way to get task log url?

### ISSUE THREAD

**Issue by spiilmusic** [ansible-semaphore/semaphore#314]
How can I share a task log with my teammates? I tried something like this http://ci.mydomain.com/project/5/task/327 but get redirect to main page.

Thank you.

**Comment by matejkramny** [comment]
Does the colleague have access to the project?

**Comment by spiilmusic** [comment]
Of course! I mean that the task logs are loaded with XHR and there is no way to get the direct url of the log :(

**Comment by strangeman** [comment]
@spiilmusic you can get task output (without formatting, in JSON representation) via API: https://ansible-semaphore.github.io/semaphore/#!/project/get_project_project_id_tasks_task_id_output

For example https://ansible.example.com/api/project/6/tasks/666/output

**Comment by spiilmusic** [comment]
@strangeman Ok, thank you countryman 👍
