### ISSUE TITLE
MySQL table column user__token.id is too small

### ISSUE THREAD

**Issue by mr-joom** [ansible-semaphore/semaphore#315]
MySQL table column user__token.id has type varchar(32), but token string encoded to base64 has length 45 symbols. So, generated token is cutted within MySQL.
Example:

POST /user/tokens
Response body:
```json
{
  "id": "hwtpo9kx1yz2rsjqbg8jmm8nmenkaqjximkypvcpqxg=",
  "created": "2017-04-03T12:39:27.894526124-04:00",
  "expired": false,
  "user_id": 1
}
```
GET /user/tokens
Response body:
```json
[
  {
    "id": "hwtpo9kx1yz2rsjqbg8jmm8nmenkaqj",
    "created": "2017-04-03T16:39:27Z",
    "expired": false,
    "user_id": 1
  }
]
```

**Comment by metacoma** [comment]
Confirm this bug

Workaround:
`docker-compose exec mysql mysql -h localhost -u semaphore --password=semaphore semaphore -e 'alter table user__token CHANGE COLUMN id id VARCHAR (45);'`

**Comment by matejkramny** [comment]
dup #303
