### ISSUE TITLE
panic: Error 1040: Too many connections  / panic: dial tcp 127.0.0.1:3306: socket: too many open files

### ISSUE THREAD

**Issue by jrm** [ansible-semaphore/semaphore#316]
When running a task template with debug enabled semaphore dies with:

panic: Error 1040: Too many connections

Running the same task template without debug, semaphore dies with:

panic: dial tcp 127.0.0.1:3306: socket: too many open files

Both produce the same stack trace...

github.com/ansible-semaphore/semaphore/api/tasks.(*task).log.func1(0xc42037e000, 0xc4201d0300, 0x34, 0xed076f134, 0xee735b6, 0x1a68ec0)
	/Users/m/p/go/src/github.com/ansible-semaphore/semaphore/api/tasks/logging.go:36 +0x19f
created by github.com/ansible-semaphore/semaphore/api/tasks.(*task).log
	/Users/m/p/go/src/github.com/ansible-semaphore/semaphore/api/tasks/logging.go:38 +0x612

My environment is:

Semaphore 2.2.0
MySQL: 5.7.12 Homebrew (local)
OSX: 10.11.4 (15E65)

My task template references a playbook that contains 3 tasks and is targeting 3 hosts.

Is this a sign of a bad MySQL server config?

**Comment by strangeman** [comment]
Duplicates https://github.com/ansible-semaphore/semaphore/issues/132
