### ISSUE TITLE
Release 2.2.0 websocket: not a websocket handshake: 'upgrade' token not found in 'Connection' header'

### ISSUE THREAD

**Issue by metacoma** [ansible-semaphore/semaphore#317]
semaphore_proxy_1  | 172.21.0.1 - - [05/Apr/2017:15:27:03 +0000] "GET /api/ws HTTP/1.1" 400 12 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, l[146/1932]
 Chrome/57.0.2987.110 Safari/537.36"
semaphore_api_1    | 
semaphore_api_1    | 
semaphore_api_1    | 2017/04/05 15:27:03 [Recovery] panic recovered:
semaphore_api_1    | GET /api/ws HTTP/1.0
semaphore_api_1    | Host: semaphore_api:3000
semaphore_api_1    | Connection: close
semaphore_api_1    | Accept-Encoding: gzip, deflate, sdch, br
semaphore_api_1    | Accept-Language: en-US,en;q=0.8
semaphore_api_1    | Cache-Control: no-cache
semaphore_api_1    | Connection: close
semaphore_api_1    | Cookie: semaphore=MTQ5MTQwNTY0OHxyWUdPaEh6eUU1MVFQb2pxNXo3MVlxOUxudVEyajVvN2p0RWdMNmVSVWFGSHlIY3F3RXNUNnYydFJzMnpvWGlrWGNYMUhWbzNONmhiQTdzVlNKWGdmcUk
9fHunAbVAHsL27ixyFKkUmZ9hNrR4gA9LqxygYcGfIG8P
semaphore_api_1    | Origin: http://localhost:8082
semaphore_api_1    | Pragma: no-cache
semaphore_api_1    | Sec-Websocket-Extensions: permessage-deflate; client_max_window_bits
semaphore_api_1    | Sec-Websocket-Key: 99VMT56G6z8rRWMNM0LKVQ==
semaphore_api_1    | Sec-Websocket-Version: 13
semaphore_api_1    | User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.110 Safari/537.36
semaphore_api_1    | 
semaphore_api_1    | 
semaphore_api_1    | websocket: not a websocket handshake: 'upgrade' token not found in 'Connection' header
semaphore_api_1    | /usr/local/Cellar/go/1.8/libexec/src/runtime/panic.go:489 (0x42875f)
semaphore_api_1    | /Users/m/p/go/src/github.com/bugsnag/bugsnag-go/bugsnag.go:52 (0x6d3e23)
semaphore_api_1    | /usr/local/Cellar/go/1.8/libexec/src/runtime/asm_amd64.s:514 (0x452b68)
semaphore_api_1    | /usr/local/Cellar/go/1.8/libexec/src/runtime/panic.go:489 (0x42875f)
semaphore_api_1    | /Users/m/p/go/src/github.com/ansible-semaphore/semaphore/api/sockets/handler.go:102 (0x8ee44d)
semaphore_api_1    | /Users/m/p/go/src/github.com/gin-gonic/gin/context.go:97 (0x7a56fa)
semaphore_api_1    | /Users/m/p/go/src/github.com/gin-gonic/gin/logger.go:72 (0x7b3d6f)
semaphore_api_1    | /Users/m/p/go/src/github.com/gin-gonic/gin/context.go:97 (0x7a56fa)
semaphore_api_1    | /Users/m/p/go/src/github.com/ansible-semaphore/semaphore/cli/main.go:72 (0x914232)
semaphore_api_1    | /Users/m/p/go/src/github.com/gin-gonic/gin/context.go:97 (0x7a56fa)
semaphore_api_1    | /Users/m/p/go/src/github.com/gin-gonic/gin/recovery.go:45 (0x7b4a9a)
semaphore_api_1    | /Users/m/p/go/src/github.com/gin-gonic/gin/context.go:97 (0x7a56fa)
semaphore_api_1    | /Users/m/p/go/src/github.com/gin-gonic/gin/gin.go:284 (0x7ab890)
semaphore_api_1    | /Users/m/p/go/src/github.com/gin-gonic/gin/gin.go:265 (0x7ab1ab)
semaphore_api_1    | /usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:2568 (0x6a2732)
semaphore_api_1    | /usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:1825 (0x69e9a2)
semaphore_api_1    | /usr/local/Cellar/go/1.8/libexec/src/runtime/asm_amd64.s:2197 (0x455291)

**Comment by strangeman** [comment]
Please, show your reverse-proxy (nginx?) config. Are you following recommendations from https://github.com/ansible-semaphore/semaphore/blob/master/Deploy/proxy/nginx.conf?

Especially, look at this section, looks like you're not set specific headers for websockets:
```
    location /api/ws {
      proxy_pass http://semaphore_api/api/ws;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Origin "";
    }
```

**Comment by metacoma** [comment]
> Please, show your reverse-proxy (nginx?)

Yep, correct
> proxy_set_header Origin "";

Wooops, missed reset this header, thanks!

**Comment by hongdingyi** [comment]
thanks
