### ISSUE TITLE
Non-Admin user have ability to change password for another user Release 2.2.0 

### ISSUE THREAD

**Issue by metacoma** [ansible-semaphore/semaphore#318]
Non-Admin user have ability to change password for another user

**Comment by strangeman** [comment]
Whoops, I confirm this bug.

**Comment by strangeman** [comment]
Wait. There are no Admin users. The user can be admin of project (can add new users to the project), but can't be admin of entire installation - there are no such role system.

**Comment by strangeman** [comment]
Duplicates https://github.com/ansible-semaphore/semaphore/issues/198 

Currently, everyone has 'admin' rights and can edit everybody's info (password, username, email etc). This is insecure. Need to add 'User' role - user, who can edit only personal info. 

IMPORTANT: This is different rights model than Project Admin/User/RO User (from https://github.com/ansible-semaphore/semaphore/issues/344)
