### ISSUE TITLE
Docker Build Broken iojs 3.x.x (hiredis, node-gyp, nan)

### ISSUE THREAD

**Issue by gcoffey** [ansible-semaphore/semaphore#32]
Using the current docker image running iojs 3.x.x, fails during installation of hiredis node module.
The problem is linked to an issue with hiredis 0.4.0 & nan.

https://github.com/redis/hiredis-node/issues/95
https://github.com/redis/hiredis-node/pull/96

It doesn't look like the hiredis fix has been merged into master yet.

**Comment by matejkramny** [comment]
Ok but i think you're posting it to the wrong repository. There's nothing I can do about this..
