### ISSUE TITLE
Add task status method to REST API

### ISSUE THREAD

**Issue by templed** [ansible-semaphore/semaphore#326]
Hello,

I'm using the REST API for part of our tooling and found it useful to have a method to query the status of a task as the only time I can otherwise get its state is by parsing the output of it.

I've added a method for this feature and the code is available at https://github.com/ansible-semaphore/semaphore/compare/master...commodityvectors:REST_status

If this is something that would be useful to add but requires some tidying up (my Go is still not great) then please let me know.

Cheers

**Comment by matejkramny** [comment]
Interesting. We could certainly add an API endpoint for fetching a task.

Currently the UI gets `/tasks` and when you click on one it gets the data from that.

The code: good but everything you need is in the `task` (`api/tasks/http.go:102`). The database fetch is unnecessary unless there's information not already present.

Documentation wise, rename `TaskStatus` to `Task`.

Thanks!

**Comment by matejkramny** [comment]
@templed can you check if PR #357 would provide what you need over the API?

**Comment by templed** [comment]
PR #357 provides what I need (just the `status` string). The only difference I can see is that my API change includes the various times (create, start, end) which are not required for me but I believed were "nice to haves". If someone needs them in the future then this can be looked into again, but I'm happy to close this and use #357's changes.
