### ISSUE TITLE
Make inventory not mandatory

### ISSUE THREAD

**Issue by strangeman** [ansible-semaphore/semaphore#328]
We store inventory files directly in playbooks repo (and throw them to the Semaphore via Extra CLI Arguments `"-i", "inventory/test/"`). I created `empty` inventory to pass around mandatory inventory field in task templates, but for each task call, Semaphore creates empty `inventory_task_id` file in the Semaphore directory. Currently, it looks like that and it a bit annoying:

![2017-04-20-113401_1366x768_scrot](https://cloud.githubusercontent.com/assets/1083576/25209277/6ea29434-25bd-11e7-874d-abb85791def1.png)

Can we make inventory not mandatory and not create any files, if inventory not defined?

**Comment by matejkramny** [comment]
semaphore also needs to clean up after itself!

**Comment by twhiston** [comment]
Closing in favour of #47 which should provide generalised inventory sources support, including none.
