### ISSUE TITLE
Upgrade does not run migrations

### ISSUE THREAD

**Issue by JanSchr** [ansible-semaphore/semaphore#332]
Hi,

i can't run any task anymore currently, i'm alway getting this error message (the semaphore process is ending itself after writing the panic in the logfiles and need to be started again):

Semaphore 2.3.0
Port :3000
MySQL root@127.0.0.1:3306 semaphore
Tmp Path (projects home) /var/lib/ansible-playbooks
 200  17:55:23  3.189484538s |   GET     /api/ws
 200  17:55:24    5.217196ms |   GET     /api/user
 200  17:55:25    5.372453ms |   GET     /api/info
 200  17:55:25    6.798181ms |   GET     /api/projects
 200  17:55:25   28.005801ms |   GET     /api/events
 200  17:55:26    7.279139ms |   GET     /api/project/2
 200  17:55:27    6.651142ms |   GET     /api/project/2/tasks
 200  17:55:27   10.077811ms |   GET     /api/project/2/events
 200  17:55:30    4.699112ms |   GET     /api/users/1
 200  17:55:30   10.979563ms |   GET     /api/project/2/tasks/12/output
 200  17:55:36    5.868763ms |   GET     /api/project/2/inventory
 200  17:55:36    8.689869ms |   GET     /api/project/2/keys
 200  17:55:36    8.344061ms |   GET     /api/project/2/repositories
 200  17:55:36    7.842716ms |   GET     /api/project/2/templates
 200  17:55:36    8.961039ms |   GET     /api/project/2/environment
&{{19 9 waiting false true   0xc4200d0620 {63628473348 35689625 0xe76d80} <nil> <nil>} {0 0 0 0 0 <nil>   <nil> false} {0   <nil> <nil> <nil> false} {0  0  <nil> {0   <nil> <nil> <nil> false} <nil> {0   <nil> <nil> <nil> false}  false} {0  0  0 false {0   <nil> <nil> <nil> false}} {0  0 <nil>  false} [] 2 false}
 201  17:55:48    9.744697ms |   POST    /api/project/2/tasks
Stopped running tasks
panic: Error 1054: Unknown column 'alert' in 'field list'
2017/04/22 17:55:48 notifying bugsnag: Error 1054: Unknown column 'alert' in 'field list'
2017/04/22 17:55:48 bugsnag.Notify: not notifying in development

It did work for some time after initially setting up sempahore using 2.2.0, at some point it stopped working, upgrading to 2.3.0 today was succesfull but makes no differences at all. 

Any hints how to get this fixed are appreciated!

kind regards

jan

**Comment by matejkramny** [comment]
Can you look up the `migrations` table in your database, look for `2.3.2` version?

Migrations might not have been executed after the upgrade

**Comment by JanSchr** [comment]
Hi,

thanks for the quick reply, looks like your're right:

mysql> show tables;
+----------------------------+
| Tables_in_semaphore        |
+----------------------------+
| access_key                 |
| event                      |
| migrations                 |
| project                    |
| project__environment       |
| project__inventory         |
| project__repository        |
| project__template          |
| project__template_schedule |
| project__user              |
| session                    |
| task                       |
| task__output               |
| user                       |
| user__token                |
+----------------------------+
15 rows in set (0.00 sec)

mysql> select * from migrations;
+---------+---------------------+-------+
| version | upgraded_date       | notes |
+---------+---------------------+-------+
| 0.0.0   | 2017-03-29 19:01:01 | NULL  |
| 0.1.0   | 2017-03-29 19:01:02 | NULL  |
| 1.0.0   | 2017-03-29 19:01:02 | NULL  |
| 1.1.0   | 2017-03-29 19:01:02 | NULL  |
| 1.2.0   | 2017-03-29 19:01:02 | NULL  |
| 1.3.0   | 2017-03-29 19:01:02 | NULL  |
| 1.4.0   | 2017-03-29 19:01:02 | NULL  |
| 1.5.0   | 2017-03-29 19:01:02 | NULL  |
| 1.6.0   | 2017-03-29 19:01:02 | NULL  |
| 1.7.0   | 2017-03-29 19:01:02 | NULL  |
| 1.8.0   | 2017-03-29 19:01:02 | NULL  |
| 1.9.0   | 2017-03-29 19:01:02 | NULL  |
+---------+---------------------+-------+
12 rows in set (0.01 sec)

mysql>

Kind regards

jan

**Comment by matejkramny** [comment]
Alright. Looks like the upgrade process doesn't run migrations.

**Comment by JanSchr** [comment]
Is there a way to run the migration manually?

**Comment by matejkramny** [comment]
If you pass the `-migrate` flag it will execute migrations and exit

**Comment by JanSchr** [comment]
Thank you, that fixed it, not it's working again. Thank you for that quick response!
