### ISSUE TITLE
Contrib Review: Bootstrapping with Ansible

### ISSUE THREAD

**Issue by thedumbtechguy** [ansible-semaphore/semaphore#333]
I have published a role [semaphore](https://galaxy.ansible.com/thedumbtechguy/semaphore/) which can be used to setup semaphore on an ubuntu server.

It was written for Ubuntu 16.04 and 16.10 but can be expanded to cater for more.

It is interesting because it contains a [script](https://github.com/thedumbtechguy/ansible-role-semaphore/blob/master/bootstrap.sh) that can be used in bootstrapping a complete solution easily and painlessly.
I would like to add it to the wiki, but would prefer if you reviewed it first to find out if it is satisfactory,

**Comment by twhiston** [comment]
I've added a comment pointing generally towards the ansible-galaxy search for semaphore, where yours is displayed. That being said if you are still interested in feedback on this open a new issue and I will do it
