### ISSUE TITLE
[CRITICAL] If LDAP enabled, user can login with ANY login/password

### ISSUE THREAD

**Issue by strangeman** [ansible-semaphore/semaphore#335]
After refactoring in https://github.com/ansible-semaphore/semaphore/commit/fe8851bcfec73538ea454a397d89c8610c946d89, login logic was completely broken. Currently, anybody can log in with any login/password, even if wrong. He can't access to projects/tasks but allowed to change a password to any non-LDAP user.

**Comment by strangeman** [comment]
Closed by https://github.com/ansible-semaphore/semaphore/pull/336

**Comment by matejkramny** [comment]
@strangeman i'm reading the code in `api/login.go` and it still appears to have an issue w/ security.

The logic is currently (as of the PR):

```
if LDAP is on (line 118)
  try ldap login
  if fail, log the error

if LDAP is off or no LDAP-error (line 146)
  do regular authentication

create session (Line 170)
log the user into the system
```

with this logic, it follows that if ldap login fails the user gets authenticated anyway unless there's something i'm not seeing.

**Comment by matejkramny** [comment]
I'll rewrite the login bit & make a PR. Would appreciate if you can review this so the same mistake doesn't happen again 👍
