### ISSUE TITLE
Changing task templates fail since 2.3.0 upgrade

### ISSUE THREAD

**Issue by JanSchr** [ansible-semaphore/semaphore#337]
Hi,

since i updated to semaphore 2.3.0 i can't change any setting within a task template anymore (i'm getting a 502 Error in the Web UI). Deleting the task template and recreate it from scratch works though (so it not that important).

http: panic serving [::1]:48894: runtime error: invalid memory address or nil pointer dereference
goroutine 336 [running]:
net/http.(*conn).serve.func1(0xc4201f4fa0)
	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:1721 +0xd0
panic(0x9b61e0, 0xe65750)
	/usr/local/Cellar/go/1.8/libexec/src/runtime/panic.go:489 +0x2cf
github.com/ansible-semaphore/semaphore/api/projects.UpdateTemplate(0xce7e60, 0xc4205812c0, 0xc4205a6800)
	/Users/m/p/go/src/github.com/ansible-semaphore/semaphore/api/projects/templates.go:134 +0x188
github.com/castawaylabs/mulekick.Router.Handle.func1(0xce8460, 0xc4200fdb20, 0xc4205a6800)
	/Users/m/p/go/src/github.com/castawaylabs/mulekick/router.go:69 +0x11a
net/http.HandlerFunc.ServeHTTP(0xc4202b9500, 0xce8460, 0xc4200fdb20, 0xc4205a6800)
	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:1942 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc4200179a0, 0xce8460, 0xc4200fdb20, 0xc4205a6800)
	/Users/m/p/go/src/github.com/gorilla/mux/mux.go:114 +0x10c
github.com/gorilla/handlers.ProxyHeaders.func1(0xce8460, 0xc4200fdb20, 0xc4205a6200)
	/Users/m/p/go/src/github.com/gorilla/handlers/proxy_headers.go:59 +0x117
net/http.HandlerFunc.ServeHTTP(0xc4202de060, 0xce8460, 0xc4200fdb20, 0xc4205a6200)
	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:1942 +0x44
net/http.(*ServeMux).ServeHTTP(0xe76a20, 0xce8460, 0xc4200fdb20, 0xc4205a6200)
	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:2238 +0x130
net/http.serverHandler.ServeHTTP(0xc4202e0000, 0xce8460, 0xc4200fdb20, 0xc4205a6200)
	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc4201f4fa0, 0xce8c20, 0xc420434300)
	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:2668 +0x2ce

kind regards

jan

**Comment by ericlakich** [comment]
+1

**Comment by joesm** [comment]
I have this issue also.  Since I am just starting to learn Ansible Semaphore (meaning I make lots of changes), I find the issue a bit more painful than an established user probably would.

Great product, though.  I am very impressed!

**Comment by deepak7093** [comment]
+1

**Comment by ericlakich** [comment]
For anyone with this issue, the fix (#355) will patch this in a future release. For a short-term workaround, when you update a Task Template and that task template has no Extra CLI Arguments, simply add a blank CLI arg with:

`["",""]`

That will bypass the nil exception (the bug).

**Comment by kaleescts** [comment]
After CLI arguments are updated, if i hit Start Job URL , it is not running the playbook properly. It is working if i manually run the commit.sh file.
Can you tell me what is the issue here?
