### ISSUE TITLE
docker-compose proxy path is wrong 

### ISSUE THREAD

**Issue by rgarrigue** [ansible-semaphore/semaphore#339]
Hello

Trying docker-compose up on newly cloned repo, 

     ~/work/semaphore master $ docker-compose up
    ERROR: build path /home/remy/work/semaphore/proxy either does not exist, is not accessible, or is not a valid URL.

... because it's script/proxy, to be updated in docker-compose.yml.

Regards,

**Comment by tmidi** [comment]
Same issue with ***/proxy

**Comment by matejkramny** [comment]
Docker stuff needs updating. It should build semaphore as the CI does.

**Comment by akhilbatra898** [comment]
When I am trying to follow [https://github.com/ansible-semaphore/semaphore/blob/develop/circle.yml](url)

I am getting this error while running `make.sh` part

`Adding bindata
bindata: Input path 'config.json' is not a directory.
`

**Comment by twhiston** [comment]
closing as docker deployments have been refactored
