### ISSUE TITLE
Can't connect to Mongo using the docker setup

### ISSUE THREAD

**Issue by mickengland** [ansible-semaphore/semaphore#34]
I followed the instructions in the README.md for Docker Quick Start. After getting the three containers up and running I see this in the logs for semaphore:

Mongodb Connection Error: { [MongoError: connect EHOSTUNREACH 172.17.0.25:27017]
  name: 'MongoError',
  message: 'connect EHOSTUNREACH 172.17.0.25:27017' }

For the Mongo container I see this in the logs:
2015-09-07T15:21:35.814+0000 I NETWORK  [initandlisten] waiting for connections on port 27017

I tried just using -p 27017:27017 for mongo, thinking maybe it was only listening on localhost but same results in logs.

**Comment by matejkramny** [comment]
Are the containers properly linked?
The other thing is if the semaphore config uses the correct hostname as the container link defines them.

Eg if you do `docker inspect <id>`, it should show that the containers link and share ports

**Comment by mickengland** [comment]
This is what inspect shows me for links. Only the semaphore container has links defined, as per the instructions. 

$ sudo docker inspect -f "{{ .HostConfig.Links }}" semaphore
[/mongodb:/semaphore/mongo /redisio:/semaphore/redis]

sudo docker inspect -f "{{ .HostConfig.Links }}" mongodb
[]

[mick@mick-fedora semaphore]$ sudo docker inspect -f "{{ .HostConfig.Links }}" redisio
[]

For the Mongo container I see this:

"PortBindings": {
            "27017/tcp": [
                {
                    "HostIp": "127.0.0.1",
                    "HostPort": "27017"
                }

Which is making me think it is only listening on localhost but I don't know how to fix that. Do I need to add another link at run time and if so where?

**Comment by matejkramny** [comment]
Hmm no i think docker does port forwarding.

Have you got a config file for semaphore?

**Comment by mickengland** [comment]
I am using whatever configs are within the repos. I simply cloned the repo and went through the Docker Quickstart without making any changes to configs. Not sure what you are looking for but it will be identical to what is in this repository.

**Comment by mickengland** [comment]
@matejkramny Thanks for looking into this. This log from semaphore shows that it is trying to connect to the IP address of the Mongo container:
$ sudo docker logs semaphore
app.js:110 Semaphore listening on port 80
Mongodb Connection Error: { [MongoError: connect EHOSTUNREACH 172.17.0.25:27017]
  name: 'MongoError',
  message: 'connect EHOSTUNREACH 172.17.0.25:27017' }

and a docker inspect of mongodb shows that the IP address is correct.

 "Gateway": "172.17.42.1",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "HairpinMode": false,
        "IPAddress": "172.17.0.25",

I don't know enough about nodejs/mongo to troubleshoot this even if I attach a shell to the containers.

**Comment by matejkramny** [comment]
I'll try the tutorial and let you know.

**Comment by matejkramny** [comment]
Hey, Sorry I was a little busy today. I'll have time today after work

Thanks

**Comment by mickengland** [comment]
Thanks @matejkramny I will check back later to see how it works out for you.

**Comment by matejkramny** [comment]
I setup a brand new box (ubuntu 15.04 with docker) and copy-pasted all the steps in the "Docker quickstart" section and seems to work well.

Can you try:
`docker run -it --rm --link mongodb:mongo castawaylabs/semaphore /bin/bash`

Inside, you can ping `mongo` hostname, and prod it for open ports. If that doesn't work, then its a fault in docker or your firewall because I think docker sets up iptables to do port forwarding

**Comment by mickengland** [comment]
Thanks @matejkramny I think this is a bug in docker on Fedora 22. I found some posts on this elsewhere. You can close this issue now. I will get this running on a Ubuntu system.

**Comment by Echobob** [comment]
Closing upon request
