### ISSUE TITLE
Is there a possibility to pass semaphore user name to ansible vars?

### ISSUE THREAD

**Issue by spiilmusic** [ansible-semaphore/semaphore#340]
i.e.: Some variables in environment JSON.
Or it can be also realised by webhooks call from semaphore if task has been completed.
Please leave any thoughts. I absolutely don't know the golang, but I can try to do this.

At this moment we use custom ansible plugin to send task info to the slack chat, and this plugin just uses system user name, so if playbook runs by semaphore, user will be semaphore.

Thanks.

**Comment by matejkramny** [comment]
Semaphore could add variables like when script was started, link to the UI.

We can parse the JSON, add `"SEMAPHORE_xyz"` keys & encode to JSON again. The issue is maintaining integrity & possible side effects. Currently semaphore just accepts the JSON string as it is.

Any ideas?

**Comment by fiftin** [comment]
Yes, now it happens automatically, more details here: https://docs.ansible-semaphore.com/administration-guide/build-and-deploy
