### ISSUE TITLE
Question : non interactive setup

### ISSUE THREAD

**Issue by Niflou** [ansible-semaphore/semaphore#347]
Hi !

I'm wondering if there is a way to install semaphore automatically (lets say with .. hmmm .. ansible ? :smile: )

So far we can generate the config file ourselves since its self explanatory then run the migration process on a brand new database (and its working fine :sunglasses: ) but I didn't find a way to create the first user.

Is it possible ?

Thanks !

**Comment by strangeman** [comment]
Hi! Take a look on this: https://github.com/ansible-semaphore/semaphore/issues/333

**Comment by Niflou** [comment]
Nice thank you ! 

I missed that post.
