### ISSUE TITLE
Feature: Signal notifications

### ISSUE THREAD

**Issue by morph027** [ansible-semaphore/semaphore#349]
We are using Signal rather than Telegram. There's this great project: https://github.com/janimo/textsecure we're using for our monitoring and so on...

What do you think about implementing it?

By the way, thanks for your great project!

**Comment by matejkramny** [comment]
We should also add Slack & webhooks in addition.

**Comment by twhiston** [comment]
I'd like to make a generic notification interface for this that we can start adding providers to, we would also like slack integration

**Comment by megakoresh** [comment]
> I'd like to make a generic notification interface for this that we can start adding providers to, we would also like slack integration

Yes, I think there is diminishing returns in adding multiple different providers. Better to add one generic notification interface to allow templating any generic http(s) request. Then it can be used to integrate with any external service. We use our own microservice for example. Ansibel Tower has this sort of functionality.

**Comment by cerberek** [comment]
@fiftin is there done general notification interface? I would like to send notifications to slack
