### ISSUE TITLE
Docker-Compose arguments

### ISSUE THREAD

**Issue by tmidi** [ansible-semaphore/semaphore#351]
What are the environment arguments variables accepted when running semaphore_api container?
a whole list would be appreciate.
Thanks

**Comment by twhiston** [comment]
check https://github.com/ansible-semaphore/semaphore/blob/develop/scripts/docker-startup.sh

**Comment by xagaba** [comment]
File it's missing, any location with this info ?

**Comment by twhiston** [comment]
https://github.com/ansible-semaphore/semaphore/blob/develop/deployment/docker/common/semaphore-wrapper
