### ISSUE TITLE
Enhancement : default credentials / initial credentials

### ISSUE THREAD

**Issue by x-drum** [ansible-semaphore/semaphore#354]
Hi,
default credentials or the ability to create an administrative account in a non-interactive  way (currently available only with command line interactive setup), will be very useful with unattended installations (eg: using CFEs like ansible, chef, etc.).

**Comment by matejkramny** [comment]
Agree, maybe we can also do setup from the web interface instead of the CLI. It's a much better user experience

**Comment by fiftin** [comment]
Done. You can use CLI:

```bash
semaphore user add --config ./config.json --admin --login admin --email=admin@example.com --name Admin --password=12345
```

More info by command:

```
semaphore user --help
```
