### ISSUE TITLE
Does Semaphore with Ansible roles?

### ISSUE THREAD

**Issue by pnayak** [ansible-semaphore/semaphore#36]
Glad to see this alternative to Tower... great work....

Before I dive in, was wondering if this worked with roles and/or with Ansible's standard project/folder structures... so if the Github repo has playbooks which reference roles that are also stored in that repo?

Thanks

**Comment by matejkramny** [comment]
Basically all this tool does is provide a web interface to running `ansible-playbook` command. If you specify which roles to execute in a playbook file, it should be all good for you.

See [this file](https://github.com/ansible-semaphore/semaphore/blob/master/lib/runner.js#L193) for all the options it provides to `ansible-playbook`.
