### ISSUE TITLE
unable to install from contribution guide

### ISSUE THREAD

**Issue by akhilbatra898** [ansible-semaphore/semaphore#361]
While Installing 

got this error at the following command
`go get ./... github.com/cespare/reflex github.com/jteeuwen/go-bindata/... github.com/mitchellh/gox
package context: unrecognised import path "context" (import path does not begin with hostname)
`
Also, node requires package.json and other files to install async 
please help

**Comment by matejkramny** [comment]
try getting them individually, not sure what file imports `"context"`.

Is there more log output?

We can make a package.json or yarn file. I believe node installs packages in your home directory and should be working.

**Comment by akhilbatra898** [comment]
No more log output. I am trying  to find a way out.

For node yes it is asking for package.json.

**Comment by twhiston** [comment]
cant reproduce
