### ISSUE TITLE
bindata: Input path 'config.json' is not a directory.

### ISSUE THREAD

**Issue by Oleksandr1** [ansible-semaphore/semaphore#362]
Hi! 
I used your manual from CONTRIBUTING.md
I installed dependencies, set up config.json and database.
When I run ' go-bindata -debug -o util/bindata.go -pkg util config.json db/migrations/ $(find public/* -type d -print) ' I get the error 'bindata: Input path 'config.json' is not a directory.'
What did I do wrong?

**Comment by matejkramny** [comment]
Create `config.json` as the error specifies.

Here's an example:

```
{
    "mysql": {
        "host": "127.0.0.1:3306",
        "user": "root",
        "pass": "",
        "name": "semaphore"
    },
    "session_db": "127.0.0.1:6379",
    "port": ":3000"
}
```

**Comment by Oleksandr1** [comment]
Hi!
Maybe it will be useful for you. 
I found a solution. I used go-bindata from the Ubuntu repository and it showed this error. But I replaced it with compiled from sources code(git@github.com:jteeuwen/go-bindata.git) and now it's work good.
