### ISSUE TITLE
Concurrent deploys

### ISSUE THREAD

**Issue by Natanande** [ansible-semaphore/semaphore#365]
In our use case, we make slightly below 10 000 deploys each month. When using semaphore, we deploy to prod and test servers in different projects. We currently have to wait to make deploys to production servers if someone is deploying to a test server or vice versa. This becomes a problem, especially when the job takes long time because it triggers server restarts or similar, halting the development process. It would also be nice to be able to deploy to different test servers simultaneously if one knows that there's no collision for the hosts.

**Comment by Echobob** [comment]
Merged in #366
