### ISSUE TITLE
Link broken for nginx configuration in Installation guide

### ISSUE THREAD

**Issue by akhilbatra898** [ansible-semaphore/semaphore#369]
The link given for nginx.conf is [](https://github.com/ansible-semaphore/semaphore/blob/master/Deploy/proxy/nginx.conf)

It is broken now. Please check and update.

**Comment by yujunz** [comment]
It seems to be moved to https://github.com/ansible-semaphore/semaphore/blob/master/scripts/proxy/nginx.conf

You may send a PR to correct the document @akhilbatra898
