### ISSUE TITLE
Need to specify command-line argument equivalents

### ISSUE THREAD

**Issue by gdavis2** [ansible-semaphore/semaphore#37]
The functionality at this point is great, the only thing that prevents me from using it is that I can't specify passwords for privilege escalation (or I must allow paswordless-sudo escalation, which is a non-starter). Is this on the roadmap?

**Comment by matejkramny** [comment]
Thats interesting. Enabling projects to customise the ansible command would be helpful in terms of being able to customise the environment..

It wasn't in the roadmap but i'll add it.

**Comment by matejkramny** [comment]
Possible, and to the extent of rewriting semaphore's default arguments (v2-alpha)
