### ISSUE TITLE
Wrong time in Project activity list

### ISSUE THREAD

**Issue by strangeman** [ansible-semaphore/semaphore#372]
Looks like typo in date format - it shows month instead of minutes

![project dashboard semaphore](https://user-images.githubusercontent.com/1083576/26856895-1bc67a46-4b6a-11e7-82b0-a1854473784d.png)

**Comment by matejkramny** [comment]
Good catch. Let's fix that..

**Comment by strangeman** [comment]
@matejkramny assign it to me, please, I'll fix it tomorrow

**Comment by matejkramny** [comment]
np, thanks!
