### ISSUE TITLE
Roles managment

### ISSUE THREAD

**Issue by frimdo** [ansible-semaphore/semaphore#377]
Feature Idea:
I did not find any way to let semaphore manage roles. What about adding a new menu, where you would define your repos with your roles, and semaphore would fetch/update those roles when needed (same as playbooks)

**Comment by strangeman** [comment]
Semaphore supports `requirements.yml` file (https://galaxy.ansible.com/intro#download-advanced). I think, managing roles as a Code is a much better way than clicking in a web interface.

**Comment by frimdo** [comment]
That is great! But you need to access bash of the server to edit `requirements.yml` and than to run `ansible-galaxy install -r requirements.yml`
It would be better to edit the file from web GUI and than run the command with some button...

**Comment by strangeman** [comment]
Semaphore runs it automatically when task is launched. File stored in playbooks repo, in `roles` folder.

**Comment by frimdo** [comment]
Oh. Ok. My bad. Thank you :-)
