### ISSUE TITLE
Feature: Allow omitting inventory

### ISSUE THREAD

**Issue by mckelvin** [ansible-semaphore/semaphore#378]
In my use case, The inventory file is existed (as `hosts.ini`) in my ansible playbooks repository, and there's also a ansible.cfg with following content:

```cfg
[defaults]
inventory = hosts.ini
```

So there's no need to add inventory on semaphore again for me but I have to. I wish there's an options for me to omit inventory on semaphore.

**Comment by strangeman** [comment]
duplicates https://github.com/ansible-semaphore/semaphore/issues/328
