### ISSUE TITLE
Use the UI to prompt for user and sudo/ssh password

### ISSUE THREAD

**Issue by joernott** [ansible-semaphore/semaphore#379]
For security reasons, I am not allowed to use passwordless sudo and the ssh connect to the remote machines should ideally happen with my user, not a shared "semaphore" user.

I have seen that there is an option "Extra CLI Arguments", but I would like to use "-K" (--ask-become-pass) and -u to specify the remote user and the password for sudo (ideally using the user name which is using the UI). Is there a way to achieve this kind of behaviour?

**Comment by matejkramny** [comment]
Not currently, however there are ideas in #85, #115, #113..

**Comment by joernott** [comment]
I have been thinking about how all these can be solved in a consistent way. I believe,a valid approach would be:
Making use of variables solves a lot of problems (e.g. setting usernames, passwords). Host specific variables can already be set in inventories. There should be a way to pre-define variables from the context (e.g. username, password from the currently logged in user (useful for ask_become_pass when using LDAP). We should have a way of setting variables (or telling semaphore to prompt for them) in task templates. We also should have a way of specifying a users ssh key (including a prompt for the keys password) and a user specific vault. Of course, it is the responsibility of the user to actually make sure, that the vault contains the information needed.

Thoughts:
- Passing ansible variables via "--extra-vars="@extravars_file" is preferable over specifying them at the commandline and thus exposing them to the process list. There is no extra-var for the vault password though, so we have to use the vault password file.
- Vault reduces the number of passwords to be sent to one, the rest can be set from the user specific variables
- We either have to remember passwords when logging in or have to provide them on every run of a task
- Vault password files should be deleted after running the task. Ideally they should be stored in a folder which can be mounted as tmpfs so that no traces on disk remain

I have forked the project and I will try to implement the above. At the moment, it looks like a rather large feature. Lets see what happens
RFC

**Comment by matejkramny** [comment]
@joernott semaphore already utilises `--extra-vars` and passes the json environment.

You're describing a number of features:

- Passing additional envirnoment variables to ansible
- Semi-interactive terminal ?
- Vault enhancements

Matej

**Comment by joernott** [comment]
Hello Matej,

I have seen, that you already use extra-vars. But currently, these are defined in a template and are open to all users.

I am currently in a project, where we process sensitive data and have to fulfill a set of requirements. This includes an audit trail on every server (Who did what when) and forbids global shared users and passwordless sudo and ssh keys without passwords. ssh passwords and sudo passwords can be passed as variables, however, having a global "semaphore" user is out of the question. 

Having a set of "personal" variables attached to the user makes it possible that every admin can define his own ansible_user once and doesn't need to write a json blurb every time he runs a playbook.

Storing passwords (for sudo/admin users) in plaintext (e.g. in extra-vars) is an absolute no-go, as is storing them in an encrypted way, where it is quite easy for one admin to get the others passwords. That is where things become tricky, when you don't want to use a HSM. This is where vault comes into the game.

Instead of using an interactive terminal, I'd rather pass the passwords via a vars file (command line parameters are visible in the process list, environment variables can be snooped, too). 

When using a personal vault for passwords, the admin needs to unlock that vault (e.g. on login or when scheduling the playbook). As there may be some time between scheduling and running the playbook, we need to pass that information somehow. Designing that part is the most difficult thing at the moment, as it is out of question to store plaintext passwords somewhere in the tasks table.

At the moment, my solution would be to have a global vault in which the sensitive data is temporarily stored/encrypted until the task runs (or is cancelled) and that information is no longer needed. At that point in time, it is discarded. This would minimize the time where other people with admin access could possibly gain knowledge of the users credentials.

I hope, that by next week, I will have some code for you to review.

**Comment by joernott** [comment]
Hello Matej,
I have just pushed my changes to https://github.com/joernott/semaphore/tree/feature/user-vault. As this is still work in progress, I have not yet created a pull request.

Main changes are:
- Users can have personal variables (e.g. ansible_become_user) and a personal vault stored in the user object/table. The vault should be created using ansible-vault using the same password as for the login to semaphore and the content of the encrypted file should then be pasted into the textarea.
- A in-memory cache is used to remember passwords of logged in users
- When defining access keys, these keys can be marked as public (keys are accessible by anyone) or you can specify an owner. Keys belonging to an owner are not shown to other users, however, you can change a keys owner to public or to another user.
- When defining a template, you can choose to allow user variables and the user specific vault. This will result in writing them to files and adding appropriate command arguments
- When defining a template, instead of defining a fixed ssh key to run that template, you can choose a "user specific" key. Instead of using the global semaphore key, a key for the logged in user will be fetched and used to connect. This is not yet fully implemented, but will be done in the next few days depending on my work load.

**Comment by matejkramny** [comment]
Hi Joern, I'll review and test

**Comment by twhiston** [comment]
@joernott do you still need this feature? Did you do any more work on this? If so can you make a W.I.P PR for the feature so we can review it. Thanks!

**Comment by joernott** [comment]
I did some work on this but I need to resolve some merge conflicts resulting from upstream changes first. As I am now working for a different project, I am limited to work on this in my free time. So it may take me a few days to get this done.

**Comment by fiftin** [comment]
![image](https://user-images.githubusercontent.com/914224/133695409-ab069a6f-eaab-4731-a974-94c0c142119c.png)


Sudo password can be configured in the Inventory settings. Available in v2.7.20.

https://github.com/ansible-semaphore/semaphore/releases/tag/v2.7.20

**Comment by Akshay-Hegde** [comment]
Any solution in 2026 like awx/tower prompt for private key passphrase and prompt for password at runtime ?

Or any alternate solution to manage passphrase, password and vault password at runtime instead of storing permanently in database
