### ISSUE TITLE
Question on use of roles

### ISSUE THREAD

**Issue by mickengland** [ansible-semaphore/semaphore#38]
Trying to run a playbook that references a role I get the following error:

Starting play run.yml.
ERROR: cannot find role in /root/playbook_5605429dd87177010043a335/roles/achaussier.apache or /root/playbook_5605429dd87177010043a335/achaussier.apache or /etc/ansible/roles/achaussier.apache
/etc/ansible/roles/achaussier.apache exists on the semaphore host.

I included a roles directory in my unusable-apache reposthat the job is calling and the job ran successfully.
```
My playbook contains:
- hosts: all
  remote_user: mick
  sudo: yes
  remote_user: mick
  roles:
    - achaussier.apache
```
What is the correct way to reference that role in semaphore so I don’t have to duplicate roles in each playbook repository?

**Comment by matejkramny** [comment]
Currently no way. V2-alpha has capability to specify command-line arguments before running a playbook. You could tell ansible to run the roles needed using this feature.
