### ISSUE TITLE
Task Template Concurrency on Roadmap?

### ISSUE THREAD

**Issue by JimFicarra** [ansible-semaphore/semaphore#380]
As I was testing Ansible Semaphore, it seems that task template concurrency is not supported (e.g. the ability to execute multiple task templates simultaneously even when using different inventories, or GHE projects.)  Instead, the jobs queue up and run sequentially.

I did not see this feature on the road map? I did not see it.

Thanks in advance

**Comment by matejkramny** [comment]
Is not in roadmap but this PR #366 will be merged once reviewed which will allow for concurrent tasks.

**Comment by Echobob** [comment]
Merged in #366, let us know if you're still having issues.
