### ISSUE TITLE
How can I change username that ansible use ?

### ISSUE THREAD

**Issue by rangsan** [ansible-semaphore/semaphore#382]
It seems like ansible connect to remote host using "semaphore" user. I want to use different user. How can I do that ?

Thank you.

**Comment by matejkramny** [comment]
You can specify the ssh user inside the playbook or inventory.

Playbook:

```
- hosts: x
  remote_user: root
```

**Comment by rangsan** [comment]
Is there a way to make it as semaphore configuration as default without specify remote_user in playbook ?

I did specify "remote_user = ansible" in ansible.cfg but still can't connect.  How do semaphore work with ansible.cfg ?
