### ISSUE TITLE
UI not loading / Assets not loading

### ISSUE THREAD

**Issue by chavenor** [ansible-semaphore/semaphore#383]
I used the Wiki to install but I'm not sure it worked? 

The login page seems to just be the un-rendered template?   

How can I troubleshoot this?   Where are the logs?

**Comment by matejkramny** [comment]
Could be the release, but it has been tested it and it is working well.

Can you post the output in the browser?

**Comment by channing342** [comment]
I just upgrade to 2.4.0  facing this problem

**Comment by zateevas** [comment]
i think i have similar problem. I has this problem only with 2.4.0, version 2.3.0 running succesfull. 


![2017-06-30 12-52-03](https://user-images.githubusercontent.com/20357079/27730755-270dab64-5d93-11e7-9c06-053b7fde8295.png)

**Comment by channing342** [comment]
@zateevas  can you  paste you config file  semaphore_config.json  "web_host" setting 

--->　"web_host": "http://10.22.13.199:3000/",

**Comment by matejkramny** [comment]
Hmm maybe it hasn't built properly. I've taken it down and will reupload later today.

@channing342 web host is for emailing and alerts only. The web UI is unaffected by this

**Comment by channing342** [comment]
@matejkramny  really ?  , I just change  "web_host" is normal now , LOL

**Comment by matejkramny** [comment]
Hmm I thought that's the case. Might be as you say, i can't tell right now. Either way there's a bug if it doesn't load the UI

**Comment by zateevas** [comment]
@channing342 
{
        "mysql": {
                "host": "mysql:3306",
                "user": "root",
                "pass": "*******",
                "name": "semaphore"
        },
        "port": "",
        "tmp_path": "/etc/semaphore",
        "cookie_hash": "****************************",
        "cookie_encryption": "**************************************",
        "email_alert": true,
        "email_sender": "semaphore@******",
        "email_host": "**********",
        "email_port": "2529",
        "web_host": "http://localhost:3000",
        "ldap_enable": false,
        "ldap_binddn": "",
        "ldap_bindpassword": "",
        "ldap_server": "",
        "ldap_needtls": false,
        "ldap_searchdn": "",
        "ldap_searchfilter": "",
        "ldap_mappings": {
                "dn": "",
                "mail": "",
                "uid": "",
                "cn": ""
        },
        "telegram_alert": false,
        "telegram_chat": "",
        "telegram_token": ""
 }

**Comment by channing342** [comment]
@zateevas   if you want fix it 2.4.0 now , you can change your config
"web_host": "http://localhost:3000",  --->  "web_host": "http://**yourserverip**:3000",

root case still need @matejkramny  investigation, 
@matejkramny thanks for development this awesome tool , and TGIF

**Comment by zateevas** [comment]
@channing342

this don't work for me(

in mysql logs i see this:
2017-06-30T10:18:28.897114Z 10 [Note] Aborted connection 10 to db: 'semaphore' user: 'root' host: '172.17.0.2' (Got an error reading communication packets)
2017-06-30T10:21:03.851831Z 14 [Note] Aborted connection 14 to db: 'semaphore' user: 'root' host: '172.17.0.2' (Got an error reading communication packets)
2017-06-30T10:22:03.256571Z 15 [Note] Aborted connection 15 to db: 'semaphore' user: 'root' host: '172.17.0.2' (Got an error reading communication packets)

**Comment by chavenor** [comment]
The host name changed worked for me.

**Comment by zateevas** [comment]
May be this case don't work for me because i use semaphore in container? @chavenor @channing342 How do you use semaphore?

**Comment by chavenor** [comment]
Outside of the docker container.

**Comment by chavenor** [comment]
Ok so when trying to run my first task on 2.4.0 it hung up and won't restart.   I'm not familiar with go-lang but are there any logs to see what happened?  

I tried to re-install but noticed that 2.4 isn't around anymore 

I just tried installing 2.3.0 and that dosn't seem to work either the ```nohup ./semaphore -config /tmp/semaphore/semaphore_config.json``` command just sits there and I can't access the webpage from port 8010. 

Is this tool considered production ready?

**Comment by channing342** [comment]
@zateevas   I am not using not using  container

**Comment by matejkramny** [comment]
If you omit `web_host` the UI works. If it is set, the UI sets the "base" path and all resources like css/js are expected to load from that url.

Related to #350.

**Comment by manishalankala** [comment]
My grafana also use same  default port 3000

after service start i see the error

How can i change this
