### ISSUE TITLE
Github Pull Request Not Working?

### ISSUE THREAD

**Issue by chavenor** [ansible-semaphore/semaphore#386]
I still have yet to get a task template from github it's constantly saying it dosn't exist yet when I run the command line in the terminal (no password / with SSH) it works. 

Other questions... 
- Can I use local files instead of going to github for the Task Templates? 
- When entering keys into the semaphore does it matter if there are  trailing whitepaces?   Does it matter if the START and STOP txt for the private key is included?
- Changing keys via UI causes error with no human readable reason why?

**Comment by matejkramny** [comment]
> Can I use local files instead of going to github for the Task Templates?

You can use local git repositories. It needs to be a "bare" repository

> When entering keys into the semaphore does it matter if there are trailing whitepaces? Does it matter if the START and STOP txt for the private key is included?

Is same as if you edited the keys yourself on the command line.

> Changing keys via UI causes error with no human readable reason why?

This does looking into. The UI will not say anything, and the API gives back a HTTP `400` with an error message.
