### ISSUE TITLE
semaphore 2.4.1 is broken

### ISSUE THREAD

**Issue by oguzy** [ansible-semaphore/semaphore#388]
I already installed semaphore with a local user and i am attaching what i got when i tried to open the login page
![screen shot 2017-07-03 at 15 27 38](https://user-images.githubusercontent.com/97524/27792315-cd2d85f8-6001-11e7-8a73-743d6d2045c3.png)

**Comment by matejkramny** [comment]
Have you set the web host parameter in config?

**Comment by psywhale** [comment]
If you are using a reverse proxy with nginx or whatever. Set your web host parameter to the outside facing url.

**Comment by ndeixonne** [comment]
I confirm that solves this trouble :)

**Comment by matejkramny** [comment]
Yes correct. I will think about making this more obvious or documented
