### ISSUE TITLE
Implement a System Tracking

### ISSUE THREAD

**Issue by jcmartins** [ansible-semaphore/semaphore#389]
Is it possible implement a feature to check a manual change in the server(linux instance) and semaphore run automatic the playbook again to force the version that semaphore have?

It's very usual to security!!!

tks
joao

**Comment by matejkramny** [comment]
not sure I understand what you mean. You want to check that the system hasn't been tampered with?

**Comment by jcmartins** [comment]
Yes, it's good to compliance.

**Comment by matejkramny** [comment]
I'm not sure how semaphore could do this, aside from verify that the binary is "official" and not been modified.

The function of this tool is not to maintain a state of the system it runs on and I think doing this would require a huge side step in a different direction.

**Comment by jcmartins** [comment]
it't not about semaphore binary.
It's  about a playbook versions management.
the intention is check if semaphore and a node(linux instance) have the same playbook version and send 
alert case the version is different.
PS: Chef-server have this feature.

**Comment by matejkramny** [comment]
I see, maybe I misunderstood. Semaphore does a `git pull` on the playbook on every run, is this what you're describing?
