### ISSUE TITLE
Run semaphore as normal user

### ISSUE THREAD

**Issue by brodul** [ansible-semaphore/semaphore#39]
Hi,

I really like semaphore, but the problem is that I don't run my infrastructure in docker and I don't want to run semaphore as `root` user. 

It would be great if we could run semaphore as a normal user eg. `semaphore` .

**Comment by matejkramny** [comment]
Its technically ok to run anywhere as any user, the only issue at the moment is some hardcoded paths that stores the repositories in `/root/`.

**Comment by matejkramny** [comment]
Im going to label this as a bug since it isn't considered a feature and behaves in a way nobody really wants.
