### ISSUE TITLE
2.4.1 using a ssh jump host is not working

### ISSUE THREAD

**Issue by psywhale** [ansible-semaphore/semaphore#391]
[Ansible jump host howto](http://docs.ansible.com/ansible/faq.html#how-do-i-configure-a-jump-host-to-access-servers-that-i-have-no-direct-access-to)

In 2.3.0 this worked with my group_vars for those hosts needing a jump-host. Now those hosts are unreachable. 
Do I need to configure a separate environment?

**Comment by matejkramny** [comment]
Interesting. Could this be related to the CLI parameters we pass onto ansible?

**Comment by olakunleoladimeji** [comment]
same issue here

**Comment by fiftin** [comment]
Hi @olakunleoladimeji Could you provide more details.
