### ISSUE TITLE
[New feature] Cancel a running playbook

### ISSUE THREAD

**Issue by ndeixonne** [ansible-semaphore/semaphore#392]
Hey,

I really appreciate Semaphore. It could be awesome if we could cancel a running playbook after launching it. Indeed, sometimes, we might launch it by error and we want to stop it.

At the beginning, I thought it was the delete button on bottom right that could do that when a playbook is running but clicking on this button just shutdown the server directly.

**Comment by matejkramny** [comment]
👍

**Comment by fiftin** [comment]
Done in v2.7.5

https://github.com/ansible-semaphore/semaphore/releases/tag/v2.7.5
