### ISSUE TITLE
How to setup semaphore programatically

### ISSUE THREAD

**Issue by kinghrothgar** [ansible-semaphore/semaphore#399]
It is unclear to me what all running 'semaphore -setup' does.  Is all I need to do is play the config file and run 'semaphore -migrate' or are there other things I need to do.

**Comment by strangeman** [comment]
Look here:

- https://github.com/ansible-semaphore/semaphore/issues/194#issuecomment-294479361
- https://github.com/ansible-semaphore/semaphore/issues/333

**Comment by matejkramny** [comment]
`semaphore -setup` does:

- Generation of config file
- Create the first user w/ hashed password

Migrations are now run on every startup. You can run `semaphore -hash <pwd>` which will output the hash, but then it needs to be inserted to the database manually. This is something that will be improved (on roadmap).
