### ISSUE TITLE
Manual installation

### ISSUE THREAD

**Issue by irraz** [ansible-semaphore/semaphore#4]
Hello,

I need help installing without docker and without vagrant . 
I have a production server with Ansible and only wish to apply the web layer " semaphore" . You can help with installation?

Regards

**Comment by matejkramny** [comment]
Hi @irraz, the runner is embedded (and strongly coupled) into the app, so it will execute ansible tasks on the system the app is ran on.

It may not be ideal to run w/o Docker or Vagrant as it writes to `/root/.ssh` and stores playbooks in `/root/playbook_`. It may also be insecure as playbooks can execute tasks locally.

As to what to do to install semaphore, see this playbook. Vagrant runs this to provision the system. https://github.com/ansible-semaphore/semaphore/blob/master/playbooks/playbook.yml

**Comment by irraz** [comment]
Hi,

In the production environment our ansible server does not go directly to the internet so the deploy of vagrant and docker fail in the process.

The playbook is well , I hope to have better luck , although instructions would be desirable :)

Thank You

**Comment by matejkramny** [comment]
@irraz it is probably failing because it has no internet. The app downloads npm & bower dependencies during install.

Maybe download all the dependencies on a similar system (eg docker image) and then transport the whole directory to your production system?

**Comment by irraz** [comment]
Thanks , I'll try that , I acknowledge that I have experience in methodology devops I'm a sysadmin proble dated and old , who has not yet been recycled :-)

**Comment by matejkramny** [comment]
@irraz the new docker image should provide a very easy & convenient install path

**Comment by kantmakm** [comment]
Here's a post on installing semaphore without a VM for those that need it:  http://code-complete.com/code/?p=40

**Comment by matejkramny** [comment]
Thanks! We'll feature it in the readme

**Comment by geonetsoft** [comment]
code-complete.com not working ...could be nice if another locations for howtos ...like howtoforge.
i`m in a similar situation.

im trying now on a laptop with opensuse .

**Comment by kranjith490** [comment]
hey guys,am trying to installing semaphore using code-complete.com,but when am trying to setup it throws the following error:
 Database migrations failed!
 Error 1067: Invalid default value for 'created'
anybody faced this issue?
kindly help me out to work with it.
ping me at kranjith490@gmail.com
