### ISSUE TITLE
Semaphore exits with no error message or error code when port wrong

### ISSUE THREAD

**Issue by kinghrothgar** [ansible-semaphore/semaphore#401]
I'm not sure what's going on or how to debug this. I read through the code and the only way I can see for it to exit before it prints "Migrations Finished" is if an error is returned from MigrateAll() which should cause a panic.

```bash
[semaphore@wilber ~]$ /usr/bin/semaphore -config /home/semaphore/semaphore_config.json
Semaphore 2.4.1
Port 3000
MySQL semaphore@127.0.0.1:3306 semaphore
Tmp Path (projects home) /home/semaphore
Checking DB migrations
[semaphore@wilber ~]$ echo $?
0
```

UPDATE: It appears it is because the port configuration requires a colon in front of it. This exitting without any error makes it very difficult to debug.

**Comment by matejkramny** [comment]
Hmm that's quite easy to miss this, and probably just as easy to prevent.

I'll tag this as an improvement and have this fixed hopefully by the next release.

**Comment by eRadical** [comment]
Saved by this bug report... before (re)generating  semaphore_config.json! Thanx @kinghrothgar
