### ISSUE TITLE
update semaphore from 2.3.0 to 2.4.1 failed the web UI.

### ISSUE THREAD

**Issue by rangsan** [ansible-semaphore/semaphore#403]
Today I upgrade semaphore from 2.3.0 to 2.4.1 . The UI is broken as you can see. 
![2017-07-25 15_18_42-semaphore](https://user-images.githubusercontent.com/10152146/28562514-bb3f4870-714c-11e7-8d59-0bf891208ac9.png)

It seems the database didn't migrate properly. I just replace the latest semaphore binary into /usr/bin/ and restart the service. Could someone please help here?

Log here
...
Semaphore 2.4.1
Port :3000
MySQL semaphore@127.0.0.1:3306 semaphore
Tmp Path (projects home) /home/semaphore
Checking DB migrations

**Comment by strangeman** [comment]
Please, set `web_host` parameter in config

**Comment by strangeman** [comment]
```
	"web_host": "http://your_semaphore_installation.com",
```

**Comment by rangsan** [comment]
@strangeman Thank you very much. It works.

**Comment by strangeman** [comment]
@rangsan please, close the issue if it working as expected
