### ISSUE TITLE
ldap enable debugging

### ISSUE THREAD

**Issue by rangsan** [ansible-semaphore/semaphore#404]
I still can't log in via my AD account when ldap is enabled. Is there any way to open debug log? So I can get more info what I've missed. All setting works when I use ldapbrowser tool for ldap testing. Below is the config and log when I login.

 > 403  17:29:57       7.614µs |   GET     /api/user
 400  17:30:05     802.695µs |   POST    /api/auth/login
 200  17:30:43    2.105007ms |   GET     /api/users

> "ldap_enable": true,
        "ldap_binddn": "bindac@it.org",
        "ldap_bindpassword": "secret",
        "ldap_server": "ad.it.org:389",
        "ldap_needtls": false,
        "ldap_searchdn": "OU=infra,OU=IT Users,DC=it,DC=org",
        "ldap_searchfilter": "(&(sAMAccountName=%s)(memberOf=CN=infra,OU=Resources,DC=it,DC=org))",
        "ldap_mappings": {
                "dn": "cn",
                "mail": "userPrincipalName",
                "uid": "sAMAccountName",
                "cn": "cn"
        },

**Comment by strangeman** [comment]
Some info arrives in the main semaphore log:

```
июл 25 14:50:24 dev5 semaphore_linux_amd64[17145]:  403  14:50:24       5.479µs |   GET     /api/user
июл 25 14:50:32 dev5 semaphore_linux_amd64[17145]: time="2017-07-25T14:50:32+03:00" level=info msg="LDAP Result Code 50 "Insufficient Access Rights": INSUFFICIENT_ACCES
июл 25 14:50:32 dev5 semaphore_linux_amd64[17145]: baseDn : 'ou=users,dc=crowd'
июл 25 14:50:32 dev5 semaphore_linux_amd64[17145]: filter : '(|(0.9.2342.19200300.100.1.1=a.markelov)(2.5.4.0=referral))'
июл 25 14:50:32 dev5 semaphore_linux_amd64[17145]: scope : whole subtree
июл 25 14:50:32 dev5 semaphore_linux_amd64[17145]: typesOnly : false
июл 25 14:50:32 dev5 semaphore_linux_amd64[17145]: Size Limit : no limit
июл 25 14:50:32 dev5 semaphore_linux_amd64[17145]: Time Limit : no limit
июл 25 14:50:32 dev5 semaphore_linux_amd64[17145]: Deref Aliases : never Deref Aliases
июл 25 14:50:32 dev5 semaphore_linux_amd64[17145]: attributes : 'dn', 'mail', 'uid', 'cn'
июл 25 14:50:32 dev5 semaphore_linux_amd64[17145]: : ERR_5 Attempted operation SEARCH_REQUEST by unauthenticated caller."
июл 25 14:50:32 dev5 semaphore_linux_amd64[17145]:  400  14:50:32   549.97994ms |   POST    /api/auth/login
```

**Comment by rangsan** [comment]
@strangeman  I started the process via nohup command line.  There's no others log in /var/log/ but only nohup which seems to be only access log.  Is there any way to enable debug mode ?


>nohup semaphore -config /home/semaphore/semaphore_config.json &

**Comment by strangeman** [comment]
```
If standard output is a terminal, append output to 'nohup.out' if possible, '$HOME/nohup.out' otherwise.  If standard error is a terminal, redirect it to standard output.  To save output to FILE, use 'nohup COMMAND > FILE'.
```

**Comment by rangsan** [comment]
@strangeman Thank you. The ldap authentication works now , I don't know why just restart the service.

**Comment by strangeman** [comment]
Great! :) Please, close the issue.
