### ISSUE TITLE
when a host can not access, semaphore will hang

### ISSUE THREAD

**Issue by jffree** [ansible-semaphore/semaphore#408]
Computer node1 has none authority to access node2, when I run task on semaphore, semaphore will hang。。。。。

`09:35:41: 
09:35:41: PLAYBOOK: one ******************************************************************
09:35:41: 1 plays in one
09:35:41: 
09:35:41: PLAY [test] ********************************************************************
09:35:42: META: ran handlers
09:35:42: 
09:35:42: TASK [install httpd] ***********************************************************
09:35:42: task path: /tmp/semaphore/repository_1/one:5
09:35:42: Using module file /usr/lib/python2.7/site-packages/ansible/modules/commands/command.py
09:35:42: <172.16.100.16> ESTABLISH SSH CONNECTION FOR USER: root
09:35:42: <172.16.100.16> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/tmp/semaphore/access_key_1"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/semaphore/.ansible/cp/adf3b6743f 172.16.100.16 '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''`
How could I solve this problem?

**Comment by jffree** [comment]
I hope semaphore will tell the error, bug not hang......
So I will not reboot semaphore

**Comment by jffree** [comment]
When I use ansible-playbook, it show that:
`[semaphore@node1 ~]$ ansible-playbook -i /tmp/semaphore/inventory_7 /tmp/semaphore/repository_1/one

PLAY [test] ************************************************************************************************************************************************************************************

TASK [install httpd] ***************************************************************************************************************************************************************************
The authenticity of host '172.16.100.16 (172.16.100.16)' can't be established.
ECDSA key fingerprint is b7:83:38:89:2d:84:cb:bf:33:47:83:79:3d:c5:cf:9d.
Are you sure you want to continue connecting (yes/no)? yes
fatal: [172.16.100.16]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Warning: Permanently added '172.16.100.16' (ECDSA) to the list of known hosts.\r\nPerm
ission denied (publickey,gssapi-keyex,gssapi-with-mic,password).\r\n", "unreachable": true}
        to retry, use: --limit @/tmp/semaphore/repository_1/one.retry

PLAY RECAP *************************************************************************************************************************************************************************************
172.16.100.16              : ok=0    changed=0    unreachable=1    failed=0 `

**Comment by strangeman** [comment]
Semaphore doesn't support dialog interactions, so you need to accept key fingerprint before, or set up your SSH client to accept all fingerprints by default (`StrictHostKeyChecking no`)

**Comment by jffree** [comment]
Where I set this option?

**Comment by strangeman** [comment]
In your ansible.cfg - https://stackoverflow.com/questions/41324572/ansible-ecdsa-key-fingerprint-prompt

**Comment by jffree** [comment]
Will you add dialog interactions support for semaphore ? This will be more convenient.

**Comment by strangeman** [comment]
PR's are welcome :)

**Comment by jffree** [comment]
I know little about go .......
Sorry....
