### ISSUE TITLE
Opt-in analytics

### ISSUE THREAD

**Issue by matejkramny** [ansible-semaphore/semaphore#41]
Thinking of starting up a piwik instance and giving Anonymous read access for anyone interested.

I want to ask what the users think of this.

It would be opt-in. You would get a dialog when its introduced, asking if you want to enable anonymous data collection and a link where the aggregates can be viewed.

Couple of points regarding privacy:
- No personal/company identifiable information would be collected
- Last ipv4 segment anonymised

What would be collected:
- Pages visited
- Possibly number of playbooks/keys/etc created

It would help analyse how semaphore is used.

**Comment by twhiston** [comment]
@strangeman any objection to me closing this? This is not something I really want to implement

**Comment by strangeman** [comment]
I don't need this, I don't think that we will analyze this data. :)
