### ISSUE TITLE
I buils semaphore mysef, but it is useless

### ISSUE THREAD

**Issue by jffree** [ansible-semaphore/semaphore#412]
First, when I run `semaphore -setup`, there is an error:

`[root@node1 semaphore]# ./cli/semaphore_linux_amd64 -setup
Cannot Find configuration! Use -c parameter to point to a JSON file generated by -setup.

 Hint: have you run `-setup` ?`

Second,  when I run `./cli/semaphore_linux_amd64 -setup -config /tmp/semaphore/semaphore_config.json` there is an db error:

`		"cn": ""
 	},
 	"telegram_alert": false,
 	"telegram_chat": "",
 	"telegram_token": ""
 }

 > Is this correct? (yes/no): yes
 Running: mkdir -p /tmp/semaphore..
 Configuration written to /tmp/semaphore/semaphore_config.json..
 Pinging db..

 Running DB Migrations..
Checking DB migrations
Executing migration v0.0.0 (at 2017-08-02 10:46:06.81903805 +0800 CST)...
panic: asset: Asset(db/migrations/v0.0.0.sql): Asset db/migrations/v0.0.0.sql can't read by error: Error reading asset db/migrations/v0.0.0.sql at /Users/m/p/semaphore/db/migrations/v0.0.0.sql: open /Users/m/p/semaphore/db/migrations/v0.0.0.sql: no such file or directory

goroutine 1 [running]:
github.com/ansible-semaphore/semaphore/util.MustAsset(0xc4201320e0, 0x18, 0x5, 0xa1a2ce, 0x4)
	/root/goproj/src/github.com/ansible-semaphore/semaphore/util/bindata.go:4856 +0x12e
github.com/ansible-semaphore/semaphore/db.(*DBVersion).GetSQL(0xc420011800, 0xc4201320e0, 0x18, 0x0, 0x2, 0x4a)
	/root/goproj/src/github.com/ansible-semaphore/semaphore/db/versionHistory.go:51 +0x39
github.com/ansible-semaphore/semaphore/db.(*DBVersion).Run(0xc420011800, 0x0, 0x0)
	/root/goproj/src/github.com/ansible-semaphore/semaphore/db/migrations.go:44 +0x1bf
github.com/ansible-semaphore/semaphore/db.MigrateAll(0xc420127b78, 0x1)
	/root/goproj/src/github.com/ansible-semaphore/semaphore/db/migrations.go:104 +0x169
main.doSetup(0x2)
	/root/goproj/semaphore/cli/main.go:122 +0x7b8
main.main()
	/root/goproj/semaphore/cli/main.go:25 +0x644`

How to solve these problems?

**Comment by jffree** [comment]
@benwyrosdick can you help me?

**Comment by strangeman** [comment]
How you build Semaphore? With `make.sh` script? Looks like you're not created `bindata`.

**Comment by jffree** [comment]
I  run `./make.sh` directly, then I got semaphore.

How Could I create `bindata` ?

**Comment by strangeman** [comment]
That's right, `make.sh` calls `go-bindata`. Do you have sql files in `db/migrations` folder? Like here: https://github.com/ansible-semaphore/semaphore/tree/develop/db/migrations

**Comment by jffree** [comment]
I have these files, like this:
`
[root@node1 semaphore-2.4.1]# ls db/migrations
v0.0.0.sql  v1.0.0.sql  v1.2.0.sql  v1.4.0.sql  v1.6.0.sql  v1.8.0.sql  v2.2.1.sql  v2.3.1.sql  v2.4.0.sql
v0.1.0.sql  v1.1.0.sql  v1.3.0.sql  v1.5.0.sql  v1.7.0.sql  v1.9.0.sql  v2.3.0.sql  v2.3.2.sql
`

I do not know why.....

**Comment by jffree** [comment]
I build like this:
`
[root@node1 semaphore-2.4.1]# export GOPATH=$HOME/goproj
[root@node1 semaphore-2.4.1]# export GOBIN=$GOPATH/bin
[root@node1 semaphore-2.4.1]# export PATH=$PATH:$GOBIN
[root@node1 semaphore-2.4.1]# ./make.sh 
Creating util/bindata.go
/vendor/angular.min.js
/vendor/angular-couch-potato.js
/vendor/angular-ui-router.min.js
/vendor/angular-ui.min.js
/vendor/angular-loading-bar/loading-bar.js
/vendor/moment/moment.min.js
/vendor/sweetalert/sweetalert.min.js
/js/app.js
/js/routes/router.js
/js/routes/auth.js
/js/routes/project.js
/js/factories/project.js
/vendor/require.min.js
/js/../require_config.js
/root/goproj/semaphore-2.4.1
Adding bindata
Number of parallel builds: 1

-->     linux/amd64: _/root/goproj/semaphore-2.4.1/cli

`

**Comment by strangeman** [comment]
`util/bindata.go` contains sql files? 

```
// Code generated by go-bindata.
// sources:
// config.json
// db/migrations/v0.0.0.sql
// db/migrations/v0.1.0.sql
// db/migrations/v1.0.0.sql
// db/migrations/v1.1.0.sql
// db/migrations/v1.2.0.sql
```

```
func dbMigrationsV000Sql() (*asset, error) {
	bytes, err := dbMigrationsV000SqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "db/migrations/v0.0.0.sql", size: 4061, mode: os.FileMode(420), modTime: time.Unix(1486783087, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}
```

**Comment by jffree** [comment]
In `util/bindata.go` I got this:

`
// Code generated by go-bindata.
// sources:
// config.json
// db/migrations/v0.0.0.sql
// db/migrations/v0.1.0.sql
// db/migrations/v1.0.0.sql
// db/migrations/v1.1.0.sql
// db/migrations/v1.2.0.sql
// db/migrations/v1.3.0.sql
// db/migrations/v1.4.0.sql
// db/migrations/v1.5.0.sql
// db/migrations/v1.6.0.sql
// db/migrations/v1.7.0.sql
// db/migrations/v1.8.0.sql
`

`
func dbMigrationsV000Sql() (*asset, error) {
        bytes, err := dbMigrationsV000SqlBytes()
        if err != nil {
                return nil, err
        }

        info := bindataFileInfo{name: "db/migrations/v0.0.0.sql", size: 4061, mode: os.FileMode(436), modTime: time.Unix(1499071243, 0)}
        a := &asset{bytes: bytes, info: info}
        return a, nil
}
`

**Comment by jffree** [comment]
I got the source code from https://github.com/ansible-semaphore/semaphore/archive/v2.4.1.tar.gz

**Comment by strangeman** [comment]
Strange... do you have `go-bindata` installed? Have no idea what else may be wrong.

**Comment by jffree** [comment]
I have installed `go-bindata`.

First I think we can solve this problem:
```
[root@node1 semaphore]# ./cli/semaphore_linux_amd64 -setup
Cannot Find configuration! Use -c parameter to point to a JSON file generated by -setup.

Hint: have you run -setup ?
```

I download semaphore from https://github.com/ansible-semaphore/semaphore/releases/download/v2.4.1/semaphore_linux_amd64 do not need -c when I run `semaphore -setup`, why?

**Comment by jffree** [comment]
@benwyrosdick can you help me?

**Comment by jffree** [comment]
@benwyrosdick which version you use golang ?

**Comment by strangeman** [comment]
@jffree how you fixed it?

**Comment by benwyrosdick** [comment]
@jffree I just saw these notices. Let me know if you are still having issues.

**Comment by jffree** [comment]
@strangeman @benwyrosdick 
Sorry, I reply later.
I have solved my problem.
Just because I have not put semaphore source code in GOPATH/src dir.
Thank you!
