### ISSUE TITLE
Add ability to make playbooks run at a interval or a definite time

### ISSUE THREAD

**Issue by sanders54** [ansible-semaphore/semaphore#414]
I would like the ability to run a playbook at a certain time everyday, or once a week or so. Pick a date and time and recurring yes/no when creating templated. More or less add a playbook run like you would in Cron but within the GUI of Semaphore.

**Comment by strangeman** [comment]
Currently, you can make an API call to Semaphore via cron

**Comment by fiftin** [comment]
Available in v2.7.20. 
https://github.com/ansible-semaphore/semaphore/releases/tag/v2.7.20
