### ISSUE TITLE
How to integrate Git with ansible-semaphore

### ISSUE THREAD

**Issue by NTDBANNU** [ansible-semaphore/semaphore#416]
I'm unable to add git credentials to ansible-semaphore, please let me know if anyone faced this issue before.

**Comment by strangeman** [comment]
Semaphore able to interact with Git only via SSH (add the ssh key on
project page), not via HTTPS+username+password.

пн, 7 авг. 2017 г., 5:18 NTDBANNU <notifications@github.com>:

**Comment by twhiston** [comment]
Closed in favour of #75 where we can discuss https support
