### ISSUE TITLE
failed to start the semaphore

### ISSUE THREAD

**Issue by zysamuel** [ansible-semaphore/semaphore#418]
Previously，I can start the semaphore, and can visit it throw web browser.
But unfortunatly, when I executed one task, the connection lost. and I can never start  the semaphore again.That is, I can never visit的web page.How can I solve this problem? Did anyone see that before?

when I tried to start semaphore, the shell answered me like below

```
root@WUH1000106353:~/.ssh# nohup semaphore -config /tmp/semaphore/semaphore_config.json &
[2] 4952
root@WUH1000106353:~/.ssh# nohup: ignoring input and appending output to 'nohup.out'

[2]-  Done                    nohup semaphore -config /tmp/semaphore/semaphore_config.json
root@WUH1000106353:~/.ssh#
```

I have excuted “semaphore -setup” again， and restarted the mysql，but it didn't work at all.

**Comment by twhiston** [comment]
@zysamuel do you still need support for this? If not I will close it in the next few days

**Comment by twhiston** [comment]
closing due to lack of response
