### ISSUE TITLE
is the pause module supported

### ISSUE THREAD

**Issue by mark-vdb** [ansible-semaphore/semaphore#420]
Hi, 

Im pretty sure the output answers my question, but would be good to confirm: is the pause module supported ? 

Eg: 

```
- name: Hello World Sample
  hosts: all
  tasks:
    - name: hello msg
      debug:
        msg: "hello world!"
    - name: pause
      pause:
    - name: goodby msg
      debug:
        msg: "goodbye world!"
```

**Comment by strangeman** [comment]
Semaphore currently not supported user interactions with Ansible, so `pause` without `seconds` or `minutes` will wait forever.
