### ISSUE TITLE
Ansible semaphore tty error

### ISSUE THREAD

**Issue by NTDBANNU** [ansible-semaphore/semaphore#422]
I am trying to execute a playbook from Ansible semaphore to a client machine and it gives me the below error. Has any one encountered this error before ?  i would really appreciate your help. 
![error](https://user-images.githubusercontent.com/24846966/29256367-c308f008-805e-11e7-8584-ed5d3a16f32e.png)

**Comment by strangeman** [comment]
>read_passphrase

Looks like you're using password-protected SSH key. Semaphore currently not support user inputs with keys/playbooks.

**Comment by NTDBANNU** [comment]
I'm not using password protected SSH. I'm able to do manually, but semaphore unable to reach.

**Comment by twhiston** [comment]
I'm closing this as @strangeman is correct, the error clearly shows that it needs some manual input for a password. Perhaps your cli and semaphore are not running as the same user
