### ISSUE TITLE
No web gui

### ISSUE THREAD

**Issue by KarlFiabeschi** [ansible-semaphore/semaphore#426]
Hi there, 

classic installation, when i launch 

semaphore -config /etc/ansible/roles/semaphore_config.json
Semaphore 2.4.1
Port :3000
MySQL xxxx@127.0.0.1:3306 semaphore
Tmp Path (projects home) /etc/ansible/roles/tmp
Checking DB migrations

but i have this:

![error](https://user-images.githubusercontent.com/19261917/29994681-93bbaf4e-8fd5-11e7-8ee5-b2790d769af6.png)

the db looks fine, i don't know how i can debug this, any advice?

**Comment by matejkramny** [comment]
Hi, this may be the web_url configuration property. Please check it is blank if you don't use a proxy

**Comment by KarlFiabeschi** [comment]
> Hi, this may be the web_url configuration property. Please check it is blank if you don't use a proxy

i checked, i have my fqdn url like:

 "web_host": "http://xxx.yyy.zz",

i tried:

 "web_host": "http://localhost",

same result, there is a log file can i check? ty

**Comment by matejkramny** [comment]
have a look at the html source of the page. It will be linking to an incorrect css/js file

**Comment by KarlFiabeschi** [comment]
![error](https://user-images.githubusercontent.com/19261917/29996270-fffac516-8ffb-11e7-8067-b61b2995d987.png)

ok found it, but i can't understand, i follow the instructions of wiki for installation, just wget the linux bin, put on /usr/bin/semaphore, setup and run

**Comment by matejkramny** [comment]
it'll either be:

- the domain incorrect
- incorrect proxy configuration

Leaving the `web_url` property blank, does it work?

**Comment by KarlFiabeschi** [comment]
> Leaving the web_url property blank, does it work?

yep, blank work Fine. Ty
