### ISSUE TITLE
DB connection error

### ISSUE THREAD

**Issue by DDJSM** [ansible-semaphore/semaphore#428]
Hi, SM 2.4.0 and 2.4.1 give me a error in Mysql 5.7.17 but SM 2.3.0 dont, the error is...

[Note] Aborted connection 19 to db: 'semaphore' user: 'myuser' host: 'localhost' (Got an error reading communication packets)

googleing a bit it looks some db connections are not being closed properly, anyway, I will keep my setup at 2.3.0 whit is working for me right now.

Update1: did a test with upgrade from 2.1.0 to 2.4.1 and this way I got no erros in Db connections, so just when I do a fresh install with 2.4.0 or 2.4.1 I get the DB connection error.

regards.

**Comment by markhowells** [comment]
I'm seeing the same (or similar) error.
I'm just using the 2.3.0 docker image and a compose file (that's more or less the same as the shipped one - just tweaked to run semaphore behind traefik). 
The error I see attached to the semaphore container is 
` 200  10:12:49 1m28.376766488s |   GET     /api/ws`
`Failed to insert task output: Error 1040: Too many connections`
It's easily reproducible and appears to be caused/provoked by overlapping task runs - either from the API or the Gui

**Comment by markhowells** [comment]
Update: I may have been a bit hasty above. I now believe the problem is associated with long playbookswhen running in debug mode. Even a single run, on a freshly launched semaphore container seems to cause the problem.

**Comment by markhowells** [comment]
Update:
I've built a container with v2.4.1
It exhibits the same problem, but with different log mesages
` 200  12:12:05     3.02926ms |   GET     /api/users/1`
` 200  12:12:05    4.166331ms |   GET     /api/project/1/tasks/8/output`
`&{{9 1 waiting true false dnsservers.yml  0xc4201787e0 {63644357542 119291549 0xddeb20} <nil> <nil>} {0 0 0 0 0 <nil>   <nil> false} {0   <nil> <nil> <nil> false} {0  0  <nil> {0   <nil> <nil> <nil> false} <nil> {0   <nil> <nil> <nil> false}  false} {0  0  0 false {0   <nil> <nil> <nil> false}} {0  0 <nil>  false} [] 1 false }`
` 201  12:12:22    4.776619ms |   POST    /api/project/1/tasks`
` 200  12:12:27    7.990164ms |   GET     /api/project/1/tasks`
` 200  12:12:27   16.001855ms |   GET     /api/project/1/events`
`Failed to insert task output: Error 1040: Too many connections`
`panic: Error 1040: Too many connections`
`goroutine 3746 [running]:`
`github.com/ansible-semaphore/semaphore/api/tasks.(*task).log.func1(0xc420312380, 0xc420687380, 0x23, 0xed17fd3ae, 0x104efe08, 0xddeb20)`
`        /Users/m/p/go/src/github.com/ansible-semaphore/semaphore/api/tasks/logging.go:37 +0x267`
`created by github.com/ansible-semaphore/semaphore/api/tasks.(*task).log`
`        /Users/m/p/go/src/github.com/ansible-semaphore/semaphore/api/tasks/logging.go:39 +0x612`

**Comment by fiftin** [comment]
Caught this error when ansible prints large amount of log records

**Comment by twhiston** [comment]
dup of #132 #393
