### ISSUE TITLE
error 500 - request Failed. Try again later

### ISSUE THREAD

**Issue by idgdmg** [ansible-semaphore/semaphore#429]
the valid user   / credentials  (as the matter of fact ANY user /credentilals) is failing with 500 Request Failed error. The debug log is:

`
2017/09/09 22:05:24 notifying bugsnag: gorp: No fields [external alert] in type User
2017/09/09 22:05:24 bugsnag.Notify: not notifying in development

2017/09/09 22:05:24 [Recovery] panic recovered:
POST /api/auth/login HTTP/1.1
Host: 172.24.222.234:3000
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.8,ru;q=0.6,es;q=0.4,zh-CN;q=0.2,zh;q=0.2,fr;q=0.2
Cache-Control: no-cache
Connection: keep-alive
Content-Type: application/json;charset=UTF-8
Origin: http://172.24.222.234:3000
Referer: http://172.24.222.234:3000/auth/login
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36

gorp: No fields [external alert] in type User
/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:426 (0x42de89)
/Users/m/p/gospace/src/github.com/bugsnag/bugsnag-go/bugsnag.go:52 (0x533361)
/usr/local/Cellar/go/1.6/libexec/src/runtime/asm_amd64.s:472 (0x45d17e)
/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:426 (0x42de89)
/Users/m/p/gospace/src/github.com/ansible-semaphore/semaphore/routes/login.go:49 (0x4cd305)
/Users/m/p/gospace/src/github.com/gin-gonic/gin/context.go:97 (0x53c41a)
/Users/m/p/gospace/src/github.com/gin-gonic/gin/logger.go:66 (0x54dd4a)
/Users/m/p/gospace/src/github.com/gin-gonic/gin/context.go:97 (0x53c41a)
/Users/m/p/Projects/semaphore/main.go:74 (0x401aef)
/Users/m/p/gospace/src/github.com/gin-gonic/gin/context.go:97 (0x53c41a)
/Users/m/p/gospace/src/github.com/gin-gonic/gin/recovery.go:45 (0x54eab1)
/Users/m/p/gospace/src/github.com/gin-gonic/gin/context.go:97 (0x53c41a)
/Users/m/p/gospace/src/github.com/gin-gonic/gin/gin.go:284 (0x543072)
/Users/m/p/gospace/src/github.com/gin-gonic/gin/gin.go:265 (0x542ca7)
/usr/local/Cellar/go/1.6/libexec/src/net/http/server.go:2081 (0x65176e)
/usr/local/Cellar/go/1.6/libexec/src/net/http/server.go:1472 (0x64e01e)
/usr/local/Cellar/go/1.6/libexec/src/runtime/asm_amd64.s:1998 (0x45f831)
`

**Comment by fiftin** [comment]
Looks like version of database does not match the version of app.
