### ISSUE TITLE
semaphore service won't start

### ISSUE THREAD

**Issue by wardcomm** [ansible-semaphore/semaphore#430]
I am using:
Red Hat Enterprise Linux Server release 7.2 (Maipo)
semaphore_linux_amd64

I followed instructions and I am getting this when I try to start service:

 systemd: Started Semaphore.
 systemd: Starting Semaphore...
 systemd: semaphore.service holdoff time over, scheduling restart.
 systemd: start request repeated too quickly for semaphore.service

systemd: Failed to start Semaphore.
systemd: Unit semaphore.service entered failed state.
systemd: semaphore.service failed.

/var/log/messages is showing the same thing

I am trying to get this to work on rhel 7 following these instructions:
https://estebanmonge.tk/doku.php/semaphore_ansible

my systemd unit file looks like this

[Unit]
Description=Semaphore
After=network.target

[Service]
User=semaphore
Group=semaphore
ExecStart=/bin/sh -c "/usr/bin/semaphore -config /home/semaphore/semaphore_config.json 2>&1 &"
Restart=always
#journalctl -u semaphore

[Install]
WantedBy=multi-user.target

**Comment by twhiston** [comment]
do you still have this problem? what is the journalctl output for semaphore?

**Comment by denics** [comment]
Sorry to jump in like this, probably your issue is because of the user "semaphore". For example in Debian that user is not created. Personally I am running the service as www-data. I'll do a PR for discussion.
