### ISSUE TITLE
Bug when update git repository

### ISSUE THREAD

**Issue by Gamoth** [ansible-semaphore/semaphore#431]
Hello,

I use a HTTPS GIT repository with credential.
I resolve my problem HTTPS certifcate by variable http.sslcainfo in git config global.
I resolve my credential problem with credential.helper in git config global.

I can clone repository but when I wish relaunch an existing repository, I 'm the following error : 
fatal: unable to access 'https://git.extra.pouette.fr/depot/jenkinsSalve.git/': Peer's Certificate issuer is not recognized.

My config 
RHEL 7.2 with mariadb-server-5.5.50-1.el7_2.x86_64
Semaphore : 2.4.1
Firefox Nightly 58.

Regards,
Gamoth

**Comment by fiftin** [comment]
> Semaphore able to interact with Git only via SSH (add the ssh key on
project page), not via HTTPS+username+password.

https://github.com/ansible-semaphore/semaphore/issues/416

**Comment by fiftin** [comment]
https://github.com/ansible-semaphore/semaphore/issues/416#issuecomment-320535174

**Comment by Gamoth** [comment]
it would be a good feature ?

**Comment by twhiston** [comment]
closed in favour of #416 where we can discuss if we want https support
