### ISSUE TITLE
Logs conflicts when multiple playbooks running in parallel

### ISSUE THREAD

**Issue by ndeixonne** [ansible-semaphore/semaphore#432]
Hi,

I've detected a unexpected behavior in Semaphore. I've tried to run two tasks at the same time. When I launch the first task, no trouble, it's launching the right playbook. When I launch my second task (first task didn't finish of course), I see the log of the first task in the log window and not my second task log running.

Does someone know why that behavior happens ?

Thanks !

**Comment by markhowells** [comment]
I also see this. However, when the tasks finish, the task logs appear to be correct.

**Comment by ndeixonne** [comment]
Yes, same here. When the task is finished, log appear correctly. But in anyways, it's still a problem if we can't see running logs when you execute multiple playbooks.

**Comment by fiftin** [comment]
UI totally rewritten, closing issue.
