### ISSUE TITLE
Semaphore is running but webpage not correctly display

### ISSUE THREAD

**Issue by arequipeno** [ansible-semaphore/semaphore#438]
Hi everybody,

First of all thanks for the good work.

I respect wiki instructions and setup everything but webpage is not correctly display can with have more logs to debug (options to set to semaphore binary do not permit to have more logs or debug info)

![semaphoreissuewebpage](https://user-images.githubusercontent.com/12070810/32557883-b7d54fb8-c4a3-11e7-9e6c-6bc0d52b3174.png)

I am using:
- rhel7 Workstation 
- rpm: 
mariadb-server-5.5.52-1.el7.x86_64
mariadb-libs-5.5.52-1.el7.x86_64
mariadb-5.5.52-1.el7.x86_64
git-1.8.3.1-6.el7.x86_64
ansible-2.3.1.0-1.el7.noarch

I am using over https with apache, and launch it with systemd without any error.

I try to use in standalone mode and to launch it from command line and i have the same behaviour.

I hope this can help you to see what is wrong. Maybe i need some angular dependencies.

I am come back next week so i can only do more test next week.

Browser used is firefox:
firefox-52.3.0-2.el7_4.x86_64

**Comment by Echobob** [comment]
Hi there, please check https://github.com/ansible-semaphore/semaphore/issues/426
This may be an issue with your `web_url` property.

**Comment by arequipeno** [comment]
Hi, 

Yes, Many thanks.
