### ISSUE TITLE
syntax error near unexpected token `newline'

### ISSUE THREAD

**Issue by wh211212** [ansible-semaphore/semaphore#446]
# when i use the command wget:
sudo curl -L https://github.com/ansible-semaphore/semaphore/releases -o /usr/bin/semaphore
chmod +x  /usr/bin/semaphore

 but when i execute semaphore -setup,whill be error:

/bin/semaphore: line 7: syntax error near unexpected token `newline'
/bin/semaphore: line 7: `<!DOCTYPE html>'

**Comment by DarkSeraphim** [comment]
Aren't you downloading an HTML page instead of the actual release?
