### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by nblaginin** [ansible-semaphore/semaphore#447]
**CentOS Linux release 7.4.1708 (Core)**
Linux host 3.10.0-693.11.6.el7.x86_64 #1 SMP Thu Jan 4 01:06:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
**ansible 2.4.2.0**
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
**semaphore**
https://github.com/ansible-semaphore/semaphore/releases/download/v2.4.1/semaphore_linux_amd64
**semaphore_config.json**
{
        "mysql": {
                "host": "127.0.0.1:3306",
                "user": "semaphore",
                "pass": "topsecret",
                "name": "semaphore"
        },
        "port": "",
        "tmp_path": "/home/semaphore",
        "cookie_hash": "5ooClrAEpzId5aSqhTW4P2pIGuWuhPPrPlhCapv6crw=",
        "cookie_encryption": "yBPXcgjf7TaLTNRDqeJFJO8f8L/SS5244B31lVUXIN8=",
        "email_alert": true,
        "email_sender": "semaphore@mail.corp",
        "email_host": "localhost",
        "email_port": "25",
        "web_host": "192.168.1.225:8010",
        "ldap_enable": false,
        "ldap_binddn": "",
        "ldap_bindpassword": "",
        "ldap_server": "",
        "ldap_needtls": false,
        "ldap_searchdn": "",
        "ldap_searchfilter": "",
        "ldap_mappings": {
                "dn": "",
                "mail": "",
                "uid": "",
                "cn": ""
        },
        "telegram_alert": false,
        "telegram_chat": "",
        "telegram_token": ""
 }

**nohup.out**
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5f4270]

goroutine 1 [running]:
net/url.(*URL).String(0x0, 0x12, 0x0)
        /usr/local/Cellar/go/1.8.3/libexec/src/net/url/url.go:726 +0x40
github.com/ansible-semaphore/semaphore/util.init.1()
        /Users/m/p/go/src/github.com/ansible-semaphore/semaphore/util/config.go:164 +0x466
github.com/ansible-semaphore/semaphore/util.init()
        /Users/m/p/go/src/github.com/ansible-semaphore/semaphore/util/version.go:5 +0x16f12
github.com/ansible-semaphore/semaphore/db.init()
        /Users/m/p/go/src/github.com/ansible-semaphore/semaphore/db/versionHistory.go:76 +0x4e
github.com/ansible-semaphore/semaphore/api.init()
        /Users/m/p/go/src/github.com/ansible-semaphore/semaphore/api/users.go:115 +0x61
main.init()
        /Users/m/p/semaphore/cli/main.go:179 +0x75

**Comment by souxls** [comment]
try again.  "web_host": "http://192.168.1.225:8010",
