### ISSUE TITLE
Allow copying from task log

### ISSUE THREAD

**Issue by strangeman** [ansible-semaphore/semaphore#468]
Currently, copying from task log is not working. This is annoying because there is no way to copy part of log.

![2018-02-28-103936_1366x768_scrot](https://user-images.githubusercontent.com/1083576/36763498-f26c8e0c-1c73-11e8-825c-6e2a8ab48ee0.png)

**Comment by twhiston** [comment]
What browser are you using? Seems like its only happening in firefox for me (tested chrome, vivaldi, firefox and safari)

**Comment by strangeman** [comment]
Yeah, I'm using Firefox. I found the problem: need to change `disabled` property of textarea to `readonly`. Testing the fix now.

![2018-02-28-105620_1366x768_scrot](https://user-images.githubusercontent.com/1083576/36763974-1bfdcf40-1c76-11e8-904a-c4503b41269b.png)
