### ISSUE TITLE
Dynamic Inventory support

### ISSUE THREAD

**Issue by lakshmantgld** [ansible-semaphore/semaphore#47]
I use aws with ansible, so dynamic inventory is used instead of adding hosts manually. Is this possible with semaphore?
Documentation for running playbooks from local machine? I am not able see the documentation for running test playbooks with git repo, if I have missed it, can you point the documentation.

**Comment by gvenka008c** [comment]
@here... Any updates on this?

**Comment by Lakshman-LD** [comment]
@gvenka008c No answers. Built my own Ansible Tower.

**Comment by gvenka008c** [comment]
@Lakshman-LD Thanks. Got any repo to clone / view your unusable tower version?

**Comment by gvenka008c** [comment]
@Lakshman-LD Any updates?

**Comment by matejkramny** [comment]
You can automate the API, or adjust runner.js to have dynamic inventory.

**Comment by Lakshman-LD** [comment]
Dont have any repo to share!! sorry @gvenka008c

**Comment by gvenka008c** [comment]
@Lakshman-LD what repo you want sir??? anyway thanks.

**Comment by gvenka008c** [comment]
@matejkramny I updated runner.js. How can i ensure the updated script is picked up by docker?

**Comment by gvenka008c** [comment]
@Lakshman-LD Thanks.

**Comment by matejkramny** [comment]
@gvenka008c you can re-build the image or create an image from the semaphore image, and then edit those files.. Or you can attach to the container and edit files directly, restarting the node process afterwards

**Comment by matejkramny** [comment]
Dynamic inventories will be supported in version 2 of semaphore.

It is WIP in branch https://github.com/ansible-semaphore/semaphore/tree/v2

**Comment by matejkramny** [comment]
Sorry guys, reassigned to v2.1 release

**Comment by adambonny** [comment]
:+1:

**Comment by nathan-v** [comment]
Is there any update on when this feature will be available?

**Comment by matejkramny** [comment]
It'll be a couple of weeks/days.

So far (in my mind) the inventory will fetch EC2 instances using an AWS key, then filter it by a regex specified by the user.

Is there more to it or just simple as that?

**Comment by nathan-v** [comment]
Better would be utilizing the EC2 instance tags rather than just the instance metadata.

My preference would be to _also_ allow instance selection by grabbing instances that are members of an Auto Scaling Group. Often instances in AWS are deployed initially as AMIs to ASGs; being able to target the ASG members would be awesome.

**Comment by srpayne** [comment]
Why not just use ec2.py instead of creating something new? or give the option of piping to it?

**Comment by pgporada** [comment]
I was expecting to be able to point at a custom inventory file as well.

**Comment by theasp** [comment]
@pgporada I agree.  I'm able to do it using an empty inventory in Semaphore (I named it "From Hosts File"), and adding this to the "Extra CLI Arguments":
```json
["--inventory", "hosts", 
 "--limit", "some-group"]
```
Being able to specify a file from the git repository would allow running it as a script, as per normal ansible behaviour.

**Comment by pgporada** [comment]
@theasp Fantastic idea!

**Comment by JanSchr** [comment]
Beeing able to choose an inventory file from a git repository would be awesome.

**Comment by morph027** [comment]
Jip, would love it! So far, the extra cli arguments stuff works for me.

**Comment by punktik** [comment]
Is there anywhere a howto for someone not familiar with nodejs? 
I still cannot selct AWS dynamical inventory. 
Thank you in advance for your help.

**Comment by aioue** [comment]
is this released yet? It's greyed out in `2.3.0`

**Comment by tobiasfielitz** [comment]
Still grayed out in v2.4.1. I have added AWS credentials in Key Store.

**Comment by anitakrueger** [comment]
Hi there,
I've just installed semaphore 2.4.1 and got all excited that I could now use AWS as the inventory. But when trying to create an inventory, as @tobiasfielitz said, AWS is greyed out as an option.
Is there a configuration step I am missing which is why it is greyed out? Or is the functionality not available yet?

Thanks!
- Anita

**Comment by brad** [comment]
@aioue @tobiasfielitz @anitakrueger It's still unchecked in [the roadmap](https://github.com/ansible-semaphore/semaphore/issues/325)

**Comment by GanimanSwift** [comment]
I think this missing feature is what's going to prevent me from using Semaphore.  I'd really like to be able to point it at a custom script.

**Comment by jospina-316** [comment]
Is there a way to just point a static inventory to the ansible hosts file on the server semaphore is running off? e.g. /etc/ansible/hosts

**Comment by ndeixonne** [comment]
Actually you can specify custom inventory. You jsut need to override the parameter -i in the task template. The last -i in the code is given the priority.
If you need override any other parameters, try to override it in task template.

**Comment by twhiston** [comment]
I would like to try to get this feature in, via the api rather than an -i override into a 2.6.0 version

**Comment by twhiston** [comment]
closing this as file type of inventory allows for dynamic inventory files to be included in the source repo
