### ISSUE TITLE
Default admin user gets recreated even if deleted from panel

### ISSUE THREAD

**Issue by brodul** [ansible-semaphore/semaphore#48]
Default admin user gets recreated even if deleted from panel

https://github.com/ansible-semaphore/semaphore/blob/master/lib/config.js#L66

**Comment by matejkramny** [comment]
Ha nice find, never thought it'd ever be deleted.

**Comment by brodul** [comment]
@matejkramny what solution would you prefer?

**Comment by matejkramny** [comment]
In config.js, have a similar lookup (replacing the current one) for existing users. If none can be found, create an admin account.

This way an admin is still created but it won't stand in the way if you decide to delete him.
