### ISSUE TITLE
Create pretty-looking page for task log

### ISSUE THREAD

**Issue by strangeman** [ansible-semaphore/semaphore#481]
Improvement for https://github.com/ansible-semaphore/semaphore/pull/440

Current realization (simple link to the API page with JSON-formatted task log) is ugly (but still better than nothing). Can we create a pretty-looking separate page for it? I'm totally dumb in JS, so maybe @fiftin can take this task? The separate page is very useful to share results among team members.

![2018-03-10-120056_1366x768_scrot](https://user-images.githubusercontent.com/1083576/37237105-21d794cc-245b-11e8-8f5b-b87e36737d8e.png)
![2018-03-10-120101_1366x768_scrot](https://user-images.githubusercontent.com/1083576/37237106-220f9e26-245b-11e8-9113-ab2993447429.png)

**Comment by fiftin** [comment]
Yes, I can take on this task

**Comment by strangeman** [comment]
Great, thank you!

**Comment by fiftin** [comment]
Added URL for running task

![image](https://user-images.githubusercontent.com/914224/99889911-9bb71a80-2c7b-11eb-991c-76938a31ba1c.png)
