### ISSUE TITLE
Fix frontend issues reported in Codacy

### ISSUE THREAD

**Issue by twhiston** [ansible-semaphore/semaphore#485]
Codacy reports some issues with the FE code that we should tackle to fix some errors and give the codebase a consistent style. @fiftin maybe you could take a look at the results and if any feel like a false positive let me know and I will alter the Codacy configuration.

https://app.codacy.com/app/twhiston/semaphore/issues?bid=6755282&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6WyJKYXZhc2NyaXB0Il19LHsiaWQiOiJDYXRlZ29yeSIsInZhbHVlcyI6W251bGxdfSx7ImlkIjoiTGV2ZWwiLCJ2YWx1ZXMiOltudWxsXX0seyJpZCI6IlBhdHRlcm4iLCJ2YWx1ZXMiOltudWxsXX0seyJpZCI6IkF1dGhvciIsInZhbHVlcyI6W251bGxdfV0=

**Comment by fiftin** [comment]
Where I can see codestyle description? 

I see some mismatches with PR codestyle check results.

Here:
```
Strings must use singlequote. (quotes)
controller: "SignInCtrl",
```

In PR https://github.com/ansible-semaphore/semaphore/pull/479:
```
Strings must use doublequote. (quotes)
$http.post('/upgrade').then(function () {
```
