### ISSUE TITLE
Override semaphore arguments is ticked by default

### ISSUE THREAD

**Issue by twhiston** [ansible-semaphore/semaphore#493]
![screen shot 2018-03-14 at 20 46 25](https://user-images.githubusercontent.com/17698613/37427171-cceedfee-27c8-11e8-9f67-540f3ae88543.png)
looks like by default overriding the semaphore arguments is ticked in the ui, surely this is an error.
Interestingly it also does not seem to respect the value set, if i untick and save and then reload the page it is ticked again
@fiftin maybe this is a quick fix for you?

**Comment by fiftin** [comment]
Very strange bug. This checkbox binded to user.admin field :)

**Comment by twhiston** [comment]
😱 well that is totally wrong then!

**Comment by fiftin** [comment]
I'll fix it after merge FE refactoring PR. I have a problem with return to old schema to test solution.

**Comment by twhiston** [comment]
awesome, thanks so much :)
