### ISSUE TITLE
Saving an environment with no name is allowed

### ISSUE THREAD

**Issue by twhiston** [ansible-semaphore/semaphore#494]
Not sure if we should block this at the ui or the api level, but currently you can create an environment without a name and save it successfully, leading to a weird empty line in the environment list
![screen shot 2018-03-14 at 20 51 55](https://user-images.githubusercontent.com/17698613/37427418-b44a3a28-27c9-11e8-901b-63ff629c0c98.png)

**Comment by strangeman** [comment]
This is actual for Task Templates, Environment, Inventory, Keys, Repositories (for Repo we can make Git URL empty too). Looks like this is the complex problem.

**Comment by twhiston** [comment]
html5 validation in the frontend should be a 'low cost' way to stop this happening for most cases i guess, but really we should also stop it in backend too, so that it fails to save, some not null database settings etc....

**Comment by fiftin** [comment]
Fixed
