### ISSUE TITLE
Better feedback when tasks fail early

### ISSUE THREAD

**Issue by twhiston** [ansible-semaphore/semaphore#495]
Sometimes jobs fail early, for example at the list host time, and we don't currently log these problems well. Ansible can provide some helpful info (playbook not found, missing plugin, stack trace) but we just state the error code and that is it. It would be more useful to also capture the std.Err from the command and write it to the log in these instances so the problem is more easily diagnosed and fixed

**Comment by strangeman** [comment]
Yeah, it will be very useful. I can do it.

**Comment by strangeman** [comment]
I checked this issue and found only one poor feedback - in `listPlaybookHosts()` function. But it's the important step because it usually failing due to syntax errors in playbooks.
Please, tell me, if I missed other poorly feedbacked steps.
