### ISSUE TITLE
Extra arguments are not being saved in task templates

### ISSUE THREAD

**Issue by twhiston** [ansible-semaphore/semaphore#496]
I'm having an issue whereby Extra CLI Arguments in the task template are not being saved to the database currently. It looks from the .pug that this field is currently tied to `task.Environment`, but actually in the go code it should end up being saved in `db.template Arguments` field (see db/Template.go)
@fiftin - is this something that just needs an fe fix?

**Comment by fiftin** [comment]
This is my mistake
