### ISSUE TITLE
npm global install permission issues 

### ISSUE THREAD

**Issue by twhiston** [ansible-semaphore/semaphore#506]
As reported in #503 

> while I run task deps.It call some npm install -g.that as normal user under ubuntu will trigger a permission problem.

This permission problem is also true in my Fedora development environment.

Do these dependencies really need to be installed globally? Can't they be dev dependencies in the `package.json`?
Needs to be resolved in 2.5.0 as it blocks contribution currently

**Comment by strangeman** [comment]
I tested npm without global install (just deleted `-g` option from nodemon, less and pug installation command) - all working correctly.

**Comment by twhiston** [comment]
yeah, it works ok like that for me too. So we should add these to the package.json as dev dependencies and then we can tidy the fe install a lot and avoid these permission issues. I know that @fiftin said before that local installs of some of these things are not usual, but honestly i struggle to find evidence for or against it, but FE is not my thing, so if anyone has any good reason not to make these local dev dependencies speak now!

**Comment by twhiston** [comment]
I think the downside of a local install is that they will end up in the web/node_modules/.bin folder, which almost definitely is not going to be in your path, so we would have to change the taskfile to reference the files directly to keep it working.
This is easy to deal with on linux as we can just do `$(pwd)/web/node_modules/.bin/cless` but I guess this will fail on windows :disappointed:

**Comment by strangeman** [comment]
Does taskfile support relative path? Like `./web/node_modules/.bin/cless`

**Comment by twhiston** [comment]
yes, it should do

**Comment by strangeman** [comment]
Yeah, just checked. 

```
task compile:fe
./node_modules/.bin/lessc resources/less/semaphore.less > public/css/semaphore.css
./node_modules/.bin/pug resources/pug --out public/html

  rendered /mnt/src/sources/go/src/github.com/ansible-semaphore/semaphore/web/public/html/abstract.html
  rendered /mnt/src/sources/go/src/github.com/ansible-semaphore/semaphore/web/public/html/admin.html
...
```

I'll test it on Windows and make a PR.

**Comment by twhiston** [comment]
awesome, please add these as devDependencies in the `package.json` https://github.com/npm/npm/blob/2e3776bf5676bc24fec6239a3420f377fe98acde/doc/files/package.json.md#devdependencies

**Comment by strangeman** [comment]
Unfortunately, we have another problem: `reflex` not working under Windows. :(
```
PS C:\Users\Administrator\go\src\github.com\ansible-semaphore\semaphore> go get github.com/cespare/reflex
# github.com/cespare/reflex
..\..\cespare\reflex\reflex.go:227:14: undefined: syscall.Kill
..\..\cespare\reflex\reflex.go:262:14: undefined: pty.Start
```

**Comment by twhiston** [comment]
That's a known issue which is in the contribution guide so for now we can just ignore it I think
