### ISSUE TITLE
Is there a reason why bugsnag is a dependency? 

### ISSUE THREAD

**Issue by NeMO84** [ansible-semaphore/semaphore#51]
I am trying to understand why bugsnag is a dependency. I reviewed bugsnag and they don't seem to have a free plan. They have a free trial plan, but after the current 30 day limit the bugsnag dependency will cause issues. 

It would be nice if the dependency were ignored when the configuration was not supplied in the credentials.json file.

**Comment by NeMO84** [comment]
This was my mistake. It doesn't seem to be seem to be a dependency for running the application. I just didn't run it with proper credentials. My mistake.

**Comment by matejkramny** [comment]
Well it shouldn't really be there, because it is viewed as a third-party analytics tool (ublock blocks it.)..

See #41 for an ongoing discussion with myself about the topic :P
