### ISSUE TITLE
Proposal to change CI

### ISSUE THREAD

**Issue by twhiston** [ansible-semaphore/semaphore#510]
I would propose that we move the project from CircleCI to another Continuous Integration solution. CircleCI seems to me to become increasingly weak when testing apps with any level of complexity, and we have seen a build break today that worked fine in testing but broke on merge. 

This issue was due to the CircleCI caching approach, which I feel is particularly problematic. Files that are cached in circleci are kept indefinitely, the only way to run a build with a fresh cache is to bump the cache version in the configuration. This means that while testing a major change it is extremely easy to either break the caching, or pull in older files that render some of your configuration steps incorrect, or as was the case today, appeared to be correct until the build used the project and not the fork's caches.
This sort of situation where you need to think carefully about performing manual steps to ensure the build is correct (bump cache versions in both write and restore cache steps to clear them before making a pr) goes against a devops mentality and is extremely difficult to catch before something is merged, leading to decreased release confidence.
For completeness its worth mentioning that this issue is also caused in part by the fact that circle uses a concatenated list of directories for GOPATH and does not include the final entry in the PATH, which lead to the situation where the app was downloaded correctly using the GOPATH variable but could not be called later in the process. 

What other CI's do people here have experience with? I've had a lot of success with both Codeship and Gitlab CI (which is now available on github (https://about.gitlab.com/features/github/)

**Comment by twhiston** [comment]
Another issue I have with circle is that it spams you, tests run on the same branch do not create threads but instead separate emails, so you end up with a lot of noise in your inbox if you are doing lots of testing on your fork

**Comment by strangeman** [comment]
I have some experience with Travis (on small projects), but mostly I work with Jenkins. Unfortunately, it wants a separate server. I heard much positive feedback about Gitlab CI.

**Comment by twhiston** [comment]
I'm not a fan of jenkins tbh, feels a bit old school these days. We recently migrated everything at work away from it and on to gitlab. The ci  is really great, another declarative yaml style system with good container support (depending on the runner used) and really easy to do parallel steps etc... to speed up test runs. Once we have 2.5.0 out the door i'll make a PR with gitlabci integration to show how it works and then we can make a decision if we want it or if we need to look for something else

**Comment by twhiston** [comment]
we just had another incident where the ci worked on the PR branch and then failed when merged in to develop (due to npm not being installed, which is very strange as we explicitly install it). When I re-ran the tests from the UI they then passed. This kind of inconsistency around testing is really annoying and makes circle seem really brittle imo.

**Comment by fiftin** [comment]
CircleCI works fine. So far it is not relevant.
