### ISSUE TITLE
Failed default login

### ISSUE THREAD

**Issue by anti43** [ansible-semaphore/semaphore#52]
Hi,

I have just installed Semaphore under Ubuntu following the readme instructions but I am unable to login with the default credentials. The Semaphore login page comes up fine at localhost but entering the credentials just redirects to the login page again. UMongo tells me the user 'admin@semaphore.local' is in the database.

Log says:

GET / 304 8.508 ms - -
GET /view/auth/login 304 7.786 ms - -
POST /auth/password 201 75.863 ms - 7
GET / 304 7.934 ms - -
GET /view/auth/login 304 12.306 ms - -

Any advice on how to correct this?

**Comment by matejkramny** [comment]
From past experience, this seems like a sessions issue. Either sessions aren't being persisted or the sessions middleware is updated and doesn't work as expected..

For some reason we don't have a lockdown on dependency versions yet so it might have happened that you installed a too-new version of the session middleware.

**Comment by matejkramny** [comment]
Try the following:

1. Copy [this file](http://pastebin.com/y3P8qaNS) to `npm-shrinkwrap.json`
2. Delete `node_modules` folder
3. `npm install` again
4. report back

**Comment by anti43** [comment]
Hello,

After replacing the file it says "Login successful" briefly, then redirect to login page.

**Comment by matejkramny** [comment]
Hmm but you need to re-install all node dependencies. The file tells npm which version to install.

Are you running redis?

**Comment by anti43** [comment]
No redis. I *think* i did the npm install after deleting node_modules before, but however now i get


npm WARN unmet dependency /home/andreas/semaphore/node_modules/bower/node_modules/inquirer requires chalk@'^0.5.0' but will load
npm WARN unmet dependency /home/andreas/semaphore/node_modules/bower/node_modules/chalk,
npm WARN unmet dependency which is version 1.1.1
npm WARN unmet dependency /home/andreas/semaphore/node_modules/bower/node_modules/handlebars/node_modules/uglify-js requires async@'~0.2.6' but will load
npm WARN unmet dependency /home/andreas/semaphore/node_modules/async,
npm WARN unmet dependency which is version 1.4.2

so probably i need to reinstall all ..

**Comment by matejkramny** [comment]
Hmm you need to have redis. It might be failing quietly.

All sessions are stored in redis.

**Comment by anti43** [comment]
thank you., that was it!

2015-12-07 12:15 GMT+01:00 Matej Kramny <notifications@github.com>:
