### ISSUE TITLE
Missing maintainer Debian package

### ISSUE THREAD

**Issue by sscheib** [ansible-semaphore/semaphore#526]
Hello,

just installed the latest version using the .deb Package and got the following warning:
dpkg: warning: parsing file '/var/lib/dpkg/tmp.ci/control' near line 13 package 'semaphore':
 missing maintainer

**Comment by twhiston** [comment]
:grimacing: thanks for reporting this. I'll get it fixed and add some tests to make sure that the packages install correctly. Apologies for the inconvenience.
