### ISSUE TITLE
nginx sample configuration link broken

### ISSUE THREAD

**Issue by sscheib** [ansible-semaphore/semaphore#527]
Hello,
I wanted to setup semaphore using nginx as reverse proxy.
However, the link, which should point to the nginx configuration sample is broken.
It points to:
https://github.com/ansible-semaphore/semaphore/blob/master/scripts/proxy/nginx.conf
This site is not accessible anymore

**Comment by twhiston** [comment]
try `https://github.com/ansible-semaphore/semaphore/blob/develop/deployment/docker/prod/proxy/nginx.conf`
Where did you see that link?

**Comment by sscheib** [comment]
Thank you.
I found the link following the "Install Instructions" link on the main page, which directs to the wiki page (https://github.com/ansible-semaphore/semaphore/wiki/Installation)

At the bottom within the section **HTTPs and security** the broken link can be found.

**Comment by twhiston** [comment]
Thanks, I have fixed the link and will close this now
