### ISSUE TITLE
semaphore -setup unable to ping maria db

### ISSUE THREAD

**Issue by sscheib** [ansible-semaphore/semaphore#528]
Hello,

I ran semaphore -setup and came up with the following configuration:
` Generated configuration:
 {
        "mysql": {
                "host": "127.0.0.1:3306",
                "user": "semaphore",
                "pass": "removed",
                "name": "semaphore"
        },
        "port": "",
        "tmp_path": "/home/semaphore",
        "cookie_hash": "removed",
        "cookie_encryption": "removed",
        "email_sender": "semaphore@removed",
        "email_host": "localhost",
        "email_port": "25",
        "web_host": "",
        "ldap_binddn": "",
        "ldap_bindpassword": "",
        "ldap_server": "",
        "ldap_searchdn": "",
        "ldap_searchfilter": "",
        "ldap_mappings": {
                "dn": "",
                "mail": "",
                "uid": "",
                "cn": ""
        },
        "telegram_chat": "",
        "telegram_token": "removed",
        "concurrency_mode": "",
        "max_parallel_tasks": 0,
        "email_alert": true,
        "telegram_alert": true,
        "ldap_enable": false,
        "ldap_needtls": false
 }
 > Is this correct? (yes/no): y
 > Config output directory (default /root/sources/certbot): /home/semaphore
 Running: mkdir -p /home/semaphore
 Configuration written to /home/semaphore/config.json..
 Pinging db..

 Cannot connect to database!
 dial tcp 127.0.0.1:3306: connect: connection timed out`

As you can see it is unable to connect to the database.
However, it is up and running and I am able to connect with the user provided:
`root@removed:/home/semaphore# netstat -tulpen | grep 3306
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      109        4199766    30219/mysqld        
root@removed:/home/semaphore# mariadb -usemaphore -premoved
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 2
Server version: 10.1.26-MariaDB-0+deb9u1 Debian 9.1

Copyright (c) 2000, 2017, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| semaphore          |
+--------------------+
2 rows in set (0.00 sec)

MariaDB [(none)]> Ctrl-C -- exit!
Aborted`

Is there something I should have done differently?

**Comment by strangeman** [comment]
Are you run Semaphore as binary or as Docker image? I have the same config and all working correctly.

**Comment by sscheib** [comment]
Hello,

sorry for the late response - I was busy with other things.
However: I identified the issue here. The problem is, that semaphore is not using interface **lo** to connect to 127.0.0.1. I have blocked all requests to 127.0.0.1, which use as interface not lo.
Semaphore in this case is using eth0 to connect to 127.0.0.1 (which is in fact lo) - I would consider this as bug.

**Comment by strangeman** [comment]
duplicate https://github.com/ansible-semaphore/semaphore/issues/538
