### ISSUE TITLE
Users page does not work after 2.5.0 upgrade

### ISSUE THREAD

**Issue by slickvoodoo** [ansible-semaphore/semaphore#529]
We replaced our 2.4.1 binary with 2.5.0 and now users no longer populate on the Users page. Have tried this with Admin user with the same result.

Requests to /api/user are only returning the logged in user. No errors in semaphore log and no console errors in chrome tools when browsing.

I looked at /db/migrations/v2.5.0.sql just to make sure we are not requiring a DB change but that does not seem to help.

Any ideas??
![users](https://user-images.githubusercontent.com/19964270/39145547-b0d1dd20-46f9-11e8-8a1e-d35cb0cf5586.PNG)

**Comment by slickvoodoo** [comment]
have to correct myself slightly. I see that /api/user**s** is returning a full list. But no display on the page.

**Comment by idxsmr** [comment]
I have upgraded to the new version 2.5.0. The main reason I upgraded to this version is for the user management. Could you please let me know when this fix(user page does not work) in 2.5.1 version would be released.

Also I tried to create a new user which throws an error for me. I have uploaded the screenshot.
![user-creation-error](https://user-images.githubusercontent.com/33719300/39695987-f4204376-5209-11e8-8aa9-f7ad0d4b0911.jpg). Not sure if this has already been fixed....

**Comment by twhiston** [comment]
The above is a new one to me, please can you start a separate issue for it.
I'll try to do a 2.5.1 release in the next week or so.

**Comment by idxsmr** [comment]
Created a new issue #535
