### ISSUE TITLE
If Semaphore is served https, external fonts should use https too.

### ISSUE THREAD

**Issue by Ranzear** [ansible-semaphore/semaphore#530]
Mixed content warnings in Chrome regarding font links:

http://fonts.gstatic.com/s/roboto/v18/KFOlCnqEu92Fr1MmWUlfBBc9.ttf

Semaphore's pages need to use https protocol if hosted with https protocol.

**Comment by fiftin** [comment]
@twhiston Did you reproduce this bug?

**Comment by twhiston** [comment]
@fiftin - I havn't had time to try yet tbh as I was at KubeCon last week. I'll try and reproduce it this week

**Comment by matejkramny** [comment]
Seems to be fixed with 01a0ec271fea5e075dc72826137f3dd9fa5f50d1
