### ISSUE TITLE
When I select a playbook file, is there a way to select a local file?

### ISSUE THREAD

**Issue by doicom** [ansible-semaphore/semaphore#532]
Hi all,
Someone, please help us.

I chose the Github URL of the Playbook Repository,Can I change this to a local directory?
When changing, where is the document whose details are listed?

 Since this is a git clone, it can not be changed, so does it need to create from source?

Warm Regards,

**Comment by twhiston** [comment]
There was some discussion around using local folders instead of git in this issue #327 is that what you mean?

**Comment by doicom** [comment]
Thanks twhiston
I'm sorry to reply late.

In # 327 it seems to solve what I want to do, so I would like to try it.

Thank you for teaching me, it was a great help.
