### ISSUE TITLE
New user feature does not work after 2.5.0 upgrade

### ISSUE THREAD

**Issue by idxsmr** [ansible-semaphore/semaphore#535]
Not able to create a new user. Below is the error screenshot.

![user-creation-error](https://user-images.githubusercontent.com/33719300/39697052-3de55070-520d-11e8-9471-e7ac7d07c925.jpg)

**Comment by twhiston** [comment]
I can recreate this. 
@fiftin any ideas why this happens? Creating a user via the API still works correctly

**Comment by idxsmr** [comment]
Any idea when the new release with these fixes would be out?

**Comment by twhiston** [comment]
Sorry i've had to travel more than usual this month and it's messed up my planning a bit. I will aim to get a release with this fix out by the end of the week

**Comment by idxsmr** [comment]
Thank you...
