### ISSUE TITLE
Unable to Get GUI

### ISSUE THREAD

**Issue by abishekabi** [ansible-semaphore/semaphore#54]
After running node *bin/semaphore.js* , i get the error 

root@puppetmaster:/home/sateam/semaphore-master# node bin/semaphore.js 
 [trace] app.js:110  Semaphore listening on port 5000
 [trace] app.js:47  Mongodb connection established

GET / 304 487.081 ms - -
  LESS File error : '../vendor/fontawesome/less/font-awesome.less' wasn't found. Tried - /home/sateam/semaphore-master/public/vendor/fontawesome/less/font-awesome.less,../vendor/fontawesome/less/font-awesome.less
  LESS File : /home/sateam/semaphore-master/public/css/semaphore.less 13:0
GET /vendor/requirejs/require.js 304 73.432 ms - -
Error: '../vendor/fontawesome/less/font-awesome.less' wasn't found. Tried - /home/sateam/semaphore-master/public/vendor/fontawesome/less/font-awesome.less,../vendor/fontawesome/less/font-awesome.less

------------------------------------------------------------------------------------------------------------------------
At the browser end i am able to see only   * Loading... * text

**Comment by matejkramny** [comment]
Ok, seems like bower dependencies aren't installed.

`bower install` might do the trick

**Comment by matejkramny** [comment]
Please reopen if the issue isn't fixed.

Thanks

**Comment by abishekabi** [comment]
Thanks for help, issue got fixed, does this support svn repositories instead of git
