### ISSUE TITLE
Semaphore doesn't create ssh key for template when inventory and playbook repo use different key

### ISSUE THREAD

**Issue by JontiH** [ansible-semaphore/semaphore#547]
I have a server I have setup that runs semaphore. The playbook repo is local, and the inventory is static. 

I initially used my own ssh key to test everything out, and then decided to add an "admin" user to execute my playbooks. So I created a new ssh key, sent it out etc. But even though I could manually ssh to my other servers as this user just fine, semaphore kept saying :

UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).\r\n", "unreachable": true}

I spent a lot of time trying to figure out what the issue and finally realized that the /tmp/semaphore/access_key for my admin key was not getting created. I fixed this by using that key for the inventory and repo, but I don't see why I should need to do that when I don't use an ssh key for either of those seeing as they are directories.

steps to reproduce: 
1.have 2 ssh keys. 
2.Use the first for the playbook repo and inventory
3.Use the second for the actual template.
4.After running the template, your semaphore folder will only have the access_key and access_key_-cert.pub for the first key

**Comment by fiftin** [comment]
Hi @JontiH,

Problem was with template key, it never used. I removed it.

Inventory Key - used to access to servers.
Repo Key - used for clone git repository.
