### ISSUE TITLE
Migration script fails on inserting new field in users table 

### ISSUE THREAD

**Issue by feistus** [ansible-semaphore/semaphore#548]
Hi folks,

I did a fresh setup (v2.5.1) and when performing the setup, the migration tool stumbles on altering the users table (see error below).

I'm unsing the mysql docker container as recommended in the install instructions.

panic: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'admin BOOLEAN NOT NULL DEFAULT 1 AFTER password' at line 1

**Comment by twhiston** [comment]
what mysql version are you using? I've been setting this up regularly in docker without issues, however mysql 8 will not work currently

**Comment by feistus** [comment]
Oh, ok, I'm using 8.0.11. That's the problem then. I'll try a lower version. Thank you!
