### ISSUE TITLE
Is project still alive? 

### ISSUE THREAD

**Issue by QIvan** [ansible-semaphore/semaphore#55]
Hello @matejkramny ! Do you develop this project or it's needed to fork this repo?

**Comment by matejkramny** [comment]
This project is still alive (ie - i haven't abandoned it).

I have plans for it, however it has been exceptionally busy in the past 6 months which explains why things haven't been merged or worked on.

**Comment by QIvan** [comment]
It's very good news! Thank you for this project I will track updates
Happy coding! )
