### ISSUE TITLE
New Feature request: ability to add passwords along with keys

### ISSUE THREAD

**Issue by srimandarbha** [ansible-semaphore/semaphore#550]
Hello

I am sorry if this feature was already asked, it would be great if we have ability to add passwords along with keys in semaphore.

Thanks
Rup

**Comment by garthvh** [comment]
I would second this request, all of my playbooks use keys, except the initial setup playbook that sets the key which I need to run using username and password

**Comment by fiftin** [comment]
Done, use Access key with type `Login with password`.
