### ISSUE TITLE
https proxy and "api/router.go" implementation

### ISSUE THREAD

**Issue by verybigbadboy** [ansible-semaphore/semaphore#552]
Hi guys, I have issue related to setup nginx (no js/css resources loaded)
I believe it is issue related to string compare in "api/router.go"

Initially I see variable path set to "/". variable path changed to "/html/index.html".
https://github.com/ansible-semaphore/semaphore/blob/9a20b17320df58719a3e409549ed2d6821ba603f/api/router.go#L139

but some lines later code has check for  path == "html/index.html".
https://github.com/ansible-semaphore/semaphore/blob/9a20b17320df58719a3e409549ed2d6821ba603f/api/router.go#L153
issue is it checks without leading "/". It means "web_host" config parameter is never used,

My nginx config is similar to:
location /semaphore/ {
...
  proxy_pass http://localhost:3000/;
}

My config file has line "web_host": "https://hostname/semaphore/"

**Comment by verybigbadboy** [comment]
it was broken by https://github.com/ansible-semaphore/semaphore/commit/b745ec6fa2af29fd012673cc3243530bf84147ce#diff-78db7d6f9aaaa6067b74141a9f9aaa90L129

**Comment by strangeman** [comment]
Fixed in https://github.com/ansible-semaphore/semaphore/pull/569, can you review, please?

**Comment by verybigbadboy** [comment]
yes it is working fine. thank you
