### ISSUE TITLE
Cannot connect to database

### ISSUE THREAD

**Issue by opnine** [ansible-semaphore/semaphore#553]
Hello,

Executing this for the first time, and getting this error:

Cannot connect to database!
 This authentication plugin is not supported:
docker ps -a
50c2fd6b5f29        mysql               "docker-entrypoint..."   5 minutes ago       Up 5 minutes        127.0.0.1:3306->3306/tcp   mysql

Docker version 1.13.1, build 94f4240/1.13.1

OS: Centos 7

**Comment by aarisr** [comment]
Check that you have auth_socket plugin loaded
```
cat /etc/mysql/mariadb.conf.d/50-server.cnf  | grep auth
plugin-load-add = auth_socket.so
# * Unix socket authentication plugin is built-in since 10.0.22-6
# Needed so the root database user can authenticate without a password but
# See https://mariadb.com/kb/en/unix_socket-authentication-plugin/

```

Also check this out: https://solidfoundationwebdev.com/blog/posts/how-to-fix-mysql-error-1524-hy000-plugin-auth_socket-is-not-loaded-in-mysql-5-7
