### ISSUE TITLE
gpg public key

### ISSUE THREAD

**Issue by ha02148** [ansible-semaphore/semaphore#555]
Hi,

Where do I get the public key to verify the checksum signature?

Thanks

**Comment by strangeman** [comment]
Hi! It published in Readme:

```
Release Signing

All releases after 2.4.1 are signed with the gpg public key 9B25 8A9C 32B9 7E50 E753 3575 DE95 8D8F 20C7 845F
```

**Comment by ha02148** [comment]
Thanks

I was able to get the key with the following.

gpg --recv-keys 20C7845F
