### ISSUE TITLE
Load balancing and HA

### ISSUE THREAD

**Issue by ha02148** [ansible-semaphore/semaphore#556]
Hi,

I have Semaphore behind our load balancer with the following URL.

https://mycompany.com/semaphore

The web_host is also set to the same.

I got the same issue as https://github.com/ansible-semaphore/semaphore/issues/552.

![image](https://user-images.githubusercontent.com/5472821/43960415-ed33a56a-9c7f-11e8-8603-2e0c3459285d.png)

Anyway to fix this beside using the URL https://semaphore.mycompany.com?

Also, any issue with 2 instances of Semaphore for load balancing and HA?

Thanks

**Comment by ha02148** [comment]
I was able to get it to work by getting the source, update the router.go, and build the binary.

diff router.go router.go_orig
36c36
<       api := r.Group("/semaphore/api")
---
>       api := r.Group("/api")
128c128
<       if strings.HasPrefix(path, "/semaphore/api") {
---
>       if strings.HasPrefix(path, "/api") {
133c133
<       if !strings.HasPrefix(path, "/semaphore/public") {
---
>       if !strings.HasPrefix(path, "/public") {
142c142
<       path = strings.Replace(path, "/semaphore/public/", "", 1)
---
>       path = strings.Replace(path, "/public/", "", 1)
153c153
<       if util.WebHostURL != nil {
---
>       if util.WebHostURL != nil && path == "html/index.html" {

**Comment by strangeman** [comment]
Can you make a pull request, please?

**Comment by strangeman** [comment]
Fixed in https://github.com/ansible-semaphore/semaphore/pull/569, can you review, please?

**Comment by megakoresh** [comment]
Why is this still open?
