### ISSUE TITLE
Export reports

### ISSUE THREAD

**Issue by Serienmorder** [ansible-semaphore/semaphore#557]
Is there any interest in a reporting feature to show to upper management/customers, rather than the text output that is currently provided? If you've used Nessus, I imagine something similar to that.

**Comment by strangeman** [comment]
What kind of reports did you need? Semaphore just launching tasks and shows their status. For a detailed analysis, you can use something like Ara (https://github.com/openstack/ara).

**Comment by Serienmorder** [comment]
More or less I guess what Ara does. So would I run Ara beside Semaphore?

**Comment by strangeman** [comment]
Sure. You can add Ara lookup plugin to your playbooks repo and setup server-side part on the same machine that runs Semaphore.
