### ISSUE TITLE
Using local repository

### ISSUE THREAD

**Issue by mramirezacr** [ansible-semaphore/semaphore#558]
We'd like to use a local repository for Semaphore.  I created a new directory /etc/ansible/playbooks:

drwxrwxrwx. 2 root root    27 Aug 20 12:57 playbooks

I put a playbook in that directory and set up the template to run a touch_file.yml test playbook inside this directory.  But when I did a dry run of the template, I got this...

12:59:45: Started: 3
12:59:45: Run task with template: Touch File

12:59:45: access key ansible installed
12:59:45: Cloning repository /etc/ansible/playbooks
12:59:45: Failed updating repository: exit status 128
12:59:45: fatal: repository '/etc/ansible/playbooks' does not exist
12:59:45: access key ansible installed
12:59:45: Cloning repository /etc/ansible/playbooks
12:59:45: Failed updating repository: exit status 128
12:59:45: fatal: repository '/etc/ansible/playbooks' does not exist

The directory exists, but above error shows up.  Can you use local directories for playbooks or am I forced to use Git?  If local repositories are allowed, any help in setting this up?  Am I running into permissions problems?

**Comment by strangeman** [comment]
Duplicate https://github.com/ansible-semaphore/semaphore/issues/327

**Comment by strangeman** [comment]
@mramirez-t look at this: https://github.com/ansible-semaphore/semaphore/issues/327#issuecomment-295477387

**Comment by apo208** [comment]
adding this may help for local repo/ testing


```
    volumes:
      - /etc/ansible:/home/semaphore
```

**Comment by anjoze** [comment]
After trying about 300 times I can run a local repository
I've done a tutorial with my example (attachment
[Semaphore_docker.pdf](https://github.com/user-attachments/files/17934474/Semaphore_docker.pdf)
)
