### ISSUE TITLE
Windows / WinRM Support?

### ISSUE THREAD

**Issue by prelegalwonder** [ansible-semaphore/semaphore#56]
I've been having issues similar to [issue 23](https://github.com/ansible-semaphore/semaphore/issues/23) except I get the bugsnag ENOENT when semaphore goes to execute the playbook. 

I've tried running it with debug logs as well as strace but can't tell why I'm getting the spawn error on ansible-playbook. 

I've confirmed that I can run the ansible-playbook command manually against the downloaded playbook. Git is installed and semaphore connects to git just fine and downloads the playbook. 

I tried debugging the runner.js but I'm no whiz at javascript and I couldn't find anything out of place and I'm guessing it's either an issue with my vault key or the fact that I'm using winrm?

Here's the basic error -

```
 node /srv/semaphore/bin/semaphore.js
app.js:110 Semaphore listening on port 80
app.js:47 Mongodb connection established


express deprecated res.send(status): Use res.sendStatus(status) instead ../srv/semaphore/lib/routes/task/tasks.js:79:6
::ffff:10.10.0.50 - - [22/Dec/2015:14:54:13 +0000] "POST /playbook/56787e7e389c472a006f0d6c/job/56787ece389c472a006f0d6d/run HTTP/1.1" 201 7 "http://semaphore-host.example.com/playbook/56787e7e389c472a006f0d6c/jobs" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36"
runner.js:240 Updating SSH Keys

runner.js:240 SSH Keys Updated.

runner.js:240
Downloading Playbook.

runner.js:240 Cloning into 'playbook_56787e7e389c472a006f0d6c'...

runner.js:240

Playbook Downloaded.

runner.js:240
Set up Ansible Hosts file with contents:
[windows]
192.168.1.10


runner.js:240
Starting play config/2012/Base.yml.

../node_modules/bugsnag/lib/logger.js:29 Bugsnag:  Error: spawn ansible-playbook ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1054:32)
    at child_process.js:1145:20
    at process._tickDomainCallback (node.js:381:11)
```
I've attached more detailed logs (strace and node-debug) as well as my customized Dockerfile if you want to try and reproduce. I needed a later ansible to get some of the newer win_modules.
 
This is nodejs v0.12.9

[semaphore_logs.zip](https://github.com/ansible-semaphore/semaphore/files/69820/semaphore_logs.zip)

[Dockerfile-sempahore.txt](https://github.com/ansible-semaphore/semaphore/files/69824/Dockerfile-sempahore.txt)

**Comment by prelegalwonder** [comment]
I believe I just ruled out vault issues by decrypting the one vault protected group_vars yml and creating a new playbook that doesn't leverage vault at all.

**Comment by prelegalwonder** [comment]
I've identified the issue. Its partly due to my custom docker file and where it installs ansible, and partly due to the fact that runner.js has hard-coded environment variables. 

What do you think about doing a loop over the existing environment variables and adding them to runner? 

What I had to modify was PATH, so maybe make PATH what you've currently got it set as then append :$PATH  

As well as adding other ENV vars (I added PYTHONPATH) to the nodejs env for spawn?

**Comment by matejkramny** [comment]
Hmm that should be configured in the ansible admin console and not when running.

How are you running semaphore?

I haven't tested semaphore on windows but its node.js / docker therefore I assumed it would be ok. The paths in runner.js expect a UNIX sort of system.

**Comment by prelegalwonder** [comment]
Sorry,

I could have been more clear. My ansible server / source is a docker linux system. The nodes I'm managing are Windows over winrm. Regardless, it wasn't windows / winrm related as I had initially thought. 

You mentioned ansible admin console is where ENV vars and PATH should be set, what url/uri would that be in Semaphore? (I probably just missed it). 

If you want to reproduce what I'm seeing, I attached my Dockerfile in the first post. You can remove all of the artifactory and openssl stuff thats specific to me just running in a corp environment. 

I'll poke around a bit more in semaphore and see if I can find what you're referring to and if not, fork and submit a PR and see what you think.

Cheers,
Andrew

**Comment by matejkramny** [comment]
Right I was suggesting that if the ENV paths were to be configurable then it should be via the config in the web interface.

See if changing the paths here: https://github.com/ansible-semaphore/semaphore/blob/master/lib/runner.js#L206 lead to anything.

Locate the ansible-playbook binary and add it to the path. See if that works and ping back! :)

Cheers,
Matej

**Comment by prelegalwonder** [comment]
Yep, thats the issue. I've got ansible-playbook in my $PATH but runner.js sets a specific environment that doesn't take into account the existing environment. When I added my path to ansible on that line it works fine. 

Using that as a work-around, will see if I can submit a PR to pull in existing ENV when executing runner unless you can think of reasons you wouldn't want that to be default behavior.

**Comment by matejkramny** [comment]
What is the path that you needed?

It might be good to use that path while semaphore is running under your environment.

**Comment by prelegalwonder** [comment]
@matejkramny 

What do you think about these for a PR? 

Essentially for the PATH, just prepend existing ENV PATH, and for PYTHONPATH, if it's not set, it shouldn't impact anything since you're not setting it in the runner.js already?

Changes:
pullGit - [PATH](https://github.com/prelegalwonder/semaphore/blob/feature/fix-environment/lib/runner.js#L134)
playTheBook - [PATH](https://github.com/prelegalwonder/semaphore/blob/feature/fix-environment/lib/runner.js#L206) and [PYTHONPATH](https://github.com/prelegalwonder/semaphore/blob/feature/fix-environment/lib/runner.js#L208)

**Comment by matejkramny** [comment]
https://github.com/prelegalwonder/semaphore/commit/199b82a69934b61ab793936fa815e4d6cb0398c8 looks ok.

If you make a PR i can merge that straight away..

Thanks

**Comment by corystein** [comment]
This is a workaround to use WinRM.

https://www.ansible.com/blog/connecting-to-a-windows-host
