### ISSUE TITLE
The purpose of the ssh key field of the template is unknown.

### ISSUE THREAD

**Issue by dahyungKwon** [ansible-semaphore/semaphore#560]
Hi,
I encountered a problem while running the template.

After registering playbooks repository and inventory, I created new template and run ansible.

At this time, it was not log into the inventory’s servers. The reason is that ssh key registration is wrong.

When I created the template, I registered the ssh key for log into the servers.
However when I run ansible using the template, semaphore doesn’t generate the ssh key registered in the template.

I found that using the ssh key in inventory to log into the servers, I solved the problem.
But I was confused by the template's ssh key field.
What is the purpose of the ssh key registered in the template?

<img width="590" alt="2018-09-05 1 02 16" src="https://user-images.githubusercontent.com/16604419/45043500-439a9a80-b0a8-11e8-84b3-a3f0118e64cf.png">

It looks like a problem with [#547](https://github.com/ansible-semaphore/semaphore/issues/547).

**Comment by Liaipon** [comment]
If there is only one ssh key, the key will be regenerated every time when the task is running, which takes 5s.

**Comment by fiftin** [comment]
Removed
