### ISSUE TITLE
Updating Ansible Semaphore Task template fails to run the YML file properly

### ISSUE THREAD

**Issue by kaleescts** [ansible-semaphore/semaphore#561]
After CLI arguments through Ansible Semaphore Update Template API, are updated, if i hit Start Job URL , it is not running the playbook properly. It is working if i manually run the commit.sh file.
Can you tell me what is the issue here?

**Comment by kaleescts** [comment]
16:05:03: Started: 783
16:05:03: Run task with template: patch2

16:05:03: access key Key installed
16:05:03: Updating repository /root/ansiblerepo
16:05:04: From /root/ansiblerepo
16:05:04:  * branch            master     -> FETCH_HEAD
16:05:05: Already up-to-date.
16:05:05: access key Key installed
16:05:05: installing static inventory
16:05:11: Usage: ansible-playbook [options] playbook.yml [playbook2 ...]
16:05:11: 
16:05:11: Runs Ansible playbooks, executing the defined tasks on the targeted hosts.
16:05:11: 
16:05:11: Options:
16:05:11:   --ask-vault-pass      ask for vault password
16:05:11:   -C, --check           don't make any changes; instead, try to predict some
16:05:11:                         of the changes that may occur
16:05:11:   -D, --diff            when changing (small) files and templates, show the
16:05:11:                         differences in those files; works great with --check
16:05:11:   -e EXTRA_VARS, --extra-vars=EXTRA_VARS
16:05:11:                         set additional variables as key=value or YAML/JSON, if
16:05:11:                         filename prepend with @
16:05:11:   --flush-cache         clear the fact cache
16:05:11:   --force-handlers      run handlers even if a task fails
16:05:11:   -f FORKS, --forks=FORKS
16:05:11:                         specify number of parallel processes to use
16:05:11:                         (default=5)
16:05:11:   -h, --help            show this help message and exit
16:05:11:   -i INVENTORY, --inventory=INVENTORY, --inventory-file=INVENTORY
16:05:11:                         specify inventory host path or comma separated host
16:05:11:                         list. --inventory-file is deprecated
16:05:11:   -l SUBSET, --limit=SUBSET
16:05:11:                         further limit selected hosts to an additional pattern
16:05:11:   --list-hosts          outputs a list of matching hosts; does not execute
16:05:11:                         anything else
16:05:11:   --list-tags           list all available tags
16:05:11:   --list-tasks          list all tasks that would be executed
16:05:11:   -M MODULE_PATH, --module-path=MODULE_PATH
16:05:11:                         prepend colon-separated path(s) to module library
16:05:11:                         (default=[u'/root/tempfiles/.ansible/plugins/modules',
16:05:11:                         u'/usr/share/ansible/plugins/modules'])
16:05:11:   --new-vault-id=NEW_VAULT_ID
16:05:11:                         the new vault identity to use for rekey
16:05:11:   --new-vault-password-file=NEW_VAULT_PASSWORD_FILES
16:05:11:                         new vault password file for rekey
16:05:11:   --skip-tags=SKIP_TAGS
16:05:11:                         only run plays and tasks whose tags do not match these
16:05:11:                         values
16:05:11:   --start-at-task=START_AT_TASK
16:05:11:                         start the playbook at the task matching this name
16:05:11:   --step                one-step-at-a-time: confirm each task before running
16:05:11:   --syntax-check        perform a syntax check on the playbook, but do not
16:05:11:                         execute it
16:05:11:   -t TAGS, --tags=TAGS  only run plays and tasks tagged with these values
16:05:11:   --vault-id=VAULT_IDS  the vault identity to use
16:05:11:   --vault-password-file=VAULT_PASSWORD_FILES
16:05:11:                         vault password file
16:05:11:   -v, --verbose         verbose mode (-vvv for more, -vvvv to enable
16:05:11:                         connection debugging)
16:05:11:   --version             show program's version number and exit
16:05:11: 
16:05:11:   Connection Options:
16:05:11:     control as whom and how to connect to hosts
16:05:11: 
16:05:11:     -k, --ask-pass      ask for connection password
16:05:11:     --private-key=PRIVATE_KEY_FILE, --key-file=PRIVATE_KEY_FILE
16:05:11:                         use this file to authenticate the connection
16:05:11:     -u REMOTE_USER, --user=REMOTE_USER
16:05:11:                         connect as this user (default=None)
16:05:11:     -c CONNECTION, --connection=CONNECTION
16:05:11:                         connection type to use (default=smart)
16:05:11:     -T TIMEOUT, --timeout=TIMEOUT
16:05:11:                         override the connection timeout in seconds
16:05:11:                         (default=10)
16:05:11:     --ssh-common-args=SSH_COMMON_ARGS
16:05:11: ERROR! You must specify a playbook file to run
16:05:11:                         specify common arguments to pass to sftp/scp/ssh (e.g.
16:05:11:                         ProxyCommand)
16:05:11:     --sftp-extra-args=SFTP_EXTRA_ARGS
16:05:11:                         specify extra arguments to pass to sftp only (e.g. -f,
16:05:11:                         -l)
16:05:11:     --scp-extra-args=SCP_EXTRA_ARGS
16:05:11:                         specify extra arguments to pass to scp only (e.g. -l)
16:05:11:     --ssh-extra-args=SSH_EXTRA_ARGS
16:05:11:                         specify extra arguments to pass to ssh only (e.g. -R)
16:05:11: 
16:05:11:   Privilege Escalation Options:
16:05:11:     control how and which user you become as on target hosts
16:05:11: 
16:05:11:     -s, --sudo          run operations with sudo (nopasswd) (deprecated, use
16:05:11:                         become)
16:05:11:     -U SUDO_USER, --sudo-user=SUDO_USER
16:05:11:                         desired sudo user (default=root) (deprecated, use
16:05:11:                         become)
16:05:11:     -S, --su            run operations with su (deprecated, use become)
16:05:11:     -R SU_USER, --su-user=SU_USER
16:05:11:                         run operations with su as this user (default=None)
16:05:11:                         (deprecated, use become)
16:05:11:     -b, --become        run operations with become (does not imply password
16:05:11:                         prompting)
16:05:11:     --become-method=BECOME_METHOD
16:05:11:                         privilege escalation method to use (default=sudo),
16:05:11:                         valid choices: [ sudo | su | pbrun | pfexec | doas |
16:05:11:                         dzdo | ksu | runas | pmrun ]
16:05:11:     --become-user=BECOME_USER
16:05:11:                         run operations as this user (default=root)
16:05:11:     --ask-sudo-pass     ask for sudo password (deprecated, use become)
16:05:11:     --ask-su-pass       ask for su password (deprecated, use become)
16:05:11:     -K, --ask-become-pass
16:05:11:                         ask for privilege escalation password
16:05:11: Running playbook failed: exit status 5

**Comment by kaleescts** [comment]
Any inputs on this?

**Comment by strangeman** [comment]
> 16:05:11: ERROR! You must specify a playbook file to run

Looks like you pass wrong arguments, or trying to call not existed playbook. Can you show what arguments you're set?
