### ISSUE TITLE
How to input environment variables from semaphore UI or replace environment variables of OS

### ISSUE THREAD

**Issue by vantinhuynh** [ansible-semaphore/semaphore#562]
I use the Semaphore for as a tool to run Ansible Playbook.
I got the problem with our playbook that will initial AWS environment (create VPC, EC2,...).
This playbook needs to call aws credentials, I have tried 2 ways:
- Create playbook task to create credentials file under ~/.aws/
- Input credentials of AWS use Environment of semaphore
But the playbook cannot get the correct credential as I expect => So my playbook always failed when running from semaphore UI.

But I log in to semaphore container  and run from the command line it the successful

**Comment by strangeman** [comment]
Can you provide more details? Which module you're using, playbook example etc.
