### ISSUE TITLE
init user/pwd

### ISSUE THREAD

**Issue by TedWithAHammer** [ansible-semaphore/semaphore#570]
![image](https://user-images.githubusercontent.com/9396361/48000229-d3f46a80-e13f-11e8-9e8f-12ebd3f1b3f3.png)
i just start semaphore on centos7,everything seems ok,but i can not find any user/pwd info from the console log,even i restart the semaphore

**Comment by strangeman** [comment]
How you launch it? If you use Docker - default login/password sets in ENV variables `SEMAPHORE_ADMIN_PASSWORD` and `SEMAPHORE_ADMIN_NAME`. If you launch binary - semaphore will ask login/password when you did `semaphore -setup`.

**Comment by TedWithAHammer** [comment]
![image](https://user-images.githubusercontent.com/9396361/48036427-52362880-e1a3-11e8-91ee-7e4c3a4d39f6.png)
i just launch mysql in docker,but semaphore in rpm,i just run setup again ,but i can not find the user/pwd tip,or anything wrong with my config

**Comment by TedWithAHammer** [comment]
![image](https://user-images.githubusercontent.com/9396361/48036633-2c5d5380-e1a4-11e8-9b78-6d1094b15753.png)
i just rerun the setup,and it show no step asking for user or pwd

**Comment by TedWithAHammer** [comment]
tks,i just rerun setup
