### ISSUE TITLE
LDAP error -1 Request Failed. Try again later.

### ISSUE THREAD

**Issue by igalvarez** [ansible-semaphore/semaphore#571]
I'm using version 2.5.1 on red hat linux. I have setup ldap as you can see below:

 
{
        "mysql": {
                "host": "127.0.0.1:3306",
                "user": "root",
                "pass": "DBpasswd",
                "name": "semaphore"
        },
        "port": "",
        "tmp_path": "/tmp/semaphore",
        "cookie_hash": "EYjMkDCR5e9JXSnPmHc3/34KFt+0K5pEeljnPUjeUus=",
        "cookie_encryption": "YEqSUyaLdOhi4NiVNwiMgbwwMQFzA9Tmu+Vz4r4dWEQ=",
        "email_sender": "semaphore@anssysprd.domain.net",
        "email_host": "localhost",
        "email_port": "25",
        "web_host": "http://anssysprd.domain.net:8010",
        "ldap_binddn": "CN=Usuari AIX cust,OU=Serveis,OU=Usuaris Especials,OU=CUSTOMER,DC=domain,DC=net",
        "ldap_bindpassword": "passwd",
        "ldap_server": "domain.net:389",
        "ldap_searchdn": "OU=Usuaris Oberts,OU=CUSTOMER,DC=domain,DC=net",
        "ldap_searchfilter": "(&(sAMAccountName=%s))",
        "ldap_mappings": {
                "dn": "dn",
                "mail": "mail",
                "uid": "uid",
                "cn": "cn"
        },
        "telegram_chat": "",
        "telegram_token": "",
        "concurrency_mode": "",
        "max_parallel_tasks": 0,
        "email_alert": true,
        "telegram_alert": false,
        "ldap_enable": true,
        "ldap_needtls": false
 }
`
First login, using LDAP authentication worked OK!, you can login successfully to semaphore, but if you authenticate again it show this error:
  -1 Request Failed. Try again later.

Is it a known issue?

Thanks much!
Israel.

**Comment by fiftin** [comment]
Hi, please check release 2.7.2
