### ISSUE TITLE
env problem

### ISSUE THREAD

**Issue by liliyongleo** [ansible-semaphore/semaphore#573]
Please help.
I tried to execute playbook with semaphore, in my playbook, 
- include_tasks: "{{ network_type }}.yaml"

which tried to pass variables "network_type" to it.  
I add an environment as below, 
{
    "network_type": "calico"
}

but still, it runs with error:
-----------------------------------------------------
The offending line appears to be:

- include_tasks: "{{ network_type }}.yaml"
  ^ here
We could be wrong, but this one looks like it might be an issue with
missing quotes.  Always quote template expression brackets when they
start a value. For instance:

    with_items:
      - {{ foo }}

**Comment by liliyongleo** [comment]
when I run following command instead of semaphore, it worked. 
ansible-playbook -e env.yaml playbook/install.yaml

**Comment by fiftin** [comment]
Works similar in v2.6.6.
