### ISSUE TITLE
2.5.1 running the application gives this error

### ISSUE THREAD

**Issue by ghost** [ansible-semaphore/semaphore#577]
When starting version 2.5.1 we see this
Semaphore v2.5.0
Port :3000
MySQL root@127.0.0.1:3306 semaphore
Tmp Path (projects home) /tmp/semaphore
Checking DB migrations
Executing migration v1.1.0 (at 2019-02-06 08:28:09.564530851 +0000 UTC m=+0.060271208)...
 [1/1]WARN[0000]
 ERR! Query: /* update precision of output logs - also prevents confusion when sorting the table to guarantee it is in the same order */
alter table task__output change `time` `time` datetime(6) not null;

Rolling back v1.1.0 (time: 2019-02-06 08:28:09.565085519 +0000 UTC m=+0.060825789)...
Rollback SQL does not exist.

panic: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(6) not null' at line 2

goroutine 1 [running]:
main.main()
	/go/src/github.com/ansible-semaphore/semaphore/cli/main.go:52 +0x5a1

the datatime on mysql can't be ()

**Comment by Serverfrog** [comment]
Could reproduce that with a fresh installed Debian System with mysql 5.5.62 und semaphore 2.5.1

```
root@testmachine:/opt/semaphore# semaphore -config config.json
Using config file: config.json
Semaphore v2.5.1
Port :3000
MySQL root@127.0.0.1:3306 semaphore
Tmp Path (projects home) /opt/semaphore/tmp/playbook
Checking DB migrations
Executing migration v1.1.0 (at 2019-09-10 17:41:27.211562901 +0200 CEST m=+0.050863252)...
 [1/1]WARN[0000]
 ERR! Query: /* update precision of output logs - also prevents confusion when sorting the table to guarantee it is in the same order */
alter table task__output change ´time´ ´time´ datetime(6) not null;


Rolling back v1.1.0 (time: 2019-09-10 17:41:27.212158214 +0200 CEST m=+0.051458548)...
Rollback SQL does not exist.

panic: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(6) not null' at line 2

goroutine 1 [running]:
main.main()
        /go/src/github.com/ansible-semaphore/semaphore/cli/main.go:52 +0x5a1


root@testmachine:/opt/semaphore# mysql --version
mysql  Ver 14.14 Distrib 5.5.62, for debian-linux-gnu (x86_64) using readline 6.3

```

**Comment by fiftin** [comment]
https://github.com/ansible-semaphore/semaphore/issues/90

MySQL 5.6.4 or greater or MariaDB 5.3 or greater required.
