### ISSUE TITLE
I was able to delete admin user

### ISSUE THREAD

**Issue by lukaspour** [ansible-semaphore/semaphore#58]
Hi, while trying to change default users password, I have deleted the admin user. Now I can not recreate one or login. I believe the UI should not let user to delete admin user ;-) 

BTW, when this happens, how do I create a new admin user? Directly in MongoDB?

thank you

**Comment by matejkramny** [comment]
Hi, during load it creates a new admin user automatically.

File -> https://github.com/ansible-semaphore/semaphore/blob/master/lib/config.js#L60

I think just restarting the server can do, unless the user still exists in the database. In that case, just nuke the document and restart the server.

**Comment by matejkramny** [comment]
Actually it looks like you might have to delete all users in order for this to create the admin user.
