### ISSUE TITLE
Security issue: SSH private key stays plaintext in Semaphore homedir after runnning task

### ISSUE THREAD

**Issue by divxdigit** [ansible-semaphore/semaphore#580]
A SSH has been inserted in the Key Store. After running a task, the file 'access_key_1' with private key is created in the Semaphore home directory. Permission 'rw' for the semaphore user.
But after the task has finished, this file is not cleaned up.

**Comment by pedroelbanquero** [comment]
this is solved ?? i can't reproduce, can you give me more details ? SO, path ..

**Comment by divxdigit** [comment]
As far as I know, the private key is still saved in the playbook path provided at the install of Semaphore at step Playbook path (default /tmp/semaphore) .

**Comment by dR3b** [comment]
@divxdigit 
What you say is true. The permissions are set as follows:
```bash
-rw------- 1 bla bla  399 10. Mär 16:08 access_key_1
-rw------- 1 bla bla   90 10. Mär 16:08 access_key_1-cert.pub
```

**Comment by ForrestFeng** [comment]
**A workround:** 
You can run the semaphore as root user(sudo) or run it as a service.
This way only the root user has the read-write permission for the keys.

This can prevent most users from seeing the keys.

**Comment by dR3b** [comment]
Running tools like Semaphore as "root" is not very useful for security reasons.

**Comment by fiftin** [comment]
What behavior should be in your opinion? Should Semaphore delete private key after running playbook? Will that be enough?

**Comment by shunkica** [comment]
The private key is also stored plain-text in the database.
Maybe a solution would be to start semaphore with some variable, eg. "secret_key", encrypt the private key using the secret, then decrypt only on-demand in the memory.
This way the private keys are encrypted at rest.

It would also be a good idea do remove display of private keys in the UI.

**Comment by gaia** [comment]
> The private key is also stored plain-text in the database.
> Maybe a solution would be to start semaphore with some variable, eg. "secret_key", encrypt the private key using the secret, then decrypt only on-demand in the memory.
> This way the private keys are encrypted at rest.
> 
> It would also be a good idea do remove display of private keys in the UI.

Given the current way Semaphore handles private keys, it seems that the only way to be reasonably secure is to use a very high entropy passphrase for the SSH private key. But I have not figured out [how to pass the passphrase to Semaphore](https://github.com/ansible-semaphore/semaphore/issues/687).

**Comment by pedroelbanquero** [comment]
deprecate RSA

**Comment by gaia** [comment]
> deprecate RSA

RSA? all keys we use are ed25519

**Comment by pedroelbanquero** [comment]
nice haha

**Comment by fiftin** [comment]
ansible-playbook use private key from file system only.

**Comment by fiftin** [comment]
I added encryption for private key (for database only): https://github.com/ansible-semaphore/semaphore/blob/74436710592122cf06d73489eed223f8706df5d3/db/AccessKey.go#L40

What do you think?

**Comment by fiftin** [comment]
Summary:

* Added encryption of private key in database
* Added removing private key file after task running
* Removed public key from Access Key
