### ISSUE TITLE
Cannot build for Docker (or maybe at all): unavailable dependency: CastawayLabs/mulekick

### ISSUE THREAD

**Issue by scream314** [ansible-semaphore/semaphore#582]
As the images on Docker Hub are pretty old, I tried to build my own version off the `master` branch, using `semaphore/deployment/docker/prod/`.
The first problem was with `go-task/task`, the installation failed the way it is specified in `deployment/docker/prod/bin/install`. The workaround I found was to install it the  "recommended way" (https://github.com/go-task/task/blob/master/docs/installation.md#install-script):
```
-go get -u -v github.com/go-task/task/cmd/task
+curl -sL https://taskfile.dev/install.sh | sh
+export export PATH="${PATH}:$(pwd)/bin"
```

The second (bigger) issue is, that the dependency `CastawayLabs/mulekick` disappeared/is private.

Is there any way to build a recent version?

**Comment by megakoresh** [comment]
Hey this has been open for almost a month. Following instructions reproduces this 100% of the time. Is this project still maintained or... ?

```
go get -u github.com/golang/dep/cmd/dep
go get github.com/cespare/reflex || true
go get -u github.com/gobuffalo/packr/...
go get -u github.com/haya14busa/goverage
go get github.com/snikch/goodman/cmd/goodman
 curl -L https://github.com/goreleaser/goreleaser/releases/download/v0.67.0/goreleaser_$(uname -s)_$(uname -m).tar.gz | tar -xz -C ${GOPATH}/bin
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   621    0   621    0     0   1778      0 --:--:-- --:--:-- --:--:--  1774
100 3215k  100 3215k    0     0  1109k      0  0:00:02  0:00:02 --:--:-- 2001k
 chmod +x ${GOPATH}/bin/goreleaser
:
go get -u github.com/alecthomas/gometalinter
gometalinter --install
Installing:
  deadcode
  dupl
  errcheck
  gochecknoglobals
  gochecknoinits
  goconst
  gocyclo
  goimports
  golint
  gosec
  gotype
  gotypex
  ineffassign
  interfacer
  lll
  maligned
  misspell
  nakedret
  safesql
  staticcheck
  structcheck
  unconvert
  unparam
  varcheck
dep ensure -vendor-only
grouped write of manifest, lock and vendor: error while writing out vendor tree: failed to write dep tree: failed to export github.com/castawaylabs/mulekick: 
        (1) failed to list versions for https://github.com/castawaylabs/mulekick: fatal: could not read Username for 'https://github.com': terminal prompts disabled
: exit status 128
        (2) failed to list versions for ssh://git@github.com/castawaylabs/mulekick: Warning: Permanently added the RSA host key for IP address '140.82.118.4' to the list of known hosts.
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
: exit status 128
        (3) failed to list versions for git://github.com/castawaylabs/mulekick: fatal: remote error: 
  Repository not found.
: exit status 128
        (4) failed to list versions for http://github.com/castawaylabs/mulekick: fatal: could not read Username for 'https://github.com': terminal prompts disabled
: exit status 128

task: Failed to run task "deps": task: Failed to run task "deps:be": exit status 1
```

@matejkramny Is somehow affiliated with this CastAwayLabs, maybe he can shed some light on this situation

It seems the library is used only for sending responses. Perhaps it would be possible to remove that dependency if the library is no longer available?

**Comment by megakoresh** [comment]
I think @matejkramny doesn't get notification if I edit it into the post. Someone please get on this, it's a critical issue. It's preventing people from contributing to the project

**Comment by HardySimpson** [comment]
agree，I also face this problem

**Comment by HardySimpson** [comment]
It seems that castawaylabs remove mulekick project

**Comment by megakoresh** [comment]
@strangeman Maybe you can help? I am really interested in this project, but if you don't know what that mulekick library does, it's very hard to reverse-engineer it's functions and remove the dependency.

**Comment by strangeman** [comment]
@megakoresh I pushed it from my gopath to https://github.com/strangeman/mulekick, but it doesn't have any license so I'm not sure how legal is it.
Maybe @matejkramny can clear its license?

**Comment by megakoresh** [comment]
> @megakoresh I pushed it from my gopath to https://github.com/strangeman/mulekick, but it doesn't have any license so I'm not sure how legal is it.
> Maybe @matejkramny can clear its license?

I think the safest bet here would be to port those functions directly into semaphore's codebase and remove the dependency (its very few anyway). If the library was under MIT, then it should be perfectly legal. I can do that, though it would be nice to know first the licensing terms.

**Comment by matejkramny** [comment]
Hi all, let me address these points and the issue at hand.

- @strangeman mulekick is indeed under MIT license
- mulekick was removed from our repository due to other reasons (which I cannot state here); lack of foresight caused issues like this arising

The best path forward is to embed it inside this project as @megakoresh mentioned. I'll do this in a bit.
