### ISSUE TITLE
Keep getting 403 from /api/ws

### ISSUE THREAD

**Issue by MikeLing** [ansible-semaphore/semaphore#586]
<img width="972" alt="Screen Shot 2019-07-19 at 9 57 35 AM" src="https://user-images.githubusercontent.com/2166227/61503876-e41d5300-aa0b-11e9-9ba5-189785a324fb.png">

##env:
OS: osx 10.14
lang: golang1.12
semaphore: 2.5.1

**Comment by MikeLing** [comment]
sorry, I got it

**Comment by bkraul** [comment]
@MikeLing, dude what was the issue, and how did you resolve it?
