### ISSUE TITLE
404 not found on all delete and put api

### ISSUE THREAD

**Issue by aidan-777** [ansible-semaphore/semaphore#587]
I run semaphore --config config.json,  and service has been started. But there was something wrong with the put and delete api , they all returned 404 , but post and get api is normal.

![image](https://user-images.githubusercontent.com/14037183/62189936-cef8da80-b3a2-11e9-9204-4ba828c789ff.png)

![image](https://user-images.githubusercontent.com/14037183/62189972-df10ba00-b3a2-11e9-8ea3-5ad9be5d84cd.png)

**Comment by megakoresh** [comment]
Are you building and running latest source code or latest release?

**Comment by re1656** [comment]
> Are you building and running latest source code or latest release?

I run task watch on develop branch

**Comment by aidan-777** [comment]
> Are you building and running latest source code or latest release?

i 'm running on develop branch

**Comment by megakoresh** [comment]
> i 'm running on develop branch

I will try to remember to take a look when I have time. I may have messed something up during routing refactor. Have you tried adding trailing `/` to the `PUT` urls and seeing if they work that way?

**Comment by aidan-777** [comment]
> > i 'm running on develop branch
> 
> I will try to remember to take a look when I have time. I may have messed something up during routing refactor. Have you tried adding trailing `/` to the `PUT` urls and seeing if they work that way?

Thank you !  I just now checkouted  to tag v2.5.1, and the problem was solved.

**Comment by megakoresh** [comment]
@re1656 Really sorry for the long wait. It was not an easy problem to figure out so I put it off for a day and then things happened and I simply forgot about this. Should now be fixed in #588

**Comment by pedroelbanquero** [comment]
here solved more routes DELETE and PUT of @megakoresh version, some mistakes in put and delete actions in route files, no error in the new version but not works if you dont make the changes
#595
