### ISSUE TITLE
Ansible 2.0

### ISSUE THREAD

**Issue by QIvan** [ansible-semaphore/semaphore#59]
Hi!
Ansible 2.0 has arrived http://www.ansible.com/blog/ansible-2.0-launch ! Can you rebuild docker image with new version? Ansible 2.0 is avalible with ```pip install```

Thank!

**Comment by prelegalwonder** [comment]
@QIvan / @matejkramny  -

You can substitute (or just add) [this gist](https://gist.github.com/prelegalwonder/252f7d53c16e70194872) in the checked out repo and build against it. 

I too need 2.x for additional Windows modules. 

Ex. 
```
git clone https://github.com/ansible-semaphore/semaphore.git
cd semaphore
docker build  -t semaphore:ansible2 -f Dockerfile-semaphore .
```

**Comment by matejkramny** [comment]
With semaphore v2, ansible 2 will be supported.

**Comment by matejkramny** [comment]
Closing, is fixed with v2-alpha.
