### ISSUE TITLE
Port 3000

### ISSUE THREAD

**Issue by manishalankala** [ansible-semaphore/semaphore#593]
My grafana also use same default port 3000

after service start i see the error

How can i change this

**Comment by matejkramny** [comment]
probably using the PORT environment variable or by configuration

**Comment by fiftin** [comment]
@manishalankala Do you use Semaphore binary or docker image? Is this issue actual for you?

**Comment by jeanfrancoisgratton** [comment]
This is somewhat critical for me, so yes, the ability to change the default port (through CLI or the JSON config) would be nice.

**Comment by fiftin** [comment]
@jeanfrancoisgratton you can do this using `config.json` option `port`. Docs: https://docs.semui.co/administration-guide/configuration
