### ISSUE TITLE
Develop version not works , put and delete method fails and other issues

### ISSUE THREAD

**Issue by pedroelbanquero** [ansible-semaphore/semaphore#594]
here a working version with the last changes

https://github.com/pedroelbanquero/semaphore

**Comment by jvijay-work** [comment]
Getting the following error with go build

../util/config.go:140:15: undefined: Version

**Comment by pedroelbanquero** [comment]
works fine for me , im again building updates if you need something tell me

**Comment by pedroelbanquero** [comment]
you need to build with task buil, like in the documentation, and check if you are using my develop version

**Comment by fiftin** [comment]
Fixed
