### ISSUE TITLE
Docker bash

### ISSUE THREAD

**Issue by QIvan** [ansible-semaphore/semaphore#60]
How can I get access for bash-shell inside container? Standard way with ```docker exec``` does not work.

```bash
$ docker exec -it semaphore bash 
no such file or directory
```

Thanks!

**Comment by matejkramny** [comment]
I'm not too familiar with how `docker exec` works but you can do `docker run -it --rm semaphore /bin/bash`

**Comment by prelegalwonder** [comment]
@QIvan usually thin containers don't have full bash (like busybox). 

Try `docker exec -ti semaphore sh`

**Comment by QIvan** [comment]
Thank you @prelegalwonder but I've tried this solution already. It's the same error:
```bash
$ docker exec -it semaphore sh
no such file or directory
$ echo $?
255
```

**Comment by QIvan** [comment]
@matejkramny That is not what I'm looking for but it works and can help. Thanks!

**Comment by matejkramny** [comment]
@QIvan i suppose you want to attach to the living container right?

Another trick is to copy the files you need with `docker cp`

**Comment by QIvan** [comment]
Honestly this question is connected with next issue https://github.com/ansible-semaphore/semaphore/issues/59 . I just want to update ansible inside my production semaphore )

**Comment by matejkramny** [comment]
@QIvan the best way is to build on top of the semaphore image and update ansible.
