### ISSUE TITLE
Question: Semaphore fork

### ISSUE THREAD

**Issue by detvan** [ansible-semaphore/semaphore#605]
Hi all,

since this project is no longer maintained, please do you know about well maintained fork?

Thank you

**Comment by fiftin** [comment]
@strangeman are you still interested in this project? Is your fork actual?

**Comment by fiftin** [comment]
May be this https://github.com/CodyGuo/semaphore? @CodyGuo what do you think?

**Comment by strangeman** [comment]
@fiftin unfortunately, we're dropped support of Semaphore and moved to Rundeck.

**Comment by CodyGuo** [comment]
@fiftin our department is using this, and I'm only doing partial function maintenance, but I don't have enough ability to make continuous improvement.

**Comment by detvan** [comment]
@strangeman thanks for good reference for RunDeck with nice community i will try it. AWX, is pretty heavy for me - no single app, just container. Tower is commercial.

**Comment by fiftin** [comment]
@detvan I'm not going to give up using the Semaphore. We use modified version of Semaphore in conjunction with https://github.com/jorkey/update (our internal development) and it is works fine. 

I created fork https://github.com/ansiphore/ansiphore. I want to move the project towards CI. I merged https://github.com/ansible-semaphore/semaphore/pull/595 to it and published release https://github.com/ansiphore/ansiphore/releases/tag/v2.5.5.

Next step: review and merge https://github.com/ansible-semaphore/semaphore/pull/473.

**Comment by detvan** [comment]
@fiftin your code is really nice. Ansible is industry standard, so i would prefer it, but RunDeck has big advantage - single war file. Thus you can easily keep it up to date and run it by single command: java -Xmx4g -jar rundeck-3.3.3-20200910.war.

It would be nice to have similar single package of Ansiphore (just boom, one click, it is up and running :) ). I know, it is for your internal usage, you are working on it, spending your own time, because of your needs, but maybe once your project will be famous.

**Comment by fiftin** [comment]
@detvan, @CodyGuo, @strangeman I continue to develop the project in the current repository.

**Comment by CodyGuo** [comment]
thanks
