### ISSUE TITLE
[feature request] Indicate when everything is done loading and server is running

### ISSUE THREAD

**Issue by markfaine** [ansible-semaphore/semaphore#614]
See the log message below:

```
Attempting to connect to database semaphore on tasks.mariadb:3306 with user semaphore ...
Using config file: /home/bean/semaphore/config.json
Semaphore v2.5.2
Interface tasks.semaphore
Port :3000
MySQL semaphore@tasks.mariadb:3306 semaphore
Tmp Path (projects home) /tmp/semaphore
Checking DB migrations
```
It's just a little ambiguous. I don't know if it's done and the server is running or it's still checking db migrations.  I guess it usually doesn't matter except for when you are trying to troubleshoot.

**Comment by fiftin** [comment]
Done, will be in 2.6.0 soon.

![image](https://user-images.githubusercontent.com/914224/99847640-34756980-2b9a-11eb-9a40-e0cd99dfc4c7.png)
