### ISSUE TITLE
Consistently use relative links to everything loaded by the main page.

### ISSUE THREAD

**Issue by markfaine** [ansible-semaphore/semaphore#615]
I was debating weather this is a bug or a feature request, I'll let you decide that.

I'm running in a docker container behind nginx, so I keep having trouble finding a way to make everything load.  It appears that some resources are loaded relative to the index page:

```
<script src="public/js/bundle.js"></script>
```

Others are relative to the root:
```
<link href="/public/img/icon.png" type="image/png" rel="icon">
```

And yet others use the web_host variable from config.json:

```
<script type="text/javascript" charset="utf-8" async="" data-requirecontext="_" data-requiremodule="controllers/dashboard" src="https://semaphore.mydomain.com/public/js/controllers/dashboard.js"></script>
```

I've had some luck by setting web_host to my external url, i.e. https://semaphore.mydomain.com, however, then I have trouble with the web socket not being accessible: 
```
Firefox can’t establish a connection to the server at wss://semaphore.mydomain.com/api/ws
```
That allows the gui to render but nothing works.
Even if it did work though, it wouldn't be optimal, since it would be better to access locally than going the long way back through the front door.

Personally, I'd like to see all links to css, js, images, etc. all be relative links but you may have a better solution that still accomplishes the same goal.  

As for the connection to the socket, it should probably be wss://interface:port/api/ws, however, when I try to set web_host to http://tasks.semaphore:3000, it crashes with:
```
http: panic serving 192.168.3.241:52922: runtime error: invalid memory address or nil pointer dereference
```
Thanks

**Comment by markfaine** [comment]
[semaphore-1602606327321.log](https://github.com/ansible-semaphore/semaphore/files/5372794/semaphore-1602606327321.log)
[semaphore-config.txt](https://github.com/ansible-semaphore/semaphore/files/5372835/semaphore-config.txt)

**Comment by fiftin** [comment]
I think it is must to work without defining `web_host`. I not sure why `web_host` required at all, because it is not working properly.

`interface` required if you have several notwork interfaces but want to you only one. It should be IP address.

> Firefox can’t establish a connection to the server at wss://semaphore.mydomain.com/api/ws

Are you sure problem not at the nginx?

nginx config for location should be like:

```
location = / {
             proxy_pass http://<semaphore-host>:3000;
             proxy_http_version 1.1;
             proxy_set_header Upgrade $http_upgrade;
             proxy_set_header Connection "upgrade";
}
```
