### ISSUE TITLE
Not able to use after container upgrade to 2.5.2

### ISSUE THREAD

**Issue by zeug-it** [ansible-semaphore/semaphore#616]
After container upgrade to 2.5.2 I get a destroyed login page with http://0.0.0.0:8081 in the url for the js files. I tried to fix it with changeing the web_host to my  apache url (Docker -> Apache as ReversProxy). The Login page renders like before, but after successful login, I'm redirected to login page while loading Events.

**Comment by fiftin** [comment]
Yes, you are right, problem with `web_host`.

**Comment by fiftin** [comment]
@zeug-it I removed default web_host from image. Please check version v2.5.3. I tested, it is works.

HTTP port 3000.

**Comment by zeug-it** [comment]
Now, after update to 2.5.3 I get an JS error GET https://api/user/ net::ERR_NAME_NOT_RESOLVED bundle.js:115 in JS Console.

**Comment by fiftin** [comment]
I have no any errors with 2.5.3. 

My docker compose file: https://gist.githubusercontent.com/fiftin/7c7e7d605c3f5079490e84393fe7fec6/raw/b0376e1602428ad5db4a3e1a8918d57e95d53d87/docker-compose.yml

**Comment by zeug-it** [comment]
Found the Problem I had a typo in my apache reverse Proxy config. Works now.
