### ISSUE TITLE
Telegram config is being ignored and Email one doesn't work neither

### ISSUE THREAD

**Issue by JustDevZero** [ansible-semaphore/semaphore#618]
I've added the telegram config to receive general updates, but I feel Like i'm being ignored.

I receive no updates, no messages, no nothing :(

If i try to send notifications by my seld with a curl, they work without any problem.

What's the cause?

Is there any debug I can enable to help to find a solution?

Thanks!

PS: I analized the code, and the email config will never work either, due to the lack of being able to authenticate.

**Comment by fiftin** [comment]
Did you allow alerts for the project?

![image](https://user-images.githubusercontent.com/914224/97789873-dd592600-1be5-11eb-8cff-e43c55df1fc4.png)

**Comment by JustDevZero** [comment]
It was done via the config file instead, cuz for some reason the gui wasn't showing this inputs.

**Comment by fiftin** [comment]
```go
t.alert = project.Alert
```

```go
func (t *task) sendTelegramAlert() {
	if !util.Config.TelegramAlert || !t.alert {
		return
	}
	...
}
```
Config file is not enough, you should check project settings.
