### ISSUE TITLE
ansible-galaxy support broken for collection

### ISSUE THREAD

**Issue by ottimo** [ansible-semaphore/semaphore#620]
the ansible-galaxy interface changed:
now ansible-galaxy is used for roles and collections and the type should be defined before the install action.

previous:
ansible-galaxy install -r requirements.yml

now:
for role: ansible-galaxy install -r requirements.yml
for collection: ansible-galaxy collection install -r requirements.yml

**Comment by ottimo** [comment]
I tried to build semaphore to test a commit should help for this issue, but when I run it and I try to access to port 3000 I get a 404 not found error.
I do not found any documentation or issue talking about this problem.

**Comment by fiftin** [comment]
@ottimo What OS?

**Comment by ottimo** [comment]
> 
> 
> @ottimo What OS?

ubuntu 18.04 

golang
  1.13.4
nodejs
  12.13.1

**Comment by fiftin** [comment]
I have next environment:

Ubuntu 20.10
Go  1.15.4
Node.js  14.15.0

I made all by instruction https://github.com/ansible-semaphore/semaphore/blob/develop/CONTRIBUTING.md and it is works fine.

**Comment by fiftin** [comment]
Done, will be in 2.6.0.
