### ISSUE TITLE
Fresh install returns 404

### ISSUE THREAD

**Issue by vlitvin** [ansible-semaphore/semaphore#625]
I'm new to semaphore.

I followed [installation guide](https://github.com/ansible-semaphore/semaphore/wiki/Installation):
- setup mysql, ansible, git, nginx
- copied 2.6.1 binary to /usr/bin (using amd64 deb package)
- run `semaphore -setup`
- configure nginx using [example config](https://github.com/ansible-semaphore/semaphore/blob/develop/deployment/docker/prod/proxy/nginx.conf), slightly modified, but forwarding all requests to semaphore daemon
- run `semaphore -config ./config.json`
```
Using config file: ./config.json
Semaphore v2.6.1
Interface 
Port :3000
MySQL semaphore@127.0.0.1:3306 semaphore
Tmp Path (projects home) /tmp/semaphore
Checking DB migrations
Server is running
```

What i did:
- `curl https://<hostname>/`

Expected behavior:
- Some index page

Observed behavior:
- curl returns '404 not found' with http code 404
- 404 in nginx logs
- `GET : https:/// --> 404 Not Found` in semaphore output

So:
* Nginx proxy works fine passing all requests
* I guess, it's something like:
  * static html missing in installation guide
  * missconfiguration in `config.json`
  * bug in binary

**Comment by fiftin** [comment]
@vlitvin This is bug in binary. I updated release https://github.com/ansible-semaphore/semaphore/releases/tag/v2.6.1.

If you used deb package you can remove old version by `sudo dpkg -r semaphore`.

**Comment by vlitvin** [comment]
@fiftin Thanks, it's fixed.
