### ISSUE TITLE
public/js/angular-ui-router.js.map missing

### ISSUE THREAD

**Issue by vlitvin** [ansible-semaphore/semaphore#627]
Semaphore v2.6.1, auth page (`auth/login`) uses `public/js/angular-ui-router.js.map`, but binary returns 404.

Steps to reproduce:
- Install semaphore as described in documentation
- Open `<web_host>` URL in browser

Expected behavior:
- No warnings in browser console

Observed behavior:
- In browser console log:
  ```
  DevTools failed to load SourceMap: Could not load content for https://<host>/public/js/angular-ui-router.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
  ```
- Semaphore output:
  ```
  path
  js/angular-ui-router.js.map
  GET : https:///public/js/angular-ui-router.js.map --> 404 Not Found
  ```

**Comment by fiftin** [comment]
New UI does't use Angular.js. Did you set flag `old_frontend` to `true` in config.json?

**Comment by fiftin** [comment]
I fixed bug with routing, fix available in new release: https://github.com/ansible-semaphore/semaphore/releases/tag/v2.6.3

**Comment by fiftin** [comment]
Hi @vlitvin, I can not reproduce the bug, cloud you please check version https://github.com/ansible-semaphore/semaphore/releases/tag/v2.6.4 ?

**Comment by vlitvin** [comment]
@fiftin 
Same on v2.6.4.
Looks like it's nothing serious, as it's browser "feature" to debug js, works in chromium and firefox after opening dev console.

And as I can tell `public/js/bundle.js` mentions it like
```
//# sourceMappingURL=angular-ui-router.js.map
```
And it's maybe related how it's bundled, or upstream bug.
