### ISSUE TITLE
Make the binary self-contained

### ISSUE THREAD

**Issue by ymmijgno** [ansible-semaphore/semaphore#630]
v2.6.1. I tried it in an isolated network without internet, it couldn't load. Some resources like fonts and the material css are loaded from the internet.

Also, able to add a switch to disable the update check?

**Comment by fiftin** [comment]
@gnoymmij yes, you are right, I already created similar task: https://github.com/ansible-semaphore/semaphore/issues/623. I plan to add this in the next release (v2.6.3).

PS: v2.6.1 has bug with routing when option `web_host` defined in config.js. I fixed it in v2.6.2.

**Comment by ymmijgno** [comment]
Tested the latest v2.6.4. The UI is now able to load without the fonts and css and still somewhat functional. However, when you change web_host to something else other than "/" then it will break. Seems like some resources are still in /js. Not sure if fixing the CDN resources will fix this.

**Comment by fiftin** [comment]
@gnoymmij Done in version v2.6.6 https://github.com/ansible-semaphore/semaphore/releases/tag/v2.6.6
