### ISSUE TITLE
Bug on /api/user/1 

### ISSUE THREAD

**Issue by andreadragotta** [ansible-semaphore/semaphore#631]
Hello everyone,

Related to this https://github.com/ansible-semaphore/semaphore/issues/628 i've found another bug on the routing.

When click on edit user the dialog in empty and in console i have this error.

http://my-semaphore-url.com/api/users/1 -> 301 to http:///api/users/1

**Comment by fiftin** [comment]
I installed CentOS to VMWare, I can't reproduce the bug. Semaphore redirects to location without host `/api/users/1/`. In your example location must be `http:///api/users/1/`.

Do you use nginx as proxy? What version of nginx? May it replaces location with this URL. I don't know.

Could you try use Semaphore without nginx?

**Comment by andreadragotta** [comment]
Without nginx it's work correctly.

The nginx version is: nginx/1.18.0 (CentOS)

This is my conf
```

upstream semaphore {
    server 192.168.18.10:3000;
}

server {
    listen 80;

    server_name semaphore.myurl.com;

    include hidden_lock;
    client_max_body_size 0;
    chunked_transfer_encoding on;

    location / {
        proxy_pass http://semaphore;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_buffering off;
        proxy_request_buffering off;
    }

    location /api/ws {
        proxy_pass http://semaphore/api/ws;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Origin "";
    }

}
```

**Comment by fiftin** [comment]
@andreadragotta thank you. I removed redirects. Now all should works. Cloud you please check version https://github.com/ansible-semaphore/semaphore/releases/tag/v2.6.4 ?

**Comment by andreadragotta** [comment]
Ok, i've tried on private browser and work properly

**Comment by fiftin** [comment]
Thank you!
