### ISSUE TITLE
web interface not running

### ISSUE THREAD

**Issue by lgwapnitsky** [ansible-semaphore/semaphore#637]
new install on ubuntu 20.04. config'ed web interface, it's not running. going to port 3000 in web browser brings a blank page.

**Comment by fiftin** [comment]
What version of Semaphore?

**Comment by fiftin** [comment]
Do you have any errors in browser console?

**Comment by lgwapnitsky** [comment]
Latest version, and I'll have to check the browser later

**Comment by lgwapnitsky** [comment]
[image: Screenshot at 2020-12-26 17-47-51.png]

*Larry G. Wapnitsky*


*E: Larry@Wapnitsky.com*
*Web: Larry.Wapnitsky.com <http://larry.wapnitsky.com/>Twitter:
@LGWapnitsky*

**Comment by lgwapnitsky** [comment]
```
# semaphore -config /root/config.json 
Using config file: /root/config.json
Semaphore v2.6.7
Interface 
Port :3000
MySQL ansible@127.0.0.1:3306 semaphore
Tmp Path (projects home) /tmp/semaphore
Checking DB migrations
Server is running
```

as for errors, yes.  the web host is not running when i start semaphore. so that causes the issues, apparently

**Comment by lgwapnitsky** [comment]
```
root@ansible:~# cat config.json 
{
        "mysql": {
                "host": "127.0.0.1:3306",
                "user": "ansible",
                "pass": "#####",
                "name": "semaphore"
        },
        "port": "",
        "interface": "",
        "tmp_path": "/tmp/semaphore",
        "cookie_hash": "//ODmvIj0jZxR81shbrwoehSLwT1ZMVwGdQSD4ABPEc=",
        "cookie_encryption": "6GwCl9wwNh2YknfbIkB1FQf3BNYWhmRzueRF9gt81ME=",
        "email_sender": "",
        "email_host": "",
        "email_port": "",
        "web_host": "http://10.150.33.31:8010",
        "ldap_binddn": "",
        "ldap_bindpassword": "",
        "ldap_server": "",
        "ldap_searchdn": "",
        "ldap_searchfilter": "",
        "ldap_mappings": {
                "dn": "",
                "mail": "",
                "uid": "",
                "cn": ""
        },
        "telegram_chat": "",
        "telegram_token": "",
        "concurrency_mode": "",
        "max_parallel_tasks": 0,
        "email_alert": false,
        "telegram_alert": false,
        "ldap_enable": false,
        "ldap_needtls": false,
        "old_frontend": false
 }
```

**Comment by fiftin** [comment]
looks like problem in config option `"web_host": "http://10.150.33.31:8010"`.

Cloud you remove it for test?

**Comment by lgwapnitsky** [comment]
tried, and it doesn't work. running the ss command shows no open port on
8010. Event tried as localhost with no change

*Larry G. Wapnitsky*


*E: Larry@Wapnitsky.com*
*Web: Larry.Wapnitsky.com <http://larry.wapnitsky.com/>Twitter:
@LGWapnitsky*

**Comment by air-vision** [comment]
Hi fitin,

i remove the web_host option and the web interface is accessible on port 3000

at ubuntu 1804

**Comment by fiftin** [comment]
Hi @air-vision,
Does it work fine?

**Comment by jinyanroot** [comment]
@lgwapnitsky I get the same problem.
When I  delete "web_host": "http://xxx:8010",I can access http://xxx:3000 successfull.

But there is the problem:Why can not use 8010 port？

**Comment by lgwapnitsky** [comment]
even going in on port 3000 gives me blank pages

*Larry G. Wapnitsky*


*E: Larry@Wapnitsky.com*
*Web: Larry.Wapnitsky.com <http://larry.wapnitsky.com/>Twitter:
@LGWapnitsky*

**Comment by air-vision** [comment]
Hi @fiftin 

yes it is working fine
