### ISSUE TITLE
Unable to set the password of a new user

### ISSUE THREAD

**Issue by 0bb0** [ansible-semaphore/semaphore#639]
I've installed Semaphore v2.6.7 on Ubuntu 18.04.5 LTS.
When I try to create a new global user account, the dialog does not show any option to set the password. The same thing happens when I try to edit the existing user. 
As shown in the screenshot below, no matter if I client New User button or edit an existing account, the label of the dialog says Edit User.
![image](https://user-images.githubusercontent.com/53031094/108676880-0575e780-753d-11eb-8cb7-8d03b2f2d9fd.png)
Currently, I am only able to modify the password of the master account that was created during setup by clicking the user name on bottom left and clicking Change Password option.
The LDAP configuration is blank and the users are being created locally.

**Comment by fiftin** [comment]
Thank you @0bb0! I working on this bug.

**Comment by fiftin** [comment]
Fixed in release 2.6.8: https://github.com/ansible-semaphore/semaphore/releases/tag/v2.6.8

Added field "Password":
![image](https://user-images.githubusercontent.com/914224/108890389-5534db80-762f-11eb-8a2a-09a86046e32d.png)

**Comment by Red967** [comment]
@fiftin same bug in a develop branch
