### ISSUE TITLE
keep group_vars in db

### ISSUE THREAD

**Issue by carlos-alarcon** [ansible-semaphore/semaphore#64]
It will be really nice to keep group_vars in the db (and also the ability of editing them)
It will be great if in the host form we had the chance of creating group_vars which would be stored in DB.
latter in the runner Those group_vars would be retrieved and stored under group_vars/group

**Comment by matejkramny** [comment]
Good idea :+1:

**Comment by matejkramny** [comment]
Environment variable editing is also in v2 (alpha currently)
