### ISSUE TITLE
When too many output to screen - sometnig goes WRONG

### ISSUE THREAD

**Issue by dobrys** [ansible-semaphore/semaphore#642]
i have a simple playbook that connects to 3 servers running Centos 8 , get installed rpm's and print it on screen
`
# This playbook is for testing only.
- hosts: virtuals
  become: True
  tasks:
   - name: Gather the rpm package facts
     package_facts:
       manager: auto
   - name: Print the rpm package facts
     debug:
       var: ansible_facts.packages
`

This happens on virtual env (proxmox)  , all servers, plus ansible master are virtual (ssd as storage).
This playbook , executed on CONSOLE - finish for a seconds.
When start it on SEMAPHORE - NEVER ENDING (started it before 30 min. and still Running) !!!!

Semaphore is started as **ansible** user **sudoers** , without password and with ssh keys distributed to nodes

**Comment by fiftin** [comment]
It is looks like result of `StrictHostKeyChecking`.

Could you try to connect to one of the server via SSH from server where Semaphore running?

**Comment by ForrestFeng** [comment]
### No, its not a result of StrictHostKeyChecking. 

@bodrys said

> This playbook , executed on CONSOLE - finish for a seconds.

Happen to the same issue. The ssh connection to hosts is OK. We can see the playbook is running and a partial stdout displaying in the Task running Window. But, the task is running forever, seems it has trouble to fetch all the playbook output if the output is too long.

I guess, Could it be a database issue, is there any restriction for the length of the output string?
Or could it be the buffer size issue, it is too small?
Or other issues?

![图片](https://user-images.githubusercontent.com/5875631/111016311-1ef5ab00-83e8-11eb-89fd-d1c36b293577.png)


### Console output

The output contains the debug msg to show all processes running on the server, it is very long, 
The full output when running from a command line is shown below. 
`
$ sudo ansible-playbook -i IVInventory Demo-ivbsrv-Get-Process.yml  --private-key ../access_key_1

PLAY [ivbsrv] **********************************************************************************************************************************************

TASK [Get Remote Processes] ********************************************************************************************************************************
changed: [myserver-i0]

TASK [Debug gps] *******************************************************************************************************************************************
ok: [myserver-i0] => {
    "gps": {
        "changed": true,
        "cmd": "Get-Process",
        "delta": "0:00:00.533407",
        "end": "2021-03-13 02:42:11.971409",
        "failed": false,
        "rc": 0,
        "start": "2021-03-13 02:42:11.438002",
        "stderr": "",
        "stderr_lines": [],
        "stdout": "\r\nHandles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName                                                  \r\n-------  ------    -----      -----     ------     --  -- -----------                                                  \r\n    325      20     9388       2404       0.19   3380   1 ApplicationFrameHost                                         \r\n     49       4     2260        308       0.02   5100   1 cmd
                                           \r\n     45       5     2524        300       0.08  11832   0 cmd
          \r\n    150      10     5796       1020       1.03   2336   0 conhost                                                      \r\n    248      14     8684       8104       2.77   4960   1 conhost                                                      \r\n    160      10     5840      11856       0.03   6172   0 conhost                                                      \r\n    786      24     2052       2064      53.73    664   0 csrss
                                  \r\n    497      17     1944       1668       5.52    760   1 csrss
 \r\n    382      15     3592       5968       5.52   7052   1 ctfmon                                                       \r\n    333      18     6820      10196       6.16   5376   0 dasHost                                                      \r\n    123       7     1564       5872       0.00   5988   0 dllhost                                                      \r\n    158       9     2128        528       0.05  13176   1 dllhost
                         \r\n    629      35    46796      45068      21.20   1108   1 dwm                                                          \r\n   2836     260    64652     104260     194.17   7028   1 explorer                                                     \r\n     45       6     1568       1044       1.94    100   0 fontdrvhost                                                  \r\n     45       7     2148       1692       0.39    104   1 fontdrvhost                                                  \r\n    189      11     1800        188       0.42    756   0 GoogleCrashHandler
                \r\n    170       9     1832        208       0.00   6876   0 GoogleCrashHandler64                                         \r\n      0       0       56          8                 0   0 Idle                                                         \r\n    247      16     8212       2068       0.13   3212   0 IpOverUsbSvc                                                 \r\n   5450      70   160508      14632   2,708.92   9988   0 java
                                        \r\n    354      17     2980       1728       0.27   9560   1 jucheck
       \r\n    393      18     3212       1188       0.23  10664   1 jusched                                                      \r\n    494      25    11052       4040       0.28   8640   1 LockApp                                                      \r\n   1527      26     8700      13248     181.02    896   0 lsass                                                        \r\n      0       0      532      77976     550.98   4204   0 Memory Compression
                               \r\n   1390      47    51720      47428       5.06  11608   1 Microsoft.Photos                                             \r\n    358      33     7216       3160       0.09   3544   0 mqsvc                                                        \r\n    157      10     2156       3068       0.20   8420   1 MSASCuiL                                                     \r\n    206      13     2896        888       0.06   3672   0 msdtc                                                        \r\n    818      82   359404     360312  13,862.09   9972   0 MsMpEng
                      \r\n    215      12     6532       5892      38.86   5292   0 NisSrv                                                       \r\n    446      26    19928      14568      28.98   9136   1 notepad++                                                    \r\n    751      58    26156      56452       5.19  13372   1 OneDrive                                                     \r\n    568      27    50252      49332       0.25   2568   0 powershell                                                   \r\n    499      34   138496     168180       7.00   6820   1 powershell
             \r\n    692      32   102712     100420       0.77   7200   0 powershell                                                   \r\n    558      27    50168      48912       0.14   8692   0 powershell                                                   \r\n    570      28    61240      62396       0.34   8904   0 powershell                                                   \r\n      0      11      400       3324       7.14    168   0 Registry
                                     \r\n    206      11     2732       2748       0.48   7080   1 RuntimeBroker
    \r\n    453      23     7552      13764      32.88   7560   1 RuntimeBroker                                                \r\n    296      17     5980      14908       5.69   7680   1 RuntimeBroker                                                \r\n    386      17     5016      14780      38.95   8564   1 RuntimeBroker                                                \r\n    354      19     7040       1964       0.36   8808   1 RuntimeBroker
                            \r\n    400      19    10792      31560       3.80  16320   1 RuntimeBroker                                                \r\n    760      79    41860      36304      76.00   3412   0 SearchIndexer                                                \r\n   1218      82    95080     105428      21.91   7432   1 SearchUI                                                     \r\n    376      16     5272       8880       1.08   3268   0 SecurityHealthService                                        \r\n    302      16     4524      12300       0.59  10168   0 sedsvc
                   \r\n    700      11     5636       7100      97.42    880   0 services                                                     \r\n     65       5     2800       3176       6.56  10232   0 SgrmBroker                                                   \r\n   1047      37    31556      61036     114.50   7264   1 ShellExperienceHost                                          \r\n    526      18     8344      17488      58.75   5088   1 sihost
                                           \r\n    575      35    13464       6640       0.45   8228   1 SkypeApp
          \r\n    170       9     2136       3172       0.03   8256   1 SkypeBackgroundHost                                          \r\n     52       3      512        216       0.14    480   0 smss                                                         \r\n    419      21     5768       3792       0.11   3000   0 spoolsv                                                      \r\n    147       9     2216       7504       0.00   2644   0 sshd
                                  \r\n    122      10     2160       7208       0.05   5324   0 sshd
 \r\n    106      11     1540       6512       0.09   6288   0 sshd                                                         \r\n     84       5      996        848       0.00    120   0 svchost                                                      \r\n   1056      23    16812      22800     167.50    452   0 svchost                                                      \r\n   1181      19     7924      10300     106.27    764   0 svchost
                         \r\n    132      14     1684       2452       0.39    892   0 svchost                                                      \r\n    296      11     3108       4396      24.44    928   0 svchost                                                      \r\n    503      19     5280       4688      12.88   1164   0 svchost                                                      \r\n    165       9     1876       1044       0.05   1200   0 svchost                                                      \r\n    185      11     2128       4560       0.17   1232   0 svchost
                \r\n    170      10     1852       1216       0.02   1352   0 svchost                                                      \r\n    173       7     1348       1660       0.11   1412   0 svchost                                                      \r\n    236      13     2880       5124       0.92   1428   0 svchost                                                      \r\n    222      14    95384      90420   5,447.02   1436   0 svchost
                                        \r\n    186       9     1664       1092       0.02   1648   0 svchost
       \r\n    409      18     6500       8704      11.09   1656   0 svchost                                                      \r\n    177       9     2400       4432       0.64   1776   0 svchost                                                      \r\n    153       9     2368       4644       2.92   1784   0 svchost                                                      \r\n    474      33    18164      17788      42.38   1792   0 svchost
                               \r\n    450      13    14688      12080     137.34   1800   0 svchost                                                      \r\n    173      10     2192       2792       1.30   1808   0 svchost                                                      \r\n    143      24     4876       3636       5.63   1816   0 svchost                                                      \r\n    194      11     2172       2860      12.50   1992   0 svchost                                                      \r\n    219       9     2548       3808      46.72   2008   0 svchost
                      \r\n    138       9     1628       1164       0.03   2092   0 svchost                                                      \r\n    167      10     2016       5220       0.22   2100   0 svchost                                                      \r\n    225      14     2280       3340       0.02   2200   0 svchost                                                      \r\n    374      15     4964       6008      64.52   2292   0 svchost                                                      \r\n    198      10     2224       3348       0.05   2304   0 svchost
             \r\n    915      10     2556       4876       9.03   2312   0 svchost                                                      \r\n    191      11     2084       1300       0.06   2500   0 svchost                                                      \r\n    500      10     3204       5080       4.20   2508   0 svchost                                                      \r\n    305      11     2468       2608       0.23   2516   0 svchost
                                     \r\n    223      13     3120       4136     123.00   2532   0 svchost
    \r\n    123       9     1720       1992       0.78   2540   0 svchost                                                      \r\n    182      12     2304       1332       0.20   2772   0 svchost                                                      \r\n    203      11     2268       1288       0.02   2796   0 svchost                                                      \r\n    181      10     5868      10652      33.72   3016   0 svchost
                            \r\n    474      19     9592      13944     693.78   3156   0 svchost                                                      \r\n    293      30     6708       8976      27.19   3172   0 svchost                                                      \r\n    336      18    29276      32968     126.41   3180   0 svchost                                                      \r\n    125       9     1628       1140       0.03   3188   0 svchost                                                      \r\n    162       7     1372       1144       0.06   3196   0 svchost
                   \r\n    230      12     2672       1268       0.08   3204   0 svchost                                                      \r\n    370      19     4680      12220       1.47   3228   0 svchost                                                      \r\n    206      12     2572       3764      13.45   3512   0 svchost                                                      \r\n    448      15     3668       3620       1.14   3732   0 svchost
                                           \r\n    103       7     1360       1016       0.00   3816   0 svchost
          \r\n    364      23     3340       3084       0.36   4336   0 svchost                                                      \r\n    160       9     1800       1140       0.02   4564   0 svchost                                                      \r\n    239      13     4020       9784       0.63   4728   1 svchost                                                      \r\n    147      10     1804       3652       0.42   4856   0 svchost
                                  \r\n    178      15     6660       2788       0.08   5104   0 svchost
 \r\n    220      12     2628       1516       0.06   5164   0 svchost                                                      \r\n    134       7     1692       2556       0.53   5276   0 svchost                                                      \r\n    195      14     2140       2956      41.11   5284   0 svchost                                                      \r\n    249      12     3204       7556       1.16   5568   0 svchost
                         \r\n    243      19     2568       3312      20.34   5620   0 svchost                                                      \r\n    212      11     2796       4792       0.25   5892   0 svchost                                                      \r\n    472      22     8348      34100       4.41   6076   1 svchost                                                      \r\n    127       8     1580       1068       0.00   6160   0 svchost                                                      \r\n    976      88    53524      43288      83.48   6300   0 svchost
                \r\n    261      12     2504       4568       0.08   6416   0 svchost                                                      \r\n    258      13     2616       6308       1.77   6576   0 svchost                                                      \r\n    179      10     3796       4088       0.36   7180   0 svchost                                                      \r\n   1648      24    16372      21660      19.22   7576   0 svchost
                                        \r\n    275      16     4200      10556       0.52   8176   0 svchost
       \r\n    172      10     2060        476       0.00   8580   0 svchost                                                      \r\n    262      19     3960       4280       0.19   9364   0 svchost                                                      \r\n    239      15     3000       7620      37.83   9696   0 svchost                                                      \r\n    201      11     2352       4752       0.31  11108   0 svchost
                               \r\n    465      25     5508      20536       0.34  11196   1 svchost                                                      \r\n    420      21     7056      12336      49.78  11292   0 svchost                                                      \r\n    484      30    11112      11368       1.34  11844   0 svchost                                                      \r\n    340      15     4252      14436       0.41  14236   0 svchost                                                      \r\n    184      10     2276       8000       2.05  14832   0 svchost
                      \r\n   3048       0      192        988   5,766.25      4   0 System                                                       \r\n    794      38    14388        324       0.28  11032   1 SystemSettings                                               \r\n    297      28     6792       8528       2.91   3540   1 taskhostw                                                    \r\n    398      22     7772       9844       0.23   8184   1 taskhostw                                                    \r\n    179      12     3332       1204       0.05   3164   0 VGAuthService
             \r\n    130       8     1868       4616       0.28   5076   0 vmcompute                                                    \r\n    551      22    40120      19060       0.25   3712   0 vmms                                                         \r\n    404      22    11248       8804     423.08   3220   0 vmtoolsd                                                     \r\n    240      18     4152       3300     349.70  10256   1 vmtoolsd
                                     \r\n    447      32    20940       6976       4.67  10688   0 vmware-converter
    \r\n    367      23    15512       2076       1.61  10968   0 vmware-converter                                             \r\n    386      26    15160       2096       1.67  10196   0 vmware-converter-a                                           \r\n    151      10     1348         36       0.05    744   0 wininit                                                      \r\n    277      13     2956       2640       0.23    852   1 winlogon
                            \r\n    389      18    21260      29376     856.45   4884   0 WmiPrvSE                                                     \r\n    353      10     2572       2104       3.30   1768   0 WUDFHost                                                     \r\n    324      17     9356       7196   1,170.19   1708   0 zabbix_agentd                                                \r\n\r\n\r\n",
        "stdout_lines": [
            "",
            "Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName                                                  ",
            "-------  ------    -----      -----     ------     --  -- -----------                                                  ",
            "    325      20     9388       2404       0.19   3380   1 ApplicationFrameHost                                         ",
            "     49       4     2260        308       0.02   5100   1 cmd                                                          ",
            "     45       5     2524        300       0.08  11832   0 cmd                                                          ",
            "    150      10     5796       1020       1.03   2336   0 conhost                                                      ",
            "    248      14     8684       8104       2.77   4960   1 conhost                                                      ",
            "    160      10     5840      11856       0.03   6172   0 conhost                                                      ",
            "    786      24     2052       2064      53.73    664   0 csrss                                                        ",
            "    497      17     1944       1668       5.52    760   1 csrss                                                        ",
            "    382      15     3592       5968       5.52   7052   1 ctfmon                                                       ",
            "    333      18     6820      10196       6.16   5376   0 dasHost                                                      ",
            "    123       7     1564       5872       0.00   5988   0 dllhost                                                      ",
            "    158       9     2128        528       0.05  13176   1 dllhost                                                      ",
            "    629      35    46796      45068      21.20   1108   1 dwm                                                          ",
            "   2836     260    64652     104260     194.17   7028   1 explorer                                                     ",
            "     45       6     1568       1044       1.94    100   0 fontdrvhost                                                  ",
            "     45       7     2148       1692       0.39    104   1 fontdrvhost                                                  ",
            "    189      11     1800        188       0.42    756   0 GoogleCrashHandler                                           ",
            "    170       9     1832        208       0.00   6876   0 GoogleCrashHandler64                                         ",
            "      0       0       56          8                 0   0 Idle                                                         ",
            "    247      16     8212       2068       0.13   3212   0 IpOverUsbSvc                                                 ",
            "   5450      70   160508      14632   2,708.92   9988   0 java                                                         ",
            "    354      17     2980       1728       0.27   9560   1 jucheck                                                      ",
            "    393      18     3212       1188       0.23  10664   1 jusched                                                      ",
            "    494      25    11052       4040       0.28   8640   1 LockApp                                                      ",
            "   1527      26     8700      13248     181.02    896   0 lsass                                                        ",
            "      0       0      532      77976     550.98   4204   0 Memory Compression                                           ",
            "   1390      47    51720      47428       5.06  11608   1 Microsoft.Photos                                             ",
            "    358      33     7216       3160       0.09   3544   0 mqsvc                                                        ",
            "    157      10     2156       3068       0.20   8420   1 MSASCuiL                                                     ",
            "    206      13     2896        888       0.06   3672   0 msdtc                                                        ",
            "    818      82   359404     360312  13,862.09   9972   0 MsMpEng                                                      ",
            "    215      12     6532       5892      38.86   5292   0 NisSrv                                                       ",
            "    446      26    19928      14568      28.98   9136   1 notepad++                                                    ",
            "    751      58    26156      56452       5.19  13372   1 OneDrive                                                     ",
            "    568      27    50252      49332       0.25   2568   0 powershell                                                   ",
            "    499      34   138496     168180       7.00   6820   1 powershell                                                   ",
            "    692      32   102712     100420       0.77   7200   0 powershell                                                   ",
            "    558      27    50168      48912       0.14   8692   0 powershell                                                   ",
            "    570      28    61240      62396       0.34   8904   0 powershell                                                   ",
            "      0      11      400       3324       7.14    168   0 Registry                                                     ",
            "    206      11     2732       2748       0.48   7080   1 RuntimeBroker                                                ",
            "    453      23     7552      13764      32.88   7560   1 RuntimeBroker                                                ",
            "    296      17     5980      14908       5.69   7680   1 RuntimeBroker                                                ",
            "    386      17     5016      14780      38.95   8564   1 RuntimeBroker                                                ",
            "    354      19     7040       1964       0.36   8808   1 RuntimeBroker                                                ",
            "    400      19    10792      31560       3.80  16320   1 RuntimeBroker                                                ",
            "    760      79    41860      36304      76.00   3412   0 SearchIndexer                                                ",
            "   1218      82    95080     105428      21.91   7432   1 SearchUI                                                     ",
            "    376      16     5272       8880       1.08   3268   0 SecurityHealthService                                        ",
            "    302      16     4524      12300       0.59  10168   0 sedsvc                                                       ",
            "    700      11     5636       7100      97.42    880   0 services                                                     ",
            "     65       5     2800       3176       6.56  10232   0 SgrmBroker                                                   ",
            "   1047      37    31556      61036     114.50   7264   1 ShellExperienceHost                                          ",
            "    526      18     8344      17488      58.75   5088   1 sihost                                                       ",
            "    575      35    13464       6640       0.45   8228   1 SkypeApp                                                     ",
            "    170       9     2136       3172       0.03   8256   1 SkypeBackgroundHost                                          ",
            "     52       3      512        216       0.14    480   0 smss                                                         ",
            "    419      21     5768       3792       0.11   3000   0 spoolsv                                                      ",
            "    147       9     2216       7504       0.00   2644   0 sshd                                                         ",
            "    122      10     2160       7208       0.05   5324   0 sshd                                                         ",
            "    106      11     1540       6512       0.09   6288   0 sshd                                                         ",
            "     84       5      996        848       0.00    120   0 svchost                                                      ",
            "   1056      23    16812      22800     167.50    452   0 svchost                                                      ",
            "   1181      19     7924      10300     106.27    764   0 svchost                                                      ",
            "    132      14     1684       2452       0.39    892   0 svchost                                                      ",
            "    296      11     3108       4396      24.44    928   0 svchost                                                      ",
            "    503      19     5280       4688      12.88   1164   0 svchost                                                      ",
            "    165       9     1876       1044       0.05   1200   0 svchost                                                      ",
            "    185      11     2128       4560       0.17   1232   0 svchost                                                      ",
            "    170      10     1852       1216       0.02   1352   0 svchost                                                      ",
            "    173       7     1348       1660       0.11   1412   0 svchost                                                      ",
            "    236      13     2880       5124       0.92   1428   0 svchost                                                      ",
            "    222      14    95384      90420   5,447.02   1436   0 svchost                                                      ",
            "    186       9     1664       1092       0.02   1648   0 svchost                                                      ",
            "    409      18     6500       8704      11.09   1656   0 svchost                                                      ",
            "    177       9     2400       4432       0.64   1776   0 svchost                                                      ",
            "    153       9     2368       4644       2.92   1784   0 svchost                                                      ",
            "    474      33    18164      17788      42.38   1792   0 svchost                                                      ",
            "    450      13    14688      12080     137.34   1800   0 svchost                                                      ",
            "    173      10     2192       2792       1.30   1808   0 svchost                                                      ",
            "    143      24     4876       3636       5.63   1816   0 svchost                                                      ",
            "    194      11     2172       2860      12.50   1992   0 svchost                                                      ",
            "    219       9     2548       3808      46.72   2008   0 svchost                                                      ",
            "    138       9     1628       1164       0.03   2092   0 svchost                                                      ",
            "    167      10     2016       5220       0.22   2100   0 svchost                                                      ",
            "    225      14     2280       3340       0.02   2200   0 svchost                                                      ",
            "    374      15     4964       6008      64.52   2292   0 svchost                                                      ",
            "    198      10     2224       3348       0.05   2304   0 svchost                                                      ",
            "    915      10     2556       4876       9.03   2312   0 svchost                                                      ",
            "    191      11     2084       1300       0.06   2500   0 svchost                                                      ",
            "    500      10     3204       5080       4.20   2508   0 svchost                                                      ",
            "    305      11     2468       2608       0.23   2516   0 svchost                                                      ",
            "    223      13     3120       4136     123.00   2532   0 svchost                                                      ",
            "    123       9     1720       1992       0.78   2540   0 svchost                                                      ",
            "    182      12     2304       1332       0.20   2772   0 svchost                                                      ",
            "    203      11     2268       1288       0.02   2796   0 svchost                                                      ",
            "    181      10     5868      10652      33.72   3016   0 svchost                                                      ",
            "    474      19     9592      13944     693.78   3156   0 svchost                                                      ",
            "    293      30     6708       8976      27.19   3172   0 svchost                                                      ",
            "    336      18    29276      32968     126.41   3180   0 svchost                                                      ",
            "    125       9     1628       1140       0.03   3188   0 svchost                                                      ",
            "    162       7     1372       1144       0.06   3196   0 svchost                                                      ",
            "    230      12     2672       1268       0.08   3204   0 svchost                                                      ",
            "    370      19     4680      12220       1.47   3228   0 svchost                                                      ",
            "    206      12     2572       3764      13.45   3512   0 svchost                                                      ",
            "    448      15     3668       3620       1.14   3732   0 svchost                                                      ",
            "    103       7     1360       1016       0.00   3816   0 svchost                                                      ",
            "    364      23     3340       3084       0.36   4336   0 svchost                                                      ",
            "    160       9     1800       1140       0.02   4564   0 svchost                                                      ",
            "    239      13     4020       9784       0.63   4728   1 svchost                                                      ",
            "    147      10     1804       3652       0.42   4856   0 svchost                                                      ",
            "    178      15     6660       2788       0.08   5104   0 svchost                                                      ",
            "    220      12     2628       1516       0.06   5164   0 svchost                                                      ",
            "    134       7     1692       2556       0.53   5276   0 svchost                                                      ",
            "    195      14     2140       2956      41.11   5284   0 svchost                                                      ",
            "    249      12     3204       7556       1.16   5568   0 svchost                                                      ",
            "    243      19     2568       3312      20.34   5620   0 svchost                                                      ",
            "    212      11     2796       4792       0.25   5892   0 svchost                                                      ",
            "    472      22     8348      34100       4.41   6076   1 svchost                                                      ",
            "    127       8     1580       1068       0.00   6160   0 svchost                                                      ",
            "    976      88    53524      43288      83.48   6300   0 svchost                                                      ",
            "    261      12     2504       4568       0.08   6416   0 svchost                                                      ",
            "    258      13     2616       6308       1.77   6576   0 svchost                                                      ",
            "    179      10     3796       4088       0.36   7180   0 svchost                                                      ",
            "   1648      24    16372      21660      19.22   7576   0 svchost                                                      ",
            "    275      16     4200      10556       0.52   8176   0 svchost                                                      ",
            "    172      10     2060        476       0.00   8580   0 svchost                                                      ",
            "    262      19     3960       4280       0.19   9364   0 svchost                                                      ",
            "    239      15     3000       7620      37.83   9696   0 svchost                                                      ",
            "    201      11     2352       4752       0.31  11108   0 svchost                                                      ",
            "    465      25     5508      20536       0.34  11196   1 svchost                                                      ",
            "    420      21     7056      12336      49.78  11292   0 svchost                                                      ",
            "    484      30    11112      11368       1.34  11844   0 svchost                                                      ",
            "    340      15     4252      14436       0.41  14236   0 svchost                                                      ",
            "    184      10     2276       8000       2.05  14832   0 svchost                                                      ",
            "   3048       0      192        988   5,766.25      4   0 System                                                       ",
            "    794      38    14388        324       0.28  11032   1 SystemSettings                                               ",
            "    297      28     6792       8528       2.91   3540   1 taskhostw                                                    ",
            "    398      22     7772       9844       0.23   8184   1 taskhostw                                                    ",
            "    179      12     3332       1204       0.05   3164   0 VGAuthService                                                ",
            "    130       8     1868       4616       0.28   5076   0 vmcompute                                                    ",
            "    551      22    40120      19060       0.25   3712   0 vmms                                                         ",
            "    404      22    11248       8804     423.08   3220   0 vmtoolsd                                                     ",
            "    240      18     4152       3300     349.70  10256   1 vmtoolsd                                                     ",
            "    447      32    20940       6976       4.67  10688   0 vmware-converter                                             ",
            "    367      23    15512       2076       1.61  10968   0 vmware-converter                                             ",
            "    386      26    15160       2096       1.67  10196   0 vmware-converter-a                                           ",
            "    151      10     1348         36       0.05    744   0 wininit                                                      ",
            "    277      13     2956       2640       0.23    852   1 winlogon                                                     ",
            "    389      18    21260      29376     856.45   4884   0 WmiPrvSE                                                     ",
            "    353      10     2572       2104       3.30   1768   0 WUDFHost                                                     ",
            "    324      17     9356       7196   1,170.19   1708   0 zabbix_agentd                                                ",
            "",
            ""
        ]
    }
}

PLAY RECAP *************************************************************************************************************************************************
myserver-i0            : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
`

**Comment by fiftin** [comment]
@ForrestFeng Yes, It can be problem with DB (too many connections), it is known problem. Semaphore is interrupted in this case and you will see error in stdout/stderr.

I marked this issue as a bug.

Problem details: when output of the playbook is very long, Semaphore creates a lot of parallel connections to DB. 

Possible solution: create queue of output records.

**Comment by fiftin** [comment]
Hi @ForrestFeng 
I fixed issue "too many connections" in v2.7.9

https://github.com/ansible-semaphore/semaphore/releases/tag/v2.7.9

**Comment by fiftin** [comment]
Now we use channel for storing logs to database. It is use single connection. I closing the issue.

**Comment by ocafebabe** [comment]
I'm facing the same issue with Semaphore 2.8.49: with a large output the web console gets stuck forever!

Is there a way to debug this?
