### ISSUE TITLE
fatal: remote branch master not found

### ISSUE THREAD

**Issue by dR3b** [ansible-semaphore/semaphore#646]
I created a new git repository with the default branch "main".  The branch must be named "master" or you will get this error message:
```bash
4:00:29 PM Task 1 added to queue
4:00:30 PM Preparing: 1
4:00:30 PM Prepare task with template: test
4:00:30 PM access key awx installed
4:00:30 PM Cloning repository /semaphore/git
4:00:30 PM Clone to 'repository_1' ...
4:00:30 PM fatal: Remote branch master not found in upstream repository origin
4:00:30 PM Failed updating repository: exit status 128
```

**Comment by Weilbyte** [comment]
Can replicate.

**Comment by Weilbyte** [comment]
Can replicate. As a workaround format your Git URL like this: `git@github.com:User/repo.git#branch`, should work!

**Comment by dR3b** [comment]
@Weilbyte 
Jepp I can confirm that your workaround works.

**Comment by fiftin** [comment]
@dR3b @Weilbyte Sorry for offtop, but how you found this repo? I see a lot of new users today.

I trying to do marketing and it is very important to me.

**Comment by Weilbyte** [comment]
@fiftin I used to have AWX for my homelab but it was too resource intensive so I discovered Semaphore through a Reddit post. Some stuff could certainly be better but so far it is pretty good.

**Comment by fiftin** [comment]
@Weilbyte Thank you. Feel free to create issue if you need some feature :)

**Comment by dR3b** [comment]
@fiftin 

Keeping AWX up to date is a big effort. Of course, 2-3 things are still missing like:

* Documentation
* User authentication (LDAP, OAUTH)
* Cron

But so far it's really good!

**Comment by Weilbyte** [comment]
@dR3b LDAP works fine, no OAUTH though.
