### ISSUE TITLE
arm64 RPM does not install on aarch64 (package does not have a compatible architecture)

### ISSUE THREAD

**Issue by FloThinksPi** [ansible-semaphore/semaphore#648]
When installing the arm64 rpm package on fedora 33 aarch64 on a rpi3 i get folllowing error.

```
[root@myhostname ~]# uname -a
Linux myhostname 5.8.15-301.fc33.aarch64 #1 SMP Thu Oct 15 15:56:58 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
[root@myhostname ~]# dnf install ./semaphore_2.6.8_linux_arm64.rpm
Error:
 Problem: conflicting requests
  - package semaphore-2.6.8-1.arm64 does not have a compatible architecture
(try to add '--skip-broken' to skip uninstallable packages)
```

Isnt aarch64 and arm64 the same arch though ? (https://stackoverflow.com/a/47274698)

**Comment by fiftin** [comment]
@FloThinksPi Thank you. I didn't test it on ARM. Will do this ASAP.

**Comment by FloThinksPi** [comment]
The arm64 binary in the tar.gz works fine so it must be some rpm specifc thing that tells dnf what arch this package is. Its not actually tested by identifying the elf architechture.

**Comment by fiftin** [comment]
Looks like problem really in the RPM. DEB package successfully installed on rpi 4.

**Comment by FloThinksPi** [comment]
@fiftin where is the rpm.spec file located ? i cannot find it in this project.

**Comment by fiftin** [comment]
@FloThinksPi Sorry, I don't know what is it. 
NFPM used for creating different packages: https://github.com/goreleaser/nfpm

**Comment by FloThinksPi** [comment]
Ah interesting thats why. A specfile is a formula to build a rpm package, see https://rpm-packaging-guide.github.io/#what-is-a-spec-file . Similar how a Dockerfile works though a lot more ancient tech there. I suspect NFPM to generate that spec file and execute the rpmbuild command to generate the rpm package. I guess we then need to look there why the generated rpm.spec and the resulting package is not working on aarch64.

Already found https://github.com/goreleaser/goreleaser/blob/master/internal/linux/arch.go#L13-L14 meaning in their coding aarch64 and arm64 is not interchangeable. Will open a bug there then.

**Comment by caarlos0** [comment]
> I suspect NFPM to generate that spec file and execute the rpmbuild command to generate the rpm package

not really, it builds the rpm package using go code only. No spec, no rpmbuild :) 

nfpm uses this https://github.com/goreleaser/nfpm/blob/master/rpm/rpm.go#L61, so it should be correct...
