### ISSUE TITLE
Set hosts as globals instead of being private of each playbook

### ISSUE THREAD

**Issue by carlos-alarcon** [ansible-semaphore/semaphore#65]
I think this is  an enhancement instead of an issue.
Think about host being globals: 

1. You first define your host (perhaps calling them inventories would be better since they are actually used as inventories in the commad 'ansible-playbook' triggered by runner.js (groups and hosts)
1. Then when creating / editing playbooks you can assign them an 'inventory' to be used for such playbook

**Comment by matejkramny** [comment]
:+1: sounds good.

Will be implemented within v2.

**Comment by matejkramny** [comment]
Please try out v2-alpha, inventory management is much better.
