### ISSUE TITLE
How do I force kill a task which is running for ever?

### ISSUE THREAD

**Issue by Bkbest** [ansible-semaphore/semaphore#656]
Hi, 

I have installed the latest Ansible-Semaphore and have been playing with it for couple of days. Today I have observed an unusual case where large debug messages caused multiple tasks to enter a state of limbo for hours:
![image](https://user-images.githubusercontent.com/16200783/113566539-7de6c280-962a-11eb-9ed3-7ea60560ad7e.png)

Although this is another issue altogether, I would like to know how I can force kill these stranded tasks which have been running for ever.

Thanks,
Aravind

**Comment by fiftin** [comment]
Hi,

yes, it is known bug https://github.com/ansible-semaphore/semaphore/issues/642. It will be fixed in next release.

By the stopping the tasks - currently it is not possible. This feature in the plan.

**Comment by Bkbest** [comment]
Hi, 
thanks for replying, I will look for the next release. 
Thanks
Aravind

**Comment by johnneman** [comment]
Good day,

Do yoy have any news on the next release? This issue is really bothering us :)

Thank you very much!

Regards,

John

**Comment by Bkbest** [comment]
Hi team,

A button to kill a running task will be really helpful. Is this planned?

Thanks,
Aravind

**Comment by fiftin** [comment]
Please try v2.7.5

https://github.com/ansible-semaphore/semaphore/releases/tag/v2.7.5

**Comment by Bkbest** [comment]
Hey @fiftin , thank you very much. I will try it definitely tomorrow.

Thanks,
Aravind

**Comment by Bkbest** [comment]
Hi, I have just upgraded the server from v2.6.8 to v2.7.5, I see that Dashboard is not loading:
![image](https://user-images.githubusercontent.com/16200783/130903383-52077115-30f3-479c-8cae-bd111950f5e7.png)

However, I am able to run tasks from task templates and able to stop them too.

Let me know how we can debug this @fiftin 

Thanks,
Aravind

**Comment by Bkbest** [comment]
Ran this command to fix it: **update task set project_id = 0 where project_id is null**

However, one observation, before upgrade I had couple of tasks which were running forever. After upgrade unable to stop them with stop Button. Stop button works for any new task that I trigger.

Thanks,
Aravind

**Comment by fiftin** [comment]
Hi @Bkbest 
Thank you very mach, looks like it is migration issue.

**Comment by fiftin** [comment]
> However, one observation, before upgrade I had couple of tasks which were running forever. After upgrade unable to stop them with stop Button. Stop button works for any new task that I trigger.

With stop button you can stop only active tasks. Old tasks not active, it only have `running` state in database.

I will add check of running tasks when app started.
