### ISSUE TITLE
Do you have plans to create a helm chart?

### ISSUE THREAD

**Issue by botzill** [ansible-semaphore/semaphore#659]
Would be great to have a helm chart so that we can easily test this one k8s. 

thx.

**Comment by fiftin** [comment]
How Semaphore can be used for k8s?

**Comment by botzill** [comment]
Well, we can install it there and execute specific playbooks via UI or eventually API as well. At least this is what I'm looking forward.

**Comment by TrayserCassa** [comment]
@botzill 
If you using kubernetes maybe you want to use awx, because they updated the standard installation and use minikube as an example. Well it is buggy but more for advanced deployments with k8s clusters. Helm charts are also not complicated if you are not trying to install prometheus for example :smile:

**Comment by fivaldi** [comment]
@fiftin 

> How Semaphore can be used for k8s?

For deploying helm charts using playbooks (**one-click configurable deployments**: create namespace(s), set labels, installation of charts from Git (for devs), wait for resources, patch deployments, keep secrets outside of values files in Ansible vaults, possibility to trigger deployment using Semaphore API from a CI/CD pipeline and many more....)

Infinite possibilities of customization of your own CI/CD/release processes and simply Swiss army knife in k8s and automation and all related operations. Yes, there are tools for helm, but that's all they can do. All the rest you have to automate _somehow_, which is always a pain, unless you use Ansible. :)

**Comment by cruscio** [comment]
+1
The [Install documentation](https://docs.ansible-semaphore.com/administration-guide/installation) has a docker-compose example. Having a similar helm chart or other documentation for a quick-start in k8s-compatible ecosystems would be a welcome addition.

**Comment by tboerger** [comment]
For those who are searching for a Helm chart, I have built my own one which you can find at https://artifacthub.io/packages/helm/cloudhippie/ansible-semaphore, the only disadvantage it currently got is that it won't create an initial admin user as this chart directly writes the `config.json` which prevents running the Semaphore setup process. But you are able to create the initial user with a command like this: 

```
kubectl -n semaphore-system exec -ti $(kubectl -n semaphore-system get pod -l app.kubernetes.io/name=ansible-semaphore -o name) -- semaphore --config /etc/sempahore/config.json user add --email admin@example.com --login admin --name Admin --password p455w0rd
```

I am currently building some basic documentation as part of the README, maybe you are able to see it later that day.

**Comment by MozeBaltyk** [comment]
small typo in the `--config /etc/sempahore/config.json `

**Comment by tboerger** [comment]
As you can see at https://github.com/ansible-semaphore/semaphore/discussions/1622 there are already at least two different sets of Helm charts.
