### ISSUE TITLE
Provide setup details for a pure Node installation

### ISSUE THREAD

**Issue by slimandslam** [ansible-semaphore/semaphore#66]
Can you guys take the info from this article:  http://code-complete.com/code/?p=40
(or your own experience) and provide setup details for deploying semphore on
a plain old Linux server with Node running?  Among other things, that might
help people who want to understand the article interaction a bit better. Thanks!

**Comment by matejkramny** [comment]
Hi @slimandslam, we can write some wiki articles with more details

**Comment by matejkramny** [comment]
Once `v2` is out, we will provide a detailed wiki on semaphore.

**Comment by kantmakm** [comment]
I wrote the above referenced blog on running semaphore outside of a container, and would be happy to help out with same for v2.  There are a few details that I now realize were not included in the post as it was really a bit of tinkering to get things working.  Of note however, was that I also needed to place a config file in /root/.ssh/config  with the following:
`Host *
  StrictHostKeyChecking no
  CheckHostIp no
  PasswordAuthentication no
  PreferredAuthentications publickey`

**Comment by matejkramny** [comment]
@kantmakm version 1 was already writing a config file. Upon later thought however, I am not sure it ever worked

**Comment by kantmakm** [comment]
It very well may have written the file without my interference, I acutually just noticed it today when trying (unsuccessfuly) to ssh as root from the box to another server that was only using password auth when looking at the debug info noticed this:

debug1: Reading configuration data /root/.ssh/config
