### ISSUE TITLE
Inventory ID in body and URL must be the same

### ISSUE THREAD

**Issue by Red967** [ansible-semaphore/semaphore#660]
Error when trying to create ssh key in develop mode - "Inventory ID in body and URL must be the same". Can someone explain why it's happend?

**Comment by fiftin** [comment]
What version of Semaphore?

UPDATE:  figured out, from develop branch.

Develop branch can contains bugs. it will fix it.

**Comment by Red967** [comment]
@fiftin so which branch better to use for stable development?

**Comment by fiftin** [comment]
2-6-stable

But code in develop branch changed a lot. I refactored it to support multible DBs. But not finished yet.

**Comment by Red967** [comment]
@fiftin i'll tried to add postgres support to devepol branch - but getting this error. So now i'm stuck. Any updates about multi db?

**Comment by TrayserCassa** [comment]
This bug happens, because on create environment or keys the code try to get the Object from the empty Table and then the project id is empty.

example ssh (keys.go):

var key db.AccessKey
key.ProjectID is nil

if you want to develop you can uncomment the code which checked the ProjectID
```
	//if key.ProjectID == nil || *key.ProjectID != project.ID {
	//	helpers.WriteJSON(w, http.StatusBadRequest, map[string]string{
	//		"error": "Inventory ID in body and URL must be the same",
	//	})
	//	return
	//}
```
And you need to set the ProjectID of the AccessKey like this:
```
	var key db.AccessKey
	key.ProjectID = &project.ID
```

It looks like this is copy pasted from the update method, where of course the key var contains the ProjectID

**Comment by Red967** [comment]
@TrayserCassa Thank you so much. Solved

**Comment by TrayserCassa** [comment]
well this is not closed yet, so please don't close issues while they are not fixed yet in the remote branch :)

**Comment by Red967** [comment]
@TrayserCassa Oh sry. My bad

**Comment by fiftin** [comment]
> @fiftin i'll tried to add postgres support to devepol branch - but getting this error. So now i'm stuck. Any updates about multi db?

I hope updates will be soon. I refactored migrations and tested work with postgres via https://github.com/lib/pq driver. It works.

**Comment by Red967** [comment]
@TrayserCassa Hi. Can you please help with another problem. In api/tasks/http.go inside GetTaskMiddleware function the value of  taskID always 0. Why it's can happened?

**Comment by fiftin** [comment]
@Red967 
Thank you for reporting about the bug. It is UI bug - required field (`project_id`) missed in request body. Fixed in branch `develop`. I will be very grateful if you test it :)

**Comment by Red967** [comment]
@fiftin Working as expected.
