### ISSUE TITLE
Is There a way to save cli arguments in Semaphore?

### ISSUE THREAD

**Issue by Bkbest** [ansible-semaphore/semaphore#662]
Hi team,

I am running the latest Semaphore version, While running the tasks, we provide **CLI Arguments** to the extra CLI Arguments text area as in the image:
![image](https://user-images.githubusercontent.com/16200783/115350273-874b5f80-a1d2-11eb-89ca-093a051ee14c.png)

I would like to know if there is a way to save cli arguments in semaphore itself so that I won't need to copy paste them all the time before running the task, since we have good number of CLI arguments to provide.

Thanks,
Aravind

**Comment by fiftin** [comment]
Hi @Bkbest 

Thank you for the question. You found UI bug 👍 :) Task Template must have textarea for extra args. I will fix it ASAP.

**Comment by fiftin** [comment]
Fixed in https://github.com/ansible-semaphore/semaphore/releases/tag/v2.6.9.

I will be very grateful if you test the fix :)

![image](https://user-images.githubusercontent.com/914224/115553794-4123f800-a2c7-11eb-8d26-37de51255c0b.png)

**Comment by Bkbest** [comment]
Hi @fiftin,

Thank you for such a quick response, I will test this for you and get back!!

Aravind

**Comment by Bkbest** [comment]
Hi @fiftin,

sorry for the delay, but I have finally tested this.
Both creating the task template from UI as well as from rest endpoint, works like a charm now.

Thanks,
Aravind

**Comment by fiftin** [comment]
@Bkbest Thank you!
