### ISSUE TITLE
Any plan to release a docker image with ansible 2.10?

### ISSUE THREAD

**Issue by jcollas** [ansible-semaphore/semaphore#663]
I'd like to use the ansiblesemaphone/semaphore docker image with ansible 2.10, since i'm using absible-galaxy collections.

**Comment by fiftin** [comment]
For production image we install ansible via apk. And currently it is v2.8.16.

Do you have any suggestions on how to install a newer version?

@TrayserCassa may be you have ideas? We can install latest version via pip3, right? Or it is bad idea for production?

**Comment by TrayserCassa** [comment]
we execute all commands in a shell, so I don't see a Problem for Production. But if he want to use the upstream version of Ansible, @jcollas can Build his own image. This is what I would do. 

I installed the latest version on my arch with pacman and after googleing I see no difference between pip and system installation. It's up to you @fiftin.

**Comment by jcollas** [comment]
I'll take a shot at buildin a custom image.  Semaphore looks good, thanks for building it.
