### ISSUE TITLE
Ansible semaphore and sshpass

### ISSUE THREAD

**Issue by bpmb82** [ansible-semaphore/semaphore#665]
The default docker image doesn't have _sshpass_ installed so it can't handle passing passwords.

I then built my own docker image: https://github.com/bpmb82/ansible-semaphore

This one works fine and I no longer see the message regarding _sshpass_ but it does fail when connecting to certain hosts that require a password. Even when I put the password in the inventory file I cannot connect..

Are ssh passwords unsupported by semaphore?

**Comment by fiftin** [comment]
You can only specified password as extra argument https://github.com/ansible-semaphore/semaphore/issues/662.

**Comment by bpmb82** [comment]
@fiftin Could you show me how? I've tried this:

["-e","ansible_user=myuser ansible_password=mypassword"]

But I still get an error about incorrect username/ password.. Semaphore doesn't support this from the inventory file?

**Comment by fiftin** [comment]
@bpmb82 It's supports. Semaphore supports all what supports Ansible. 

Did you try to use this login/password from command line like: `ansible-playbook ... -e "ansible_user=myuser ansible_password=mypassword"`? Semaphore do similar - it is simply runs ansible-playbook with args.

**Comment by bpmb82** [comment]
Yes I did and that works..

**Comment by fiftin** [comment]
@bpmb82 I will try to reproduce, thank you

**Comment by bpmb82** [comment]
I will have another look as well, just to be sure, this is what I'm passing:

`["-e","ansible_user=myuser ansible_password=mypassword"]`

**Comment by fiftin** [comment]
Hi @bpmb82 

This feature implemented in v2.7.22.

Create new Access Key with type `Login with password`

![image](https://user-images.githubusercontent.com/914224/133782005-571c8fc8-a6fa-44f7-bd3c-181ae7cd8d35.png)

User it in Inventory settings:

![image](https://user-images.githubusercontent.com/914224/133781848-869c5a38-6197-4ad4-b017-899f07db6b31.png)

Available here: https://github.com/ansible-semaphore/semaphore/releases/tag/v2.7.22
Or via snap `sudo snap install semaphore`: https://snapcraft.io/semaphore

You should install `sshpass` to use this feature.

**Comment by esfateev** [comment]
Hi @fiftin,
Unfortunately, docker image still don't include package sshpass. Is it possible to add? As I righly understand, it's impossible to use new feature (Access Key with type Login with password) without this package inside docker image. 

Thanks!

**Comment by fiftin** [comment]
Thank you @esfateev , I will fix it ASAP.

**Comment by fiftin** [comment]
@esfateev please try latest version of Semaphore image.

**Comment by esfateev** [comment]
@fiftin Checked with latest version of docker container, fixed. Thanks a lot!
