### ISSUE TITLE
Fails loading inventory

### ISSUE THREAD

**Issue by flantel** [ansible-semaphore/semaphore#667]
Hi. Trying Sepaphore for the first time. 

I have tried both using my existing file inventory (ini format), as well as a static set up as follows:
```
[test]
192.168.2.23
```

I get the following error when I try to run the playbook.

```
 11:23:53 AM
installing static inventory
11:23:53 AM
Could not unmarshal arguments to []string
11:23:53 AM
Listing playbook hosts failed: json: cannot unmarshal object into Go value of type []string 
```

Is there a specific inventory format I need to use?

**Comment by fiftin** [comment]
Thank you, I will try to reproduce it ASAP.

**Comment by fiftin** [comment]
Sorry for delay with answer. I can't reproduce the issue.

**Comment by fiftin** [comment]
Looks like you entered incorrect template or task args.

Validation of the args required. Will be added.

**Comment by fiftin** [comment]
Validation added (start from v2.8.17)
