### ISSUE TITLE
Count not read username : No such device or address

### ISSUE THREAD

**Issue by gvenka008c** [ansible-semaphore/semaphore#67]
I have the playbook in path caps-sps/jenkins_mesos/ansible/jenkins_ansible.yml

I added the same in Semaphore Jobs section, but seeing the below error. Can you please suggest?

runner.js:241
Starting play caps-sps/jenkins_mesos/ansible/jenkins_ansible.yml.
runner.js:241 ERROR! the playbook: caps-sps/jenkins_mesos/ansible/jenkins_ansible.yml could not be found
runner.js:216 done. 1

**Comment by matejkramny** [comment]
Hi there,

Can you inspect what's inside your `$HOME`?, If set, semaphore will store data under this directory.

**Comment by gvenka008c** [comment]
@matejkramny Thanks. figured it out.
