### ISSUE TITLE
Is it possible to integrate existing Ansible into semaphore ?

### ISSUE THREAD

**Issue by ledufakademy** [ansible-semaphore/semaphore#670]
hello,

i mean using Alternatives layout : 
https://docs.ansible.com/ansible/latest/user_guide/sample_setup.html#id2

how to integrate this in semaphore ?
we use , vault, ssh custom port, only yaml file, group_vars, host_vars, roles .

Actualy we have one git repository for all , with root : /etc/ansible 
and ./playbooks/prod/...yml , ./playbooks/test/...yml.

**Comment by fiftin** [comment]
@ledufakademy Hello,

![image](https://user-images.githubusercontent.com/914224/117876974-6780f600-b2bd-11eb-9123-e80dd0db24d1.png)

**Comment by ledufakademy** [comment]
> @ledufakademy Hello,
> 
> ![image](https://user-images.githubusercontent.com/914224/117876974-6780f600-b2bd-11eb-9123-e80dd0db24d1.png)

Hello fiftin,

it's not working.
please take note that all our SSHD server are running on port 15366.
i click on create, noting happened.
i do not understand why i need sshkey for accessing : /etc/ansible/inventories/test/hosts ?
But anyway , with a good key/pub ... it's not wroking.

i also have an issue with playbook repository : did the solution need ssh access to gitlab server  ? (because our gitlab server only offer HTTPS git clone) ?

Last question : did semaphore have a scheduler for playbooks launching ?

**Comment by fiftin** [comment]
> please take note that all our SSHD server are running on port 15366. 

It can be configured in hosts file

> i do not understand why i need sshkey for accessing : /etc/ansible/inventories/test/hosts ?

Do you have inventory on the server and roles in GitLab repo? Currently Semaphore can works only with single repo for task (roles and inventory in same git repo)

> Last question : did semaphore have a scheduler for playbooks launching ?

Development in progress.

**Comment by fiftin** [comment]
> i do not understand why i need sshkey for accessing : /etc/ansible/inventories/test/hosts ?

The SSH key required for access to servers described in hosts.
