### ISSUE TITLE
Not able to get Email alerts

### ISSUE THREAD

**Issue by Bkbest** [ansible-semaphore/semaphore#673]
Hi team,

I am running latest semaphore version as of today: 2.6.9

I have configured email alerts in:
1. config.json
2. enabled alerts in project settings in semaphore UI.

The mail host I am using is valid. (I have tested the mail host from a small shell script to send a sample email)

Can you let me know what I am missing here?

Thanks,
Aravind

**Comment by fiftin** [comment]
@Bkbest I will check it, thank you.

**Comment by Bkbest** [comment]
Hi @fiftin, I am getting notifications. Are the notifications only on failure?

**Comment by fiftin** [comment]
Yes, it is. But I agree, success results require notifications too.

**Comment by Bkbest** [comment]
yeah, also @fiftin , I am receiving email alerts like this:
![image](https://user-images.githubusercontent.com/16200783/123269886-0768ab00-d51d-11eb-88ba-e61a009947be.png)
any Idea what I should do?
we use outlook.

**Comment by fiftin** [comment]
You can see task log for details.

or did I misunderstand your question?

**Comment by Bkbest** [comment]
That is how I received the email, there was no clickable link in the email to see the details.
![image](https://user-images.githubusercontent.com/16200783/123272295-413ab100-d51f-11eb-95dd-d4c0fef336e4.png)

Is there a way I can redirect from email to semaphore?

**Comment by fiftin** [comment]
Looks like it is a bug. Link must have full URL, it contains only path.

**Comment by fiftin** [comment]
To get full URL in email/telegram message you should specify `web_host` in config file.

Also I added Telegram notifications for success tasks.
