### ISSUE TITLE
Upgrade Error 2.7.0

### ISSUE THREAD

**Issue by scomcd** [ansible-semaphore/semaphore#677]
Hi,
I am running Ansible-Semaphore 2.6.9 on Oracle Linux 8.4.

After installing the semaphore binary from the rpm 'semaphore_2.7.0_linux_amd64.rpm',
then attempting to upgrade it to Semaphore 2.7.0 I receive the following error.

# /usr/bin/semaphore -config /etc/semaphore/config.json -upgrade
Using config file: /etc/semaphore/config.json
current release is vv2.7.0
panic: cannot find binary for your system

goroutine 1 [running]:
main.main()
        /go/src/github.com/ansible-semaphore/semaphore/cli/main.go:44 +0x98e

**Comment by fiftin** [comment]
Hi @scomcd,

You don't need to run `-upgrade` after upgrading via rpm.

You can check current version of Semaphore by command:

```
semaphore -version
```

Option `-update` is outdated and will be removed. Do you have any problem with running v 2.7.0?

**Comment by scomcd** [comment]
Hi @fiftin,

Thank you for clarifying the upgrade process.
No problems encountered so far since updating to v 2.7.0.
