### ISSUE TITLE
after upgrade v2.7.0 , the project Dashboard loading failed

### ISSUE THREAD

**Issue by keepcleargas** [ansible-semaphore/semaphore#678]
when i upgrade form v2.6.9 to v2.7.0
i got the error:
<img width="1402" alt="图片" src="https://user-images.githubusercontent.com/1215177/124871633-d8f7cf00-dff6-11eb-8292-a0aa5841a407.png">
And my project Dashboard is loading failed.
<img width="1587" alt="图片" src="https://user-images.githubusercontent.com/1215177/124871743-fb89e800-dff6-11eb-9f9d-c2d6f6710dc6.png">

api `http://192.168.31.175:8000/api/project/59/tasks/last`  is http status `400` - bad request.

**Comment by keepcleargas** [comment]
i just execute sql
```
update task set project_id = 0 where project_id is null
```
issue fixed

**Comment by fiftin** [comment]
Hm, it looks like a bug. Thank you, I will check.

**Comment by fiftin** [comment]
Fixed by migration.
