### ISSUE TITLE
New Installation 2.7.0 Mysql DB error Invalid DSN

### ISSUE THREAD

**Issue by scomcd** [ansible-semaphore/semaphore#679]
Hi,

When performing a fresh installation of ansible-semaphore 2.7.0 on a new host running Oracle Linux 8.4, Mariadb,
I encountered the following error during the intial semaphore-setup process.

 > Is this correct? (yes/no): yes
 > Config output directory (default /root/tmp): /etc/semaphore
 Running: mkdir -p /etc/semaphore..
 Configuration written to /etc/semaphore/config.json..
 Pinging db..
WARN[0078] invalid DSN: missing the slash separating the database name

 Cannot connect to database!
 Error 1049: Unknown database 'semaphore'

If I create the DB 'semaphore' manually via the mysql client then re-run the semaphore-setup, the
installation proceeds normally.

#----------------------------------------------------------------------------------#
 Setup options and Console Output:
#----------------------------------------------------------------------------------#

`# semaphore -setup

 Hello! You will now be guided through a setup to:

 1. Set up configuration for a MySQL/MariaDB database
 2. Set up a path for your playbooks (auto-created)
 3. Run database Migrations
 4. Set up initial semaphore user & password

 > DB
   1 - MySQL
   2 - bbolt
   (default 1): 1
 > DB Hostname (default 127.0.0.1:3306): 127.0.0.1:3306
 > DB User (default root): root
 > DB Password: obfuscated
 > DB Name (default semaphore): semaphore
 > Playbook path (default /tmp/semaphore): /opt/semaphore
 > Web root URL (optional, see https://github.com/ansible-semaphore/semaphore/wiki/Web-root-URL):
WARN[0051] An input error occurred:unexpected newline
 > Enable email alerts (y/n, default n): n
 > Enable telegram alerts (y/n, default n): n
 > Enable LDAP authentication (y/n, default n): n

 Generated configuration:
 {
        "mysql": {
                "host": "127.0.0.1:3306",
                "user": "root",
                "pass": "obfuscated",
                "name": "semaphore"
        },
        "bolt": {
                "host": "",
                "user": "",
                "pass": "",
                "name": ""
        },
        "port": "",
        "interface": "",
        "tmp_path": "/opt/semaphore",
        "cookie_hash": "dre3IhNpH0Ht1lyRNA/Swvi4BiC9WtYuSBKBCJ3Xjys=",
        "cookie_encryption": "gteNVAfs6r2mzfRcltqcvzeo4tKxfCjUxkarYXX2pzw=",
        "email_sender": "",
        "email_host": "",
        "email_port": "",
        "web_host": "",
        "ldap_binddn": "",
        "ldap_bindpassword": "",
        "ldap_server": "",
        "ldap_searchdn": "",
        "ldap_searchfilter": "",
        "ldap_mappings": {
                "dn": "",
                "mail": "",
                "uid": "",
                "cn": ""
        },
        "telegram_chat": "",
        "telegram_token": "",
        "concurrency_mode": "",
        "max_parallel_tasks": 0,
        "email_alert": false,
        "telegram_alert": false,
        "ldap_enable": false,
        "ldap_needtls": false
 }

 > Is this correct? (yes/no): yes
 > Config output directory (default /root/tmp): /etc/semaphore
 Running: mkdir -p /etc/semaphore..
 Configuration written to /etc/semaphore/config.json..
 Pinging db..
WARN[0078] invalid DSN: missing the slash separating the database name

 Cannot connect to database!
 Error 1049: Unknown database 'semaphore'
 `

**Comment by RockSlice** [comment]
I am also having this issue.  Any idea how to get past this?

**Comment by scomcd** [comment]
Hi @RockSlice 

As a work-around, we created the 'semaphore' db in MariaDB manually via the mysql command line.
eg:
$ mysql -u root -p
MariaDB [(none)]> CREATE DATABASE semaphore;

Then re-ran the semaphore-setup script from the OS command line as per normal.

**Comment by fiftin** [comment]
Yes, it is a bug, thank you!

**Comment by fiftin** [comment]
Bug fixed in v2.7.3+
