### ISSUE TITLE
Installation fails with foreign key constraint error

### ISSUE THREAD

**Issue by kolbyjack** [ansible-semaphore/semaphore#681]
I'm trying to set up an semaphore docker stack using the docker-compose file from https://github.com/ansible-semaphore/semaphore/issues/148#issuecomment-801076001, but when I run docker-compose up, the container fails with

```
Error 1005: Can't create table `semaphore`.`task__output` (errno: 150 "Foreign key constraint is incorrectly formed")
```

**Comment by kolbyjack** [comment]
After updating my stack to use `mysql:5.6` instead of `mariadb:10`, it started working.

**Comment by fiftin** [comment]
Thank you. I think it is a bug. I will try reproduce it.

**Comment by atroxes** [comment]
Experienced the same error when trying to do a regular installation on Rocky Linux 8.4.

Problem appeared when using "MariaDB-server-10.6.4-1.el8.x86_64" from the official MariaDB CentOS repository.

Seeing @kolbyjack had succeeded using MySQL 5.6 I figured it might be a new feature/change/deprecation in MariaDB and I tried going back to "mariadb-server-3:10.3.28-1.module+el8.4.0+427+adf35707.x86_64" from the Rocky Linux repos. Also made sure to remove the MariaDB data directory contents before switching to 10.3.28.

Error disappeared and Semaphore server is now starting up without issue.

**Comment by nbkgroup** [comment]
Same error on Ubuntu 20.04.3 LTS using 10.6.4+maria~focal.

```code
Running DB Migrations..
Checking DB migrations
Creating migrations table
Executing migration v0.0.0 (at 2021-09-01 13:03:25.666791794 +0300 MSK m=+26.535953079)...
 [12/0]9]
Executing migration v1.0.0 (at 2021-09-01 13:03:25.805213194 +0300 MSK m=+26.674374502)...
 [6/200]WARN[0026] 
 ERR! Query: create table `task__output`
(
    task_id int not null
        references task
            on delete cascade,
    task varchar(255) not null,
    time datetime not null,
    output longtext not null
)

 
Rolling back v1.0.0 (time: 2021-09-01 13:03:25.884467679 +0300 MSK m=+26.753628992)...
Rollback SQL does not exist.

Database migrations failed!
 Error 1005: Can't create table `semaphore`.`task__output` (errno: 150 "Foreign key constraint is incorrectly formed")
```

**Comment by HuTaeh** [comment]
Same error on Debian 11.0 using 10.5.11-MariaDB
```
Running DB Migrations..
Checking DB migrations
Creating migrations table
Executing migration v0.0.0 (at 2021-09-14 11:48:51.809117054 +0200 CEST m=+375.572080452)...
 [12/0]9]
Executing migration v1.0.0 (at 2021-09-14 11:48:52.028492988 +0200 CEST m=+375.791456387)...
 [6/200]WARN[0375] 
 ERR! Query: create table `task__output`
(
    task_id int not null
        references task
            on delete cascade,
    task varchar(255) not null,
    time datetime not null,
    output longtext not null
)

 
Rolling back v1.0.0 (time: 2021-09-14 11:48:52.14387883 +0200 CEST m=+375.906842248)...
Rollback SQL does not exist.
```

**Comment by fiftin** [comment]
Thank you. I will check MariaDB

**Comment by ziptx** [comment]
Troubleshooting detail:

Environment:  NAME="AlmaLinux" / VERSION="8.4 (Electric Cheetah)" / ID="almalinux" / ID\_LIKE="rhel centos fedora" / VERSION\_ID="8.4"

What Works:  
semaphore 2.7.16 setup with MariaDB 10.4

Completed a mysqldump of 10.4.21-MariaDB after a fresh setup from semaphore\_2.7.16\_linux\_amd64.rpm.  \[Dump script below\]  
Applied the sqldump to a fresh install of 10.6.4-MariaDB ... NO ERRORs.   

The failure seems to be related to the actual migration script itself ... near v1.0.0 as documented by HuTaeh.

The bug surfaces with the use of MariaDB 10.6+ during 'setup'.

\==

\-- MariaDB dump 10.19  Distrib 10.4.21-MariaDB, for Linux (x86\_64)  
\--  
\-- Host: localhost    Database: semaphore  
\-- ------------------------------------------------------  
\-- Server version       10.4.21-MariaDB

/\*!40101 SET @OLD\_CHARACTER\_SET\_CLIENT=@@CHARACTER\_SET\_CLIENT \*/;  
/\*!40101 SET @OLD\_CHARACTER\_SET\_RESULTS=@@CHARACTER\_SET\_RESULTS \*/;  
/\*!40101 SET @OLD\_COLLATION\_CONNECTION=@@COLLATION\_CONNECTION \*/;  
/\*!40101 SET NAMES utf8mb4 \*/;  
/\*!40103 SET @OLD\_TIME\_ZONE=@@TIME\_ZONE \*/;  
/\*!40103 SET TIME\_ZONE='+00:00' \*/;  
/\*!40014 SET @OLD\_UNIQUE\_CHECKS=@@UNIQUE\_CHECKS, UNIQUE\_CHECKS=0 \*/;  
/\*!40014 SET @OLD\_FOREIGN\_KEY\_CHECKS=@@FOREIGN\_KEY\_CHECKS, FOREIGN\_KEY\_CHECKS=0 \*/;  
/\*!40101 SET @OLD\_SQL\_MODE=@@SQL\_MODE, SQL\_MODE='NO\_AUTO\_VALUE\_ON\_ZERO' \*/;  
/\*!40111 SET @OLD\_SQL\_NOTES=@@SQL\_NOTES, SQL\_NOTES=0 \*/;

\--  
\-- Table structure for table \`access\_key\`  
\--

DROP TABLE IF EXISTS \`access\_key\`;  
/\*!40101 SET @saved\_cs\_client     = @@character\_set\_client \*/;  
/\*!40101 SET character\_set\_client = utf8 \*/;  
CREATE TABLE \`access\_key\` (  
 \`id\` int(11) NOT NULL AUTO\_INCREMENT,  
 \`name\` varchar(255) NOT NULL,  
 \`type\` varchar(255) NOT NULL,  
 \`project\_id\` int(11) DEFAULT NULL,  
 \`secret\` text DEFAULT NULL,  
 \`removed\` tinyint(1) DEFAULT 0,  
 PRIMARY KEY (\`id\`),  
 KEY \`project\_id\` (\`project\_id\`),  
 CONSTRAINT \`access\_key\_ibfk\_1\` FOREIGN KEY (\`project\_id\`) REFERENCES \`project\` (\`id\`) ON DELETE SET NULL  
) ENGINE=InnoDB DEFAULT CHARSET=latin1;  
/\*!40101 SET character\_set\_client = @saved\_cs\_client \*/;

\--  
\-- Table structure for table \`event\`  
\--

DROP TABLE IF EXISTS \`event\`;  
/\*!40101 SET @saved\_cs\_client     = @@character\_set\_client \*/;  
/\*!40101 SET character\_set\_client = utf8 \*/;  
CREATE TABLE \`event\` (  
 \`project\_id\` int(11) DEFAULT NULL,  
 \`object\_id\` int(11) DEFAULT NULL,  
 \`object\_type\` varchar(20) DEFAULT '',  
 \`description\` text DEFAULT NULL,  
 \`created\` datetime NOT NULL,  
 \`user\_id\` int(11) DEFAULT NULL,  
 KEY \`project\_id\` (\`project\_id\`),  
 KEY \`object\_id\` (\`object\_id\`),  
 KEY \`created\` (\`created\`)  
) ENGINE=InnoDB DEFAULT CHARSET=latin1;  
/\*!40101 SET character\_set\_client = @saved\_cs\_client \*/;

\--  
\-- Table structure for table \`migrations\`  
\--

DROP TABLE IF EXISTS \`migrations\`;  
/\*!40101 SET @saved\_cs\_client     = @@character\_set\_client \*/;  
/\*!40101 SET character\_set\_client = utf8 \*/;  
CREATE TABLE \`migrations\` (  
 \`version\` varchar(255) NOT NULL,  
 \`upgraded\_date\` datetime DEFAULT NULL,  
 \`notes\` text DEFAULT NULL,  
 PRIMARY KEY (\`version\`)  
) ENGINE=InnoDB DEFAULT CHARSET=latin1;  
/\*!40101 SET character\_set\_client = @saved\_cs\_client \*/;

\--  
\-- Table structure for table \`project\`  
\--

DROP TABLE IF EXISTS \`project\`;  
/\*!40101 SET @saved\_cs\_client     = @@character\_set\_client \*/;  
/\*!40101 SET character\_set\_client = utf8 \*/;  
CREATE TABLE \`project\` (  
 \`id\` int(11) NOT NULL AUTO\_INCREMENT,  
 \`created\` datetime NOT NULL,  
 \`name\` varchar(255) NOT NULL,  
 \`alert\` tinyint(1) NOT NULL DEFAULT 0,  
 \`alert\_chat\` varchar(10) DEFAULT '',  
 PRIMARY KEY (\`id\`)  
) ENGINE=InnoDB DEFAULT CHARSET=latin1;  
/\*!40101 SET character\_set\_client = @saved\_cs\_client \*/;

\--  
\-- Table structure for table \`project\_\_environment\`  
\--

DROP TABLE IF EXISTS \`project\_\_environment\`;  
/\*!40101 SET @saved\_cs\_client     = @@character\_set\_client \*/;  
/\*!40101 SET character\_set\_client = utf8 \*/;  
CREATE TABLE \`project\_\_environment\` (  
 \`id\` int(11) NOT NULL AUTO\_INCREMENT,  
 \`project\_id\` int(11) NOT NULL,  
 \`password\` varchar(255) DEFAULT NULL,  
 \`json\` longtext NOT NULL,  
 \`name\` varchar(255) DEFAULT NULL,  
 \`removed\` tinyint(1) DEFAULT 0,  
 PRIMARY KEY (\`id\`),  
 KEY \`project\_id\` (\`project\_id\`),  
 CONSTRAINT \`project\_\_environment\_ibfk\_1\` FOREIGN KEY (\`project\_id\`) REFERENCES \`project\` (\`id\`) ON DELETE CASCADE  
) ENGINE=InnoDB DEFAULT CHARSET=latin1;  
/\*!40101 SET character\_set\_client = @saved\_cs\_client \*/;

\--  
\-- Table structure for table \`project\_\_inventory\`  
\--

DROP TABLE IF EXISTS \`project\_\_inventory\`;  
/\*!40101 SET @saved\_cs\_client     = @@character\_set\_client \*/;  
/\*!40101 SET character\_set\_client = utf8 \*/;  
CREATE TABLE \`project\_\_inventory\` (  
 \`id\` int(11) NOT NULL AUTO\_INCREMENT,  
 \`project\_id\` int(11) NOT NULL,  
 \`type\` varchar(255) NOT NULL,  
 \`inventory\` longtext NOT NULL,  
 \`ssh\_key\_id\` int(11) DEFAULT NULL,  
 \`name\` varchar(255) DEFAULT NULL,  
 \`removed\` tinyint(1) DEFAULT 0,  
 \`become\_key\_id\` int(11) DEFAULT NULL,  
 PRIMARY KEY (\`id\`),  
 KEY \`project\_id\` (\`project\_id\`),  
 CONSTRAINT \`project\_\_inventory\_ibfk\_1\` FOREIGN KEY (\`project\_id\`) REFERENCES \`project\` (\`id\`) ON DELETE CASCADE  
) ENGINE=InnoDB DEFAULT CHARSET=latin1;  
/\*!40101 SET character\_set\_client = @saved\_cs\_client \*/;

\--  
\-- Table structure for table \`project\_\_repository\`  
\--

DROP TABLE IF EXISTS \`project\_\_repository\`;  
/\*!40101 SET @saved\_cs\_client     = @@character\_set\_client \*/;  
/\*!40101 SET character\_set\_client = utf8 \*/;  
CREATE TABLE \`project\_\_repository\` (  
 \`id\` int(11) NOT NULL AUTO\_INCREMENT,  
 \`project\_id\` int(11) NOT NULL,  
 \`git\_url\` text NOT NULL,  
 \`ssh\_key\_id\` int(11) NOT NULL,  
 \`name\` varchar(255) DEFAULT NULL,  
 \`removed\` tinyint(1) DEFAULT 0,  
 PRIMARY KEY (\`id\`),  
 KEY \`project\_id\` (\`project\_id\`),  
 KEY \`ssh\_key\_id\` (\`ssh\_key\_id\`),  
 CONSTRAINT \`project\_\_repository\_ibfk\_1\` FOREIGN KEY (\`project\_id\`) REFERENCES \`project\` (\`id\`) ON DELETE CASCADE,  
 CONSTRAINT \`project\_\_repository\_ibfk\_2\` FOREIGN KEY (\`ssh\_key\_id\`) REFERENCES \`access\_key\` (\`id\`)  
) ENGINE=InnoDB DEFAULT CHARSET=latin1;  
/\*!40101 SET character\_set\_client = @saved\_cs\_client \*/;

\--  
\-- Table structure for table \`project\_\_schedule\`  
\--

DROP TABLE IF EXISTS \`project\_\_schedule\`;  
/\*!40101 SET @saved\_cs\_client     = @@character\_set\_client \*/;  
/\*!40101 SET character\_set\_client = utf8 \*/;  
CREATE TABLE \`project\_\_schedule\` (  
 \`id\` int(11) NOT NULL AUTO\_INCREMENT,  
 \`template\_id\` int(11) DEFAULT NULL,  
 \`project\_id\` int(11) NOT NULL,  
 \`cron\_format\` varchar(255) NOT NULL,  
 PRIMARY KEY (\`id\`)  
) ENGINE=InnoDB DEFAULT CHARSET=latin1;  
/\*!40101 SET character\_set\_client = @saved\_cs\_client \*/;

\--  
\-- Table structure for table \`project\_\_template\`  
\--

DROP TABLE IF EXISTS \`project\_\_template\`;  
/\*!40101 SET @saved\_cs\_client     = @@character\_set\_client \*/;  
/\*!40101 SET character\_set\_client = utf8 \*/;  
CREATE TABLE \`project\_\_template\` (  
 \`id\` int(11) NOT NULL AUTO\_INCREMENT,  
 \`project\_id\` int(11) NOT NULL,  
 \`inventory\_id\` int(11) NOT NULL,  
 \`repository\_id\` int(11) NOT NULL,  
 \`environment\_id\` int(11) DEFAULT NULL,  
 \`playbook\` varchar(255) NOT NULL,  
 \`arguments\` text DEFAULT NULL,  
 \`override\_args\` tinyint(1) NOT NULL DEFAULT 0,  
 \`alias\` varchar(100) DEFAULT NULL,  
 \`description\` longtext DEFAULT NULL,  
 \`removed\` tinyint(1) NOT NULL DEFAULT 0,  
 \`vault\_pass\_id\` int(11) DEFAULT NULL,  
 PRIMARY KEY (\`id\`),  
 KEY \`project\_id\` (\`project\_id\`),  
 KEY \`inventory\_id\` (\`inventory\_id\`),  
 KEY \`repository\_id\` (\`repository\_id\`),  
 KEY \`environment\_id\` (\`environment\_id\`),  
 CONSTRAINT \`project\_\_template\_ibfk\_1\` FOREIGN KEY (\`project\_id\`) REFERENCES \`project\` (\`id\`) ON DELETE CASCADE,  
 CONSTRAINT \`project\_\_template\_ibfk\_3\` FOREIGN KEY (\`inventory\_id\`) REFERENCES \`project\_\_inventory\` (\`id\`),  
 CONSTRAINT \`project\_\_template\_ibfk\_4\` FOREIGN KEY (\`repository\_id\`) REFERENCES \`project\_\_repository\` (\`id\`),  
 CONSTRAINT \`project\_\_template\_ibfk\_5\` FOREIGN KEY (\`environment\_id\`) REFERENCES \`project\_\_environment\` (\`id\`)  
) ENGINE=InnoDB DEFAULT CHARSET=latin1;  
/\*!40101 SET character\_set\_client = @saved\_cs\_client \*/;

\--  
\-- Table structure for table \`project\_\_user\`  
\--

DROP TABLE IF EXISTS \`project\_\_user\`;  
/\*!40101 SET @saved\_cs\_client     = @@character\_set\_client \*/;  
/\*!40101 SET character\_set\_client = utf8 \*/;  
CREATE TABLE \`project\_\_user\` (  
 \`project\_id\` int(11) NOT NULL,  
 \`user\_id\` int(11) NOT NULL,  
 \`admin\` tinyint(1) NOT NULL DEFAULT 0,  
 UNIQUE KEY \`project\_id\` (\`project\_id\`,\`user\_id\`),  
 KEY \`user\_id\` (\`user\_id\`),  
 CONSTRAINT \`project\_\_user\_ibfk\_1\` FOREIGN KEY (\`project\_id\`) REFERENCES \`project\` (\`id\`) ON DELETE CASCADE,  
 CONSTRAINT \`project\_\_user\_ibfk\_2\` FOREIGN KEY (\`user\_id\`) REFERENCES \`user\` (\`id\`) ON DELETE CASCADE  
) ENGINE=InnoDB DEFAULT CHARSET=latin1;  
/\*!40101 SET character\_set\_client = @saved\_cs\_client \*/;

\--  
\-- Table structure for table \`session\`  
\--

DROP TABLE IF EXISTS \`session\`;  
/\*!40101 SET @saved\_cs\_client     = @@character\_set\_client \*/;  
/\*!40101 SET character\_set\_client = utf8 \*/;  
CREATE TABLE \`session\` (  
 \`id\` int(11) NOT NULL AUTO\_INCREMENT,  
 \`user\_id\` int(11) NOT NULL,  
 \`created\` datetime NOT NULL,  
 \`last\_active\` datetime NOT NULL,  
 \`ip\` varchar(39) NOT NULL DEFAULT '',  
 \`user\_agent\` text NOT NULL,  
 \`expired\` tinyint(1) NOT NULL DEFAULT 0,  
 PRIMARY KEY (\`id\`),  
 KEY \`expired\` (\`expired\`),  
 KEY \`user\_id\` (\`user\_id\`)  
) ENGINE=InnoDB DEFAULT CHARSET=latin1;  
/\*!40101 SET character\_set\_client = @saved\_cs\_client \*/;

\--  
\-- Table structure for table \`task\`  
\--

DROP TABLE IF EXISTS \`task\`;  
/\*!40101 SET @saved\_cs\_client     = @@character\_set\_client \*/;  
/\*!40101 SET character\_set\_client = utf8 \*/;  
CREATE TABLE \`task\` (  
 \`id\` int(11) NOT NULL AUTO\_INCREMENT,  
 \`template\_id\` int(11) NOT NULL,  
 \`status\` varchar(255) NOT NULL,  
 \`playbook\` varchar(255) NOT NULL,  
 \`environment\` longtext DEFAULT NULL,  
 \`debug\` tinyint(1) NOT NULL DEFAULT 0,  
 \`created\` datetime DEFAULT NULL,  
 \`start\` datetime DEFAULT NULL,  
 \`end\` datetime DEFAULT NULL,  
 \`user\_id\` int(11) DEFAULT NULL,  
 \`dry\_run\` tinyint(1) NOT NULL DEFAULT 0,  
 \`arguments\` text DEFAULT NULL,  
 \`project\_id\` int(11) DEFAULT NULL,  
 PRIMARY KEY (\`id\`),  
 KEY \`template\_id\` (\`template\_id\`),  
 CONSTRAINT \`task\_ibfk\_1\` FOREIGN KEY (\`template\_id\`) REFERENCES \`project\_\_template\` (\`id\`) ON DELETE CASCADE  
) ENGINE=InnoDB DEFAULT CHARSET=latin1;  
/\*!40101 SET character\_set\_client = @saved\_cs\_client \*/;

\--  
\-- Table structure for table \`task\_\_output\`  
\--

DROP TABLE IF EXISTS \`task\_\_output\`;  
/\*!40101 SET @saved\_cs\_client     = @@character\_set\_client \*/;  
/\*!40101 SET character\_set\_client = utf8 \*/;  
CREATE TABLE \`task\_\_output\` (  
 \`id\` int(11) NOT NULL AUTO\_INCREMENT,  
 \`task\_id\` int(11) NOT NULL,  
 \`task\` varchar(255) NOT NULL,  
 \`time\` datetime NOT NULL,  
 \`output\` longtext NOT NULL,  
 PRIMARY KEY (\`id\`)  
) ENGINE=InnoDB DEFAULT CHARSET=latin1;  
/\*!40101 SET character\_set\_client = @saved\_cs\_client \*/;

\--  
\-- Table structure for table \`user\`  
\--

DROP TABLE IF EXISTS \`user\`;  
/\*!40101 SET @saved\_cs\_client     = @@character\_set\_client \*/;  
/\*!40101 SET character\_set\_client = utf8 \*/;  
CREATE TABLE \`user\` (  
 \`id\` int(11) NOT NULL AUTO\_INCREMENT,  
 \`created\` datetime NOT NULL,  
 \`username\` varchar(255) NOT NULL,  
 \`name\` varchar(255) NOT NULL,  
 \`email\` varchar(255) NOT NULL,  
 \`password\` varchar(255) NOT NULL,  
 \`alert\` tinyint(1) NOT NULL DEFAULT 0,  
 \`external\` tinyint(1) NOT NULL DEFAULT 0,  
 \`admin\` tinyint(1) NOT NULL DEFAULT 1,  
 PRIMARY KEY (\`id\`),  
 UNIQUE KEY \`username\` (\`username\`),  
 UNIQUE KEY \`email\` (\`email\`)  
) ENGINE=InnoDB AUTO\_INCREMENT=2 DEFAULT CHARSET=latin1;  
/\*!40101 SET character\_set\_client = @saved\_cs\_client \*/;

\--  
\-- Table structure for table \`user\_\_token\`  
\--

DROP TABLE IF EXISTS \`user\_\_token\`;  
/\*!40101 SET @saved\_cs\_client     = @@character\_set\_client \*/;  
/\*!40101 SET character\_set\_client = utf8 \*/;  
CREATE TABLE \`user\_\_token\` (  
 \`id\` varchar(44) NOT NULL,  
 \`created\` datetime NOT NULL,  
 \`expired\` tinyint(1) NOT NULL DEFAULT 0,  
 \`user\_id\` int(11) NOT NULL,  
 PRIMARY KEY (\`id\`)  
) ENGINE=InnoDB DEFAULT CHARSET=latin1;  
/\*!40101 SET character\_set\_client = @saved\_cs\_client \*/;  
/\*!40103 SET TIME\_ZONE=@OLD\_TIME\_ZONE \*/;

/\*!40101 SET SQL\_MODE=@OLD\_SQL\_MODE \*/;  
/\*!40014 SET FOREIGN\_KEY\_CHECKS=@OLD\_FOREIGN\_KEY\_CHECKS \*/;  
/\*!40014 SET UNIQUE\_CHECKS=@OLD\_UNIQUE\_CHECKS \*/;  
/\*!40101 SET CHARACTER\_SET\_CLIENT=@OLD\_CHARACTER\_SET\_CLIENT \*/;  
/\*!40101 SET CHARACTER\_SET\_RESULTS=@OLD\_CHARACTER\_SET\_RESULTS \*/;  
/\*!40101 SET COLLATION\_CONNECTION=@OLD\_COLLATION\_CONNECTION \*/;  
/\*!40111 SET SQL\_NOTES=@OLD\_SQL\_NOTES \*/;

==EDIT==
For those using this dump script to get 10.6 working ... you'll need this data in the 'migrations' table:
--
-- Dumping data for table `migrations`
--
LOCK TABLES `migrations` WRITE;
/*!40000 ALTER TABLE `migrations` DISABLE KEYS */;
INSERT INTO `migrations` VALUES ('0.0.0','2021-09-15 16:53:25',NULL),('1.0.0','2021-09-15 16:53:26',NULL),('1.2.0','2021-09-15 16:53:26',NULL),('1.3.0','2021-09-15 16:53:26',NULL),('1.4.0','2021-09-15 16:53:26',NULL),('1.5.0','2021-09-15 16:53:26',NULL),('1.6.0','2021-09-15 16:53:26',NULL),('1.7.0','2021-09-15 16:53:26',NULL),('1.8.0','2021-09-15 16:53:26',NULL),('1.9.0','2021-09-15 16:53:26',NULL),('2.2.1','2021-09-15 16:53:26',NULL),('2.3.0','2021-09-15 16:53:26',NULL),('2.3.1','2021-09-15 16:53:26',NULL),('2.3.2','2021-09-15 16:53:26',NULL),('2.4.0','2021-09-15 16:53:26',NULL),('2.5.0','2021-09-15 16:53:26',NULL),('2.5.2','2021-09-15 16:53:26',NULL),('2.7.1','2021-09-15 16:53:26',NULL),('2.7.10','2021-09-15 16:53:26',NULL),('2.7.12','2021-09-15 16:53:26',NULL),('2.7.13','2021-09-15 16:53:26',NULL),('2.7.4','2021-09-15 16:53:26',NULL),('2.7.6','2021-09-15 16:53:26',NULL),('2.7.8','2021-09-15 16:53:26',NULL),('2.7.9','2021-09-15 16:53:26',NULL);
/*!40000 ALTER TABLE `migrations` ENABLE KEYS */;
UNLOCK TABLES;

**Comment by fiftin** [comment]
Fixed, Meriadb supported.

**Comment by janhelwich** [comment]
@fiftin can you let us know how it was fixed?
