### ISSUE TITLE
Can't authenticate with openldap

### ISSUE THREAD

**Issue by kupe-dono** [ansible-semaphore/semaphore#685]
Hi there ! :)

I tried with a lot of difficulties to configure authentication with openldap.
You can find below my json config file anonymized : 

`
{
        "mysql": {
                "host": "127.0.0.1:3306",
                "user": "semaphore",
                "pass": "semaphore",
                "name": "semaphore"
        },
        "bolt": {
                "host": "",
                "user": "",
                "pass": "",
                "name": ""
        },
        "port": "",
        "interface": "",
        "tmp_path": "/home/ansible",
        "cookie_hash": "blablablabla",
        "cookie_encryption": "blablablablabla",
        "email_sender": "",
        "email_host": "",
        "email_port": "",
        "web_host": "",
        "ldap_binddn": "cn=readonly,ou=people,dc=ldap,dc=example,dc=com",
        "ldap_bindpassword": "password",
        "ldap_server": "ldap.example.com:389",
        "ldap_searchdn": "dc=ldap,dc=example,dc=com",
        "ldap_searchfilter": "(uid=%s)",
        "ldap_mappings": {
                "dn": "dn",
                "mail": "mail",
                "uid": "uid",
                "cn": "cn"
        },
        "telegram_chat": "",
        "telegram_token": "",
        "concurrency_mode": "",
        "max_parallel_tasks": 0,
        "email_alert": false,
        "telegram_alert": false,
        "ldap_enable": true,
        "ldap_needtls": false
 }
`

With this config file I get the following error log : 

Jul 27 21:23:44 ansible semaphore[3737]: Using config file: /etc/semaphore/config.json
Jul 27 21:23:44 ansible semaphore[3737]: Semaphore v2.7.0
Jul 27 21:23:44 ansible semaphore[3737]: Interface
Jul 27 21:23:44 ansible semaphore[3737]: Port :3000
Jul 27 21:23:44 ansible semaphore[3737]: MySQL semaphore@127.0.0.1:3306 semaphore
Jul 27 21:23:44 ansible semaphore[3737]: Tmp Path (projects home) /home/ansible
Jul 27 21:23:44 ansible semaphore[3737]: Checking DB migrations
Jul 27 21:23:44 ansible semaphore[3737]: Server is running
**Jul 27 21:23:59 ansible semaphore[3737]: time="2021-07-27T21:23:59+02:00" level=info msg="LDAP Result Code 32 \"No Such Object\": "**
Jul 27 21:23:59 ansible semaphore[3737]: 2021/07/27 21:23:59 http: panic serving 127.0.0.1:58506: sql: no rows in result set
Jul 27 21:23:59 ansible semaphore[3737]: goroutine 53 [running]:

I'm pretty sure that the problem come from the ldap_search filter wich I leave to default value.

I tried without the placeholder and set it to "ldap_searchfilter": "(&(objectclass=posixaccount)(objectclass=person))",
And get the following error : 

**Jul 27 21:29:50 ansible semaphore[3760]: time="2021-07-27T21:29:50+02:00" level=info msg="LDAP Result Code 201 \"Filter Compile Error\": ldap: finished compiling filter with extra at end: %!(EXTRA string=login_example)"**

I have difficulties to figure out if the issue come from my configuration or if it's an actual bug :(

I can confirm that my host can contact the ldap server and get the information that I'm looking for but I just can't do the same with semaphore.

Can you give me some help on this ?

Kind regards

**Comment by fiftin** [comment]
Hi @kupe-dono, please try new release https://github.com/ansible-semaphore/semaphore/releases/tag/v2.7.1

**Comment by kupe-dono** [comment]
Hi (again) @fiftin !

Great that works perfectly :+1: 

level=info msg="User test user with email test@test.local authorized via LDAP correctly" <-- made my day ! :)

Thank you !
