### ISSUE TITLE
Feature Request: Add Documentation to a Template

### ISSUE THREAD

**Issue by kaiszy** [ansible-semaphore/semaphore#689]
Hi,

for my collegues i put some ansible Jobs into semphore (they dont know ansible :). Now it would be very nice if i can add some documentation to a template for them.

Best regards,
  Kai.

**Comment by fiftin** [comment]
How do you see this feature?

**Comment by fiftin** [comment]
Done in v2.7.12.

https://github.com/ansible-semaphore/semaphore/releases/tag/v2.7.12

![image](https://user-images.githubusercontent.com/914224/131749583-54fd0aa4-7d35-4bca-b449-3203d02b67ab.png)

**Comment by kaiszy** [comment]
Sorry....back from long holidays :) Great...thanks a lot!
