### ISSUE TITLE
Adding And Configuring Boto3 library to Semaphore Docker Image?

### ISSUE THREAD

**Issue by slimandslam** [ansible-semaphore/semaphore#69]
The AWS Linux server running docker and semaphore has an IAM role assigned to it that allows it to create AWS images (e.g. virtual inventory). However, when the Ansible ec2 module is executed by Semaphore, it quickly fails with: 

```
TASK [Startup AWS Server] ******************************************************
fatal: [localhost -> localhost]: FAILED! => {"changed": false, "failed": true, "msg": "boto required for this module"}
```

I assume this is because you have not included the Boto3 library in the Semaphore Docker image. Without the Boto library, none of the Ansible EC2 modules can be used. Can you add this to the Docker image?    https://github.com/boto/boto3

**Comment by slimandslam** [comment]
Looking at this again, the issue may simply be that boto is not installed in Semaphore's Docker container?

**Comment by slimandslam** [comment]
I went ahead and added an ansible command to install boto3:

```
pip: name=boto3
```

That executes successfully, but when I get to the first EC2 module command, I still get the "boto required for this module" error.  Is there something else I need to do?

**Comment by matejkramny** [comment]
Hi @slimandslam, unfortunately this won't be supported in the current release.

Version 2 will be deployed without docker & if boto is present on the local box then it will work
