### ISSUE TITLE
Feature request: Local Tar (system directory access) playbook without Git

### ISSUE THREAD

**Issue by kupe-dono** [ansible-semaphore/semaphore#693]
(Edit) Hi again :)

Would be great if we could configure a local directory for Playbooks.
Git presents some constraints, the problems concerning the management of SSH keys do not help either.

I don't know if my request is dumb but It would be amazing if we could just map a local system directory where Ansible is already installed without using Git.

Thanks again for semaphore :) !

**Comment by fiftin** [comment]
Related to https://github.com/ansible-semaphore/semaphore/issues/715
