### ISSUE TITLE
Ask inventory on run

### ISSUE THREAD

**Issue by eherce** [ansible-semaphore/semaphore#694]
Hi all, I've been testing semaphore for a few hours and there's a feature I miss in comparison with AWX/Tower.

In AWX/Tower when you create a template there's an option to specify the inventory file on run stage. This provides high flexibility, as I may have to run the same template over different inventory files without creating the same template over and over.

I'd love this feature to be present on semaphore, could it be possible?
As an extra, I'd love the interface to support YAML format and not only JSON.

Thanks in advance,
Eduardo

**Comment by eherce** [comment]
Sorry to post another request in the same issue.

Would it be possible for the UI to provide a more interactive way of building the inventory?
Instead of only providing the code of the inventory (using JSON or YAML if you finally add this option) it'd be fantastic if you could create an inventory, and then inside the inventory you could add a host or a group.
In every level (whole inventory, host or group) you would be able to create variables using JSON or YAML

**Comment by mholttech** [comment]
I was just looking for this capability myself. I'd love to be able to select an inventory at run time.

**Comment by mapdeep** [comment]
I just wanted to know if this feature has been implemented on https://github.com/ansible-semaphore/semaphore/milestone/8. It would be of immense help and would avoid editing and changing the template while running tasks. It would be nice, at least, if this could be done via API.

**Comment by fiftin** [comment]
Done in v2.11.0-beta9
