### ISSUE TITLE
Imporve inventory text box

### ISSUE THREAD

**Issue by tiny-pangolin** [ansible-semaphore/semaphore#698]
editing inventories is currently very difficult using the built in editor. it would be nice if the pop up window was larger and/or resizable. It would also be nice if the text box would use something like [codemirror](https://codemirror.net),[codemirror-vue](https://github.surmon.me/vue-codemirror/), or [tiptap](https://www.tiptap.dev) to get syntax highlighting or a better experience. 

also this app is very simple and easy to use and manage keep up the great work.

**Comment by fiftin** [comment]
Done, codemirror-vue used.
