### ISSUE TITLE
Proxy settings

### ISSUE THREAD

**Issue by frague59** [ansible-semaphore/semaphore#7]
Hi, 

I'm currently trying to install semaphore in my corporation network. 
The main goal is to test ansible and semaphore for a day-to-day use, to distribute some django web applications for LAN and for the web.

I'm currently working behind a corporate proxy (which is a NTLM one behind a cntlm authentication proxy for linux boxes). The proxy works perfectly... proxy address is like http://<proxy_address>:3128/

I'm trying to setup semaphore's vagrant image, but it does not work due to this proxy. There are multiple areas where proxy is blocking install requests : 
* apt_repository
* apt
* npm
* bower

Each of those requests are blocked by the proxy... 
* No way to configure proxy for apt_repository. I've tried to set the "environment" dict in the playbook, but it doesn't work.
* I've *manually* tuned /etc/apt/apt.conf.d/60proxies in VM for my proxy settings > OK. Is there a way to configure it through ansible ?
* No way to configure proxy for npm ?
* .bowerrc file > OK

I'm a really beginner in ansible tech, I've took a look at playbooks, hack a bit into them, and I'm not a vagrant fan. Is there a simple way to install semaphore

Thanks for your help !

PS : commit a little bit speedy at first attempt...

**Comment by matejkramny** [comment]
Hi Francois,

Can you describe the issue?

**Comment by frague59** [comment]
proxy address is like http://proxy.example.com:3128/

**Comment by matejkramny** [comment]
Hi the vagrant file uses the ansible playbook for provisioning..

See if this helps: http://docs.ansible.com/playbooks_environment.html

There will soon be a Docker image with everything configured (currently beta in feature/ui-work branch)

**Comment by matejkramny** [comment]
Also try running the steps manually inside the box?

Configure npm: http://jjasonclark.com/how-to-setup-node-behind-web-proxy

**Comment by matejkramny** [comment]
@frague59 how's it going?

**Comment by matejkramny** [comment]
Closing as proxy settings are out of the project's control (should be system-wide)
