### ISSUE TITLE
Task not being created.

### ISSUE THREAD

**Issue by tbynum** [ansible-semaphore/semaphore#71]
I have not been able to successfully Semaphore. When I am successfully able to create a task, it fails with an error. When I correct the error, I cant get a task to even try to execute. I am running the docker versions of Redis, Mongo, and Semaphore as in the instructions. If I go to where the yml files are downloaded (/root/playbookxxxxxxxxxxx) I and able to run the play successfully by running ansible-playbook -i semaphore-hosts some.yml .

What am I doing wrong? Is Redis banged up? I cant find the log files in the Docker container to even try to troubleshoot there.

Please help.

Tim

**Comment by matejkramny** [comment]
Hmm try this:

```
$ docker ps
$ docker logs <container>
```

I don't remember exactly if it logs to the stdout or to a file.

If there are no logs, execute something like

```
$ docker cp <container>:/var/log logs
```

now inspect logs directory

**Comment by tbynum** [comment]
Here is what the log shows:

Starting play ping.yml.

../node_modules/bugsnag/lib/logger.js:29 Bugsnag:  TypeError: Cannot read property 'length' of undefined
    at playTheBook (/srv/semaphore/lib/runner.js:203:24)
    at nextTask (/srv/semaphore/node_modules/async/dist/async.js:3727:18)
    at /srv/semaphore/node_modules/async/dist/async.js:3721:17
    at /srv/semaphore/node_modules/async/dist/async.js:229:31
    at /srv/semaphore/node_modules/async/dist/async.js:753:16
    at /srv/semaphore/lib/runner.js:184:3
    at /srv/semaphore/node_modules/less-middleware/node_modules/less/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:82:15)
app.js:110 Semaphore listening on port 80
app.js:47 Mongodb connection established
10.37.130.36 - - [28/Mar/2016:00:44:52 +0000] "GET /playbook/56f764e95cc5e50600d32842/tasks HTTP/1.1" 200 2 "http://<redacted>/playbook/56f764e95cc5e50600d32842/jobs" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36"

**Comment by matejkramny** [comment]
Please recreate your job.

it is crashing as you created the job before an update which had features to define extra variables.

**Comment by tbynum** [comment]
Thank you. it is working now. So it sounds like I cannot leave the Extra Vars parameter blank when creating a new job. If that is the case, then perhaps it would be appropriate to check that mandatory fields are populated when you create the job and return an error message. I am new to Ansible and was not using any extra parameters (i.e. env) so I just left it blank.

Regards,

Tim

**Comment by tbynum** [comment]
By the way, how do you update the docker container if you have an update to the code?

**Comment by matejkramny** [comment]
Hi Tim,

It can be left blank, however it was undefined in the database as it was
created before the patch.

Thanks,
Matej
On Mon, 28 Mar 2016 at 2:03 am, tbynum <notifications@github.com> wrote:

> Thank you. it is working now. So it sounds like I cannot leave the Extra
> Vars parameter blank when creating a new job. If that is the case, then
> perhaps it would be appropriate to check that mandatory fields are
> populated when you create the job and return an error message. I am new to
> Ansible and was not using any extra parameters (i.e. env) so I just left it
> blank.
>
> Regards,
>
> Tim
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/ansible-semaphore/semaphore/issues/71#issuecomment-202179671>
>
-- 
Matej Kramny

**Comment by tbynum** [comment]
so do I need to do any patching? I assume that is now in the database so it can be blank going forward?

Tim

**Comment by matejkramny** [comment]
No patching needed.

The image is rebuilt by docker hub and then you just need to pull new image and re-create the container.

Deployment & Updates will get easier in the very near future ;)
