### ISSUE TITLE
"JSON is not valid" when using curl to trigger task

### ISSUE THREAD

**Issue by insanity54** [ansible-semaphore/semaphore#720]
I would like to run a task via cron. I am using the wiki guide at https://github.com/ansible-semaphore/semaphore/wiki/API-&-automation#to-run-a-task-template-you-need-its-id

Everything goes swimmingly until I run the following command.

```
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'Authorization: Bearer ****' -d '{"template_id": 1, "debug": true, "playbook": "site.yml", "environment": "future"}' http://192.168.69.114:3000/api/project/1/tasks -v
```

I see that the task appears in semaphore, but I get an error that the JSON is not valid.

```
10:03:54 AM Task 42 added to queue
10:03:58 AM Preparing: 42
10:03:58 AM Prepare task with template: provision
10:03:58 AM access key LEO-COMPUTE installed
10:03:58 AM Updating repository https://github.com/****/****.git
10:03:59 AM From https://github.com/****/****
10:03:59 AM * branch main -> FETCH_HEAD
10:03:59 AM Already up to date.
10:03:59 AM access key LEO-COMPUTE installed
10:03:59 AM No roles/requirements.yml file found. Skip galaxy install process.
10:03:59 AM JSON is not valid
10:03:59 AM Listing playbook hosts failed: invalid character 'u' in literal false (expecting 'a') 
```

`Listing playbook hosts failed: invalid character 'u' in literal false (expecting 'a') ` Is the error that I'm seeing. I don't know what to do about this.

I'm thinking it has something to do with the quotes around true and false. I tried adding double quotes to the "true" and "false" in the JSON data. This results in `HTTP/1.1 400 Bad Request` and no task is created in semaphore.

Is semaphore failing to parse the JSON, or is there something wrong with my API call?

**Comment by fiftin** [comment]
I think problem in `"environment": "future"`. "environment" must be valid JSON. Use this field if you want to override some fields from Environment assiciated with the task template.

**Comment by insanity54** [comment]
Ah! That explains the problem. So it's an override. Ok that explains why I still had access to my ENV variables when I just left `environment` as an empty string like in the example.
