### ISSUE TITLE
Cannot create a template without setting cron spec

### ISSUE THREAD

**Issue by MrChausson** [ansible-semaphore/semaphore#721]
*In Pre-release v2.7.13*
There is no way to create a task template without setting up cron. It would be great if it could disable cron when the field is empty.

![image](https://user-images.githubusercontent.com/28267018/132309328-1796fb46-0d66-4fe0-80f8-e5a10fdcc3e4.png)

By the way good work on that, I was waiting for this feature for a long time  :)

**Comment by MrChausson** [comment]
I just re-tested it and in fact, I can create the template.
But only if I enter something in the cron field first and then I remove everything from it.

**Comment by fiftin** [comment]
Fixed in v2.7.14

https://github.com/ansible-semaphore/semaphore/releases/tag/v2.7.14
