### ISSUE TITLE
Cannot remove cron from an already created task template

### ISSUE THREAD

**Issue by MrChausson** [ansible-semaphore/semaphore#724]
*Tested in v2.7.14*
It is not possible to remove cron from a template as it gets an error with status code 500 when clicking on save.

![image](https://user-images.githubusercontent.com/28267018/132325663-3c0bd9e9-a1f9-4626-bc55-c2b3da9e43b4.png)

**Comment by fiftin** [comment]
Will spend some time for tests :)

**Comment by fiftin** [comment]
Fixed in https://github.com/ansible-semaphore/semaphore/releases/tag/v2.7.15

**Comment by MrChausson** [comment]
Indeed, great! Closing the issue
