### ISSUE TITLE
Cannot remove anything which was used in a deleted task template

### ISSUE THREAD

**Issue by MrChausson** [ansible-semaphore/semaphore#725]
*In version v2.7.14 using official mysql docker image*

When I want to remove an inventory, I get this message:
![image](https://user-images.githubusercontent.com/28267018/132345066-262257d0-d8ea-42bb-86a3-717b1f6db9ec.png)

But I was able to figure out what that errors means. In the database, we cannot remove any row that is linked in another row.
The problem is actually that **no template is removed from the database**. As you can see here:

**My template page:**

![image](https://user-images.githubusercontent.com/28267018/132345343-f57d70b7-a402-462e-9926-85577749fd64.png)

**My project__template table**

![image](https://user-images.githubusercontent.com/28267018/132345902-2a85ed2a-3ed9-49b7-bd76-bfb2f693424e.png)

So we cannot remove any row which was previously linked to those templates...

Steps to reproduice:
- Create a template
- Remove the template
- (try to) Remove the inventory which was used by the template

**Comment by fiftin** [comment]
Agree, it is a bug. Task template can't be deleted from database because it is linked with task logs. I sure we should preserve task logs for audit purpose.

But I not sure the best solution. We can set null inventory_id, repository_id, etc of deleted templates.

Or we can use removed flag for environment and inventories.

Or we can set null template_id for tasks.

**Comment by MrChausson** [comment]
I feel like it's best to not keep too much unused things in the database, as it can end up taking a lot of storage. I'd not keep those logs for audit purposes, as I don't really see why someone would need it after having deleted the template.

But if we absolutely  must keep those logs, I'd suggest doing this:
**Moving those logs in another table let's say backup__logs and then remove the task template, so we won't have anything linked anymore.**

**Comment by fiftin** [comment]
It is very interesting how this implemented in AWX.

**Comment by fiftin** [comment]
Fixed, please try release https://github.com/ansible-semaphore/semaphore/releases/tag/v2.8.39
