### ISSUE TITLE
Boto module not found

### ISSUE THREAD

**Issue by tbynum** [ansible-semaphore/semaphore#73]
I am getting the following error when trying run a playbook that uses BOTO. I am using the docker setup.

TASK [ec2_remote_facts ] *************************
fatal: [<REDACTED>]: FAILED! => {"changed": false, "failed": true, "msg": "boto required for this module"}

As far as I can tell, BOTO is installed. Any ideas or has anyone seen anything similar?

Here is the task snipped from the yml file:

    - name: ec2_remote_facts 
      ec2_remote_facts:
        filters:
          "tag:ASV": <REDACTED>
      register: server_facts
    - debug: var=server_facts

Regards,

Tim Bynum

**Comment by matejkramny** [comment]
Tim, is it installed in the docker container or on the host?

**Comment by matejkramny** [comment]
Hi Tim, you will need to install boto.

To fix you will need to add it to the container/image running or wait for use v2 and have it on the root system.

**Comment by mmospanenko** [comment]
I can't understand how local package affects on semaphore runtime inside container. Could you explain please. I have running semaphoreui/semaphore:v2.8.74, how to solve issue with absent package inside? 

```
"msg": "Failed to import the required Python library (botocore or boto3) on a6e5e58d6472's Python /usr/bin/python3. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"
```
