### ISSUE TITLE
Problem with private ssh key formating

### ISSUE THREAD

**Issue by MrChausson** [ansible-semaphore/semaphore#732]
*Tested in semaphore v2.7.16*

When I don't put a newline at the end of the key. When I start a task I get a message saying key is not valid.

![image](https://user-images.githubusercontent.com/28267018/132876602-cac363c7-27b8-41a8-a91f-68b33e4acfa0.png)

Which make sense as any Linux files should end with a newline.

Is it possible to **automatically add a newline** if the user forgot ? As it might confuse new Linux users.

Thanks

**Comment by fiftin** [comment]
Hm, thank you, will be done.

**Comment by fiftin** [comment]
Fixed here: https://github.com/ansible-semaphore/semaphore/releases/tag/v2.7.20
