### ISSUE TITLE
Add CLI command for changing encryption key

### ISSUE THREAD

**Issue by fiftin** [ansible-semaphore/semaphore#734]
Currently we have configuration option `access_key_encryption` for encrypting secrets in database.

But if user changed this option old secrets become unavailable.

I think we should add CLI command to fix this problem.

After user changed `access_key_encryption` in config.json, next command should be executed:

```
semaphore access-key rekey --old-encryption <xxx>
```

or we should add option `old_access_key_encryption` and use command:

```
semaphore access-key rekey
```

**Comment by tboerger** [comment]
I'm closing this issue since it have been implemented with `semaphore vault rekey`, right?
