### ISSUE TITLE
Reverse Proxy Auth

### ISSUE THREAD

**Issue by danielband** [ansible-semaphore/semaphore#735]
Hi, would it be possible to authenticate via reverse proxy by using an HTTP Header? I would like to integrate semaphore with Pomerium. Gitea has a [feature](https://github.com/go-gitea/gitea/issues/8561#issuecomment-543180689) like this. I could try to implement it, if you could tell me how to build the app.

**Comment by fiftin** [comment]
Hi @danielband,

Please try this instruction: https://github.com/ansible-semaphore/semaphore/blob/develop/CONTRIBUTING.md

**Comment by fiftin** [comment]
Hi @danielband,

Any updates by feature? Or I can close this issue?

**Comment by danielband** [comment]
Hi, I didnt have the time to look into it. You may close the issue. If I find the time I will make a pull request.

**Comment by fiftin** [comment]
Ok, thank you @danielband
