### ISSUE TITLE
Update task fails when using PostgreSQL database

### ISSUE THREAD

**Issue by sabertail** [ansible-semaphore/semaphore#736]
I installed semaphore 2.7.11 and configured it to use a PostgreSQL 12 database.  When running a task it always fails with the error  "Failed to update task status".  There is also a panic level log with the message:

    pq: syntax error at or near \"end\"" error="Failed to update task status"

This appears to occur in the UpdateTask() function which runs the query

   update task set status=?, start=?, end=? where id=?

I think the syntax error is because 'end' is a reserved word in PostgreSQL.  I connected to the db with psql and tried to update both the 'start' and 'end' timestamp columns separately:

    semaphore=> update task set start=NOW() where id=1;
    UPDATE 1
    semaphore=> 
    semaphore=> update task set end=NOW() where id=1;
    ERROR:  syntax error at or near "end"
    LINE 1: update task set end=NOW() where id=1;

I can use double quotes to make the query work:

    semaphore=> update task set "end"=NOW() where id=1;
    UPDATE 1

But it might be better to rename the column instead:

    semaphore=> alter table task rename column "end" to end_time;
    ALTER TABLE
    semaphore=> update task set end_time=NOW() where id=1;
    UPDATE 1

**Comment by fiftin** [comment]
Thank you @sabertail !

Will rename column in next release.

**Comment by fiftin** [comment]
https://github.com/ansible-semaphore/semaphore/releases/tag/v2.7.20
