### ISSUE TITLE
New Template > Vault Password selection is not saving

### ISSUE THREAD

**Issue by ziptx** [ansible-semaphore/semaphore#738]
Apologies for not knowing git process and reporting an error.   I see this feature in the code of the v2.7.16 release.   The "New Template" in the GUI has the "Vault Password" dropdown.   The GUI is not currently saving the "vault\_pass\_id" into the "project\_\_template" table.   \[Fails on both a creating a new template and updating a template\].   If the correct "id" from the "access\_key" table is manually added to the "vault\_pass\_id" in the "project\_\_template" record, the vault password functionality works as expected when running the template/playbook.    The insert/update code is correct in templates.go on lines 101 & 139.  I would guess the "vault\_id" /template.VaultID variable is not getting passed into the module.

_Originally posted by @ziptx in https://github.com/ansible-semaphore/semaphore/pull/473#issuecomment-920923922_

**Comment by fiftin** [comment]
Thank you @ziptx ! Fix will be in v2.7.20.

**Comment by fiftin** [comment]
https://github.com/ansible-semaphore/semaphore/releases/tag/v2.7.20

**Comment by ziptx** [comment]
@fiftin  👍 confirmed working.   Fantastic piece of software, btw!
