### ISSUE TITLE
API?

### ISSUE THREAD

**Issue by realmcuser** [ansible-semaphore/semaphore#739]
t's probably just me being stupid, (i'm absolutely no coder), but since version v2.6.9 I have not been able to use the API with curl and  launch a task as per instructions here: https://github.com/ansible-semaphore/semaphore/wiki/API-&-automation

Just tested v2.7.17. "Log in" works, "create new  token" works, "get user tokens again" works, but i'm not just able to launch a task!(?). I know, it's me, but is there anyone out there who can get me in the right directions to solve this?

Other than that Semaphore is just fantastic :-)

Best regards 
Johan

**Comment by jdhayes** [comment]
I am new to semaphore and I am having a similar issue.
I am not able to launch a task using a token (or authenticate at all via token, for that matter).
I am able to login and create a session cookie. With this cookie I can also launch a task.
Have you tried launching a task with a session cookie?

**Comment by fiftin** [comment]
@realmcuser, @jdhayes, sorry for delay. Please provide example of query. Many users use API without issues.

**Comment by realmcuser** [comment]
@fiftin I have just (yesterday) reinstalled my test Semaphore server from scratch with version 2.8.0, and now it **works**!! After login with curl and generating new tokens (as per instructions, link first post) I now can launch a task again. Happiness!  in my opinion, this issue can be closed.

(But for real,  I didn't get this to work in version 2.7.17 at all. I wonder if it depends on my "one by one" version upgrade path of Semaphore.)  

@jdhayes, thanks for trying to help me! (Sorry for any bad English! Not my native language!)

Semaphore is just fantastic :) 

Best regards!
Johan

**Comment by fiftin** [comment]
@realmcuser Thank you :)
