### ISSUE TITLE
Encryption mysql password in config.json

### ISSUE THREAD

**Issue by BlogofraisFR** [ansible-semaphore/semaphore#746]
Hello,

It's possible to encrypt password mysql ?

Thank a lot

Blogofrais

**Comment by fiftin** [comment]
Hi @BlogofraisFR,

I have no idea how to do this. Do you have any idea?

**Comment by BlogofraisFR** [comment]
Hi @fiftin,

For example : https://gobyexample.com/base64-encoding

In semaphore setup to encrypt a lot of password

Just for little security

**Comment by fiftin** [comment]
base64 is not encryption.

MySQL password stored on file system. Encryption key should stored in other place to make it make sense.

I didn't find any solutions.

**Comment by BlogofraisFR** [comment]
it's always better than clear ;)

**Comment by fiftin** [comment]
May be some practices exist. Wait for advice from the community.
