### ISSUE TITLE
integrating with ldap - level=info msg="User does not exist or too many entries returned"

### ISSUE THREAD

**Issue by emollusion** [ansible-semaphore/semaphore#747]
Hi!

I am trying to integrate with ldap, before Semaphore is accessed, user is passed through an nginx auth module wich connects to the ldap server and is successfull.
But when trying to login using an ldap account I get this error:
level=info msg="User does not exist or too many entries returned"

So it searched but can not find.
Is there an upper limit, if so what?
If not, I probably have a mapping issue relatied to the username, possibly?

ldap config:
```
 	"ldap_binddn": "cn=ansible_ldap,ou=Service accounts,ou=Services,dc=my,dc=ldap,dc=server",
 	"ldap_bindpassword": "*****",
 	"ldap_server": "my.ldap.server:389",
 	"ldap_searchdn": "ou=Users,dc=my,dc=ldap,dc=server",
 	"ldap_searchfilter": "(uid=%s)",
 	"ldap_mappings": {
 		"dn": "dn",
 		"mail": "mail",
 		"uid": "uid",
 		"cn": "cn"
 	},
```

Is it possible to, as an alternative, to pass the credentials through to sempahore from nginx?
Since nginx authenticates the user, all it needs is a mapping of the username in semaphore.

Any thoughts heplful!

Thank you!

(also a sidenote, having a space in the ldap_binddn for semaphore setup didn't relly work, what was after the space ended up as a password in config and an error message instead:
```
WARN[0045] An input error occurred: expected newline 
```

**Comment by fiftin** [comment]
> User does not exist or too many entries returned

Bad error message... I will split it to "LDAP user does not exist" and "more than one LDAP user found".

**Comment by fiftin** [comment]
I never use LDAP, but I found following exmaple of LDAP configuration: https://github.com/ansible-semaphore/semaphore/issues/684#issuecomment-891924145

Search must return only 1 user. May you need more specific filter?

**Comment by emollusion** [comment]
Thank you for your quick response and help.

It was indeed a filter issue, and also a bit of mapping. Who was I to think that Active Directory followed ldap standards without quirks.

I found [#684 (comment)](https://github.com/ansible-semaphore/semaphore/issues/684#issuecomment-891924145) and [#404](https://github.com/ansible-semaphore/semaphore/issues/404) to be of help.

I ended up with this configuration:
```
    "ldap_binddn": "bindaccount@my.ldap.server",
 	"ldap_bindpassword": "****",
 	"ldap_server": "my.ldap.server:389",
 	"ldap_searchdn": "ou=Users,ou=Team,dc=my,dc=ldap,dc=server",
 	"ldap_searchfilter": "(&(sAMAccountName=%s)(|(memberOf=CN=it-role-semaphore-admin,OU=Roles,OU=Administration,DC=my,DC=ldap,DC=server)(memberOf=CN=it-role-semaphore,OU=Roles,OU=Administration,DC=my,DC=ldap,DC=server)))",
 	"ldap_mappings": {
 		"dn": "distinguishedName",
 		"mail": "userPrincipalName",
 		"uid": "sAMAccountName",
 		"cn": "cn"
 	}
```

Would you like me to open a specific ticket for the problem with using space in semapahore setup for ldap?
