### ISSUE TITLE
Template Api Documentation

### ISSUE THREAD

**Issue by ogomaemmanuel** [ansible-semaphore/semaphore#748]
Add documentation on how to launch a template and the required params to launch a template

**Comment by fiftin** [comment]
Hi @ogomaemmanuel 
Do you mean docs for API?

**Comment by ogomaemmanuel** [comment]
@fiftin No, I would love no know how to invoke a template via rest call. Currently I cannot find it anywhere. Also include the authentication methods allowed, eg Basic, Tokens etc

**Comment by fiftin** [comment]
You can find it in API docs: https://ansible-semaphore.github.io/semaphore/

![image](https://user-images.githubusercontent.com/914224/134769050-afacb099-ec0b-4dc6-94b7-c95171c3a07f.png)

**Comment by fiftin** [comment]
I will add link to README

**Comment by ogomaemmanuel** [comment]
Great
