### ISSUE TITLE
Use libgit2/git2go binding

### ISSUE THREAD

**Issue by matejkramny** [ansible-semaphore/semaphore#75]
Instead of spawning git, use the package binding

**Comment by twhiston** [comment]
2.5.0 and 2.6.0 tags for now as it would be great to get in to 2.5.0 but it's a stretch goal

**Comment by twhiston** [comment]
we could also consider a pure go solution like https://github.com/src-d/go-git

**Comment by twhiston** [comment]
removing 2.5.0 label as we will implement this in 2.6.0
Plan is probably to use go-git now to remove a system dependency and replace with a pure go solution

**Comment by tboerger** [comment]
This have been implemented with https://github.com/ansible-semaphore/semaphore/releases/tag/v2.8.89
