### ISSUE TITLE
Email_alerts: Config options for config.json files

### ISSUE THREAD

**Issue by kupe-dono** [ansible-semaphore/semaphore#750]
Edit: auto-signed = self-signed.. bad english

Hey guys!

I'd like to propose 2 little options for email alerts if they don't already exist.
I actually use (temporary) TLS self-signed certificate for smtp usage.
It would be great if we could have options to get the CA not verified.
For example, with php I usually use something like this:

```
$mail_smtp_secure = 'tls';
$mail_smtp_autotls = true;
$mail_smtp_options = array(
   'ssl' => array(
   'verify_peer' => false,
   'verify_peer_name' => false,
   'allow_self_signed' => true)
);
```

And the second one will be the possibility to add a "mail_from_name" option.

Have a geat day!

**Comment by kupe-dono** [comment]
Hi Guys! Any follow up for this case :) ?

**Comment by kupe-dono** [comment]
Hello! You can close the case, it seems that email works fine even if the smtp server uses a self-signed certificate.

**Comment by fiftin** [comment]
Thank you
