### ISSUE TITLE
ModuleNotFoundError: No module named 'pyvcloud'

### ISSUE THREAD

**Issue by genesis42** [ansible-semaphore/semaphore#752]
Hi!
I'm using:
- Semaphore v2.7.22
- ansible-module-vcloud-director
- Python 3.9.2

Playbook that deploys VM in vCloud run correctly from console.
But when I run it from Semaphore, I get error "ModuleNotFoundError: No module named 'pyvcloud'" :

`"module_stderr": "Traceback (most recent call last):\n File \"/root/.ansible/tmp/ansible-tmp-1633002485.3107715-36526-51228640537232/AnsiballZ_vcd_vapp_vm.py\", line 102, in <module>\n _ansiballz_main()\n File \"/root/.ansible/tmp/ansible-tmp-1633002485.3107715-36526-51228640537232/AnsiballZ_vcd_vapp_vm.py\", line 94, in _ansiballz_main\n invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n File \"/root/.ansible/tmp/ansible-tmp-1633002485.3107715-36526-51228640537232/AnsiballZ_vcd_vapp_vm.py\", line 40, in invoke_module\n runpy.run_module(mod_name='ansible.modules.vcd_vapp_vm', init_globals=None, run_name='__main__', alter_sys=True)\n File \"/usr/lib/python3.9/runpy.py\", line 210, in run_module\n return _run_module_code(code, init_globals, run_name, mod_spec)\n File \"/usr/lib/python3.9/runpy.py\", line 97, in _run_module_code\n _run_code(code, mod_globals, init_globals,\n File \"/usr/lib/python3.9/runpy.py\", line 87, in _run_code\n exec(code, run_globals)\n File \"/tmp/ansible_vcd_vapp_vm_payload_8zxfkco1/ansible_vcd_vapp_vm_payload.zip/ansible/modules/vcd_vapp_vm.py\", line 198, in <module>\nModuleNotFoundError: No module named 'pyvcloud'\n",`

vcd_vapp_vm.py line 198 is:
`from pyvcloud.vcd.vm import VM`

I have pyvcloud installed:
![image](https://user-images.githubusercontent.com/91604575/135448575-0f85e2bd-59d6-402b-8a3b-86f4740da7b1.png)
![image](https://user-images.githubusercontent.com/91604575/135454121-bed8cd5f-625d-416d-9b39-28250ab0e681.png)

Semaphore also wanted module python3-lxml and after installation error was solved.
But with pyvcloud i don't know what to do :( 

Tried solution from https://github.com/ansible-semaphore/semaphore/issues/714 - didn't help.

**Comment by fiftin** [comment]
How you installed the modules (with --user or not)?

**Comment by genesis42** [comment]
both:
pip3 install --user pyvcloud
pip3 install pyvcloud
pip install --user pyvcloud
pip install pyvcloud

**Comment by fiftin** [comment]
https://docs.ansible.com/ansible/latest/collections/community/vmware/vca_vapp_module.html

The below requirements are needed on the host that executes this module.

pyvcloud <= 18.2.2

**Comment by genesis42** [comment]
In the link you sent it says that the module is deprecated:
![image](https://user-images.githubusercontent.com/91604575/135479501-a1ef5d57-5d8f-4d28-a016-029c7a681f9f.png)
That's what i'm using - https://github.com/vmware/ansible-module-vcloud-director
In their requirements.txt no version of pyvcloud:
![image](https://user-images.githubusercontent.com/91604575/135482269-bd592fd1-f29c-4f59-9cca-b7b0223b1483.png)

In that case I still need downgrade pyvcloud?
