### ISSUE TITLE
Bug: Cron job still in DB after removing a task template

### ISSUE THREAD

**Issue by kupe-dono** [ansible-semaphore/semaphore#754]
Hi guys!

Something unusual that I found lastly.

To reproduce:
- Create a task template in a project 
- Configure cron in this task and save it
- Let the scheduled task run at least one time
- Delete the template task without disabling the cron
- The cron still try to run in the project page

After investigating, the cron entry is still present in project__schedule table.

**Comment by fiftin** [comment]
Hi @kupe-dono,

yes, you are right. It is known problem, I will start solving it soon. I think fix will be in v2.8.0.

**Comment by finzzz** [comment]
Hello, is there any follow up? I encounter the same issue.

**Comment by fiftin** [comment]
Fixed, please try release https://github.com/ansible-semaphore/semaphore/releases/tag/v2.8.39
