### ISSUE TITLE
cli --help for `user get` shows info for `user delete` 

### ISSUE THREAD

**Issue by fkuep** [ansible-semaphore/semaphore#757]
* look at the output for 
  * --login
  * --email

``` bash
~ $ semaphore version
v2.7.22
~ $ semaphore user get --help
Show user's data

Usage:
  semaphore user get [flags]

Flags:
      --email string   Email of the user you want to delete
  -h, --help           help for get
      --login string   Login of the user you want to delete

Global Flags:
      --config string   Configuration file path
~ $ 
```
I beleive the this concerns this code: 

https://github.com/ansible-semaphore/semaphore/blob/22e422e15a90344e74453f19787d979b487c96a9/cli/cmd/user_get.go#L10-L11

**Comment by fiftin** [comment]
@fkuep Thank you! Will be fixed in next release. It is only description issue :)

**Comment by fkuep** [comment]
Yes - just a typo, which makes me think that this would be an enough low hanging fruit for me to be a first contribution.

Would You mind me creating a pull request ?
I would:
*  change it like this:
``` diff
- userGetCmd.PersistentFlags().StringVar(&targetUserArgs.login, "login", "", "Login of the user you want to delete") 
- userGetCmd.PersistentFlags().StringVar(&targetUserArgs.email, "email", "", "Email of the user you want to delete") 
+ userGetCmd.PersistentFlags().StringVar(&targetUserArgs.login, "login", "", "Login of the user you want to show") 
+ userGetCmd.PersistentFlags().StringVar(&targetUserArgs.email, "email", "", "Email of the user you want to show") 
```
* run it through the steps in `contributing`  *for practise sake*
* make a pull request out it.
