### ISSUE TITLE
using restful-api and return {"message": "unauthirized"}

### ISSUE THREAD

**Issue by Ace-Tang** [ansible-semaphore/semaphore#76]
I use docker to quick start semaphore just as the README.md adviced, and log in the webui use initial login, but I cannot use restful api to connect semaphore, even cannot ping, like 

$ curl -X GET --header 'Accept: application/json' 'http://localhost:3000/api/ping'
{"message":"Unauthorized"}

curl always return {"message":"Unauthorized"} , am I something wrong? can someone help me

**Comment by Echobob** [comment]
Hi @Ace-Tang,

The running version (v1) does not have a public API, but you can authenticate by adding a cookie header and inspecting what the browser does

The [documentation](https://ansible-semaphore.github.io/semaphore/) is for the upcoming release of [Semaphore v2](https://github.com/ansible-semaphore/semaphore/tree/v2). You can checkout the v2 branch at https://github.com/ansible-semaphore/semaphore/tree/v2.

**Comment by Ace-Tang** [comment]
thank @Echobob , that helps
