### ISSUE TITLE
sudo does not work

### ISSUE THREAD

**Issue by laoshaw** [ansible-semaphore/semaphore#761]
the playbook works fine else where, and if no sudo permission is need it works fine with semaphore, however whenever I need sudo to modify the system, it always reports 'permission denied'

below is the way I'm debugging to pass the password via extra-vars, which can never work.

```
[
"-v",
"-e ansible_become_pass=mypassword"
]
```
semphore reports:

```
Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
```

failed to find related docs.

**Comment by fiftin** [comment]
You can use field `Become User Access Key` in Inventory settings.

Access Key must be `Login with password`

**Comment by laoshaw** [comment]
I create a ssh login key using the same ssh password for my host, then used it with inventory, it worked when no sudo power is needed. 

I also added -K to the playbook extra CLI args, it did not prompt a password on the semaphore terminal either.

**Comment by laoshaw** [comment]
my inventory file

```
[vm2004]
192.168.0.2

[vm2004:vars]
ansible_connection=ssh
ansible_user=user
ansible_ssh_password=useruser
ansible_port=22
ansible_become_password=useruser
```

**Comment by functionaldude** [comment]
i encountered the same issue, for me the solution was to make sure that there is no `Login` value saved, just the password
