### ISSUE TITLE
extra-vars via api ?

### ISSUE THREAD

**Issue by wdsff1** [ansible-semaphore/semaphore#767]
Hi,

is there an option to run a task template via API and extra vars about this.

curl -v -XPOST \-H 'Content-Type: application/json' \-H 'Accept: application/json' \-H 'Authorization: Bearer xxxxxxx' \-d '{"template_id": 2, "enviroment": ??}' \http://myip:3000/api/project/1/tasks

example: 
{
 "ansible_limit": "loadbalancer",
 "ipa_check": false
}

**Comment by fiftin** [comment]
Hi @wdsff1 ,

`"enviroment": "{\"ansible_limit\":\"loadbalancer\",\"ipa_check\":false}"`
