### ISSUE TITLE
Colorize output

### ISSUE THREAD

**Issue by mwxp06** [ansible-semaphore/semaphore#780]
Hallo,
is any possibility colorize output (like in terminal on OS)?
Green - success
Red - error ....

I tried to add to ansible.cfg:
```
[defaults]
force_color = True

[colors]
force_color = True
diff_add = bright purple
diff_remove = bright yellow
```

But without success :(
Can be possible to turn if on/off in GUI?

**Comment by bakito** [comment]
@fiftin If you added the env var `cmd.Env = append(cmd.Env, "ANSIBLE_FORCE_COLOR=True")` here, you would have colorized output.
https://github.com/ansible-semaphore/semaphore/blob/develop/lib/AnsiblePlaybook.go#L27

If you have the color coded output, you perhaps could render it in the web ui accordingly.

**Comment by bakito** [comment]
I created a PR with a possible implementation: https://github.com/ansible-semaphore/semaphore/pull/887

**Comment by andreas-marschke** [comment]
#887 was merged, can this be closed?
