### ISSUE TITLE
Provide extra variables at runtime?

### ISSUE THREAD

**Issue by 1nerdyguy** [ansible-semaphore/semaphore#786]
Is there a way to provide extra variables at task runtime? One of the features I love so much about AWX/Tower is the "Survey" tool allowing my end users to provide at run time info, to better serve their uses. This lets us have dynamic playbooks that do multiple tasks, and they can drive it.

**Comment by bpmb82** [comment]
I would love to have this!

**Comment by jdhayes** [comment]
I have been looking into something similar.
I actually needed to add the limit arg to ansible at runtime (https://github.com/ansible-semaphore/semaphore/pull/811)
Once my pull request is approved, I can add extra-vars as well.

**Comment by fiftin** [comment]
Will be implemented soon.

**Comment by fiftin** [comment]
Available in v2.8.25

https://github.com/ansible-semaphore/semaphore/releases/tag/v2.8.25

![image](https://user-images.githubusercontent.com/914224/150135648-99a4bc06-770e-4f2c-84bd-6e4a56ebf94e.png)

**Comment by steadfasterX** [comment]
my assumption of Survey Variables was that I can set them and so override a variable defined in "Environment". Is it intended that Environment has precedence over survey variables? Imho I would expect that survey vars should be able to overwrite them but thats not the case currently and I am not sure if thats a bug or wanted behavior?! @fiftin
