### ISSUE TITLE
MySQL Error w/ Docker Image, InnoDB Cluster

### ISSUE THREAD

**Issue by trschilke** [ansible-semaphore/semaphore#787]
Hi,

I am trying to use the Docker image to run a new installation of semaphore. As the application runs through the database migrations, the docker container terminates with "Error 3098: The table does not comply with the requirements by an external plugin."

It would appear that the task__output table (and possibly others) don't have a primary key assigned, causing the table creation to fail -- I am using an InnoDB cluster.  Would it be possible to get a primary key added to the table definitions in the migrations?  Adding the keys manually prior to container startup isn't an option since the migrations drop and recreate the table.

```
Is this correct? (yes/no) (default yes): 
Config output directory (default /home/semaphore): 
Running: mkdir -p /etc/semaphore.. 
Configuration written to /etc/semaphore/config.json.. 
 Pinging db.. 
Running DB Migrations.. 
Checking DB migrations 
Creating migrations table 
Executing migration v0.0.0 (at 2021-11-09 00:03:20.803589393 +0000 UTC m=+0.435080437)... 

 [1/268]
 [2/128]
 [3/302]
 [4/270]
 [5/291]
 [6/315]
 [7/239]
 [8/594]
 [9/199]
 [10/275]
 [11/239]
 [12/0] 
Executing migration v1.0.0 (at 2021-11-09 00:03:21.764750931 +0000 UTC m=+1.396243476)... 

 [1/59]
 [2/58]
 [3/82]
 [4/86]
 [5/59]
 [6/216]
 [7/62][0001] 
 ERR! Query: insert into `task__output` select * from `task__output_backup` 
 
 
[0001] Error 3098: The table does not comply with the requirements by an external plugin. 

```

Thank you!

**Comment by fiftin** [comment]
Hi @trschilke,

Table `task__output` has primary key.

Problem with copying data from one table to another. Did you try do this manually? May be columns must be specified explicitly...

```
insert into `task__output` (task_id, task, time, output) select task_id, task, time, output from `task__output_backup`
```

What version of MySQL do you use?

**Comment by trschilke** [comment]
Hi @fiftin ,

I am using MySQL  Ver 8.0.26 for Linux on x86_64 (MySQL Community Server - GPL).  There is no data to copy, as this is a fresh install.

When I look in the migration, I don't see a primary key assigned -- just a foreign key?

```
create table `task__output`
(
    task_id int not null,
    task varchar(255) not null,
    time datetime not null,
    output longtext not null,

    foreign key (`task_id`) references task(`id`) on delete cascade
);
```

My MySQL log also reports:
```
2021-11-09T00:03:22.255392Z 8314156 [ERROR] [MY-011542] [Repl] Plugin group_replication reported: 'Table task__output does not have any PRIMARY KEY. This is not compatible with Group Replication.'
```

**Comment by fiftin** [comment]
@trschilke ,

ah, yes, primary key (`id`) was added in migration 2.2.1, you got error in 1.0.0.

But it is bad idea to modify old migrations.

**Comment by fiftin** [comment]
Looks like I found solution. Migration 1.0.0 removes unique index from `task__output` for unknown reasons. I will remove this action.

**Comment by fiftin** [comment]
We have another table without primary key and unique index... And it can't be solved so easy.

**Comment by fiftin** [comment]
@trschilke ,

Please try this version: https://github.com/ansible-semaphore/semaphore/releases/tag/v2.8.20

**Comment by trschilke** [comment]
@fiftin 

I made it a lot farther without any errors this time, but still encountered one in migration v2.8.20.

```
2021-11-11T02:44:28.978005Z 10350176 [ERROR] [MY-011542] [Repl] Plugin group_replication reported: 'Table event_backup_7534878 does not have any PRIMARY KEY. This is not compatible with Group Replication.'
```
```

Executing migration v2.8.20 (at 2021-11-11 02:44:28.833179255 +0000 UTC m=+6.859094261)... 

 [1/52]
 [2/377]
 [3/162][0007] 
 ERR! Query: 
insert into `event`(project_id, object_id, description, created, user_id) select project_id, object_id, description, created, user_id from `event_backup_7534878` 
 
 
[0007] Error 3098: The table does not comply with the requirements by an external plugin. 
```

So close!

Thank you so much for your help with this!

**Comment by fiftin** [comment]
Table `event_backup_7534878` has unique index, according to docs it should be enough... It worked for `task__output`. 

Did you apply migrations for empty database?

**Comment by trschilke** [comment]
I started from a blank database again, yes.

When `task__output` is created in v2.2.1, it is created with a primary key.
```
create table task__output
(
    id integer primary key autoincrement,
    task_id int not null,
    task varchar(255) not null,
    time datetime not null,
    output longtext not null,

    foreign key (`task_id`) references task(`id`) on delete cascade
);
```

When the `event` table is created in v1.4.0, it's not created with a primary key at that time.  The table is then renamed to  `event_backup_7534878` in v2.8.20 (so the backup table is now the one without the primary key) and the `event` table is recreated in v2.8.20 with the primary key in place.

Would a possible solution be, in v2.8.20, to first check to see if the `event_backup_7534878` table has an `id` column and if not, alter the table to add the `id` column as primary key and autoincrement before the insert statement is processed?  I believe MySQL would fill in the column automatically at the time of its creation.

**Comment by fiftin** [comment]
Initially `task__output` created in migation v0.0.0 without primary key:

```
create table `task__output` (
	`task_id` int not null,
	`task` varchar(255) not null,
	`time` datetime not null,
	`output` longtext not null,

	unique (`task_id`, `time`),
	foreign key (`task_id`) references task(`id`) on delete cascade
);
```

in v2.2.1 data from old `task__output` copied to new table with primary kay. Similar like for `event`. But for unknown reason it doesn't work for `event`.

**Comment by fiftin** [comment]
Ok, I will try another way.

**Comment by trschilke** [comment]
@fiftin 
I'm just grasping at straws, but could it be that `task__output` defines the columns as `not null`, whereas the `event` table defines them as `DEFAULT null`?  The default values in the `event` table would break a primary key / would not be unique?

**Comment by fiftin** [comment]
@trschilke ,
Please try https://github.com/ansible-semaphore/semaphore/releases/tag/v2.8.22

**Comment by trschilke** [comment]
I made it through all the migrations and the application started!  I will start running through some use of the program and will let you know if I run into any other issues.

Thank you!!
