### ISSUE TITLE
Git repo custom ssh port

### ISSUE THREAD

**Issue by shizzgar** [ansible-semaphore/semaphore#788]
Hello, team!)
First of all, thank you for your awesome work!)

The second thing,  I have a problem with my private gitlab instance. I want to use ansible playbooks from closed repo with own key. But my gitlab instance has ssh at 2222 port. How can i ask semaphore to use this specific port?

The third thing, as I already sad, I have a private gitlab instance with ssl certificate. I have successfully rebuild docker image with my own cert, but is possible to add somewhere an option to add certs some more "friendly" way?)

Sorry for my English, 
И привет из России!)
I'm trying to do my best 😅

**Comment by fiftin** [comment]
Hi @shizzgar ,

Did you try `ssh://git@mydomain.com:2222/xxx` ?

**Comment by Enissay** [comment]
This fails for me, yet it works fine from the cli: 

```bash
GIT_SSH_COMMAND='ssh -i ~/.ssh/keys/private_key' git clone ssh://git@my-repo.com:222/enissay/ansible.git
```

My key is not psw protected, so I have no idea what is it complaining about!
![image](https://github.com/user-attachments/assets/f5983d03-d83c-4946-8445-7a8d529f2e3c)
