### ISSUE TITLE
Looking for help finishing setup

### ISSUE THREAD

**Issue by ghost** [ansible-semaphore/semaphore#793]
Hello!

Thank you for the time and effort put into this project. I am not a big git user so I'm not sure what to do on this error.

Task 2147483623 added to queue
Prepare task with template: ping
access key gitlab installed
Cloning repository git@gitlab.com:kozodev/ansible-repository.git
Cloning into 'repository_5_6'...
Warning: Permanently added 'gitlab.com,172.65.251.78' (ECDSA) to the list of known hosts.
fatal: Remote branch master not found in upstream origin
Failed updating repository: exit status 128

ssh -T ~~ works fine and I can git clone using the ssh address. I'm not sure how to deal with this remote branch error.

Thank you for your time!

**Comment by fiftin** [comment]
Hi @Zavoka ,

https://docs.ansible-semaphore.com/user-guide/faq#how-do-i-use-a-specific-branch-or-tag
