### ISSUE TITLE
running semaphore migration fails with the ERR! Query insert into event

### ISSUE THREAD

**Issue by coolhusker** [ansible-semaphore/semaphore#796]
Specifically with the following error:

Checking DB migrations
Executing migration v2.8.20 (at 2021-11-15 19:40:43.804159502 -0700 MST m=+0.180279465)...
 [3/162]WARN[0000] 
 ERR! Query: 
insert into "event"(project_id, object_id, description, created, user_id) select project_id, object_id, description, created, user_id from "event_backup_7534878"

I've tried to run 2.8.21 as well, but get the same error...any thoughts?

**Comment by coolhusker** [comment]
I was able to truncate the event table in the database and the migration ran without error.

For specifics:

Ansible-Semaphore: source 2.8.19 with the target of 2.8.20
Database: PostgreSQL
Operating System: Ubuntu 20.04.3 LTS
Package Install: (non docker/snap installation) via dpkg -i semaphore_2.8.20_linux_amd64.deb

D

**Comment by KenK73** [comment]
I just upgraded from v2.8.0 to v2.8.22 with a minor issue involving an event_backup_* table that existed for some reason. I was able to go into the msql server and drop the table. All seems good now.
