### ISSUE TITLE
Use ENV variables

### ISSUE THREAD

**Issue by benwyrosdick** [ansible-semaphore/semaphore#8]
The app is hard to deploy and host because you have to deal with a JSON config file that you don't want checked in but needs to be on the server. It would make sense for the config object to try to read from ENV and fall back to defaults. This would make it easier to deal with and deploy.

**Comment by matejkramny** [comment]
Fair point, and shouldn't be too hard..
It will probably be done at the same time as the UI upgrade (feature/ui-work branch).

**Comment by benwyrosdick** [comment]
:+1:

**Comment by bibby** [comment]
IMO, this is only partly done. The default values for the environment variables only come into play in the presence of the config json file you are trying to remove. Default env vars should be present in the Dockerfile as an indicator for users who wish to override them.

For example
```
ENV REDIS_HOST 127.0.0.1
ENV REDIS_PORT 6379
```

**Comment by matejkramny** [comment]
@bibby Check out https://github.com/ansible-semaphore/semaphore/blob/master/lib/config.js#L7

The program is runnable w/o configuration files.

**Comment by bibby** [comment]
The line you have linked tests for the _absence_ of environment variables. The defaults are then loaded from the configuration file. So in that way, no, it cannot run w/o config files.

Using `ENV` in the dockerfile with a default value means the required value is never absent, being either a user defined value or the predefined default.

**Comment by matejkramny** [comment]
1. Tries to load configuration file
2. If not present, tests for some required env variables. If they're not present, the program cannot run
3. Load default configuration
4. (line 17-21) Overrides configuration from environment
