### ISSUE TITLE
Repository pulls after git history re-writes fail

### ISSUE THREAD

**Issue by ilikejam** [ansible-semaphore/semaphore#800]
Hello!

The pull args in:
https://github.com/ansible-semaphore/semaphore/blob/5d89a766f49066034867fe694b5d89e15330ac64/api/tasks/runner.go#L530
don't handle instances where git history has been re-written since the last pull (e.g. with a force-pushed amend commit - something we do a lot on development branches).

Adding '--rebase' to the pull args, e.g.:
    cmd.Args = append(cmd.Args, "pull", "--rebase", "origin", repoTag)
should cover this case without any side-effects.

**Comment by fiftin** [comment]
Not sure. I think right way is delete repo and clone again. But how to detect this situation?

**Comment by ilikejam** [comment]
'git fetch; git merge-base --is-ancestor HEAD origin/\<branch\>' will tell if the local branch can be fastforwarded. If that succeeds - merge, if not - delete-and-clone.

It's not a show-stopper - we've added 'HOME=/tmp/semaphore git config --global pull.rebase true' in our container set up, and that's working for us.

**Comment by fiftin** [comment]
Fixed, please try https://github.com/ansible-semaphore/semaphore/releases/tag/v2.8.31
