### ISSUE TITLE
dashboard links 404

### ISSUE THREAD

**Issue by timelsass** [ansible-semaphore/semaphore#802]
In the Dashboard UI under the History section via the URL http://api.trial.test/semaphore/project/1/history I see links to the templates running the tasks:
![image](https://user-images.githubusercontent.com/11907254/145117959-35c4d5b5-855f-40a7-945d-e7eb4a4c2688.png)

The URL here points to:  http://api.trial.test/project/1/templates/7  and gives a 404.
Instead it should point to http://api.trial.test/semaphore/project/1/templates/7 

For reference, the links generated in other places like the Task Templates view are still correct:
![image](https://user-images.githubusercontent.com/11907254/145118698-90b9c383-c302-4324-9769-976a0fe1bb59.png)

using docker `image: ansiblesemaphore/semaphore:latest` and have nginx ingress with `path: /sempahore` if that helps in troubleshooting

**Comment by fiftin** [comment]
Please try prerelease 2.8.23
