### ISSUE TITLE
copy template dialog width incorrect

### ISSUE THREAD

**Issue by timelsass** [ansible-semaphore/semaphore#803]
When I select "New Template" from Task Templates and the button in the top right corner - I am presented with a dialog like this:
![image](https://user-images.githubusercontent.com/11907254/145120598-dacf564f-ed43-45b0-b8ec-c08ff2bc2659.png)

However when I click on a task template and then click on the copy task template icon in the top right - I am presented with a dialog like this:
![image](https://user-images.githubusercontent.com/11907254/145120868-c9ecc86c-d91d-4eb1-9604-493b9a282143.png)

I am unable to navigate to the build deploy tabs with the arrow to select those, and the UI is very small and hard to work with efficiently.  I believe this UI is meant to be similar in appearance to the first screenshot for "New Template", but just filled in with details copied over.

**Comment by fiftin** [comment]
Thank you @timelsass for fix.
