### ISSUE TITLE
Task template is not pulling the repo correctly

### ISSUE THREAD

**Issue by 0xbentang** [ansible-semaphore/semaphore#806]
# Issue

After adding a git repo with a branch, when I push a commit, and then execute the task template, it will return the error `error: Your local changes to the following files would be overwritten by merge:`

My questions are:

1. Why would there be local changes?
2. The git pull should at least clear all local changes before pulling

# Expected result

checkout all local changes, pull the latest changes from the branch

# Actual result

`error: Your local changes to the following files would be overwritten by merge`

# Error logs

```
 3:08:56 PM
* branch ansible -> FETCH_HEAD
3:08:56 PM
error: Your local changes to the following files would be overwritten by merge:
3:08:56 PM
Updating d7c7ee56..5e16149e
3:08:56 PM
Pipfile
3:08:56 PM
Pipfile.lock
3:08:56 PM
ansible/deploy.yml
3:08:56 PM
ansible/roles/deploy/tasks/main.yml
3:08:56 PM
Please commit your changes or stash them before you merge.
3:08:56 PM
Aborting
3:08:56 PM
Failed updating repository: exit status 1
```

# Versiosn
Semaphore 2.8.9 installed via snap

# Reproduce
Add a repo with #branch
Commit a change that will modify a playbook
Run a task template

**Comment by 0xbentang** [comment]
More information:

When I first create the template run it, it always fails with a bunch of 

`error: unable to create file XXX No such file or directory`

Ending with

`Failed updating repository: exit status 128`

the second run is fine

**Comment by fiftin** [comment]
Please try https://github.com/ansible-semaphore/semaphore/releases/tag/v2.8.31
