### ISSUE TITLE
 Listing playbook hosts failed

### ISSUE THREAD

**Issue by 10n01** [ansible-semaphore/semaphore#807]
Hello everyone,

I cannot find a solution to my problem.
why my system returns the result: Cloning into 'repository_2_1' ...
While the people's results have not '_1' at tail as 'repository_2'
This makes my task running Listing playbook hosts failed: chdir /tmp/semaphore/repository_2: no such file or directory

<img width="643" alt="image" src="https://user-images.githubusercontent.com/23330554/147398248-dae07008-13c3-45d4-91b8-3ef767080b32.png">
 
Thank you for your time!

**Comment by fiftin** [comment]
Sorry for delay, it is looks like a bug.

**Comment by fiftin** [comment]
Looks like it is old version of Semaphore

**Comment by l3system** [comment]
Im having the same issue when running the binary standalone or from systemd.
Running a docker container w. same repo/inventory works fine (Im using the same db).
Static inventory or from file gives same result.

I tried running the binary as root with same result, no luck.
Cheked out files are in place in /tmp/semaphore/, same goes for the inventory_xx files.
Im suspecting that the binary cant find ansible/ansible-playbook (in /usr/bin), but Im not sure how to debug.

Binary download: semaphore_2.8.49_linux_amd64.tar.gz
OS: Fedora 34 x86_64
Selinux is disabled

Server startup output:

```
MySQL semaphore@localhost:3306 semaphore
Tmp Path (projects home) /tmp/semaphore
Semaphore v2.8.49
Interface 
Port :3000
Server is running

```

Output of play:

```
7:32:36 PM Task 35 added to queue
7:32:41 PM Preparing: 35
7:32:41 PM Prepare TaskRunner with template: main
7:32:41 PM Warning: Permanently added 'git.l3system.se' (ED25519) to the list of known hosts.
7:32:42 PM Updating Repository git@git.l3system.se:leif/ansible.git
7:32:42 PM Warning: Permanently added 'git.l3system.se' (ED25519) to the list of known hosts.
7:32:42 PM From git.l3system.se:leif/ansible
7:32:42 PM * branch master -> FETCH_HEAD
7:32:42 PM Already up to date.
7:32:42 PM Get current commit hash
7:32:42 PM Get current commit message
7:32:42 PM No roles/requirements.yml file found. Skip galaxy install process.
7:32:43 PM Listing playbook hosts failed: exit status 4

```

Thanks a lot for your time!

**Comment by fiftin** [comment]
@l3system  it is looks like different issue...

**Comment by l3system** [comment]
> @l3system it is looks like different issue...

Let me know if you want me to open a new issue or do some more troublehooting.

**Comment by fiftin** [comment]
I need some more troublehooting, but I don't know how to get it :)

**Comment by fiftin** [comment]
Looks like some checks required before running ansible-playbook.

**Comment by l3system** [comment]
Actually its not a big deal.
The reason I was trying out the standalone binary was that I needed to include the python module "pywinrm" in the docker image, to be able to run ansible against windows hosts.

In case you would like to include it in the official Semaphore image this is the command (as per ansible docs):
`pip install "pywinrm>=0.3.0"`

Official docs Ansible Windows Remote Management:
https://docs.ansible.com/ansible/latest/user_guide/windows_winrm.html

I think this would be a welcomed addition.

**Comment by dewongway** [comment]
Hi, I believe I'm hitting the same error as well. Wondering if you have fixed it?  I'm using the semaphore_2.8.49_linux_amd64.rpm

My semaphore setup:
```
Postgres semaphore@localhost:5432 semaphore
Tmp Path (projects home) /etc/semaphore/playbook
Semaphore v2.8.49
Interface 
Port :3000
Server is running
```


```
This is the failed message from the task run:
1:58:44 PM
Task 9 added to queue
7:58:45 PM
Prepare TaskRunner with template: Test
7:58:46 PM
Warning: Permanently added 'xxxxxxxxxxxxx' (ECDSA) to the list of known hosts.
7:58:46 PM
Updating Repository xxxxxxxxxxx
7:58:46 PM
Warning: Permanently added 'xxxxxxxxxxxxx' (ECDSA) to the list of known hosts.
7:58:47 PM
From xxxxxxxxxxxxxx
7:58:47 PM
* branch main -> FETCH_HEAD
7:58:47 PM
Already up to date.
7:58:47 PM
Get current commit hash
7:58:47 PM
Get current commit message
7:58:47 PM
installing static inventory
7:58:47 PM
No roles/requirements.yml file found. Skip galaxy install process.
7:58:47 PM
Listing playbook hosts failed: exit status 4
```
