### ISSUE TITLE
Browser is not caching js/css files

### ISSUE THREAD

**Issue by roshansingh** [ansible-semaphore/semaphore#814]
Semaphore should respond with appropriate cache control headers for sempahore. 

I am using nginx to proxy sempahore. This is the response:

```
curl -I 'https://example.com/js/app.cbdb12f7.js'

HTTP/1.1 200 OK
Server: nginx/1.18.0 (Ubuntu)
Date: Sat, 15 Jan 2022 14:29:17 GMT
Content-Type: application/javascript
Connection: keep-alive

```

If it returns cache control headers then it would load faster on slower internet connections.

**Comment by macau23** [comment]
I am getting a 15 second load time on /css/app.X.css for some reason, so perhaps this would help.

**Comment by tboerger** [comment]
I have created a pull request which integrates done basic cache headers for static assets.
