### ISSUE TITLE
Git - Pulling without specifying how to reconcile divergent branches is discouraged

### ISSUE THREAD

**Issue by schadom** [ansible-semaphore/semaphore#815]
From the job logs:

    6:00:01 AM Updating repository ssh://git@git.xxx.com:22/xxx/ansible.git
    6:00:01 AM hint: Pulling without specifying how to reconcile divergent branches is
    6:00:01 AM hint: discouraged. You can squelch this message by running one of the following
    6:00:01 AM hint: commands sometime before your next pull:
    6:00:01 AM hint:
    6:00:01 AM hint: git config pull.rebase false # merge (the default strategy)
    6:00:01 AM hint: git config pull.rebase true # rebase
    6:00:01 AM hint: git config pull.ff only # fast-forward only
    6:00:01 AM hint:
    6:00:01 AM hint: You can replace "git config" with "git config --global" to set a default
    6:00:01 AM hint: preference for all repositories. You can also pass --rebase, --no-rebase,
    6:00:01 AM hint: or --ff-only on the command line to override the configured default per
    6:00:01 AM hint: invocation.
    6:00:02 AM Warning: Permanently added '[git.xxx.com]:22' (ECDSA) to the list of known hosts.
    6:00:03 AM From ssh://git.xxx.com:22/xxx/ansible
    6:00:03 AM * branch master -> FETCH_HEAD
    6:00:03 AM Already up to date.

Solution:

`docker exec -it semaphore git config --global pull.rebase false`

**Comment by fiftin** [comment]
Fixed
