### ISSUE TITLE
util.CheckUpdate causes semaphore to stop working in air-gaped systems

### ISSUE THREAD

**Issue by gaby** [ansible-semaphore/semaphore#818]
### Problem:
I was testing the semaphore latest docker image in an air-gap system. I think the current router.go code is doing a check against a new release on Github, the check will fail in non-connected instances and will not allow anyone to login.

Lucky for us, we tested this in a staging environment. 

### Cause:
I think the culprit is this line: https://github.com/ansible-semaphore/semaphore/blob/develop/api/router.go#L338

As seen in line https://github.com/ansible-semaphore/semaphore/blob/develop/api/router.go#L342 the function will return nothing if it can't get a results from the call to `github`.

### Possible solution:
* Add a cli-argument to disable checks for updates to `semaphore`
* Add proper error-handling to the check for updates, we are unable to login into semaphore with this error.
* Add an ENV variable to enable/disable checks for updates.

CC @fiftin

**Comment by zapalotta** [comment]
I just noticed the same behaviour when evaluating semaphore. Any workarond?

**Comment by gaby** [comment]
@zapalotta None so far, I had to rollback to `v2.8.21`

**Comment by fiftin** [comment]
@gaby, @zapalotta got it, will be fixed soon, thank you

**Comment by fiftin** [comment]
Fixed, please try latest pre-release.
