### ISSUE TITLE
Starts a job with arguments

### ISSUE THREAD

**Issue by mag1kan1n** [ansible-semaphore/semaphore#819]
Hi team,
We like your product, tell us how to run Job with arguments via API. To execute playbook with host limit? I didn't find it in the API documentation. Here is the expected example - `ansible-playbook configuration.yml -i inventory.ini --diff --limit=test.server`

**Comment by fiftin** [comment]
Hi @mag1kan1n ,

Currently you can do it only via Template settings, but we can discuss ability to this via Task.

Let's continue it in this thread: https://github.com/ansible-semaphore/semaphore/issues/832
