### ISSUE TITLE
Can't start job via API

### ISSUE THREAD

**Issue by webdev4u** [ansible-semaphore/semaphore#820]
Trying start new job via API.
Send data via POST request to  api/project/{project_id}/tasks

curl --location --request POST 'http://127.0.0.1:3000/api/project/3/tasks' \
--header 'Content-Type: application/json' --header 'Accept:application/json' \
--header 'Cookie: semaphore=MTY0MjI4ODQyM3x5Yml5b3FCeVM0cXVwdldZVjhRQ28wLTNHamF0bm1ubVJrR1JvR2NRUWpqNzc0V1FPN21fTDNiSDQ1MEhqTDZ2N1lyczBCVW5DV1U1bGlqeHpYaUdqTzA9fM4i4UwRbHTSi2KGYpnkGcMqYMBI8O3zZ7b7UOxr7CyR' \
--data-raw '{
    "template_id": 15,
    "debug": true,
    "dry_run": false,
    "playbook": "swte/create_file.yml",
    "environment": "barium"
}
'

Receive response with new task id. 
{"id":98,"template_id":15,"project_id":3,"status":"waiting","debug":true,"dry_run":false,"playbook":"swte/create_file.yml","environment":"barium","user_id":1,"created":"2022-01-16T12:30:56.854232734+03:00","start":null,"end":null,"message":"","commit_hash":null,"commit_message":"","build_task_id":null,"version":null}

Semaphore start task and fail with error:

12:30:56 PM Task 98 added to queue
12:31:00 PM Preparing: 98
12:31:00 PM Error: invalid character 'b' looking for beginning of value

Semaphore version:  2.8.21
Operating System: Debian GNU/Linux 10 (buster)
Kernel: Linux 4.19.0-18-amd64
Architecture: x86-64

**Comment by rmfirth** [comment]
Looks like your `environment` value is not a valid JSON converted to a string. The task is expecting `environment` to be a JSON object that has been serialized into a string, and you have provided the value `barium`, which is not a serialized JSON object (hence the message `invalid character 'b' looking for beginning of value`). Perhaps this is an indication that the API docs could be a little more clear, but if you delete the `environment` value on the task, or if you provide a valid serialized JSON object of key-value pairs to be passed to the playbook, your task should run as expected

**Comment by webdev4u** [comment]
Yes, @rmfirth, you are right. This solved my problem. I thought that in the `environment` parameter it is necessary to specify the name of the environment saved in the GUI. Thank you for your help.
