### ISSUE TITLE
Gitlab located behind the proxy- Unable to clone repo

### ISSUE THREAD

**Issue by patilrs** [ansible-semaphore/semaphore#821]
Hi guys ,
I need to use the http_proxy,https_proxy to clone the repo. Unable to run the template task .
Please let me know how to use/configure proxy for https repo clone

**Comment by fiftin** [comment]
Hi, need more details. Did you try do this via `/etc/environment`?

**Comment by patilrs** [comment]
Hi guys,

I tried adding proxy in /etc/environment. Still there is issue in cloning
the repo using https

Thanks and regards
Rudragouda patil
