### ISSUE TITLE
Extra CLI Arguments for task template missing in v2.8.25

### ISSUE THREAD

**Issue by kennethso168** [ansible-semaphore/semaphore#822]
In latest docker image with semaphore v2.8.25, I can't see the "Enter extra CLI arguments" box when creating a task template

![image](https://user-images.githubusercontent.com/5262487/150634309-b59671e5-9120-4e61-a797-d3f8bda3fd18.png)

There is a "Enter extra CLI arguments" box on the screenshot in user guide. I can also see this box when I try with v2.8.21

![image](https://user-images.githubusercontent.com/5262487/150634351-5008076b-3b77-4803-9701-51c9d2764bbd.png)

**Comment by fiftin** [comment]
Will fix asap.

**Comment by fiftin** [comment]
Fixed in https://github.com/ansible-semaphore/semaphore/releases/tag/v2.8.34

Available in Advanced options:

<img width="300px" src="https://user-images.githubusercontent.com/914224/151122210-a8c9dedb-da73-4067-885c-f9c71cd7978f.png" />
