### ISSUE TITLE
Docker: please keep the "latest" tag for stable releases, or at least have another tag pointing for latest stable releases

### ISSUE THREAD

**Issue by kennethso168** [ansible-semaphore/semaphore#823]
The release page on GitHub shows v2.8.21 as the latest release.

However, when I pulled the docker image with latest tag, the image with v2.8.25 was pulled, which was unexpected to me.

In my opinion, the latest tag should point to latest stable release. Better to use some other tags (e.g. "dev") for pre-releases (c.f. [the tags used by home assistant for example](https://hub.docker.com/r/homeassistant/home-assistant/tags))

If you would like to keep the way as is, maybe you could add another tag pointing to stable releases (e.g. "stable"), so that I can track the latest stable releases using diun. Thank you.

**Comment by fiftin** [comment]
Creating of docker image is automated process, but approving releases in GitHub is manual process. I can't create different tags for release and pre-release. But I'll think how to do this.

We already have dev tag for builds without version.

**Comment by fiftin** [comment]
Done
