### ISSUE TITLE
bug:  environment variable configuration does not take effect when rerunning

### ISSUE THREAD

**Issue by OPSTime** [ansible-semaphore/semaphore#824]
**run task**
$ curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -H 'Authorization: Bearer XXXXXXXXXXXXXXXXXXXXX' -d '{
  "template_id": 1, 
  "environment": "{\"env_a\":\"tttttt\"}"
 }' 'http://172.168.1.11:3000/api/project/1/tasks'
{"id":62,"template_id":1,"project_id":1,"status":"waiting","debug":false,"dry_run":false,"playbook":"","environment":"{\"env_a\":\"tttttt\"}","user_id":1,"created":"2022-01-22T18:26:55.548924193Z","start":null,"end":null,"message":"","commit_hash":null,"commit_message":"","build_task_id":null,"version":null}

**but rerun task 62, environment variable configuration does not take effect:**
mysql> select id,template_id,status,playbook,environment,debug,created,start,end from task;
......
| 62 |           1 | success |                         | {"env_a":"tttttt"}                       |     0 | 2022-01-22 18:26:56 | 2022-01-22 18:27:04 | 2022-01-22 18:27:24 |
| 63 |           1 | success |                         | {}                                       |     0 | 2022-01-22 18:27:44 | 2022-01-22 18:27:54 | 2022-01-22 18:28:14 |
+----+-------------+---------+-------------------------+------------------------------------------+-------+---------------------+---------------------+---------------------+

**Comment by fiftin** [comment]
@OPSTime Thank you, will fix soon.

**Comment by fiftin** [comment]
Fixed in https://github.com/ansible-semaphore/semaphore/releases/tag/v2.8.30

**Comment by OPSTime** [comment]
Thank you.
