### ISSUE TITLE
Request: Docker release for ARM arch

### ISSUE THREAD

**Issue by mvdkleijn** [ansible-semaphore/semaphore#826]
Please provide an arm architecture release for the Docker container. Since this is a Golang app, that should be fairly easy? :crossed_fingers:  :smile:

**Comment by fiftin** [comment]
Yes, it is easy, but I don't know how to do this using Circle CI 😀

**Comment by mvdkleijn** [comment]
Then I'll see if I can make some time to figure that out for you. :smile:

**Comment by thunderstorm99** [comment]
@fiftin @mvdkleijn has there been any progress in the meantime? Thanks for your great app!

**Comment by mvdkleijn** [comment]
My apologies. I took a look at the time and the docs aren't very clear about how to do this in CircleCI. I also seem to remember that arm support was sketchy. After that I kinda got sidetracked by life and forgot about this. :-) No excuse, I know but still.

**Comment by fiftin** [comment]
We moved to GitHub Actions.

**Comment by nmcc1212** [comment]
has moving to github actions changed whether you can do it?

**Comment by fiftin** [comment]
Available in v2.8.73 (https://hub.docker.com/r/semaphoreui/semaphore).

![image](https://user-images.githubusercontent.com/914224/198143610-299cb3d5-ce57-4bcd-9ced-64eeb75cd8e9.png)

**Comment by fiftin** [comment]
Duplicate https://github.com/ansible-semaphore/semaphore/issues/1064
