### ISSUE TITLE
How to run tasks in playbook according to the specified tag?

### ISSUE THREAD

**Issue by OPSTime** [ansible-semaphore/semaphore#832]
How to run tasks in playbook according to the specified tag?

The command line can specify tags through -- tags.

**$ cat  roles/get_host_info/tasks/main.yml**                
```
- name: get userid
  shell: id
  register: userid
  tags:
    - userid

- name: print userid
  debug: 
    msg: "userid: {{ userid.stdout }}"
  tags:
    - userid

- name: get cpu core num
  shell: lscpu|awk '/^CPU\(s\):/{print $2}'
  register: cpu_core_num
  tags:
    - cpu_core_num

- name: print cpu core num
  debug:
    msg: "CPU num: {{ cpu_core_num.stdout }}"
  tags:
    - cpu_core_num

- name: get memory size
  shell: free -g|awk '/Mem/{print $2}'
  register: memory_size
  tags:
    - memory_size

- name: print memory size
  debug:
    msg: "memory: {{ memory_size.stdout }}G"
  tags:
    - memory_size
```

**Comment by fiftin** [comment]
Currently you can specify it in Template settings only.

<img width="300px" src="https://user-images.githubusercontent.com/914224/151141429-27256eca-c7b3-44b1-8193-48df4a9a68d7.png" />
<img width="300px" src="https://user-images.githubusercontent.com/914224/151141477-b00135d3-3344-4ee0-bfde-66f47fe87af5.png" />

**Comment by fiftin** [comment]
Available in v2.8.35 https://github.com/ansible-semaphore/semaphore/releases/tag/v2.8.35

<img src="https://user-images.githubusercontent.com/914224/151388520-9b885364-97d1-49bb-a3e1-c1d1d6cecfa0.gif" />

**Comment by OPSTime** [comment]
The function was tested and found to be ineffective.
version: 2.8.36

![run_playbook](https://user-images.githubusercontent.com/5848331/151567842-04dfc9b3-ccbe-4d4e-ba4c-950e428338a3.png)

**Comment by fiftin** [comment]
@OPSTime, please try this (https://github.com/ansible-semaphore/semaphore/discussions/848):

<img width=500 src="https://user-images.githubusercontent.com/914224/152433414-c2424df2-230f-411e-9d42-fa5d0ddf1c88.gif">

**Comment by fiftin** [comment]
Checked, it works. UI fix will be in next release.
