### ISSUE TITLE
Not able to clone github repo using PAT

### ISSUE THREAD

**Issue by mambon2** [ansible-semaphore/semaphore#833]
How can I setup a github repository with personal access token?
I've tried every combination offered by the semaphore UI

**Comment by fiftin** [comment]
It is impossible now. Will be implemented soon.

**Comment by fiftin** [comment]
Implemented in v2.8.35 https://github.com/ansible-semaphore/semaphore/releases/tag/v2.8.35

**Comment by pavkamlc** [comment]
I cannot sync with PAT:

`11:28:03 AM
Task 4 added to queue
11:28:06 AM
Prepare TaskRunner with template: updates
11:28:06 AM
Updating Repository https://github.com/pavkamlc/ansible.git
11:28:06 AM
warning: Pulling without specifying how to reconcile divergent branches is
11:28:06 AM
discouraged. You can squelch this message by running one of the following
11:28:06 AM
commands sometime before your next pull:
11:28:06 AM
11:28:06 AM
git config pull.rebase false # merge (the default strategy)
11:28:06 AM
git config pull.rebase true # rebase
11:28:06 AM
git config pull.ff only # fast-forward only
11:28:06 AM
11:28:06 AM
You can replace "git config" with "git config --global" to set a default
11:28:06 AM
preference for all repositories. You can also pass --rebase, --no-rebase,
11:28:06 AM
or --ff-only on the command line to override the configured default per
11:28:06 AM
invocation.
11:28:06 AM
11:28:06 AM
From https://github.com/pavkamlc/ansible
11:28:06 AM
* branch main -> FETCH_HEAD
11:28:06 AM
Already up to date.
11:28:06 AM
Get current commit hash
11:28:06 AM
Get current commit message
11:28:06 AM
Failed to install inventory: access key type not supported for ansible user`

**Comment by fiftin** [comment]
It is not looks like PAT issue.

**Comment by fiftin** [comment]
It is not looks like PAT issue.

**Comment by fiftin** [comment]
It is not looks like PAT issue.
