### ISSUE TITLE
Disable cronjobs for redudent setup

### ISSUE THREAD

**Issue by TheNerdyHamster** [ansible-semaphore/semaphore#837]
Hi,

I am currently working on setting up a secondary instance of semaphore (a copy of main instance, that updates once a day) which is just a backup in case of the main instance goes down.

This is resulting in that all cronjobs from the main instance is also running on the secondary instace, which might result in changed playbooks being runned etc.

Is there any recommended solution for disabling cronjobs currently in semaphore?

**Comment by fiftin** [comment]
Why not to stop semaphore on the second instance? I don't know how to do this another way.
