### ISSUE TITLE
User Access Permissions

### ISSUE THREAD

**Issue by asmartin** [ansible-semaphore/semaphore#84]
Semaphore looks like a very promising project! One feature that would make this very useful to me would  be the ability to restrict certain users to being able to only run certain playbooks or roles. The use case would be that certain users would only be able to run ansible on certain hosts and with certain playbooks. For examples, developers could only spin up their own development machines but not run other playbooks. Is this a feature that Semaphore could support?

**Comment by matejkramny** [comment]
Certainly is, with v2 (beta at the moment) we have the following architecture:

```
- Project 
  -> user (admin/non-admin)
  -> playbooks
  -> ...
```

**Comment by asmartin** [comment]
Excellent! Can you elaborate a little bit more on how it works in v2? Can I create links between certain users and certain playbooks? Can I also restrict users and hosts, or is that done solely through where their SSH keys are present?

**Comment by matejkramny** [comment]
Right, basically everything is relative to the project.. Users are global and so are projects and access keys (ssh, aws, google cloud, ...).

Project then has templates, tasks, access keys (only for that project) and links to users.

Linking a user to the project gives them permission to view and do everything inside it. Administrator privileges within the project should restrict them from adding anyone else / removing anyone from the project.

I'd like to have more permissions, but I don't see a way of doing that without too much complexity.

One way perhaps, which is something we haven't done yet, is ask for passwords to playbooks/tasks.

**Comment by asmartin** [comment]
Excellent, that sounds great! I see that you can associated inventories with playbooks - is it possible to associate inventories with projects as well (e.g. Dev Team A would have their own inventory with their own vault files and other inventory files and Dev Team B would have a separate set)?

**Comment by matejkramny** [comment]
I could explain this at length here, but I think you'll find more in the actual work :)

Beta 2: https://github.com/ansible-semaphore/semaphore/releases/tag/v2.0-beta-2

Inventories are associated with projects & linked to task templates. One thing to note is that one project = one team of people. Teams can be explored further though, it does seem like it could have some use.

**Comment by asmartin** [comment]
I have installed v2.0-beta-2, worked around #83, and configured my ansible playbooks git repository and keys. Inside the root of my repository is `test.yml` which is the playbook I want to try to run. It contains the following:

````
---
- hosts: '{{ hostlist }}'
  remote_user: root
  roles:
   - testrole
````

I then configured a Task Template with the following Extra CLI arguments:

````
["-e", "hostlist='myhost'"]
````

However when running it, I get an error that `test.yml` does not exist:

````
15:08:09: Running playbook failed: exit status 1
15:08:09: ERROR: the playbook: test.yml could not be found
15:08:09: access key test installed
15:08:09: installing static inventory
15:08:09: Already up-to-date.
15:08:09:  * branch            master     -> FETCH_HEAD
15:08:09: From ssh://example.com/repo.git
15:08:08: Updating repository
15:08:08: access key test installed
15:08:08: Started: 7
````

Running `ansible-playbook -i hosts -e "hostlist=myhost" test.yml` on the command line works.

What am I missing?

**Comment by matejkramny** [comment]
What is your temp path and does the repository there exist?

Maybe the changes haven't been pushed, the logs indicate no changes have been made to the repository.

NB: I am guessing you have two repositories, one which ansible downloaded from your central repository and one which you edited.

**Comment by asmartin** [comment]
The path I configured during setup was `/mnt/tmp` and I saw an error in the console that `/mnt/tmp/repository_3` does not exist, so I created `/mnt/tmp/repository_3` myself. I have not seen anything created inside this directory, I would expect semaphore to git clone the repo into this directory, correct?

My understanding is that `Playbook Name` field on the Task Template must be a file that exists already on the git repository specified in `Git URL` on the Playbook Repositories screen. If this is correct, I'm not sure why it isn't working because `test.yml` exists in the repository at the specified git URL.

**Comment by matejkramny** [comment]
I see.

The old version didn't create the tmp path (latest does). Semaphore does clone the repo, and after that does `git pull origin master` inside the folder.

You understand it correctly, I would say the reason it doesn't work is because it looks into the wrong folder.

Would you mind downloading the latest release, pointing it to eg `/mnt/semaphore` or an empty directory & re-running the task?

The server logs may also reveal some clues, might you post it here? (just around the `POST /tasks` hit)

**Comment by asmartin** [comment]
You want me to just pull from the head of the v2 branch?

**Comment by matejkramny** [comment]
@asmartin v2 is now mainstream. You should download a release instead

**Comment by asmartin** [comment]
I tried out v2 and it is working, thanks!
