### ISSUE TITLE
Telegram chat id could be VARCHAR(14)

### ISSUE THREAD

**Issue by ball6847** [ansible-semaphore/semaphore#844]
I tried setting my project telegram chat id to receive notification but semaphore didn't allow me to do that, due to column definition  of `project.alert_chat` which is current defined as `VARCHAR(10)` but my channel id is 14 characters long (`-1009999999999`) and cannot be fit in 10 chars.

After I changed it to `VARCHAR(14)`,  the notification worked fine.

If I'm doing something wrong, please let me know.

Thank you.

**Comment by fiftin** [comment]
Fixed in 2.8.41 https://github.com/ansible-semaphore/semaphore/releases/tag/v2.8.41
