### ISSUE TITLE
Private key passphrase

### ISSUE THREAD

**Issue by irongomme** [ansible-semaphore/semaphore#85]
How to manage private key with passphrase under the app ?

For tests i've regenerated a passphraseless private key to make it works ...

**Comment by matejkramny** [comment]
Keys without passphrase must be submitted.

You can use protected keys for inventory logins, and supply the password in the task arguments.

There's a couple of options to have passphrases & better security in general:

- Key is unencrypted, but stored as an encrypted value in the database. UI can ask for passphrase
- Key is encrypted, but passphrase must be supplied (this may not be possible, as the commands are not run interactively)
- Key is supplied encrypted, but decrypted once it is used. A passphrase is supplied before running and the unencrypted key is written to disk

**Comment by asmartin** [comment]
I would vote for prompting the user when performing the run to enter the passphrase to decrypt. You could then use `ssh-agent` to keep the key unencrypted and available for use for a specific period of time (e.g. 30 minutes)

**Comment by twhiston** [comment]
> I would vote for prompting the user when performing the run to enter the passphrase to decrypt.

I am generally against this approach as it makes scheduled jobs a lot harder to maintain. Is there a way that the passphrase can be stored in a secure way and just decrypted when needed by Semaphore itself?

**Comment by GeroL** [comment]
So what is the status here?

**Comment by kingii98** [comment]
> You can use protected keys for inventory logins, and supply the password in the task arguments.

How exactly do I supply the password?

**Comment by densanki** [comment]
From a security point of view, it is unfavorable if a tool is not familiar with secure key storage mechanisms.
