### ISSUE TITLE
mariadb 10.5.13 variable error

### ISSUE THREAD

**Issue by adriansev** [ansible-semaphore/semaphore#853]
Hi! After creating a new project on a newly started ansible-semaphore v2.8.40
and after checking alerts checkbox i get this:
`ERRO[0004] sql: Scan error on column index 4, name "alert_chat": converting NULL to string is unsupported`
and i'm no longer able to use the installation.

**Comment by fiftin** [comment]
Fixed in 2.8.41 https://github.com/ansible-semaphore/semaphore/releases/tag/v2.8.41
