### ISSUE TITLE
Migration Error From 2.8.33 to 2.8.45

### ISSUE THREAD

**Issue by nlvw** [ansible-semaphore/semaphore#857]
Hi, when testing the new pre-release/release I hit a migration error.  This is using a mariadb database (same host) on RHEL 8.

```
(python-venv) [semaphore@ansible-p1 ~]$ ./semaphore service --config=/opt/semaphore/config.json
Executing migration v2.8.36 (at 2022-02-05 17:32:12.462427154 -0700 MST m=+0.138713807)...
 [4/0]]
Executing migration v2.8.38 (at 2022-02-05 17:32:12.485832953 -0700 MST m=+0.162119673)...
 [9/0]]]
Executing migration v2.8.39 (at 2022-02-05 17:32:12.512218089 -0700 MST m=+0.188504797)...
 [8/0]]]
Executing migration v2.8.40 (at 2022-02-05 17:32:12.569799062 -0700 MST m=+0.246085772)...
 [7/0]]
Executing migration v2.8.42 (at 2022-02-05 17:32:12.634695208 -0700 MST m=+0.310981918)...
 [1/99]WARN[0000]
 ERR! Query: alter table `task` drop foreign key `task_ibfk_3` /* postgres:`task_build_task_id_fkey` mysql:`` */


FATA[0000] Error 1091: Can't DROP FOREIGN KEY `task_ibfk_3`; check that it exists
```

**Comment by fiftin** [comment]
Fixed in [v2.8.46](https://github.com/ansible-semaphore/semaphore/releases/tag/v2.8.46).

**Comment by nlvw** [comment]
Awesome I need to deploy a new dev VM to test the upgrade and I'll verify the fix (could take a few days).

**Comment by venkatasankhya** [comment]
when we try to upgrade from v2.7.22 to v2.8.49 . we see following errors and semaphore getting failed. right now, it working for v2.8.21 and all above versions getting same error. please help me on this.

Error: unknown command "/etc/semaphore/config.json" for "semaphore"
semaphore.service: main process exited, code=exited, status=1/FAILURE
Unit semaphore.service entered failed state.
semaphore.service failed.

**Comment by fiftin** [comment]
Yes, you should change you service's `ExecStart` field to:
```
ExecStart=/usr/bin/semaphore server --config /etc/semaphore/config.json
```

**Comment by venkatasankhya** [comment]
Thank you for your help. it worked great after changing ExecStart and upgraded to v2.8.49.

**Comment by nlvw** [comment]
@fiftin this has fixed our issue.  Thanks for the quick response!!
