### ISSUE TITLE
Documentation of non-docker installation

### ISSUE THREAD

**Issue by MrMEEE** [ansible-semaphore/semaphore#86]
Hi

I would like some information on howto install semaphore without using docker/vagrant...

**Comment by matejkramny** [comment]
Install redis & mysql, then download a binary for your system here:

https://github.com/ansible-semaphore/semaphore/releases

**Comment by MrMEEE** [comment]
Great.. maybe that should be added to the README?

**Comment by MrMEEE** [comment]
After installing and launching.. I get:

"Can't find user sql: no rows in result set" when trying to login???

**Comment by MrMEEE** [comment]
MariaDB [(none)]> use sematest;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
MariaDB [sematest]> show tables;
+----------------------------+
| Tables_in_sematest         |
+----------------------------+
| access_key                 |
| event                      |
| migrations                 |
| project                    |
| project__environment       |
| project__inventory         |
| project__repository        |
| project__template          |
| project__template_schedule |
| project__user              |
| task                       |
| task__output               |
| user                       |
| user__token                |
+----------------------------+
14 rows in set (0.00 sec)

MariaDB [sematest]> select * from user;
+----+---------------------+----------+--------+-----------------+--------------------------------------------------------------+
| id | created             | username | name   | email           | password                                                     |
+----+---------------------+----------+--------+-----------------+--------------------------------------------------------------+
|  1 | 2016-05-11 13:17:32 | mj       | Martin | mj@casalogic.dk | $2a$11$QvTMSFTGzsrp.skGttji5Oi7j4Yo9UNWtLfWU3OX3TnonVjoQrhKS |
+----+---------------------+----------+--------+-----------------+--------------------------------------------------------------+
1 row in set (0.00 sec)

MariaDB [sematest]>

**Comment by MrMEEE** [comment]
I have tried to login with both mj and mj@casalogic.dk as username...

**Comment by MrMEEE** [comment]
Never mind... I reinstalled and it works

**Comment by matejkramny** [comment]
Its not in readme because its a beta version, unreleased yet, and `master` is currently an old branch
