### ISSUE TITLE
Upgrade Semaphore

### ISSUE THREAD

**Issue by jsinic** [ansible-semaphore/semaphore#868]
Hi

I have troubles with upgrading Semaphore from version 2.5.1 to latest stable 2.8.53. Update over GUI can not process, I got prompt : Upgrade seems to be taking a long time. Check server logs!

I do not know where to find these logs. Or what could be wrong, why update failed?

Thanks

**Comment by Vitexus** [comment]
there is few differencies:

1. make database migrate fist: ```semaphore migrate --config /etc/semaphore/config.json```
2. application is now started by: ```semaphore server --config /etc/semaphore/config.json``` - so update your /etc/systemd/system/semaphore.service to:


```systemd
[Unit]
Description=Modern UI for Ansible

[Service]
User=ansible
WorkingDirectory=/var/ansible/semaphore
ExecStart=semaphore server --config /etc/semaphore/config.json
Restart=always

[Install]
WantedBy=multi-user.target

```

**Comment by jsinic** [comment]
Ok in which directory I have to run these commands. I had attached CLI logs with errors.

[Semaphore_commands.txt](https://github.com/ansible-semaphore/semaphore/files/8112199/Semaphore_commands.txt)

**Comment by fiftin** [comment]
@jsinic 
```
listen tcp :3000: bind: address already in use
```
Someone else uses port 3000. You should stop it or change Semaphore port.

**Comment by jsinic** [comment]
I have changed the port but update still failes, so I made new install with snap. I can access web GUI login page, I follow instalation guide, but I am unable to add new user after install

[root@ansible ~]# sudo semaphore user add --admin --name ******* --login ansible --email ********** --password  *********
sudo: semaphore: command not found

Do you have any advice how to solve these?

My sistem is:   Operating System: Rocky Linux 8.5 (Green Obsidian

**Comment by fiftin** [comment]
Problem solved?

**Comment by Vitexus** [comment]
@fiftin in my case yes :)
