### ISSUE TITLE
 fatal: bad numeric config value '0

### ISSUE THREAD

**Issue by vknetlab** [ansible-semaphore/semaphore#871]
Used docker to install semaphore latest version and i got this error "fatal: bad numeric config value '0" 
Not sure if it bug or some config issue. Thanks
```
8:01:16 PM Cloning repository https://github.com/*******/test.git
8:01:16 PM Cloning into 'repository_1_1'...
8:01:16 PM fatal: bad numeric config value '0
8:01:16 PM ' for 'GIT_TERMINAL_PROMPT': invalid unit
8:01:16 PM Failed updating repository: exit status 128
```

**Comment by ckieser** [comment]
I had the exact same issue using a https://gitlab repository. 
I think there's an issue with https:// and username/password/token. 

Using ssh keys and git URL instead of https helped me to get it working.

**Comment by shawnweeks** [comment]
Also encountering this issue and my GitLab Repo is HTTPS only so I don't have the option to use SSH.

**Comment by Ex0Cate** [comment]
use a personal access Token instead of ssh key. This helped me out!

**Comment by erioshi** [comment]
As noted above I linked the issue I reported to this one as it looks to be related.

Unfortunately in my case, using http along with a PAT also returned the same failure.

I have not set up SSH access into the GitBucket container yet, but would prefer to avoid this as I already use ansible / ssh to manage the underlying docker host and containers.

**Comment by manuel-held** [comment]
Same here, 

i've also tried to workaround with setting GIT_TERMINAL_PROMPT: 0 in the docker-compose environment - but this does not helped.

**Comment by fiftin** [comment]
Duplicate https://github.com/ansible-semaphore/semaphore/issues/1025
