### ISSUE TITLE
panic: type must be ssh

### ISSUE THREAD

**Issue by Driaan** [ansible-semaphore/semaphore#873]
Executing docker semaphore latest. Tried with setting user/password or ssh key in key store against the static inventory. 

> semaphore_1  | .MySQL semaphore@mysql:3306 semaphore
semaphore_1  | Tmp Path (projects home) /tmp/semaphore
semaphore_1  | Semaphore v2.8.43
semaphore_1  | Interface
semaphore_1  | Port :3000
semaphore_1  | Server is running
semaphore_1  | time="2022-02-23T13:14:38Z" level=info msg="Task 8 added to queue"
semaphore_1  | time="2022-02-23T13:14:38Z" level=info msg="Set resource locker with TaskRunner 8"
semaphore_1  | time="2022-02-23T13:14:39Z" level=info msg="Stopped preparing TaskRunner 8"
semaphore_1  | time="2022-02-23T13:14:39Z" level=info msg="Release resource locker with TaskRunner 8"
semaphore_1  | panic: type must be ssh
semaphore_1  |
semaphore_1  | goroutine 97 [running]:
semaphore_1  | github.com/ansible-semaphore/semaphore/db.AccessKey.GetSshCommand(0x1, 0xc00058b060, 0x19, 0xc001891e78, 0x3, 0xc001891e80, 0xc0018a4050, 0x0, 0x0, 0x0, ...)
semaphore_1  |  /go/src/github.com/ansible-semaphore/semaphore/db/AccessKey.go:157 +0x1de
semaphore_1  | github.com/ansible-semaphore/semaphore/lib.AnsiblePlaybook.makeCmd(0x1, 0x18b0190, 0xc0017fa000, 0x1, 0xc001891c40, 0xb, 0x1, 0xc0007dbac0, 0x3c, 0xc001891c50, ...)
semaphore_1  |  /go/src/github.com/ansible-semaphore/semaphore/lib/AnsiblePlaybook.go:25 +0x145
semaphore_1  | github.com/ansible-semaphore/semaphore/lib.AnsiblePlaybook.GetHosts(0x1, 0x18b0190, 0xc0017fa000, 0x1, 0xc001891c40, 0xb, 0x1, 0xc0007dbac0, 0x3c, 0xc001891c50, ...)
semaphore_1  |  /go/src/github.com/ansible-semaphore/semaphore/lib/AnsiblePlaybook.go:37 +0xd6
semaphore_1  | github.com/ansible-semaphore/semaphore/services/tasks.(*TaskRunner).listPlaybookHosts(0xc0017fa000, 0x0, 0x0)
semaphore_1  |  /go/src/github.com/ansible-semaphore/semaphore/services/tasks/runner.go:567 +0x150
semaphore_1  | github.com/ansible-semaphore/semaphore/services/tasks.(*TaskRunner).prepareRun(0xc0017fa000)
semaphore_1  |  /go/src/github.com/ansible-semaphore/semaphore/services/tasks/runner.go:257 +0x5e5
semaphore_1  | created by github.com/ansible-semaphore/semaphore/services/tasks.(*TaskPool).Run
semaphore_1  |  /go/src/github.com/ansible-semaphore/semaphore/services/tasks/pool.go:153 +0x6a5

**Comment by fiftin** [comment]
Problem solved?

**Comment by Driaan** [comment]
No but its probably environmental.. when I ran the docker equivalent it was fine so I'm just doing that
