### ISSUE TITLE
missing docs

### ISSUE THREAD

**Issue by tiny-pangolin** [ansible-semaphore/semaphore#879]
I was trying to find the repo for documentation so I could submit a pull request but couldn't I find it. I was wondering if the repo for docs.ansible-semaphore.com could be made public for pull requests.

**Comment by fiftin** [comment]
It is public,

https://github.com/fiftin/ansible-semaphore-docs

I will update README to reference this repo.

**Comment by nook24** [comment]
Would be good to move this under the ansible-semaphore orga on GitHub. I had to search for the docs as well.

**Comment by fiftin** [comment]
I have no access to ansible-semaphore organisation. I have access only to semaphore repo.

**Comment by steadfasterX** [comment]
my main prob is that the docs are simply empty, e.g. "environment", inventory, repositories are all empty. currently was trying to find out what the meaning of environment is..
