### ISSUE TITLE
LDAP duplicate entry issue Semaphore v2.8.53

### ISSUE THREAD

**Issue by ElvisATF** [ansible-semaphore/semaphore#898]
I am getting an issue with Semaphore v2.8.53
LDAP is integrated, on first login user is getting logged-in successfully. After log-out it cannot login anymore. It gives me the  following error:
INFO[0033] User with email authorized via LDAP correctly
2022/03/21 14:25:23 http: panic serving 10.128.194.237:56434: Error 1062: Duplicate entry " '' for key 'user.username'
goroutine 50 [running]:

Can someone help if there is a solution.

**Comment by fiftin** [comment]
I can try to help

**Comment by sohailasghar688** [comment]
Issue is resolved by using following LDAP mappings:

       "ldap_mappings": {
                "dn": "dn",
                "mail": "mail",
                "uid": "uid",
                "cn": "cn"
        },

**Comment by pao-pirka** [comment]
> Issue is resolved by using following LDAP mappings:
> 
> ```
>    "ldap_mappings": {
>             "dn": "dn",
>             "mail": "mail",
>             "uid": "uid",
>             "cn": "cn"
>     },
> ```

I configured my config.json like this, sadly did not help. Any further ideas on this?

**Comment by sohailasghar688** [comment]
@pao-pirka can you share your other ldap configuration fields as well to have a look?

**Comment by pao-pirka** [comment]
> @pao-pirka can you share your other ldap configuration fields as well to have a look?


I hope that helps, if not please give me a heads up! 



[...]
       },[...]
	"ldap_binddn": "CN=yyy,OU=yxy,OU=xxyy,OU=yxy,OU=xxyyx,OU=yyyy,DC=yxyxy,DC=xyxyxy,DC=xr",
        "ldap_bindpassword": "password",
        "ldap_server": "abc:389",
        "ldap_searchdn": "OU=xx,OU=xy,DC=xyx,DC=xyx,DC=xr",
        "ldap_searchfilter": "(uid=%s)",
        "ldap_mappings": {
                "dn": "dn",
                "mail": "mail",
                "uid": "uid",
                "cn": "cn"
        },
        "telegram_chat": "",
        "telegram_token": "",
        "max_parallel_tasks": 2,
        "email_alert": false,
        "email_secure": false,
        "telegram_alert": false,
        "ldap_enable": true,
        "ldap_needtls": false,
        "ssh_config_path": "",
        "demo_mode": false
 }

**Comment by sohailasghar688** [comment]
@pao-pirka I dont find anything odd in configurations, just a confirmation that you are not using tls with ldap?

What was the default admin user you had at Semaphore configurations? Make sure to have a complete email ID as admin user not something e.g. admin
