### ISSUE TITLE
Clarify v2 MySQL version requirement

### ISSUE THREAD

**Issue by athak** [ansible-semaphore/semaphore#90]
Hi,
Migration 1.1.0 of v2, changes a datetime field to precision 6. According the MySQL docs, fractional seconds were added in 5.6.4:

> MySQL 5.6.4 and up expands fractional seconds support for TIME, DATETIME, and TIMESTAMP values, with up to microseconds (6 digits) precision

It would be great to clarify that MySQL 5.6.4 or later is required since many linux distros ship with older versions.

Cheers,
Atha

**Comment by matejkramny** [comment]
Hmm I see. What about MariaDB?

**Comment by matejkramny** [comment]
Unless we alter the migrations the requirement will be that users have MySQL 5.6.4 or greater or MariaDB 5.3 or greater.

I will toy with a file-db like InnoDB and see if that can be used as a fallback.

**Comment by matejkramny** [comment]
Im a bit tired, innodb isn't what I intended to say.

I meant sqlite..

**Comment by athak** [comment]
You are correct, millisecond precision has been supported in MariaDB since 5.3. The earliest release available however is 5.5.

For sqlite, I don't think that syntax will work. To achieve millisecond resolution, something like this apparently is necessary: http://stackoverflow.com/questions/17574784/sqlite-current-timestamp-with-milliseconds.

**Comment by matejkramny** [comment]
Hmm right, maybe it should be stored as a blob or something. Perhaps bigint which is ms duration from start of the task.
