### ISSUE TITLE
Posibility for more survey types in task templates

### ISSUE THREAD

**Issue by Cronick** [ansible-semaphore/semaphore#900]
Hi.

Is there a posibility to add more survey types like Ansible AWX?

> Textarea: A multi-line text field.
> Password: Responses are treated as sensitive information, much like an actual password is treated.
> Multiple Choice (single select): A list of options, of which only one can be selected at a time. Enter the options, one per line, in the Multiple Choice Options box.
> Multiple Choice (multiple select): A list of options, any number of which can be selected at a time. Enter the options, one per line, in the Multiple Choice Options box.
> Float: A decimal number.

**Comment by ySp-chld** [comment]
#904 and #986  are referencing the same thing, I think that would be a very nice feature to have indeed.

**Comment by fiftin** [comment]
Duplicate https://github.com/ansible-semaphore/semaphore/issues/904
