### ISSUE TITLE
[feature request] Add git repository as inventory type

### ISSUE THREAD

**Issue by ziouf** [ansible-semaphore/semaphore#902]
This may allow to manage source code of dynamic inventory scripts

This feature would require to set spécific fields in the UI : 
- git repository (choice among project's repositories)
- file path (free text to set the path of the inventory file from git repository root)

Every job using this inventory will trigger git pull as first runtime step.

Does it make sens for you ? 
Thank you

**Comment by ziouf** [comment]
Another need, which is linked to this one would be: 

- allow usage of dynamic inventory scripts

I tryied to setup python script as "file" type, but it's not invoked and produces the following error :

``` 
3:52:21 PM [WARNING]: Unable to parse /tmp/dynamic-inventory.py as an inventory source
3:52:21 PM [WARNING]: No inventory was parsed, only implicit localhost is available
3:52:21 PM [WARNING]: provided hosts list is empty, only localhost is available. Note that
3:52:21 PM the implicit localhost does not match 'all'
```

But locally this invocation works

```
ansible all -i dynamic-inventory.py -m ping
```

**Comment by zorrobiwan** [comment]
+1

**Comment by Alethio36** [comment]
i hate to bump this, but is there any response on when/if this can become a reality?

*edit: typo

**Comment by nobilisgkill4** [comment]
+1

In addition: This would also make sense to have the option for "enviroment" as well due to the fact that both parts are traditionaly part on an ansible project.

**Comment by zorrobiwan** [comment]
Already possible in a certain way : https://github.com/ansible-semaphore/semaphore/discussions/1071

**Comment by pwannenmacher** [comment]
Will there be an option to select a Git repo as an investoy in the UI in the near future?

**Comment by geelenbert** [comment]
+1

would realy like the github inventory feature

**Comment by fiftin** [comment]
Implemented: https://github.com/semaphoreui/semaphore/releases/tag/v2.9.100-beta
