### ISSUE TITLE
Survey Variables

### ISSUE THREAD

**Issue by jhaesselbacher** [ansible-semaphore/semaphore#904]
For Survey Variables when editing a template, it is possible to provide a Type multiple choice list for string or integer ?
Multiple choice options with a single selection  for the variable ?
it is also possible to provide a minimum and maximum number of characters when user entering the string ?
it is also possible to provide for entering a password type variable for which the characters will be masked ?

**Comment by Twim4** [comment]
Would be interested in that too. To have more types of surveys

**Comment by AndrewSav** [comment]
Yep, I would also like to indicate that this is the top feature on my list missing. Static surveys would be an improvement, but dynamic surveys, a-la rundeck would be ideal.

**Comment by fiftin** [comment]
> Yep, I would also like to indicate that this is the top feature on my list missing. Static surveys would be an improvement, but dynamic surveys, a-la rundeck would be ideal.

What is dynamic surveys? I didn't use Rundeck.

**Comment by AndrewSav** [comment]
@fiftin Something like [this](https://docs.rundeck.com/docs/manual/job-options.html#remote-option-values) and [this](https://docs.rundeck.com/docs/manual/job-options.html#option-model-provider) The entire page is actually relevant as a primer what a more advanced survey interface can achieve. Also "Cascading Remote Options" section a bit further down is of a particular interest to me.

In short, you can fetch options and their possible value from remote URLs and you can have selection of options/answers depending on the values entered by the user for other options.

**Comment by Sohn123** [comment]
A static multiple choice option would be really great.

**Comment by ySp-chld** [comment]
This issue seems to have a lot of traction and several people liked to have some better survey variable see #1157
Also i'd add maybe if variable is empty having a default value would be great.

**Comment by SupremeGit** [comment]
Until survey variables are improved,, Semaphore is nothing but a useless annoying toy, and a waste of time for anyone attempting to use if for anything useful.

Survey variables are currently so useless and inflexible, it is a disgrace. You don't even have a boolean type FFS.

Why is this request being ignored?

**Comment by AndrewSav** [comment]
@SupremeGit, first of all no one owes you anything here, if you chose to waste your time attempting to use something you cannot use, this is on you. You are receiving free software with no obligations whatsoever, take it or leave it.

With this out of the way, if you care about a feature you are interested in being added at all coming here and insulting the very people who can make it happen is counterproductive. Do you think they will read what you wrote and think: "Jeez, this guy is so right we totally suck, we need to drop everything right now and work on this as a first priority, to redeem somewhat the fact that our software is completely useless!"? I can assure you this is not going to happen.

> Why is this request being ignored?

That's really simple. It is an open source project, where things are getting done by people contributing their time to move it forward. No one has chosen to contribute their time towards this feature so far, this is why it has not been done yet.

**Comment by ianpogi5** [comment]
anyone working on this?

**Comment by sparsick** [comment]
Hi, 

I create a PR #1598  for the use case "hiding passwords"

**Comment by fiftin** [comment]
Done
