### ISSUE TITLE
Local Repository "Failed to checkout repository"

### ISSUE THREAD

**Issue by magichome** [ansible-semaphore/semaphore#907]
I have a cloned git playbook repository defined in Semaphore with a file:// URL.  The repository resides locally on the Semaphore server.

When I try to run a playbook I get the error below...

```
7:24:42 PM
Task 7 added to queue
7:24:45 PM
Preparing: 7
7:24:45 PM
Prepare TaskRunner with template: Endpoint
7:24:45 PM
Failed to checkout repository to required commit: stat /tmp/semaphore/repository_1_1: no such file or directory
7:24:45 PM
Prepare TaskRunner with template: Endpoint
7:24:45 PM
Failed to checkout repository to required commit: stat /tmp/semaphore/repository_1_1: no such file or directory
```

The '/tmp/semaphore/repository_1_1' directory does not in fact exist but since it gets deleted when I do create it (for debugging), I presume Semaphore is managing it.

Any help appreciated.

**Comment by fiftin** [comment]
Hi @magichome ,

It is known issue. It was fixed in `develop` branch. It will be in next release soon.

**Comment by magichome** [comment]
Thanks
