### ISSUE TITLE
Unable to log twice using LDAP

### ISSUE THREAD

**Issue by jlebleu** [ansible-semaphore/semaphore#915]
Seems to be duplicate of #801 but it may not :)

1 When logging into ansible semaphore with a LDAP account it properly logs in with the correct user.
2 Log out
3 Attempt to login again and it results in a unique constraint violation for user_username_key

2022/04/19 16:54:53 http: panic serving 10.169.112.151:51501: pq: duplicate key value violates unique constraint "user_username_key"

All my users usersid are stored in capital letter in lDAP but when you log into semaphore the username is converted in lowercase 👍 

login.go
```go
...
login.Auth = strings.ToLower(login.Auth) 
...
```
But user is stored using LDAP original username (could be in uppercase)

So when after login we try fo find the user in database, user is not found, and semaphore try to recreate the same user => duplicate key.

I suggest to lower the username coming from ldap (Not tested yet) : 

```diff
diff --git a/api/login.go b/api/login.go
index 16bcc17..115dcb6 100644
--- a/api/login.go
+++ b/api/login.go
@@ -84,7 +84,7 @@ func tryFindLDAPUser(username, password string) (*db.User, error) {
        }

        ldapUser := db.User{
-               Username: sr.Entries[0].GetAttributeValue(util.Config.LdapMappings.UID),
+               Username: strings.ToLower((sr.Entries[0].GetAttributeValue(util.Config.LdapMappings.UID)),
                Created:  time.Now(),
                Name:     sr.Entries[0].GetAttributeValue(util.Config.LdapMappings.CN),
                Email:    sr.Entries[0].GetAttributeValue(util.Config.LdapMappings.Mail),
```

**Comment by fiftin** [comment]
Hi @jlebleu,

Thank you! Could you create PR? I will merge it immediately.

**Comment by jlebleu** [comment]
@fiftin Hello did the merge request, took a bit of time as I had to setup a go dev environment to be able to test my patch :)
Thanks for your help

**Comment by jlebleu** [comment]
I have rebuilded the docker image and tested, seems to be ok, you may  close this issue i think
