### ISSUE TITLE
how to create a vault password so it can be selected in templates?

### ISSUE THREAD

**Issue by steadfasterX** [ansible-semaphore/semaphore#919]
well maybe its me being stupid again but how to fill the vault selection dropdown in a template?

I ref to this: 
![](https://user-images.githubusercontent.com/914224/133695053-41983d96-518a-449e-bd87-80e628c8733e.png) (mentioned [here](https://github.com/ansible-semaphore/semaphore/issues/113#issuecomment-921310222))

I saw ppl writing db entries manually but that can't be the right process.. or? for me it says just "no data available" and I cannot add a new key in keystore with type "vault" or similar. what do I miss?

**Comment by wdsff1** [comment]
hi,

use keystore > new key > type="login with password"
![save](https://user-images.githubusercontent.com/92681375/167261784-fa2c2c81-f26c-4f3f-b61d-da978f63ccc7.jpg)

**Comment by steadfasterX** [comment]
Thx! Would be great having that in the documentation..

**Comment by luca-motterle-ICE** [comment]
How do I refer to that password in the playbook?

**Comment by fiftin** [comment]
@lucmot 

You can't, it used in `ansible-playbook` with flag `--vault-password-file`.

What purpose to use it in playbook? Please provide use cases, perhaps we will implement it. Thank you.

**Comment by frank-cini-oc** [comment]
> @lucmot
> 
> You can't, it used in `ansible-playbook` with flag `--vault-password-file`.
> 
> What purpose to use it in playbook? Please provide use cases, perhaps we will implement it. Thank you.

@lucmot , I have a use case where I have a bootstrap project.  In this project, one could  generate/regenerate secrets and add them to the vault, so they would need to see the password from within the playbook.

In a separate project where the vault is read (but never written to), then those playbooks would only used via the --vault-password-file as you described above.

Perhaps there is a better pattern also.

**Comment by s-juozaitis** [comment]
> @lucmot
> 
> You can't, it used in `ansible-playbook` with flag `--vault-password-file`.
> 
> What purpose to use it in playbook? Please provide use cases, perhaps we will implement it. Thank you.


Hi @fiftin 

The use case is: 
I'm trying to create playbook which will be used to deploy required packages and configuration to newly build VM  
In the template I want to create service account with password:

    - name: Set password for service_account
      shell: |
        echo "{{ service_account_password }}" | passwd --stdin service_account
      vars:
        service_account_password: !vault |
            $ANSIBLE_VAULT;1.1;AES256
            65343338353763303864393566323639646433633263653765383631663562326463333939623139
            6261653762646635373830653832373365663634343035390a373937306261323537643937663065
            61393034373066646233393734623635633233343435393763656232653666383963313035666665
            6132393433306266350a343262376333623165393934323363613461356263343261393363636435
            3232
            
Any advice how to achieve this?

**Comment by grulicht** [comment]
I have this same problem in ansible semaphore with vault like @s-juozaitis. All configuration for vault password and tesks etc. is good, but still if playbook run failed and say:
"msg": "Decryption failed (no vault secrets were found that could decrypt)".

Please some solutions??
Thanks.

**Comment by dbethke** [comment]
I'm getting this msg too
