### ISSUE TITLE
Error when adding project

### ISSUE THREAD

**Issue by hernandesbsousa** [ansible-semaphore/semaphore#92]
Hi there,

I'm running [v2.0](https://github.com/ansible-semaphore/semaphore/releases/tag/v2.0) on OSX. I have succeed at the initial db and project setup however, when I try to add a new project, I get an error: `Error 1364: Field 'created' doesn't have a default value`.

Am I doing something wrong?

**Comment by matejkramny** [comment]
Hmm no I don't think so.. This is mysql complaining the SQL schema isn't 'properly written'.

Could you tell us your mysql version?
Have you modified the configuration of mysql?

I feel that turning off strict mode would help, but this is an issue that needs to be addressed (it was in the past, probably not completely).

**Comment by dsmorse** [comment]
my mysql was 100% new
  docker run -d --name=mysql -p 127.0.0.1:3306:3306 -e MYSQL_DATABASE=semaphore -e MYSQL_ALLOW_EMPTY_PASSWORD=true mysql

**Comment by matejkramny** [comment]
I found what's causing this issue and working on a fix.

Turns out there are small differences from my local dev db to what was in
the sql migrations.
On Fri, 20 May 2016 at 8:58 pm, David S Morse <notifications@github.com>
wrote:

> my mysql was 100% new
> docker run -d --name=mysql -p 127.0.0.1:3306:3306 -e
> MYSQL_DATABASE=semaphore -e MYSQL_ALLOW_EMPTY_PASSWORD=true mysql
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/ansible-semaphore/semaphore/issues/92#issuecomment-220704023>
>
-- 
Matej Kramny
