### ISSUE TITLE
How to access the demo?

### ISSUE THREAD

**Issue by dberardo-com** [ansible-semaphore/semaphore#929]
What are the credentials for accessing the demo instance? I really didnt manage to find them, is it on purpose?

**Comment by jcmdln** [comment]
Visiting https://demo.ansible-semaphore.com implicitly treats you as a test user with read-only access, though you can explore the UI and run tasks. If you're looking to test Semaphore beyond these limitations I think you may need to consider deploying it yourself.

**Comment by dberardo-com** [comment]
when i access the demo site the page asked me to log in but i have no credentials for it.

Now it seems to work again, so probably there was a bug a couple of days ago?
