### ISSUE TITLE
Document customizing the Semaphore container(s)

### ISSUE THREAD

**Issue by jcmdln** [ansible-semaphore/semaphore#933]
For my use of Semaphore, I need netaddr installed for several playbooks but it's missing in the official container images. Looking around I saw some building totally new images, though should Semaphore briefly document how to easily customize the official image? I'd like to discuss the value and framing of providing something like the following example of adding py3-netaddr:

```Dockerfile
FROM ansiblesemaphore/semaphore

# Set user to 'root'
USER root

# Install additional system dependencies
RUN apk --no-cache add py3-netaddr

# Set user back to 'semaphore'
USER semaphore
```

**Comment by dgibbs64** [comment]
I also need netaddr installed in the docker container. I think it would be worth just getting it added in to the official image

**Comment by Apollo3zehn** [comment]
I would like to have rsync installed to be able to use the `ansible.posix.synchronize` task. For now I am installing it manually using `sudo podman exec -it -u root semaphore apk add rsync` which is fine for now.

But my first approach was to create a play which does the installation of that package. However, no `sudo` or `doas` is available in the container so I could not get sudo permissions to install the package.
