### ISSUE TITLE
Trying to login after login out fails in Safari

### ISSUE THREAD

**Issue by PeterFalken** [ansible-semaphore/semaphore#941]
After login out of a semaphore session on the web using Safari - shows an error page (401 Unauthorized)
- User is not redirected to the login page.
- Quitting the browser and trying to login again within a short period also redirects to the error page.
![semaphore](https://user-images.githubusercontent.com/2557898/169630729-618b9b3a-34c6-426b-b0b4-1f3ce1441ab5.png)

**Comment by rbnhln** [comment]
Same problem here. Using Safari Version 17.2.1 (19617.1.17.11.12) under MacOS 14.2.1 (23C71) Sonoma on a M1 MacBook Pro.

**Comment by PeterFalken** [comment]
Yes, not sure what is causing it.
In my case the connection is established with `http` (instead of `https`) as it is on the internal network on kubernetes pod.

**Comment by PeterFalken** [comment]
It seems that this might be related to #1587.

**Comment by PeterFalken** [comment]
Fixed on 2.11.1
Thank you @fiftin
