### ISSUE TITLE
Ldap: already encrypted

### ISSUE THREAD

**Issue by luca-motterle-ICE** [ansible-semaphore/semaphore#947]
First of all thanks for the nice tool. 
I'm trying to integrate the interface with AD however when I log in I can see the error:

INFO[0011] LDAP Result Code 200 "Network Error": ldap: already encrypted

The config file look like: 
        "ldap_binddn": "cn=svcLinuxServers,ou=ServiceAccounts,ou=ICE,dc=ice,dc=loc",
        "ldap_bindpassword": "password",
        "ldap_server": "FQDN:636",
        "ldap_searchdn": "ou=Users,dc=domain,dc=loc",
        "ldap_searchfilter": "(&(objectCategory=Person)(sAMAccountName=%s))",
        "ldap_mappings": {
                "dn": "dn",
                "mail": "mail",
                "uid": "uid",
                "cn": "cn"
        },
        "ldap_enable": true,
        "ldap_needtls": true,

Is it possible to increase the debug level to understand better the error?

Thanks

**Comment by fiftin** [comment]
What version of Semaphore do you use?

**Comment by luca-motterle-ICE** [comment]
Hi Denis,
                I have version v2.8.49.

***@***.*** semaphore]# ./semaphore version
v2.8.49


Luca


From: Denis Gukov ***@***.***>
Date: Friday, 10. June 2022 at 14:35
To: ansible-semaphore/semaphore ***@***.***>
Cc: Luca Motterle ***@***.***>, Author ***@***.***>
Subject: Re: [ansible-semaphore/semaphore] Ldap: already encrypted (Issue #947)
CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe and secure.


What version of Semaphore do you use?

—
Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fansible-semaphore%2Fsemaphore%2Fissues%2F947%23issuecomment-1152312248&data=05%7C01%7Cluca.motterle%40iceservices.com%7C9e3f6bedace945e8bc0d08da4addacef%7C14eafca971f443c69551d5e8fa8d6007%7C0%7C0%7C637904613208459209%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=rbwaes%2F8tnfrod58cYliQ3e%2FIDOPJw3ZaGvbIf49vy4%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FARL4SXPXMC4AHP4N5FR7X3DVOMZAJANCNFSM5XDXGQUQ&data=05%7C01%7Cluca.motterle%40iceservices.com%7C9e3f6bedace945e8bc0d08da4addacef%7C14eafca971f443c69551d5e8fa8d6007%7C0%7C0%7C637904613208459209%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=2Vk0OqoaMhQEmQe1uh45ZE6yhv15nOirpKpI846Ega8%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

Disclaimer: This e-mail from ICE and any attachments enclosed hereto may contain information which is confidential, privileged and exempt from disclosure under applicable law.

**Comment by fiftin** [comment]
Please try to update to v2.8.53

**Comment by luca-motterle-ICE** [comment]
Hi,
                I updated the binary. Now I see more information in the console when I try to log in:

INFO[0089] User Luca Motterle with email ***@***.*** authorized via LDAP correctly
2022/06/10 16:07:37 http: panic serving 10.10.9.145:55021: Error 1062: Duplicate entry ***@***.***' for key 'user.email'
goroutine 137 [running]:
net/http.(*conn).serve.func1(0xc0000b4d20)
                /usr/local/go/src/net/http/server.go:1805 +0x153
panic(0x9bb480, 0xc0011852d8)
                /usr/local/go/src/runtime/panic.go:971 +0x499
github.com/ansible-semaphore/semaphore/api.login(0x18b9240, 0xc0007aee00, 0xc0003fb400)
                /go/src/github.com/ansible-semaphore/semaphore/api/login.go:171 +0x7b4
net/http.HandlerFunc.ServeHTTP(0x1828690, 0x18b9240, 0xc0007aee00, 0xc0003fb400)
                /usr/local/go/src/net/http/server.go:2050 +0x44
github.com/ansible-semaphore/semaphore/api.JSONMiddleware.func1(0x18b9240, 0xc0007aee00, 0xc0003fb400)
                /go/src/github.com/ansible-semaphore/semaphore/api/router.go:23 +0x131
net/http.HandlerFunc.ServeHTTP(0xc0005d3770, 0x18b9240, 0xc0007aee00, 0xc0003fb400)
                /usr/local/go/src/net/http/server.go:2050 +0x44
github.com/ansible-semaphore/semaphore/cli/cmd.runService.func1.1(0x18b9240, 0xc0007aee00, 0xc0003fb400)
                /go/src/github.com/ansible-semaphore/semaphore/cli/cmd/root.go:81 +0x182
net/http.HandlerFunc.ServeHTTP(0xc00023ed00, 0x18b9240, 0xc0007aee00, 0xc0003fb400)
                /usr/local/go/src/net/http/server.go:2050 +0x44
github.com/gorilla/mux.CORSMethodMiddleware.func1.1(0x18b9240, 0xc0007aee00, 0xc0003fb400)
                /go/src/github.com/ansible-semaphore/semaphore/vendor/github.com/gorilla/mux/middleware.go:51 +0xf7
net/http.HandlerFunc.ServeHTTP(0xc000033cc0, 0x18b9240, 0xc0007aee00, 0xc0003fb400)
                /usr/local/go/src/net/http/server.go:2050 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000248000, 0x18b9240, 0xc0007aee00, 0xc0003fb200)
                /go/src/github.com/ansible-semaphore/semaphore/vendor/github.com/gorilla/mux/mux.go:212 +0xd3
github.com/gorilla/handlers.ProxyHeaders.func1(0x18b9240, 0xc0007aee00, 0xc0003fb200)
                /go/src/github.com/ansible-semaphore/semaphore/vendor/github.com/gorilla/handlers/proxy_headers.go:59 +0x114
net/http.HandlerFunc.ServeHTTP(0xc000231140, 0x18b9240, 0xc0007aee00, 0xc0003fb200)
                /usr/local/go/src/net/http/server.go:2050 +0x44
github.com/ansible-semaphore/semaphore/cli/cmd.cropTrailingSlashMiddleware.func1(0x18b9240, 0xc0007aee00, 0xc0003fb200)
                /go/src/github.com/ansible-semaphore/semaphore/cli/cmd/server.go:27 +0x97
net/http.HandlerFunc.ServeHTTP(0xc000231158, 0x18b9240, 0xc0007aee00, 0xc0003fb200)
                /usr/local/go/src/net/http/server.go:2050 +0x44
net/http.serverHandler.ServeHTTP(0xc0002441c0, 0x18b9240, 0xc0007aee00, 0xc0003fb200)
                /usr/local/go/src/net/http/server.go:2868 +0xa3
net/http.(*conn).serve(0xc0000b4d20, 0x18bad60, 0xc00023eb40)
                /usr/local/go/src/net/http/server.go:1933 +0x8cd
created by net/http.(*Server).Serve
                /usr/local/go/src/net/http/server.go:2994 +0x39b

Are you able to point what’s can be the issue from this?

Thanks

Luca

From: Denis Gukov ***@***.***>
Date: Friday, 10. June 2022 at 16:01
To: ansible-semaphore/semaphore ***@***.***>
Cc: Luca Motterle ***@***.***>, Author ***@***.***>
Subject: Re: [ansible-semaphore/semaphore] Ldap: already encrypted (Issue #947)
CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe and secure.


Please try to update to v2.8.53

—
Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fansible-semaphore%2Fsemaphore%2Fissues%2F947%23issuecomment-1152394825&data=05%7C01%7Cluca.motterle%40iceservices.com%7Cbbaa6bd5a1a44dea7b9108da4ae9b1a9%7C14eafca971f443c69551d5e8fa8d6007%7C0%7C0%7C637904664811554083%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=JsFsQ3dikEPuRXfJE%2FvUg8ardI1mJGHjh%2Bxrw%2BebijA%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FARL4SXOE55DHPU3VPZSKRE3VONDC5ANCNFSM5XDXGQUQ&data=05%7C01%7Cluca.motterle%40iceservices.com%7Cbbaa6bd5a1a44dea7b9108da4ae9b1a9%7C14eafca971f443c69551d5e8fa8d6007%7C0%7C0%7C637904664811554083%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=QjX862AXFsArrt7%2FwBlJyAo659jmK4Ne7cVd92p8tUY%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

Disclaimer: This e-mail from ICE and any attachments enclosed hereto may contain information which is confidential, privileged and exempt from disclosure under applicable law.

**Comment by fiftin** [comment]
May it helps: https://github.com/ansible-semaphore/semaphore/issues/808#issuecomment-1076260460

**Comment by luca-motterle-ICE** [comment]
Hi Denis,
                It seems to work no.

INFO[0116] User Luca Motterle with email ***@***.*** authorized via LDAP correctly.

It was not clear to me how to handle users. I created a local user matching the login name of LDAP.

Thanks

Luca

From: Denis Gukov ***@***.***>
Date: Friday, 10. June 2022 at 16:38
To: ansible-semaphore/semaphore ***@***.***>
Cc: Luca Motterle ***@***.***>, Author ***@***.***>
Subject: Re: [ansible-semaphore/semaphore] Ldap: already encrypted (Issue #947)
CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe and secure.


May it helps: #808 (comment)<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fansible-semaphore%2Fsemaphore%2Fissues%2F808%23issuecomment-1076260460&data=05%7C01%7Cluca.motterle%40iceservices.com%7C2dcc48d30f4c4f67aeb708da4aeec68d%7C14eafca971f443c69551d5e8fa8d6007%7C0%7C0%7C637904686844897666%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=SCaJD6JeRlkOVZMeTnrBwMTsK%2B4UNK41RpDMnEsCCKM%3D&reserved=0>

—
Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fansible-semaphore%2Fsemaphore%2Fissues%2F947%23issuecomment-1152431075&data=05%7C01%7Cluca.motterle%40iceservices.com%7C2dcc48d30f4c4f67aeb708da4aeec68d%7C14eafca971f443c69551d5e8fa8d6007%7C0%7C0%7C637904686844897666%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=3kOzQWQnRybQSkH3NdIip3rsTee4DsMZfarVgIydU5o%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FARL4SXMPCANBP6TJWEDAB2TVONHLJANCNFSM5XDXGQUQ&data=05%7C01%7Cluca.motterle%40iceservices.com%7C2dcc48d30f4c4f67aeb708da4aeec68d%7C14eafca971f443c69551d5e8fa8d6007%7C0%7C0%7C637904686844897666%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=oGzHv3QCA2B0zyiMV3O9bxcPEgqpC794PNHIYSIRdIM%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

Disclaimer: This e-mail from ICE and any attachments enclosed hereto may contain information which is confidential, privileged and exempt from disclosure under applicable law.

**Comment by luca-motterle-ICE** [comment]
I think version v2.8.53 solved the issue. Thanks

**Comment by lucmot** [comment]
I said it too early. Even if the info log is positive the interface seems to care only about the local users. Is there some specific configuration to change?
