### ISSUE TITLE
API call to list actual schedules

### ISSUE THREAD

**Issue by cerberek** [ansible-semaphore/semaphore#950]
I miss API call which gives me a list with all configured schedules. Ideally that template json will have schedule_id related with it.

**Comment by kristophercrawford** [comment]
@cerberek - I think I was able to find what you are looking for using curl. 

```
curl --cookie "semaphore=..." "http://ansible.local:3000/api/project/<project id>/templates/<task template id>/schedules"
```

For me, this returned:

```
[{"id":1,"project_id":1,"template_id":4,"cron_format":"0 6 * * 0","repository_id":null}]
```

**Comment by cerberek** [comment]
Great, that call i didn't find in documentation. Thanks

**Comment by kristophercrawford** [comment]
I didn't either, I used inspect element in my browser and navigated to the schedule section of a task to find the url being called.
