### ISSUE TITLE
how to use repository https://

### ISSUE THREAD

**Issue by thanakiat-h** [ansible-semaphore/semaphore#957]
i can't select https// path of respository
![image](https://user-images.githubusercontent.com/105916470/172526375-df40090f-5925-4bb2-9db3-63f28fc090dd.png)

**Comment by anvme** [comment]
> i can't select https// path of respository
> ![image](https://user-images.githubusercontent.com/105916470/172526375-df40090f-5925-4bb2-9db3-63f28fc090dd.png)

What's your version of ansible-semaphore?

**Comment by thanakiat-h** [comment]
I clone repository from [contribute version](https://github.com/ansible-semaphore/semaphore/blob/develop/CONTRIBUTING.md),
 branch develop. I think it is lastest version.

**Comment by fiftin** [comment]
Hi @thanakiat-h ,

Yes, I missed this. Will fix asap.

**Comment by MudraMartin** [comment]
I created pullrequest for this:  #1007 
It is locally tested and it works OK, since backend for HTTPS git pull was already there and only thing missing was the VUE UI elements
![image](https://user-images.githubusercontent.com/5605432/185163529-21e16784-4e50-45b5-830f-91e911c6edf0.png)

**Comment by fiftin** [comment]
Please try v2.8.57. It should work.
