### ISSUE TITLE
Problem with using local repository

### ISSUE THREAD

**Issue by afeefghannam89** [ansible-semaphore/semaphore#968]
Hello,

I am still testing semaphore before deciding to use it in production or not. I am using the latest version v2.8.53. I want to use a local repository on my server, but faced to problems:

01- semaphore does not create the target path to whom he wants to check out the source/local repository.
![Screenshot 2022-06-16 at 11 52 23](https://user-images.githubusercontent.com/39904920/174046093-eab3eb17-a11a-49d5-afc5-219472491a7d.png)

02- I created the path with CLI, then I have rerun the task and faced another failure:
![Screenshot 2022-06-16 at 12 02 20](https://user-images.githubusercontent.com/39904920/174046540-a272fdb6-124f-4362-85a5-3e77e93f3438.png)
 
Here is the config from the local repository:

![Screenshot 2022-06-16 at 12 04 32](https://user-images.githubusercontent.com/39904920/174046996-b5d73673-0435-4120-ac30-459f535eb97f.png)

In addition, why must I set a branch name, when I am using a local repository?

Thanks

**Comment by afeefghannam89** [comment]
@fiftin do you have any idea please?

**Comment by yoanloulchev** [comment]
Hello!

Local repository means local git repository (git is one of the prerequisites for installing Ansible Semaphore).

**Comment by fiftin** [comment]
Please try latest version of Semaphore.
