### ISSUE TITLE
Accessing vault passwords from playbook

### ISSUE THREAD

**Issue by mark4409** [ansible-semaphore/semaphore#972]
Not an issue as such - just clarification needed as I can't find anything in the documentation. Does the key store use ansible vault in the background? And can I reference the keys directly from playbooks?

**Comment by wdsff1** [comment]
Hi,

https://github.com/ansible-semaphore/semaphore/issues/919

**Comment by luca-motterle-ICE** [comment]
#919 explain how to store it in the UI but not how to use it in a playbook. Should be referenced as a variable? Thanks Luca

**Comment by mark4409** [comment]
I'm happy if you can close this - it was down to a lack of knowledge on my part with regards to how Ansible vault works.

**Comment by lucmot** [comment]
Of course. thanks
