### ISSUE TITLE
fix db migration

### ISSUE THREAD

**Issue by ghost** [ansible-semaphore/semaphore#980]
I've built [2.8.65](https://github.com/ansible-semaphore/semaphore/releases/tag/v2.8.65) version, and got
> level=fatal msg="pq: column \"env\" of relation \"project__environment\" contains null values"

to fix it, I've changed [db/sql/migrations/v2.8.57.sql](https://github.com/ansible-semaphore/semaphore/blob/v2.8.65/db/sql/migrations/v2.8.57.sql):
```
diff --git a/db/sql/migrations/v2.8.57.sql b/db/sql/migrations/v2.8.57.sql
index 8bff07a..42c3774 100644
--- a/db/sql/migrations/v2.8.57.sql
+++ b/db/sql/migrations/v2.8.57.sql
@@ -1,4 +1,4 @@
-alter table `project__environment` add column `env` longtext not null;
+alter table `project__environment` add column `env` longtext not null default '';
 alter table `task` add column `hosts_limit` varchar(255) not null default '';
```

**Comment by fiftin** [comment]
@sm-edr thank you! Will fix asap

**Comment by ghost** [comment]
Thanks! Tested. It works fine.

There is `hosts_limit`, it is used to limit on which host(s) it will be run?
It is currently possible only via API, and via CLI args in task, i.e.
```
["-l", "<hostname>" ]
```

There is currently no dedicated option in web UI? as I couldn't find.

**Comment by fiftin** [comment]
@sm-edr 
Yes, for API only. Will add to UI soon.
