### ISSUE TITLE
Change user password fails with syntax error on Postgres 14

### ISSUE THREAD

**Issue by thingnl** [ansible-semaphore/semaphore#994]
Good day.

I am getting my feet wet with semaphore so we hopefully can provide some ansible playbooks to our non-tech-savy users.
I'm running:
 - image: ansiblesemaphore/semaphore:v2.8.53
 - image: postgres:14.4-alpine
On Docker version 20.10.16, build aa7e414
 
If I try to change a user passwod, the gui gives me a: Request failed with status code 400
and on docker show me:
> semaphore-postgres-1   | 2022-07-15 13:17:58.252 UTC [28] ERROR:  syntax error at or near "user" at character 8
> semaphore-postgres-1   | 2022-07-15 13:17:58.252 UTC [28] STATEMENT:  update user set name=$1, username=$2, email=$3, alert=$4, admin=$5, password=$6 where id=$7
> semaphore-semaphore-1  | time="2022-07-15T13:17:58Z" level=error msg="pq: syntax error at or near \"user\""

Creating new and deleting old users is not a problem. It's not a show stopper but I thought someone might want to know.
If more information is needed, happy to provide.

**Comment by scmmmh** [comment]
I can confirm this.

**Comment by flover97** [comment]
same error
debian 11
postgresql 13.7
Semaphore v2.8.53 deb

**Comment by jm4rc05** [comment]
Same error

Docker container `image: ansiblesemaphore/semaphore:latest` created this week

But as a workaround it's possible to remove and `semaphore user add` after

**Comment by fiftin** [comment]
How you did this?
Correct way:

```
semaphore user change-by-login --login user123 --password 123456
```

**Comment by fiftin** [comment]
Looks like issue was fixed. Please try v2.8.66
